### ISSUE TITLE
Convert model interface to concrete implementation in API

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#100]
Otherwise the serializer won't work with attributes.

**Comment by amulware** [comment]
It might be enough to add constructors to all models that take their own interface and set all their properties and then calling it like this before serialisation:

```
var apiTag = tag as Tag ?? new Tag(tag);
```

tag tag.

Also it would be cool if we could somehow check that we aren't missing this conversion anywhere (by checking in the serialiser that we are serialising a concrete class, not an interface? Alternatively, we can cover this in unit tests. Opinions welcome).

**Comment by willsb** [comment]
👍 for covering it all in unit tests.

**Comment by amulware** [comment]
If possible, we should generate the constructors for the models, instead of writing them manually.

**Comment by willsb** [comment]
We are already doing it! Jus approve #104 to see :D
