### ISSUE TITLE
Outdated App UI

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1005]
Design: https://zpl.io/VxYdoRa

<img width="350" alt="screen shot 2017-11-21 at 16 50 02" src="https://user-images.githubusercontent.com/3987892/33082026-0fc4a6be-cedc-11e7-8dcd-bbe3b41f48cb.png">

- [ ] show this overlay when we receive 410 or 418 codes from the api
- [ ] if the user restarts the app, this overlay still has to be visible, and no sync may be triggered
- [ ] if the user restarts the app after updating it, the overlay will no longer be shown, and sync is triggered

**Comment by amulware** [comment]
@pe0ny please confirm:

- the update button leads to the app store page of the app?
- the link leads to http://toggl.com ?

**Comment by pe0ny** [comment]
@amulware yes 👍
