### ISSUE TITLE
Add validation to password length during sign up

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#1021]
Follow up #1018, we need to disable sign up while the password is too short and clear the error message after the length is big enough. 

This needs further clarification from @pe0ny

**Comment by pe0ny** [comment]
@willsb Can you clarify which one do you mean - sign up or log in? (since the name says 'sign up' and description 'log in')

**Comment by willsb** [comment]
Sign up

**Comment by pe0ny** [comment]
Approved from my side:

- [ ] Show 'Password should be at least 6 characters.' until user has entered a password that is at least 6 char. Disable 'Next' button (opacity 50%)
- [ ] When user can entered a password that is at least 6 char, remove 'Password should be at least 6 characters.' and show checkmark on the right. Enable and change 'Next' opacity to 100%

![toggl - ios - sign up step2 1x](https://user-images.githubusercontent.com/5064445/33213627-03ab69b0-d131-11e7-8e5b-a2e709a6e821.png) ![toggl - ios - sign up step2 confirmed 1x](https://user-images.githubusercontent.com/5064445/33213628-063a4106-d131-11e7-8c5e-9e2f49ba28c4.png)

**Comment by willsb** [comment]
What about the "View password" button? I think it add much more value than this checkmark (after all, the error disappearing and the next being enabled should be enough evidence that the password is valid).

**Comment by pe0ny** [comment]
I need coffee or something stronger...

**Comment by simonrozsival** [comment]
And when user deletes some of the characters and it goes back to < 6, it should re-appear?

What happens when the API call fails and the error message is shown in the label and user changes the Password field - should the message appear again?

**Comment by pe0ny** [comment]
> And when user deletes some of the characters and it goes back to < 6, it should re-appear?
yes

> What happens when the API call fails and the error message is shown in the label and user changes the Password field - should the message appear again?
you mean when user taps 'next' and then api call fails > we say 'Sorry, we’re having trouble signing you up. Please try again.' > and then user deletes some char > then yes, we show again 'password should be longer...'

**Comment by willsb** [comment]
While at it, please try and check #1117
