### ISSUE TITLE
Start/stop button freezes app intermittently 

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1025]
No steps to reproduce so far, but the user reports that sometimes after using the app for a while, the start/stop button causes the app to freeze, and they have to restart to get it usable again.

There must either be something that happens randomly/rarely, or something that happens after using the app for some time.

**Comment by robincooper** [comment]
App freezes when stopping a timer.   Need to restart app in order to communicate the stop to other devices.  iOS version 11.2, ipad pro.

**Comment by amulware** [comment]
@robincooper Thanks for the report. Does this happen every single time you stop the timer? Or is there some specific pattern?

Does this maybe happen right after you open the app? Or does it also crash always/sometimes when you've had the app open for 10-20 or more seconds?

**Comment by robincooper** [comment]
@amulware Thanks for replying.  I downloaded the new version of the app yesterday from the app store and have since used it twice on my ipad.  Both times it froze when I stopped the timer after over 1.5 hours.

**Comment by amulware** [comment]
@robincooper We've had another update (version 1.1) in the meantime that should address this problem. Could you update the app and confirm if it's now fine for you, or if the problem still exists?

**Comment by amulware** [comment]
I'm closing this until there are further reports, believing it to be fixed in 1.1
