### ISSUE TITLE
Remove search from Workspaces view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1028]
Remove search from Workspaces view when creating a new project. It's not needed since users usually have only 1-2 workspaces which don't need search.

Zeplin: https://zpl.io/bzwqAWG

**Comment by willsb** [comment]
Will we need to reenable typing once the user is allowed to create a namespace?

Because I can either completely remove this field from code or just hide it until we need again, based on your answer

**Comment by pe0ny** [comment]
Let's hide it for now.
