### ISSUE TITLE
Indicate selected workspace in Workspaces view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1029]
Use green checkmark (like with tags, but only one option can be selected) to indicate selected workspace in Workspaces view when creating a new project.

Zeplin: https://zpl.io/bzwqAWG

**Comment by simonrozsival** [comment]
I believe it already works like this: http://prntscr.com/hep8za

Did you see a screen without the green mark?

**Comment by pe0ny** [comment]
I have the latest TF build and there isn't any checkmark :/

**Comment by pe0ny** [comment]
Yes, it's working now. 👍 Issue can be closed.
