### ISSUE TITLE
TE creation view: no projects

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1031]
- [ ] Show this when user taps @ or project icon below and doesn't have any project
- [ ] When user starts typing, show '+ Create project "new-project-name"', and keep the empty state text visible as well

Zeplin: https://zpl.io/V0PpoEE & https://zpl.io/aXK84xM

![toggl - ios - add new entry first project 1x](https://user-images.githubusercontent.com/5064445/33311888-e32b8ba6-d42e-11e7-9033-261bcff444f0.png) ![toggl - ios - add new entry first project v2 1x](https://user-images.githubusercontent.com/5064445/33311892-e4a13080-d42e-11e7-9cf5-8d11d94476e0.png)

**Comment by simonrozsival** [comment]
Most of the implementation is in the PR #1215, so we should wait until it is merged.
