### ISSUE TITLE
TE creation view: no tags

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1032]
- [ ] Show this when user taps # or tags icon below and doesn't have any tag
- [ ] When user starts typing, show '+ Create a tag "new-tag-name"', and keep the empty state text visible as well

Zeplin: https://zpl.io/2y1P3eo & https://zpl.io/VKE8lX8

![toggl - ios - add new entry first tag 1x](https://user-images.githubusercontent.com/5064445/33312165-bd9b9d1c-d42f-11e7-8d83-cbc5830d7589.png) ![toggl - ios - add new entry first tag v2 1x](https://user-images.githubusercontent.com/5064445/33312169-bf337276-d42f-11e7-84ca-3a2fe62ece29.png)

**Comment by amulware** [comment]
@pe0ny How does this work? What happens if the user taps the 'create a tag' thing? According to #820 there is no additional screen for tag creation, it happens in place, and can thus only work if the user has typed in something behind the '#'.

**Comment by pe0ny** [comment]
☝️ Good points above. Both tags and projects empty states were changed in TE creation flow.

**Comment by willsb** [comment]
Bro-tip: Make this guy a cell and use the DataSource to display it accordingly. Much simpler than messing around with visibility bindings
