### ISSUE TITLE
Implement endpoint to fetch unknown projects

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1036]
This will be necessary to show archived projects in our reports (see #970).

We may also want to use this to show archived projects in the log, but that will be more difficult to get right.

There should be an endpoint to request several projects by id. More info soon.

**Comment by amulware** [comment]
The endpoint is: `POST /reports/api/v3/projects/search` wih as body the project ids: `{"ids":[array of ids]}`

**Comment by simonrozsival** [comment]
Is this really the correct URL or is this feature already on staging server? I am getting 404.

**Comment by simonrozsival** [comment]
I checked the source code and the correct route is `POST /reports/api/v3/workspace/{workspace_id}/search/projects`
