### ISSUE TITLE
Handle HTTP 429 responses

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1037]
We don't implement actual rate limiting right now. While we could do that, I rather am optimistic and let the API tell us when we are pushing too much.

In that case (we get a 429) we should either simply back off for a bit, or enter the retry loop. I think using the retry loop sort of makes sense? Or will the status endpoint also return 429?

**Comment by amulware** [comment]
The status endpoint is also rate limited, but let's go into the retry loop anyways. The first status call is likely to fail, but then it will wait incrementally longer until it's fine again.

**Comment by simonrozsival** [comment]
This is a good way of doing it in the sync manager. What about the login, signup, etc. Will we check for 429 there as well, or will we just handle that as login/signup/... failed and show some generic error message to the user?

**Comment by amulware** [comment]
I think it's fine not to handle this error for those other cases since those don't happen often and really shouldn't be that problematic.

**Comment by simonrozsival** [comment]
Follow-up question: will we handle this exception also in PULL sync, or only in PUSH sync?
