### ISSUE TITLE
TE creation view: Ask confirmation when discarding TE 

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1042]
Ask confirmation: 'Discard' or 'Continue Editing' when user taps 'x' in TE creation view.

Zeplin: https://zpl.io/2jpx48Q

![toggl - ios - add new entry discard confirmation 1x](https://user-images.githubusercontent.com/5064445/33310925-e26cc1e2-d42b-11e7-866b-1dc57a897ef2.png)

**Comment by amulware** [comment]
Do we want to also show this if the user has not entered anything?

**Comment by pe0ny** [comment]
Let's show this only when user has entered something.
