### ISSUE TITLE
Create Project API

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#105]
For endpoints see #29.

For now it should be sufficient to add GETting of all the user's projects, and POSTing of new ones. This should be exposed in a nicer way as `Create()` or similar. (Editing them using PUT is not needed.)

Please `curl` the endpoints to see the exact format of the data it returns. Otherwise feel free to orient yourself on the already existing model, endpoints, etc.

Models and clients should have unit tests.

Please submit multiple small PRs for easier reviewing.

- [ ] endpoints
- [ ] models
- [ ] api client
- [ ] integration tests

**Comment by amulware** [comment]
This was started here: #63

Feel free to ignore or reuse as appropriate.

**Comment by kornelijepetak** [comment]
Implemented in f4d471ae74ec88d237999d4841d1b150a1859bed.
