### ISSUE TITLE
Multiple occurences of the same tag in new TE screen

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1050]
Currently you can add a single tag multiple times when creating a new TE screen.
As far as I understand, they will not be created multiple times, but from UX perspective, this should probably not be allowed.

@pe0ny It's your call whether we should just silently ignore the tap when user clicks on a tag suggestion for a tag that is already added, or should it be hidden from suggestions altogether.

**Comment by kornelijepetak** [comment]
![image](https://user-images.githubusercontent.com/7033216/33365019-1e4e5d2c-d4e7-11e7-81e3-763cee651b36.png)

**Comment by amulware** [comment]
If it is already added, the same tag should not be shown in the suggestions. Or alternatively (up to @pe0ny ) it is shown in the suggestions as checked and the user can UNcheck it.

**Comment by pe0ny** [comment]
☝️ What Paul just said. User should not be able to add the same tag multiple times and same tag should not be shown in the suggestions.
Let's not add checkboxes there atm.
