### ISSUE TITLE
Reports UI: loading state

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1056]
- Show this state while loading data
Zeplin: https://zpl.io/bzwZzME

![toggl - ios - reports loading state 1x](https://user-images.githubusercontent.com/5064445/33381854-d6204632-d527-11e7-8b5d-3a6f0b682cda.png)

- Colours that should change: #ECF0F2 and #FAFBFC
- Duration for one full circle: 4s
- Curve: Linear *check #172*

![ezgif-2-438229309a](https://user-images.githubusercontent.com/5064445/33381664-4a0dfec8-d527-11e7-9592-bce675810178.gif)

**Comment by amulware** [comment]
What kind of transition is there when the data gets there @pe0ny? A simple fade?

**Comment by amulware** [comment]
And if the user selects a different date range, does it go back to this loading state?

**Comment by pe0ny** [comment]
> What kind of transition is there when the data gets there @pe0ny? A simple fade?
Yes, let's use just fade for now.
For future reference, it would be super nice to use the same animation but faster (duration 2s, instead of 4s). So when data is ready to display, the loader will move on and show actual data/ colours, not grey area anymore.

> And if the user selects a different date range, does it go back to this loading state?
Yes.

**Comment by simonrozsival** [comment]
This issue is almost finished - what is missing is the fade transition.
