### ISSUE TITLE
App doesn't offer to create a new tag in TE creation view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1068]
The app doesn't offer to create a new tag in TE creation view, meaning it doesn't display 'Create a tag 'x''. It only allows creating new tags in Edit > Tags view.

**Comment by arturs105** [comment]
This is already implemented and working, however #1007 has made sorta broken it (the "+ create tag" cell isn't showing). We probably should have had a test that broke for such a change, but 🤷‍♂️ .

I hope the new project suggesting behaviour has a test that breaks, if the new functionality from #1007 is changed (@willsb knows about that better).
