### ISSUE TITLE
Change syncing bar in accordance with designs

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1074]
Check designs on zeplin, and change the bar accordingly.

**Comment by amulware** [comment]
Specifically, when we reach 'offline', the bar should stay and have a dismiss button. Possibly the same for 'failed'?  ping @pe0ny

**Comment by simonrozsival** [comment]
Also I noticed that the "Synced[tick]" seems strange - the icon is too close to the text.

**Comment by willsb** [comment]
It looks weird after #1102 was merged because it relied on the padding added by the initial space when creating attachments. 

We simply need to add that space back at the end of the `Synced` string.

**Comment by pe0ny** [comment]
Offline state with 'try again' and 'dismiss' buttons: https://zpl.io/bPrBM6D
When syncing fails because of no connection, it makes sense to show the same 'Offline' state ☝️ 
But I believe we should have separate 'Failed' state as well when for example backend won't respond? @amulware

**Comment by amulware** [comment]
I'm not sure what you mean with 'won't respond'. Do you mean in case the servers are down, or otherwise entirely unreachable? I'm not sure how much we can detect technically here. I think those cases would currently look the same as 'offline' to us.

**Comment by simonrozsival** [comment]
What happens when the servers are unreachable (but the user is connected to the Internet) is that the app will try repeating it several times which might take a few minutes (2-3) and eventually a `TimeoutException` will be thrown and the user will see a "Failed" msg and the bar will become red. There are no "failed" state designs in Zeplin though.

**Comment by pe0ny** [comment]
@simonrozsival Thanks! That's what I was wondering about if we need 'Failed' state or not. I'll add this to Zeplin as well.

**Comment by pe0ny** [comment]
Failed view: https://zpl.io/VKEYoeW
_I'm not really a big fan of big red error messages, so I would keep it grey but with different text on it._

**Comment by simonrozsival** [comment]
The UI is finished, but the "retry button" and "dismiss button" don't actually have any logic assigned to them. When the user taps on the screen when the syncing bar is visible, it is dismissed (the scroll view resets its position). I wasn't able to prevent this default behavior and implement this explicitly and I will have to consult this with @willsb or @arturs105 so I don't waste too much time searching for a solution.

**Comment by amulware** [comment]
Moving milestone as a bunch of this has been implemented now, and the rest can be done soon(tm).

**Comment by arturs105** [comment]
@simonrozsival So what else needs to be done here? Do the retry and dismiss buttons need some actions assigned to them, or is there something else?

**Comment by amulware** [comment]
Also maybe take into account #1355, #1202

**Comment by simonrozsival** [comment]
@arturs105 yes, we need the dismiss button to dismiss the bar and the refresh button to call the refresh command. That is all that's left from this issue.
