### ISSUE TITLE
Fix incorrect suggestions behavior

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1076]
I noticed two weird ways the "Create project" and "Create tag" suggestions in the "Start time entry view" which should be fixed to make it more predictable:

1. Creating duplicate tags
    - create a tag "abcde"
    - go to start time entry view
    - type in "abcdef"
    - hit backspace
    - you will get a `+ Create tag "abcde"` suggestion
    - click on the suggestion
    - you now have two tags called "abcde"
2. Incorrect project name suggestion
    - go to start time entry view
    - type in something like "time entry @project #tag" without selecting any suggestions
    - you will get a suggestion `+ Create project "tag"` instead of "project" (or in fact I am not really sure what should be the correct suggestion, but definitely not "tag" - this should be discussed in the comments IMO)

**Comment by simonrozsival** [comment]
@pe0ny @amulware What should happen, when user types something like "time entry @project #tag" without selecting any suggestion in the meantime and moving the cursor (so it is at the very end)?`
    

a) show  `+ Create project "project #tag"` (supposing there is no project with that name) 
b) show `+ Create project "tag"` (supposing there is no project with that name)
c) when typing #, switch from suggesting projectst to suggesting tags containing "tag"?
d) something else

**Comment by amulware** [comment]
a) maybe. # is definitely allowed in project names
b) absolutely not
c) maybe, this is similar to what todoist does, which is pretty intuitive to me, but people can't use '#' for searching projects then
d) not sure

Unless there is another option I can't think of, I think c) is best.

**Comment by pe0ny** [comment]
I agree with Paul: c) is the best and most intuitive. Also, that's how we already do it :)

**Comment by pe0ny** [comment]
Oh, never mind me, we don't. We still suggest projects, not tags. So yes, we should suggest tags.

**Comment by simonrozsival** [comment]
OK

**Comment by simonrozsival** [comment]
Follow-up question: What should happen when user types `abc @def ghi @jkl mno` or `abc #def ghi #jkl mno`? Should we consider only the part from the second symbol, or the whole thing after the first symbol?

**Comment by amulware** [comment]
From the second in my opinion.
