### ISSUE TITLE
Discuss serialization approach

### ISSUE THREAD

**Issue by cmoresid** [toggl/mobileapp#111]
Right now, both the Serialize and Deserialize methods on IJsonSerializer are asynchronous. It makes sense for the Deserialize method to be asynchronous because there is the potential for large JSON graphs to be returned from backend.

However, the asynchronous Serialize method is a bit cumbersome to use in the context of the API clients. From what I can surmise, the Serialize method is primarily used when POSTing / PUTing an entity to the backend. For example, we would have to do something like the following (types are not 100% compatible, but the idea is there):

```csharp
public IObservable<IClient> Post(string username, string password, Client client)
{
    var header = GetAuthHeader(username, password);
    return Observable.When(
                Observable.Create<string>(async observer =>
                {
                    var serializedClient = await serializer.Serialize(client, SerializationReason.Default);
                    observer.OnNext(serializedClient);
                    observer.OnCompleted();
            }).Then(body => CreateObservable<IClient>(endPoints.Post(client.WorkspaceId), header, body)));
}
```

A simpler method would be just to make the Serialize method synchronous and we could have the API call look like this:

```csharp
public IObservable<IClient> Post(string username, string password, Client client)
 {
    var header = GetAuthHeader(username, password);
    var body = serializer.Serialize(client, SerializationReason.Post);
    var observable = CreateObservable<IClient>(endPoints.Post(client.WorkspaceId), header, body);
    return observable;
}
```

From my understanding, the JSON that we are POSTing / PUTing isn't going to be huge, so there SHOULDN'T be an impact on performance.

How should we proceed?

**Comment by willsb** [comment]
Proposal:

- Change the whole API to be sync.
- Verify with backend what models/endpoints can return unusually large amounts of data.
- Write performance tests for said models.

While our perf tests don't show that the serializer is slow (since we still have many changes to do on the serializer layer), we don't care. If things start getting a tad too slow, we run the deserialization on a background task and avoid locking the UI while deserializing.
