### ISSUE TITLE
Handle creating projects in another workspace

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#1111]
Currently "change workspace" dialog is shown from start time entry view after the project has been created, but instead it should be shown from the project creation view before creating the project.

So the flow should be something like this:
1. User opens project creation view from start time entry view
2. Changes the workspace
3. Presses "Save"
4. "Change workspace" dialog is shown
 4.1. User presses "Cancel" -> do nothing, stay in project creation view
 4.2. User presses "Confirm" -> create the project, close project creation view, set project for time entry and change workspace of time entry

**Comment by pe0ny** [comment]
Copy changes for the dialog:

You've changed the workspace.
Your project and time entry will be allocated under the selected workspace.
Cancel; Ok;
