### ISSUE TITLE
Abort retry, if retry delay is more than <injected value>

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1115]
This counts for both the api and the status retry. If things are so bad that retrying doesn't get us there we should just give up after some time.

The value should be injectable (and maybe be allowed to be null for never giving up?), since we might want to have different things for different platforms/use cases.

For the current apps I think >1m is reasonable. This will make sure to retry the status a couple of times to see if the error persists, and it will retry the API at least once if the status is clear.

If the limit is crossed, it should not wait, but instead, emit a 'failed' sync event.

**Comment by amulware** [comment]
It might be worth considering to add a configuration object that the app can inject into the datasource (or wherever the syncman is created), so we can add more settings in the future if we like.

**Comment by simonrozsival** [comment]
If I am not mistaken, right now the delayed transition will timeout when it is > 1 minute long. That is not intentional, but I noticed it happens. I'm not sure what the result is, but I think it emits a Fail.

**Comment by simonrozsival** [comment]
Just to make sure: failure should occur when the next delay would be over the limit (that's what I suppose should happen), or if the user gets stuck in the retry loop for longer than the limit?

**Comment by amulware** [comment]
You suppose correctly. It should fail when the next delay is over 1 minute (it should work fine for exactly one minute). It does not matter how long the user has been in the loop, or how often we have retried.
