### ISSUE TITLE
Report syncing errors to crash reporting tools

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1116]
This will need a custom abstraction that allows us to report errors/warnings no matter what service we are using.

The reason behind this is that we should gather analytics about what kind of errors happen with what frequency to improve the syncing algorithms and detect problems quicker.

We probably want to report ALL errors that happen inside the syncing machine for the start. If some of them happen a lot and we don't actually care we can always filter them later.

However, we have to be extremely careful that these errors do not contain any actual user data.

**Comment by simonrozsival** [comment]
I checked how to store handled exceptions using the AppCenter and apparently, it is not possible to do that at the moment: https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/140

**Comment by simonrozsival** [comment]
@amulware would it be enough to log this as a "SyncError" event with a parameter which would hold the type of the exception and the message of the exception?

**Comment by amulware** [comment]
Similar to time entry creation events, etc.?

Does App Center have no way of reporting warnings, or custom errors?

I'm not sure we should mix data like this with data about user behaviour if we can avoid it. What are your thoughts?

**Comment by simonrozsival** [comment]
As I pointed out in the previous comment, we cannot send handled exceptions to AppCenter. We can just track custom events with properties just like in Firebase (https://docs.microsoft.com/en-us/appcenter/sdk/analytics/xamarin).

**Comment by amulware** [comment]
My bad. I didn't see the comment above. It looks like they will add the feature we want soon, but I rather not wait. Let's do it as you suggest for now!
