### ISSUE TITLE
Edit view UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1121]
- [x] Description and duration use inline editing.
- [x] Project and tags use a separate view.
- [x] Start/stop times and date use pickers.
- [x] Tapping back arrow discards changes.
- [x] Tapping 'Save' saves changes.
- [x] When time entry is running, the duration must be ticking as well.
- [x] Show 'Set' only when time entry is running.
- [x] Tapping 'Stop' stops a time entry and sets an end time.

### Edit view
![edit](https://user-images.githubusercontent.com/5064445/33831868-68657770-de82-11e7-950d-b4df8972864e.png)

Zeplin: https://zpl.io/V4E1oDz

### Description field active
![edit - description](https://user-images.githubusercontent.com/5064445/33722522-e1e663b0-db72-11e7-893b-72f761dce882.png)

Zeplin: https://zpl.io/bezYOnz

### All fields selected
![edit all fields selected](https://user-images.githubusercontent.com/5064445/33831874-70bdafd2-de82-11e7-8c31-d4bf5792423d.png)

Zeplin: https://zpl.io/VQMY1rm

**Comment by amulware** [comment]
Implementations of specific features: #1122 #1123 #1143 #1144

**Comment by kornelijepetak** [comment]
Closed by #1353 .

Redesigning UI will be part of a separate issue.
