### ISSUE TITLE
Projects view UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1122]
- [x] User can access projects view from the edit view.
- [x] When a user has only one WS, don't show WS labels (ie. don't filter project by workspaces).
- [x] When a user has multiple WS, group projects by workspaces.
- [x] Indicate selected project with coloured background/token.
- [x] When a project includes tasks, show tappable 'N tasks' label on the right side.
- [x] User can access tasks by tapping Tasks label on the right side which opens tasks list. *Arrow should rotate 180 degrees based on if tasks are opened or not.*
- [x] Use fade for long project/client/task names. *Use different paddings for fades based on if projects have or not have tasks.*
- [x] When a user has typed in project name that doesn't exist yet, show 'Create project' option.
- [x] Tapping 'Create project' opens project creation view.

### Projects view: multiple workspaces
![projects](https://user-images.githubusercontent.com/5064445/33727411-98000b6c-db80-11e7-975f-758dd6286d50.png)

Zeplin: https://zpl.io/awydrQN

### Projects view: tasks
![projects - tasks](https://user-images.githubusercontent.com/5064445/33727438-b2dfc9e0-db80-11e7-88a2-9d91358ca3ae.png)

Zeplin: https://zpl.io/2p0gdrr

### Projects view: one workspace
![projects one workspace](https://user-images.githubusercontent.com/5064445/33727446-bc11d12a-db80-11e7-9ee5-ff9ff9e22b41.png)

Zeplin: https://zpl.io/V1MA8kX

### Projects view: create project
![projects - create project](https://user-images.githubusercontent.com/5064445/33755512-c97f1d9e-dbf9-11e7-9b1a-ffd01261700c.png)

Zeplin: https://zpl.io/2y1omwy

**Comment by kornelijepetak** [comment]
Requires #1636 to be completed first.

**Comment by kornelijepetak** [comment]
Closed after finishing #1730 
There is also another issue related #1731, but this one can now be closed.
