### ISSUE TITLE
Tags view UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1123]
- [x] User can access tags view from the edit view.
- [ ] Show tags only from the workspace that the time entry is assigned to.
- [x] Indicate selected tags with blue checkboxes.
- [x] Use fade for long tag names.
- [x] When a user has typed in tag name that doesn't exist yet, show 'Create tag' option.
- [x] Tapping 'Create tag' creates a new tag and selects it automatically.

### Tags view
![tags](https://user-images.githubusercontent.com/5064445/33755601-3ed9335e-dbfa-11e7-8267-a357871972b2.png)

Zeplin: https://zpl.io/2Ed87e8

### Tags view: create tag
![tags - create tag](https://user-images.githubusercontent.com/5064445/33755553-fa043972-dbf9-11e7-85aa-35d58f29dbfa.png)

Zeplin: https://zpl.io/VDpm8qv

**Comment by willsb** [comment]
It's really weird to see text on the right side of the material toolbar. Can we use an icon there instead?

**Comment by willsb** [comment]
Also, I noticed that this view has twice the height of a normal toolbar, but the projects/new clients/see clients views all have normal toolbar height. Any reason for that?

**Comment by pe0ny** [comment]
I think designers used higher toolbar because tags view needs both search and save option. It's similar to start view except we use text instead of the icon at the top right corner.

About the icon itself - floppy disk? 😛
