### ISSUE TITLE
Chinese keyboard creates both Chinese and Latin characters in start view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1124]
I don't know enough about international keyboards to give exact steps to reproduce or advise otherwise.

**Comment by ApocalypticFish** [comment]
When using a Chinese Simplified (Pinyin) -I think-  keyboard or Japanese Romaji Keyboard and attempting to type a description in a new entry or editing an existing entry to type characters it is supposed to replace the Latin characters, and does this behaviour in other iOS apps (messenger/messages) but when attempting on the app it creates the Chinese characters and leaves the international/English characters.
To replicate this with the Chinese or Japanese keyboard enabled type an english character then attempt to enter the Japanese or Chinese character from the suggestions bar, it will create the Chinese or Japanese character but won't remove the Latin character from the description field.

**Comment by amulware** [comment]
Possibly related to #1158

**Comment by simonrozsival** [comment]
I tested this with Chinese (simplified) keyboard and it worked the same way as with the Japanese keyboard. There were definitely no Latin characters inserted into the text. I think we can close this for now and reopen it if we get another bug report after this fix is released.

**Comment by willsb** [comment]
Tested this with a Chinese speaker and the problem seems to be gone, indeed
