### ISSUE TITLE
Sign up UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1133]
- [x] User can sign up using the email and password 
- [ ] User can sign up using Google login.
- [x] Back arrow takes the user back to the onboarding view.
- [x] Green fab takes the user to the next step: password entering.
- [x] Show loader on the right side.
- [x] Show error messages below the email/password input field.

### Sign up: step1
![sign up - step1](https://user-images.githubusercontent.com/5064445/33769172-cb00264e-dc31-11e7-845f-db65a76a45df.png)

Zeplin: https://zpl.io/aRmKzEg

### Sign up: step2
![sign up - step2](https://user-images.githubusercontent.com/5064445/33769188-dbc27ff4-dc31-11e7-96f1-c86ac51ecf37.png)

Zeplin: https://zpl.io/V4En5QQ

**Comment by willsb** [comment]
Closed by #1206
