### ISSUE TITLE
Edit date UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1145]
- [x] A dialog picker is used to select a single date.
- [x] The selected day is indicated by a filled circle. The current day is indicated by a different colour and type weight.
- [x] A user can swipe left to right to navigate through the months.

### Date edit view
![edit - date](https://user-images.githubusercontent.com/5064445/33835091-071f37ce-de8e-11e7-89f1-f91e9c7e1d2b.png)

Zeplin: https://zpl.io/2ZqdqAJ

**Comment by kornelijepetak** [comment]
@pe0ny Having a title 'Start date' is a hell to implement on Android. They don't allow titles on these... Is this necessary?

**Comment by pe0ny** [comment]
@kornelijepetak Nope, that's not a high priority so let's skip it for now.
