### ISSUE TITLE
Improve state machine behaviour for longer delays

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1151]
As followup to #1115, we should increase the delay that the sync state machine allows an individual state to take before it will abort.

I think that we might as well make this value injectable, and that we maybe want to go with a value between 2-5 minutes.

Alternatively, it would be great if we could somehow be smart about this. The goal is to detect if a state gets stuck and then abort. Maybe there is a better solution.

I have not thought it through very much though. Other thoughts are welcome.

**Comment by simonrozsival** [comment]
I can't think of any simple/clever way of how to make sure that any state doesn't get stuck. Making the timeout limit configurable should be enough for now IMO.

**Comment by simonrozsival** [comment]
I understand https://realm.io/docs/dotnet/latest/#crash-reporting in such way that the user data won't be in the exception message. Our crash reporting tools only show the stack trace and the message of the exception - no data should be exposed if we use the message from the realm exception.

**Comment by amulware** [comment]
Yeah, I'm fine with that. Let's inject that and set it to 2 minutes? I can't see anything except the retry delay states getting anywhere close to that.

**Comment by amulware** [comment]
Nothing here in a while, and we'll take another big-picture look at syncing soon anyways.
