### ISSUE TITLE
Bad deserialization case in reports API

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#1156]
Ping me if you need the JSON that causes the deserialization error.

Doesn't seem to happen if the user has no time entries for the selected period.

**Comment by simonrozsival** [comment]
I found out that deserialization fails when the `billable_seconds` field is missing, e.g.:
```json
[{"user_id":3226369,"project_id":null,"tracked_seconds":15}]
```

**Comment by simonrozsival** [comment]
... but the real issue was the linker.
