### ISSUE TITLE
Japanese input bug keyboard and flick input

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1158]
From Twitter:

>My env is iOS 11.2 on iPhone 6.
>There is flic-input bag in Japanese on new toggl iOS app, I hope it will be fixed as soon as possible.
>For example, when typing with ABC, it is output as AABABC.(Replace the alphabet with Japanese characters)
>As I confirmed it now, the same problem has occurred not only in flick input but also in keyboard input in Japanese characters." 

https://twitter.com/mtane0412/status/940784885521895424/video/1

Assuming it's something like this? https://www.imore.com/how-use-keyboard-flick-ipads-quicktype-keyboard-ios-11

**Comment by simonrozsival** [comment]
The bug is most likely hidden in the `TextViewTextInfoTargetBinding` class. I will continue debugging this.

**Comment by simonrozsival** [comment]
This is probably bug of the `UITextView` when using the attributed text with multibyte characters, see: https://stackoverflow.com/questions/31430308/uitextview-attributedtext-with-japanese-keyboard-repeats-input

**Comment by ricotheque** [comment]
Thanks for working on this guys!

Just wanted to share a walkthrough from a user, in case it's helpful:
1. First, I flick "て", then "て" is shown. (this is expected)
2. Next, I flick "す", then "ててす" is shown. ("てす" is expected)
3. I flick "と", then "ててすてすと" is shown. ("てすと" is expected)

![image](https://user-images.githubusercontent.com/5687885/34153837-70d5949a-e4ee-11e7-86bd-0c265716a192.png)
