### ISSUE TITLE
CJK keyboards not supported

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#1164]
> The previous version had no problems with Japanese input, but CJK input methods are rendered useless in this version.

https://toggl.desk.com/agent/case/602415

![image](https://user-images.githubusercontent.com/5687885/34023720-6f578f30-e181-11e7-9de0-82d0c0dea653.png)
![image](https://user-images.githubusercontent.com/5687885/34023732-774d2a60-e181-11e7-8b16-5fd6833578ab.png)

**Comment by nicktoggl** [comment]
Same as #1158 can close
