### ISSUE TITLE
Add open source licenses to App

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#1172]
We **must** add and `About` or `Open source` tab to our app with this info (in the settings, I think)

Please note that it should not rely on the internet, since this info must be available even when the app has no connectivity

**Comment by pe0ny** [comment]
We need a list of licenses we have to add first before we can start with designing this.

**Comment by willsb** [comment]
This is a list of all our projects. We'll hunt licenses (when applicable) tomorrow.

Common:
Fody
Microsoft.Reactive.Testing
MvvmCross
Newtonsoft.Json
PropertyChanged.Fody
Realm
StyleCop.Analyzers
System.Reactive.Core
System.Reactive.Interfaces
System.Reactive.Linq
System.Reactive.PlatformServices

Test projects:
FluentAssertions
FsCheck
FsCheck.Xunit
FSharp.Core
NUnit
NSubstitute
Xamarin.TestCloud.Agent
Xamarin.UITest
xunit

iOS:
Xamarin.1PasswordExtension
Xamarin.Firebase.iOS.Analytics
Xamarin.Firebase.iOS.Core
Xamarin.Firebase.iOS.CrashReporting
Xamarin.Firebase.iOS.InstanceID
Xamarin.Google.iOS.Core
Xamarin.Google.iOS.SignIn

Android: 
Xamarin.Android.Support.Animated.Vector.Drawable
Xamarin.Android.Support.Annotations
Xamarin.Android.Support.Design
Xamarin.Android.Support.Fragment
Xamarin.Android.Support.v7.AppCompat
Xamarin.Android.Support.v7.RecyclerView
Xamarin.Android.Support.Vector.Drawable

**Comment by pe0ny** [comment]
@willsb Should we link those to somewhere as well?

**Comment by willsb** [comment]
Nope. They simply have a plain text license that we need to display somewhere in our app, that's all

**Comment by amulware** [comment]
@pe0ny This still needs a design. I figure having it somewhere in the settings is good. Doesn't have to be prominent, just so that users can find it if they insist. Maybe just behind a button called 'Licenses', or maybe we can find smarter/funnier copy.

**Comment by amulware** [comment]
And @willsb was gonna hunt licenses. ;) Let's see if we can group things so it doesn't look like some crazy long list? I imagine most of the things above will have the same few licenses.

**Comment by pe0ny** [comment]
I would do it so then: List all the projects that have the same license and display the license below it.

## Design Preview
### Licenses
![toggl - ios - licenses 1x](https://user-images.githubusercontent.com/5064445/35962692-015c776a-0cbb-11e8-94bc-b0542c5004de.png)

Zeplin: https://zpl.io/2Zx5kGX

**Comment by amulware** [comment]
I'd consider hiding the licenses behind another button, given that some of them might be long. @willsb is the expert here though.

**Comment by amulware** [comment]
What is this waiting for?

**Comment by arturs105** [comment]
I have this implemented locally, but there is a bug/glitch with dynamic cell heights - sometimes cells are way too tall. Might be related to cell reuse, but i haven't completely tracked the issue.

Also, when i had completed this, i didn't make a PR to avoid merge conflicts in settings xib file, since we already had a PR that made changes to that.
