### ISSUE TITLE
Add feedback option to the Settings page

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1181]
- [ ] Add feedback option so users can contact us directly from the app.
- [ ] Let's keep it simple and open an email-sending form when user taps 'Submit Feedback'. *(Like the one we used for Superday)*
- [ ] Send email to support@toggl.com
- [ ] Subject line: Toggl iOS feedback
- [ ] Include app version number, OS version and device in the email
- [ ] When a user doesn't have an email account set up, display this error message:
*Oops! Seems like your email account is not set up*
*Go to “Settings > Mail > Add Account” to set up an email account or send us your feedback to support@toggl.com*
- [ ] When a user is offline, display this error message:
*Sorry. Can’t send the email.*
*You’re offline. Please connect to the internet and try again.*

### Settings
![toggl - ios - settings synced copy 1x](https://user-images.githubusercontent.com/5064445/34160769-f4e047a2-e4d6-11e7-9c0f-fe146bb1a248.png)

Zeplin: https://zpl.io/25NG94r

### Email account not set up
![toggl - ios - settings error1 1x](https://user-images.githubusercontent.com/5064445/34161310-f0d833c0-e4d8-11e7-8e89-777b27d4b95e.png)

Zeplin: https://zpl.io/VkKk7eg

### No connection
![toggl - ios - settings error2 1x](https://user-images.githubusercontent.com/5064445/34161332-017881a8-e4d9-11e7-8427-a68bf5160856.png)

Zeplin: https://zpl.io/bo056Mg

**Comment by amulware** [comment]
@pe0ny Why do you want to send emails instead of using a custom view and endpoint like the old app? I think the latter gives a much better user experience and allows us to send the extra data more 'sneakily' (mostly without confusing users).

**Comment by pe0ny** [comment]
@amulware Do we have that endpoint in v9, too?

I don't mind having UI for that but for me, email seems to be the easiest way to do it and UX wise we have tons of other stuff to focus on atm.

**Comment by amulware** [comment]
There currently is no endpoint for v9. If we want the feedback function as soon as possible, I'd say do it as described above. In either case, we can have backend make us a custom endpoint sometime soon so we can do this 'properly' down the line.

**Comment by pe0ny** [comment]
Yep, let's go with the simple email solution for now. 👍

**Comment by amulware** [comment]
Since we are handing off responsibility for sending to the Mail app, I don't think we should check for network connection. The email can be composed either way, and there already is no guarantee that it actually gets send (we have to trust the Mail app, and the user), so the online-check seems like redundant work to me. More discussion on Slack. Also pinging @pe0ny
