### ISSUE TITLE
Greyed out/unresponsive play button

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#1193]
User writes that their play button is greyed out and won't start the timer when pressed. Also says experiencing crashing when he attempts to press. Any ideas? Will check to see if imminent update fixes issue.

Thanks,

Edited to remove user data - ![image-1](https://user-images.githubusercontent.com/17441860/34237697-4211f468-e652-11e7-950e-9c725b7f0726.jpg)

**Comment by willsb** [comment]
Might've been fixed by #1190

**Comment by amulware** [comment]
Closing this as likely fixed. If there is more information feel free to reopen.
