### ISSUE TITLE
New app sync issue

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#1194]
We have a user who has written in regarding some entries that haven't synced with the new app. Please see attached screenshot,

Edited to hightlight particular entry problem

![image1](https://user-images.githubusercontent.com/17441860/34240013-695765dc-e65f-11e7-9ba3-5d0474b40a77.png)

Not sure if it's relevant but in backoffice and h4xx she did delete an entry that ran across the 18th-19th, not sure if that has caused a fault somewhere.

User Id in backoffice is 2780806

**Comment by amulware** [comment]
@nicktoggl I don't see anything to fix here. The user can open the time entry details, and there should be an error message explaining why syncing fails. Without those error messages, this is 100% intended behaviour.

**Comment by amulware** [comment]
Feel free to reopen if there is more information that indicates something is wrong with the app.
