### ISSUE TITLE
Mark current day in the reports calendar

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1197]
There is no visual feedback which day is today. There is currently no design in Zeplin.

**Comment by amulware** [comment]
I suggest we add a transparent overlay, maybe 30% or so opacity, light gray with rounded corners to the background (no matter if the day is in the selected range or not).

**Comment by simonrozsival** [comment]
Could you please have a look at this issue, @pe0ny?

**Comment by pe0ny** [comment]
I like Paul's idea. Let's use the same colour that we use for non-selected shortcuts below for the background: #B5BCC0 12%
Text colour will remain black #000000
