### ISSUE TITLE
Make it easier to view reports for a single day

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1201]
When I tap once at some date and I hide the calendar, I would expect the app to show reports for that single day, but nothing happens.

It is necessary to click on that date again to set it as both the start and end date. Also the title says e.g., “21 Dec - 21 Dec”, but it should say simply “21 Dec”.

Please consider this feedback, @pe0ny and @amulware, and feel free to close this if you don’t agree.

- [x] Make selecting a single day easier
- [x] Add Today and Yesterday shortcuts

**Comment by amulware** [comment]
Yes, I think this would be an improvement. If @pe0ny agrees, let's do it.

**Comment by pe0ny** [comment]
Agreed 🙌 let's do this!
- Tapping once and closing the calendar should show reports for that single day
- Title should show only this one date, too.

**Comment by pe0ny** [comment]
Also, another idea. I would add two more shortcuts there as well: Today and Yesterday.
@simonrozsival Do you want me to create another issue for that or could be done in this?
