### ISSUE TITLE
Report calendar displaying wrong date

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#1203]
"Today, it's Friday, Dec 22 while the app calendar (in the date picker of reports) thinks it the 21...
<see screenshots attached>"

I can replicate but it appears correct on Jordan's and Rico's

![image1 2](https://user-images.githubusercontent.com/17441860/34286407-9f17d456-e734-11e7-831d-ed30f3199ba3.png)

case/606543

**Comment by ricotheque** [comment]
User is in the UTC +2 timezone. No daylight savings time switches or anything similar have occured in this area:
https://www.timeanddate.com/time/change/timezone/utc2

**Comment by ricotheque** [comment]
Just reconfirming that the calendar that appears is for 2018 (not 2017). Also received feedback from a UTC +0 user who encountered this same issue.

**Comment by ricotheque** [comment]
Hey team, another user (case/619280) reports the same issue.

"For example, January 1, 2018 is shown as a Wednesday and it should be a Monday."

Not sure if this is based on the year or anything related.

**Comment by amulware** [comment]
@ricotheque Could you investigate if this might be related to the first-day-of-the-week setting? Maybe only the headers or only the calendar take this setting into account, causing them not to line up correctly unless Monday is set as the first day of the week?

**Comment by simonrozsival** [comment]
I would like to point out that the calendar in the current version doesn't highlight any date as today - that will come in the next release (https://github.com/toggl/mobileapp/pull/1204 - merged yesterday). What the users here are seeing is some date they tapped on themselves. I agree that the UX is confusing, see this issue: https://github.com/toggl/mobileapp/issues/1201

**Comment by amulware** [comment]
I might be missing your point, but there is definitely a bug here. 2017-12-22 was a Friday, while the screenshot above shows it as a Saturday - just to make sure we're on the same page. Otherwise, you're right there is (probably) no issue with the highlighting.

**Comment by nicktoggl** [comment]
Just on this issue, this user is providing some interesting examples of the problem and how it changes the time he is tracking.

Screenshots included case/619417

I'll just post his quotes

"Just wondered if you'd made any progress on resolving the Calendar issue. I've attached some screen shots taken from my first week in 2018 which show up the anomalies.

Screenshot one - days of the week at the top of the calendar don't correspond with the dates.

Screenshot 2 - Here I get a figure of 24:50:39 but that doesn't include Monday.

However, if I click on the 'This Week' tab at the bottom left of the calendar I get a figure of 32:21:41 which includes Sunday.

This is the correct number of hours and includes Sunday.

I can't work out why there is a discrepancy between the two views where one is working off a week beginning on Sunday and the other a week beginning on Monday."

**Comment by amulware** [comment]
It sounds like there MAY be more than one bug at play here. Let's fix the display first, so that it correctly takes the user setting (first day of the week) and of course the correct calendar dates into account when showing the calendar (and make sure it actually requests data for the correct selected dates).

If there is still an issue afterwards, there may be a bug in the api endpoint not taking time zones or days of the week into account correctly or something of the sort.

**Comment by ricotheque** [comment]
@amulware Sorry for the late reply! It's unrelated to their first-day-of-week setting.
