### ISSUE TITLE
Make FAB and Back button states follow the VM state

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1207]
Currently, the back button and the FAB do not get disabled or enabled according to the VM flow.

The calls to the handlers get swallowed if they should not be pressed at certain state, but the visuals don't change at all.

**Comment by willsb** [comment]
Now that I think about it, I've never seem the FAB with a disabled color. One thing we could do is calling `Show` and `Hide` so it's only visible when it can be clicked, but this needs to be well thought

For the back arrow, I'm not sure if disabling the physical back button while loading is a good idea. I know for a fact I'd feel weird if an app disabled my physical back button, for whichever reason. Maybe if the physical back is pressed while loading we should ask if they want to cancel the operation and close the login view altogether?

**Comment by willsb** [comment]
ping @pe0ny for clarifying the above ☝️

**Comment by pe0ny** [comment]
To sum up the conversation in slack:
- FAB will be hidden instead of disabled.
- Back button won't be disabled and cancels login.
