### ISSUE TITLE
Detect that user already has an account during sign up

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1221]
When user tries to create a new account for an email address which is already used by some account, we receive a 200 response from the backend with the response `{"has_account":"true"}`.

We should display some better copy for the error msg in this case - please provide some text @pe0ny or @amulware.

**Comment by amulware** [comment]
Subject to approval, I propose: "Email address already associated with an account. Try logging in instead." (part of) the last sentence could be a link to the login page

Alternatively, should we simply try logging the user in with the provided credentials?

Or we could ask the user if they wanted to try and login with the same credentials instead.

Many options.

**Comment by pe0ny** [comment]
Let's keep it simple:
"User with this email already exists. **Try logging in instead.**"
Last sentence links to log in page with email field already filled.

**Comment by willsb** [comment]
Technical compliment to the above: I believe that simply changing the `LoginType` of the page **might** work, but note that some things might not behaving accordingly (i.e.: The page's title might not change, since it was never thought to be bindable).
