### ISSUE TITLE
Set up HockeyApp to track crashes

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1222]
Given how badly Firebase works with Xamarin let's use HockeyApp to get better stack traces instead. We also might not have any need for uploading symbol files there - it certainly wasn't necessary with Xamarin Insights.

**Comment by amulware** [comment]
Note that we'll keep tracking crashes in Firebase as well, since we can get a much better overview of crash-free user percentages, etc. there.

**Comment by amulware** [comment]
Het another change. We're gonna use App Center!

**Comment by willsb** [comment]
I can take this one once the apps are created on App Center

**Comment by amulware** [comment]
The apps have been created there, and everyone on the team should have access.
