### ISSUE TITLE
Improve login screen invalid data feedback

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1223]
Here are a couple of pain points of mine:

- when no valid email is entered or the password field is empty, the 'next' button is grayed out, but the effect is so subtle I can only tell because I know. This could confuse users if they try tapping the button
- when I hit [return] on the keyboard with no valid password entered, the keyboard closes, but nothing else happens
- when I hit return with an empty password field, the keyboard closes

I think we should make it clearer to the user that a valid email is required, and definitely not close the keyboard. Also if possible, we should change the return-button text to 'next' or similar.

Maybe if the user tries to hit next/return when there is no password/an invalid email, we should show a message stating so under the text field? "Please enter a valid email address." "Please enter your password."(login)/"Please enter a password."(signup)

**Comment by willsb** [comment]
Ref #1021

**Comment by ApocalypticFish** [comment]
Not sure if this needs to be changed for the field on each page, but this occurs (or doesn't occur) on signup, login and forgot your password pages

**Comment by amulware** [comment]
We probably have to rethink this with the upcoming changes to the login/signup screens anyways. Still leaving it open so that we take another look at the UX in the future.

**Comment by amulware** [comment]
We should also show a specific error when we detect the user being offline.

**Comment by amulware** [comment]
Shall be superseded given we have an entirely new design.
