### ISSUE TITLE
Make sure all lists are sorted correctly

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1237]
As a follow up on #1209, let's compile a list of all lists, suggestions, completions, whatever that we show in the app, and if and how each is sorted. We can then see what still has to be sorted and can discuss how if it's not obvious.

In general, we should probably make it policy to sort any list we'll show in the future in a non-arbitrary way.

**Comment by arturs105** [comment]
So i went through the app and these are the lists that we are showing and might need to sort differently:
- [ ] Suggestions (Working on these tasks view)
- [x] Log (sorted chronologically)
- [x] Reports legend (sorted by percentage, i assume)
- [x] Calendar quick select actions (sorted as we see fit)
- [ ] Select workspace view (looks like it's sorted alphabetically, though i couldn't find where we do it in our code, so i assume Realm returns them in alphabetical order)
- [ ] Time entry suggestions when starting a time entry
- [ ] Project workspace groups when starting a time entry
- [ ] Projects in a workspace when starting a time entry
- [ ] Tasks for a project when starting a time entry
- [ ] Tags when starting a time entry (looks like they are sorted alphabetically, though we aren't explicitly sorting them, so Realm i guess)
- [x] Projects, when editing a time entry (sorted alphabetically)
- [ ] Project groups (by workspace) when editing a time entry
- [ ] Tasks for a project when editing a time entry
- [x] Selecting tags when editing a time entry (sorted alphabetically and selected ones at the top)
- [ ] Tags displayed in edit time entry view

@pe0ny The unchecked ones probably need sorting criteria from you. You can also check, whether the checked ones are sorted properly.

**Comment by pe0ny** [comment]
**Here are the unchecked ones with my proposals:**

- [ ] Select workspace view (looks like it's sorted alphabetically, though i couldn't find where we do it in our code, so i assume Realm returns them in alphabetical order)
   - yep, should be sorted alphabetically (also, note that this applies both - when selecting a default ws from settings and when selecting a ws when creating a new project)

- [ ] Time entry suggestions when starting a time entry (this should apply to all suggestions including time entries and projects)
   - sorted alphabetically

- [ ] Project workspace groups when starting a time entry
   - sorted alphabetically and default one at the top

- [ ] Projects in a workspace when starting a time entry
   - sorted alphabetically

- [ ] Tasks for a project when starting a time entry
   - sorted alphabetically

- [ ] Tags when starting a time entry (looks like they are sorted alphabetically, though we aren't explicitly sorting them, so Realm i guess)
   - yep, should be sorted alphabetically

- [ ] Project groups (by workspace) when editing a time entry
   - sorted alphabetically and default one at the top

- [ ] Tasks for a project when editing a time entry
   - sorted alphabetically

- [ ] Tags displayed in edit time entry view
   - sorted alphabetically



**And couple of more things I found:**

- [ ] Clients when creating a new project
   - sorted alphabetically

- [ ] Suggestion workspace groups when starting a time entry
   - sorted alphabetically and default one at the top

**Comment by pe0ny** [comment]
I'm thinking that maybe we should do it like webapp does it and group by Time Entries, Projects, Tasks and sort suggestions under each category alphabetically. I know that we already have grouping by workspaces but I think it's still doable.
Time entries will be sorted based on the description only.

Thoughts?

**Comment by amulware** [comment]
That makes sense to me, but that's actually a pretty big functional/UI change. We'd have to think how that even works on the tiny display (compared to web) - maybe it needs tabs for TEs/projects/tasks or something, because right now when I search for 'meeting' it gives me A LOT of time entries that include that word in the description, and a lot of time entries that include it in the project name, and if the user only wants the project, they can't be expected to scroll all the way to the bottom.

**Comment by amulware** [comment]
Actually, maybe it should show tasks/projects at the top, not at the bottom, since matches with that might actually be a lot more significant/important than matches in generally longer descriptions? Just a thought. Maybe worth trying out.

**Comment by amulware** [comment]
This has been left lying around for a while.

Here is what I'd like someone to do:

- check all the above
- see what is still up to date, and what isn't (check both iOS and Android please, in case there is a difference somehow!)
- list what we still have to do
- write proposals for all cases that are not clear (describe what it's doing right now, and give one or multiple options for how to improve it)
- create one issue per case and ping @amulware with them when done

And then we'll close this epic. :D

**Comment by juanlaube** [comment]
I checked the bullets that are sorted correctly in the list above and created issues #4225, #4226 and #4227 for the stuff that is pending.

**Comment by juanlaube** [comment]
I'd like to discuss the order of time entry suggestions before creating an issue for that though, because the previous comments are not clear enough or might not be up to date.

Ping @amulware and @maritoggl.

**Comment by amulware** [comment]
Please summarise what it is doing right now, and what our options are. Either here or a new issue is fine. 😊

**Comment by sofokli1** [comment]
I have checked above what are done until this point. Moving this to 1.18 since there are a few not finished

**Comment by sofokli1** [comment]
@amulware only the unchecked cases from the lists above are still not done. should I make issues or leave them be and close this?

**Comment by amulware** [comment]
Let's create issues and close this. :)

**Comment by amulware** [comment]
And note my comment above as well.

**Comment by juanlaube** [comment]
I thought I created an issue for that but I can't find it now, so I guess I didn't 🙈 
@sofokli1 are you taking care of that?

**Comment by sofokli1** [comment]
both of these i think talk about the same thing but not 100% sure (correct me if I am wrong)

> * Time entry suggestions when starting a time entry (this should apply to all suggestions including time entries and projects)
> * Suggestion workspace groups when starting a time entry

Currently when typing something the suggested TEs are grouped by workspace (workspace are NOT order alphabetically and default workspace is NOT on top). Suggestions in the workspace group seem organised alphabetically but does not perform well when having mix language in TE description (it will use the first english work it finds in the text to order the TE even though the initial work of the description could be in a random language like greek).

@amulware I would suggest a new issue that requires the grouping of workspace to happen the same as we do when selecting a project (workspaces sorted alphabetically and default one at the top). We do nothing for now regarding the mixed languages in TE description.

PS: not sure how the mix language will behave in project names, task etc. but I do not know how much mix languages is used by toggl users.

**Comment by amulware** [comment]
I believe this is issue is no longer needed then? Please close it if that is the case.

**Comment by sofokli1** [comment]
The last unchecked sort case has its own issue. Closing this
