### ISSUE TITLE
Remove duration icon from TE creation view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1257]
Remove duration icon from TE creation view and keep only four: projects, tags, billable and start/stop time. The last one opens the wheel popup where a user can edit start/stop time/date and duration together. See #1053

<img width="339" alt="screen shot 2018-01-09 at 16 35 57" src="https://user-images.githubusercontent.com/5064445/34725943-34c0dffa-f55b-11e7-86e5-66b23b13bf2b.png">

**Comment by simonrozsival** [comment]
Question: In the new Wheel view user can stop the TE and set the new duration of the TE. Should this view accept the stop time? I believe it should but I am asking just to be sure.

**Comment by pe0ny** [comment]
@simonrozsival Good question but nope. Atm, we do not allow stopping a time entry from this view.

**Comment by amulware** [comment]
Clarification: The user cannot stop in the start view, but they can in the wheel view. So what we have now is how it should be. All good. 👌
