### ISSUE TITLE
Sync issues new iOS

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#1265]
"There is a whole list of active projects on my iPhone which did not get transferred to my PC toggl or to my iPads. One project that I started on an iPad (as a trial) appears on my PC but does not appear on my iPhone. I did not check all the instances on my PC, my iPhone, or my iPads -- but there definitely seems to be something incorrect in the synchronization between my devices. Can you help? If you need additional information, please let me know exactly what.
One more point: among the active projects on my iPhone that do not appear on my PC/iPads, most (but not all) are marked with two curved arrows around an exclamation point. I have no idea what this mark means.
Second: nothing happens when I tap the exclamation points – except that the
Edit window opens.

I keep trying to force refresh/sync on my iPhone. Nothing happens except
that in the grey area (revealed by pulling down) I see "syncing" with the
rotating circle – which goes on indefinitely and does not end."

Is this due to the use of iPad which is unsupported by our iOS app?

**Comment by maritoggl** [comment]
Case #626208, user #3810347. 
Reached out to ask additional screenshots and information about the iPhone and the iOS version that the user is on.

**Comment by amulware** [comment]
For non-syncing TEs, the edit view should show an error message stating why the sync failed.

Screenshots (except of the error message), iPhone and iOS version are most likely not useful.

Without more information, there is nothing we can do here.

**Comment by amulware** [comment]
Please see internal communication for likely cause and workarounds.

Short summary:
- user might have been removed from (or deleted) workspace/project
- the app does not yet notice this change
- the app tries to create the TEs under the wrong ws/project, and syncing that fails

This is something we cannot fix easily, but the solution is planned and will come sometime down the line.

what users can try is:
- edit TE to different project/workspace (even if it looks right, maybe try to edit forth and back)
- change default workspace in the app to prevent this from happening again
- get access back to that workspace/project and then edit the entry to make it try and sync again
- logout/in to have the app re-download workspaces/projects (THIS WILL DELETE UNSYNCED DATA)

I'm closing this for now. If there are syncing problems that do not fall under what I described, feel free to make new issues.
