### ISSUE TITLE
Edit view: error message UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1271]
- [x] Add the error message at the top of the input fields.
- [x] Allow scrolling if the content doesn't fit on the screen anymore.
- [ ] User can't close or hide the error message.
- [ ] Error message will disappear when the error is fixed (eg user changed the project).

### Error message
![edit error](https://user-images.githubusercontent.com/5064445/34825406-0bb19768-f6db-11e7-94cb-3337cff82d9e.png)

Zeplin: https://zpl.io/be1WR3W

**Comment by kornelijepetak** [comment]
A comment from @amulware 

> yeah, the last can’t be done. the error might not be shown if the entry was edited in any way (since the sync state will be different), and if it fails to sync again, the error will come back. if it does sync, the error wouldn’t be shown

@pe0ny This flow is a bit strange, requires a lot of fiddling with validation, and I am not sure if we can detect that all errors are fixed unless trying to resync the TE and backend validates it.

So, how do you want to proceed? Should we still do what the Toggl iOS does: mark as invalid, dismiss it by clicking the message and wait for another attempt?

**Comment by amulware** [comment]
Note: Syncing with backend is currently the ONLY way to validate, and for the foreseeable future that'll be all we have. Workspace settings like required fields and locked time entries are important, but just not doable right now.

**Comment by pe0ny** [comment]
@kornelijepetak I see. Obviously, we can remove the last point in the list then. And yes, I would go with the iOS way and let user dismiss it by tapping on the error message and waiting for another attempt.
