### ISSUE TITLE
Fix how calendar appears in reports view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1275]
Temporarily we decided to open calendar at the top of the content. Let's fix it now and make it how it should be:
- [x] Calendar expands the header; Content reveals the calendar.
- [x] When user start scrolling down (swipes up), then content covers the calendar and in the end closes it.

**Comment by amulware** [comment]
Check with @willsb and @Odrakir, they had a partial/prototype implementation of this.

**Comment by simonrozsival** [comment]
@willsb or @Odrakir do you still have the code for this prototype somewhere?

**Comment by Odrakir** [comment]
I don't think I do. I sent it to @willsb
