### ISSUE TITLE
Edit view: Limit time entry description

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1283]
- [ ] Limit time entry description to 3000 characters.
- [ ] Display the exceeded number of characters when the limit is exceeded (when users try to enter more than 3000 characters).
- [ ] Disable save button.
- [ ] When a user deletes exceeded characters, remove the number and enable save button again.

### Exceeded number of characters
![edit exceeded chars](https://user-images.githubusercontent.com/5064445/34864529-6b8319e4-f77d-11e7-96bc-51a183ef8781.png)

Zeplin: https://zpl.io/bJO4v4D

**Comment by heytherewill** [comment]
🙅‍♂️
