### ISSUE TITLE
TE creation view: Limit time entry description

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1284]
- [ ] Limit time entry description to 3000 characters.
- [ ] Display the exceeded number of characters when the limit is exceeded (when users try to enter more than 3000 characters).
- [ ] Disable save button.
- [ ] When a user deletes exceeded characters, remove the number and enable save button again.

### Exceeded number of characters
![new time entry exceeded chars](https://user-images.githubusercontent.com/5064445/34865447-7a68eb88-f781-11e7-9d92-9e81c1bdd0ab.png)

Zeplin: https://zpl.io/ag9dryZ

**Comment by willsb** [comment]
So the text view used for the start time entry in Droid will always have only one line, regardless of the text lenght?

**Comment by pe0ny** [comment]
@willsb Nope, and thanks for pointing this out. I'm afraid we don't have a screen for that yet but we'll allow two lines and then text goes smaller. I'll make a new issue for that.

**Comment by amulware** [comment]
🚫
