### ISSUE TITLE
Time entry rivals resolver might have a bug

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1303]
Needs more investigation, but looking over this code: https://github.com/toggl/mobileapp/blob/41e8f0a59066c5952089844ec1df417102361e9b/Toggl.Foundation/Sync/ConflictResolution/TimeEntryRivalsResolver.cs#L31-L43

It seems to me like the stop method is not considering the other time entry, if that one just came in through the API, meaning that the TE might be stopped at the current time, causing an overlap between that one and the other one that is running.

If so, then this should be easily reproducible, testable and fixable.

**Comment by simonrozsival** [comment]
Currently we only search among the TEs that were already written to the database. Which is not entirely correct, as you point out. But if we want to keep this in the same transaction (and I believe we do), then we have a problem with two sets of data: our database (as it was before the transaction was started) and a bunch of TEs we received from the server. There are of course possible conflicts in these two sets of data.

First we do basic conflict resolution ("merging the two sets") and we remember any entities which we downloaded from the server with potential rivals (in our case, at least for now, only a running TE).

Now we have an uncommitted transaction with correct data, but if we would commit, we might, of course, end up with two running TEs which would be "embarrassing". But we would have the best data possible for the rivals' resolution.

We have a list of "results" - for each TE we know if we deleted/created/updated the entity and what is the final version of the TE.

What we should do is to update the above query in such a way that:
- we search the old state of the database (as above)
    - filter out the TEs which are among the deleted TEs
    - look if the start time of the TE wasn't changed and if it was, then we should repeat this to see if there wasn't any better candidate in the DB possibly multiple times
    - look into the results for any created or updated TEs and see if the closest one of these isn't closer than the one we found in the database
- now we have the closest TE and we can determine the stop time (=> duration) of the TE which should be stopped as if we already committed the transaction

Are there any more cases? Is this even correct? Isn't there an easier solution? What do other clients do in this situation?

**Comment by amulware** [comment]
I think the solution above is 'correct', but it is rather complicated indeed. It would probably be simpler to load all realm time entries into memory (as realm objects), do all logic on that collection, and then save them again (which is basically free with closing the transaction?).

No idea about performance though.

**Comment by amulware** [comment]
@simonrozsival this is still a thing, right?
