### ISSUE TITLE
`EntityNotFoundException` when starting multiple time entries quickly

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1306]
Followup of https://github.com/toggl/mobileapp/pull/1304

Happens for both continuing and suggestion-starting, not sure about the start button.

**Comment by simonrozsival** [comment]
Apparently clicking the continue button repeatedly leads to a state when there are now two running TEs in the local database. My theory is that there are two parallel Realm write transactions which both add a running TE and both succeed. I am not 100% sure this is what happens, but I will keep debugging this and make sure we avoid this. Once this happens, the app will crash and it won't work properly anymore (no running TE will be displayed).

**Comment by simonrozsival** [comment]
Interesting - syncing the app _fixes_ this inconsistency (backend probably stopped one of the TEs when pushing and then pulling). So at least it is easy to recover from this state if some user ever experiences this before we fix it/prevent this from happening.

**Comment by simonrozsival** [comment]
I found out that user can "easily" tap the stop button twice with a double tap (the button is still active while it is shrinking) and the second stop, of course, cannot stop anything and it will cause a crash.

I think we should fix this in two different ways:
- introduce some "locking" mechanism into TimeEntriesDataSource to prevent race conditions
- disable buttons for a short period of time once they are clicked so the user can't accidentally click it twice (this could be easily done for the stop button - you can only click this button once and then it must be disabled until a new TE is started

**Comment by amulware** [comment]
Disabling the button (without changing the way it's drawing) while it shouldn't be used makes perfect sense to me.

About the locking mechanism, I'm not really sure. I would like to hear some more specifics and other's opinions.

**Comment by simonrozsival** [comment]
_Specifics_: we do several operations while user stops the TE, starts, updates, ... - we build an entity from a DTO, we make a database operation, we update the internal state of the data source (`long? currentlyRunningTimeEntryId`). This should be a sort of a transaction. We shouldn't run several of these transactions in parallel and each of them should wait until the previous one completes all of its steps. These operations happen quite rarely and they are mostly triggered by some of the user's action (clicking a button, pull-to-refresh).

**Comment by willsb** [comment]
A lock mechanism **in the UI** is the cleanest, most testable and more cross platform solution. A simple implementation of `CanExecute` in the `StopCommand` will fix this.

**Comment by simonrozsival** [comment]
The app still crashes when I try to quickly click the continue button several times in a row.

**Comment by simonrozsival** [comment]
With push sync disabled, this does not happen.

**Comment by amulware** [comment]
Possibly related/overlapping with/duplicated by: #2102 #2103

**Comment by amulware** [comment]
Closed due to inactivity and possible duplicativity.

**Comment by simonrozsival** [comment]
I think this issue is fixed by #2573 although I am not sure if this wasn't a different UI-releated bug (it seems that the UI element had an old (negative) ID assigned to it when the user tapped it even though the ID of the item already changed in the database.

Furiously tapping on the time entry or a suggestion doesn't catch any crashes after the #2573 fix though, so I think we can close this.

**Comment by amulware** [comment]
We'll see if it's still there after the next release.
