### ISSUE TITLE
Improve card dismissal accidentally cancelling changes

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1313]
I've seen at least one user report this, and it just happened to me: I edited a TE, and then closed the card with the X in the top corner, realising too late that my changes would be lost that way.

I think we have to either communicate this better or maybe rethink how we cancel and confirm changes as a whole.

The user suggested that there should be a dialog asking if you mean to discard, and lets you cancel the card-close, but I think that is probably too intrusive and annoying.

**Comment by amulware** [comment]
Comments welcome, decision up to @pe0ny.

**Comment by pe0ny** [comment]
I agree it's an issue. We'll go over all the navigation and save/cancel logic in the upcoming weeks and make a decision.

**Comment by pe0ny** [comment]
I had a discussion with Leez about save/cancel logic and we decided to use the same confirmation dialog that we're using in the Start view to keep it consistent. The same logic will apply to Android.
New issue was made #1612 so I'll close this one.
