### ISSUE TITLE
Reports loader is too big

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1314]
Loader chart should be the same size as a regular pie chart but atm it's way bigger (~2x) and doesn't fit into the screen (Tested with iPhone SE).

**Comment by simonrozsival** [comment]
I can confirm this bug. It shouldn't be hard to fix.

**Comment by simonrozsival** [comment]
A fix was merged into the release branch, this issue should be closed once we merge that branch into develop.

**Comment by amulware** [comment]
Release was merged.
