### ISSUE TITLE
Track successful/failed sync of entities

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1323]
On fail, we should try and include the reason for the failure, but we have to make sure that we do so in an anonymous way. This might need investigation whether we can include the error message returned from backend or not.

Related to #1116

**Comment by simonrozsival** [comment]
Is there something like a list of all possible error messages or is there some way of extracting it from the v9 repo?

**Comment by amulware** [comment]
Not to my knowledge, maybe backend can help.

**Comment by kornelijepetak** [comment]
I had a talk with @amulware and it was decided that we will track:

1) Every entity (workspace, tag, client...) as it's own type for the sake of accuracy
2) Every occurence of an error as an event
3) Every successful sync of a single entity as an event

If at any time we realize there are sending too many of them, we will think about the solution then. Until that happens (if it does), it's more useful to have better numbers from the start.

**Comment by kornelijepetak** [comment]
Also, it seems that backend takes responsibility to make sure that no server response will return any kind of identifying data...
