### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1331]
This needs a list of what exactly is needed to be displayed, and what exactly can be changed. @pe0ny please provide a list ahead of time, since some things might be easier to do than others.

This will also include the respective shared code support for the android settings here: #1268

**Comment by pe0ny** [comment]
* Email (static)
* Name and avatar (user should be able to change those)
* Password (user should be able to change that)
* Default workspace (user should be able to change that)
* Time zone (user should be able to change that)
* Date format (user should be able to change that)
* First day of the week (user should be able to change that)
* Duration display format (user should be able to change that)
* 12/24-hour clock (user should be able to change that)
* Group similar time entries (user should be able to change that)
* Feedback option
* Help (which directs to KB)
* About (which shows version number and directs to about page)
* Sign out option
* Sync indicator

**Comment by amulware** [comment]
That's a lot of things. I'll split it up into multiple issues sometime soon. Please complain if I forget.

**Comment by amulware** [comment]
We can't do all at once, but I edited the issue numbers for individual issues into @pe0ny post. More will come down the line.

**Comment by pe0ny** [comment]
## Design Preview
### Settings
![toggl - ios - settings 1x](https://user-images.githubusercontent.com/5064445/35963676-282b4f80-0cbe-11e8-9b86-50dbb4192b61.png)

Zeplin: https://zpl.io/29EBEz2

**Comment by simonrozsival** [comment]
Ref #1355

**Comment by amulware** [comment]
Closing this big issue. We can make individual ones for anything we're missing in the future.
