### ISSUE TITLE
Prune time entries older than two months

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1333]
By start date. We have to decide if we can do this on every app wake, or only on app wake after a certain amount of time, or only on app start. Maybe doing it on every app wake isn't too bad, if the query is either very fast, or we just do it in the background anyways.

I think this should always be rounded to midnight (i.e. setting hour/minute/second to 0) as the cutoff date, to not have time entries disappear one by one during the day. As such, maybe we can just prune on app activation once per day?

One thing to take into account is what will happen if the app is scrolled all the way to the end of the time entry list as the entries get removed. We have to make sure the user can't continue a time entry just in the moment it gets deleted, causing a crash, or something similar.

**Comment by willsb** [comment]
I say we leverage on the existing midnight observable to run this query.

**Comment by willsb** [comment]
How do we define 2 months? 8 weeks? 60 days?
