### ISSUE TITLE
UI to see projects/clients/tags that failed to sync

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1334]
- [ ] We should try to show meaningful error messages, either those from backend or custom ones
- [ ] The user should be given a hint on how to resolve the issue (for example getting access back to a workspace)
- [ ] Users should be able to RETRY, DELETE(, RENAME?)
- In the future, if we allow projects/tags/clients to be edited, we may want to include the option to 'reset' the change by downloading the entity from backend

Overall, I think this screen should require the user to do a lot manually, but also give them the power to 'fix' their own syncing issues.

There are two different cases that should maybe be handled differently, in terms of what errors/hints to show:
- Actual sync of an entity failed
  - use backend error messages
- We find out that the user lost access to a workspace where they have unsynced entities
  - use custom error message
  - give hint about getting access back to workspace

**Comment by amulware** [comment]
On a related note, time entries affected by any of the cases above should not even try to sync, since that sync is bound to fail. However, if the user manages to fix an issue, the affected time entries should again sync.

Maybe it is worth linking to this screen from the error message shown in such TEs.

**Comment by amulware** [comment]
For now we can go ahead on this without design and hide the screen behind an `#if DEBUG` so we can already start using it for testing. The button for it can be next to the toggl logo or something in the navigation bar on the main view (only visible in debug builds!)

The screen should show all unsynced/unsyncable entities in a list, with a gray 'needs syncing' or red 'sync error' icon, and the sync error string next to that.

The screen does not have to update live but only when opening, and there needs to be a back button leading back to the main view.

**Comment by amulware** [comment]
Entities to show: TEs, clients, projects, tags, user, user preferences (not sure about the latter two, but in principle something could go wrong there)

**Comment by amulware** [comment]
I suggest @Odrakir or @sofokli1 handle this one. :)

**Comment by amulware** [comment]
Also, for the first version of this, we don't need the screen to be interactive yet. Just as long as we can look at the data.

**Comment by Odrakir** [comment]
Any hints on how to get from the DB those entities that failed to sync?

**Comment by amulware** [comment]
Certainly, the relevant models should all have a `SyncState` which you can filter on.

I propose maybe using an interactor for this since that's the hip new thing we're doing now.
