### ISSUE TITLE
Sync archived projects

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1335]
When pulling time entries with unknown project ids, we should create 'temporary'/archived/disabled projects inside realm, that have correct ids, but otherwise no data. That will ensure we don't lose references to projects. We may want to show '(inaccessible project)' in the UI for these.

Then, after pulling those TEs, if we are missing projects, we should fetch those one by one from backend with the single-project endpoint, and if we have access to them persist them in realm, overriding the temporary ones.

From that point on the time entries will be rendered correctly. But we have to make sure not to include those projects in auto completion, etc.

If for some reason we really cannot get the project (I'm not sure if this is possible, might be worth checking with backend), we can continue to use the temporary object and show '(inaccessible project)'.

We have to also figure out how to show this in the edit view when the user tries to edit the project of a time entry with an archived/unknown project.

**Comment by amulware** [comment]
If a time entry shows with an archived projects, it's probably best to render the project name as `My Project (archived)` to be really clear about it, and to better 'explain' to the user why they cannot use the continue button on it for example.

**Comment by amulware** [comment]
Two thoughts:

## Failing Sync
In case sync gets interrupted after storing the dummy projects, it should still try and fetch them next time, so it has to grab the projects to try and fetch from the DB. If a project is entirely inaccessible, this might mean trying to pull it with every pull sync, but not sure what we can do about that. Giving it a flag that we already tried syncing means that if we get access back in the future, we wouldn't notice, which is also bad.

## Realm weirdness
With the way Realm.Get works inside transactions, we might have to persist the fake projects before we insert TEs into the list. I think using two transactions for this should be (strictly logically speaking) fine. I can't think of a way this could fail.

I.e. do something like:

- get list of all project ids of the pulled TEs
- batch update projects to ignore existing projects, and create non-existing ones (as fake/ghost/whatever)
- now persist all TEs, and project ids will resolve fine

**Comment by simonrozsival** [comment]
It should be easy to pull projects, pull time entries, look for the projects that the pulled TEs refer to, look if these projects are either among the pulled projects or in the DB projects, and create ghost entities for those, which don't exist.

In fact, when we persist TEs, the projects are already persisted, so we need to look just into the DB. The easiest way to hammer this into the pull sync flow would be to create a specific state for time entries, which will first make sure that we have all the projects in the DB and then use the regular persist state implementation to do its job.

**Comment by simonrozsival** [comment]
I don't really understand how you mean the weirdness of Realm - we persist project in one transaction and then we persist time entries in a different transaction.

I will try to read it again tomorrow morning when I can focus better. Maybe we can have a call about this and agree on the final way how we will implement this.

**Comment by simonrozsival** [comment]
I would like to have #1993 merged first before writing any new syncing code. Could we maybe move this to the next milestone?

**Comment by amulware** [comment]
Turns out that if we want to, we can pull archived projects with the reports endpoint as well. However, that one can have much higher replication lag (by design). So I think we may still want to fetch them one by one - it should not take much time, since there should rarely be too many(?) - we do pull 8 weeks of TEs now 🤔 

Maybe we can track this? Every time we start pulling archived projects, push an event with the number of projects we have to pull? (or maybe split them into a handful of classes, to have the properly group nicer, like (0, <5, <20, <50, <100, <200, OMG TOO MANY (track exact number in that case as sanity check))

**Comment by simonrozsival** [comment]
I think that having a sync state which will pull ghost projects one-by-one will be "easy". We should add another `SyncStatus` - something like `ReplacingWithActualDataNeeded` and loop over these entities one by one. If sync fails... maybe remember the last time when we tried to fetch them (we could abuse `At`?) and try to fetch them only once per day or something? (we won't need the `At` for anything - we will always override the entity as long as the sync status is `ReplacingWithActualDataNeeded` or something like that.

It would be interesting to track how many entities we pull.

**Comment by simonrozsival** [comment]
All relevant PRs were merged, this issue can now be closed.
