### ISSUE TITLE
Periodically fetch app projects to detect removed/archived ones

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1338]
How often? Not sure. Arguments below. My intuition says every 1-2 weeks (as part of a regular pull sync)? We should ideally decide this with some real data on how often projects get archived, and how long the request takes.

If we detect that a project is missing, but we still have TEs referring to it, we should try and fetch those projects individually to see what's what:

- [ ] Removed projects should also be removed from the app. If TEs refer to these still (not sure if this is possible, needs to be checked with backend), #1337 and issues linked there applies
- [ ] Archived projects can simply be marked as archived locally as well, sot hat the app behaves appropriately. The removal-when-no-references-anymore from #1337 still applies though.

Also see #1335

**Comment by simonrozsival** [comment]
We could use the `https://toggl.com/api/v9/workspaces/{wid}/projects?actual_hours=true&active=false&client_ids=&group_ids=&user_ids={uid}&billable=both&page=1&force=false` endpoint, which Snowball uses on the project page.
