### ISSUE TITLE
TE creation view: allow two lines

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1345]
- [ ] Allow two lines when a user enters a longer description.
- [ ] Decrease the font size.

### TE creation view: two lines
![new time entry two lines](https://user-images.githubusercontent.com/5064445/35429759-171e0cfe-027e-11e8-9706-f132d62548cb.png)

Zeplin: https://zpl.io/bzyzyrE

**Comment by amulware** [comment]
@pe0ny What happens if the user enters too much for two lines?

**Comment by lizaPlotnikova** [comment]
@pe0ny and @amulware, the description field in TE Creation should behave the same way as in Edit 

- the description field has a max height (108dp)
- if the text exceeds that max height it begins to scroll within the field (currently there's no scroll bar element implemented, but I think we should implement that)

One thing that we haven't done yet, that was mocked up in the original design, was to enforce the character limit in the UI. 

To prevent the user trying to save a description over 3000chars:
- show how many characters over the limit the current input is
- and disable the Save button, until excess characters are deleted

Here's the mockup:
<img width="378" alt="screen shot 2018-07-03 at 11 20 27 am" src="https://user-images.githubusercontent.com/24964497/42228927-308e0674-7eb3-11e8-9850-e11f8ad6cce1.png">

https://zpl.io/a3xE6Py

**Comment by amulware** [comment]
Not gonna happen for now. We'll revisit this in future designs and when we make edit/start more similar.

⛔️
