### ISSUE TITLE
Make start button tappable area larger

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1348]
It has occurred to me a couple of times now that I just missed the start button and then continued an entry right behind it. I think we should consider making the button have a larger tappable area around it. Certainly, it should not be possible to tap anything else to the bottom/right of it I think.

**Comment by amulware** [comment]
Ref #1485

**Comment by khoi** [comment]
This should make a good first PR for me. Let me grab this 🙇

**Comment by khoi** [comment]
Oh wait, I've just realized that I only made the changes for iOS.

**Comment by kornelijepetak** [comment]
@amulware this may also be an issue on Android. I have turned on layout bounds debugging and indeed, tapping anything outside of immediate FAB's bounding box is registered as a tap to whatever is in the background. If it should be done also on Android, please open an issue or add a label to this one. In the latter case, @khoi should not `Close` this issue automatically by referencing it in his #2427

**Comment by amulware** [comment]
We're working to have separate issues for android and ios things, so yes, this can be closed. :+1:
