### ISSUE TITLE
Use user settings for formatting times and dates

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1349]
We may want to cache this or something for performance when rendering time entries, etc.?

The setting should be respected everywhere in the app. Maybe a list should be made.

**Comment by simonrozsival** [comment]
These are the places where we display a time (not duration) I am aware of:

- The edit time entry view (start time, in the future maybe the stop time)
- ~The duration view~
- The wheel view (start and stop time + the date picker)
- The select start time view (date picker)

All of these places show the date and time side by side (e.g., "Mon, 22 Jan 16:00").

**Comment by simonrozsival** [comment]
Dates are also shown in the headers of the time entries log.

**Comment by simonrozsival** [comment]
Technically, what we need to do is to inject the user's settings into the `DateToTitleStringValueConverter` class and the `DateTimeToTimeValueConverter` class.

Both of these have the formats hardcoded in: `$"{value:ddd, dd MMM}"` and `.ToString("HH:mm")` respectively.

**Comment by simonrozsival** [comment]
☝️ this means that we don't need two tasks for this - all of the code will be shared by the platforms.
