### ISSUE TITLE
Use user settings for formatting times and dates

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1350]
Same as #1349 but for 🤖

**Comment by simonrozsival** [comment]
In the iOS app we have two converters which should do this but both of them are in the Daneel project. We should move them into Foundation.MvvmCross to make them cross-platform (there is no and there is even no reason to be any platform-specific code in either of the classes) to make them available to Android.

**Comment by amulware** [comment]
Closing this in favour of #1349 then.
