### ISSUE TITLE
Bring back bouncing in scroll views

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#1355]
Make iOS users happy and let the scroll views bounce freely.

That includes the bottom of the timeline, the reports page and the whole settings page.

The pull to refresh should also stretch freely and not get stuck as it does now.

- [X] Main view (with stretching pull-to-refresh)
- [X] Reports
- [ ] Settings
- [x] Start time entry suggestions
- [x] Project list
- [x] Workspace list
- [x] Tags list
- [x] Clients list
- [X] EditView
- [x] Onboarding

**Comment by willsb** [comment]
Please note that there are more scroll view that need bouncytty bouncy treatment:

- Start time entry suggestions
- Project list
- Workspace list
- Tags list
- EditView (not sure about this one)
- *Maybe* the onboarding process (@Odrakir can correct me here, I'm not an iOS user)
