### ISSUE TITLE
Start/end/duration view: numpad

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1362]
- [x] Tapping on a duration, opens numpad.
- [x] When the numpad is open, allow users to add hours and minutes.
- [x] Tapping outside the numpad closes it and saves what user typed in.
- [x] When user didn't type anything and closes the numpad, keep the previous duration.

### Wheel view - Numpad:
![toggl - ios - startendtimes - numpad 1x](https://user-images.githubusercontent.com/5064445/35508926-ed586d18-04fa-11e8-9d09-ceadaf9edf19.png)

Zeplin: https://zpl.io/2pxWzON

**Comment by amulware** [comment]
1) Does the wheel and the end time adjust as the user types?

2) Do the numbers the user type move to the left as follows?

- user types '3' -> 00:03
- user types '4' -> 00:34
- user types '1' -> 03:41
- user types '2' -> 34:12

3) Do we allow for more than 99 hours to be entered? (I'd say no, just don't allow more than 4 digits, or cut off the front most digit)

4) Before the user starts typing, should it maybe show the original duration in faint gray as placeholder?

**Comment by simonrozsival** [comment]
@amulware I think we should be able to display three digit hour values - we might pull some from the server.

**Comment by amulware** [comment]
Display sure, but entering?

**Comment by simonrozsival** [comment]
If we can display it, why shouldn't we allow entering it?

**Comment by simonrozsival** [comment]
If the user wants to do so then he (probably) knows what he's doing.

**Comment by amulware** [comment]
Maybe..

**Comment by pe0ny** [comment]
To sum up our discussion in slack:
We display always 2 zeros (for hours) but allow users to enter more if they want to. For example:
When I have typed in: ‘02:00’ and I'll add '2', then it will be '20:02' and if one more: '200:23'.

**Comment by simonrozsival** [comment]
- I am not 100% sure how the cursor should work: should it always be visible after the last zero, as it is in the screenshot?
- When I've entered '200:23' and I press another key, say 5, should it ignore it, or should it go to '02:35'?
- Paul already asked in Slack I think, but just to be sure: when user inputs '12:89', it will be converted into '13:29'
    - when user inputs > 999 h (e.g., '999:12', '998:61') it will be changed into '999:00', right?
- when user presses backspace, everything will shift to the right and the last digit will be forgotten?

**Comment by amulware** [comment]
- I think the cursor would always be after the last zero, yeah
- probably ignore?
- q: change to 999 maximum in place or after saving?
- yes

**Comment by amulware** [comment]
the rest is for @pe0ny

**Comment by pe0ny** [comment]
1) Yes, cursor should always be after the last zero
2) Ignore
3) Yes, and change to 999 after user taps outside the numpad/saves duration
4) Yes

**Comment by simonrozsival** [comment]
> When user didn't type anything and closes the numpad, keep the previous duration.

When user taps the duration, should it be always reset to zero so he enters the whole duration from scratch, or should it prefill it with the previous duration (maybe at the time of tapping it for running TEs) so user can edit it (add more digits, backspace ("pop") old digits)?

From the specification, I think it should be the first option (showing zeros and if there is no input, discard it), but I am not 100% sure I get it right.

Also, there is really no way of discarding the whole thing? I think some "cancel" button would be useful when the implicit behavior is to save the edited changes.

One last edge case I can think of: pressing backspace enough times to reset the input ("00:00") and then dismissing the keyboard ("saving") should be the same as not touching the input at all or should it set the duration to zero? The first option gives the user the option to change his/her mind about editing the duration (when there is not cancel button), the other makes it possible to enter zero duration, but in a weird way (input something "123", hit backspace enough times to make it "00:00", "save").

**Comment by pe0ny** [comment]
@simonrozsival 

> When user taps the duration, should it be always reset to zero so he enters the whole duration from scratch

Yes.

> One last edge case I can think of: pressing backspace enough times to reset the input ("00:00") and then dismissing the keyboard ("saving") should be the same as not touching the input at all or should it set the duration to zero?

I would say it should be the first one - as not touching the input at all.
