### ISSUE TITLE
TE creation view: UI updates

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1363]
- [x] Add calendar icon which opens calendar barrel (start date) in a popup.
- [x] Clock icon opens the wheel view. 
- [ ] Add icon and background to the duration.
- [x] Tapping on duration, opens numpad. #1364

### TE creation view
![toggl - ios - running entry 1x](https://user-images.githubusercontent.com/5064445/35509520-1123b732-04fd-11e8-8635-c99fca043ba1.png)

Zeplin: https://zpl.io/25e53nJ

Calendar icon can be found here: https://zpl.io/25EAOe2

**Comment by simonrozsival** [comment]
Question: the calendar barrel popup should change just the date, but not to change time, right?

**Comment by amulware** [comment]
Yes.
