### ISSUE TITLE
TE creation view for manual entry

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1365]
We'll have two TE creation views: one for timer and one for manual mode.

- [ ] Trigger TE creation view for manual entry when a user has set so in the settings.
- [ ] Do not start the timer.
- [x] Set default duration value for 30min.
- [x] Change description placeholder to "What have you done?".

### TE creation view: manual entry
![toggl - ios - manual entry 1x](https://user-images.githubusercontent.com/5064445/35512002-d636d6a4-0506-11e8-8be6-d9202bc2cbf6.png)

Zeplin: https://zpl.io/2jkOBmm

**Comment by simonrozsival** [comment]
What should be the default start time? Now or 30 minutes in the past or something completely different?

**Comment by pe0ny** [comment]
@simonrozsival End time should be now and start should be 30min in the past.
