### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1397]
- [x] Use datepicker to set a start date.
- [x] User can access datepicker from:
a) Edit view
b) TE creation view (from timer and manual mode)

### Datepicker
![toggl - ios - date 1x](https://user-images.githubusercontent.com/5064445/35632252-d1b66afa-06ae-11e8-8aa4-3c5ac5902a26.png)

Zeplin: https://zpl.io/bzylKeE

**Comment by willsb** [comment]
To whoever works on this: Please ping either me or @kornelijepetak before starting work so we can sync iOS and Android

**Comment by simonrozsival** [comment]
@kornelijepetak is currently working on the view model, so I will wait until he finishes his work there and adjust it for iOS.
