### ISSUE TITLE
Incorrect Billable total on Reports

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#1399]
case/632454:

For a week user logged time in only one Project, with all entries marked as Billable.

However, when viewing "This Week" on the iOS app's Reports, the Billable percentage only goes up to "62.51%".

Screenshots in case.

**Comment by amulware** [comment]
Asked for more details internally. As this stands it's either a user error or an error in the endpoint.

**Comment by ricotheque** [comment]
Double-checked the entries in staging, and all have been marked as billable.

**Comment by amulware** [comment]
Haven't had other reports of this. Assuming fixed of single case.
