### ISSUE TITLE
Add haptic feedback to the iOS app

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1400]
This is a minor feature I want to add - many other iOS apps (facebook, twitter, ...) have this kind of feedback for the pull-to-refresh gesture where the user gets a light vibration when he can stop pulling and the app will refresh. I think it makes the app feel a lot better.

I added a PR with an implementation and it can be used in the future for reference: #1305 

There are also probably many other places where this kind of feedback makes sense and would be a nice touch (e.g., pressing the start or stop buttons) and it might be worth it to go through the app and find some more.

**Comment by amulware** [comment]
Agreed, but this issue isn't specific enough. Let's keep it in mind in the eventual rewrite of the syncing notification bar thing.
