### ISSUE TITLE
Cancel login/sync on BACK

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1411]
Basically, if the user uses the hardware back button during the login/initial sync we need to cancel all that and return back to the login screen.

To make sure that no data is persisted, and won't be persisted asynchronously, we should call the regular logout which makes sure to freeze the syncing and cleans the database.

**Comment by willsb** [comment]
Ref #1207

**Comment by amulware** [comment]
@kornelijepetak Is this being taken care of in your login/signup flow changes?

**Comment by amulware** [comment]
Assigned to project, so it'll get done as part of that if still necessary.

**Comment by kornelijepetak** [comment]
🔑 project was somewhat abandoned, so it's still something to do.
