### ISSUE TITLE
Changing start date in the edit view can cause negative duration

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1440]
There is a problem with validation - when I set some time in the future as a start time, I can get negative duration (end time doesn't change, but also isn't used as the max value for the picker).

**Comment by amulware** [comment]
For stopped entries, changing the start date should keep the duration the same.

For running entries, the start date should never be allowed to be in the future.

Case to be solved:
- time entry is running, with start date in the past, and start TIME > local time of current dat
- start date is set to 'today'
-> leads to negative duration

Proposed solution: do not allow 'today' in that case.

Alternatively: change start TIME in that case, but that sounds like a bad idea.

**Comment by simonrozsival** [comment]
Also, I believe that for stopped time entries the minimum date should be (stop - 999 hours), as usual, right?

**Comment by amulware** [comment]
I don't think so. Since the stop time changes (duration stays the same) there should be no minimum start date, except the 2006 one.

**Comment by simonrozsival** [comment]
Oh I see, I need more ☕️... Thanks!

**Comment by simonrozsival** [comment]
This was already merged to the release branch.
