### ISSUE TITLE
Device type detection fails

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1441]
The prefilled information in the feedbac email is incorrect. For my iPhone 7 it says “Failed to detect phone model”.

This might be possible to fix after i bit of a debugging, but I would suggest to include the model type onlywhen we can detect it and skip it if we can’t. It doesn’t look good...

**Comment by simonrozsival** [comment]
@pe0ny @amulware What do you think about not displaying the model name if we can't detect it? Is that a good idea or a bad idea or what kind of an idea is it? :)

**Comment by pe0ny** [comment]
I think it makes sense not to display it if we can't detect it :)
