### ISSUE TITLE
Syncing gets stuck when the device is disconnected from the internet during sync

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1443]
I will continue testing and I will provide more information tomorrow.

**Comment by simonrozsival** [comment]
This might not be a bug. It just takes a very long time for the request to fail when the device was previously online but is now disconnected.

We don't specify the timeout for the request ourselves, so probably some default value is used. I'm not sure if it is wise to pick some arbitrary number (like 30 seconds) and use that as the timeout - on some bad networks downloading a lot of data might take that much time (e.g., downloading 1 MB over EDGE takes at least 21 seconds when the max speed of 384 kbit/s is reached, but I didn't read the documentation very thoroughly and I am not sure how exactly is the timeout applied and it won't throw while data is already being downloaded).

Also with bad signal reception, the request might be repeated a few times before the device decides to give up and throw an exception 🤷‍♂️ I am not able to reproduce a state where it won't eventually finish and show "Offline" in the status bar.

What is a pity is that we process the requests in a given order - I can see in the debugger that some of the requests fail really soon after the request was sent (because of being offline), but the one which is awaited first (workspace) takes tens of seconds. If we know other requests failed, then we could throw right away and it won't seem as though it is deadlocked.

**Comment by amulware** [comment]
Don't see us doing anything about this any time soon.
