### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1450]
Part of #1331

- [x] Privacy Policy: https://toggl.com/legal/privacy
- [x] Terms of Service: https://toggl.com/legal/terms
- [x] Licenses #1172

### About page
![toggl - ios - about 1x](https://user-images.githubusercontent.com/5064445/35963844-ba875130-0cbe-11e8-8afb-32cae3507203.png)

Zeplin: https://zpl.io/aN4Z9Ad

**Comment by dshr** [comment]
@pe0ny Do the privacy policy and ToS links lead to a native view with the content from the link, to a WebView pointing to those pages or do they take the user to Safari altogether?

**Comment by dshr** [comment]
@pe0ny can't seem to find anything related to the Help page in the code 😞. Do we have some mockups for it that I can use for guidance?
