### ISSUE TITLE
Wheel view UI updates

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1455]
- [ ] Do not to use a full-screen view instead, the view’s height should depend on the content - like the edit view.
- [x] When user taps on the duration, the view should move up to make a room for the keyboard.

### Wheel view
![toggl - ios - wheel 1x](https://user-images.githubusercontent.com/5064445/35971052-2e6fcac6-0cd5-11e8-8948-7bceb3219aae.png) ![toggl - ios - wheel - duration edit 1x](https://user-images.githubusercontent.com/5064445/35971056-3062809e-0cd5-11e8-83ce-74c801f30015.png)

Zeplin: https://zpl.io/aRNr8Q0

**Comment by simonrozsival** [comment]
This was merged into the release branch.
