### ISSUE TITLE
App freezes when starting or continuing TE

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1468]
What the title says.

**Comment by simonrozsival** [comment]
It works in the development build, doesn't work in the production build - maybe linker issues?

**Comment by simonrozsival** [comment]
... or maybe it is the Firebase Analytics event logging?

**Comment by pe0ny** [comment]
App also freezes when starting a new entry (after tapping a green checkmark in the start view), not only when continuing.
After restarting the app, the started time entry is still running but tapping on it to open, also freezes the app.

**Comment by amulware** [comment]
Adhoc/Appstore have the same build settings when it comes to the linker, etc. so that SHOULD not be the issue. Unless it's something about linking the analytics service, but I can't see why that would be a problem.

So that's bad.

**Comment by simonrozsival** [comment]
This was resolved by removing Firebase crash reporting from the solution. Should we close this?

**Comment by amulware** [comment]
Let's do so.
