### ISSUE TITLE
Refactor abstract base test classes for integration tests

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#147]
Different HTTP methods should be tested in a different way as the actions have incompatible results - especially when the same action is repeated, some examples:

- POSTing the same named entity twice should fail to prevent duplicates
- GETting the same entity twice should get the same thing twice
- DELETE requests can't delete the same thing twice

The base tests for authentication must take this into account.

**Comment by amulware** [comment]
This was closed by #151, correct? If so, please close this issue.
