### ISSUE TITLE
Grouped projects/tags/clients from the default workspace should be displayed first

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1472]
... and all the other workspaces under it in some order (currently arbitrary, maybe it could be alphabetically by the name of the workspace?).

This is a suggestion for organizing the groups of tags/projects/clients in the selection views - I find it very inconvenient that I have to scroll down to look for the projects I use the most, which are obviously (?) in the default workspace.

Please consider this, @pe0ny and @amulware.

**Comment by pe0ny** [comment]
@simonrozsival Do you mean the start view -> projects and tags views or projects and tags view which opens from the edit view?
In both cases, we group projects and tags by workspaces. Though, I think you are correct that currently those groups are ordered arbitrary. Default WS group should always be at the top.
What part of it needs design, though?

**Comment by simonrozsival** [comment]
Yes, that is what I mean.

The label is misleading, it should have been something else - I just wanted confirmation that this issue makes sense and we should implement it at some point.
