### ISSUE TITLE
Tapping continue button too quickly leads to a crash

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1474]
Tapping the continue button too many times too fast causes problems with updating the time entries log.

```
Unhandled Exception:
Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInternalInconsistencyException Reason: Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (264) must be equal to the number of rows contained in that section before the update (262), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).
Native stack trace:
...
```

Until #1306 is fixed, disable push sync after continuing a TE to reproduce this.

**Comment by simonrozsival** [comment]
We should wait for #1484 to be merged before we start working on fixing this bug. Crash log in app center: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/e17dd28fc0b2d62e4cbb3b78e654efc33e65ba5e

**Comment by simonrozsival** [comment]
I wasn’t able to reproduce this offline, it only happens when I am online. This leads to my hypothesis that the problem is with the conflict resolution of rivals - tapping the continue button repeatedly with the push sync running in background, we end up with two running TEs.

**Comment by amulware** [comment]
Closing as out-of-date.
