### ISSUE TITLE
App crashes in the Start view

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1483]
How to reproduce:
- start a new time entry
- tap the tags or projects button
- select a tag/project
- tap the tags or projects button
- app crashes

Entering everything using @ and # shortcuts works well though.

**Comment by ApocalypticFish** [comment]
Confirmed, can replicate.

**Comment by ricotheque** [comment]
Confirmed for /case/643665

**Comment by ricotheque** [comment]
Confirmed for /case/640544

**Comment by ricotheque** [comment]
Confirmed for /case/643681

**Comment by amulware** [comment]
Merged into hotfix branch. Will be released later today.

**Comment by ricotheque** [comment]
FWIW, this user has found a workaround: save before adding tags

https://twitter.com/kathylamotte/status/963544739520897024
