### ISSUE TITLE
Include more details with exceptions thrown by Realm

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1487]
https://github.com/toggl/mobileapp/blob/develop/Toggl.PrimeRadiant.Realm/BaseStorage.cs#L58

Right now we replace `InvalidOperationException` with `EntityNotFoundException`, losing all additional data. It would be great if we can get some idea of what exceptions we might be getting, and how we could include more information.

In all cases, we have to make sure that we do **not** include user data **under any circumstances**.

**Comment by simonrozsival** [comment]
I understand https://realm.io/docs/dotnet/latest/#crash-reporting  in such way that the user data won't be in the exception message. Our  crash reporting tools only show the stack trace and the message of the  exception - no data should be exposed if we use the message from the  realm exception.
