### ISSUE TITLE
Status bar for pre-marshmallow devices

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1494]
- [ ] For pre-marshmallow devices use a dark status bar for all the views to make sure icons on the status bar will stand out.

### Dark status bar
![edit](https://user-images.githubusercontent.com/5064445/36139994-58b7e472-10a8-11e8-8793-1df5cc413fc0.png)

Zeplin: https://zpl.io/VQWoZKn

**Comment by kornelijepetak** [comment]
Ref #1425

**Comment by daividssilverio** [comment]
Even for when we have blue toolbars? they notifications icons are visible on the bluish background. @pe0ny

**Comment by daividssilverio** [comment]
Look: 
<img src="https://user-images.githubusercontent.com/2173493/41320088-5a802bd0-6e6c-11e8-8eee-10efbb12631c.png" width=240/>

**Comment by lizaPlotnikova** [comment]
The constraint is that in pre-marshmallow is that the status bar icons have to be white. 

So, for pre-mallow versions let's do this:
1) When toolbar color is blue, set status bar color to blue (i.e. the screenshot above looks fine)
2) when toolbar color is white, set status bar color to black (i.e. as in the mockup above)
3) when toolbar color is (near) black, set status bar color to black (i.e. same as in the post-mallow version)
