### ISSUE TITLE
Manual mode new time entry screen description field not fully tappable for pasting

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#1496]
User submitted video recording of the issue available in case/643765. 

In manual mode, when user is opening the insert time entry screen and wants to paste a TE description, it is difficult for them to do so. 
Select/copy/paste menu appears only when tapping on the | selector or on text when there's any text to tap on. 
The field itself does not seem to be tappable, which makes it difficult to paste a TE description when the field is empty. 

Haven't come across the same issue on any other screens so far, for example on TE edit screen or when adding new tags. 

User's iPhone Model is 6S, I have also tested with 7. User reported that the same issue persisted when I switched to English keyboard.

**Comment by simonrozsival** [comment]
This was already merged into a hotfix branch.
