### ISSUE TITLE
Improve API error return value

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#150]
Right now we are returning pretty useless exceptions with the http content of the response as message.

Soon we will also need _at least_ the http error code, for both the status endpoint, and all other endpoints as well.

**Comment by willsb** [comment]
The whole idea is that `ApiException` must be extended, as needed, to provide more meaningful data. Similar to what is being done Prime Radiant

**Comment by amulware** [comment]
I'm ok with that implementation. :+1:

**Comment by amulware** [comment]
Ref #306
