### ISSUE TITLE
Track failures/exceptions during sync

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1507]
This covers everything not covered already in #1323, #1116

I want to make sure we report all 400 and 500 errors that are not already covered by the above, just so that we get an idea of how many of them happen.

**Comment by amulware** [comment]
This might need an investigation about what and how we track things already, and what/how to add.

As part of this, I'd also like to see internal documentation of what exactly we track about sync.

**Comment by dshr** [comment]
What we track as of now:
- Sync operation start `SyncOperationStarted`, with operation type
- Every state transition `SyncStateTransition`, with state name
- When we detect offline mode `OfflineModeDetected`
- An entity gets synced `EntitySynced`, noting whether it was create, updated or deleted and the entity type
- Every entity sync status change `EntitySyncStatus`, with the entity type
- Entities inaccessible after cleanup, with the number of inaccessible entities:
    - Tags: `TagsInaccesibleAfterCleanUp`
    - Time entries: `TimeEntriesInaccesibleAfterCleanUp`
    - Tasks: `TasksInaccesibleAfterCleanUp`
    - Clients: `ClientsInaccesibleAfterCleanUp`
    - Projects: `ProjectsInaccesibleAfterCleanUp`
    - Workspaces: `WorkspacesInaccesibleAfterCleanUp`
- When project placeholders get created `ProjectPlaceholdersCreated`, with the number of placeholders
- Whenever a user gains access to a new workspace `GainWorkspaceAccess`, 
- Whenever a user loses access to a workspace `LostWorkspaceAccess`
- Whenever a user has no default workspace `NoDefaultWorkspace`
- Leaky bucket overflows `LeakyBucketOverflow`, 
- Any time we get a rate limiting delay `RateLimitingDelayDuringSyncing`, with the total time in seconds
- All sync errors `SyncFailed`, with the name, message and stacktrace of the error
