### ISSUE TITLE
Hotspot banner overlaps the upper part of the app

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#1509]
Hotspot banner overlaps the upper part of the iOS app, v1.3.1
![img_0065](https://user-images.githubusercontent.com/35216651/36194661-42a18e38-1173-11e8-86d4-a2e845671f39.PNG)

**Comment by amulware** [comment]
The same probably happens with calls and other things that pop up there.

**Comment by simonrozsival** [comment]
This issue was already fixed and does not happen in 1.9.
