### ISSUE TITLE
Rename classes which changed their purpose

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1514]
We should change the name of at least these two views:

- Edit duration view (`EditDurationViewModel`, `EditDurationViewController`) is now the "wheel view" on iOS and it does not change just the duration, but also the start time and the stop/end time
- Start time entry view (`StartTimeEntryViewModel`, `StartTimeEntryViewController`) is now used for starting a new TE and also for creating a new stopped time entry when in the manual mode. It should be renamed to `CreateTimeEntry*`

If there are other classes that should be renamed, please add them to the list or mention them in the comments.

**Comment by amulware** [comment]
Old. Also, let's have either specific issues, or just do things like this without issue.
