### ISSUE TITLE
[onboarding] phase 1: TE create view

### ISSUE THREAD

**Issue by fonorobert** [toggl/mobileapp#1519]
Phase 1 of onboarding flow.
Phase 2: #1520 
Phase 3: #1521 
Phase 4: #1522 

Add:

- [x] tooltip for start button in log view
- [x] modified TE create view
- [x] modified checkmark button in TE create view
- [x] tooltip for stop button in log view

**Only show this phase to users that are new users and signed up in the app!**

# Steps & designs
## 1. Tooltip in log view pointing user to start button
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a8301c783a1a15b4f6e5f6f
![screenshot from 2018-02-14 13-41-02](https://user-images.githubusercontent.com/6963710/36208034-0412cd60-1198-11e8-8593-74cf3587321d.png)

**Show:**
- when user first signs up and sees log view

**Hide:**
- If user has tapped the tooltip to dismiss it
- If user tapped the start button.

Copy: “Tap to start timer”

## 2. New TE view, once user taps “start” for the first time
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a84129c0bcd0643489d675a

![screenshot from 2018-02-14 13-42-48](https://user-images.githubusercontent.com/6963710/36208069-1d995b5a-1198-11e8-8309-894829a430db.png)

Secondary input fields for project and tag adding are removed.
Checkmark button in bottom right is greyed out.

**Show:**
- first time the user starts a TE in the app

## 3. Checkmark button highlighted
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a84129b74b47303abb16429
![screenshot from 2018-02-14 13-46-28](https://user-images.githubusercontent.com/6963710/36208082-29e8bc66-1198-11e8-9c0c-abe237ef3bcb.png)

Checkmark is white, green solid circle around it.

**Show:**
- After step 2, when user starts typing in description field

## 4. Second tooltip in log view pointing to stop button
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a8301c63467b6111e837b8d
![screenshot from 2018-02-14 13-48-00](https://user-images.githubusercontent.com/6963710/36208091-339cd27e-1198-11e8-907a-55bf3085f8bb.png)

**Show:**
- After step 3
- first time user has a running TE in the app

**Hide:**
- If user has tapped the tooltip to dismiss it
- If user tapped the stop button.

**Comment by fonorobert** [comment]
Updated to specify that this phase should only be shown to new users that signed up in the app, not existing Toggl users that logged in.

**Comment by pe0ny** [comment]
Some notes from my side:
**In step 2:** When the save button (checkmark) is grey, it is not disabled, meaning in principle user can still tap on it to save. We just want to emphasize the importance of the save button.
It will be grey only first time when a user opens the start view. Other times there will be a green circle with a white checkmark.

**Comment by amulware** [comment]
On a technical note for whoever is going to work on this: I want this stuff tied to the actual UI as little as possible, and the code for it should be in as few places as possible, not scattered all around the app. Also, I want all storage to be platform specific only, not shared (well, there might be a shared interface for general storage, but I don't want specific keys and methods in foundation); the two apps might have different onboarding and triggers, and we shouldn't have that in shared code.

**Comment by simonrozsival** [comment]
Question:
- user signs up in the app, we show him the "Tap to start timer" tooltip
- user taps on the tooltip and dismisses it
- user logs out
- user signs up in the app (same device, no uninstall, potentially months later) 
- **should we now show the tooltip again?**

**Comment by fonorobert** [comment]
i'd say yes, i think on a new login/signup onboarding should start over regardless if it was already shown on this device

**Comment by simonrozsival** [comment]
Will there be any animations for showing and hiding the tooltips?

**Comment by simonrozsival** [comment]
Question for steps 2/3: when the user types something and the green checkmark is shown and then the user deletes the description, should it show the checkmark as gray again (it is also slightly easier to implement it this way :D)?

**Comment by fonorobert** [comment]
late to the party a bit but yeah, i think it's ok if the checkmark goes back to grey

**Comment by pe0ny** [comment]
@simonrozsival 
Q1: Yes, like Robert said.
Tooltip animation: #1538
Q3: Yes, it's ok.

**Comment by simonrozsival** [comment]
All the steps were implemented and merged, the animations will be handled separately as they have their own issue. I am closing this now.
