### ISSUE TITLE
[onboarding] phase 2: edit view

### ISSUE THREAD

**Issue by fonorobert** [toggl/mobileapp#1520]
Phase 2 of onboarding flow.

Phase 1: #1519 
Phase 3: #1521 
Phase 4: #1522 

Add:
- [x] tooltip pointing to TE in log view
- [x] tooltip pointing to project field in edit view

**Only show this phase to users that are new users and signed up in the app!**

# Steps & designs
## 1. Tooltip prompting to edit
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a83017e7f9525902f5dbee4

![screenshot from 2018-02-14 13-49-36](https://user-images.githubusercontent.com/6963710/36208315-fac30dbe-1198-11e8-9496-fe40f536bed8.png)

Copy: 
“You’ve created your first time entry 🙌
Tap to edit it”
Points to topmost TE (the one user just created in phase 1 - #1519 )

**Show:**
- once user has at least one saved (stopped) TE

**Hide:**
- If user taps the tooltip to dismiss it
- If user opens editing view
- If user navigates to another view (reports, new TE, settings, etc.)

## 2. Project field tooltip in TE edit view
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a83017be88dfaa2682860b6

![screenshot from 2018-02-14 15-09-12](https://user-images.githubusercontent.com/6963710/36208364-1c440fa6-1199-11e8-9a71-7b61916df548.png)

Copy: “Categorize your time with projects”

**Show:**
- First time when entering edit view

**Hide:**
- If TE being edited has a project assigned
- If user taps tooltip to dismiss it
- If user taps project field

**Comment by fonorobert** [comment]
Updated to specify that this phase should only be shown to new users that signed up in the app, not existing Toggl users that logged in.

**Comment by pe0ny** [comment]
@fonorobert In step2: We should also hide it when user taps on the project field, right (users don't have to assign a project but we should hide it when they already tap on that field)? Also, you said:
> Hide: If TE being edited has a project or tag assigned

I believe you meant if Te as **a project** assigned? Tags don't matter at this point because we're focusing on projects only?

**Comment by fonorobert** [comment]
@pe0ny correct on both points, updated :)

**Comment by simonrozsival** [comment]
@fonorobert `once the user has at least one saved (stopped) TE` - shouldn't this be rather `once the user stops the first time entry`? What if the user then pulls more TEs from the server? He/she won't tap the TE, won't dismiss the tooltip, won't navigate to a different view. Should we hide it then?

**Comment by fonorobert** [comment]
on the first point i'd say it does make sense to make it `once user stops first TE in app`, let's see if @pe0ny agrees as well :)

if there are TEs pulled from the server, i'd say keep showing the tooltip until they do something else in the app. (starting a new TE eg. would count as navigating to a different view, correct?) in that case it should "stick" to the TE it's on initially

**Comment by amulware** [comment]
Should have been closed for 19 days already. Oh well.
