### ISSUE TITLE
[onboarding] phase 4: gestures

### ISSUE THREAD

**Issue by fonorobert** [toggl/mobileapp#1522]
Phase 4 of onboarding flow.

Phase 1: #1519 
Phase 2: #1520 
Phase 3: #1521 

Showcases continue and delete gestures.

Add:
- [x] animation for continue gesture
- [x] tooltip for continue gesture
- [x] animation for delete gesture
- [x] tooltip for delete gesture

# Design
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a83017c94d98154382ff899
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5a83017c83c07a9d141a5510

     
![screenshot from 2018-02-14 14-53-04](https://user-images.githubusercontent.com/6963710/36208957-b6664e54-119a-11e8-8c13-41d46b74dbaa.png)
    
    
![screenshot from 2018-02-14 14-53-23](https://user-images.githubusercontent.com/6963710/36208961-b975d57e-119a-11e8-8a15-130157ce6671.png)

Copy:
“Swipe right to continue”
“Swipe left to delete”

Animate swipe on a single TE
(show swipe animation one way, display tooltip, once dismissed show swipe animation the other way with the other tooltip)
(both continue and delete showcased on the same TE)
Show on topmost TE that has a project or a description or both

**Show:**
- once user has at least 5 TEs tracked

**Comment by kornelijepetak** [comment]
I believe a tooltip should show after say 5 TEs tracked saying something like: `You can swipe to continue or delete`. Otherwise, these would appear only if user actually swipes (some users only by accident). If one never tries swiping they would never know...

**Comment by fonorobert** [comment]
The idea here was to show the animation without the user actually swiping. Sorry if that didn't come through :(

**Comment by kornelijepetak** [comment]
All is well. The screens are somewhat misleading cause they show as if swiping has already been done.

**Comment by amulware** [comment]
Will this show the animation and then stop there with the tooltip open? That seems somewhat disruptive. Not to mention that the tooltip doesn't add much I think, it just repeats what the user can already see.

I think it would be enough to quickly animate the entry moving left and right, revealing the red/green area just partially, just to indicate to the user 'there is something here to do', and let them figure it out. I know of several apps that do this, and I think it's clear enough.

And in fact, I would play that animation not just once, but maybe up to once a week, if the user has not used either of the two gestures for 1 or 2 weeks to remind them.

**Comment by fonorobert** [comment]
@amulware the original idea was to only show the animation like you suggested. We ended up on the current version because while it is indeed more disruptive, they remove the potential for confusion. Otherwise users not as familiar with this way of showcasing gestures might miss the animation or (since it's fairly quick and doesn't pause for them to understand better) might not get what the gestures do or that it's something they can do in the first place. With the tooltips and the pausing I'm hoping to avoid "what just happened?!" syndrome :)

**Comment by pe0ny** [comment]
I agree with Robert, when we just animate something on the page without any information or explanation it will cause confusion because something "just" happened without any input from the user. The whole thing depends on the animation, so we have to make sure to get it right.

**Comment by amulware** [comment]
I've seen this in many apps and it is such a common gesture I think it's totally fine. But alright. I'll go disagree somewhere else. :P

**Comment by pe0ny** [comment]
Can you give us some example? Because I've seen this a lot, too but always with some overlay or another additional text somewhere.

**Comment by amulware** [comment]
Sorry, no examples. I know I saw it just recently, but can't remember what app.

**Comment by pe0ny** [comment]
Animation for the swipe animation: #1650

**Comment by simonrozsival** [comment]
The description of this issue is very vague when compared to the other onboarding phases.

> both continue and delete showcased on the same TE

What if the user deletes the TE? Should it be displayed on a different TE?

How is the tooltip dismissed? By tapping on it as usual (I suppose that should always work), by performing the action (continuing or deleting), and by swiping in the opposite direction to avoid continuing/deleting? Any other possibilitites?

**Comment by simonrozsival** [comment]
Also on older versions of iOS we don't support continuing swipe. That will be skipped then.

**Comment by fonorobert** [comment]
@simonrozsival re. tooltip, you listed all the dismiss possibilities i think :+1: 

re user deleting TE, imho it should be shown on the topmost TE (ie. latest) that has at least a project or a description. if there are no TEs matching that, wait for one to be created and then show the animations and tooltip

**Comment by pe0ny** [comment]
What Robert said. Also, an update on the animation: As discussed in Slack we'll use bounce like shown in here #1650 instead of the actual swipe thingy.
