### ISSUE TITLE
App is crashing when tapping projects/tags empty state.

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1524]
Steps to reproduce:
1) Start a new entry
2) Tap on the projects or tags icon (or use @ or #)
3) *When a user doesn't have any project or tag, the empty state is displayed.* Tap on that empty state.
4) App crashes.

*This happens only in projects/tags view in Start view.*

**Comment by simonrozsival** [comment]
The PR #1560 was already merged into the hotfix-1.3.3 branch and is already on `develop`.
