### ISSUE TITLE
Log not updating correctly

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1526]
@pe0ny describes:
> I don’t know how to reproduce this but *sometimes* the UI doesn’t display newly created time entries. This means:
> 1) When I stop an entry, I can see in the UI it almost appears there but in the end it doesn’t. some sort of glitch happens.
> 2) When I start and stop another entry, then the first one I created before appears and second one doesn’t etc…

**Comment by amulware** [comment]
We also know that restarting the app fixes the issue for some time, until it occurs again.

**Comment by simonrozsival** [comment]
Do we have any more information on this bug?

**Comment by amulware** [comment]
The above is all I have :/

**Comment by amulware** [comment]
If we can't reproduce it, drop it for now until we get more info.

**Comment by amulware** [comment]
Closing this, since a lot has changed in the meantime.
