### ISSUE TITLE
Implement the v9 /me/preferences endpoint

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1534]
We currently have no way of getting user's preferences - mainly regarding the date, time and duration formatting.

The endpoint is `/api/v9/me/preferences`, the response looks like this:
```json
{
    "timeofday_format": "h:mm A",
    "date_format": "MM/DD/YYYY",
    "duration_format": "improved",
    "record_timeline": false,
    "send_product_emails": true,
    "send_weekly_report": true,
    "send_timer_notifications": true,
    "CollapseTimeEntries": true
}
```

- [x] Add a model
- [x] Add singleton repository
- [x] Add the endpoint
- [x] Add HTTP client class (GET, POST)
- [x] Add persisting state (similar to workspace features - override unless the sync state is set to `SyncNeeded`)
- [ ] Add pushing state
- [x] Add reference to the repository to the database
- [x] Add reference to the data source

**Comment by amulware** [comment]
Should we include properties that we don't care about?
Our policy so far has been not to add things we know we won't care about, so I propose we only consider:
```
{
    "timeofday_format": "h:mm A",
    "date_format": "MM/DD/YYYY",
    "duration_format": "improved",
    "CollapseTimeEntries": true
}
```

I believe if we don't include the other properties on pushing, it will not override them either, so that should be fine.

**Comment by amulware** [comment]
There was an internal discussion about using `me/preferences/mobile` (which would have to be created first), with the conclusion that we won't.

**Comment by amulware** [comment]
It occurs to me that we either need to ensure that fetching the preferences always works during signin/signup or we have to have some default settings in the app. Otherwise, the app might get into a state where it always crashes because it tries to access user settings to display data.

The same might be true for workspaces?

**Comment by simonrozsival** [comment]
I think that we should use some default values (e.g., what we use now) in case we couldn't pull user's settings.

What exactly do you have in mind wrt workspaces?

**Comment by amulware** [comment]
Well, we can retry at least, but I'm not sure how often this would even happen.

We can also for now just let it be caught by https://github.com/toggl/mobileapp/issues/1342
(for now == when that is implemented)

**Comment by simonrozsival** [comment]
This could happen if the user was online at the time of logging in but then he lost the Internet connection during pull sync. Or if the endpoint is broken. Or if the server randomly dies for this single request or that request time-outs (but then it should be fixed in the retry loop automatically I believe).

**Comment by amulware** [comment]
I'm putting this here: backend has confirmed to me that the date/time formats are validated by the api, so we will never get garbage values. No checks on our side are necessary. (Posting invalid values will fail with.)
