### ISSUE TITLE
Refactor json converters

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#1541]
There seems to be some code repetition (or at least very similar) code in the few json converters that we have, but adding something like `JsonConverterBase<T>` would help that and would be useful for any future converters that we might have.

@amulware suggested using [this](https://github.com/amulware/awgraphics/blob/master/src/amulware.Graphics/Serialization/JsonNet/Vector2Converter.cs) as an example.

**Comment by amulware** [comment]
Slight correction: The most up to date version of the base converter I use is this:
https://github.com/beardgame/td/blob/develop/src/Bearded.TD/Mods/Serialization/Converters/JsonConverterBase.cs

It might not be perfect but has served me well. It does all type checking and casting work for you, allowing the actual converters to be very clean.

**Comment by amulware** [comment]
Old.
