### ISSUE TITLE
Edit view UI updates

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1542]
- [x] Move description to the top on the toolbar like we have it in the start view.
- [x] When a user is editing the description, the action changes from "Save" to "Done".
- Selecting "Done" will bring them back into "Edit everything" mode where description field is not active (user is not currently editing the description).
- Selecting "Save" in "Edit everything" mode saves the changes and closes the edit view.
- [x] Tapping 'X' will discard the changes and closes the edit view. 'X' behaves the same way when the description field is not active and when it's active (when a user is currently typing the description). *Check confirmation #1543*
- [x] Remove the delete icon from the toolbar and move it at the bottom of the edit view list.
- [x] Tapping "Delete this entry" opens confirmation #1269 and tapping "Delete" once more, deletes this entry.
- [x] Show "Duration" label in the duration field.

### Edit view
![edit](https://user-images.githubusercontent.com/5064445/37646227-c0e29fac-2c31-11e8-99ab-336787f8c1f9.png)

Zeplin: https://zpl.io/bPrLJQD

**Comment by kornelijepetak** [comment]
Two remaining points moved to #1830
