### ISSUE TITLE
Edit view: Ask confirmation when discarding changes

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1543]
- [x] Ask confirmation: "Discard" or "Keep Editing" when a user taps 'X' in the edit view.
- [x] Ask confirmation only when a user has changed anything. Use the same logic we use in iOS #1042 
- [x] Don't ask anything if a user hasn't made any changes.
- [x] Changes to consider:
- Description
- Project/task
- Tags
- Start/end time/date
- Duration
- Billable flag
- [x] When a user changes the field (eg description) and then changes it back, then the app shouldn't ask this confirmation, and consider this as no changes were made.

### Edit view: confirmation
![edit cancel edit](https://user-images.githubusercontent.com/5064445/36371522-0eb7bd8a-156b-11e8-8822-30997c481a5c.png)

Zeplin: https://zpl.io/VDDzzR3

**Comment by kornelijepetak** [comment]
@pe0ny Why the difference in wording between iOS and Droid?
`keep editing` vs `continue editing`?

**Comment by pe0ny** [comment]
@kornelijepetak Good question. Let's keep it consistent and use "Continue editing"
