### ISSUE TITLE
Edit view: allow tokens

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1545]
- [ ] Allow using shortcuts @ and # and tokens to add project and tags. *Like the way we do it in the start view.*

**Comment by kornelijepetak** [comment]
@pe0ny does this change the way we are showing the projects and tags below?

**Comment by pe0ny** [comment]
@kornelijepetak Nope, we still display Projects and Tags fields the same way like we do now.

Another note: Show tokens only when the Description field is active. When user is in the Edit view and Description field is not active, display only description - project and tags are visible in the fields below.

**Comment by kornelijepetak** [comment]
Yes, this make sense. Thanks 😄

**Comment by amulware** [comment]
Yes, but as part of a future redesign.
