### ISSUE TITLE
Figure out line endings

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#160]
It should be possible to work on this repo on different platforms with ideally no changes to the IDE settings.

We should look into maybe using the `.gitattributes` to enforce intended line endings so we never run into ugly diffs.

**Comment by willsb** [comment]
Windows:
`git config --global core.autocrlf true`
🍎:
`git config --global core.autocrlf input`

:shipit:

**Comment by amulware** [comment]
I think adding a .gitattributes is better, since this will enforce the correct behaviour for everyone working on the repo. I'm no expert on the correct settings though.

Maybe we can also enforce this with linting, but I'm not sure that's the right use case.

**Comment by willsb** [comment]
The settings I provided should be enough :)

**Comment by amulware** [comment]
Also see #38 for a possible alternative.

**Comment by amulware** [comment]
Closed with #298
