### ISSUE TITLE
Sign up flow changes: Active consent to our Terms of Service

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1611]
Regarding GDPR (General Data Protection Regulation) changes we will need 2 additions to current sign up flow: User’s Country of residence & active consent to our Terms of Service.

## Active consent to our Terms of Service
- “By signing up you agree to terms of service…” can no longer be just a passive text or pre-ticked checkbox. This means the user must “actively” consent, so e.g. tick a box or push some “Agree” button, in order to create an account. We decided to use two-step sign up and ask user to interact with "I agree" button.
- Confirmation with timestamp that they have done this must be sent to backend, they’ll modify the v9/signups endpoint accordingly https://github.com/toggl/backend/issues/6354
- Open this popup after user taps "Sign up for free" button in the Sign up view #1960
- Send the form to the BE after user has tapped "I agree" button
- User can close the popup by tapping the 'x' button or on the background. Then user will be directed back to the Sign up page. Fields that user filled in before must remain filled.
- ToS: https://toggl.com/legal/terms/
- PP: https://toggl.com/legal/privacy/

### ToS & PP popup
![toggl - ios - sign up tos pp 1x](https://user-images.githubusercontent.com/5064445/39252618-b7148e74-48ae-11e8-8a8e-c84a2be69fa7.png)

Zeplin: https://zpl.io/blmM4jk

**Comment by fonorobert** [comment]
Update to this: we'll need to have users accept the Privacy Policy separately as well. If eg. this will be a checkbox then it needs to be two separate checkboxes. :/

**Comment by fonorobert** [comment]
new update: we don't need to have the user accept ToS and PP separately, they can accept it in a single step

**Comment by pe0ny** [comment]
> I take it the TOS/PP popup here https://github.com/toggl/mobileapp/issues/1611 is shown before we send anything to backend, and we only actually sign up if the user clicks ‘I agree’?

yes

> How does this work with google signup? Do we show the same popup before we _actually_ take them to google?

it will be: tos->google->google signup
