### ISSUE TITLE
Edit view: Ask confirmation when discarding changes

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1612]
- [x] Ask confirmation: 'Discard' or 'Continue Editing' when a user has made any changes and taps 'x' in the edit view. (Like in the Start view #1042)
- [x] Don't ask anything if a user hasn't made any changes.
- [x] Changes to consider:
- Description
- Project/task
- Tags
- Start/end time/date
- Duration
- Billable flag
- [x] When a user changes the field (eg description) and then changes it back, then the app shouldn't ask this confirmation, and consider this as no changes were made.

**Comment by amulware** [comment]
@pe0ny Does/will this work the same on android?

**Comment by amulware** [comment]
#1313 says yes. 👌

**Comment by pe0ny** [comment]
@amulware yes. #1543
