### ISSUE TITLE
Reports: Pie chart

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1622]
Reports view includes three different sections: **Summary**, **Bar chart** and **Pie chart** with a list. In this issue implement the **Pie chart section with a list**.

- [x] Pie chart shows top projects with percentages.
- [ ] We show all the projects that duration exceed 10% of the total duration. All the projects that duration doesn't exceed 10% of the total duration will be generated under 'Other' category which may contain one or more projects (the reason behind is to group smaller project so they don't clutter the pie chart and the list below).
- [x] The list view includes: a project name, client (if any), percentage and duration
- [x] Sort projects by duration (desc.)

### Reports
![reports](https://user-images.githubusercontent.com/5064445/36897665-330502fc-1e20-11e8-9453-400746f664f1.png)

Zeplin: https://zpl.io/2yBEpQL

**Comment by simonrozsival** [comment]
Wouldn't it be better to group the projects just in the pie chart, but display all of them in the list?

**Comment by amulware** [comment]
I would agree with that (I actually thought that's how it was designed). Up to @pe0ny

**Comment by pe0ny** [comment]
I like Simon's idea - let's do it so 🙌
