### ISSUE TITLE
Settings UI - Submit feedback

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1627]
Implement submitting feedback.

Ref #1268

**Comment by pe0ny** [comment]
- [ ] Add feedback option so users can contact us directly from the app.
- [ ] Let's keep it simple and open an email-sending form when user taps 'Submit Feedback'. *(Like the one we used for iOS app)*
- [ ] Send email to support@toggl.com
- [ ] Subject line: Toggl Android feedback
- [ ] Include app version number, Android OS version and device in the email if possible
