### ISSUE TITLE
Settings UI - Avatar

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1629]
I have no idea what we need to do with this one. 
Get it from backend or what?
Whatever we need to do, this is the issues for that.

Ref #1268

**Comment by willsb** [comment]
We need an interactor that gets the `byte[]` from backend so it's easy to bind the Avatar on both platforms in an XPlat way. I think we already have the image URL in the user object.

I'd normally suggests using Picasso, but it's kind of an overkill to include a link for, literally, only one image.

**Comment by simonrozsival** [comment]
User has the `string ImageUrl` property.
