### ISSUE TITLE
Changes to Project Selection logic

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#1636]
Since our current model has some UX flaws, we have decided to change things a bit. 
At some point, this will have to be done for both iOS and Droid.
But the first step is of course the shared code.

- [x] Update view models
- [x] Update iOS
- [x] Update Android

@pe0ny will provide more details.

**Comment by pe0ny** [comment]
![projectselectionlogic](https://user-images.githubusercontent.com/5064445/36960660-ae3d0bae-2050-11e8-9ad9-6ba3c42229a1.jpg)

@kornelijepetak provided us with this nice project selection logic chart. Here are some additional details:

**Case 1:** When user has 0 projects (and it doesn’t actually matter how many workspaces), then we don't display “No project” option, instead we have an empty state view for that. For Android the empty state is WIP but for iOS we have this one ready: https://zpl.io/bLNKoeM

**Case 2:** All matches are shown, regardless of whether the full match exists.
For example, use typed in "Project 4. We have a matching project "Project 4" and semi-matches like "Project 48" and "Project 41". All of them will be displayed.

In this spec we only mentioned projects but we include tasks in the search, too (using the same logic).

**Comment by pe0ny** [comment]
Also, matches from default WS should be displayed first (that affects sorting).

**Comment by kornelijepetak** [comment]
The chart is now in sync with the above comments.

**Comment by kornelijepetak** [comment]
Also, if the search term (for example `the best app`) does not match anything at all, only the 

* `Create project "the best app"` 

will be displayed.

**Comment by kornelijepetak** [comment]
Oh yeah, this was completed by 3 recently closed PRs.
