### ISSUE TITLE
Track login/signup failures

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1662]
I want to know how often login and signup fail, and for what reason.

Reasons I can think of right now:
- invalid email/password (login only)
- offline
- server error?
- missing api token in response (see #1652)

There are probably more reasons, feel free to add to the list. It should be easy to filter on app center to see what reasons correspond with signups and what reasons correspond with logins. Maybe two different events make sense, dunno.

**Comment by amulware** [comment]
Another important reason:
- sync failed
  - and if so, I want to know more details here, like what exception caused it, with what message

**Comment by juanlaube** [comment]
Another reason: signup with used email.
