### ISSUE TITLE
Rounding Issue

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#1670]
Case/654253

Version: Daneel/1.3.3
Phone: iPhone 7
OS: iOS 11.2.6

Has 3 entries on the 05/03/18 that total 6 hours.
On the iOS app, it shows 5:59:08 the total should be 6:00:00

Started                   Stopped                                        Duration      Created
05.03.18 11:40:00 | 05.03.18 15:00:00 | Daneel/1.3.3 | 03:20:00 |   | 07.03.18 09:36:15 
05.03.18 09:10:00 | 05.03.18 11:40:00 | Daneel/1.3.3 | 02:30:00 |   | 07.03.18 09:34:36
05.03.18 09:00:00 | 05.03.18 09:10:00 | Daneel/1.3.3 | 00:10:00 |   | 07.03.18 09:31:21

**Comment by simonrozsival** [comment]
Are we really sure that those start and end times have the second component set to zero? I don't think it is because otherwise, we would calculate it correctly. Was this table sent to you by the user or is this a dump from our database?

**Comment by amulware** [comment]
@ApocalypticFish ☝️

**Comment by ApocalypticFish** [comment]
Created exactly the same time entries in my account, same date and all and couldn't replicate the issue.

**Comment by willsb** [comment]
@amulware Consider closing this as stale, maybe?

**Comment by amulware** [comment]
![](http://www.relatably.com/m/img/hasty-memes/6926853b67558cc8275646e96cf9d8dcadd868b239c30fbc4181492671b9d508.jpg)
