### ISSUE TITLE
Suggestions don't support long descriptions

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1677]
Suggestions don't support long descriptions/projects/clients/task names.
Suggestions should have the same fade as log items have.

**Comment by kornelijepetak** [comment]
Just noted this myself. An example: 

![image](https://user-images.githubusercontent.com/7033216/37160190-f14ab4f4-22ef-11e8-8820-5812d2dc44bf.png)

**Comment by simonrozsival** [comment]
This was fixed in #1671
