### ISSUE TITLE
App notification never syncs and only displays last app toggl

### ISSUE THREAD

**Issue by thecjharries** [toggl/mobileapp#168]
Android+iOS. I can provide screengrabs if necessary.

To duplicate this issue,

1. Start a toggl in the app
2. Change Toggl's state elsewhere (e.g. via the web interface, toggl out)

The Toggl notification should continue counting the original app Toggl, even though it's been ended/switched/totally purged elsewhere.

**Comment by amulware** [comment]
Hi @thecjharries,

We are aware of the syncing issues with the current app. I suggest you try force-refreshing it by pulling down the list of entries in the app (a spinner should appear). If this does not help, please get in touch with our support at: support@toggl.com

This repository is an entirely new app which will replace the current one.
