### ISSUE TITLE
Input disappears (and new app does nothing)

### ISSUE THREAD

**Issue by thecjharries** [toggl/mobileapp#169]
Android+iOS. I can provide screengrabs if necessary.

To duplicate this issue,

1. Start a toggl in the app
2. Change Toggl's state elsewhere (e.g. via the web interface, toggl out)

The Toggl notification should continue counting the original app Toggl, even though it's been ended/switched/totally purged elsewhere.

**Comment by willsb** [comment]
Hi @thecjharries,

We are aware of the issues with the current app. They however should not be reported at this repository, since it only contains code for our new app, which is currently not ready. I suggest you get in touch with our support at support@toggl.com if you need further help.
