### ISSUE TITLE
Conflict resolution problem

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1691]
Steps to reproduce:
- start a TE in mobile app
- stop the TE in the web app
- start another TE in the web app
- force sync in the mobile app
- there will be a weird animation and the "play" button will be semitransparent

One user reports that after doing this whenever he then opens the app, it crashes.

**Comment by amulware** [comment]
I can reproduce, but if I then sync again, it fixes itself and my new entry is there.

One thing we could investigate is in what order pulled TEs are received and persisted. It would make sense to me to always persist an included running entry last to avoid running conflict resolution when it's not needed.

**Comment by amulware** [comment]
Also, when I close and reopen the app in the broken state, it shows me the running time entry fine afterwards. No crashing.

**Comment by simonrozsival** [comment]
This is caused by two animations running at the same time: one hides the currently running time entry card (because the current one was stopped) and the other one which is triggered just milliseconds later tires to show it (because a new TE was started). The result is this weird animation and incorrect UI state.

We should run the animation only if the state changes. If there is already a running TE and a different one should be shown then we don't have to run the close the card and then reopen it (or in the worse case show it and then close it so, in the end, nothing is visible.

**Comment by simonrozsival** [comment]
It will still be necessary to make sure that pull sync changes the state of the currently running TE just once, not twice.

**Comment by amulware** [comment]
This was actually closed way back.
