### ISSUE TITLE
Add different icons for Debug/AdHoc builds

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#1699]
We need different icons for Debug and AdHoc builds, like superday does.
We need @pe0ny to provide the icons and then we need to somehow replace the files using cake, similar to what's already being done for the bundle id and app name.

This issue allows #1675 to be merged.

**Comment by pe0ny** [comment]
![toggl-app-icon-1024x1024px-adhoc](https://user-images.githubusercontent.com/5064445/39567686-7f9572fe-4ec8-11e8-83ff-b542b7c1299e.png)
![toggl-app-icon-1024x1024px-debug](https://user-images.githubusercontent.com/5064445/39567689-8121dcfc-4ec8-11e8-9e5c-7a35321befdd.png)
