### ISSUE TITLE
Catch `UserIsMissingApiTokenException` on login and signup

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1701]
When this exception is encountered on login/signup, let's retry the endpoint say... 2? more times, after a couple of seconds each. Maybe once after 2 seconds, and then after 10, just to make sure?

That should give our replicas enough time to catch up and return us a valid API token.

If the retries still fail to get us a token, then we'll fail as we would on any server error.

Follow up to #1652

**Comment by amulware** [comment]
We should probably do this in the google cases as well, yes. If we can. This needs testing, since the google login token might only be valid for a single request. And after signup we don't wanna signup again, but just login. Similar with regular signup.


Also: Unassigning @daividssilverio. Someone else can take this over.

**Comment by amulware** [comment]
Nevermind, you can continue this when you're back @daividssilverio :D

**Comment by amulware** [comment]
Note: not receiving an api token on signup does not indicate that the signup failed. Hence, we should never retry the signup endpoint in that case, it will fail with duplicate email. Instead, we should retry with the login endpoint.

**Comment by daividssilverio** [comment]
I'll make changes to address that.
