### ISSUE TITLE
Show syncing errors and being offline

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1708]
#1707 implemented a syncing spinner but no display of error/offline or retry buttons. @willsb proposes using a snackbar for these things.

Needs concrete design by @pe0ny.

**Comment by pe0ny** [comment]
Yep, I agree. Let's use Android default slackbar for that. Some notes:
- Snackbar animates upwards from the bottom edge of the screen.
- FAB animates upwards together with the snackbar.
- Snackbar disappears automatically after a timeout (5 seconds - *if the default is something different, please let me know. 5s was what i saw apps using for connection problems*) or after any user interaction elsewhere.

## Design
### Snackbar

![timer - offline](https://user-images.githubusercontent.com/5064445/37374615-fab39364-26e9-11e8-97b0-39da84241869.png)

Zeplin: https://zpl.io/bzY4k4X

**Comment by willsb** [comment]
The default times are indeed too short. 5s is a sweet spot :)
