### ISSUE TITLE
Bug(?) in pull-sync ?since logic

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1709]
I'm reasonably sure this is a thing, but maybe @simonrozsival can confirm it.

- Imagine a user who stops changing their projects.
- The project-since-date will be set to that last change date.
- Two months later, the app will think the project list is out of date and fetch all projects.
- No new since date is found, so now, on every pull sync, all projects will be fetched.

I have no idea how many users are affected by this, but it is a case that worries me a bit. Not so much for the additional traffic itself (I assume that users that don't edit their projects much won't have many projects and vice versa), but more for the potential slow down of the sync (which I realise is sort of dependent on the amount of traffic).

Options I see:
1. do nothing and forget about it until backend comes knocking (we need A LOT more users before that happens)
2. set the ?since date ourselves based on some criterion (I can't think of a way that guarantees we don't lose any changes here though)
3. get backend to send us a new guaranteed since date in the request (not before v10)
4. get backend to make an endpoint giving us the server time, subtract a couple of minutes from that, use that as since dates (this is feasible, would also help us use server time instead of user time to avoid wrong-time-settings-issues)

1 or 4? Which shall it be?

**Comment by amulware** [comment]
Another option: Track it (on GETting full list, if list is not empty, and last item is 2+ months old), and see if it's actually a thing. :D

**Comment by simonrozsival** [comment]
This is interesting, it will indeed fetch all projects on any following request. From the given options, I would pick number 1 - leave it as it is for now.

Number 3 would be ideal, but that won't happen soon I guess, 4 might be easier and safer for backend to implement but it would mean more HTTP requests, but we definitely shouldn't use 2 (user's date time settings might be way off and some data won't be synced).

**Comment by simonrozsival** [comment]
`X` could be even 10 minutes, 1 hour, 1 day... that'll still help with this problem. And we would prefer the `at` values whenever they are more up to date. It would also partially solve our "always fetch the last entity" problem.

**Comment by amulware** [comment]
Good point on fixing the other issue (partially). For that purpose, we shouldn't pick X too large.

**Comment by amulware** [comment]
I'll talk to backend once more soon, but unless they can deliver a better solution soon, I think we should do as you suggest.

**Comment by juanlaube** [comment]
I like the option where we track this too and see if this is really a problem, those are not mutually exclusive.
