### ISSUE TITLE
Open start view if 3d-touching suggestion

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1724]
This is a proposal for now, but I had the idea that when one 3d-touched (i.e. with more force) a suggestion, it could open the start view with the usual 3d touch animation. That would allow the user to start the suggestion but also quickly modify it. And it would be a cool feature.

Ref @pe0ny

**Comment by pe0ny** [comment]
@amulware Just to clarify, you mean when a user taps one of the suggestions in the app? Yeah, that would be a nice feature, I agree :)
I believe, we can remove the 'needs-design' label and add this to our backlog?

**Comment by amulware** [comment]
Backlogged.

**Comment by amulware** [comment]
It could even be a two step thing, where at first it pops open so the user can see all the data of the new TE better, and then they have to fully press in to make it pop open the start view. But maybe that's also over the top because there's just a cancel button anyways.

**Comment by willsb** [comment]
We've tried to implement these in #3335 , but it fell flat for a myriad of reasons:

- The preview VC needs to pop into full screen VC, which is not the case for the start TE view
- The start TE VC is a terrible preview VC. These need to be succinct and show only crucial info
- Peek and pop needs the quick actions so users can ignore the pop element and just something quickly

I say we go back to the drawing board and design the feature properly before we start implementing it.

**Comment by amulware** [comment]
Closed until we have a unified edit/start view and we can see if we still want this.
