### ISSUE TITLE
Continuing a TE doesn't copy tags when another TE is running at that moment

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1725]
How to reproduce:

1. make sure all TEs are stopped
2. continue a TE A which has at least one tag
3. check the newly created TE B - it has the same tags as A
4. continue the TE A again (while B is still running)
5. B will be stopped, a new TE C will be running
6. check the TE C - it doesn't have any tags, expected behavior would be to have the same tags as A

**Comment by ricotheque** [comment]
Thanks for finding this @simonrozsival! This will definitely help with /case/605341 and /case/654501

**Comment by simonrozsival** [comment]
The problem is in `RealmAdapter` on line 201 - for some reason, the `entity` has all the correct tags, the `fixedEntity` also has all the tags, but after `entity.SetPropertiesFrom(fixedEntity, realm);` the entity has 0 tags.

**Comment by simonrozsival** [comment]
This was already merged into the 1.4.2 hotfix which was already released.
