### ISSUE TITLE
System back button should exit the app when being used on the main screens

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1733]
We had a discussion what the system back button should do on the main screens when user switches between Timer-Reports-Settings. We ended up with this:
- The system back button on the Timer, Reports and Settings screens = Exit app

**Comment by amulware** [comment]
I missed the relevant discussion. What was the reasoning to exit the app when hitting back on the reports/settings screens? Shouldn't it go back to the main screen?

**Comment by daividssilverio** [comment]
There was some other discussion about this today. So, what's gonna happen about this feature?

It feels weird to me to close the app from the settings and reports views. The time entry does look like the main main screen.

**Comment by pe0ny** [comment]
I believe this issue can be closed because now we'll have only one main screen and the back button already closes the app. Check #1852
