### ISSUE TITLE
Tapping 1Password icon on login causes app to crash

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#1736]
As reported by [this social post](https://app.agorapulse.com/inbox/twitter/51704?view=inbox&filter=any&item=974502055959285760) (https://twitter.com/peeja/status/974502055959285760) and reproduced by yours truly.

1. Open Toggl app (If logged into Toggl app, log out through settings screen)
2. Progress through welcome screen
3. Tap on Log in button
4. Tap on 1Password button beside the Email textbox 
5. App crashes to home screen

Confirmed on iOS 11.2.6 (15D100) for the following devices:
* iPhone 8
* iPhone 8 Plus

**Comment by simonrozsival** [comment]
The fix was already released in `1.4.2`.
