### ISSUE TITLE
Editing entry puts default date to 31st December

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#1748]
Video of issue can be found in case 658422

"When activating the time wheel to edit start/end time, it seems to be defaulting back to December 31 even though the current end time is the current date. "

**Comment by simonrozsival** [comment]
From the video it seems that the time is set to the start time and the date is always set to December 31. This might be related to the problem where the date picker shows the start time even though the user wants to edit the end time. I will look into this soon.

**Comment by amulware** [comment]
Superseded by #1887
