### ISSUE TITLE
Make back/close button tap area bigger on the toolbar

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1749]
At the moment the tap area is ~16x16dp but it's really hard to tap it. Let's make it 56x56dp instead.
This applies to toolbar's back/close buttons in all views.

For example:

<img width="363" alt="screen shot 2018-03-19 at 10 35 58" src="https://user-images.githubusercontent.com/5064445/37585311-621ed588-2b61-11e8-8dfb-c4255fd8c130.png">

**Comment by daividssilverio** [comment]
Hey @pe0ny could you get me a new arrow-back icon with paddings on all sides? 
It currently doesn't have paddings to the left.

**Comment by lizaPlotnikova** [comment]
@daividssilverio You can grab the asset from zpl.io/2EdyAwM

**Comment by pe0ny** [comment]
All the assets are available in Zeplin.

**Comment by pe0ny** [comment]
@willsb Example from the current edit view:

<img width="412" alt="screen shot 2018-04-04 at 14 53 01" src="https://user-images.githubusercontent.com/5064445/38306071-f88529a6-3817-11e8-8666-3a4779cabf05.png">
