### ISSUE TITLE
Settings view: Move Sign out button at the bottom

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1751]
Since it's quite easy to sign out by accident, move Sign out button at the bottom of the screen, further from the other list like we do in iOS.

### Settings
![settings](https://user-images.githubusercontent.com/5064445/37586541-54499728-2b65-11e8-89cc-c49fe3c63327.png)
*Sign out cell should have top and bottom borders which doesn't stand out here in GH issue but are visible in Zeplin*

Zeplin: https://zpl.io/VD73lje

**Comment by kornelijepetak** [comment]
@lizaPlotnikova I see you have updated above mentioned Zeplin design. It is reverted to the old one. Was that intentional? Because it is no longer in sync with what is specified on this issue ? 

@pe0ny can you check too?

**Comment by pe0ny** [comment]
@kornelijepetak Damn, there must have been a merge conflict. I'll try to figure it out and update it again.

**Comment by pe0ny** [comment]
_updated again_
