### ISSUE TITLE
Timer page: Suggestions UI fixes

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1753]
- [X] "Working on these" should be displayed in uppercase.
Paddings are a bit off at the moment:
- [ ] Padding between the Toolbar and Suggestions should be 16dp (atm it's more)
- [X] Padding between "Working on these" and the cards should be 12dp (atm it's more)
- [x] Suggestion cards should have 16dp padding from the left (atm it's more)
- [x] ~Padding between Suggestions and the Log should be 32dp (atm it's less)~ To be fixed in #1752

Zeplin: https://zpl.io/be1Le3l

**Comment by willsb** [comment]
> Padding between the Toolbar and Suggestions should be 16dp
This is set to exactly 16dp at the moment

> Suggestion cards should have 16dp padding from the left (atm it's more)
Same, this is 16dp. But due to the shadow, it looks offset. I changed the margin to 14dp (-2dp because of the shadow) and it indeed looks much better

**Comment by pe0ny** [comment]
Sounds good 🙌
