### ISSUE TITLE
Change toolbar colour to blue

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1761]
Change toolbar background colour to blue #2196f3
- [x] Start view
- [x] Edit view
- [x] Projects view
- [x] New project view
- [x] Tags view
- [x] Clients view
- [x] Also, change text colour and icons to white

Zeplin (Start view example): https://zpl.io/bzy1R3z

**Comment by daividssilverio** [comment]
@pe0ny the icons you are talking are the project, tag, back-arrow and billable icons, right?
Btw, at least of the Start View, the design from zeplin and what's currently implemented is different in relation to where the project, tag and billable icons are currently placed.

Should I make them white anyway?

**Comment by daividssilverio** [comment]
@pe0ny So far It's looking like this, at least for the Start view.

![blue_toolbar](https://user-images.githubusercontent.com/2173493/37631788-8d478d30-2bc1-11e8-8846-89cf629223e9.png)

**Comment by pe0ny** [comment]
@daividssilverio Sorry, it shouldn't have been in plural - only one icon (the 'Back' icon which should be replaced with 'X' and should be white).

Project, tag and billable icons can remain the same because these will be removed to another place #1743

Also, can you change the insertion mark colour to white as well?

**Comment by daividssilverio** [comment]
Got it! @pe0ny.
Yes, I can do it, I don't know why it looks green though.
Btw, I got the colour of the status bar and the text hint with a colour picker, because Zeplin would only give me transparency, do they look fine?
Status bar: #559fec
TextHint: #b9d9f7

**Comment by daividssilverio** [comment]
@pe0ny here are all the now blue toolbars.
![toolbars](https://user-images.githubusercontent.com/2173493/37687615-a000c610-2c72-11e8-980f-ae2df034b49f.png)

The custom made toolbars are a little off and hard to click on, but I'll take a look at that on #1749 .
