### ISSUE TITLE
Time/date/duration popup

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1764]
- [ ] Open this popup when user taps
a) Clock icon or Duration in the Start view
b) Start/stop/duration in the Edit view
- [ ] User can switch between three options: start time/date, stop time/date and duration
- [ ] Swipe gestures are used for navigating between tabs. Also, user can tap the titles to navigate between tabs.
- [ ] Tabs show currently selected time or duration, eg 12:30 PM or 0:30:15. The selected tab shows instead name of the tab/content, eg "Start", "End" or "Duration".
- [ ] User can also edit the date in the same view by tapping on the date in the blue area. Clock content will be replaced with Date picker.

### Time/date/duration popup

![edit - time](https://user-images.githubusercontent.com/5064445/37646380-3404bdf8-2c32-11e8-9b8d-490b32bbee3a.png)

Zeplin: https://zpl.io/aBOz3Mq

### Date

![edit - date](https://user-images.githubusercontent.com/5064445/37646648-dc3eba96-2c32-11e8-94f8-f55136663f81.png)

Zeplin: https://zpl.io/aRN4k5z

**Comment by willsb** [comment]
Has this been superseded by #2040?
If so, shouldn't this be closed?

**Comment by kornelijepetak** [comment]
Not superseded, but split. Indeed, it should.
