### ISSUE TITLE
Settings view: Add manual switch

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1766]
- [ ] By default manual mode is off.
- [ ] When a user turns on manual mode then play icon in the timer page will be replaced by the ‘+’ icon.

### Settings
![settings](https://user-images.githubusercontent.com/5064445/37664192-79056d18-2c63-11e8-98a3-498ddd237ee4.png)

Zeplin: https://zpl.io/VD73lje

'+' Icon is available here: https://zpl.io/2EdyAwM

**Comment by daividssilverio** [comment]
The '+' icon is missing on https://zpl.io/VD73lje 
Can we get a new one, like these "play-white", "stop-white" from the Styleguide?
I've used the "add_new" and it doesn't for testing.
