### ISSUE TITLE
Group smaller projects into a single segment on reports pie chart

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#1800]
Right now, we are using the `Segments` property of the `ReportsViewModel` both for plotting the Pie Chart and for showing the Legend. What we should do instead is having a property like `LegendItems` that has all the segments and perform a transformation on the segments that will be used in the pie chart to group them according to the rules stated in #1622.

I'm opening this as a separate issue because it will affect iOS as well, so we're better off doing this after the basic reports functionality is stable on Android.

**Comment by amulware** [comment]
Sounds fine to me, but not a priority for now. We're gonna change up reports a lot soon anyways, so let's wait until we have a better idea of that so we can don't waste our time. :)

**Comment by amulware** [comment]
Ok, I misunderstood. Let's copy iOS for now, leaving the `other` grouping out, and when they both (mis)behave the same, we'll do this as suggested here.
