### ISSUE TITLE
Weird UI state after creating a TE

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#1813]
Steps to reproduce:
1. start the app
2. if you are not logged in, log in
3. log out
4. log in or sign in as a new user
5. start a new time entry
6. the current TE card is shown with an empty description and the duration stays at the default value of `0:00:00`, the stop button is disabled 😢 

This problem definitely affects iOS and it might affect Android as well - @willsb will try it out and add further information.

**Comment by amulware** [comment]
@simonrozsival does this still happen?

**Comment by simonrozsival** [comment]
This was fixed by #1927, I forgot to reference and close this issue.
