### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#183]
Implement the timeline at the top of the main screen of the app. The timeline shows the colour of all time entries, and smoothly scrolls to past days when dragged.

Please see designs, or ask for any additional details.

**Comment by arturs105** [comment]
Should we create this control as a part of `Toggl.Daneel` or as a separate project, since this could be reused?

**Comment by amulware** [comment]
Platform independent code should be un Foundation.MvvmCross, but the platform specific code should be on Daneel.

**Comment by jayvdb** [comment]
Noting it is confusing to call this 'timeline', which is a feature of Desktop app

**Comment by pe0ny** [comment]
I'll close this because it's not in our plans atm.
