### ISSUE TITLE
Select all doesn’t select the last character of a TE description when TE includes an emoji

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#1832]
Select all doesn’t select the last character of a TE description when TE includes an emoji

Video: https://drive.google.com/open?id=1iw1xT0JtTgwNzZZFybyC2vIHzNg8fXlW

Version: Daneel/1.4.2
Phone: iPhone 7 Plus
OS: iOS 11.3

**Comment by simonrozsival** [comment]
In the creation works selecting all works well, the bug is only in the edit view.

**Comment by simonrozsival** [comment]
I think that this is related to #1831 - that crashes also only in the edit view.

**Comment by simonrozsival** [comment]
The problem is in the `TextViewWithCharacterCounter` class.
