### ISSUE TITLE
Edit view: keyboard doesn't close after editing description

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1845]
Steps to reproduce:
1. Open edit view
2. Tap on the description field to edit
3. Keyboard appears. Tap 'Done'
4. Keyboard doesn't close, though it should

**Comment by kornelijepetak** [comment]
@pe0ny Could you please try this again? I tried in emulator and on the device. I am not able to reproduce this. My keyboard closes every time I click on `Done`.

**Comment by pe0ny** [comment]
@kornelijepetak yes. happens every time to me.

**Comment by kornelijepetak** [comment]
What is the device you are using? @willsb can you try on your device?

**Comment by pe0ny** [comment]
I have Sony Xperia and android 7.0

**Comment by willsb** [comment]
Pixel 2, Oreo 8.1, can confirm that the keyboard gets dismissed just fine. 

Congratulations, we just found or first bug that only happens because companies mess with Stock Android 🎉

**Comment by kornelijepetak** [comment]
Not sure which xperia, but I know some of the have problems with autoclosing soft input, like this one here [Z3+ bug with soft input](https://www.youtube.com/watch?v=W12WyJA0454)

**Comment by pe0ny** [comment]
It's XA1

**Comment by kornelijepetak** [comment]
@willsb The only thing that comes to mind is put the call to `HideSoftInputFromWindow` into `Post`. I've seen exactly *one* in total google result where that helped, but with no references to a specific phone model. Do you think it's worth a try?

**Comment by kornelijepetak** [comment]
@willsb We've tried with putting stuff in `Post` but this did not solve the issue on @pe0ny's phone. 

We'll need to  test some more phones for that to see if other cell phones are affected too.
We are basically doing the most native thing there is, so I don't think there's much to do in order to fix this. Will post more information once I have them.

**Comment by kornelijepetak** [comment]
I'm putting this issue on hold until we have more information about how to deal with this and we get more internal testing data.

**Comment by pe0ny** [comment]
I'm closing this because it's been either fixed or it fixed itself.
