### ISSUE TITLE
Basic suggestions

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#185]
Implement a flexible suggestions framework allowing for multiple providers that can be extended in the future. (discuss details/requirements as needed)

The first and simplest provider should show the most used time entry in the last two weeks, matching by description, project and task.

**Comment by arturs105** [comment]
Is this something like autocomplete, where the suggestion provider receives some (unfinished) input from user and tries to guess, what the user is trying to type?

**Comment by willsb** [comment]
Nope. This is something that generates possible TimeEntries based on... stuff 😄
