### ISSUE TITLE
After creating a new project, the app should direct user back to the time entry

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1861]
Currently, it takes user back to the Projects view with the new project name typed in.

**Comment by willsb** [comment]
This is a known MvvmCross bug:
https://github.com/MvvmCross/MvvmCross/pull/2513

Fixes on v6, so we need to update it

**Comment by willsb** [comment]
Should this be put `on-hold`, @amulware ?

**Comment by willsb** [comment]
Putting this on-hold until we update the framework

**Comment by pe0ny** [comment]
I'm opening this issue again since the problem still occurs after the MvvmCross update.

**Comment by amulware** [comment]
Any update on this @daividssilverio?

**Comment by daividssilverio** [comment]
I tested yesterday, still not working.
I did some tests before when we updated to Mvx6 following some instructions on the related source bug report without luck.
I'm trying this again today, see If I missed something, but I don't know how to proceed. I'll be firing randomly.
