### ISSUE TITLE
Sign up and log in flow: password field is not focused

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1863]
Steps to reproduce:
1) Pick either Sign up or Log in
2) Enter email
3) Tap next
4) Start typing the password - nothing happens. When you go back you can see it was typed in the email field instead.

**Comment by simonrozsival** [comment]
I cannot reproduce it neither. I tested it only in the emulator though (but I do not expect this to behave differently in the emulator than on a real device).

**Comment by simonrozsival** [comment]
I think we can close this, @pe0ny.

**Comment by kornelijepetak** [comment]
I noticed this a while while ago, when the login/signup screen was first created. Haven't noticed this since. 

@pe0ny Feel free to close this issue. If something like this occurs again, we will reopen the issue and see what's going on.

**Comment by pe0ny** [comment]
The same thing is happening again. Device: Huawei WAS-LX1; Android version 7.0

**Comment by amulware** [comment]
Closing this since we're rewriting the entire login flow anyways.
