### ISSUE TITLE
Verify the EditText cursor colors

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#1864]
Right now they are the default green-ish color. I assume @pe0ny wants them to be either blue or white, depending on the field.

**Comment by pe0ny** [comment]
Yes. White on the blue background and blue on the white background.

**Comment by lizaPlotnikova** [comment]
It should be slightly transparent white (40% opacity) so that it doesn't blend with the typed-in text. The designs were updated in Zeplin when we made the switch to the blue toolbar. So, you should be good to go :) Here's an example: https://zpl.io/aw0YYpJ
