### ISSUE TITLE
Rewrite model generators

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1891]
They are not very readable. Let's try and do less string manipulation, and do all of it at the beginning of the file and then generate the code, possibly even using functions to encapsulate and name blocks of code.

Note that R# has a plugin that enables intellisense and pretty colours in tt files, which is nice.

**Comment by arturs105** [comment]
Leaving this here for now (might be a separate issue): the `FoundationModels.tt` generator is broken due to `ICountry` model. It tries to generate `class Country : IDatabaseCountry`, but we have no `IDatabaseCountry`, which leads to a compile time error.

**Comment by amulware** [comment]
There are no issues with reports models which are also not persisted, why is that?

**Comment by arturs105** [comment]
Maybe it's been a while, since we regenerated the file?

**Comment by amulware** [comment]
Or maybe they sit in a different folder in Multivac? :D

**Comment by simonrozsival** [comment]
The problem with `Country` will be resolved when #1993 is merged. I would wait with any changes to the templates until this PR is merged - there were already significant changes to that file.

**Comment by Odrakir** [comment]
We completely removed the generators (at least for now)
