### ISSUE TITLE
UI doesn't update after creating a new entry

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1898]
1) Install the app from scratch and log in
2) Start a new entry
3) New entry card doesn't appear at the bottom of the Timer page
4) Restart the app -> Now it’s there and running

It only happens with the first TE I start after login. Can someone reproduce?

**Comment by juanlaube** [comment]
@pe0ny I can't reproduce this with the emulator (Android Nougat), card appears immediately after creating the entry.
Do you have more info about the steps to reproduce? Happens on a device or emulator? Android version?

**Comment by pe0ny** [comment]
I'm closing this issue because I can't reproduce it anymore either.
