### ISSUE TITLE
Investigate what happens with deleted clients

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1905]
Specifically, do the projects still refer to the clients by ID? I was told they would, which should cause our syncing to fail, which should break login.

However, empirically, this does not seem to be the case.

I'd like this investigated to make sure we understand how this part of our business logic works.

Down the line, we might also wanna test other cases like what happens to TEs referring to projects that the user lost access to, but that's maybe a different thing.

**Comment by amulware** [comment]
While we are at it, we should consider writing integration tests for this.

**Comment by arturs105** [comment]
What do you think about having this as an .md file in `mobile-docs`?

**Comment by arturs105** [comment]
Investigated this. After deleting a client, the `me/projects` endpoint returns the project with `"client_id": null`

**Comment by amulware** [comment]
What if you undo the client deletion? (this should be possible on the web, as long as you stay on the page I think?)

**Comment by amulware** [comment]
And does the client `at` date change in either case?

**Comment by arturs105** [comment]
Didn't know about undoing the deletion. Will test this out.

**Comment by arturs105** [comment]
* Deleting client:
  * project.client_id is null
  * project.at does not change
* Removing client from project:
  * project.client_id is null
  * project.at is updated
  * client.at does not change

I wasn't able to find a way to undo a deletion and this makes me think that it's not possible:
![screen shot 2018-04-23 at 17 01 23](https://user-images.githubusercontent.com/15633003/39131430-0d0ef7b2-4718-11e8-98df-652833c67859.png)

**Comment by amulware** [comment]
Hm, interesting, I was told this can be done through the api. Maybe it's only used for time entries or something. But it sounds like that is all the info we are going to get then. Thanks!

**Comment by amulware** [comment]
There might be one problem case for us still, but I think it also automatically resolves itself..

- user is logged in and synced with mobile
- user deletes client online
- user syncs on mobile
- client gets deleted in realm
- project is now refering to? -> because of realm to `null` so it's actually fine 'by accident'

I don't like this, but maybe it's sort of alright. At least it shouldn't break horribly.

**Comment by arturs105** [comment]
I wanted to write an integration test for this case, but we don't have a way to delete a client and i don't want to write extra code in our app just for a single test, so 🤷‍♂️
