### ISSUE TITLE
Stop button/UI is not responding

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1909]
Phone: Huawei WAS-LX1; Android version 7.0

We're having some weird behaviour when the stop button is not responding and UI doesn't seem to update itself when it should.

**Case:**
The stop button is not responding. (Tapping it doesn't seem to do anything). User can see timer stopping after she navigates to the Settings page (tapping the cogwheel) and goes back to the Timer page).

1) Start a new time entry (either a new TE or continue an existing one - result is the same)
2) You can see the Start button turn to Stop button, but the timer doesn't seem running (only 00:00:00 displayed, no description, project or other details)
3) When you tap stop, nothing happens. When you tap the cogwheel icon, you will be navigated to the Settings page; when you return to the Timer page, the TE was stopped.

Also, the entry wasn't displayed until I refreshed the screen (pulled down to refresh), though (with a seemingly random duration).

Could it be that UI is not updating?

I tried to reproduce but it doesn't happen on my phone. If we'll have a solution @kyllikekimmel is the person to ping - she can test it on her phone.

**Comment by juanlaube** [comment]
I wasn't able to reproduce this with the emulator. I don't have a device to test.

**Comment by daividssilverio** [comment]
I wasn't able to reproduce this too on my Nexus 5 (Android 6.0.1), neither on the emulator (Android 7.0).
It seems that the description and the timer is reset (description vanished and timer zeroed) before it actually animates and disappears.

**Comment by pe0ny** [comment]
I can't reproduce it either. I'll close it until we have more info about it or if someone manages to reproduce it again.
