### ISSUE TITLE
Durations don't match

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1910]
When continuing an existing time entry, the entry that appears (after stopping it as described in here #1909) but the duration doesn't seem to match the actual time lapsed. (For example, continuing an entry of 1:40 for a couple of seconds results in a new entry of 1:35).

Could it be connected to the issue mentioned above?

Same device: Huawei WAS-LX1; Android version 7.0

**Comment by juanlaube** [comment]
I wasn't able to reproduce this with the emulator. Continuing from an existing TE creates a new one starting at 0:00:00.

**Comment by pe0ny** [comment]
I can't reproduce it either. I'll close it until we have more info about it or if someone manages to reproduce it again.
