### ISSUE TITLE
After starting a new TE, description and duration fields remain empty

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1911]
> Whenever I've clicked the 'Start' button, the description field remains empty + the duration remains at 00:00:00.

Again: Huawei WAS-LX1; Android version 7.0

**Comment by daividssilverio** [comment]
I couldn't reproduce this bug on my Nexus 5 (Android 6.0.1)
I couldn't reproduce on the emulator as well (Android 7.1.1 and 7.0)

**Comment by pe0ny** [comment]
Let's close it then and open again if someone manages to reproduce it.
