### ISSUE TITLE
Reports: Calendar shortcuts are not tappable

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1912]
Device: Galaxy S8 with Android 8.0.0

**Comment by daividssilverio** [comment]
I'm assuming you can't select those "Today", "Yesterday", "This week" buttons.
I couldn't reproduce this bug on my Nexus 5 (Android 6.0.1) (Although it was really hard to open the calendar, leave it open, to scroll between months and shortcuts too on this device).
I couldn't reproduce on the emulator as Well (Android 7.0 and 8.0 and 8.1)
