### ISSUE TITLE
Rainbow Wheel

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1913]
We had some designs internally. I vote for the coloured one that changes hue with every full rotation because it's cool.

**Comment by pe0ny** [comment]
- Let's use those 18 colours to give the wheel some extra
- Once the duration is longer, use ping-pong effect to repeat the colour scheme
- Add shadow to the end handler to distinguish it more from the start handler

Colours:
- #F1F2F3
- #EDE4F0
- #DFC3E6
- #CA99D7
- #B599D7
- #8799E5
- #5168C5
- #55BBDF
- #95D0E5
- #B0DCEC
- #BFDBD7
- #7FC5BC
- #E5F0BA
- #F0E3BA
- #F8DAB8
- #F0D06C
- #EFBA7A
- #F1ACAE

## Design
### Wheel UI
![wheel](https://user-images.githubusercontent.com/5064445/41774282-ad4fc11e-7627-11e8-997c-e1c08ad1228b.png)

Zeplin: https://zpl.io/bzWNj1l

**Comment by Odrakir** [comment]
Can someone explain how does this work? When does it change color?

**Comment by simonrozsival** [comment]
I am not sure what `ping-pong effect` means in this context.

**Comment by amulware** [comment]
ping pong effect: when you reach the end of the list, go back in reverse to the beginning, and then back to the end, etc. Don't wrap around.

The colour changes everytime the duration of the TE gets an hour longer, so it's that subtle pink below one hour, and once you drag it to be longer than one hour, the overlapping area is the darker pink. And after two hours, the overlapping area is that even darker colour, etc.
