### ISSUE TITLE
Wheel metrics

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1915]
I'd like to get some data on how our users are editing times and durations.

For that I'd like to add an event `ClosedTimeView` (or similar) with the following properties:

- changed start date with barrel
- changed start time with barrel
- changed end date with barrel
- changed end time with barrel
- changed start time using wheel
- changed end time using wheel
- changed start+end using wheel (dragged the filled area)
- changed duration using numpad
- entry was running when opening view
- stopped running entry
- navigation origin (start/edit view)
- result (save/cancel)

I figure we can have a little container with a lot of bools for this that initialises to all false when the view is opened, and when the user changes anything the respective values get set to true. In the end, this is turned into a properties dictionary and pushed as an event. Nothing more complicated (like comparing data on open and data on closed) is needed I think. This should give us a good idea of how the view is used.

**Comment by simonrozsival** [comment]
What about splitting this into several events?
- `ClosedTimeViewBarrel`
    - changed start date with barrel
    - changed start time with barrel
    - changed end date with barrel
    - changed end time with barrel
- `ClosedTimeViewWheel`
    - changed start time using wheel
    - changed end time using wheel
    - changed start+end using wheel (dragged the filled area)
- `ClosedTimeViewNumpad`
    - changed duration using numpad
- `ClosedTimeView`
    - entry was running when opening view
    - stopped running entry
    - navigation origin (start/edit view)
    - result (save/cancel)

**Comment by amulware** [comment]
When exactly are each of these fired?

**Comment by simonrozsival** [comment]
When the view is closed if the barrel/wheel/numpad was used at all.

Two benefits:
- we would see which components are (not) used - some events might not be tracked at all (👀 _numpad_)
- on Android there is no wheel/components - easier code sharing

**Comment by amulware** [comment]
I see, interesting. Though, we can see all the same stuff if it's a single even too, right? Or... you mean this helps us group related events a bit easier?

On the other hand it makes it harder to find out how users change start times specifically for example.

**Comment by simonrozsival** [comment]
The first reason - I am lazy and too many params is more work that more events (if we merge #2401).

Second I think splitting this will be easier to analyze in AppCenter.

You want to track how users combine these components? If they use the wheel for the star time and the barrel for the end time? 🤔

**Comment by amulware** [comment]
I was more thinking: If I want to know if users use wheel or barrel to edit start time, I have to check two events with this proposal.

Combining events is very tricky because we then actually would need app center to give us the correlation between different events/properties, which it does not.

**Comment by amulware** [comment]
What I'm concerned about is more events actually making it more difficult to find things in the event list, not to mention we can only have 200 I think.

**Comment by simonrozsival** [comment]
OK. Now it would be really nice if all of the params were of the same type :D -- just kidding, not everything has to be type safe I guess. It will be converted into strings anyway.

**Comment by amulware** [comment]
I'd say, for cases like this, just use the old method style syntax for tracking the event. That way it's relatively easy to add a lot of parameters without needing a special class for it, and it doesn't lose type safety either.

**Comment by Odrakir** [comment]
I just realized that this implies having a `IAnalyticsEvent` with a bunch of generic parameters with the current system... So I guess I'm using the old API and sending a dictionary directly.
