### ISSUE TITLE
App freezes after creating a new TE

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1928]
Steps to reproduce:
1) Sign up
2) Start a new TE

App freezes (doesn't respond to any tap/swipe/drag) and Stop button is a tiny bit transparent:
![image uploaded from ios 13](https://user-images.githubusercontent.com/5064445/38997746-dc33bd90-43f6-11e8-9444-46fd5e020673.jpg)

After restarting the app, i managed to get to this state:
![image uploaded from ios 12](https://user-images.githubusercontent.com/5064445/38997751-e05c143a-43f6-11e8-944e-01adb281f965.jpg)

Device: iPhone SE, OS 11.2.6

**Comment by simonrozsival** [comment]
1. will be fixed by #1927

**Comment by juanlaube** [comment]
Was fixed by #1927
