### ISSUE TITLE
Onboarding phase 4: animations are not displayed

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1929]
After creating 5 TE, the app shows me "Swipe right to continue" tooltip but without any animation:

![image uploaded from ios 2](https://user-images.githubusercontent.com/5064445/38998133-97e8df2a-43f7-11e8-8f39-cd5f5abbd5f2.png)

Device: iPhone SE, OS 11.2.6

**Comment by simonrozsival** [comment]
The animations aren’t implemented yet.
