### ISSUE TITLE
Signup - Interruption, results in unrecoverable crashes

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#1944]
-Force closed the app during signup.
-Reopened and the app shows an empty timer page
-Click on the settings button or others and the app crashes every time it is opened.

**Comment by heytherewill** [comment]
@ApocalypticFish Can you confirm if this is still a thing?

**Comment by ApocalypticFish** [comment]
No, it works now. It just acts like I signed in for the first time in a while.
