### ISSUE TITLE
Enable more StyleCop rules

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1947]
We haven't updated this in a long time. Let's see if there is more we can enable (that makes sense for us). Also, let's maybe double check if it's actually currently working in all projects.

**Comment by kornelijepetak** [comment]
@amulware, what did you have in mind?
I can't think of anything that is really that important to introduce... 🤔

**Comment by amulware** [comment]
Is having StyleCop at all useful then? I don't think we have that many rules enabled.

I was hoping we could enable some of the rules we already follow as per our guidelines.

And maybe there are other things as well that would make sense.

**Comment by kornelijepetak** [comment]
I suggest waiting until I get more information from other devs when they return from 🌴

**Comment by amulware** [comment]
If you need more time to get information, or if you want to do this after Mvexit like discussed in the PR, feel free to move the issue to the 2.1 release projects (both platforms), but do coordinate with the release managers.

**Comment by kornelijepetak** [comment]
Yes, I do want to move this issue out because it does not make sense to repair stuff until MVX is out of the app, in `develop`.

**Comment by heytherewill** [comment]
With #5460 merged, this can be safely moved back into the refactor drawing board. Let's latter discuss whether we should enable more rules or not before we close this for good :)

**Comment by kornelijepetak** [comment]
@heytherewill I'm confused about this comment of yours.
Did not #5460 apply all proposed changes?
If not, why does it not specify which ones it did in particular?
Or did I understand your comment wrongly?

**Comment by heytherewill** [comment]
@kornelijepetak It did, but that doesn't mean we don't wanna enable more rules in the future; hence why I'm not closing it
