### ISSUE TITLE
Stop using short versions of properties like "wid" and "pid"

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#196]
Some models in `Ultrawave` expect backend to return `wid`, `pid` and `cid` instead of `workspace_id`, `project_id` etc. We need to change that (simply remove `JsonProperty` attributes) once backend starts returning long versions.

**Comment by willsb** [comment]
Still used for `Project` and `Client`. Is this still relevant?

**Comment by simonrozsival** [comment]
It can be removed from `Project` as the API returns both short and long names of the fields and I will make a PR for that, but we cannot remove it from `Client` yet, because the API still returns only the short versions.

**Comment by amulware** [comment]
Please do another check, fix all that can be fixed, and list all remaining offenders here.

**Comment by simonrozsival** [comment]
Unfortunately still only the short version is available:

`GET /api/v9/me/clients`

```json
[
    {
        "id": 33192727,
        "wid": 2221495,
        "name": "Client 1",
        "at": "2017-12-07T08:32:38+00:00"
    }
]
```

**Comment by amulware** [comment]
Is that the only endpoint? If so, let's create a backend issue and put this on hold until that one is resolved.

**Comment by amulware** [comment]
For better or worse, we'll have to wait for backend to change the api. Issues is referenced.

**Comment by simonrozsival** [comment]
The good thing about this is that it doesn't affect the way we store data in the database, which would need a migration to fix in the future, this is just a matter of JSON serialization/deserialization.

**Comment by amulware** [comment]
Closing since this won't happen anytime soon.
