### ISSUE TITLE
[onboarding] phase 4: gesture hints should be shown only once

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1963]
Continue and Delete gestures should be shown only once, though when I log out and log back in with the same account (while having at least 5 TE) I can see these hints every time when I'm logged in again.

**Comment by simonrozsival** [comment]
Even though you tapped on them or swiped in the direction to dismiss them? That would be strange 🤔

**Comment by pe0ny** [comment]
Yes. I tapped on the tooltip.

**Comment by amulware** [comment]
In general for now, logout should not reset the saved onboarding state.

#1969 complicates this later.

**Comment by simonrozsival** [comment]
This was closed by #1970 and will be shipped with the next RC of 1.5.
