### ISSUE TITLE
Keep history of previous users

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#1968]
This has to happen in an as anonymous way as possible.

So I propose that, upon logout, we store the user's email (salted and hashed) in the OS provided storage with a timestamp.

For the hashing, we can do something like `sha1(lowercase(email + salt))`. We can use a random guid for the salt.

Note that we also have to store the salt of course.

- [ ] Have a nice interface abstracting this all away, which is called on log out
- [ ] Compute the salted, hashed email
- [ ] Persist the hash and salt
- [ ] Persist the current time
- [ ] Have an easy way of checking if and when a given email was used before
- [ ] Have it keep track of an arbitrary number of previous users
- [ ] Have it correctly _update_ an existing user record if the same user logs out a second time

**Comment by amulware** [comment]
We still need confirmation from product if we can do this.

**Comment by syko** [comment]
From what I can see it's ok. Hashing does not fall under Export of Cyptography.
Green light

**Comment by amulware** [comment]
This is complicated, dangerous, and has no significant benefits.
