### ISSUE TITLE
Ask users to rate us in the app

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1972]
## A/B Testing
We would like to ABCD test when is the best time to ask rating from the users.

~a) Show this pop to users who have at least 10 time entries in total over the course of 5 distinct days & trigger the popup when user is on the Timer page & stops the time entry by tapping the red Stop button.~
~b) Show this pop to users who have at least 10 time entries in total over the course of 5 distinct days & trigger the popup when user is on the Timer page & the TE is currently running.~
~c) Show this pop to users who have at least 20 time entries in total & have used the app at least 14 days & trigger the popup when user is on the Timer page & stops the time entry by tapping the red Stop button.~
~d) Show this pop to users who have at least 20 time entries in total & have used the app at least 14 days & trigger the popup when user is on the Timer page & the TE is currently running.~

~👆 This part is WIP, so feel free to suggest ideas. Main thing we should keep in mind is that we should target users who are actually a bit more familiar with the app and use it. We don't want to annoy first-second day users who are very much in the discovering mode.~

### 📣 Update

We want to test when is the best time to ask feedback/rating from the users and for that we came up with **3 different triggers**:
1) Show the popup when user is on the Timer page & stops the time entry by tapping the red Stop button.
2) Show the popup when user is on the Timer page & continues any TE (either using a swipe to continue or tapping the continue button on a log or the suggestion item).
3) Show the popup when user is on the Timer page & started a new time entry (comes from the Start view and did confirm the changes there).

In addition to these ☝️ We want to test different time periods how long user has been using the app:
a) after 5 days
b) after 10 days
☝️ These will be managed in Firebase and we can change those if needed.

### 💡Other things to keep in mind
- [ ] Don’t block the UI. Meaning that user can continue his flow (starting a new entry, go to reports etc) if he wants to.
- [ ] When user hasn’t interacted with the card in a 5 min, hide it and don't show it anymore.
       - When the app goes into background and user comes back before 5 mis has passed, he/she can still see the popup. After 5 min, the popup will be hidden.
      - When user closes the app completely, the popup will be hidden despite the time passed.

### ❓Do we ever wanna show it again?
In the future we might wanna show it again and for that let's store locally: Which one of the 7 options user ended up with and when.

**7 options:**
- No iteraction
- Yes
- No
- Rating: yes
- Rating: no
- Feedback: yes
- Feedback: no

## Flow
Enjoying -> Yes -> Would you mind rating on the App Store? -> Yes -> App Store popup i.e. sytem rating prompt https://developer.apple.com/ios/human-interface-guidelines/system-capabilities/ratings-and-reviews#system-rating-and-review-prompts
Enjoying -> Yes -> Would you mind rating on the App Store? -> No -> Close the popup
Enjoying -> No -> Would you mind giving us some feedback? -> Yes -> Open feedback form
Enjoying -> No -> Would you mind giving us some feedback? -> No -> Close the popup

## UI notes
- [ ] Display the Rating card below the suggestions (if there are any) or just at the top of the page below the nav bar if there are no suggestions.
- [ ] Padding from the Suggestions/Nav bar: 24pt.
- [ ] Padding from the Log: 56pt for the first popup (step1) - when second/third one appears, the log content remains to the same position.

### Step1: with and without suggestions
![toggl - ios - timer - rate - step1 1x](https://user-images.githubusercontent.com/5064445/40157113-f27c9a58-59a5-11e8-864c-28ce44467b1d.png) ![toggl - ios - timer - rate - step1 no suggestions 1x](https://user-images.githubusercontent.com/5064445/40157116-f3f567fc-59a5-11e8-87ce-5c6edc8a6e4f.png)

Zeplin: https://zpl.io/VDOWvzr & https://zpl.io/brrL7E5

### Step2: v1 When user said "Yes" in the step1
![toggl - ios - timer - rate - step2 rating 1x](https://user-images.githubusercontent.com/5064445/40157120-f9fbcd26-59a5-11e8-93d1-683f2108b995.png)

Zeplin: https://zpl.io/VkmeNnM

### Step2: v2 When user said "No" in the step1
![toggl - ios - timer - rate - step2 feedback 1x](https://user-images.githubusercontent.com/5064445/40157124-fe0d70c2-59a5-11e8-9c69-201c63702fdb.png)

Zeplin: https://zpl.io/VxkwJ1m

**Comment by amulware** [comment]
Which test group the user belongs to should be decided randomly on app start, and stay fixed. (Store it in the OS key/value storage) That key is specific to this UI.
(Unless we decide to use firebase provided AB testing systems, but we would have to investigate more first.)

Ideally, the different options are not super hardcoded into the UI so that we can change the triggers without too much worry (and in the future remove those that work worse).

I also want two events tracking this:
1. When the view is shown. Only property is what test group it belongs to.
2. When the user reaches the end of the flow. Properties: test group, which end was reached.
(Again this might change depending on if we use firebase systems.)

**Comment by amulware** [comment]
If anybody starts working on this before the trigger requirements are fleshed out, feel free to just implement the UI and main functionality and have this be triggered for example on stopping a time entry.

Be watchful when testing this that iOS might refuse to show the rating dialog a second time (until possibly months have passed). They have a spam-prevention mechanism in place there.

**Comment by amulware** [comment]
Note: to make sure we can test this properly, let's NOT have it actually open the iOS ratings dialogue for now. Let's instead show a dummy dialogue that we can use for testing repeatedly.

**Comment by amulware** [comment]
Information gathered in #2056 sounds good. We'll try using Firebase for the A/B testing.

**Comment by pe0ny** [comment]
See also #2150 to see what we wanna track.

**Comment by amulware** [comment]
And please remember this:
> Note: to make sure we can test this properly, let's NOT have it actually open the iOS ratings dialogue for now. Let's instead show a dummy dialogue that we can use for testing repeatedly.
