### ISSUE TITLE
No error displayed on invalid email signup

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#1977]
Attempted to sign up in 1.5 with an email address with spaces or over 200 characters or with no @ or .com and there is no error message to display that the email is invalid.

**Comment by amulware** [comment]
Was there a message in 1.4.x?

**Comment by simonrozsival** [comment]
I don't think there was ever an error message - the "next" button is just disabled until you enter a valid email. Maybe it would be better UX if we didn't ignore that tap, but showed the user an error message that his/her email is not valid 👍

**Comment by amulware** [comment]
Closing in favour of #1223
