### ISSUE TITLE
Copy, Paste, Select All fields in Password only display momentarily

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#1981]
The copy, paste and select all options only display for a fraction of a second on the password field so it's quite difficult to select all and delete or paste a password there.

Not sure if this is localised or device specific or even something we can change.

**Comment by amulware** [comment]
This occurs for me for both email and password fields, the 'paste' bubble disappears within half a second or so after opening.

**Comment by amulware** [comment]
This issue no longer occurs for me in the latest release. I'm going to close this. If this still happens or reoccurs, please create a new issue.
