### ISSUE TITLE
Ask users to rate us in the app: track events

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#1986]
Track events when we ask users to rate us in the app #1972
- [ ] Track how many users see the popup (step1)
- [ ] Track how many users tap "Yes" in step1
- [ ] Track how many users tap "Not really" in step1
- [ ] Track how many users tap agree to rate us in step2 (rating)
- [ ] Track how many users tap disagree "No, thanks" to rate us in step2 (rating)
- [ ] Track how many users give the rating (sytem rating prompt)
- [ ] Track how many users tap agree to give us feedback in step2 (feedback)
- [ ] Track how many users tap disagree "No, thanks" to give us feedback in step2 (feedback)

**Comment by amulware** [comment]
Copy from #2150:

>Let's do this with three events:

>showed the view to the user
user completed first step (property: yes/no)
user completed second step (outcome: 4 different possibilities)
That should give us all the data we want without needing tons of events, and it also makes it easy to compare the different options at each stage.

I suspect this will all be done in foundation, so I'm closing the other issue and fixing the labels accordingly.
