### ISSUE TITLE
OpenAPI file

### ISSUE THREAD

**Issue by quangkieu** [toggl/mobileapp#1991]
Hi,
I wonder if you guys have OpenAPI file or Swagger so that I could point to for easy integration.

Reguard.

**Comment by amulware** [comment]
Hey @quangkieu,

You can find some documentation on our API here: https://github.com/toggl/toggl_api_docs/blob/master/toggl_api.md

It's not entirely up to date, but a good place to get started. We'll have a new set of documentation sometime down the line, but I can't give you an ETA on that.
