### ISSUE TITLE
Step 2 isn't showing in onboarding

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2011]
Was prompted "“You’ve created your first time entry 🙌
Tap to edit it”"

Upon clicking on the entry "Categorize your time with projects” isn't showing

![image](https://user-images.githubusercontent.com/18132080/39563265-8ebf3712-4eee-11e8-9d2f-39205ea1ce49.png)

Per issue https://github.com/toggl/mobileapp/issues/1520 this should be showing the first time editing a time entry

**Comment by amulware** [comment]
Did you just sign up in the app with this user (without logging out and back in)?

As per the linked issue:
>  Only show this phase to users that are new users and signed up in the app!

**Comment by ApocalypticFish** [comment]
Yep, brand new account

**Comment by pe0ny** [comment]
I'm not sure if it's related but have vice versa situation. "Categorize your time with projects" appears but "You've created your first time entry" doesn't.

**How to reproduce:**
1. Fresh install
2. Sign up
3. Tap "Start" button
4. Start view -> Tap Save/Checkmark
5. Timer page -> Tap the card to edit 
6. Edit view: "Categorize your time with projects" appears -> Tap "Confirm changes"
7. Timer page -> Tap "Stop" button

"You've created your first time entry" should appear like mentioned here #1520 but it doesn't.

**Comment by ApocalypticFish** [comment]
Oh, so it shows if you edit before you've stopped your first entry? Did you get the Stop entry prompt? @pe0ny

**Comment by pe0ny** [comment]
@ApocalypticFish Yes, and it's ok to show the prompt before I've stopped the first entry. Only condition there is: `Show it the first time when entering edit view`
And yes, I also get the Stop entry prompt.

**Comment by simonrozsival** [comment]
I know what the problem is. Both are connected, @pe0ny, which is the problem. I will fix this ASAP.

**Comment by simonrozsival** [comment]
The fix was merged into a release branch.
