### ISSUE TITLE
App crashing for existing user when Starting a new time entry and selecting "No Project"

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2013]
The app crashes when I start a new time entry from the start button,
Select a project and select "No project" from any workspace regardless of default or other.
The app crashes.

This behaviour does not change if I've selected a description or tag.

Repeated this several times on several clean installs with several accounts.

Accounts had multiple and single workspaces and regardless always crashed when I selected no project.

**Comment by simonrozsival** [comment]
Fix was merged into the release branch.
