### ISSUE TITLE
New Log in UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2022]
- [x] New Log in UI replaces the currently in use last onboarding step (blue screen with illustrations and login/signup buttons).
- [x] New Log in UI contains all needed fields and inputs: Email and Password field, Password manager, Forgot password, Google Log in, and option to switch to Sign up page.
- [x] By default, all the fields are not focused.
- [ ] The error message should show below the associated field (if we know which field is wrong). Focus should be kept in that field still
_e.g. Not a valid email address error, should appear below the email field_
- [ ] If the error is not associated with a particular field, then we should remove focus from all fields and display the error under the Password field
_e.g. We couldn't log you in error should appear below Password field as in the mockup_
- [x] When the form can't be submitted, disable the main "Log in" button. Text opacity = 48%
- [ ] Use default input field styling with label and error messages – adjust colors to match app colors.
   *e.g. When Email field is focused or when user has already typed something in, then the placeholder moves up.*
- [x] Bottom card is always positioned at the bottom of the screen and directs user back to the Sign up page. The whole card should be tappable.
- [ ] When the keyboard is closed padding from top of screen is 88dp
- [ ] When the keyboard is open padding from top of screen is 48dp
*The goal is to keep "Forgot your password link" above the keyboard whenever possible, but still have a top/bottom balanced layout on the Login screen when the keyboard is closed*

### Log in page
![log in](https://user-images.githubusercontent.com/5064445/39583552-0706bbdc-4ef9-11e8-89ce-5386becca232.png)

Zeplin: https://zpl.io/25yo4Y0

### Error message
![log in - step2 error2](https://user-images.githubusercontent.com/5064445/39583802-96fbcb56-4ef9-11e8-8d0a-122f461a41f0.png)

Zeplin: https://zpl.io/a8EAPY6

### Loading state
![log in - step2 password entered](https://user-images.githubusercontent.com/5064445/39583845-af14d76e-4ef9-11e8-87d1-f6aa0cad0f2a.png)

Zeplin: https://zpl.io/an6PYWl

**Comment by arturs105** [comment]
Please work on this only after #2018 has been merged, since it contains `Foundation` code for the new login view.

**Comment by arturs105** [comment]
#2018 Has been merged and we now have `NewLoginViewModel` and `LoginViewModel`. For this screen you should use the `NewLoginModel` and once the whole thing has been implemented, remove `LoginViewModel`, `LoginViewModelTests` and all other files that become unnecessary, since those things were kept to keep Android working. Oh and rename `NewLoginViewModel` to `LoginViewModel` (the tests as well).

Also please update the `OnboardingViewModel.login()` method, since currently it is pretty ugly to keep Android and iOS working.

**Comment by willsb** [comment]
As discussed internally, we will test an RC before (if ever) implementing the unchecked points
