### ISSUE TITLE
New Forgot your password UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2023]
- New Forgot your password UI is accessible from the Log in page.
- User can use "Back" button on the nav bar to navigate back to the Log in page.
- If user entered already the email in the Log in form, use the same email to auto fill Forgot your password form. If user didn't enter anything, keep the field empty.
- Auto focus the email field when user opens this view.
- When resetting the password succeeded, make sure the keyboard is closed and show Done card at the bottom of the screen. (Card is positioned 40pt from the bottom.) Display the card for 4 seconds and then auto navigate back to the Log in page.
- Email field is always positioned 64pt from the nav bar on smaller screens (SE), and 136pt on bigger screens.
- Button is always positioned 32pt from the bottom.

### Forgot your password view
![toggl - ios - forgot your password 1x](https://user-images.githubusercontent.com/5064445/39593944-f6d88450-4f13-11e8-9b8f-e8e82bda72c6.png)

Zeplin: https://zpl.io/VDlYABe

### Forgot your password view: error message
![toggl - ios - forgot your password error 1x](https://user-images.githubusercontent.com/5064445/39593946-f84e1cf0-4f13-11e8-8ebc-15855a83acd4.png)

Zeplin: https://zpl.io/2pojE9o

### Forgot your password view: done
Copy: "Link sent. Please, check your email to reset the password."

![toggl - ios - forgot your password done 1x](https://user-images.githubusercontent.com/5064445/39705370-e406d894-5216-11e8-877b-7f5c990b70db.png)

Zeplin: https://zpl.io/a3voRGA

### Log in: password is reset
![toggl - ios - forgot your password ok 1x](https://user-images.githubusercontent.com/5064445/39594551-9de463a8-4f15-11e8-860d-738ea3c818d7.png)

Zeplin: https://zpl.io/adAwgO7

**Comment by amulware** [comment]
If the user navigates back to the login page, should we reflect changes to the email field there? will the password field be reset or the same as before?

**Comment by pe0ny** [comment]
When the user navigates back to the login page then the password field should be reset.
Email filed in the Log in view should remain the same as it was in the Log in page, unless user editited the email field in the Forgot password view -> then we should use that one in the Log in page.
