### ISSUE TITLE
Sign up flow changes: Active consent to our Terms of Service

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2027]
Check #1611

## Active consent to our Terms of Service
- “By signing up you agree to terms of service…” can no longer be just a passive text or pre-ticked checkbox. This means the user must “actively” consent, so e.g. tick a box or push some “Agree” button, in order to create an account. We decided to use two-step sign up and ask user to interact with "I agree" button.
- Open this popup after user taps "Sign up for free" button in the Sign up view #2025
- Send the form to the BE after user has tapped "I agree" button
- User can close the popup by tapping on the background. Then user will be directed back to the Sign up page. Fields that user filled in before must remain filled.
- ToS: https://toggl.com/legal/terms/
- PP: https://toggl.com/legal/privacy/

### ToS & PP popup
![sign up - step3](https://user-images.githubusercontent.com/5064445/39595397-0fae90d8-4f18-11e8-9442-bd388f8c7c33.png)

Zeplin: https://zpl.io/brr6oKr

**Comment by arturs105** [comment]
For this you should use `TermsOfServiceViewModel` from #2070.

**Comment by juanlaube** [comment]
I'm adding an empty ToS activity with the minimum things to make it work because I need to present it from the Sign Up screen, wait for that PR to be merged to start working on this.

**Comment by kornelijepetak** [comment]
@juanlaube I think this should be a fragment, and not an activity. (@willsb, please confirm this). Have you pushed it somewhere already? I wanted to start this working on this issue, but I am not sure of its current state.

**Comment by juanlaube** [comment]
Yes, it should be a fragment. I had an activity in my branch however, but I deleted it since William is doing it.
