### ISSUE TITLE
Stage 4 of onboarding, swipe left to delete doesn’t disappear when one entry has been deleted

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2028]
Fresh install
New sign up
Stage 1 shows correctly (start stop timer etc).
Stage 2 shows correctly (edit entry, add project, tag)
Stage 3 shows correctly upon new tone entry creation
Stage 4 swipe right to continue shows and disappears when entry is continued or prompt is tapped on.
Swipe left to delete disappears momentarily after the entry is deleted and then continues to show provided there are >5 entries or reappears as soon as there are at least five entries again. Does not reappear if it is tapped on to dismiss.

**Comment by simonrozsival** [comment]
The gesture recognizer for the left swipe is very fragile :( unless we want to force the user to always delete the time entry and we want to leave the option to release the gesture, we have to stick to the gesture recognizer which can be disabled by the UI in some cases.

**Comment by amulware** [comment]
I'd say it's good enough. Users can tap the popup to make it go away.
