### ISSUE TITLE
[GDPR] Ask existing users to agree with new ToS & PP

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2030]
**More info coming soon!**
**Endpoint is still WIP**

- After May 25th, we have to ask users to agree with the new ToS & PP if they haven't already.
- This popup can't be closed which means the user can't use the app unless he/she agrees to the new terms.
- Show this popup to all users who have not agreed to new ToS & PP starting from May 25th 00:00 UTC when they open the app.

### New ToS & PP popup
![toggl - ios - error tos 1x](https://user-images.githubusercontent.com/5064445/39615159-4df129fe-4f7d-11e8-84b4-a7d0ff474cfb.png)

Zeplin: https://zpl.io/aRqEdkz

**Comment by amulware** [comment]
For now, we can make the UI, but without the endpoint, we can't integrate it properly, and I can't give an ETA.

**Comment by amulware** [comment]
There is also no way to fully test this unless backend provides us with something.

**Comment by amulware** [comment]
Note this has to correctly interact with the following cases:

- user is offline (display error `NEEDS-DESIGN`, telling the user that they have to be online to accept)
- something else goes wrong (server error? request malformed? no idea what to do in this case - we could complicate the whole thing and store the acceptance of the terms in the database and sync them later - I REALLY rather not)
- user resets api token (the re-login interface is shown, it has much higher priority than this)
- app is out of date (the update interface is shown, it has much higher priority too)

**Comment by amulware** [comment]
Given the relevant backend stuff is still WIP, this remains on-hold for now.

**Comment by refiito** [comment]
endpoint to accept ToS - `v9/me/accept_tos`
just a post, no content
responses: 
200 - OK - everything got saved
400 - user has already accepted the ToS - "You already accepted" or something similar should be shown
500 - internal error, something went bonkers

to trigger the dialog:
`v9/me/preferences` will have a `ToSAcceptNeeded` field, show screen if its present and true

**Comment by amulware** [comment]
If the user does not accept, strictly speaking we need to let them close their account. Currently, there is no way to not accept at all, how shall we do that? We should at least let them log out, potentially tell them that they can close their account on our website?

**Comment by amulware** [comment]
Also note, with this being included in the preferences, we have to think about whether we store it or just trigger the dialog when we pull it. If we store it, we have to make sure to re-pull after accepting, without accidentally showing the dialog twice (tricky to ensure this!).

If we don't store it, we have to think about what to do when the user force-quits and relaunches the app. Do we have to put in a special flag like we do with 418 or invalid api token? If so, what if the user accepts the ToS in a different client?

**Comment by amulware** [comment]
Regarding testing this: I brought it up with backend, but we need to talk more to see what's possible. In the worst case, we should be able to coordinate for some manual testing. In the best case, I want integration tests for this.

**Comment by amulware** [comment]
We are not using `me/flags` - I was not even aware that is a thing. And yes, I agree that there shouldn't be a ton of endpoints for different triggers. Not sure that preferences is the best place though? Also, if the idea is that more events might be added in the future, please don't add them all as fields to an object. Give us a list of events to trigger, like:

```
{
    "handleMePlease" : [ "ToSAcceptNeeded", "ConfirmUserEmailNeeded", "AskToUpdateCCDetails", "whatever" ] 
}
```

or similar.

**Comment by amulware** [comment]
@pe0ny define 'when the user is connected to the internet'

Do you mean that if the user gets this dialogue, and then restarts the app, it's gone again, until we are able to sync and notice (again) that we should show it? So if the user is then offline they can keep tracking offline?

**Comment by fonorobert** [comment]
since we can't really allow the user to use the service without accepting anyway, i'd say it's ok to not give them access to unsynced entries unless they accept. so imho no trickery needed with offline/online status, just show the dialogue and then if they accept, try to push that to BE. if no internet then, the user should try again.

**Comment by pe0ny** [comment]
In addition, we also add small text there: "If any questions, please contact support@toggl.com”

Wwhen the user opens the app (no matter if being online/offline):
1) Popup opens
2) User taps “Agree” -> Push this to BE

If the user is offline:
3) We’ll display a message: “You're offline. Please connect to the internet and try again.” 

I'll work on designs.

**Comment by amulware** [comment]
Great! What about the case where the user restarts the app?

**Comment by pe0ny** [comment]
Based on what Margus already said:

We have a `ToSAcceptNeeded` field. If it's true, we'll trigger the popup.

**Comment by amulware** [comment]
It's still up to debate (or backend fiat) how we'll fetch this flag, but:

- we'll fetch it on pull sync
- if we do and it's true, we'll show the popup
- user can agree (if it fails we tell them to try again)
- we don't persist anything
- we don't stop sync

This is the simplest implementation as far as I can tell, and it's good enough.

@pe0ny when updating designs, consider if there should be an option to logout or information about closing accounts if they don't wanna accept. Otherwise, they get sort of stuck in the app until they reinstall, if they wanna use a different account (unless we really don't care about this tiny tiny minority edge case).

**Comment by pe0ny** [comment]
@amulware I understand the reasoning of "Log out" option but we should let the user know when they have unsynced data because otherwise they'll lose it.

**Comment by amulware** [comment]
Yes, it's a complex system. I don't know how to best handle that. The best idea I have is to warn the user that data unsynced data might be lost.

Business logic wise we're supposed to make the user close their account, but we don't support that in the app right now. Maybe we should, maybe we shouldn't. Up to product imo.

**Comment by fonorobert** [comment]
imo it's enough if we add a line to the copy directing ppl to contact support for help with that.
something along the lines of "If you have any questions, contact us at support@toggl.com"

**Comment by pe0ny** [comment]
Updated design:
![toggl - ios - error tos 1x](https://user-images.githubusercontent.com/5064445/40366429-c5cc18ec-5ddf-11e8-8987-784cb90e661c.png)

**Comment by amulware** [comment]
Closing as won't-do unless this actually gets sorted out properly internally.
