### ISSUE TITLE
Tag text is not visible in Edit View

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#2039]
Probably just a color issue because the width of the tag is OK. So the data is probably fine. Maybe some of the changes in previous PRs introduced this problem.

![image](https://user-images.githubusercontent.com/7033216/39688309-5f8408b0-51d2-11e8-8a47-37cdfad8f8a0.png)

**Comment by kornelijepetak** [comment]
I am not able to reproduce this anymore. It was probably a fluke at that point.

If someone sees this again, please reopen.

**Comment by kornelijepetak** [comment]
It seems that this happens again, unfortunately, but without known repro steps 😢

**Comment by pe0ny** [comment]
How it should look like:
![screenshot_20180515-093705](https://user-images.githubusercontent.com/5064445/40040665-d0957294-5823-11e8-9df2-195121d9ffe6.png)

What happens after using the app for a while:
![screenshot_20180515-093555](https://user-images.githubusercontent.com/5064445/40040674-d841747a-5823-11e8-820e-ce766561319f.png)

Sometimes the background also turns to yellow.

**Comment by pe0ny** [comment]
Steps to reproduce:

1. Open the app
2. Open the TE that has tag(s) -> Background is OK (light blue) -> Go back to Timer page
3. Open Reports -> Go back to Timer page
4. Open the TE that has tag(s) -> Background is OFF (dark grey)

**Comment by pe0ny** [comment]
I'm opening this again because with the steps above you can still reproduce.

**Comment by pe0ny** [comment]
Tags still turn to dark:

![screenshot_20180525-081013](https://user-images.githubusercontent.com/5064445/40528817-dc04a40e-5ffa-11e8-9a42-a326438023fb.png)

**Comment by kornelijepetak** [comment]
It is a different issue, but the solution is the same, so let me fix this.
I will also look at all other places where we use the same background type and fix them too.

**Comment by kornelijepetak** [comment]
This should now be closed for good as the source of the problem was exterminated.
