### ISSUE TITLE
Time-date-duration popup fixes/improvements

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2040]
Remaining features to implement:

* [x] Preventing selection in controls (min max dates etc)
* [x] Consolidate header colors between tab header and controls
* [x] Apply user's settings for formatting dates and time
* [x] Integrate popup with the start view as well
* [x] Prevent one second initial delay

**Comment by kornelijepetak** [comment]
Refs #2010

**Comment by pe0ny** [comment]
**Start/stop content is empty when opening Duration tab first**
1. Open the edit view and tap on the Duration field -> Popup opens
2. Tap either Start or Stop tap -> Content is missing
After tapping Start/Stop again, the content appears.

**Comment by kornelijepetak** [comment]
This has already been reported [here](https://github.com/toggl/mobileapp/pull/2010#issuecomment-386738784).

**Comment by pe0ny** [comment]
**"Stop timer" button doesn't disappear**

1. Open the edit view when entry is running
2. Tap "Set" -> Popup opens
3. Tap "Stop timer" button -> Time entry is stopped but the button is still there though it shouldn't be.

Note: The button is visible even for already stopped entries.

**Comment by pe0ny** [comment]
☝️ And that one too. Nvm me then.

**Comment by kornelijepetak** [comment]
☝️ That one has already been fixed 😄
