### ISSUE TITLE
Integrate with Facebook

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2049]
We want minimal integration only, just so that we can measure the effectiveness of Facebook ads.

There is a lot of useful information here: #1923

Please coordinate the integration with @djalex15 and make sure that all secret keys etc. are treated appropriately.

Please also test the integration in debug mode, just to make sure that whatever we are sending gets through correctly.

**Comment by Odrakir** [comment]
Why is this labeled iOS? Are we not doing it for Android or just not yet?
