### ISSUE TITLE
Custom feedback screen internals

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2075]
Backend will make us a custom feedback endpoint so that we don't have to rely on email availability.

That endpoint will also allow us to send more custom data without presenting it to the user or giving them the option to change it.

Here is a list of things that I can think of that I would like to send:
```
- phone model
- platform and os version
- app name and version
- number of workspaces available to the user
- number of time entries in our database (total, unsynced, unsyncable)
- time of last attempted sync
- time of last successful (full?) sync
- time of sending this feedback thing
- manual mode setting
- time of login
```

Maybe there is more, but this is my list right now. The idea here is that this data should allow our support people to help debug things faster without having to go look at user data or having to ask questions we can give them the answers to already.

**Comment by amulware** [comment]
Note the backend issue for the format of the data expected. It's basically key-value tuples which should serialise trivially from a Dictionary<string, string> (maybe cast to Enuemerable<KeyValuePair<string, string>>).

**Comment by amulware** [comment]
This is probably blocked by https://github.com/toggl/mobileapp/issues/2350

**Comment by simonrozsival** [comment]
We are waiting for the API to be implemented and deployed.
