### ISSUE TITLE
Reports: calendar is taking almost the whole screen when open in some months

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2082]
It looks like the calendar is taking too much space sometimes.
It gets hard to close it scrolling the calendar up.

Maybe we could reduce the distance between the quick selection tags and the calendar?

<img src="https://user-images.githubusercontent.com/2173493/39839054-01c6f5d8-53a9-11e8-8033-20b2d65bc6a8.png" width="240">

**Comment by willsb** [comment]
Adding `needs-design` and pinging @pe0ny

**Comment by pe0ny** [comment]
In the design, the padding between the Calendar and Shortcuts is already a lot smaller. Please, check zeplin https://zpl.io/bzYRl3A
