### ISSUE TITLE
Cannot create new account. 

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2089]
On the sign up password page it displays "please select your country" and there is no country entry field, and it won't let you leave the page or continue through to create an account, there is no country selection field. 
![screenshot_20180510-172605](https://user-images.githubusercontent.com/18132080/39859184-1c95275c-5478-11e8-9f32-6a3849400225.png)

**Comment by amulware** [comment]
This might become invalid once we replace the signup/login flow. Let's be sure to check it afterwards though.
