### ISSUE TITLE
App crashes when selecting No Project

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2090]
When creating a new time entry, if "No Project" is selected from either default or an alternate workspace, by clicking on the Project folder icon when starting the entry then the app crashes.

**Comment by ApocalypticFish** [comment]
Start a new time entry

**Comment by daividssilverio** [comment]
Is this still happening? Cannot reproduce it either on the Emulator or an actual device.
Would you let me know the device you are running it?

**Comment by pe0ny** [comment]
@ApocalypticFish I can't reproduce either. Please, let us know if you still can or can't reproduce it on the latest build.

**Comment by amulware** [comment]
iOS fix of this probably fixed both paltforms.
