### ISSUE TITLE
Times in the edit view and in the popup don't match

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2096]
I’m testing the popup again. Edit view shows me 13:40 as a start time and popup shows 10:40. Timezones?

Also when I open the popup from the start view (doesn't happen when i open the popup from the Edit view):

![screenshot_20180510-140019](https://user-images.githubusercontent.com/5064445/39866938-4f9a7462-545b-11e8-860d-5e7f4a876a88.png)

**Comment by kornelijepetak** [comment]
When both #2122 and #2123 are merged, this issue is officially done.

**Comment by kornelijepetak** [comment]
Indeed. 

I'd be great to be able to do dependencies like this :

`Closes after merge 2122 2123`
