### ISSUE TITLE
Date-time-duration popup: editing duration doesn't save the new value

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2116]
1) Open date-time-duration popup -> open duration tab
2) Tap on the duration to edit -> It activates the field but doesn't open the keyboard.
3) I'll tap again and then the keyboard opens

Is it possible to open the keyboard right on the first tap?

Also,
1) Previous value was 30min
2) Tap in 25 and tap "Ok" -> Duration is still 30min

**Comment by kornelijepetak** [comment]
Fixed by #2189
