### ISSUE TITLE
Date-time-duration popup: Fix position from the top

### ISSUE THREAD

**Issue by lizaPlotnikova** [toggl/mobileapp#2125]
Currently, the datetime popup is centered on screen. Could we please fix it so that the margin above it is 40dp? It feels a bit less jumpy this way:

![top of dialog fixed](https://user-images.githubusercontent.com/24964497/39943627-a3d2b8f6-5531-11e8-80cb-831906e245e8.gif)

**Comment by kornelijepetak** [comment]
I personally find it nicely animated, and not jumpy. 
But I think we should not do it like you suggested.

If you need it anchored, I believe it's much wiser to anchor the popup at the bottom. If it's at the top, it is *not usable* by a thumb. Trust me, it will bite us in the end. Android phones are statistically larger than iOS phones and people do really use their phones with a single hand. 

So, we will do as @pe0ny and @lizaPlotnikova decide, but indeed think about it again.

**Comment by daividssilverio** [comment]
Well, it doesn't look that different, on my device at least (5 inches). But yeah, I guess it will be a little harder to use on bigger ones (5.5, 6+ inches).

It might look good on the bottom too, let's make a test?

**Comment by kornelijepetak** [comment]
I have 6 inches and 1:2 ratio, trust me, it is far 😛.
But let's wait for reply from our UX masters 😄

**Comment by pe0ny** [comment]
@lizaPlotnikova I agree with the jumpy part. It doesn't bother me that much but it would be nicer if it's fixed. Can you maybe give us an example how this would look like on different screen sizes including the bigger ones?

**Comment by lizaPlotnikova** [comment]
So, simulating what it would look like is a bit tricky, because it's not super-easy to figure out what the dp dimensions of common devices are. 
I used this guide and picked a few sizes that seemed common https://material.io/tools/devices/  
<img width="1214" alt="screen shot 2018-05-24 at 2 28 14 pm" src="https://user-images.githubusercontent.com/24964497/40504582-a66fdf98-5f5f-11e8-984a-0a265f400b64.png">

I didn't mock up the dialog on the bottom, because, as I mentioned in slack (https://toggl.slack.com/archives/C02APMYTM/p1527176877000083?thread_ts=1527170328.000263&cid=C02APMYTM) the original goal was to "fix" the navigation (tabs) so it doesn't jump around.

**Comment by pe0ny** [comment]
@lizaPlotnikova Thanks for the examples and thorough explanation. 🙌

Let's go with the solution Leez proposed and try it out. We can always switch it back to centre if we'll get a bunch of negative feedback about it.
