### ISSUE TITLE
Handle exceptions differently in UnsyncableEntityState

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2144]
Follow up to https://github.com/toggl/mobileapp/pull/2133#discussion_r188272351

The `UnsyncableEntityState` marks entities as unsyncable for app `ApiException`s. 

https://github.com/toggl/mobileapp/blob/08ea30cf00292b95654f7dc2af0a775cefe76636/Toggl.Foundation/Sync/States/Push/UnsyncableEntityState.cs#L34-L39

It should only ever be called with `ClientException`s though.

Maybe it's worth changing this to be more strict and only allowing 'valid' exceptions?

Thoughts welcome.

**Comment by heytherewill** [comment]
♻️
