### ISSUE TITLE
Play button disappears on App after crash 1.5 (1284)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2147]
(V1.5(1284))
The play button disappeared after a crash.
Then on trying to continue any entry the app just appears to reattempt to sync.
Upon force closing the app, the play button is showing and there was a time entry running that wasn't displayed.
![syncissue1](https://user-images.githubusercontent.com/18132080/40093733-a76aea90-5902-11e8-9cb3-3effd1933e51.gif)

**Comment by amulware** [comment]
Is this still a thing? If not, please close.

**Comment by sofokli1** [comment]
not sure how to test this

**Comment by amulware** [comment]
@ApocalypticFish Do you have steps to reproduce? If not, please close this.

**Comment by amulware** [comment]
No steps, no issue.
