### ISSUE TITLE
Ask users to rate us in the app

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2149]
## Shared code
Already implemented on iOS in #1972. All we need is the equivalent Android stuff.

## Flow
Enjoying -> Yes -> Would you mind rating on the Play Store? -> Yes -> Direct user to the Play Store page *(If anybody starts working on this, please, let me know if it's possible to direct user directly to the rating part in the Play Store)*
Enjoying -> Yes -> Would you mind rating on the Play Store? -> No -> Close the popup
Enjoying -> No -> Would you mind giving us some feedback? -> Yes -> Open feedback form
Enjoying -> No -> Would you mind giving us some feedback? -> No -> Close the popup

## Other notes
- [ ] Display the Rating card below the suggestions (if there are any) or just at the top of the page below the nav bar if there are no suggestions.
- [ ] Padding from the Suggestions/Nav bar: 16pt.
- [ ] Padding from the Log: 16pt.
- [ ] Don’t block the UI. Meaning that user can continue his flow (starting a new entry, go to reports etc) if he wants to.
- [ ] When user hasn’t interacted with the card in a 5 min, snooze it for 24h.

### Step1
![rate the app](https://user-images.githubusercontent.com/5064445/40095534-4fdc43d2-58d5-11e8-9323-e20ac713735e.png)

Zeplin: https://zpl.io/a7yXemM

### Step2: v1 When user said "Yes" in the step1
![rate the app v2](https://user-images.githubusercontent.com/5064445/40095540-587b1e46-58d5-11e8-8483-45288e5f93eb.png)

Zeplin: https://zpl.io/2EjXNgl

### Step2: v2 When user said "No" in the step1
![rate the app v3](https://user-images.githubusercontent.com/5064445/40095555-60f0526c-58d5-11e8-8032-8bdde387762e.png)

Zeplin: https://zpl.io/VK0XRDR

**Comment by amulware** [comment]
This is blocked by #1972 (and evaluating data from it).

**Comment by amulware** [comment]
I.e. let's not AB test on both platforms, but figure it out on one and apply the best solution to both.

**Comment by amulware** [comment]
Off hold! We want this now. :)

**Comment by amulware** [comment]
If this issue can be split up into multiple, maybe even so that multiple developers could work on it, but definitely so that PRs are smaller, that would be great btw. :)

**Comment by lizaPlotnikova** [comment]
Hey guys! There were some problems with how the illustrations were rendering in Zeplin. I uploaded the designs again resolving the issues - the illustrations can now be downloaded as svg. 
The links in Zeplin have changed though; https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e?seid=5afb44def10c455a42071c73
