### ISSUE TITLE
MVX TargetBinding cryptic errors

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#2152]
There are some target bindings that cause this kind of error in the application log, but they do bind the UI correctly. The binding itself is working, but this is output to the log. The `SetValueImpl` does not throw. So it seems like a Mvx bug.

I've tried to see the related code in Mvx, but I seem to be unable to find this kind of error anywhere, so it might just be an artefact of an older MVX version and this might just go away when we update Mvx.

@willsb if you do have any knowledge about this, please advise, or if you know that this will go away with Mvx 6, feel free to state that in a comment and close the issue.

Bindings that create this kind of problem are `Height` and `DrawableColor`. At least those two I have seen. Maybe there are others.

```
MvxBind:Error: 26.71 Problem seen during binding execution for binding Height for MvxValueConverterValueCombiner combiner-operation - problem NullReferenceException: Object reference not set to an instance of an object.
 at MvvmCross.Binding.Bindings.Target.MvxTargetBinding`2[TTarget,TValue].SetValue (System.Object value) [0x00000] in C:\projects\mvvmcross\MvvmCross\Core\Binding\Bindings\Target\MvxTargetBinding.cs:83 
 at MvvmCross.Binding.Bindings.MvxFullBinding+<>c__DisplayClass24_0.<UpdateTargetFromSource>b__0 () [0x00025] in C:\projects\mvvmcross\MvvmCross\Core\Binding\Bindings\MvxFullBinding.cs:185 
```

I have put the `android` label because I haven't noticed this in `Daneel`'s custom target bindings.

**Comment by kornelijepetak** [comment]
With RXFactoring, this will simply go away with time... I don't think we need to do anything special about this. @willsb please confirm.

**Comment by amulware** [comment]
I agree with that assessment.
