### ISSUE TITLE
Tap and hold commands disappearing in a fraction of a second 1.5 (1284)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2153]
In the description field of a new time entry.
Attempted to tap and hold to Select All then Copy and Paste.
Tap and hold commands window disappears in a fraction of a second leaving it impossible to react in time.

![tapandhold](https://user-images.githubusercontent.com/18132080/40098799-741226c6-591c-11e8-8045-2c67cef3f81f.gif)
![tapandhold2](https://user-images.githubusercontent.com/18132080/40098800-74590302-591c-11e8-9a71-1d6b98836170.gif)

**Comment by ApocalypticFish** [comment]
This has been on all versions thus far and seems most prevalent when starting a time entry.

**Comment by amulware** [comment]
Is this the same/related to https://github.com/toggl/mobileapp/issues/1981?

**Comment by arturs105** [comment]
Nope, these issues are different.
