### ISSUE TITLE
Tags not syncing properly on 1.5 (1284)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2154]
(V1.5(1284))
Selected existing tags on a new time entry or editing an existing entry.
Clicked done on the entry or green tick.
Sync error symbol is displayed on the entry.
Click on the entry and the OOPS! Invalid tag_ids error is displayed.
De-select the tags and sync, then OOPS! User cannot access the selected project.(Provided a project is selected) and it no longer seems possible to sync.
![tagidissue](https://user-images.githubusercontent.com/18132080/40099952-60037edc-5921-11e8-800c-681b46b0b84c.gif)
![tagidissue2](https://user-images.githubusercontent.com/18132080/40100034-aa52c4b6-5921-11e8-82ec-b9b1e2afe931.gif)

**Comment by amulware** [comment]
Is this still happening? If not, please close.

**Comment by sofokli1** [comment]
can't reproduce in app store version
