### ISSUE TITLE
Strange behaviour on timer wheel when trying to edit or create entries V1.5(1284)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2155]
(V1.5(1284))
When attempting to edit an existing entry the timer wheel exhibits the below strange behaviour.
![timerwheel](https://user-images.githubusercontent.com/18132080/40101120-87ffbcf8-5925-11e8-8688-0d7922300d66.gif)

**Comment by simonrozsival** [comment]
From the gif it is not clear, what is the strange behavior. Could you elaborate?

Dragging the wheel by the middle area between the caps moves both the start and end times - that is a feature, not a bug - if that is what you meant by strange - we might consider communicating this behavior with the user better, if it is not clear what is going on.
