### ISSUE TITLE
Syncing animation stuck after going offline 1.5 (1284)

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2156]
Enabled airplane mode
Switched workspaces
Disabled airplane mode
Sync animation just continued and eventually froze.
Force sync wouldn't resolve the issue.
On force close and re-open it was corrected.

![syncafteroffline](https://user-images.githubusercontent.com/18132080/40101896-06356d96-5928-11e8-8d4c-d1d55774227f.gif)

**Comment by amulware** [comment]
Is this still current? If not, please close.
