### ISSUE TITLE
The spinner in the syncing state bar is too big

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2157]
I couldn't find the design of the "Syncing... []" indicator in Zeplin, but this is clearly too big:

<img width="429" alt="syncing-indicator-too-big" src="https://user-images.githubusercontent.com/374616/40101993-e18335d6-58f1-11e8-84b2-764bb7f4536b.png">

Please @pe0ny, could you add screens with the syncing bar states back to Zeplin (synced, syncing, offline, failed)?

**Comment by pe0ny** [comment]
Closing because of this #2281 - we'll redesign the syncing indicator.
