### ISSUE TITLE
The App doesn't react to time zone change

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2162]
How to reproduce:
- go to the app
- start a time entry
- go to the settings, change your time zone
- stop the time entry
- the displayed times will be in the old time zone
- restart the app
- the displayed times will be in the new time zone

I already discussed some ideas in #2127

**Comment by simonrozsival** [comment]
I have no idea if this problem is also on Android or not.

**Comment by heytherewill** [comment]
I think @khoi fixed this, am I correct?

**Comment by heytherewill** [comment]
It's fixed
