### ISSUE TITLE
Navigation bar in reports view is transparent on iOS 10

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#2168]
This is probably due to `TopConstraint` being null, so calling `AdaptForIos10()` extension does nothing.
![screen shot 2018-05-16 at 18 47 17](https://user-images.githubusercontent.com/15633003/40128191-b1d0ffa6-5939-11e8-88e0-4b0fc5e6402c.png)

**Comment by arturs105** [comment]
So after further investigation i found out that #2270 actually fixes this, so no additional fix is needed.

**Comment by amulware** [comment]
That PR was merged into develop, however. Can we cherry pick and fix it for the hotfix?

**Comment by amulware** [comment]
Changed my mind. It's not important enough to bother with the cherry pick.
