### ISSUE TITLE
Text selection jumps to front of description after selecting project or tag

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2171]
When creating a new time entry and after selecting/creating a project or tag the text selection jumps to the start of the description. 
Making it not possible to create or select another project or tag without deleting the existing description.

![androidselectingprojectandtaginnewentry](https://user-images.githubusercontent.com/18132080/40165806-14049c9c-59fc-11e8-84d3-5182f582626b.gif)

**Comment by pe0ny** [comment]
Duplicate #2182
