### ISSUE TITLE
App discards any started time entry details that haven't been confirmed

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2172]
If the app is minimized after starting a new time entry, after a description and project are assigned but before the entry has been saved then after a certain amount of time when the app is brought back up again the started entry is discarded and the app appears in the same state before that entry was started.

**Comment by pe0ny** [comment]
Can confirm. Happens to me as well. When the app goes into the background when the Start view is open, the TE will be discarded.

**Comment by kornelijepetak** [comment]
@ApocalypticFish @pe0ny how much time usually has to pass for this to be noticed? I may have too much RAM so it never closes it... hm...

**Comment by juanlaube** [comment]
I've found this happens when opening the app from the launcher, not from the recent apps.

**Comment by pe0ny** [comment]
@kornelijepetak I haven't found any pattern - it's rather random how much time it takes.

**Comment by amulware** [comment]
Is this still being worked on?

**Comment by juanlaube** [comment]
hmm not by me, this should be fixed by the TextFieldInfo refactor.

**Comment by amulware** [comment]
Is this still a thing? As far as I can tell, this can happen with both apps, if they are in the background too long and get killed by the OS, no?

Maybe there is a case to be made to have it... save the TE already when opening the view? We'd need to keep it in a state that doesn't sync probably, but.. maybe? Not sure. Or maybe it could sync, and we'd really just be editing it. Tricky.

**Comment by amulware** [comment]
@ApocalypticFish can you give us an estimate on how often this happens or how often it's mentioned by users?

If it doesn't seem too critical, I'd wait for us to implement proper state restoration for both apps (at least for the start view, maybe edit as well) in the future.
