### ISSUE TITLE
Test the refactored pull&push sync

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2175]
What should be tested:
- [x] initial sync (after login) works well
- [x] pushing preferences change, new tags, new clients, new projects, new time entries works as it should
- [x] pulling preferences works well (change duration format in the web app, pull in the mobile app, the way the durations are displayed in the main log should change without restarting)
- [ ] pulling workspaces, workspace features (change of free => starter - check the visibility billable switch in the edit view) works
- [x] pulling tags, clients, tasks, projects works
- [x] pulling stopped time entries works
- [x] pulling running time entry works
- [x] start a TE A in the app, start a TE B in the webapp, pull in the app -> the TE A should be stopped and B should be running in the app
- [x] deleting and updating TEs works (both pull & push)

Please test any other cases and mention them here in comments.

**Comment by ApocalypticFish** [comment]
Starts an entry fine, when sync occurs the time flashes (00:00) then shows the correct time a few seconds later.
Pressed stop to stop the entry, timer flashed for a moment then continued.
Pressed stop a second time and the app crashed.
![timerstopcrash](https://user-images.githubusercontent.com/18132080/40220134-3c54ed76-5ab7-11e8-9731-bfc8537f20d2.gif)

**Comment by ApocalypticFish** [comment]
If I start an entry on the web app.
Open the mobile app from the closed state.
Then stop the entry.
The app crashes.

**Comment by ApocalypticFish** [comment]
Settings changes from the web app are being synced successfully and are being displayed correctly.

**Comment by simonrozsival** [comment]
a) the thing with `0:00:00` flashing for a brief second - please make a separate issue, this glitch is in the app since the very beginning
b) when you stopped the TE, it correctly showed in the log, but the UI of the app didn't change - so the next time you tapped on the stop button, there was no TE which could be stopped -> the app crashed. This is a very similar problem to the one we had yesterday. I didn't notice this problem when I tested the app yesterday, but I will investigate further and fix this.
c) I will need more information than
> If I start an entry on the web app.
> Open the mobile app from the closed state.
> Then stop the entry.
> The app crashes.
Was there a running TE in the app before? Was the TE that you stopped the one which you created using the web app (i.e., the app was synced and the UI was displaying what it should before you tapped the stop btn) or was it some older TE - either the app hasn't synced yet or the UI showed an incorrect running TE?
d) I am glad that at least ssettings work well 😆

**Comment by ApocalypticFish** [comment]
C) Mobile app had no entry running.

**Comment by simonrozsival** [comment]
Thanks! I will debug this scenario.

**Comment by ApocalypticFish** [comment]
Reports aren't displaying correctly either.
The below gif should show the current and past days entries then when I go to reports and select those days it isn't showing any entries.
![reportssyncupdate](https://user-images.githubusercontent.com/18132080/40226446-d69d7f52-5aca-11e8-8fc6-edcb491ea36f.gif)

**Comment by simonrozsival** [comment]
I am not aware of any changes to the reports' logic in this branch but I will check it anyway 👌

**Comment by ApocalypticFish** [comment]
Started an entry on web and after 90 seconds mobile, while open, it hasn't updated to show the running entry.
Once sync is forced or app reopened from a closed state then it shows the running entry.
When time entry is stopped from web, mobile does not update until sync is forced but attempting to stop the already stopped entry does not cause a crash.
Is the mobile app supposed to check anything periodically when it is opened? or does it only check upon interaction?

**Comment by ApocalypticFish** [comment]
Testing in most recent iOS develop adhoc build.
(pulling preferences works well (change duration format in the web app, pull in the mobile app, the way the durations are displayed in the main log should change without restarting))
Durations aren't updated until after restart, even with forcing sync multiple times

**Comment by simonrozsival** [comment]
- app doesn’t update periodically when it is open - we sync automatically if the app has been in background for more than 5 minutes
- I thought the problem with preferences not being updated was resolved, but it doesn’t seem to be the case - I will test it and see what is wrong, thanks for the feedback

**Comment by amulware** [comment]
@simonrozsival Please create issues for any unresolved issues remaining. I'm closing this.
