### ISSUE TITLE
Investigate Firebase performance metrics

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2180]
It has them: https://firebase.google.com/docs/perf-mon

Let's gather some details below please.

Things like:

- How easy is it to integrate?
- How easy is it to use?
- What kind of data can it show?
- How can that data be evaluated?

And whatever else comes up.

**Comment by willsb** [comment]
Integration is PRETTY simple!

Xamarin provides [iOS](https://github.com/xamarin/GoogleApisForiOSComponents/tree/master/Firebase.PerformanceMonitoring) and [Android](https://github.com/xamarin/GooglePlayServicesComponents/tree/master/firebase-perf) packages for this. We just drop the lib in to get free:

- App start performance metrics (from cold start to app being usable)
- Performance of individual ViewControllers and Activities (containing dropped frame info, for example)
- Performance in Background and Foreground

Regarding custom traces, it seems as cumbersome as creating events (meaning: it's not hard, just looks a bit messy).

I can guarantee that the two first metrics, specially the first one, are of great value. I highly advise considering this for our next release.

**Comment by amulware** [comment]
That sounds good. Let's do it!
