### ISSUE TITLE
🍵 Test App deprecation

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2184]
We either need to coordinate with backend to block test build versions, OR make special builds where we can change the version number at runtime.

Once we have either, we want to test the following:

- [ ] test fresh install
- [ ] test logged in
  - [ ] with everything synced/with data unsynced/offline
  - [ ] with first operation being pull sync/push sync/reports/logout(and then login I suppose)
- [ ] test in all the above cases that there is no way to get past the block (and that no data is synced)
- [ ] test updating in all the above cases to make sure things get reset
  - [ ] test being online/offline when updating to another deprecated version
  - [ ] test being online/offline when updating to a current build
  - [ ] test also with variations of synced/unsynced/whatever to see what happens

**Comment by heytherewill** [comment]
We need this big time now, ping @amulware

**Comment by heytherewill** [comment]
The deprecation strategy can be found [here](https://www.notion.so/toggl/Project-Aurora-The-Great-Rewrite-of-2020-9ea070b5111c41a682e25cb98770d3d2?p=5e4a06a02c1947dda15761c6301df6ae)

**Comment by juanlaube** [comment]
@heytherewill we can close this issue, right?
