### ISSUE TITLE
Google sign up doesn't work

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2192]
1) Open sign up screen
2) Tap "Sign up with Google" -> I'm getting "Sorry, we're having trouble signing you up. Please try again." And the spinner keeps spinning.

**Comment by sofokli1** [comment]
There is a possibility that the parameters needed for google sign-in are only set when we create release build so I would leave this for testing from testflight (not bitrise nightly builds).

**Comment by sofokli1** [comment]
@pe0ny did you manage to test this on the testflight version?

**Comment by pe0ny** [comment]
Yes. I was just about to write a comment here. Google sign in works fine on the Testflight version 🙌 

Jordan tested it as well and all good!

Let's close this issue and keep in mind next time that it doesn't work on adhoc builds.
