### ISSUE TITLE
App crashes first time after clean install

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2211]
The app crashes only once after clean install. Next time when I try to open the app, it works fine.

Can anyone reproduce?

**Comment by amulware** [comment]
I've seen the same.

**Comment by juanlaube** [comment]
I wasn't able to reproduce this on the emulator. Maybe someone with an actual device can? Do we have more info about the device and/or Android version?

**Comment by daividssilverio** [comment]
I wasn't able to reproduce this on my Nexus 5 (Android 6.0). I tried the apk from bitrise and running directly from VS4Mac. But I've seen this happen before too. I'm not sure about the circumstances to make it happen.

**Comment by willsb** [comment]
What device were you using, Heidi? Maybe we can check data in AppCenter to see what gives?

**Comment by pe0ny** [comment]
@willsb I'm using Sony Xperia XA1

**Comment by amulware** [comment]
Should be fixed with #2413
