### ISSUE TITLE
Delete tooltip is constantly showing

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2212]
Fresh, clean install. 
Signed up with new account.
Created time entries as per Tooltips.
Completed instructions for entry deletion tooltip.
Tooltip keeps reappearing/won't dismiss.
![deletetooltip](https://user-images.githubusercontent.com/18132080/40341526-dea09d2c-5dc4-11e8-8228-fae75f638a3a.gif)

**Comment by amulware** [comment]
Can you tap it to dismiss?
