### ISSUE TITLE
Google login doesn't work

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2213]
When I try to log in with Google I will always get this message after selecting an account:
"Sorry, we're having trouble logging you in. Please try again."

Logging in with the same Google account works on iOS though.

**Comment by amulware** [comment]
Is this adhoc or playstore?

**Comment by pe0ny** [comment]
Playstore. Testers have reported the same thing.

**Comment by daividssilverio** [comment]
Should we be able to do it on local builds (running from VS4Mac or Rider or the build.sh script)?
If yes, then it is not working too. Does our CI handle secrets as env. variables?

**Comment by juanlaube** [comment]
@daividssilverio Google login won't work on local builds unless you configure some keys in your environment. I can help you tomorrow with that.

**Comment by kornelijepetak** [comment]
@amulware can we now close this with a good explanation about local environments and stuff in production?

**Comment by kornelijepetak** [comment]
For explanation why this was closed, take a look at the last comment on #2192
