### ISSUE TITLE
Terms and conditions and Privacy policy don't load properly unless page refreshed

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2217]
Clean, fresh install.
Signed up with a new account.
Attempted to access Privacy Policy and Terms and Conditions.
Safari shows failed to load the page, the page displays properly on refresh.
![linksnotappearingtoload](https://user-images.githubusercontent.com/18132080/40351042-96dd4488-5dea-11e8-98e0-5e46837092b3.gif)

**Comment by simonrozsival** [comment]
I get the same behavior in simulator, but it works well for me on an actual device 🤔
