### ISSUE TITLE
After starting a TE and tapping either "Save" or "X", Keepass2Android popup opens

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2221]
After starting a TE and tapping either "Save" or "X", Keepass2Android popup opens and asks to save the password.
For some reason, it thinks that some field is a password input. Let's investigate if we should label some field differently or if it's Keepass2Android issue and we can't do anything about it.

**Comment by pe0ny** [comment]
@daividssilverio https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet

**Comment by daividssilverio** [comment]
It seems like this a new Android feature o/ https://developer.android.com/preview/features/autofill
And @pe0ny we can either disable it by changing our inputType removing the "textVisiblePassword" or adding a flag to our layout. I'm gonna create a PR for the first option unless there's some mysterious reason whey this EditText has this flag.

**Comment by daividssilverio** [comment]
And yes, there was a reason for the inputType. It seems we need that flag to have our projects and tags little boxes on the TE description.
