### ISSUE TITLE
Unassign projects when continuing archived

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2224]
Follow up to #1344 

When continuing a TE that has an archived project, we want the newly created TE to not have a project assigned. In essence, this would make it impossible for users to track more time under archived projects, which is good.

I propose we should a little toast or otherwise unintrusive message informing the user that we did so, and maybe why. That is up to @pe0ny though.

**Comment by pe0ny** [comment]
Closing because of this #2459
