### ISSUE TITLE
Handle nginx errors

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2231]
Sometimes api requests fail in nginx, which usually should be random and not have any significant meaning for us.

The only exception I'm aware of is http 429, which should be handled like we are handling it now: going into the retry loop.

What to do best about the other errors I'm not sure. We could go into the retry loop as well, or simply try again right away? I'm worried that if something is being done wrong from our side though, we might retry the same request over and over and never get there. Maybe it is safer to let sync of the relevant entity fail? Except that we really want to insert our own error message then, and not use the one that nginx returns, because that's ugly html.

Speaking of, the (probably) best way to detect whether an error response comes form nginx is checking the content-type. It always returns text/html, so we could simply filter on that and handle it appropriately.

**Comment by webervin** [comment]
FYI: https://gogs.toggl.space/toggl/boft/src/master/guides/http_statuses.md

**Comment by amulware** [comment]
We need to talk to Backend about this.

**Comment by amulware** [comment]
Did so https://toggl.slack.com/archives/CDRNW2N1F/p1547812797063800
