### ISSUE TITLE
Sign up: Use shake animation to indicate missing/invalid field

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2233]
When the user taps "Sign up" while one of the three (email, password, country) fields is missing/invalid, use the shake animation (like when you enter a wrong password while logging into your mac) to draw attention to that field.

The Sign up button should look disabled but it should trigger the shake animation once user taps on it.

Note: In the country field, the red exclamation mark should be displayed anyways when the API fails. Also, the error message below the password field (if any).

**Comment by amulware** [comment]
I thought the idea was to use the same animation for email/password if missing/invalid?

**Comment by pe0ny** [comment]
@amulware One issue for both? sure. i'll change the title/description then
