### ISSUE TITLE
Log in: Use shake animation to indicate missing/invalid field

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2234]
When the user taps "Log in" while one of the two (email, password) fields is missing/invalid, use the shake animation (like when you enter a wrong password while logging into your mac) to draw attention to that field.

The Log in button should still look disabled but it should trigger the shake animation once user taps on it.

**Comment by khoi** [comment]
@pe0ny If both the fields are invalid. Should we shake just one or do we shake them both?

**Comment by pe0ny** [comment]
@khoi Let's add shake for both of them.

**Comment by khoi** [comment]
Here is how it would look. 
![2018-06-12 14 15 05](https://user-images.githubusercontent.com/6994441/41275421-1072ac96-6e4b-11e8-89dc-6b91d71ed7d3.gif)

**Comment by pe0ny** [comment]
Looks good! Nice and subtle 👍
