### ISSUE TITLE
The background color of `No Project` and `Other` is the same in the reports chart

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2249]
- the two segments blend together when they are next to each other
- it is even more obvious when “Other” is < 10%
    - the title is not displayed (this is now the only segment which might not have the title displayed)
    - it seems like “No Project” is a bit bigger than it should be

Same thing probably could happen for other types of projects. We should somehow separate them.

**Comment by pe0ny** [comment]
Good catch! It's quite hard to make sure that projects with the same colour won't be next to be each other in Reports, especially when the user is on paid plan and can choose whatever colours he/she wants to.

In that particular case: "Other" has a correct colour. "No Project" on the other hand should be darker.

Let's change "No Project" colour to #B5BCC0

**Comment by amulware** [comment]
Change it across the entire app, or only in reports?

**Comment by pe0ny** [comment]
Across the entire app.

**Comment by simonrozsival** [comment]
Fix was merged into the release branch.
