### ISSUE TITLE
Back button title and icon aren't vertically aligned

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#2259]
![screen shot 2018-05-24 at 13 30 11](https://user-images.githubusercontent.com/15633003/40480353-dd2fe694-5f56-11e8-9db1-d8e9048aa1cd.png)

**Comment by pe0ny** [comment]
I think Settings nav bar is too high. Probably the same issue we had on the Timer page.

**Comment by arturs105** [comment]
Yeah, i should have added that info to the issue initially. 🤷‍♂️  But it happens on iOS 10 (tested on 7 and SE simulators).
