### ISSUE TITLE
Hide manual editing on time widget

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#2263]
Pertains to API 26+:
Timepicker on Oreo actually has a button in lower left part that shows the keyboard and another way to enter the time. Since in general, android timepicker is bad and we are hacking it to add calendar icon on top of it, I think it'd be wise to remove the possibility to do this manually with keyboard because, the `Set time` label then overlaps our calendar icon.

@pe0ny please advise.

I hope there's a way to remove it.

![image](https://user-images.githubusercontent.com/7033216/40490195-53cacd5a-5f6b-11e8-95de-4b764d038fdb.png)

![image](https://user-images.githubusercontent.com/7033216/40490227-621c93ac-5f6b-11e8-97b3-7d27a0216e97.png)

**Comment by pe0ny** [comment]
Ideally, I would like to remove the "Set time" label because it's pretty obvious what's this screen about.

But this issue is not a high priority now and not needed for the beta.
