### ISSUE TITLE
Start view: Project gets deleted after moving the cursor to another place and start typing description

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2274]
_This happens both in the Start view in timer and in manual mode._

1. Start a new TE
2. Tap '# Search tags' and select a tag or two
3. Tap '@ Search projects' and select a project
4. Move the cursor at the end of the line and try to add a description

-----> First, the cursor seems to move to the beginning of the input field; when trying to type again the second time, the project gets deleted.

Or another case:

1. Start a new TE
2. Tap '# Search tags' and select a tag or two
3. Tap '@ Search projects' and select a project
4. Move the cursor between the project and tags

-----> When I start typing something inbetween the project and tag, for example, the behavior gets interesting: First, the cursor seems to move to the middle of the tag; when typing the 2nd letter, the project gets deleted.

**Comment by daividssilverio** [comment]
@pe0ny what should be the right behaviour here? 
The user shouldn't be allowed to type in the middle of the tags/projects, right? (that's how it works on iOS).
