### ISSUE TITLE
Sign up UI: show an error when the country is missing 

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2280]
If the country is not selected, show a little exclamation next to it like we do in iOS.

**Comment by lizaPlotnikova** [comment]
Hey guys! Here's the design in Zeplin: https://zpl.io/VOWrnz8

**Comment by amulware** [comment]
I note that the icon in the design is not centered vertically with respect to the text. Is this on purpose?

**Comment by kornelijepetak** [comment]
I think it is, but the text element has some kind of higher baseline or something... In any case I guess it should be aligned.

**Comment by lizaPlotnikova** [comment]
Hey guys! You're right it should be fixed – Let's adjust the font for this ... 

We should be re-using the icon asset, right? It's the same one that appears when the TEs aren't synced.  

As far as fonts go – I was noticing that we don't have consistent font styles throughout the design, and I'm wondering if you guys have any re-usable styles set up? If not, would it be helpful to have a typography "Style sheet" with all of our font styles defined?

**Comment by kornelijepetak** [comment]
I for one would love to have a stylesheet. In general, I am always for more specs than less specs, but of course, must be maintainable and also maintained. Multiple sources of truth are always bad.

But I have also realized that Zeplin has some problems showing specific elements; I can't select some elements to see the dimensions, margins, etc. Not sure if it's the design problem, or the _designer_ problem 😛

**Comment by juanlaube** [comment]
It is the same asset, no duplicates :)

I will fix the fonts.

For the typography in general, I also think a stylesheet is helpful. And I think you can define something like that in Sketch, it's exported to Zeplin and it generates some code/xml for us to import directly into the apps.

**Comment by lizaPlotnikova** [comment]
The troubles with Zeplin could be due to it not playing well with Sketch (symbols). You can always ping me if there's something that doesn't make sense/ or isn't playing well in Zeplin. 

@juanlaube I updated the design in Zeplin (font baseline adjusted) 

How difficult would it be for you guys to retroactively apply a defined group of styles> H1, H2, Body etc. in the app? Are you guys setting the font for every bit of text manually right now?

**Comment by lizaPlotnikova** [comment]
Okay. I will put together a font style-sheet. We'll see how/if we can use it
