### ISSUE TITLE
Reports do not always fade correctly from loading state to data

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2306]
About half the time, there is just no fade at all for me. That makes me sad. :(

This only appears to happen for the initial report when opening the view. It does not happen for me when I change date range in the calendar.

**Comment by khoi** [comment]
@amulware I couldn't reproduce the issue, maybe because I don't have much data in my Toggl account. Do you have a lot?

**Comment by amulware** [comment]
My test account has no data at all in the last week, so the report is actually empty. I've tested it again, and right now I can only reproduce it once, the first time after every cold start.

**Comment by simonrozsival** [comment]
I cannot reproduce this.

**Comment by sofokli1** [comment]
@amulware A video showing the wrong and right animation would be nice

**Comment by amulware** [comment]
Here is a gif (Github does not want me uploading the smaller mp4 file /shrug) that shows first the failing transition (i.e. no animation, the empy state is just replaced) and second the working animation (report fades in).
![ezgif-2-fc4ee18cf0](https://user-images.githubusercontent.com/3987892/42095687-3a3f6632-7bab-11e8-8025-0293af3ff1fc.gif)

**Comment by simonrozsival** [comment]
Oh I thought that the chart will not show at all, but the problem is the missing animation 🤦‍♂️
