### ISSUE TITLE
Consider not opening keyboard when opening project/tag list

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2307]
I noticed that especially on android (slightly smaller phone), but also on ios, the keyboard takes a lot of space when I open my tag/project/whatever list. Especially if all the items would actually fit onto the screen, having the keyboard block out some of them seems very silly.

Should we maybe not show the keyboard on these screens by default?

Or maybe at least not show them if the list fits entirely onto the screen? (or some similar condition based on count of items perhaps)

The only problem I can see with this is that it might not be clear that the top-bar-text-field is a test field and can be edited. Maybe adding a magnifying glass icon or similar helps with that?

**Comment by pe0ny** [comment]
@amulware While I see your point, most of the users have a lot of projects which means finding them is the most crucial task, right. Hence adding additional tap to open the keyboard doesn't seem such a good idea to me.
Have we had lot of complaints about items not fitting into the screen because of the keyboard?

**Comment by amulware** [comment]
> most of the users have a lot of projects

That's an assumption. :P

And no, the only complaint I'm aware of is my own.

**Comment by amulware** [comment]
But as I said, this could e conditional, based on how many projects there are. Then again, not sure it's worth it (right now).

**Comment by amulware** [comment]
One thing to consider: if there are NO projects, it should open the keyboard to easily add one. If it would then _not_ open it the second time the NEW user went to that screen, that might be strange. In general, we should think about things from a new users point of view as well, since we're trying to attract more of them.

**Comment by amulware** [comment]
Yes, exactly my point. I mean, it would be weird if we showed the keyboard for the first time, and then not again (automatically) until they added 5-10 more projects. It's an argument for always showing it.

Still, it would be nice if there was a way to just scroll through the list easier, maybe a way to dismiss the keyboard? I'm not sure...

**Comment by pe0ny** [comment]
I'm closing this now since we haven't had complaints about this. Also, added a note to trello list.
