### ISSUE TITLE
Send handled exceptions to AppCenter properly

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2322]
AppCenter allows for sending exceptions manually now. We should use that and replace the `HandledException` event.

**Comment by amulware** [comment]
Before we do this, we need to consider that out api exceptions might contain a lot of user data, so that might need some changes first.

**Comment by simonrozsival** [comment]
A list of our custom exceptions:

| exception class: | safe | comment |
|:---------------- | ------ |:----------|
| `EntityNotFoundException` (or in #2390 proposed change to `DatabaseOperationException`) | ✅  |  |
| `SerializationException` | ❓ |  possibly can contain some parts of the object which failed to serialize (but I didn't read the whole source code of json.net, maybe there can never be user data) |
| `DeserializationException<T>` | 💥 | contains the whole string which was supposed to be deserialized (as a property + in the message) |
| `EntityAlreadyExistsException` | ✅ |  |
| `DatabaseException` | ✅ |  |
| `GoogleLoginException` | ✅ |  |
| `NoRunningTimeEntryException` | ✅ | |
| `ApiErrorException` (and all derived exceptions) | 💥 | Contains the whole body of the response (might contain some of the user's data) |

**Comment by simonrozsival** [comment]
We should add some method to the `ApiException`s which will erase the sensitive data (the request, and response objects) and then we can push them to AppCenter just fine.

I am not sure what to do with the system exceptions - do we assume that they never contain anything which would be sensitive? Feels dangerous, but I have no idea how else we could handle these - the only thing might be that we track only our custom exceptions and ignore the rest...

**Comment by simonrozsival** [comment]
OR we simply don't change the `ToString()` of the `ApiException` class when not in debug mode - this way we can still get a lot of information from integration tests and we will never expose private/sensitive data to the third party service.

**Comment by amulware** [comment]
`SerializationException` is not safe. Json.NET exceptions can include text like `failed at line X, position Y, near "some text"`

**Comment by amulware** [comment]
Also, what cases does `ApiErrorException` cover? Because the API should never return user data in error responses.

**Comment by simonrozsival** [comment]
Right now it contains the endpoint - this might contain workspace ID (which is probably not that bad I guess).

**Comment by simonrozsival** [comment]
Also `ApiException` is the base class for: `ClientErrorException`, `ServerErrorException`, `DeserializationException<T>`, `UnknownApiErrorException`, `EndpointUnreachableException`.

**Comment by simonrozsival** [comment]
We should decide how to handle the sensitive data without destroying the exception and the trace.

- It should be easy to handle the `DeserializationException<T>` or the `ApiErrorException` in general (hide the request/response body).
- We can change the `SerializationException` so that it doesn't contain the inner exception - the only information we need from this exception is what entity type failed to serialize
- We can do either blacklisting or maybe rather white-listing - track only exceptions which we know are safe to push to the third party

**Comment by amulware** [comment]
I'm having trouble making up my mind about this. I suggest you use your best judgement. :D
Having a white-list makes sense to me though. That's the safest.

**Comment by simonrozsival** [comment]
We can white-list exceptions which we will upload to Crashes and keep the old way of uploading exceptions (so all exceptions will make it into the event log).

**Comment by amulware** [comment]
That sounds good. Let's not have overlap between the two though, if we can avoid it. :)

**Comment by simonrozsival** [comment]
And by overlap you mean to either push it to Crashes or to the Event Log, but not both?

**Comment by amulware** [comment]
Yes.
