### ISSUE TITLE
Clicking on the report when calendar is displayed doesn't minimise the calendar

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2345]
Testing on the most recent Android develop adhoc build.
Acess reports, click on calendar, select a date.
The calendar doesn't either, automatically minimise after a selection, or minimise when you tap on the reports section of the page. The only way to minimise the calendar is by scrolling it up.
![image](https://user-images.githubusercontent.com/18132080/40762629-a052bbf4-64e0-11e8-90a5-fad02303b28c.png)

**Comment by ApocalypticFish** [comment]
Tapping on the white space at the bottom of the page seems like it should minimise the calendar.

**Comment by amulware** [comment]
It does indeed behave that way on iOS (I didn't know). Leaving it up to @pe0ny.

**Comment by pe0ny** [comment]
I agree that calendar should be minimised when tapping the content below the calendar itself. Let's make it so.

The reason why it doesn't minimise after making a selection is because we allow the user to select only one day as well.
