### ISSUE TITLE
Google sign up not working

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2361]
On the sign up page the option under the standard email sign up shows "Sign in with Google".
In the iOS app this shows "Sign up with Google"

Not sure if it's related to this but whenever I try with my Gmail address with no Toggl account attached to sign up it displays "Sorry, we're having trouble signing you up."

**Comment by juanlaube** [comment]
@pe0ny the design copy is "Sign in with Google", that's a little weird for me too, should we match iOS?

**Comment by amulware** [comment]
@juanlaube Yes, let's match iOS. This sounds like an oversight.

I also changed the title and tags, since there is more than just a copy issue.

**Comment by lizaPlotnikova** [comment]
Copy's def. an oversight – sorry guys, now updated in designs
