### ISSUE TITLE
Undo time entry deletion

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2363]
When swipe-to-deleting a time entry, we should show a little toast that allows the user to undo.

Technically, we will only hide the TE from the UI, and only delete it if:
- [ ] the user doesn't interact with the TOAST fast enough
- [ ] the user deletes another TE (only one undo at a time)
- [ ] the user navigates to another screen (start, edit(?), reports, settings..)
- [ ] the user leaves the app/the app becomes inactive
- [ ] the user dismisses the toast (should we add this functionality)

@pe0ny What we need are:
- [ ] designs for the toast for both platforms (please make one issue per platform)
- [ ] the amount of time we give the user to undo (5 seconds? 10? 20? infinite (until they do something else))
- [ ] whether the user can dismiss the toast themselves to make it go away (without undoing)
- [ ] whether going to edit an entry dismisses the toast and deletes the entry
- [ ] whether to use this also when deleting entries from the edit dialogue (and if so, do we still need to ask for confirmation?)

**Comment by pe0ny** [comment]
- Snackbar for iOS: #2540
- Snackbar appears temporarily for 5 seconds and disappears on their own without requiring user input.
- The user can't dismiss them manually, no "hide" or "cancel" option.
- Navigating to any other screen (start, edit, reports and settings) dismisses the snackbar and deletes the entry.
- We'll use the snackbar when user deletes an entry from the Timer screen by using swipe. In the edit view we'll keep asking confirmation and won't show the undo option after that.

**Comment by amulware** [comment]
There are still some questions and missing designs on the UI issues, however, we should be able to implement this without showing the toast, which will essentially delay the deletion (and trigger the future toasts, and allow for the undo). Whenever we're ready to add the toasts we can do so.

**Comment by pe0ny** [comment]
@amulware You mean Android designs or is there something missing from iOS ones as well? Why should we implement this without showing the snackbar?

**Comment by amulware** [comment]
@pe0ny your update to the iOS issue just now covers all my concerns with that issue, so only Android is missing.

The reason we're going to implement it without UI is that we can, and smaller PRs are better, and figuring out the shared logic before we start on the UI should make the code more resilient and better tested. Or at least it will help us learn how to write code more like that.

We might not release before we implement the UI as well (currently estimated for next week), but we have to start somewhere.
