### ISSUE TITLE
Initialization of reports when opening from 3D shortcuts does not work

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2379]
The `ViewAppeared()` lifecycle method of the view model is not called => the initialization (loading of "this week") is skipped and it seems like there are no data.

**Comment by simonrozsival** [comment]
@amulware I think we should definitely fix this before we release 1.7

**Comment by amulware** [comment]
Yes.

**Comment by sofokli1** [comment]
@simonrozsival This seems to work fine, the reports open correctly and with data. Can you double check? I tried with app in background, and app in fully closed, started from shortcut `Reports`, got same as if opening the app and going to the reports.

**Comment by simonrozsival** [comment]
I can't reproduce this anymore. I am not sure what fixed it or if there wasn't a bug in the first place and I observed some different weird behavior. But that is not important right now - I am closing this.
