### ISSUE TITLE
Use HH:mm format for 24-hour format 

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#2388]
Higher echelons of power have decided that 

`HH:mm` format

 should be used on all clients for 24-hour mode (instead of previous `H:mm`).

**Comment by kornelijepetak** [comment]
At the time I wrote this the only two formats we got from backend were:
* `h:mm A`
* `H:mm`
which we convert to our .NET format in `Toggl.Multivac.TimeFormat`. 

⚠️ Since I can see from the code that this will throw if backend sends anything else, we have to synchronize the change in backend with our deployment. However, that is hard to achieve, so before backend changes things, I think we should instead of throwing use a fallback value of some default. Better display invalid format than crash the app. Once the backend changes things, we can deploy another one that throws if backend sends something else.

**Comment by amulware** [comment]
Is this actually a mistake on our side, or something that should be fixed in the API? @maritoggl

**Comment by heytherewill** [comment]
ping @maritoggl for clarification

**Comment by maritoggl** [comment]
Oh dear. Does the issue in itself still stand? In any case, I don't think we should make any client-side conversions and should rely on what we get from backend instead. So if we need to use HH:mm and we don't get that from the API, that should be fixed on the API side. With that said, I'm missing information about who were the higher echelons of power in 2018 and what was the reasoning behind the decision.
