### ISSUE TITLE
Track UserIsMissingApiTokenException occurences

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2400]
Follow up to #1701

I'd like this tracked _somewhere_, just so that we can see if it ever happens.

**Comment by amulware** [comment]
And we should track where it happens: Login, Signup, GoogleLogin, GoogleSignup

**Comment by Odrakir** [comment]
I guess it makes the most sense to do it in the `LoginManager`, so this needs for #1796 to be merged
