### ISSUE TITLE
Remove the `IAnalyticsService` interface which is used only in tests

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2416]
We could use just the abstract class `BaseAnalyticsService` for DI and create mock class inheriting from that base class for tests.

**Comment by simonrozsival** [comment]
☝️ see the discussion for the reasoning behind this issue

**Comment by amulware** [comment]
I'm not even sure if we should remove it at this point. But opinions/arguments either way are welcome.

**Comment by amulware** [comment]
🚳
