### ISSUE TITLE
Error message not clear when email is already used with Google login

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#2433]
After trying to sign up with google with an email that is already registered, it will fail, but the error is not clear, I guess it should be: “You already have an account, try Loggin in” or just login for the user.

**Comment by lizaPlotnikova** [comment]
I'd vote just log in for the user – reduce friction as much as possible

**Comment by daividssilverio** [comment]
@amulware , we will be doing that soon if #1796 gets merged.

**Comment by amulware** [comment]
@daividssilverio but that PR only covers missing api token exceptions right? The account already existing is a different exception (I sincerely hope :D).

**Comment by amulware** [comment]
The old iOS sign-up screen would inform the user of an existing account and have the `account already exists. try [logging in](link to login page)` text. Unless @pe0ny says otherwise, we're going with that.

**Comment by pe0ny** [comment]
@amulware Yep, let's go with that. 👍

**Comment by daividssilverio** [comment]
@amulware yes, only the missing api token exceptions. But for the SignUps with or without google, if it fails with the missing api token exception, it will try again with their login counterparts.

**Comment by lizaPlotnikova** [comment]
Okay! I'm on board with a message too :) But, can the login button just log them in in the case of a google signup failure instead of taking them to the login screen? It seems like a pain to have to go through the login screen again if it can be skipped.

**Comment by juanlaube** [comment]
I just tested this and backend is not returning an error anymore, instead the user signs in with the existing account. I think we should close this issue.
