### ISSUE TITLE
Make report pie chart grouping smart

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2439]
~~Turns out our users aren't liking the grouping, even for the pie chart. We're already not showing labels for small slices, so there isn't a terrible amount of visual noise, and we might as well go back to showing all project colours.~~

~~You win some, you lose some.~~

Surprise! We'll keep grouping, after all. However, we'll make it a lot smarter to keep it from grouping too many small projects into a huge 'other' slice.

The algorithm we will use for this, as developed and used by frontend, is as follows.

* For all possible displayed segments:
 * If a segment would be greater than 5% on the final pie chart it definitely gets its own segment
 * If a segment would be less than 1% on the final pie chart, it definitely gets put into the Other category
 * For the other segments, they are put into Other, smallest first, until we run out of them or Other becomes 5% *or over* on the final pie chart
* If Other is too small (but not empty) make it at least 1% on the final pie chart
* If, actually, there was only 1 item in Other, change the name & color (except how much space it takes up on the final chart! I.e. it remains at least 1%) of Other to be that original item.

Unless users have a lot of <1% projects, this will result in an other-segment of at most 10%, which is good.

Please remember to stuck the 1% and 5% thresholds into constants so we can easily change them should the need arise.

**Comment by sofokli1** [comment]
@amulware if the sum of small projects less than 1% is more than 10% (which is the max for `Other`), than how should the less than 1% segments that do not get into `Other` look like (percentage wise)? Should i show them as they are (less than 1%)?

**Comment by amulware** [comment]
To quote the post above:
> If a segment would be less than 1% on the final pie chart, it definitely gets put into the Other category

meaning that all <1% segments get grouped. If the user has 101 equal projects, they'll get one giant Other slice and nothing else.
