### ISSUE TITLE
Handle the possible crash in the settings view when the user has no default workspace

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2442]
Right now, we are working under the assumption that the default workspace is mandatory. We need proper specs on how to handle it on each platform

## 📱iOS
iOS is a tad worse, since we are passing value to another VM that then selects the value. Right now it crashes, so we need to change it. I see the intended behaviour as:

- The view to select the default WS opens with nothing selected.
- If the view is dismissed by any means other than selecting a ws, the user remains without a default workspace

If the above is correct, there's no way to unselect a default workspace (which I assume is fine, but I need confirmations)

## 🤖Android

Since we render a list with all workspaces, when the user opens the settings view the idea is that none of them will be selected as default. Questions:

- Is this behaviour the correct one?
- If the user has no default ws and selects one as the default, should tapping the ws again unselect it and make the user have no default ws?

Depending on the answers, we might not even need an issue for android

## 🚀Foundation
What we'll need to change to achieve this:

- On Droid, pretty much nothing. Just ensure everything works with no default WS
- On iOS, the SelectWorkspaceViewModel should receive `long?` instead of `long`. That should fix most problems.

I need @pe0ny to confirm the above.

**Comment by pe0ny** [comment]
> If the view is dismissed by any means other than selecting a ws, the user remains without a default workspace

User needs to have a default WS and user must select one. Check #2462

Whenever we have detected that user doesn't have a default WS, we must open the popup and ask the user to select one. And this applies to both platforms.

> On iOS, the SelectWorkspaceViewModel should receive long? instead of long. That should fix most problems.

I can't confirm that one.

@amulware Would you like to add `foundation` label to this issue and create separate issues per platform for the UI?

**Comment by pe0ny** [comment]
Android #2543
iOS #2462

**Comment by amulware** [comment]
This looks like it's redundant with the existence of the other issues.
