### ISSUE TITLE
Stopping timer in time view breaks UI

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2444]
I had a running timer, went to edit it, and stopped it in the time editing popup.

This happened:
![screenshot_20180608-102547](https://user-images.githubusercontent.com/3987892/41299436-57337a06-6e5b-11e8-8b1a-0b9911c02038.png)

Navigating between tabs fixes it.

**Comment by kornelijepetak** [comment]
Are you sure you are on the newest? Cause this has (supposedly) been solved in #2391

**Comment by kornelijepetak** [comment]
I was unable to reproduce this with the latest `develop`, @amulware

**Comment by amulware** [comment]
I was not on the newest develop.
