### ISSUE TITLE
Pie chart slice edges don't render nicely

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2445]
Not sure if my phone (Sony Xperia Z3C) or everybody, but the pie chart is all pixely and has a thin slice missing.

<img width="681" alt="screen shot 2018-06-12 at 16 16 32" src="https://user-images.githubusercontent.com/3987892/41299754-0fc1a0ac-6e5c-11e8-883b-6eadf9149c89.png">

**Comment by heytherewill** [comment]
Closed by #5727
