### ISSUE TITLE
Editing duration and shortcut buttons not playing well together

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2446]
For example:

- have TE of 10 minute duration
- go to edit it using numpad input
- type in '20' (end time does not change in popup)
- hit +30m shortcut (end time changes as if duration was 40m, duration in text field stays 20)
- hit ok (duration is set to 40)

I think it should modify the entered time when using shortcuts, or we should hide shortcuts then.

**Comment by kornelijepetak** [comment]
I need clarification of step 3... What is the desired behaviour? Should the `stop time` change while the user is editing the duration, i.e. typing into the textbox? Or should it update the `Stop time` only when textbox loses focus?

**Comment by pe0ny** [comment]
I agree with Paul on the first one: It should modify the entered time when using shortcuts at step 3.
So after I have typed in '20' and hit +30, it should change the duration to 50 (at the moment it remains 20).
