### ISSUE TITLE
Start TE View metrics that detect keyboard input

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#2447]
Track the following events in the Start TE view:

* [ ] user opened project selection by typing @
* [ ] user opened tag selection by typing #

Both events are related to scenarios where these characters are input through typing the characters on the keyboard.

**Comment by amulware** [comment]
I'm under the impression we are tracking this. @kornelijepetak please confirm.

**Comment by kornelijepetak** [comment]
This has been implemented even since #1973. 
This issue has been invalid from the start.
