### ISSUE TITLE
Confirm two-running-entry resolution when continuing/starting TE

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2454]
I noticed that there is a scenario that can happen that may or may not lead to bad/unexpected data:

- user has a running time entry, that was started at 10:00
- there is also a stopped time entry from 11:00 to 11:30
- now the user continues some random time entry at 12:00
- because of using our regular TE rival resolution, the running entry will be stopped with an end time of 11:00 instead of 12:00

Is this intended? What exactly is the expected behaviour in cases like this?

I'm sure there are other similar cases, and we should be thinking about those as well.

**Comment by amulware** [comment]
After internal discussion, it was decided we should, when starting a time entry in the app **stop the currently running TE (if any) at the current time**.

**Comment by juanlaube** [comment]
I think this can be closed if we implement the proposal linked in #5759.
