### ISSUE TITLE
Let user know about removing the project when continuing TE with an archived project

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2461]
iOS: #2567
Android #2568

**Comment by lizaPlotnikova** [comment]
I'm kind of stuck. I am having a really hard time explaining what's going on in 3-4 positive words (i.e. not "Can't continue archived project"). This makes me wonder if this interaction is straightforward enough. Maybe a more simple UX solution would be to deactivate "continue" on a Time Entry with an archived project?

**Comment by lizaPlotnikova** [comment]
I see now that you guys have had a long discussion around this, and went back and forth several times. I'll try to think of a concise way of handling this message.

**Comment by heytherewill** [comment]
💥
