### ISSUE TITLE
Investigate initial sync projects retry process

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2478]
I was debugging our initial sync pull logic, checking all requests and responses.
Checking `Toggl.Foundation/Sync/States/Pull/FetchAllSinceState.cs`, For the first sync pull try, the `since` date for every entry is null, as expected. 
But then, because of the breakpoints I added to `BaseApi.cs` before executing requests, it would sometimes result in a `OfflineException` being thrown, which would make the sync fail (*). 
The problem is that at some point, for some reason that I can't reproduce anymore, the `since` date for the projects were being set, and following FetchAllSinceState executions would result in the projects being fetched using the since parameter and partially requesting projects, even without ever succeeding in the initial full sync.

(*) I noticed that after the `OfflineException`, there was no retry on the initial pull sync, whatever failed, failed(**), and the following requests continued. Shouldn't dependent entries fail on sync if parent entries failed first, at least for the first pull sync? 

(**) There was one time where it failed with the workspaces, and I got the main log screen, was able to access the Settings screen, see that there were no workspaces in the listing, went back to the main screen, was able to click the Play button, crashing the app.

**Comment by amulware** [comment]
✂️
