### ISSUE TITLE
Tap area for the sync bar is quite small

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2483]
I had a hard time dismissing the sync status bar when in offline mode, even though the whole bar is tappable. The `X` that appears when one is offline is, in my opinion, quite misleading, but that's another topic.

I have an iPod touch and am not an iOS user, so I'm requesting a professional @pe0ny to check this when she has the time.

**Comment by amulware** [comment]
We'll be rewriting this one from scratch, so I'll close this for now.
