### ISSUE TITLE
Tap area for color picker needs revision

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2484]
Had a hard time accessing it (as in literally accepted the default color because I couldn't open the view) on my tiny iPod. No problem what-so-ever in the simulator, using a high precision RATÓN INALAMBRICO. Maybe my hands are too big? 🤷‍♂️

**Comment by pe0ny** [comment]
Tappable area should be 48x48 pt
I believe at the moments it's smaller. Let's check that and make changes if needed.

![toggl - ios - new project 1x](https://user-images.githubusercontent.com/5064445/41856731-7ada85f6-789e-11e8-8638-d0285ca50c43.png)
