### ISSUE TITLE
Wheel view: seconds are missing

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2512]
App Store version VS TF 1.7

![image from ios 1](https://user-images.githubusercontent.com/5064445/41702544-29095a26-7539-11e8-8feb-c5f2fca42d85.png) ![image from ios](https://user-images.githubusercontent.com/5064445/41702546-2b671632-7539-11e8-92f3-89cc0b06f2e2.png)

**Comment by simonrozsival** [comment]
Fix was merged into a release branch.
