### ISSUE TITLE
Investigate failing integration tests

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2528]
Our API integration tests have been failing a lot when running during the night recently, however, when I rerun them during the day, they are just fine.

Let's go over the logs or do some testing and see what tests fail, maybe it's something time-related.

If no bug that can be fixed is found, please at least post findings below.

**Comment by simonrozsival** [comment]
These tests which were added recently fail repeatedly and it is probably related to being close to midnight:

```
Failed   Toggl.Ultrawave.Tests.Integration.TimeEntriesApiTests+TheGetAllBetweenStartAndEndDatesMethod.DoesNotReturnTimeEntriesWhichStartBeforeTheStartParameter
Error Message:
 Expected list to be empty, but found {Toggl.Ultrawave.Models.TimeEntry
   {
      ApiDuration = 300L
      At = <2018-06-26 01:14:12>
      Billable = False
      CreatedWith = <null>
      Description = "ea93bf35-5d31-4084-a165-b09f8323aa01"
      Duration = 300L
      Id = 907123786L
      ProjectId = <null>
      ServerDeletedAt = <null>
      Start = <2018-04-11 01:10:33>
      Stop = <2018-04-11 01:15:33>
      TagIds = <null>
      TaskId = <null>
      UserId = 4188420L
      WorkspaceId = 2817977L
   }}.
```

```
Failed   Toggl.Ultrawave.Tests.Integration.TimeEntriesApiTests+TheGetAllBetweenStartAndEndDatesMethod.ReturnsOnlyTheTimeEntriesWhichAreBetweenTheStartAndEndDates
Error Message:
 Expected list to contain 1 item(s), but found 2.
```

**Comment by simonrozsival** [comment]
The other failing tests seem to be `BadGatewayException` and similar - so they are not problems in the logic or in the test themselves.

**Comment by daividssilverio** [comment]
I checked the `DoesNotReturnTimeEntriesWhichStartBeforeTheStartParameter` with varying start times getting close to midnight to see what happens .

As it turns out, we are expecting time entries inside the range we requested to not be present on the response from the api.

For example: I got one failure with these values:
start time: `04/13/2018 21:17:21 -04:00 (04/14/2018 01:17:21 +00:00)`
time entry time: `04/12/2018 21:17:21 -04:00 (04/13/2018 01:17:21 +00:00)` (which is inside the range we are requesting)

The api call being made is:
```
$"me/time_entries?start_date={start:yyyy-MM-dd}&end_date={end:yyyy-MM-dd}"
```
which renders to 
```
me/time_entries?start_date=2018-04-13&end_date=2018-06-12
```

Question: Do we want the api calls to behave like that? We are ignoring the timezone offset for the request, but we do consider it for creating time entries. If that's ok, to fix this test, we could just remove the timezone offset from the time entry created. Or, we could just erased, it feels like the same subject is covered in the `ReturnsTimeEntriesOnlyAfterMidnightOfTheStartDate` test.

**Comment by daividssilverio** [comment]
`ReturnsOnlyTheTimeEntriesWhichAreBetweenTheStartAndEndDates` is similar, it actually expects the same thing that `DoesNotReturnTimeEntriesWhichStartBeforeTheStartParameter` does, with the added item that should be returned.

This test, also, looks like it is covered by `ReturnsTimeEntriesOnlyUpToMidnightOfTheEndDate` and `ReturnsTimeEntriesOnlyAfterMidnightOfTheStartDate` together.

**Comment by simonrozsival** [comment]
We need to figure out what timezone does backend consider in this request - if it was reports, then this would definitely use user's settings, but who knows what happens in this endpoint...

BTW I looked at the today's log and we got:

- 11x 500 Internal Server Error
- 9x 502 Bad Gateway
- + the two failing tests we are already discussing

**Comment by amulware** [comment]
I've been told that endpoint works in GMT.

**Comment by daividssilverio** [comment]
On 403/401 related failures. It seems like the api can return both 401 and 403.
For example, https://app.bitrise.io/build/d53d623694da1e28 failed, but https://app.bitrise.io/build/a1e8165a9b933d9a passed `¯\_(ツ)_/¯ ` 

We could change our tests which expect `UnauthorizedException` to expect `Forbidden` as well.
The thing about this is that the webapp/desktop apps might break if backend fix it.

**Comment by daividssilverio** [comment]
About random 500 Internal Server Errors, as discussed internally, they seem to be related to the time the db backups/dumps happen in staging.
We can change the times our integration tests run; or better, let backend call the trigger url to run Integration tests when said backups/dumps finish running;

**Comment by daividssilverio** [comment]
Finally, 502 errors might happen occasionally (server instance might be dead), so, trying the test again might actually help.
If XUnit lets us, we could wait a little and run the same test again (a few times, maybe?) or just skip these tests.

**Comment by amulware** [comment]
502: I'm not sure if XUnit allows retrying of tests, but we should take a look.

500: Let's change the time we run the tests, I'm thinking why not run it say.. two hours earlier, but also 3 hours later? More runs gets us more data. I'll also ask backend to trigger the run after the staging copy finished.

403/401: I thought we have special code to catch this.
https://github.com/toggl/mobileapp/blob/develop/Toggl.Ultrawave/ApiClients/BaseApi.cs#L159

**Comment by amulware** [comment]
I've changed the tests to run at midnight and at 5am now. Let's see what happens.

**Comment by daividssilverio** [comment]
About 403/401.
The code you pointed considers an 403 as unauthorized when the user is logged in.
The randomly failing test in question is:
```
[Fact, LogTestInfo]
        public async Task FailsForNonExistingUser()
        {
            var (validApi, _) = await SetupTestUser();
            ValidApi = validApi;
            var email = $"non-existing-email-{Guid.NewGuid()}@ironicmocks.toggl.com".ToEmail();
            var wrongCredentials = Credentials
                .WithPassword(email, "123456789".ToPassword());

            CallingEndpointWith(TogglApiWith(wrongCredentials)).Should().Throw<UnauthorizedException>();
        }
```

We are making a request with invalid credentials.

**Comment by amulware** [comment]
We've done enough here for now. Tests are very stable these days.
