### ISSUE TITLE
About Page - Licenses UI

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2531]
Followup of #1628 
The About page is being done on #2522

When the user clicks the Licenses view for android, it should open the list of licenses we are using in the app. 

The VM is done, it just needs the UI part. (iOS version is done)

**Comment by lizaPlotnikova** [comment]
Licences page design: 
<img width="368" alt="screen shot 2018-06-25 at 2 19 44 pm" src="https://user-images.githubusercontent.com/24964497/41868038-d84eda96-7882-11e8-8675-3e2dbaff6625.png">

Zeplin:https://zpl.io/VQYvzgx

**Comment by amulware** [comment]
As part of this, please check if the current list of licenses is still correct, and update it as needed (or create a follow-up issue and let me know). Both platforms.

**Comment by semanticer** [comment]
@amulware Maybe we can use lib like https://github.com/PSDev/LicensesDialog for this purpose?

**Comment by amulware** [comment]
That's a decision for architect @heytherewill :)
