### ISSUE TITLE
Investigate Lottie

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2537]
https://airbnb.design/lottie/
Lottie is an iOS, Android, and React Native library that renders After Effects animations in real time, allowing apps to use animations as easily as they use static images.

Leez uploaded animation files in Slack: https://toggl.slack.com/files/U38C2ELBY/FBC3NH19B/animationfiles.zip

She split the animation up like this:
• demo - entire animation – shows what I intended the whole thing to look like when played together
• pull-down – is the part of the animation that is sync'ed to the swipe-down motion... it has a little bounce at the end when the user releases 
• loader-in – plays right after the pull-down animation finishes
• loading – plays looped while data is fetched (it shouldn't be interrupted in the middle though, because it won't animate out smoothly... but we can skip it altogether if the data finishes fetching while loader-in is playing) 
• loader-out – plays as soon as last loading loop finishes (data is loaded)

### Questions that need answering: 
- Is the animation the right size, will it work properly when scaled on different devices?
- Is it split up correctly to correspond with events? are the files in the correct format (basically did I export the right thing?)
- In general, is it useful for us implementing animations? will it make implementing animations faster/easier?

**Comment by heytherewill** [comment]
🤸‍♂️
