### ISSUE TITLE
Animations: Add ripple effects to Timer page elements

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2538]
Add ripple effects to:
- Suggestions (the whole card)
- Time entries (the whole card when opening the edit view, not when continuing a time entry)
- Running TE card (the whole card)

Ping @pe0ny to discuss the ripple colour. We'll start working on consistency updates soon, so it would be good to know what is the default colour at the moment and based on that, if it needs editing or not.

![ripple](https://user-images.githubusercontent.com/5064445/41856566-115e196c-789e-11e8-9a89-d3fc2bca8047.gif)

**Comment by amulware** [comment]
Check with Product with regards to the color if needed.

**Comment by amulware** [comment]
Have the points above all been addressed by #5534?

**Comment by heytherewill** [comment]
They have, yes. Closing as completed by #5534
