### ISSUE TITLE
Undo time entry deletion UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2540]
- Use the same animation to show and hide the snackbar: #1538

### Undo when the timer is not running
![toggl - ios - timer - undo 1x](https://user-images.githubusercontent.com/5064445/42158347-d5d69544-7df8-11e8-9511-d14c597a13e1.png)

Zeplin: https://zpl.io/b6MDQrR

### Undo when the timer is running
![toggl - ios - timer - undo running entry 1x](https://user-images.githubusercontent.com/5064445/42158353-da6474d2-7df8-11e8-8e9c-6ba7f26eebba.png)

Zeplin: https://zpl.io/agvk9AZ

### Tappable area: 8pt padding from left and right; 10pt from to and bottom
![screen shot 2018-07-02 at 13 07 48](https://user-images.githubusercontent.com/5064445/42158384-f2f2fea6-7df8-11e8-8e91-4a32af563681.png)

**Comment by amulware** [comment]
I must protest this. We're moving the action button to make space for the toast? Is that really what we want?

Also, I find the contrast of the text to background a bit low to the point where the text is hard to read.

**Comment by willsb** [comment]
This is indeed a weird mix of toast (due to proportions) and snackbar (due to influencing the layout). 

Also, on iOS I wouldn't use a bottom snackbar to implement undo, I'd, instead, as the user swipes to delete and turns the entire cell red, leave the cell there for a while, entirely colored in red with a button on the right corner that reads `Undo` and allows the user to restore that time entry in particular.

**Comment by pe0ny** [comment]
I had a chat with Leez about the placement of the snackbar as well (since we use the same element of Android) and I agree that it should be always above the FAB. I updated designs accordingly. Also, the colour is changed - let's use the same once we're already using in Forgot PW view (this one also doesn't have any issue with the contrast).

And for consistency reasons I would like to use snackbar for this. There will be more similar things (e.g. notification when user wants to continue TE with archived project) for which I would like to use snackbar too.
