### ISSUE TITLE
Undo time entry deletion UI 

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2541]
- Use the same animation to show and hide the snackbar: #1538 

### Undo 

![timer - undo deletion](https://user-images.githubusercontent.com/5064445/42160944-ba43cd8e-7e01-11e8-8331-4755a046d066.png)

Zeplin: https://zpl.io/a74vwZ8

**Comment by amulware** [comment]
Blocks #2665 (putting it here so we see this issue's state in that PR :))

**Comment by amulware** [comment]
This is assigned to @kornelijepetak - any update?

Also, since the main view was heavily rxfactored on iOS, we probably want to do the same on android before we can implement this? Also pinging @daividssilverio @willsb

**Comment by daividssilverio** [comment]
This is what I would expect on Android. It follows the guidelines. All good.

**Comment by kornelijepetak** [comment]
I was waiting with this until @Odrakir does his thing on iOS. Since I've done little to no progress besides looking at his code, I will unassign myself from the issue so somebody can take it while I'm away.

**Comment by amulware** [comment]
@daividssilverio I'm not sure if you answered my question. If you did, I don't follow. I'm not sure what guidelines you refer to. Do we need to rxfactor the TE log on android? If so, please create an issue and assign it to the 1.4 release with max priority (or tell me to do so).

**Comment by daividssilverio** [comment]
@amulware , Material design guidelines about snackbars: https://material.io/design/components/snackbars.html.

**Comment by daividssilverio** [comment]
Here is what I think: I rather have the rxfactor than figuring out where to place the snackbars using mvx.
The reality: it looks possible to do it without the rxfactor, the code for deletion is attached to the MainRecyclerAdapter on giskard and we could replicate the logic done on @Odrakir's pr there, but that leads to rework and code duplication! 👎.
Also: rxfactoring the main log won't be fast, but faster than it would be without the latest rxfactor done by Ricardo.

**Comment by dshr** [comment]
@daividssilverio doesn't the snackbar go just above the floating action button, and not in the time entry list, so no need to poke mvx for the position?

**Comment by daividssilverio** [comment]
It goes above the FAB itself, this is configured with CoordinatorLayout + setting Behaviours on the FAB.
As I said, it's possible to do it without touching mvx, but the code will be removed anyway with the rxfactory.
