### ISSUE TITLE
Weird UI layout when editing time by keyboard in the time editing view

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2542]
I tapped the keyboard icon in the time editing view:

![Time editing view](https://user-images.githubusercontent.com/374616/41892389-2e4b4534-7918-11e8-9d0e-c6b8aa692bd6.png)

The input method changes and is localized (maybe it would be possible to force English?) and the title changes to a localized "Time settings" string and it overlaps some of the small calendar in the header:

![The weird UI layout](https://user-images.githubusercontent.com/374616/41892273-be5f5a94-7917-11e8-99d1-e1b25391e3cf.png)

Phone: LG Nexus 5X
Android: 8.1
GUI language: Czech

**Comment by simonrozsival** [comment]
This is in fact duplicite of already closed issue #2263 which was supposed to be closed by #2380, but I can still see it in beta release (0.5).

**Comment by heytherewill** [comment]
⚪️
