### ISSUE TITLE
Ask user to pick a default WS when a default one is not assigned

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2543]
Check #2462

**Comment by lizaPlotnikova** [comment]
Same behavior as in iOS: 
When user selects an option close dialog.
![error set default workspace](https://user-images.githubusercontent.com/24964497/43086792-3632e0a4-8e6c-11e8-9dbe-b152355d34b1.png)
Zeplin: https://zpl.io/2pOgwgr
