### ISSUE TITLE
Timer page isn't refreshing the order of entries after editing a time entry

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2560]
In the Timer page if you edit an existing entry and change it's place in the order of entries the order does not update yet the duration will update.

So for example you have:

Time entry A: 9:00am - 10:00pm
Time entry B: 12:00pm - 1:00pm
Time entry C: 1:00pm - 2:00pm

You change time entry C to: 11:00am - 12:00pm

The order will still stay A,B,C until the app is refreshed.

**Comment by amulware** [comment]
iOS has the same issue.

**Comment by Odrakir** [comment]
This should be fixed when #2599 is ready, but we'll see...

**Comment by Odrakir** [comment]
iOS is fixed in with #2743. Android still needs to use the new code.

**Comment by heytherewill** [comment]
👌
