### ISSUE TITLE
Test Daneel 1.7.1

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2571]
Specific bugs that we tried to fix:

- [x] Fixed version not showing correctly in settings view
- [x] Fixed help button not working correctly
- [x] Fixed back button not working in forgot-password view
- [x] Fixed duration sometimes being shown with an ellipsis in the time edit view
- [ ] Fixed crash related to Facebook integration
- [x] Fixed time entry log not updating correctly when continuing a time entry while a timer was already running
- [ ] Fixed some animation issues with the start button and running timer that led to the start button not appearing sometimes

Of course, general testing of all the things is always good and necessary.

**Comment by ApocalypticFish** [comment]
Tested sign-up and sign-in both Google and standard.
Tested forgotten password link, terms and conditions and privacy policy links.
Tested starting new time entry, stopping, creating project, tag, client.
Tested editing entries, continuing, stopping and deletion.
Onboarding appears to be working correctly.
Reports working correctly.
Tested settings, workspace switching, format, feedback and about.
Aside from crash when continuing multiple entries quickly this entry seems good. Certain things from above I can't test definitively but none of the following have occurred thus far:
Fixed duration sometimes being shown with an ellipsis in the time edit view
Fixed crash related to Facebook integration
Fixed some animation issues with the start button and running timer that led to the start button not appearing sometimes

**Comment by simonrozsival** [comment]
This release is already public. We should probably close this issue now.

**Comment by simonrozsival** [comment]
The ellipsis glitch does not happen anymore - tested in the public release.

What do you think about closing this issue, @amulware?
