### ISSUE TITLE
Timer page: Show archived icon instead of the dot when the project is archived

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2583]
In addition to (archived) text, we want to show a little archived icon at the front of the project name instead of the dot. See #2366

![screen shot 2018-07-02 at 14 16 10](https://user-images.githubusercontent.com/5064445/42161156-7edb8218-7e02-11e8-9254-466cbcb56ae4.png)

Zeplin: https://zpl.io/a74eDz8

**Comment by semanticer** [comment]
Should be easy even for a Toggl/Xamarin newbie like me, but I need access to Zeplin
