### ISSUE TITLE
Add a tab bar

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2585]
- [x] New tab bar should be displayed only in these three views: Timer page, Reports and Settings
- [x] Remove Reports and Settings icons from the current nav bar
- [x] In Reports and Settings page, remove "Back" option from the nav bar

### Timer
![toggl - ios - timer tab bar](https://user-images.githubusercontent.com/5064445/42163383-f0cc2e74-7e0a-11e8-98db-a18458da6a3e.png)

Zeplin: https://zpl.io/VxYvxq3

### Running entry
![toggl - ios - timer - running entry tab bar 1x](https://user-images.githubusercontent.com/5064445/42168752-8a4f74ca-7e1a-11e8-8864-1d3115fa2513.png)

Zeplin: https://zpl.io/2j4RAo6

### Reports
![toggl - ios - reports tab bar 1x](https://user-images.githubusercontent.com/5064445/42163505-9287384e-7e0b-11e8-9442-9b037670d545.png)

Zeplin: https://zpl.io/bAq5JPp

### Settings
![toggl - ios - settings tab bar 1x](https://user-images.githubusercontent.com/5064445/42163521-9e33448a-7e0b-11e8-94b3-ce75c721d1c1.png)

Zeplin: https://zpl.io/2vYo9Gr

**Comment by simonrozsival** [comment]
How will it look with a running time entry? Also will it be semi-transparent only on the reports page, or should it show blurred contents everywhere?

**Comment by pe0ny** [comment]
Tab bar should be translucent in all views (it actually is it's just there is not a lot of coloured content behind it atm).

I thought I added running entry view as well - will do it asap.

**Comment by amulware** [comment]
This might look a bit strange with a translucent tab bar, but the solid timer? Maybe make them the same? Let's at least pay attention to that when implementing. :)

**Comment by amulware** [comment]
In fact, check Apple's native podcasts app. It's quite similar to our case, with a tab bar at the bottom and the playing podcast above it (including a start/pause button). There, only the playing-bar is translucent, while the tab bar seems solid white.

**Comment by sofokli1** [comment]
2 tabs coming right up
