### ISSUE TITLE
Wheel of Time™ OK and Cancel buttons stop working after orientation rotate

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#2587]
Reported by /case/733848

Steps to reproduce:
0. Hold phone in portrait orientation
1. Tap on Entry to open edit screen
2. Tap on Start time
3. Rotate phone to landscape
4. Rotate phone back to portrait
5. Tap on OK or Cancel; nothing happens.

Verified on my OnePlus 6

**Comment by kornelijepetak** [comment]
This is fixed by #2717 
We do not support rotations at this moment.
Whether we will at any other point in time, is not up to me. Who knows. :)
