### ISSUE TITLE
List of transitions needed

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2588]
Let's list in this issue all the transitions we need for Android app.

- [ ] Opening timer page after login or when the app has been closed completely
- [ ] Timer page: Stopping the timer
- [ ] Timer page: Continuing a time entry
- [ ] Opening the start view
- [ ] Closing the start view when the timer is running 
- [ ] Closing the start view when time entry was discarded
- [ ] Opening the edit view
- [ ] Closing the edit view
- [ ] Navigating from Start/Edit view to Projects/Tags views
- [ ] Opening Reports
- [ ] Opening Settings
- [ ] Opening the app: 3-step walkthrough animations
- [ ] Opening login and signup pages

**Comment by heytherewill** [comment]
👂
