### ISSUE TITLE
Step 2 of onboarding not appearing

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2614]
Step one appears (start an entry, stop an entry)
But Step 2 (Edit an entry doesn't appear)
Subsequently Step 3 doesn't appear, though this should be independent and prompted after the 5th created time entry.

**Comment by ApocalypticFish** [comment]
This is with the develop adhoc from this morning

**Comment by amulware** [comment]
I believe this is because the same was not merged yet. So far only the start/stop and add project/tag in the start view tooltips should be implemented.
