### ISSUE TITLE
Start view text field is really slow and lags

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2619]
When trying to type something in the Start view text field, it starts lagging and it's almost impossible to use. Can someone confirm?

Android
1.0 internal build

**Comment by pe0ny** [comment]
The issue happens only when entering a description. When adding a @ project or # tag, it's all good.

**Comment by kornelijepetak** [comment]
Yes, I can reproduce it in emulator. When I type quickly, the text appears even up to 2 seconds after I've typed it.
