### ISSUE TITLE
Reports: WS select UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2624]
- The user should be able to switch Workspace in Reports view to see data from another Workspace. This, however, won't change the default workspace.
- Show the WS button only if the user has more than one workspaces. If the user has only one, don't show it at all.
- WS select button should float above the content.
- Max width of the button: 192pt. If the name doesn't fit, fade the name out.
- When the user taps the WS select button, use iOS default actions to list all the WS the user has and let him/her choose between those. Display also the selected WS name.
- Make sure when the WS button is visible, the padding between the content (list) and bottom should be higher.

### Reports view with WS select
![toggl - ios - reports ws select 1x](https://user-images.githubusercontent.com/5064445/42433661-fcea49c2-8358-11e8-80ae-99e3e66c5317.png)

Zeplin: https://zpl.io/29Z0AzY

### WS select with longer name
![toggl - ios - reports ws select with longer name 1x](https://user-images.githubusercontent.com/5064445/42433914-d9e4ef1c-8359-11e8-9c59-dc09d648f597.png)

Zeplin: https://zpl.io/2vYZqA5

### WS select actions
![toggl - ios - reports workspace select with actions 1x](https://user-images.githubusercontent.com/5064445/42433936-eb0918ae-8359-11e8-8478-6e9568388c77.png)

Zeplin: https://zpl.io/V41BY94

**Comment by amulware** [comment]
1. Is the workspace icon the same as the one on the web? it looks slightly different to me. 🤔 

2. Are we using the built-in dialog? Just wondering, because so far we've been using mostly custom UI.

**Comment by pe0ny** [comment]
1. It **should** be the same. I got it from the webapp Sketch file but maybe they have changed it a bit. I'll check just in case.
2. That was the idea, yes. We also use built-in thing for the delete confirmation in the Edit view. The main reason why I didn't want to use the same Workspace view we have in the Settings is to not confuse users with Default WS selection (because this switch doesn't affect default WS). And designing yet another component doesn't really make sense in this case.

**Comment by amulware** [comment]
Requires #2702
