### ISSUE TITLE
When creating a new Tag can select create a new tag multiple times for the same tag name.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2625]
![image](https://user-images.githubusercontent.com/18132080/42436340-c82be480-8398-11e8-94d9-ed21a1f12a8c.png)
After creating a new tag, the option to create new tag stays visible and if pressed multiple times appears like above.

**Comment by sofokli1** [comment]
can't reproduce on latest develop

**Comment by amulware** [comment]
What build/version was this bug found on? Does it still occur with the latest release (1.7.2)? Develop by now includes the refactor of the start view, which might have fixed this.

**Comment by sofokli1** [comment]
can't reproduce in app store version
