### ISSUE TITLE
WS removal: remove synced TEs of lost workspace

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2631]
If we lose access to a workspace, we need to get rid of all the synced data we have in it. Unsynced data will be kept so that the user can regain access and sync it, or move it to a different workspace.

~This state will probably run after the one from #2628.~

Since time entries are not referred to by anything else, we can easily remove those that are synced from the DB.

Other entities have to be checked especially since they are referred to by time entries.

**Comment by simonrozsival** [comment]
We don't need to run this right after the access is lost, we can do this in the `CleanUp` loop instead. We should schedule a clean-up right after we detect losing access to the workspace though.
