### ISSUE TITLE
WS removal: mark workspace as ghost

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2639]
The workspace we got removed from should be marked as ghost according to #1337.

**Comment by simonrozsival** [comment]
We have the a state that detects losing access to a workspace (#2813) which returns a list of workspaces which should be marked as ghosts.

I think that it would make sense to modify that state to direcly mark those workspaces as ghosts and continue with persisting data during pull sync + trigger clean-up loop which will prune data of these ghost workspaces (synced projects, clients, time entries, and if possible the whole workspaces) - but that is already part of #2631.

**Comment by amulware** [comment]
Why the same state and not a separate one? That sounds cleaner and better testable to me.
