### ISSUE TITLE
WS removal: Set up sync graph

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2640]
There are different orders in which we can do all the different steps. I'm not sure which is the best, but here are some ideas. Please discuss.

1. delete, then ghost, per entity

- notice workspace was removed
- delete synced TEs
- mark remaining TEs as ghosts
- delete tags not referred to
- mark remaining tags as ghost
- delete projects not referred to
- mark remaining projects as ghost
- delete clients not referred to
- mark remaining clients as ghost
- mark workspace as ghost

Issue: until the workspace is marked as ghost, the user might use it and do things that break, or even create entities that will remain un-ghosted even though they shouldn't. Other than that, I think even if this algorithm gets interrupted at any point we should still end up with a correct state and the app will continue on next sync

2. ghost first

- notice workspace was removed
- mark tags, projects, clients as ghosts
- mark time entries as ghost
- mark workspace as ghost

- delete synced ghost time entries
- delete ghost tasks, projects, clients no longer referred to

This is maybe a little bit more resilient to user interference since we mark things as ghost as far as possible, however, we also have to mark a lot of data as ghosts that will be deleted anyways, which might be a waste?

However, note the break in bullet points. The last point can be executed another time. In fact we need a separate cleanup loop that repeats those two steps anyways, so this might be the way to go?

Please think through these options and the context and see if you can find any issues with it.

**Comment by amulware** [comment]
The above details are probably somewhat out of date, feel free to update them.

What I came here to say though: **Please don't actually put this new syncing stuff into the app without checking with me**.

We have a lot of big features coming up and I don't want to release EVERYTHING in a single big release. Or maybe I do, but let's think about it carefully. :D

**Comment by simonrozsival** [comment]
This was addressed in smaller issues in the NSync project. I'm closing this issue now.
