### ISSUE TITLE
Issue with tag # and @ in description entry line

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2648]
Not sure how to describe this issue but text is jumping from the already existing tag to the project, I think because of autocorrect.

Seems to correct and sync properly after it's been saved/confirmed

![time entry tag having issue](https://user-images.githubusercontent.com/18132080/42489781-23d28b3c-844c-11e8-8180-39f42115f462.gif)

**Comment by pe0ny** [comment]
I believe it is the same as described here #2618 
Let's test and confirm. Then we can close the issue.

**Comment by daividssilverio** [comment]
It's similar in fashion, it might be related. I can try on develop since #2618 is merged.

**Comment by willsb** [comment]
This has been solved by #2642
