### ISSUE TITLE
After continuing with swipe, the row remains green

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2649]
It would be great if someone could test it too and help me to figure out the exact steps how to reproduce. Atm it feels it only happens when you continue while another TE is running.

![screenshot_20180709-173842](https://user-images.githubusercontent.com/5064445/42491698-92f3a088-841e-11e8-9057-cacb7d7ed792.png)

**Comment by juanlaube** [comment]
I can reproduce this in the emulator, with or without a running TE. It's not hard to reproduce, I just started swiping right fast and some cells stay like this.

**Comment by juanlaube** [comment]
Closed by #2654
