### ISSUE TITLE
Running time entry card: Project dot isn't aligned vertically centre

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2650]
On the running time entry card, the project dot isn't aligned vertically centre to the project name.
Also, it seems the padding from the left is bigger compared to the duration padding (both should be 16dp from left).

Check designs from zeplin: https://zpl.io/25gqy0J

**Comment by kornelijepetak** [comment]
@pe0ny what about those paddings? Can you give me a screenshot? 
Or are you talking about the case when there is no description so that the padding between description and project stays, making project too offset from the left.

**Comment by pe0ny** [comment]
Yep, that's the case - when there is no description.
