### ISSUE TITLE
Projects don't sync

### ISSUE THREAD

**Issue by Dragas** [toggl/mobileapp#266]
Right now neither the desktop app nor mobile app (atleast on android) do not sync projects from your teams workspace when youre either assigned to them or theyre created and new entries under those projects show up as entries w/o a project.

A workaround for this is to log out and log back in again.

**Comment by amulware** [comment]
@Dragas Thank you for reporting the issue.

Unfortunately, this repository is not for the currently available Toggl apps, but for new apps that will be released in the future.

For now there is unfortunately nothing we can do to resolve the issue, apart from the workaround you already found, but I forwarded your feedback to our desktop developers as well.

Thanks again!
