### ISSUE TITLE
Projects/Clients view: long project/client names break the view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2660]
When the name is over 2 lines, it hides the "Create project" button.

![screenshot_20180711-090119](https://user-images.githubusercontent.com/5064445/42553821-16a365fe-84eb-11e8-8e29-8063336d7df0.png)

Both input fields in Projects and Clients view should behave the same way as the Start and Edit views like stated here: https://github.com/toggl/mobileapp/issues/1345#issuecomment-399080914

- field has a max height (108dp)
- if the text exceeds that max height it begins to scroll within the field (currently there's no scroll bar element implemented, but I think we should implement that)
- when the height increases, the content below (e.g. "create new project" or matches) should move together with the input field.

**Comment by heytherewill** [comment]
Force this to be one line for an easy fix

**Comment by amulware** [comment]
Do confirm changes with Product before merging.
