### ISSUE TITLE
Crashes almost everytime I use it

### ISSUE THREAD

**Issue by chipbite** [toggl/mobileapp#267]
Hey guys,
I am sorry that I cannot be so specific, but I have crashes almost every time I use the app.

I have used toggl for years, and the android app is part of my use. For some time now, the app crashes very, very often. Usually directly after startup or after one attempt at doing something. Regular session can mean starting, crashing a few times during the path to get whatever I am trying to accomplish, done.

Happy to provide logs, info, etc.

BR! /marcus

**Comment by amulware** [comment]
Hey Marcus,

Thank you for the report.

We are aware with the issues some of our users experience with our mobile apps.

Unfortunately (or fortunately, depending how you look at it), this repository is not for those apps, but for new apps that will replace the current ones in the future.

For now, you could try reinstalling the app (make sure all your data is synced before!), and see if that makes it more stable. If the issues remain, I have to ask for your patience, and apologize for the inconvenience.

Thanks again!

**Comment by chipbite** [comment]
Ok, that is why I got a 404 on toggl/mobile - which was the place for the current mobile app, I assume.

Well, looking forward to a better toggl experience soon, on both device and desktop. Toggl apps have a great history, hope that you can resume it.
