### ISSUE TITLE
Make sure the app looks good regardless of font/display size settings

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#2676]
Here is the list of items to take special care about (or the ones that some issues are already noticed with)

* [x] Time Entry cell in TE Log
* [x] Suggestions in TE Log
* [x] Running TE card
* [ ] The Time Selector (header labels)
* [ ] List of tags/projects/clients
* [ ] Calendar control in reports
* [ ] Settings screen (item's title + description label)
* [ ] Login (forgot password padding)
* [x] Login (sign in with google hidden)
* [x] Login (space between "Don't have an account/ sign up for free" texts and the bicycle icon)
* [x] Sign up (space between "Already have an account / Login" texts and the bicycle icon)
* [ ] Sign up (sign up with google hidden)
* [ ] Terms and privacy popup on sign up
Please fix each and every one of those in **separate** PR.

**Comment by kornelijepetak** [comment]
In case of EditTE View I believe the best course of action would be to simply move Stop time into its own row on large font/display settings. This is how it looks like on `Font:Largest`, `Display:Largest`

![image](https://user-images.githubusercontent.com/7033216/42872111-55f9c996-8a7c-11e8-8dcc-08781604698a.png)

**Comment by daividssilverio** [comment]
The problem with the bottom cards can be reproduced by having Font:Largest.
The problem with the login with google not showing can be reproduce by having Display:320 dpi.
Login (making it scrollable should be enough to show the login with google button):
<img src="https://user-images.githubusercontent.com/2173493/42908058-d29da59a-8aad-11e8-9f79-d65baee45c5a.png" width="240"/>

Sign up:
<img src="https://user-images.githubusercontent.com/2173493/42908059-d2c7ac6e-8aad-11e8-8f5e-39bce8fa7427.png" width="240"/>

**Comment by amulware** [comment]
:delorean:
