### ISSUE TITLE
TE log table view breaks

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2682]
## What?

I can still scroll, but no new cells are created above/below where I was, so it's just plain white there.

Scrolling back, the cells that were there originally are still there, so they don't get cleaned up either.

## Steps

Not 100% sure, but I think it usually happens like this:

- start a timer (might be optional)
- leave app in background for 2+ hours (no idea how long it really takes)
- come back to app
- stop timer (not sure if this is actually needed)
- notice the TE doesn't show up in the log
- scroll to see the bug described above

Restarting the app makes it work again, and the TE was also stopped properly.

When just going out of the app for a little bit, the same issue does not seem to happen.

I'll try to gather more information when this happens again, to maybe limit the range of possible causes more.

**Comment by Odrakir** [comment]
Might be fixed by #2599, so please nobody take this until that one is merged.

**Comment by amulware** [comment]
This just occurred to me with as little as 35 minutes of inactivity (wasn't using my phone at all during that time).

**Comment by amulware** [comment]
I've also had it happen without having a timer running.

**Comment by sofokli1** [comment]
@amulware can you reproduce on @Odrakir's branch

**Comment by amulware** [comment]
I'll try and reproduce it there tomorrow. But as you're asking, let's schedule this issue for later, since it might be solved and isn't a priority for now.

**Comment by Odrakir** [comment]
Probably fixed in #2743, but somebody should try to reproduce it.

**Comment by amulware** [comment]
Haven't had and won't soon have time to test this. I'll see if it still happens to me once 1.9 comes out.

**Comment by heytherewill** [comment]
📱
