### ISSUE TITLE
Date covers AM/PM selector when Android OS is set to Chinese

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#2699]
An Android user who's set his OS to use Chinese text for the interface found that the date covers the AM/PM selector above The Wheel of Time:

![image](https://user-images.githubusercontent.com/5687885/42935850-50ab0a66-8b7d-11e8-92a1-a1229e8af20e.png)

## Context
@amulware: "[the Chinese language UI text] puts am/pm to the other side" 

Version: Giskard/1.0
Phone: HUAWEI HUAWEI NXT-AL10
OS: 7.0 M

(from /case/743777)

## Expected behavior
The AM/PM selectors should still be accessible regardless of the OS' language settings.

## To reproduce
Use the app on an Android device set to the Chinese language.

## Suggestions
As a non-mobile developer, I would suggest making the UI elements on The Wheel more independent of each other, layout-wise.

The current workaround is setting the account's time format to 24-hour, so that AM/PM can be selected through The Wheel of Time instead.

**Comment by amulware** [comment]
My proposal here would be to redesign this entire view. It's given us too many issues. But that's something to discuss when the boss is back from 🏖

**Comment by pe0ny** [comment]
Yep, the view will be redesigned completely. Hence I'm closing this issue.
