### ISSUE TITLE
Reports: Allow selecting workspace

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2702]
If users have more than one workspace, we want to allow them to select one on the reports page.

It'll default to the default workspace, and not hide the selection at all when there is only a single one.

Note that selecting a different workspace should re-fetch the report, just as if a different date range was picked.

**Comment by khoi** [comment]
https://github.com/toggl/mobileapp/blob/c49c29bbdd8c266b6a830975cc9e1ebf4c81c098/Toggl.Foundation/Reports/IReportsProvider.cs#L4-L8

`workspaceId` is already a parameter here. So can this issue be closed, or am I missing something?
