### ISSUE TITLE
Custom feedback UI

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2704]
iOS version here: #2626

**Comment by lizaPlotnikova** [comment]
The design for Android https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/dashboard?seid=5b50c70375135e8158e97d77:

- Feedback view can be opened from the Settings view or Timer view (when asking rating) 
- It is composed of the black Titlebar with "Send" primary action, some explanatory text, and a multi-line text field (styled the same way it is in the Login view)
- When the form submit has succeeded, we’ll close the view and show “Done” message (snackbar) at the bottom of the previous page (either Settings or Timer page)
- When form submit went wrong, we just close the keyboard and display the error message at the top of the Feedback view (this error message should be a component already in use in the create TE/edit TE views)
- If the user hits the Titlebar or system back button and he/she has entered text already, we should ask for confirmation. 

### Feedback UI
![submit feedback first load](https://user-images.githubusercontent.com/24964497/42959979-921f70ce-8b58-11e8-8aa9-8fa1cee9ffd4.png)
Zeplin:https://zpl.io/bPYEBOl

### Feedback UI (text entered)
![submit feedback content added](https://user-images.githubusercontent.com/24964497/42960020-acee7cc4-8b58-11e8-9c41-ef22a8492cad.png)

Zeplin: https://zpl.io/aB5zve0

### Confirmation screen
![submit feedback confirmation screen](https://user-images.githubusercontent.com/24964497/42960124-ec417f8e-8b58-11e8-8eea-7946de9999ff.png)

Zeplin: https://zpl.io/2pO3g6M

### Done
![submit feedback done](https://user-images.githubusercontent.com/24964497/42960199-19f5ee2e-8b59-11e8-9b5d-b510b01b5a1c.png)

### Zeplin: https://zpl.io/2EAQ8L8

### Error states
![submit feedback error 1](https://user-images.githubusercontent.com/24964497/42960222-30e87dae-8b59-11e8-82ef-188603ebd276.png)
![submit feedback error 2](https://user-images.githubusercontent.com/24964497/42960226-336996c6-8b59-11e8-8637-3eab57aadcc3.png)

Zeplin: https://zpl.io/ad73KDn & https://zpl.io/VOkvLEl

Please reach out with any comments or complaints! Thanks :)

**Comment by pe0ny** [comment]
@lizaPlotnikova Question: why the content has more padding from left and right than usual 16dp we use, is it intentional?

**Comment by lizaPlotnikova** [comment]
I've updated the padding in these designs to 16dp for consistency with other screens.

**Comment by daividssilverio** [comment]
Hey @pe0ny @lizaPlotnikova, I was following the design in zpl.io/VK411lE and the error icon is not aligned with the oops text. It looks ok on Zeplin, but it gets weird depending on the text that's currently showing "No internet connection. Please try again." or "Something went wrong. Please try again." depending on the current screen resolution since the text tends to wrap.

I aligned vertically the "OOPS!" and the error text inside the error card. Is it ok to align the icon to the oops text as well? it would look a little nicer, imo.

**Comment by lizaPlotnikova** [comment]
The last one looks best to my eyes. (center of icon aligned to the center of Oops text) Let's go with that. I'll adjust it in the design component.

**Comment by amulware** [comment]
That's definitely the way to go with icons like this. 👌
