### ISSUE TITLE
Hitbox for editing entry hasn't moved when "Enjoying Toggl" prompt shown

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#2714]
Hitbox for editing entry hasn't moved when "Enjoying Toggl" prompt shown

## 🐛 Bug Report
-Open app
-Sign up for new account
-Start entry, stop entry
-Feedback prompt shows and can interact correctly.
-Force close app
-Feedback prompt displays again
-This time if you attempt to press the thumbs up or down it instead brings up the edit menu for the time entry below.
-This seems to occur before sync has completed.
(While syncing the time entry is under the feedback buttons on the display. This only corrects after sync)
Once sync has completed however and the feedback prompt is dismissed the UI does not update correctly and instead shows a large gap between the "Today" heading and first time entry.

## Context

Build/Branch: This is in the special build to test the feedback prompt
Phone OS:11.4
Phone model: iPhone SE

## Expected behavior
Today and time entry should never be hidden by the feedback prompt and the hitboxes for each shouldn't be interfering with each other.
The UI should update afterwards and show the Today heading and time entry as normal.

## To reproduce
Force close the app, reopen and it occurs every time.

**Comment by sofokli1** [comment]
i have see this a few times. I think is some kind of race condition. will take a look

**Comment by sofokli1** [comment]
Also I think that under normal circumstances if the users restarts the app the rating ui will not show again. Will still take a look
