### ISSUE TITLE
Improve scrolling when the keyboard is open on Login/Signup

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2731]
## Description
Currently, when the keyboard is open on the Login/Signup views it's not possible to scroll the whole view.
The app is still usable, but the user has to close to keyboard to access the views closer to the bottom of the screen.

The problem is that bottom cards have to stay visible at all times based on the current design, so changing the `WindowSoftInputMode = SoftInput.AdjustPan` to `WindowSoftInputMode = SoftInput.AdjustResize` won't play well because it will make the bottom cards float over the login/signup fields.

## Suggestions
- This can be solved by changing the design of the layout :); making the bottom cards stay inside the scrollable container and not fixed at all times at the bottom of the screen
- Also, the layout can be refactored and the keyboard state can be "detected" and the position of the bottom card changed at run time.
- Just implementing #2712 could be enough.

**Comment by amulware** [comment]
This needs a decision from @pe0ny. I can see the sense behind all three options presented above.

**Comment by daividssilverio** [comment]
🤔 #2712 got implemented. Is this still an issue?
@pe0ny any thoughts? Are we implementing one of the 2 first options or #2712 is enough?

**Comment by amulware** [comment]
Good enough for now. There might be design changes coming down the line, and we'll look into login/signup flow a bit more, so let's shelf this for now. Leaving it open so we don't forget.

**Comment by heytherewill** [comment]
🗝
