### ISSUE TITLE
MvxIoCResolveException in MvxIoCContainer

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2734]
## 💥 Crash Report
There is some IOC resolution bug. It's not happening that often, so maybe it's a race condition or something else funny?

### 👥 Impact
- 60 occurrences in the last two days
- that's 10% of crashes in 1.1
- all sorts of phones

### 📡 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/05ddb6bb5a0759077ed1b80797044dd540772ead?appVersion=1.1

### 📝  Exception & Stack Trace
`MvvmCross.Exceptions.MvxIoCResolveException: Failed to resolve type MvvmCross.ViewModels.IMvxAppStart`
```cs
MvxIoCContainer.Resolve (System.Type t)
MvxIoCContainer.Resolve[T] ()
MvxIoCProvider.Resolve[T] ()
Mvx.Resolve[TService] ()
MvxActivityViewExtensions.OnViewDestroy (MvvmCross.Platforms.Android.Views.IMvxAndroidView androidView)
MvxActivityAdapter.EventSourceOnDestroyCalled (System.Object sender, System.EventArgs eventArgs)
(wrapper delegate-invoke) .invoke_void_object_EventArgs(object,System.EventArgs)
MvxDelegateExtensions.Raise (System.EventHandler eventHandler, System.Object sender)
MvxEventSourceAppCompatActivity.OnDestroy ()
MvxAppCompatActivity.OnDestroy ()
Activity.n_OnDestroy (System.IntPtr jnienv, System.IntPtr native__this)
```

**Comment by daividssilverio** [comment]
It looks like this is the same reported here https://github.com/MvvmCross/MvvmCross/issues/2810.
And I'm able to reproduce it the same way. Trying to find a fix in our case.

**Comment by daividssilverio** [comment]
To reproduce it: open the app and press home before immediately.
