### ISSUE TITLE
TimeoutException in RetryDelayService crashes app

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2737]
## 💥 Crash Report
This exception is thrown because a server-status-checking sync state took too long (this is on purpose). And somehow this seems to crash the app (this is very much not on purpose).

I'm thinking if maybe we should rethink the way we timeout in the case of the status retry. If we know we're gonna retry for longer than the timeout will allow for, why are we not simply stopping sync with a fail right there?

But even then, exceptions in the syncing algo should not crash the app.

### 👥 Impact
- over 260 crashes in 1.7.2 at time of writing
- that's 13% of crashes in 1.7.2
- all sorts of phones

- also, about 10% of all crashes in Giskard 1.2, again all sorts of phones

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/471c4d3fec614d025f8af27f082ccbc9a385f1f9?appVersion=1.7.2&period=last90Days

### :bug: Exception & Stack Trace
`System.TimeoutException: Retry delay 119.571s exceeded the maximum delay limit 60s.`
```cs
RetryDelayService.nextDelay (System.Double factor, System.Double defaultDelay)
RetryDelayService.NextSlowDelay ()
CheckServerStatusState.delay (System.IObservable`1[T] observable)
CheckServerStatusState.Start ()
TransitionHandlerProvider+<>c__DisplayClass1_0.<ConfigureTransition>b__0 (Toggl.Foundation.Sync.ITransition _)
StateMachine.performTransition (Toggl.Foundation.Sync.ITransition transition, Toggl.Foundation.Sync.TransitionHandler transitionHandler)
StateMachine.onTransition (Toggl.Foundation.Sync.ITransition transition)
AnonymousSafeObserver`1[T].OnNext (T value)
SingleAsync`1+Sequence+_[TSource].OnCompleted ()
Catch`2+_+HandlerObserver[TSource,TException].OnCompleted ()
FirstAsync`1+Sequence+_[TSource].OnNext (TSource value)
(wrapper unknown) System.Object.gsharedvt_out()
Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Merge`1+Observables+_+InnerObserver[TSource].OnNext (TSource value)
(wrapper unknown) System.Object.gsharedvt_in()
(wrapper unknown) System.Object.gsharedvt_out()
Delay`1+Base`1+L[TSource,TParent].DrainQueue (System.Reactive.Disposables.ICancelable cancel)
Scheduler+<>c.<ScheduleLongRunning>b__73_0 (System.Action`1[T] a, System.Reactive.Disposables.ICancelable c)
DefaultScheduler+LongRunning+<>c__DisplayClass1_0`1[TState].<ScheduleLongRunning>b__0 (System.Object arg)
ConcurrencyAbstractionLayerImpl+<>c__DisplayClass7_0.<StartThread>b__0 ()
ThreadHelper.ThreadStart_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
ThreadHelper.ThreadStart ()
```

**Comment by amulware** [comment]
This also happens on Android and is responsible for about 10% of the crashes in 1.2.

**Comment by dshr** [comment]
Still happens in 1.3.2: https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/60b6d9a814c4d5d95a9dedcd927f2ee803e7f787?appVersion=1.3.2&period=last90Days

**Comment by heytherewill** [comment]
@simonrozsival Is this still a thing after Leaky Bucket? 🤔

**Comment by simonrozsival** [comment]
Once #3835 is merged, there won't be any more `RetryDelayService`. Then we can close this.
