### ISSUE TITLE
Avoid reloading the main log tableview after displaying the rating view

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#2742]
## Context

As part of #2721, the table view is being reloaded always after displaying the rating view. We must investigate this deeper to avoid reloading the whole table.

Build/Branch: develop
Phone OS: iOS

## Expected behavior

Don't reload the whole table.

**Comment by amulware** [comment]
I'm honestly not sure if this is worth doing. The ratings view will be shown to a user typically once every few months or less.
