### ISSUE TITLE
Dates from last week of each month cannot be selected

### ISSUE THREAD

**Issue by djalex15** [toggl/mobileapp#2745]
## 🐛 Bug Report
When you want to edit a time entry and select a different start or end date, you are not able to select any date that is from the last week of each month. It does not matter if the current date falls into the last week of a month, you still cannot select any date from that last week.

It is also valid for previous months, not only for the current one.

This seems to be an issue for Huawei P9 Lite.

## Context
This issue was first encountered by a user (using Huawei P9 Lite) and later confirmed by me once I've tested it on the same phone.

I've used new time entries (created for this issue) as well as old time entries, same behavior.

I've also manually changed the time on my phone (to May & April) to create time entries in previous months - results were the same, you cannot select any date that is in the last week of a month.

That week is clearly shown on the actual screen, there are no clipping issues, it is just unclickable (screenshots below).
![image](https://user-images.githubusercontent.com/24280237/43266303-602f12de-90eb-11e8-8abf-55320695ab15.png)
_June - can only select dates from 14 - 24_

![image](https://user-images.githubusercontent.com/24280237/43266314-694f221e-90eb-11e8-84ff-10a87d9d0e01.png)
_July - can only select dates from 1 - 22_ || July 26 is the current date and is selected by default; if I click any other date, i.e. July 19, I won't be able to click July 26 again

Build/Branch: **Toggl Giskard - 1.1** - downloaded from the Play Store
Phone OS: **Android**
Phone model: **Huawei P9 Lite**

## Expected behavior
Select any date from the calendar when editing a time entry.

## To reproduce
This might be related only to particular phone model(s); I just tried to select/edit a date from last week of a month and it just wouldn't let me - those dates are just not reacting.

**Comment by kornelijepetak** [comment]
Fixed by #3024
