### ISSUE TITLE
Reusable Toast view

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#2750]
📑Description

We use toast view quite frequently in our app. Currently, we're constructing each toast individually and add it to the view we want to display it.

Let's create one that's reusable and allow us to customize it. 

✍️Suggestions: 

- There should be 2 type of toasts (success and error).
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5b43160025e2c904a0a14b36
https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5b4315ffb3366bcd6a0546f2

- The title and the description of the toast can be changed

- Some toast might have an button attached to it. https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5b31bb693ea3532eaabd8084

The toast has slight blur effect, @arturs105 has played around with the code for iOS below that could be used for references:

```csharp
var frame = new CGRect(10, 10, 300, 300);
var containerView = new UIView(frame);
var blurEffect = UIBlurEffect.FromStyle(UIBlurEffectStyle.Light);
var visualEffectView = new UIVisualEffectView(blurEffect);
visualEffectView.Frame = frame;
containerView.AddSubview(visualEffectView);

var blue = new UIView(frame);
blue.BackgroundColor = UIColor.Blue;
blue.Alpha = 0.5f;

//Add blue below containerView
View.AddSubview(blue);
View.AddSubview(containerView);
```

**Comment by Odrakir** [comment]
#2801 Get's us close to this, but still some customization has to be done. So this issue should not be closed until that's done.
