### ISSUE TITLE
Investigate the permissions apis of both iOS and Android

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2757]
Please investigate and post your findings here for future reference.  Ideally we should get:

- A list of the APIs needed (with links to its docs),
- An idea of how easy it's to use it (is it easy to consume it in an async/reactive fashion? Lifecycles?)
- How similar both apis are, (what’s the iOS/Android counterpart of apis? if none is available, how could we make a non-leaky abstraction?)
- links to existing Xamarin library we can base our implementation on, if any Investigate the local notification apis of both iOS and Android

**Comment by arturs105** [comment]
**iOS permissions**
* Info.plist file needs explanations on why we need those permissions. This explanation is the copy that is shown in the dialog when asking for the permission. This is done with adding the following keys with some string values:
  * `NSCalendarsUsageDescription`
  * `NSRemindersUsageDescription ` (if we're gonna use reminders)
* We can check whether the permission has been already granted by using a static method `EKEventStore.GetAuthorizationStatus(EKEntityType)`, where `EKEntityType` is an enum of two values: `Event` and `Reminder`.
* Requesting permissions requires an instance of `EKEventStore`, which can be obtained by using the parameterless constructor of the class.
* There are 2 methods to ask for the permission: `RequestAccess(EKEntityType type, Action<bool, NSError> callback)` and `RequestAccessAsync(EKEntityType)`. Both of the methods work asynchronously, however with the latter we can use `async/await`.
* Here is the `EKEventStore` documentation:
  * [Native docs](https://developer.apple.com/documentation/eventkit/ekeventstore)
  * [Xamarin docs](https://developer.xamarin.com/api/type/EventKit.EKEventStore/)

**Comment by arturs105** [comment]
**Android permissions**
* No control of the copy that shows when asking the permission, however i've seen some apps show their own dialog explaining the usage and only then show the actual permission request. There's even a method to help with this: `shouldShowRequestPermissionRationale()`. The method returns true if the user has previously declined the permission.
* Appropriate `<uses-permission/>` tags need to be added to the manifest. Permissions that we are interested in are:
  * `<uses-permission android:name="android.permission.READ_CALENDAR"/>`
  * `<uses-permission android:name="android.permission.WRITE_CALENDAR"/>`
* On pre sdk-23 all the permissions are granted at install time. The only way the user can deny the permissions is to not install the app.
* On sdk-23 and later, we need to use runtime permissions that work similar to iOS permissions.
* Permission status can be checked with `ContextCompat.CheckSelfPermission(this, Android.Manifest.Permission.ReadCalendar);`.
* Permission can be requested with `ActivityCompat.RequestPermissions(activity, permissions, request code)`.
* Unfortunately requesting permissions isn't awaitable and what's even worse, the callback must be an override of `onRequestPermissionsResult ` inside an activity. I think this will be our biggest obstacles in creating a common interface for getting permissions.
* [Android docs on requesting permissions](https://developer.android.com/training/permissions/requesting)

**Comment by arturs105** [comment]
Regarding the shared permission library, I found a nuget plugin that does exactly that. The plugin source can be found [here](https://github.com/jamesmontemagno/PermissionsPlugin). There's even a [blog post](https://montemagno.com/simplified-ios-android-runtime-permissions-with/) about the plugin.

We can either use the plugin as is, or base our solution on it.
