### ISSUE TITLE
Editing description is very hard

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2764]
## 🐛 Bug Report
I'm not exactly sure why or how it behaves exactly, but I have a hard time editing descriptions in the edit view. Just tapping the edit view doesn't seem to focus it and open the keyboard. Either the hitbox is funny, or there is some other glitch.

What works is double dapping to select a word, which can be deleted to make a cursor appear, but that's no good.

What also works is long pressing to insert a cursor.

## Context
Build/Branch: Any that I've tested recently, including 1.7 stable
Phone OS: iOS
Phone model: iPhone 6S for me, but probably all iPhones

## Expected behavior
Tapping the description area, i.e. the whole bar from all the way left, to all the way right, from right under the header of the edit view to the separator line below should put a cursor into the description, or at the end of the description, not sure which makes more sense.

## To reproduce
- Go to edit a time entry
- Tap description field
- Nothing happens

## Suggestions
Ideas for fixing: No, I have no idea what's wrong. At least it should be easily reproducible.
Workaround: Long pressing makes the cursor appear.

**Comment by juanlaube** [comment]
This was fixed in https://github.com/toggl/mobileapp/pull/2706, the fix will be included in Daneel 1.8
