### ISSUE TITLE
Bugs in NoWorkspaceViewModel

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#2769]
## 🐛 Bug Report
Some bugs were discovered while testing the NoWorkspace UI.

- [x] `dataSource.User.Current` must call `FirstAsync()` otherwise it will never complete
- [ ] It doesn't sync the new workspace after creation. This seems simple, but it requires that a new `SyncManager` gets created and the old one gets disposed. The old one isn't usable because it has encountered an error (`NoWorkspaceException`) and is 💀.
- [ ] `TryAgain` method needs to be fixed. Due to the same SyncManager failure, a new one is required each time `TryAgain` is executed.
- [ ] When the issues are solved, the view presentation should be re-enabled in `ErrorHandlingService`.

To the person, who works on this: while you're at it, you might as well convert the view model's public methods to the new `RxAction`s (#2751).

## Expected behavior

No crashes 🙂

**Comment by arturs105** [comment]
Giving up on fixing these in #2762.

**Comment by amulware** [comment]
I was told that the sync manager does not get killed on this exception. Were we wrong then, @juanlaube?

**Comment by juanlaube** [comment]
Yeah, I was absolutely wrong about this 🙈
