### ISSUE TITLE
Longer button names break into multiple lines

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2776]
## ⛑️ User Support
We use localized button names, which vary in length. Apparently, at least some of our buttons do not resize themselves accordingly and break the text into multiple lines.

This happens at least in the time popup, but possibly also other places.

## About the user

Version: Giskard/1.0 
Phone: samsung SM-J510FN 
OS: 6.0.1 LOLLIPOP_MR1
OS Language: German

## Expected behaviour
We should either not localize these buttons, or we should make their size adjust to their content.

This decision should be made by @pe0ny.

## To Reproduce
Set your phone to a language that has long words. The screenshot is in German. I'm not sure if the size of the screen matters as well.

<img width="561" alt="screen shot 2018-07-31 at 11 54 25" src="https://user-images.githubusercontent.com/3987892/43456086-073b0cc8-94ba-11e8-9eb7-43064dd9f275.png">

**Comment by pe0ny** [comment]
Since the whole app is in English, we should not localize these buttons.
