### ISSUE TITLE
Scrollability in time view calendar

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2777]
## 🐛 Bug Report
On my Xiaomi 5A (running Android 7), there is a scrollbar in the calendar, so I can scroll to see the 6th week of a month.

On the random Samsung Galaxy J5 (SM-J510FN) (running Android 6) there is no scrollbar. There is also no separator line between the calendar and buttons below.

Xiaomi 5A / Samsung J5

<img width="1121" alt="screen shot 2018-07-31 at 12 21 36" src="https://user-images.githubusercontent.com/3987892/43456677-52896272-94bc-11e8-863e-b3be20231efa.png">

## Expected behavior
This should work the same on all phones. Either be scrollable or big enough/adapt to the size of the calendar. Ping @pe0ny for intended behaviour.

## To reproduce
Check different phones/OSes(?), and check with a month that spans six weeks.

**Comment by pe0ny** [comment]
Since it should fit to all screen sizes it should be big enough - scrolling is not intended behaviour.
