### ISSUE TITLE
Create (and mock) the ICalendarService

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2790]
Ref #2754 for architectural details
Ref #2755 for API usage details

We need to introduce the `ICalendarService` (this name is encouraged to be improved) interface, allow for it to be registered from the Foundation initialization and mock it in the Foundation layer so that Droid (and iOS for the time being) don't crash, similar to what we're doing with the `PasswordManagerService`.

Tests should be added as applicable.

**Comment by juanlaube** [comment]
Closed by #2824
