### ISSUE TITLE
Introduce (and mock) the IPermissionService

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2791]
Ref #2754 for architectural details
Ref #2757 for API usage details

We need to introduce the `IPermissionService` interface, allow for it to be registered from the Foundation initialization and mock it in the Foundation layer so that Droid (and iOS for the time being) don't crash, similar to what we're doing with the PasswordManagerService.

Tests should be added as applicable.

**Comment by juanlaube** [comment]
Closed by #2803
