### ISSUE TITLE
Introduce (and mock) the IFeatureService

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2793]
Ref #2754 for architectural details

This service is meant to be created on the MvvmCross layer, since it's not directly tied to Toggl business logic, but rather to the way we wanna rollout app features.

Similar to the other interface issues, we need to create the interface, allow for it to be registered from the Foundation initialization and mock it in the Foundation layer so that Droid (and iOS for the time being) don't crash, similar to what we're doing with the PasswordManagerService. 

The mock should always return `true` so that the calendar tab is always visible. We will change it so it always returns false before merging the branch back in develop.

Tests should be added as applicable.

**Comment by arturs105** [comment]
I'm not sure we need a new class for this, since `IRemoteConfigService` already accesses Firebase.

**Comment by willsb** [comment]
I didn't know about that. Let's then just add a property for our own thing there!

**Comment by juanlaube** [comment]
Closed by #2842
