### ISSUE TITLE
Add the means of navigating to the CalendarViewController

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2797]
Depends on #2795 and #2796

If #2771 is merged, please add a new tab item. Otherwise, add the calendar icon to the navigation bar and open an issue to move it to the Tab bar later.

Either way, the tab should respect whether the icon should be visible or not (this will already be properly implemented in the VM) and only allow navigation when the FeatureService says it's possible.

**Comment by juanlaube** [comment]
Closed by #2863
