### ISSUE TITLE
Duration editing in the creation view looks weird

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2817]
## 🐛 Bug Report
There is something with the constraints of the duration input. When you focus the duration input, it moves to the top left a bit. See the screenshot for details.

Build/Branch: develop, 1.8
Phone OS: iOS
Phone model: iPhone X, iPhone 7

## Expected behavior
The input should be aligned with the elapsed time label.

## To reproduce
Go to the app and start a new time entry, tap on the elapsed time label to focus the underlying input.

![duration_glitch](https://user-images.githubusercontent.com/374616/43640305-bc97c306-971f-11e8-89b5-142840eadd50.png)

**Comment by dshr** [comment]
I’ve encountered this while doing #2305. I’ve fixed it too, while going through all the constraints in that view.
