### ISSUE TITLE
CircularRevealAnimation.Start fails

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2822]
## 💥 Crash Report
The animation is started in a detached view. That's no good.
https://github.com/toggl/mobileapp/blob/b4c79b96bde0591e76ec674c01c2d7cb7bcd2bf9/Toggl.Giskard/Extensions/CircularRevealAnimation.cs#L107-L139

### 👥 Impact
- this has happened 10 times to 5 users in Giskard 1.2 so far
- that's about 5% of all crashes in that build
- different devices, different OS versions

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/51ffbe2151e20bf8d3a1e010bd6afa08b4b56e92?appVersion=1.2

### 📝  Exception & Stack Trace
`Java.Lang.RuntimeException: Cannot start this animator on a detached view!`
```cs
ExceptionDispatchInfo.Throw ()
JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters)
ViewAnimationUtils.CreateCircularReveal (Android.Views.View view, System.Int32 centerX, System.Int32 centerY, System.Single startRadius, System.Single endRadius)
CircularRevealAnimation.<Start>b__17_0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object.9b06c185-ebaa-449c-8e75-191b5b555028(intptr,intptr)
java.lang.IllegalStateException: Cannot start this animator on a detached view!
android.view.RenderNode.addAnimator(RenderNode.java:799)
android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:299)
android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:281)
android.animation.RevealAnimator.(RevealAnimator.java:37)
android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:71)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
android.os.Handler.handleCallback(Handler.java:789)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:251)
android.app.ActivityThread.main(ActivityThread.java:6572)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by daividssilverio** [comment]
:wat: But... but... I guess the `RunWhenAttachedToWindow` needs some tweaking...

**Comment by daividssilverio** [comment]
Not easy to reproduce and not affecting a lot of people.
20 people are affected right now with 26 events in total.
Let's put this aside for now and check again later if needed.

If really necessary, we can add another check inside
```c#
view.RunWhenAttachedToWindow(() =>
      if (view.IsAttached) { ... animate }
      else { simply change visibilities }
});
```

An extra step would add a listener to the TreeObserver of the view in question and run the code after `GlobalLayout`. But I'd only do that if I could reproduce the crash in question and that is the last option (easy to mess up).
