### ISSUE TITLE
RemoteConfigFetchFailedException

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2828]
## 💥 Crash Report
Looks that we don't handle failure to fetch remote config from Firebase correctly. Obviously, that failure should not crash our app under any circumstances. It should simply use the previous/default values and try again later (I'm assuming this is implemented by the Firebase SDK).

https://github.com/toggl/mobileapp/blob/f2c2f0271b6da21cef52f95062902a75a38b8ef7/Toggl.Daneel/Services/RemoteConfigService.cs#L13-L32

### 👥 Impact
- this has happened 558 times to 84 users in 1.8 so far
- that's over 90% of all crashes in 1.8
- all sorts of devices

### 🔗 Context
This was introduced with the recent ratings dialog.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/09c114c97fd0201409c7fde9cb0d116711aa2782?appVersion=1.8

### 📝  Exception & Stack Trace
`Toggl.Foundation.Exceptions.RemoteConfigFetchFailedException: The operation couldn’t be completed. (com.google.remoteconfig.ErrorDomain error 8003.)`
```cs
ExceptionDispatchInfo.Throw ()
ExceptionServicesImpl.Rethrow (System.Exception exception)
ExceptionHelpers.Throw (System.Exception exception)
<.cctor>b__2_1 (System.Exception ex)
(wrapper unknown) System.Object.gsharedvt_out()
AnonymousSafeObserver`1[T].OnError (System.Exception error)
(wrapper unknown) System.Object.gsharedvt_out()
Select`2+Selector+_[TSource,TResult].OnError (System.Exception error)
(wrapper unknown) System.Object.gsharedvt_out()
SelectMany`2+ObservableSelector+_[TSource,TResult].OnError (System.Exception error)
(wrapper unknown) System.Object.gsharedvt_out()
AutoDetachObserver`1[T].OnErrorCore (System.Exception exception)
(wrapper unknown) System.Object.gsharedvt_out()
ObserverBase`1[T].OnError (System.Exception error)
RemoteConfigService+<>c__DisplayClass1_0.<get_RatingViewConfiguration>b__1 (Firebase.RemoteConfig.RemoteConfigFetchStatus status, Foundation.NSError error)
Trampolines+SDRemoteConfigFetchCompletionHandler.Invoke (System.IntPtr block, System.nint status, System.IntPtr error)
(wrapper native-to-managed) ObjCRuntime.Trampolines+SDRemoteConfigFetchCompletionHandler.Invoke(intptr,System.nint,intptr)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)

```

**Comment by sofokli1** [comment]
There is no point in assigning this to self. The more people work on this the better.

**Comment by sofokli1** [comment]
I managed to reproduce the crash by:
- fresh install with 1.7.2
- update code to 1.8
- close the internet connection
- run the app
- 💥

I assume the users are updating the app when they have internet and start using the app offline and 💥.
Good news when the app runs with internet connection the crash should not happen.

**Comment by dshr** [comment]
There is not point in throwing an exception there when Firebase lets us use a default config and retry fetches using `remoteConfig.Fetch(expirationDuration:, completionHandler:)` ✨ .

For the default config we can use a .plist file loaded using `remoteConfig.SetDefaults(plistFileName:)`. What are our defaults right now?

**Comment by dshr** [comment]
Closing this.
