### ISSUE TITLE
Ratings dialog not disappearing after inactivity

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2829]
## 🐛 Bug Report
From the specs in https://github.com/toggl/mobileapp/issues/1972
> - When the app goes into background and user comes back before 5 mis has passed, he/she can still see the popup. After 5 min, the popup will be hidden.

This does not seem to happen. I've gone back to the app multiple times now, including after having it in the background for 20 minutes, and it's still there.

## Expected behavior
What the specs say:
> - When the app goes into background and user comes back before 5 mis has passed, he/she can still see the popup. After 5 min, the popup will be hidden.

I believe the intention was to snooze it for 24h - but I don't see that in the specs right now. Am I confusing something, or did I miss it? Or should it just happen on the next time the trigger happens?

Comment from @pe0ny would be appreciated as well.

## To reproduce
- Get the dialog to appear
- Don't interact with it, put app in background
- Come back after a while
- It's still there

**Comment by pe0ny** [comment]
@amulware The expected behaviour is the following:

From #1972
> When user hasn’t interacted with the card in a 5 min, hide it and don't show it anymore.
> - When the app goes into background and user comes back before 5 mis has passed, he/she can still see the popup. After 5 min, the popup will be hidden.
> - When user closes the app completely, the popup will be hidden despite the time passed.

**Comment by amulware** [comment]
But once hidden, can it be shown again?

**Comment by sofokli1** [comment]
it should snoozes for 24h. after that is gone for good

**Comment by amulware** [comment]
I'm not sure we're on the same page here. The dialog keeps just sitting there, even though I have the app closed for more than 5 minutes all the time.

It should be hiding it if I come back after more than 5 minutes of background time, but it isn't.

**Comment by dshr** [comment]
@pe0ny @sofokli1 I don't see anything regarding snoozing in #1972 :( Is there a chance it was discussed in Slack and not written down?

**Comment by sofokli1** [comment]
@dshr take a look at issue #2620
