### ISSUE TITLE
Rename one of the calendars

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#2830]
With the new calendar that we're working on, we now have two calendars:
* In reports
* The new log/calendar.

We should rename one of those, so it's easier to distinguish which classes are used for which calendar. We could prefix all the reports calendar stuff with `ReportsCalendar`. That includes quick select shortcuts, view models, view controllers, tests and anything else that has `Calendar` in it's name and is referring to the reports calendar.

**Comment by willsb** [comment]
Should this be closed?

**Comment by dshr** [comment]
Yes, idk why GH didn't close it automatically.
