### ISSUE TITLE
Add a way to persist the list of calendars in the storage

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2843]
We don't need to change Realm for this. We just need a way to read/persist the list of calendars the user wants to use. 

If we do it in the [`SettingsStorage`](https://github.com/toggl/mobileapp/blob/develop/Toggl.PrimeRadiant/Settings/SettingsStorage.cs) we won't even need to have a droid issue because it'll leverage on our existing storage mechanisms! 

Regardless of using the existing base class, I'd add another interface to keep separation of concerns in check

**Comment by juanlaube** [comment]
Closed by #2860
