### ISSUE TITLE
Calendar Onboarding screens

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2848]
Depends on #2843, #2844 and #2797
This also depends on the designs being final and on zeplin rather than on redpen, so hold yer horses before working on this issue.

## [The initial state screen](https://redpen.io/kz07d47b0bb570a549)
This is meant to be shown the first time the user navigates to the calendar screen. We should keep track of this using a property in the [`IOnboardingStorage`](https://github.com/toggl/mobileapp/blob/develop/Toggl.PrimeRadiant/Settings/IOnboardingStorage.cs)<sup>1</sup>. This property should only be set once the onboarding is completed.

## [Permission asking screen](https://redpen.io/uf9838f698ca7de46a)
This one is simple. once the user clicks the "Get Started" button, he/she will see the native iOS permission popup and will have two options. We should check in the ViewModel whether permission was given or not and react accordingly.

## [Permission denied popup](https://redpen.io/xp11d3876bc55a0845)
This one will appear once permission is denied. This does not need to be a ViewModel (for it'll only appear this one time), but rather a view that will have its visibility controlled. Clicking the continue button will end the onboarding and show the calendar view. Clicking the smaller link will take the user to the iOS settings. If permission is given when he/she returns the app, the onboarding continues. Otherwise, the onboarding ends.

## [The Select calendar popup](https://redpen.io/hd12d5dc6cae47ae4a)
This one will appear after the native iOS popup, should the user give us permissions. This should also not be another ViewModel, similar to the modal that tells the user he/she can toggle the calendar permissions in the settings. This will allow the user to select which calendars should be used by the calendar view. Clicking done finishes the onboarding.

## Once the onboarding is done
Regardless of how the onboarding ends, once it's done we should show the user the calendar view and set the flag that indicates the onboarding has been taken to true. The user can change whichever settings later in the settings page.

<sup>1</sup> Or maybe in the newly created `CalendarSettingsStorage`? I'll leave this as an exercise to the reader.

**Comment by pe0ny** [comment]
### The initial state screen
![calendar first time view step1](https://user-images.githubusercontent.com/5064445/43837994-dd12e58c-9b22-11e8-90e8-1fd400510268.png)

Zeplin: https://zpl.io/bLO7BGG


### Permission asking screen
![calendar first time view step2 1x](https://user-images.githubusercontent.com/5064445/43838022-ed94f0bc-9b22-11e8-9e35-25e978583d11.png)

Zeplin: https://zpl.io/bAqzqWe


### Permission denied popup
![calendar access denied 1x](https://user-images.githubusercontent.com/5064445/43838063-0298a8c8-9b23-11e8-8de4-4e29978bc177.png)

Zeplin: https://zpl.io/awY7YPK


### The Select calendar popup
![calendar first time view step3 1x](https://user-images.githubusercontent.com/5064445/43838089-1197f72a-9b23-11e8-995d-3900a6a8a02f.png)

Zeplin: https://zpl.io/a3qNqd8


### The Select calendar popup: with groups
![calendar first time view step3 grouped 1x](https://user-images.githubusercontent.com/5064445/43838121-2527f72c-9b23-11e8-965f-3838c72e5cd8.png)

Zeplin: https://zpl.io/beYXYOp

### The Select calendar popup: long list with scrolling
![calendar first time view step3 scrolling 1x](https://user-images.githubusercontent.com/5064445/43838147-3676f76c-9b23-11e8-9de7-78fa7fedfcac.png)

Zeplin: https://zpl.io/V0ydy5m
