### ISSUE TITLE
Consuming the calendar interactor in the CalendarViewModel

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2867]
We need to consume the Interactor introduced in #2849 (the one that fetches the `CalendarItem`s from the database/calendar) and expose its results as an observable in the CalendarViewModel. Pretty simple. This doesn't need to consume anything in the ViewController, just the Foundation changes and their appropriate tests.

The other interactor is meant to be consumed in the Onboarding issue, so this covers everything we need for now.

**Comment by juanlaube** [comment]
Closed by #2908
