### ISSUE TITLE
Bind the calendar item observable to the calendar collection view

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2868]
Depends on #2799 and #2867 

This is the iOS counterpart of #2867. We need to consume the exposed observable and bind it to the existing collection view.

⚠️This concerns only displaying the calendar entries! No need to worry about the additional functionality like TimeEntry creation by tapping calendar entries or the draggable time entries yet. ⚠️

**Comment by juanlaube** [comment]
Closed by #2946
