### ISSUE TITLE
Handle CalendarItem taps in the ViewModel

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2869]
We need to create an RxAction that receives a CalendarItem and handles them accordingly. That is:

- `switch` on the source
- If the source is database, open the `EditTimeEntryViewModel`  so the user can edit that time entry
  - When the user closes the `EditTimeEntryViewModel` we should reload the calendar view, for that time entry might've changed
- If the source is a calendar, we need to create a new time entry using the calendar info
  - Once created, we need to reload the calendar items as well, since a new time entry exists

No change in the iOS view is needed as of yet. Lots of testing is needed, however.

**Comment by juanlaube** [comment]
Closed by #2910
