### ISSUE TITLE
Calendar: Main Calendar view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2874]
The Calendar view allows users to see their existing time entries and events from the calendar. Currently, we allow the user to see only a daily timeline (from midnight to midnight). Keep in mind that in the future we would like to add an option to switch between days and/or select a day from the datepicker.

Calendar view should respect 12/24-hour clock setting.

Separators are displayed for every hour. Time entries and Events can be displayed in a 15 minute level of detail.

**Calendar: Time entries** #2875
**Calendar: Events** #2876 

### Calendar view
![calendar](https://user-images.githubusercontent.com/5064445/43821618-59898fac-9af2-11e8-9850-7ff61c1e366c.png)

Zeplin: https://zpl.io/aB57NlK

### When scrolled to the top
![toggl - ios - calendar top 1x](https://user-images.githubusercontent.com/5064445/43821747-a772884a-9af2-11e8-889e-60c3913c569e.png)

Zeplin: https://zpl.io/29Zv91W

### When scrolled to the bottom
![toggl - ios - calendar bottom 1x](https://user-images.githubusercontent.com/5064445/43821776-bad292cc-9af2-11e8-894d-c3539d3c7702.png)

Zeplin: https://zpl.io/2EAO7ov

### 12-hour time
![toggl - ios - calendar 12-hour time 1x](https://user-images.githubusercontent.com/5064445/43821834-dc0c0b44-9af2-11e8-9ecd-6577745a63aa.png)

Zeplin: https://zpl.io/boxOleW

**Comment by willsb** [comment]
Closed by #3034
