### ISSUE TITLE
Calendar: Time entries

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2875]
- Existing time entries are coloured according to project
- When a time entry doesn’t have a project assigned, use no-project colour
- Overlapping time entries might exist and, in that case, they should be shown side by side. Padding between side by side time entries should be 4pt.
- On a time entry, we display description only
- When a time entry doesn’t have a description, display “No description”
- Tapping on the time entry opens the edit view
- Long press makes the whole cell drag-able, allowing the user to change offset the time entry #2878

**Comment by willsb** [comment]
Closed by #3031
