### ISSUE TITLE
Calendar: Events

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2876]
- Events are coloured according to the colour of the calendar that they were imported from
- If it happens that we can't get the colour from the calendar, use no-project colour
- All events have background opacity 24%
- Events have a little calendar icon at the front of the description to indicate these are imported from the calendar and are not regular time entries.
- Icon and text have the same colour as the background with 100% opacity
- As for time entries, overlapping events might exist as well and, in that case, they should be shown side by side like time entries. Padding between side by side time entries/events should be 4pt.
- Calendar events are always positioned on the left side. For example, if there are overlapping events and time entries, then events are always on the left and time entries on the right.
- Events have the description that is imported from the calendar
- If there is no description, display “No description”
- Tapping on the calendar event creates a new time entry without any dialog confirmations next to the existing calendar event. When a calendar event is turned into a time entry, the event should still remain visible. _This is because there's no trivial way to tie time entries to suggestions that don't involve either persisting calendar entries or using complex heuristics that will still fail._

**Comment by willsb** [comment]
Closed by #3031
