### ISSUE TITLE
Calendar: Error states for time entries

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2877]
When time entries are not synced or can't be synced, similar icons should be displayed as we display in the Timer page.

- Show the exclamation mark in a circle when time entry can't be synced.
- Show the syncing icon with the exclamation mark when time entry is not yet synced.

### Error states
![calendar error states 1x](https://user-images.githubusercontent.com/5064445/43822874-185fa7ec-9af6-11e8-9046-848861d59f04.png)

Zeplin: https://zpl.io/bAq8YJO

**Comment by willsb** [comment]
Closed along with #2932
