### ISSUE TITLE
Calendar: Draggable time entries

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2878]
The long press makes the whole cell drag-able, allowing the user to change offset the time entry.

- While dragging the time entry, the current one should remain visible with opacity 16% to indicate previous start-stop times.
- On the left side, we should also highlight the new start time.

### Draggable time entry
![calendar dragging 1x](https://user-images.githubusercontent.com/5064445/43826500-21f4b266-9b00-11e8-8ba3-717614a04aa4.png)

Zeplin: https://zpl.io/beYN5vq

**Comment by willsb** [comment]
Closed by #3035
