### ISSUE TITLE
Calendar: Creating a new time entry

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2879]
Users can tap on a non-filled space in the Calendar view and drag their thumb to create a new time entry. This opens an Edit view with start-end and duration value already filled.

When the user is creating a new time entry in the Calendar view, allow him/her to add it on a 15min level detail.

- By default, a new entry uses no-project colour
- By default, a new entry description should be empty. However, when the user is dragging the cell to create a new entry in the Calendar view, we should display “New time entry” in the description field.
- On the left side, we should highlight the selected time period while dragging. For example, 11:00 - 11:15

### Creating a new time entry
![toggl - ios - calendar new event v1 1x](https://user-images.githubusercontent.com/5064445/43825670-04c49ca8-9afe-11e8-8540-cec7be9c89f9.png) 

![toggl - ios - calendar new event v2 1x](https://user-images.githubusercontent.com/5064445/43825672-06ff7628-9afe-11e8-9c3d-737a5ad2d833.png)

Zeplin: https://zpl.io/2vYr5Av & https://zpl.io/anKMXRO

**Comment by willsb** [comment]
Closed by #3035
