### ISSUE TITLE
Refactor showing/hiding the Rating view using observables instead of hints

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2882]
We had a problem with the presentation hints for showing and hiding the rating view in 1.8 (issue #2829 fixed by #2880). The main view is already rxfactored, so we can remove the hints and use an boolean observable for visibility of the rating dialog and subscribe to this observable instead of using hints.

**Comment by amulware** [comment]
Do be careful with this one and make sure to test the rating view well.
