### ISSUE TITLE
ArgumentOutOfRangeException in start view SegmentedRecyclerAdapter

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2884]
## 💥 Crash Report
Typing `@projectname` really fast into the start view crashes the app.

### 👥 Impact
Not sure, seems to only have occurred to me according to App Center (no occurrences of the same stack trace in 1.2), but I can reproduce it 100% of the time on my 🐌 device. There are a couple of similar stack traces though, so maybe those crashes are related.

### 🔗 Context
/shrug

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/1b737b48e77684ca69ce8264d2364f14bba50725?appVersion=1.3&period=last7Days

### 📝  Exception & Stack Trace
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
```cs
List`1[T].get_Item (System.Int32 index)
Collection`1[T].get_Item (System.Int32 index)
SegmentedRecyclerAdapter`2[TCollection,TItem].tryGetItem (System.Int32 viewPosition)
SegmentedRecyclerAdapter`2[TCollection,TItem].GetItem (System.Int32 viewPosition)
CreateSuggestionGroupedTableViewSource`2[TCollection,TItem].GetItem (System.Int32 viewPosition)
StartTimeEntryRecyclerAdapter.GetItem (System.Int32 viewPosition)
MvxRecyclerAdapter.GetItemViewType (System.Int32 position)
RecyclerView+Adapter.n_GetItemViewType_I (System.IntPtr jnienv, System.IntPtr native__this, System.Int32 position)
(wrapper dynamic-method) System.Object.45bb1d35-2f77-4752-9e56-5793b63f2c90(intptr,intptr,int)
```

**Comment by heytherewill** [comment]
💪
