### ISSUE TITLE
Reports: WS select button hides the content

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#2893]
## 🐛 Bug Report
Currently, WS select button hides the content permanently when you scroll at the bottom of the Reports list.

## Context

Build/Branch: I'm testing the current `develop` branch

## Expected behaviour
As we don't want the button to obscure any content permanently, extra padding should be added below the projects table only when the WS button is visible. When user has only one WS and we don't show the button, extra padding is not needed.

Design how this should look like is available in Zeplin: https://zpl.io/2vYZqA5

**Comment by simonrozsival** [comment]
The PR was merged into the release branch.
