### ISSUE TITLE
Layout of calendar selector in edit Time Entry view breaks minutes selectors

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#2897]
## 🐛 Bug Report
From the user: I can change my work minutes only from “Duration” window. If I’m trying to change it with “Start” or “Stop” windows, then nothing happens

![image](https://user-images.githubusercontent.com/5687885/43892820-530020fc-9bcd-11e8-9c2e-05fa8dacabac.png)

## Context
The calendar (which I assume is based on Android's default calendar UI) is not shown properly. This seems to break the functionality of the Start and Stop tabs.

Build/Branch: Giskard 1.2
Phone OS: Android 5.0
Phone model: Asus ZenFone2 ZE551ML

## Expected behavior
The calendar should show without the date and year header, and tapping on the small clock icon beside the date should make the wheel of time available.

## To reproduce
@daividssilverio would you mind sharing the steps you took in the emulator?

**Comment by daividssilverio** [comment]
About this issue: It is as easy to reproduce as using an Android 5.0 emulated device.
We can just hide the big "Day / Year" green thing there, but the calendar date picks need a little tweaking as they don't seem to be calling the appropriate callbacks.

**Comment by heytherewill** [comment]
🔵
