### ISSUE TITLE
Create Api Endpoints

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#29]
There is a number of endpoints we have to implement.
The list below is mostly complete (for our purposes here), but may change over time, and also has some inconsistencies, as well as gaps, and a bunch of question marks as to which exactly are needed.

I will improve this list in the future as our specs solidify.

These should be implemented in separate PRs. This issue serves merely to have an overview and status report.

**On the HttpMethod**

Note that the different HTTP methods mostly follow the following pattern:
- GET: retrieve a list of objects, or a single one if an id is given
- POST: create a new object
- PUT: update an existing object with the given id
- DELETE: delete an existing object with the given id

Workspace
- [x] GET /me/workspaces
- [ ] POST /workspaces (needed soon(tm))
- [x] GET /workspaces/{WID} (is this needed?)
- [ ] ~~PUT /workspaces/{WID} (is this needed?)~~
- [ ] GET /workspaces/{WID}/preferences
- [ ] ~~POST /workspaces/{WID}/preferences (probably not needed)~~
- [ ] GET /workspaces/{WID}/preferences/time_entry_constraints
- [ ] ~~POST/PUT /workspaces/{WID}/preferences/time_entry_constraints (probably not needed)~~

Client
- [x] GET /me/clients
- [x] POST /workspaces/{WID}/clients
- [ ] ~~PUT /workspaces/{WID}/clients/{CID} (is this needed?)~~

Projects
- [x] GET /me/projects
- [x] POST /workspaces/{WID}/projects
- [ ] ~~GET /workspaces/{WID}/projects/{PID} (is this needed?)~~
- [ ] ~~PUT /workspaces/{WID}/projects/{PID} (is this needed?)~~
- [ ] ~~DELETE /workspaces/{WID}/projects/{PID} (is this needed?)~~

Tasks
- [x] GET /me/tasks
- [x] POST /workspaces/{workspace_id}/projects/{project_id}/tasks

Time Entries
- [x] GET /me/time_entries
- [x] POST /workspaces/{WID}/time_entries
- [x] PUT /workspaces/{WID}/time_entries/{TID}
- [x] DELETE /workspaces/{WID}/time_entries/{TID}

Tags
- [x] GET /me/tags
- [x] POST /workspaces/{WID}/tags

Workspace Features
- [x] GET /me/features
- [ ] ~~GET /workspaces/{workspace_id}/subscription/features (probably not needed)~~

**Comment by amulware** [comment]
I updated the post above:

We should use `/me/workspaces` to get all workspaces, just like the other end points.

**Comment by amulware** [comment]
Updated again. Crossed out endpoints we won't need for the MVP. We also won't do time entry constraints for now, but those should be on our radar for soon after.

**Comment by simonrozsival** [comment]
I updated the post:

- added POST /workspaces/{WID}/tags
- checked /me/features

**Comment by amulware** [comment]
Closing this as by now pretty much unnecessary.
