### ISSUE TITLE
Animations: From login to Timer page

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#290]
![toggl-ios-login-to-timer](https://user-images.githubusercontent.com/5064445/28354409-768e2c98-6c68-11e7-9042-b4afb79e6bdd.gif)

- When user enters a password and taps 'Next', change background color, fade in timer page elements except time entries and play button. After .2 delay show time entries with .08 delay each. Then show play button with .1 delay.

```javascript
toggl.next.onTap ->
	hideEye()
	showSpinner()
	Utils.delay .4, -> //This delay is just for prototyping purposes.
		changeBackground()
		showTimerPage()
		Utils.delay .2, ->
			showTimeEntries(toggl.te1)
			Utils.delay .08, ->
				showTimeEntries(toggl.te2)
				Utils.delay .08, ->
					showTimeEntries(toggl.te3)
					Utils.delay .08, ->
						showTimeEntries(toggl.te4)
						Utils.delay .08, ->
							showTimeEntries(toggl.te5)
							Utils.delay .1, ->
								showPlayIcon()

hideEye = () ->
	toggl.ic_password.animate
		opacity: 0
		options:
			time: LeaveTimingFaster
			curve: EaseIn

showSpinner = () ->
	spinner.animate
		opacity: 1
		options:
			time: EnterTiming
			curve: SharpCurve

changeBackground = () ->
	bg_grey.animate
		opacity: 1
		options:
			time: EnterTiming
			curve: SharpCurve

showTimerPage = () ->
	timerPage.animate
		opacity: 1
		options:
			time: EnterTiming
			curve: SharpCurve

showTimeEntries = (te) ->
	te.animate
		opacity: 1
		options:
			time: EnterTiming
			curve: EaseOut

showPlayIcon = () ->
	toggl.play.animate
		scale: 1
		options:
			time: EnterTiming
			curve: EaseOut



```

**Comment by willsb** [comment]
The problem I see here: When the user logs in for the first time, it's very unlikely that we can fetch time entries so quickly and then show suggestions (unless they have a lot of recent data).

If there are no suggestions, should we animate only the play button?

**Comment by pe0ny** [comment]
Can we show the loader in log in page until we load data?

And if there are no suggestions we should only animate the play button yes.

**Comment by amulware** [comment]
I would like to have the same animations for the main view any time the app is opened, not just on login, I think that will look much better than just the quick fade apple gives us.

**Comment by amulware** [comment]
Login/Signup views are very different now. There'll be new issues for this.
