### ISSUE TITLE
Filter ghost entities for almost all requests

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2900]
We don't want to show ghost entities in:

- workspace list
- client list
- tag list
- project list
- time entry completion
- actual suggestions
- ..?

There might be more.

It's easier to say that there is **exactly one place** where we want to show ghosts: In the time entry log.

I'm not sure if we should:

a) add this check to all queries in all places

or

b) make this the default, so that we can't mess it up accidentally.

Ok, maybe b) sounds better? Opinions welcome.

**Comment by simonrozsival** [comment]
b) is probably better (although there should be an explicit way of getting everything)
