### ISSUE TITLE
Consider ghost-ness in edit view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2902]
The edit view will still open and show all the details, however:

I think we should not allow users to edit tags in this state (since the popup would show none, see #2900). They could be able to edit everything else though.

Alternatively:

We could allow the user to ONLY:
- edit project
- delete

Maybe @pe0ny wants to comment.

**Comment by arturs105** [comment]
We should definitely indicate which properties can be edited in this state, but i think it makes more sense to do it in #2904.
