### ISSUE TITLE
Visually distinguish ghost time entries in log

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2903]
I'm not sure how to best do this.

We already want to disable the continue button: #2901

In addition, maybe we want to make sure it shows the red unsyncable icon? That should get the users attention.

I'd be happy to go with a ghost-icon as well, but I'm not sure if our users would find that all that humorous. :D

Ping @pe0ny

**Comment by simonrozsival** [comment]
We could have an opt-in setting "make this app more fun"  which would show you ghosts and spiders and stuff... :D

**Comment by pe0ny** [comment]
Check my comment in #2901 I believe that solves both issues.
