### ISSUE TITLE
Visually distinguish ghost time entries in edit view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2904]
Very related to #2902, but this one is more about showing a message like "You no longer have access to the workspace of this time entry. You can change it to a different workspace, or delete it. It will also sync correctly if you regain access to the workspace."

Maybe shorter, but that's sort of the information that might be important to give to the user.

I was first thinking we could use the existing sync error property, but that would mean actually touching all the ghost TEs in the database. That seems silly if we can just check the ghost state in the VM and set the error text for the UI based on it (and ignore any actual sync error text).

Thoughts welcome! Ping @pe0ny

**Comment by simonrozsival** [comment]
I think that for now we should add a warning message which would say something like:
```
This time entry belongs to a workspace that you don't have access to anymore and it can't by synced. Either delete it or move it to a different workspace by changing the project.
```
It would be good if we could come up with a shorter copy, because this will be too long on the mobile screen of SE or even 7/8, not to mention Android phones with possibly even smaller screens.

**Comment by arturs105** [comment]
I think indicating non-editable properties should be a part of this issue as well. Probably using light grey for the non-editable rows and/or text in the edit time entry view.

**Comment by simonrozsival** [comment]
Yes, let's try light grey for individual properties.
