### ISSUE TITLE
Consider splitting workspace pull from combined fetch

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2906]
The idea is to first fetch workspaces only.

Then we can handle removal/addition/no-workspace case, and only if everything is good (i.e. we have at least one non-ghost workspace in the DB) do we go to fetch all other data.

In most cases, this will slow down pull sync a tiny bit. In the cases where workspaces change it might speed things up.

This seems like a good idea to me, except that we are then optimising for the uncommon case. Maybe we shouldn't? Just leave it optimised for the common case where workspaces did not change?

**Comment by heytherewill** [comment]
🇨🇿
