### ISSUE TITLE
Detect new workspace

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2907]
A workspace is new if it was just fetched, and if we don't have a **non-ghost** workspace with the same ID locally.

If any such workspaces are detected:
- they should be persisted (either created, or overriding the existing ghost), so that we don't end up in a loop finding the same new workspace new over and over
- all since dates should be reset (set to null, or just clear the table)
- we go back to the top of the pull sync

This will redownload all data, even what we already have locally, but it'll make sure we don't miss out on anything.

The alternative would be downloading data only for the new workspace(s), but that's complicated since we have to implement new, paged endpoints. Much easier to let backend just give us everything in the user's scope again.

Depending on how #2906 is handled, this might not even introduce a loop, since there is no point in pulling the workspaces twice.

This might be a single or multiple sync states.

**Comment by simonrozsival** [comment]
All of this was already implemented in the NSync project and @sofokli1 is working on a sync test for this whole process in #3395. I'm closing this original issue now.
