### ISSUE TITLE
Animations: Running entry description

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#291]
- When running entry's description/task/project/client doesn't fit into the area shown below, animate it to show the whole description/task/project/client.

<img width="334" alt="screen shot 2017-07-19 at 10 53 56" src="https://user-images.githubusercontent.com/5064445/28356427-b15132c8-6c70-11e7-955e-a485b748426d.png">

![toggl-ios-running-entry](https://user-images.githubusercontent.com/5064445/28356526-0d5c4b48-6c71-11e7-85ec-db99b994f70a.gif)

```javascript
moveText = () ->
	toggl.text.animate
		x: newX
		options:
			time: toggl.text.width/60
			curve: Linear

Linear = "cubic-bezier(0, 0, 1, 1)"
```

**Comment by willsb** [comment]
`<marquee>`
