### ISSUE TITLE
Optimizations in calendar collection view layout

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#2914]
Two optimizations that we can do in the collection view layout:

- Cache the layout attributes in a dictionary by indexPath: this avoids recalculating the attributes for each element.
- Visible supplementary views: include only the visible supplementary views in the layout attributes, right now the current time view is always included.
- Invalidate the layout only when needed: I think we the collectionview's width changes is the only case we need.

**Comment by willsb** [comment]
The collection view is stable enough as is. We can work on this issue some other time, after the release

**Comment by heytherewill** [comment]
Should this be included in the new calendar project as a stretch goal?

ping @juanlaube @sofokli1

**Comment by juanlaube** [comment]
I think it would be nice, it's not a UI/UX improvement though.
