### ISSUE TITLE
Email entry field flashes when using 3D Touch cursor.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#292]
Gif from iPhone 6s with iOS 11 public beta 2

![img_3026 trim](https://user-images.githubusercontent.com/15633003/28360732-0a87922a-6c7f-11e7-867b-72bde2da8a36.gif)

**Comment by simonrozsival** [comment]
I think this is now "resolved" with the new login screen - I can't reproduce the issue there.

**Comment by willsb** [comment]
@amulware Let's raise team morale by closing crazy old stuff 😄

**Comment by amulware** [comment]
Team morale raised.
