### ISSUE TITLE
Allow long pressing for changing the offset of a time entry

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2930]
Design specs can be found at #2878

When you long press a time entry, you should be able to drag it to shift its start/end times. This was already working in the prototypes developed for #2758, so it shouldn't be too hard to integrate in the actual app.

Since there's a lot of coupling, both the foundation and the iOS parts should be handled by this issue. Thorough testing is still expected, though.

⚠️ This should only be applicable to created time entries in the calendar view, so it doesn't work for calendar events! ⚠️

**Comment by juanlaube** [comment]
I'd suggest waiting for #2968 to get merged first, a lot of code will happen in the long press helper I added.

**Comment by juanlaube** [comment]
Closed by #2993
