### ISSUE TITLE
Sync status bar hides the title of suggestions

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2936]
## 🐛 Bug Report
The sync status bar hides the title of the time entries log after some pull-to-refreshing and hiding the app in background, going to reports back and forth... it looks like this:

![screen shot 2018-08-13 at 7 36 22 pm](https://user-images.githubusercontent.com/374616/44051399-0a2c5736-9f3a-11e8-9f41-9532dfe41efe.png)

It does not look good. I think this could be due to #2913.

Build/Branch: 1.8.1
iPhone X with 11.4

## Expected behavior
There should be enough space between the status bar and the title.

## To reproduce
I am not sure if there are some easy steps to reproduce this. I will try to come up with a scenario tomorrow.

**Comment by heytherewill** [comment]
This will be part of a future of a task force
