### ISSUE TITLE
Track calendar events

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#2942]
We need to track the events to our analytics service in order to obtain insights on how the calendar is being used. 

### Absolute must haves:

- [x] Edit view opened from a calendar time entry
- [x] Time entry created from a calendar event
- [x] Time entry created from a time span
- [x] Time entry was offset using the long press and drag feature
- [x] Time entry changed duration using the slider that changes duration
- [x] User clicked the Get Started button to kickoff the onboarding

**Comment by amulware** [comment]
I'd like to track at least how many users clicked the get started button. We can remove it if we don't care in the future.

Also, we should track whenever users go to the screen in the first place, just so we have an idea of how many people look at it at all. (Maybe include a parameter of the screen shows the onboarding or the calendar then, so we can filter those if we care.)

**Comment by juanlaube** [comment]
Closed by #2988
