### ISSUE TITLE
Bottom bar is covering the last TE on the main log

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2954]
## 🐛 Bug Report
The last TE on the main log is being covered by the running time entry card because of the bottom nav bar.

## Context
This is a simple bug. It was introduced when the bottom bar was added to iOS.

Build/Branch:
Phone OS: iOS
Phone model: iPhone SE

## Expected behavior
The main log should scroll to show the last item when the running time entry card is visible.

## To reproduce
1. Have enough TEs to fill the whole screen.
2. Start a new TE.
3. Check that the last item is covered by the running te card and you can't scroll over it over the card (without holding your finger to keep the list scrolled past its bounds).

**Comment by khoi** [comment]
what happened to auto close ? Closed in #2972
