### ISSUE TITLE
Sync bar stays visible after sync

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#2955]
## 🐛 Bug Report
The sync bar indicator stays visible if you scroll during sync.

## Context
I noticed this after the 1.9 update from test flight.

Build/Branch: 1.9
Phone OS: iOS
Phone model: iPhone SE

## Expected behavior
The sync bar should vanish completely after the sync is finished.

## To reproduce
1. Have enough items to be able to scroll about 2 screens worth of TEs
2. Start a pull to refresh action
3. Start scrolling down while the sync is running
4. You will see that the bottom of the sync bar stays there.

It looks like this:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/2173493/44129458-7965e842-a016-11e8-9845-5a72efdfbacf.png">

**Comment by amulware** [comment]
What an odd thing. Moving it to 1.10 though, since it goes away easily and doesn't break anything.
