### ISSUE TITLE
Get rid of similar method names in ActivityIndicatorView

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#2960]
Currently `ActivityIndicator` has a method called `StartAnimation`, which starts the spinning animation, but it also has `StartAnimating` (inherited from `UIImageView`), which is used to animate several images (set in `AnimationImages` property).

I suggest the we override the inherited method (❗️ without calling base❗️), since we will never need to animate several images with the `ActivityIndicator`. The same thing goes for `StopAnimation` and `StopAnimating`

We could also override `AnimationImages` property, so that it throws an exception, since it does not make sense to set animation images if we never animate them.

**Comment by khoi** [comment]
I'm thinking of renaming `StartAnimation` with `StartSpinning` so that we don't touch the parent's methods, and also avoid naming confusion.

**Comment by khoi** [comment]
Closes in https://github.com/toggl/mobileapp/pull/2956
