### ISSUE TITLE
Only allow creation of projects and clients if workspace setting allows it

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#2961]
Workspaces have a setting whether project and client creation is allowed for all users, or just admins.

We should obey that setting, and check whether the workspace allows creation for all, and if not, if the user is an admin (or the other way around, whatever makes more sense in code).

Relevant documentation on permissions is under Business Logic / Global Logic / Access Levels.

We only want to show valid workspaces when creating a project/client.

If the user ONLY belongs to workspaces where they cannot create them, there are two options:
1. not show the 'create project ABC' in the start/edit views at all
2. when the user taps the same, we check and notice that there are no valid workspaces, so we show them a popup instead informing them of the same

I'm not sure which is more user-friendly, or generally better.

**Comment by pe0ny** [comment]
I would go with option no 1. Let's hide it.
