### ISSUE TITLE
Currently running time entry card and the start time entry FAB are hidden by the navbar in iOS 10

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#2983]
## 🐛 Bug Report
The tab navbar hides the important UI elements in iOS 10. Tested in simulator on iPhone SE: 

![screen shot 2018-08-17 at 2 02 48 pm](https://user-images.githubusercontent.com/374616/44265530-3b78d900-a227-11e8-874e-0f642e24e0db.png)

## Context

Build/Branch: 1.9 - `zoranel`
Phone OS: iOS 10
Phone model: iPhone SE (probably not device-dependent)

## Expected behavior
The card and the FAB should be positioned correctly even on iOS 10.

## To reproduce
Just start the app on a device/in simulator with iOS 10.

## Suggestions
Probably the constraints need to be set differently? Make sure that #2954 is not brought back.

**Comment by sofokli1** [comment]
should I make a quick pr removing translucency from the tab bar for ios 10?

**Comment by sofokli1** [comment]
Sorry if hijacked. GH does not refresh on time to check assignees

**Comment by simonrozsival** [comment]
No problem :)

**Comment by amulware** [comment]
Merged into release branch.
