### ISSUE TITLE
Changes on the edit view opening flow

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3016]
Right now, when a time entry is created:

-  from a calendar event:
  - we open the edit view
  - This is misleading because users might think they tapped the wrong item/
- from tapping and draggin:
  - we don't open the edit view
  - That makes the time entry effectively useless, since it's just a chunk of time

We need to:

- Not open the edit view when creating a time entry from an event. This will allow users to see the event being created.
- Open the edit view when creating a time entry from tapping and dragging. This will allow users to input whichever info is related to that chunk of time easily.

**Comment by juanlaube** [comment]
Closed by #3028
