### ISSUE TITLE
Discuss and Improve/Simplify ForkNavigation

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#3019]
There were some disagreement about wether #2950 should use simple extensions or the interface it currently uses.

Currently we have:
The `IForkingNavigationService` interface that is injected when forking navigation is needed, and we can still inject `IMvxNavigationService` to use the old implementation with the Tracking details.
The implementation of the now `TrackingNavigationService` is injected with the `PlatformInfo` so it can be used on other ViewModels by simply injecting `IForkingNavigationService`.

What had some disagreement:
Maybe we should just create an extension for the `ForkNavigate` feature, passing the PlatformInfo as a parameter, injecting the later in the ViewModels that need it. Further more, maybe PlatformInfo stuff could simply be in the `IPlatformConstants`.

We can discuss this later @simonrozsival and @willsb 

## Why?
Because we need to keep giskard and daneel working together o/

**Comment by heytherewill** [comment]
This interface was removed from the app due to the bottom bar refactor.
