### ISSUE TITLE
Deleting TE from the Edit View doesn't show the Undo bar

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#3029]
## 🐛 Bug Report
The undo bar only show when user swipe to delete a TE. But if the TE is deleted by going to Edit View, it doesn't appear

## Context

Build/Branch: latest `develop`

## Expected behavior
The undo bar should be shown regardless of the deletion method.

## To reproduce
- Tap on a TE in the log
- Hit Delete

**Comment by amulware** [comment]
This is by design. It was decided that the edit view does not need the UNDO since it has a confirmation dialog.

@pe0ny can comment more on this, if necessary.

**Comment by pe0ny** [comment]
This is correct. Edit view does not need indeed the Undo bar since we have a confirmation dialog there.

**Comment by khoi** [comment]
False ⏰, closing
