### ISSUE TITLE
Visual glitches in calendar items

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3032]
- When text views are recycled they retain the previous size instead of taking up all the space available:
![image](https://user-images.githubusercontent.com/7688727/44460313-f36d0400-a5e2-11e8-87a5-9a40a4275523.png)

- The two time entry icons (unsynced and unsyncable) are not respecting the zeplin proportions. They are either too big or too small. Apparently the UIIMageView that displays the icons is respecting the original size instead of being resized to match zeplin. This need to be fixed.

**Comment by arturs105** [comment]
@willsb Any steps to reproduce text views being recycled? Have many events and then scroll?

**Comment by willsb** [comment]
- Create a single TE and the end of the day
- Scroll to the top
- Create a bunch of overlapping TEs
- Scroll back to the bottom

**Comment by juanlaube** [comment]
Closed by #3067
