### ISSUE TITLE
Labels in calendar view need some tweaking

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3034]
- [x] Scrolling all the way up should comfortably show midnight. Right now midnight is capped and only visible when you overscroll
- [ ] We need to pad the times from midnight to 09:00 with a zero when in 24-hour mode
![image](https://user-images.githubusercontent.com/7688727/44460525-ca993e80-a5e3-11e8-92f9-60d9a02e452a.png)

- [x] We should not show more times after 23:00
- [ ] When in ~wrong~ 12-hour mode, we don't need to prepend a `:00` to every hour nor pad the hours from midnight to 9am with a zero
![image](https://user-images.githubusercontent.com/7688727/44460591-14822480-a5e4-11e8-9a69-d5588a1ea7a9.png)

For reference, you can see what the view should look like in #2874

**Comment by juanlaube** [comment]
Closed by #3058
