### ISSUE TITLE
Rating view leaves blank space after dismissal

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3036]
## 🐛 Bug Report
@dshr reported in #3023 that the rating view leaves behind an empty area when the user is done with it.

## Context
This happened specifically on the 1.9 release branch `zoranel`. We should check if it also happens in 1.8.2. It might well be a bug introduced with the main view rxfactor that's part of 1.9.

## Expected behavior
The rating view should not leave behind any empty space. The main view should look just like before.

## To reproduce
- hardcode the rating view to always show up
- make it show up
- step through the steps to make it disappear again
- observe empty space left behind

## Suggestions
As mentioned above, please check 1.8.2 to see if there is a difference in behaviour. That might not only help for debugging but might affect our decision for whether we can go ahead with A/B testing the rating view.

**Comment by dshr** [comment]
Already have a fix for this. Should the PR be to `zoranel`?

**Comment by amulware** [comment]
Yes please!

**Comment by amulware** [comment]
Merged into release branch.
