### ISSUE TITLE
Siri Shortcuts Overview

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3041]
This particular issue is for discussion. It can be closed once everything is clear, but it'll serve as a guide. More detailed explanations on what to do will come in the specific issues.

We are splitting the implementation of this in 3 phases (with an optional extra phase)

## Phase 1
Create intents and donate for user actions in the app (stop timer, start timer, start specific task, show reports...). All these should also be deleted on logout (can be deleted in one go). For most of them the app will start when used, but do nothing (for reports, it should go to reports, though), details of each specific intent will come with each issue.

## Phase 2
Create the extension that will handle these intents. It'll use Ultrawave if possible, otherwise we will have to write its own networking code. It will also get the necessary info (like a token to build the requests) from the app via shared private storage (app groups). 

We can also share the time of the last sync, or something like that, that will make the process less problematic regarding syncing, probably. The extension will allow Siri to handle the intents and respond without opening the app.

The workflow should be something like:
- The user opens the app, it saves in the shared storage the api token and the time of last sync (maybe more data too, like wether there's an entry running or not, we'll see)
- User asks siri to start an entry via a shortcut
- The extension checks the time of last sync. At this moment we can choose to return a failure if a lot of time has passed without syncing and redirect the user to the app.
- The extension uses the api token in the shared storage to build the request. If it's not there or the request returns a login error, we redirect the user to the app so he logs in.
- If everything goes as expected it returns a message with whatever we want to say. Otherwise it returns a failure, optionally recommending the user to open the app or whatever.
- It can also set a flag in the shared storage so the main app tries to sync when it's back on foreground (or maybe a timestamp)

The rest of intents will work in a similar way.

## Phase 3
Add buttons to the app so users can easily add these shortcuts to Siri (otherwise they have to do it through settings or Siri suggestions). Maybe show a snack bar after doing a specific action 4 times: "Do you want to do this using Siri?" and a button "Add to Siri", which will show the screen in which the user records the shortcut.

Alternatively we could have a section in settings (in app) to do this.

## Phase 4 (optional)
Add a UI Extension so Siri can also show some graph or whatever, that's what will show together with the response.

**Comment by mgguinne** [comment]
Awesome, with IOS 12 release today, thinking while on my way to morning tea to have a timer in toggl to start via Siri. Super excited it's already being worked on 👍

**Comment by amulware** [comment]
@mgguinne Give us just a few days. :)

**Comment by GandalfSaxe** [comment]
I can find actions to start a timer with a certain description, but not with a certain project.

Is this really how it's currently working? Can't specify project in a siri shortcut, only description?

**Comment by Odrakir** [comment]
@GandalfSaxe Thanks, that’s coming soon. Next update probably.

**Comment by GandalfSaxe** [comment]
@Odrakir Sounds good.

One thing that bugged me was that shortcuts with any description only show up / become available once they have been entered recently in Toggl manually. Instead it would be great to simply have a description field in the Siri Shortcut itself that set any arbitrary description, existing or new.

**Comment by GandalfSaxe** [comment]
Also being able to set any tag in a field would be great 👍 

Finally, and this is a little more advanced, and an idea for the future, I'd love to see Toggl exposing Siri Shortcut actions for when the total time for some project or tag og description have reached a certain total time for the day or week. That way you could set goals of tracking X amount of time in project Y or tag Z, and have some actions be automated when this goal is reached 👍

**Comment by Odrakir** [comment]
Hey @GandalfSaxe thanks a lot for your suggestions, some of them are already on the works, although I can't give you an estimate at this moment.

I don't really understand the thing about the goals or how does it relate to Siri Shortcuts. Having goals in the app itself is an idea that's always around, but there are no plans for it at this moment.
