### ISSUE TITLE
Create start entry intent

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3046]
When ever the user hits the start button we should create and donate an intent "Start time tracking" for an empty task.

It won't get or return anything, the response should be something like "Time tracking started" or similar.

**Comment by amulware** [comment]
This will start tracking in the background? Will there be a way to start an entry and also open the app's start/edit view? Or is that not really a use case for us here?

**Comment by Odrakir** [comment]
This issue specifically is just about donating the intent from the app. So when ever the user starts a TE, we will let Siri know he does that.

I'm answering your question in the issue about handling this event: #3085

**Comment by khoi** [comment]
Shouldn't we donate the information about the time entry which the users start?

**Comment by Odrakir** [comment]
I should have been more clear. This specific intent is for hitting the start button, which will start an empty entry, afterwards the user can edit the details.

Apparently a popular use of Toggl is this way, creating empty time entries fast and then adding the details later on.
