### ISSUE TITLE
Calendar: bug while using tap and drag to change duration

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3050]
Steps to reproduce:
1. Have an event from a user calendar in our calendar view
2. Tap the event to create a time entry
3. Tap and hold on the new time entry to change it's duration
4. Drag one of the small handles (top or bottom)
5. 💥 

Here's the problem:
![aug-23-2018 17-17-23](https://user-images.githubusercontent.com/15633003/44532122-007d1680-a6fb-11e8-9d99-5a2a77a1dcf0.gif)

**Comment by juanlaube** [comment]
This issue was fixed with invisible magic and not being able to reproduce it
