### ISSUE TITLE
Remove idle/running timer notifications on logout and reset api token

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3057]
Let's make sure we cover those two cases. The logout is pretty straightforward.

With regards to the reset:
- when we detect that the api token is no longer valid, remove the notifications
- do not however clear the settings here yet, unless the user actually logs out
- when the user logs back in on the api reset screen the correct notification should be shown again (if enabled)

**Comment by kornelijepetak** [comment]
Closed by #3182
