### ISSUE TITLE
Handle 410 and 418 status codes

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#306]
410 indicates that the app is using a deprecated version of the API. 418 indicates that the current client itself has been deprecated.

Both should only happen for people who do not use the app in a very long time, or if backend detects an acute problem with a specific app version and has to block it.

In either case, we should prevent the user from entering further data (since it cannot be synced) and prompt them to update to the newest version of the app.

Optionally, we could allow users to ignore the warning, and continue tracking locally, at the risk of data loss. *dramatic finger wagging*

**Comment by pe0ny** [comment]
Link to the design: https://zpl.io/VxYdoRa
User can't close the popup or do anything before he/she has updated the app.

**Comment by amulware** [comment]
Closing in favour of #751
