### ISSUE TITLE
Duplicate workspace names crash app on start

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3060]
## 💥 Crash Report
The app crashes on startup if the user has two workspaces with the same name. This happens because the ReportsViewModel expects names to be unique here:

https://github.com/toggl/mobileapp/blob/5dc6066acde49f16d853cc930829ae1f3d28390e/Toggl.Foundation.MvvmCross/ViewModels/ReportsViewModel.cs#L141-L144

### 👥 Impact
Potentially a bunch of users, since duplicate workspaces names can easily happen with the default name being based on the user's email address.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/f43a6cced0f4c877ede22bd81d946dfedb41cf2a?appVersion=1.9&period=last7Days

### 📝  Exception & Stack Trace
`System.ArgumentException: An item with the same key has already been added. Key: <REDACTED>`
```cs
ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException (System.Object key)
Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior)
Dictionary`2[TKey,TValue].Add (TKey key, TValue value)
ToDictionary`3+_[TSource,TKey,TElement].OnNext (TSource value)
ExceptionDispatchInfo.Throw ()
ExceptionServicesImpl.Rethrow (System.Exception exception)
ExceptionHelpers.ThrowIfNotNull (System.Exception exception)
AsyncSubject`1[T].GetResult ()
ReportsViewModel+<Initialize>d__73.MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter.GetResult ()
MainTabBarViewModel+<>c+<<Initialize>b__7_0>d.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
UIKitSynchronizationContext+<>c__DisplayClass1_0.<Post>b__0 ()
NSAsyncActionDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

## ❓Other questions

What this also makes me wonder:

1. Apparently, the reports are initialised on app start - why? Does it also fetch reports right away? It makes no sense to me to initialise them before first viewing.
2. Is the initialisation called more than once? If so, does that make sense? If not, how will it know about workspaces being added/removed?

**Comment by amulware** [comment]
Also, why are we using a dictionary from string to the workspace anyways? That seems rather odd to me.

**Comment by amulware** [comment]
The answer to my question is here: https://github.com/toggl/mobileapp/blob/5851f46d33ddb4a7c1d088ab5c216703e03c1d95/Toggl.Daneel/Services/DialogService.cs#L113

**Comment by amulware** [comment]
Well, that's awkward.

**Comment by amulware** [comment]
Not that awkward actually, there doesn't seem to be any reason the dialog service is taking a dictionary. It shouldn't. What it should take is an `IEnumerable<(string DisplayName, T Item)`.

**Comment by simonrozsival** [comment]
The PR was merged into a release branch, I suppose this issue should be closed then (and probably the project as well). Am I right, @amulware?

**Comment by amulware** [comment]
Yes, thank you.
