### ISSUE TITLE
Create first intent

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3069]
Let's start with a simple one, for example "Stop current entry" (name not final). It'll return a response with the description of the entry and the time it was running if it succeeds. And an appropriate error message if it fails.

The intent should be donated every time a time entry is stopped. My idea is this should be done in Foundation but through an iOS service, or a service with an empty (for now) android implementation, but I'm open to suggestions.

**Comment by khoi** [comment]
Closed in #3086
