### ISSUE TITLE
Reload reports if the user has not looked at them for X minutes

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3073]
Reload them when the user goes back to them only of course.

The reason is that now with the tabs, a report might stay open for days while the app is in the background, so the data gets out of date.

We could maybe also show a little text at the top 'this report was generated (on X(only if not the same day)) at Y' and have a refresh button?

**Comment by pe0ny** [comment]
I think that showing a 'this report was generated' is not a good idea if we don't ask this from BE with a timestamp. Otherwise, we'll display just the local generating time which might not be the same, right?

I would say, let's reload reports if the user hasn't looked at them for 5min.

**Comment by simonrozsival** [comment]
Backend always returns the time of the response in the headers. Maybe we should consider extending our `IResponse` interface to include this time. It might be useful even for some syncing scenarios. Then we would be able to display the "correct" time when it was generated and not the device's time.

**Comment by amulware** [comment]
I'm not sure I follow the importance of getting that timestamp exactly right. But if it is important, we have to make sure that whatever way we get it is actually meaningful. I.e. check this with backend.

**Comment by simonrozsival** [comment]
If we show something like "generated 5 minutes ago", "generated 2 days ago", "generated 15 hours ago", we don't need any synchronziation between local and server time (unless we mess timezone changes).

Automatically invalidating the cache after 5-10 minutes seems reasonable to me and then we don't have to display any time information, because it will always be "up-to-date" (unless the user is offline).

**Comment by amulware** [comment]
Those both sound like decent options to me.

**Comment by khoi** [comment]
besides having the auto reload, what do you guys think about adding the `pull to refresh` action to the report screen?

**Comment by simonrozsival** [comment]
I would like to have some kind of explicit refresh and the pull-to-refresh seems like a good idea to me. 

On the other hand I think we should redesign the pull-to-refresh thing first (even on the main screen). We already discussed it earlier with @amulware and @pe0ny if I am not mistaken - could we maybe add this to Q4 or Q1 plans?
