### ISSUE TITLE
DISCUSS: GitHub projects improvement options

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3093]
GitHub projects are cool and offer some neat automation features. However, they are also somewhat limited in what can be automated. Following are some options we have.

All of these suggestions involve some amount of manual work. Those bits are **highlighted in bold**.

### Add IN PROGRESS column

- need to **move issue to in progress column manually** when assigning an issue

benefit: more overview about what issues are being worked on, and what issues are not
downside: more work when starting an issue

### Add IN REVIEW column

- remove needs-review label from issues
- instead, have to **move issue to review column manually**
- does not account for issues that aren't in any project

benefit: stops mixing WIP and IN-REVIEW issues in the same column
downside: need to navigate to project to move an issue

## Automatable options

There are a lot more automation options with pull requests for _reasons_.

To make use of that, we would have to add all PRs to projects after creating them.

In both cases mentioned below, we could have columns like:
- WIP (PR gets moved here automatically when changes are requested)
- PENDING-REVIEW (PR gets moved here **manually** by pr owner when reviews were addressed)
- APPROVED (PR gets moved here automatically when the PR gets approved)

The default could be either of the first two columns.

benefits:
- potentially better overview of that state of all PRs

downsides:
- a little bit more manual effort
- automation might not play terribly well with multiple reviewers, especially if one requests changes and another approves (this needs testing)

### Track pull requests in all projects

- need to **add every PR to the relevant project**
- could then automate PRs into columns when they get approved, or when changes are requested

benefit: a very fine-grained overview for all projects
downside: doesn't help with seeing the status of all PRs in total

### Setup specific project for tracking PRs

- need to **add every PR to this project**
- automate as above, and use to get a better overview of which PRs need to be reviewed, and which need to be updated, etc.

benefit: a great overview of the state of all PRs
downside: doesn't help with seeing the status of PRs in a specific project

---

Opinions welcome below!

**Comment by kornelijepetak** [comment]
You should've used ✋ emoji for signifying manual work. Why U no use emoji? Your issue is so boring and it could've been the nicest issue ever?

**Comment by kornelijepetak** [comment]
#### IN PROGRESS

Downside also includes manual work when for some reason stopping the work on some issue, which is in my case easier to forget to do.

#### Automation

If we use WIP for PRs that are waiting for changes to be made as requested by reviewers, that would create another semantics than current WIP label which is being assigned by a developer (for one reason or the other) instead of by the state of the issue/PR itself. Somehow I am bothered by the difference if WIP name was to be used for both.

I see you have mentioned potential ambiguity with multiple reviewers. What does GH currently do in that case?

#### Specific project for tracking PRs

**Comment by amulware** [comment]
> If we use WIP for PRs that are waiting for changes to be made as requested by reviewers [...]

The names are not final of course, that can easily be changed so it's clear.

> potential ambiguity with multiple reviewers

I do not know what GitHub does in the various cases that can occur. We would have to test that with multiple people.

> Specific project for tracking PRs

The idea would be that all PRs live inside a special project which gives a better overview of what is going on than the PR tab above. Instead of just listing PRs and relying on tags and inside knowledge, the different columns might make it easier to see what PRs need to be reviewed, etc.

**Comment by simonrozsival** [comment]
I don't think moving an issue to a column when starting working on it should be considered "extra work" - it will take 5 seconds. The same with wip/pending review. The problem might be when we forget about it and it becomes a mess. We already sometimes forget to assigns ourselves to the issue or add the `pending-review` label.

If we could make a nice short cheat-sheet (something like the superflow diagram for git branches), it could help us do things properly all the time.

The automated features are nice, but I don't think they are really necessary. Moving cars between columns is easy, we just have to do it dutifully.

**Comment by khoi** [comment]
Why don't we get rids of the need for PR tracking, and make it a issue-centric system. All the labels like `ios` `android` `pending-review` `wip` will be applied to the issue instead. 

We can then organize issues into nice little Kanban boards with columns for visual management. 

IMO, mixing Issues and PRs make it more confusing.

**Comment by amulware** [comment]
@khoi You mean.. leave it like it is right now? :P 

@simonrozsival From what you say, it is not clear to mean whether you think those complications (i.e. adding more columns to the project boards) are a good idea or not.

**Comment by simonrozsival** [comment]
I like the idea with the columns as you described it. I think we can always adjust it once we try it for a few weeks and have some experience with it.

I just wanted to say that I wouldn't worry about the automation too much, if the rules are clear and well documented (some cheatsheet).

**Comment by amulware** [comment]
Ok, got it!

**Comment by khoi** [comment]
I mean do not add PRs to the project board 😂

**Comment by juanlaube** [comment]
I like the idea of the new columns, in particular adding the PRs to the projects and using whatever can be automated. This helps me to visualize the status of a particular project and decide if I should work on new issues or review things. The extra manual work is minimum, I don't think this is a problem.

**Comment by daividssilverio** [comment]
Kinda late, but I like the idea of the PRs on the project board as well.
My only concern is that we might forget to move the cards sometimes, but I do forget to add labels too sometimes, so no big deal.

Let's see if it works well o/

**Comment by amulware** [comment]
🏛
