### ISSUE TITLE
Increase the size of the drag indicator

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3096]
When we tap and hold a time entry in the calendar view, it enters in edit mode. However, the circles that indicate this are so tiny that they can easily be overlooked. We need to make them bigger

**Comment by pe0ny** [comment]
Let's try 8pt circle instead of 6pt one:

![calendar dragging indicator 1x](https://user-images.githubusercontent.com/5064445/44703265-a6d06f80-aa9f-11e8-83f3-1abd561b3d3d.png)

Zeplin: https://zpl.io/VxlB9WJ

**Comment by willsb** [comment]
Closed by #3096
