### ISSUE TITLE
Add UI Extension to have some kind of response

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3122]
While they fix not having custom Siri responses (more info here: https://github.com/xamarin/xamarin-macios/issues/4581) we are going to use a UI Extension to show some kind of info on success (I'm afraid we can't do anything about the error cases)

So we need the following designs:
- [x] UI for "stop current entry" intent. I'd say it should show the description of the entry and how long it has been running.
- [x] UI for "start entry" intent. This is for empty entries with no description.
- [ ] UI for "start specific entry" intent. This is for existing entries, we know the description.

**Comment by pe0ny** [comment]
I have two proposals for start entry intent:

With duration:
![toggl - start entry intent v1](https://user-images.githubusercontent.com/5064445/45017549-8456cd00-b030-11e8-88ee-d54aba9b0468.png)

Without duration (if we don't have that info):
![toggl - start entry intent v2](https://user-images.githubusercontent.com/5064445/45017550-8456cd00-b030-11e8-911e-cc5251d9ee67.png)

In both cases I added a version how it looks with and without description. In addition, added a project (if we can show this).

Zeplin: https://zpl.io/bWLnrme & https://zpl.io/VDndvdl

Stop entry intent:

![toggl - stop entry intent](https://user-images.githubusercontent.com/5064445/45017631-bff19700-b030-11e8-8116-36d538064da1.png)

Again, if we could display project/task/client, it should be displayed the same way in stop entry intent as well.

Zeplin: https://zpl.io/VQEnLdx

Note: Copy above the card is just illustrative and not final!
