### ISSUE TITLE
Add the notifications settings ViewModel

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3127]
⚠️ This is a foundation issue, so please add only the view model changes here. It depends on #3115.

This will have [its own section in the settings view](https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/596cb7d64fd7d09b688fd529). This section will only appear when the calendar onboarding is done (similar to the calendar settings).

Once you open the smart notifications view, there will be two possibilities:

- [If we don't have notification permissions](https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5b855349b655371d516bbd9f)
  - We show an empty state screen
  - It will have a button that opens the native iOS settings, allowing the user to change the notifications settings

- [If we have notification permissions](https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5b855349fce7f90a66990d87)
  - We will show a list of all smart notifications we have
  - Currently we only have one type (the calendar one)
  - The calendar notifications will show the currently selected amount of time the user wants to be notified (or disabled if notifications are disabled)
  - Tapping the settings should open another view that allows the user to select among the multiple available times<sup>1</sup>

<sup>1</sup> These are the options. This is still not on zeplin. On top of what's in the image, the `Disabled` options should also appear.
![image](https://user-images.githubusercontent.com/7688727/44910058-20fb3100-acf8-11e8-939d-5c2224935fe0.png)

**Comment by juanlaube** [comment]
Closed by #3136
