### ISSUE TITLE
ArgumentOutOfRangeException in TimeEntriesLogViewSource

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3137]
## 💥 Crash Report
Something goes wrong when updating the main table view. When `EndUpdates` is called, the state of the view source and the view are not compatible and it goes 💥.

### 👥 Impact
- 113 times for 70 users
- 35% of crashes in 1.9
- all sorts of devices and iOS versions

### 🔗 Context
Some more fallout from the rxfactor?

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/31b1a1881ca095645fd2fd9fe059ce0c33871599?appVersion=1.9

### 📝  Exception & Stack Trace
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
```cs
TimeEntriesLogViewSource.GetViewForHeader (UIKit.UITableView tableView, System.nint section)
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSendSuper(intptr,intptr)
UITableView.EndUpdates ()
ReactiveTableViewBinder`2[TModel,TCell].handleCollectionChanges (System.Collections.Generic.IReadOnlyCollection`1[T] changes)
AnonymousSafeObserver`1[T].OnNext (T value)
ObserveOn`1+Context+_[TSource].OnNextPosted (System.Object value)
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by simonrozsival** [comment]
I just observed this bug in the simulator just after start. There were two sections and it tried to access header of section with index 2. I still have no idea what is going on and how to replicate it. The app did not crash when I started it again. That makes me thing that the problem happens during the initial sync.

**Comment by simonrozsival** [comment]
I was not able to reproduce this crash even after several hours of testing. We need to collect more information about this crash.

**Comment by juanlaube** [comment]
Ha! I was able to reproduce this! 😄 
The problem happens when the number of sections changes, for example, when all time entries in a day are deleted, in particular happens, with the last section of the table view.
To reproduce you need to delete all time entries for the last section from the web or another device and sync.

**Comment by juanlaube** [comment]
Looking for a solution now... 👀
