### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#314]
I ran dotCover, and here are some things that we could improve:

Not tested:
- Either.Match (both overloads)
- Test.Adapter - no test for working case?
- HttpExtensions.AddRange
- ApiConfiguration

Also, models and exceptions are not tested anywhere, but this might be alright.

**Comment by amulware** [comment]
Update: this list needs an update first.

**Comment by heytherewill** [comment]
🔥
