### ISSUE TITLE
Settings not getting saved in Daneel 1.9

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#3147]
## 🐛 Bug Report
Daneel 1.9 has two settings that can be toggled as on or off:
- 24hour setting
- manual mode setting

Unfortunately, the setting does not hold. Firstly, one has to tap the toggle button twice to change the setting and when it changes and user returns to the timer screen, the setting does not get saved. 

## Context

Build/Branch: Daneel 1.9 (1677)
Phone OS: iOS 11.4.1
Phone model: iPhone 7

## Expected behavior

Toggling the 24h or manual mode setting gets saved when returning to timer screen. 

## To reproduce
Open the settings of the app, try to change the 24h or manual mode setting, return to timer screen, go back to settings screen - old settings are still applied.

**Comment by simonrozsival** [comment]
The problem is when you tap exactly on the switch (and you can feel the haptic feedback). The app then animates the change of switch, but the change itself is not registered by our code and so it seems that the setting was not preserved when the screen is closed. The fix should not be hard.
