### ISSUE TITLE
Time entry creation view: Autocomplete

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#315]
- When user is typing without using @ or #, we suggest time entries
- When user hits # we suggest tags aka 'tags suggestion mode':
![toggl - ios - tags 1x](https://user-images.githubusercontent.com/5064445/28671765-7efe0d9c-72e6-11e7-99a8-edc5d1a6fd4b.png)
- When user hits # and then backspace, tags suggestion mode will be closed.
- To get out of tag suggestion mode, user needs to 
a) Pick a tag
b) Hit backspace enough times to remove # 
c) Tap tags button (the green one)
- When user hits @ we suggest projects (with clients and tasks) aka 'projects suggestion mode':
![toggl - ios - add new entry project search and autocomplete 1x](https://user-images.githubusercontent.com/5064445/28671174-65d56c9a-72e4-11e7-9517-2259bb9c590a.png)
- [x] When user hits @ and then backspace, projects suggestion mode will be closed.
- [x] When user hits @, starts typing and hits space, we still suggest projects. This allows entering project names with spaces.
- To get out of project suggestion mode, user needs to:
  - [x] Pick a project (including 'No project')
  - [x] Hit backspace enough times to remove @ 
  - [x] Press the project button (green folder button right above keyboard)
- [x] Show 'No project' option always when project suggestion mode is open
- [x] When user has typed in description AND picked a project AND starts typing in normal mode (not in projects suggestion mode), we do not suggest time entries anymore. *(For future reference, we can consider suggesting time entries with picked project)*
- [x] When user is in project suggestion mode and taps 'No project', it closes the project suggestion mode and adds 'no project' tag in the input field.
- [x] When user is in project suggestion mode and has typed in *something*, eg '@abc-project' and taps 'No project', it closes the project suggestion mode and replaces whatever user had typed in with 'no project' tag.
- [x] When user is in project suggestion mode and taps green project-icon below, project suggestion mode closes.
- [x] When user is in project suggestion mode and has typed in *something*, eg '@abc-project' and taps green project-icon below, project suggestion mode closes (we don't store the string user had typed in before).
- [x] When user hits second @ after already picked one project, projects suggestion mode won't open again, instead user can keep typing in normal/description mode using @ in description

- [x] When user types in description, hits @ (enters projects suggestion mode) and then moves cursor into description (text typed in before), then user is still in projects suggestion mode until he/she starts typing
- [x] When user types in description, hits @ (enters projects suggestion mode), types in *something*, eg '@abc-project' and then moves cursor into description (text typed in before), then user is still in projects suggestion mode until he/she starts typing
- [x] When user moves the cursor back to the @, he/she can continue projects search ☝️ Applies to both two above mentioned cases.

- [x] When user is typing a description, moves cursor somewhere in the middle of the description text and hits @, then nothing happens 🙀 User can keep typing description.

- [x] When entering spaces while searching for projects, each space separated word should be searched for separately, in project, task and client names, and only projects/tasks that include all the words in some way should be shown. Same applies when entering spaces while searching for time entries - each space separated word should be searched separately.

- [x] Start suggesting time entries when user has typed in at least 2 characters.

- [ ] Allow users to mix description with tags and projects. Meaning tags and projects should be where the user types them, not at the end. For example:
`description part1 @projectabc description part2 #tag1 description`

- [ ] Tapping a token opens projects or tags suggestion mode.

**Comment by amulware** [comment]
Please do a test and check the list above what is working and how well right now, and if there are any other issues (e.g. #946).

**Comment by amulware** [comment]
Other things that could be improved that are not listed here are of course also welcome.

**Comment by simonrozsival** [comment]
I went through the list and updated it (I used current develop branch).

**Comment by amulware** [comment]
I'm not sure if all the points above are still what we want them to be. Maybe @pe0ny can check again if all points are still desired behaviour.

Specifically, I think we should allow entering projects and tags at any point in the description, and not only at the end (always considering the search string from the preceding @/# character to the cursor).

**Comment by pe0ny** [comment]
@amulware You mean that we should allow users to mix description with tags and projects? For example?
`description part1 @projectabc description part2 #tag1 description`


Otherwise, I went through all the points above and I believe these still apply. I noticed only this one:


> Show 'No project' option always when project suggestion mode is open

Atm, we don't display 'No project' option when we show 'Create a new project' and I think this makes a lot of sense. So all good.

**Comment by simonrozsival** [comment]
@pe0ny I already fixed the thing with 'No Project' - but it is not in the 1.0 release, and will be in the later ones. Should I revert it?

**Comment by amulware** [comment]
@pe0ny Yes, I think tags and projects should be where the user types them, not at the end

**Comment by pe0ny** [comment]
@amulware I agree, it would be so much nicer. 👍 I'll add it to the list.

@simonrozsival If it's possible yes, please. Sorry I didn't answer before.

**Comment by simonrozsival** [comment]
> When user is typing a description, moves cursor somewhere in the middle of the description text and hits @, then nothing happens 🙀 User can keep typing description.

I don't think I understand this one - does it mean that if user types "Some text of the description", then moves the cursor say before the word "text" and types "@", so the description is now "Some @text of the description", then we shouldn't start suggesting projects? Please elaborate more on this point.

**Comment by pe0ny** [comment]
I would add another one to the list:
Tapping a token opens projects or tags suggestion mode.

**Comment by simonrozsival** [comment]
@pe0ny How does that work? If you tap on e.g. a project token [some project name], should it be removed and replaced with `@some project name` with the cursor placed right after this text? Or should it just add the query symbol at the end of the text and just open the suggestion mode?

**Comment by pe0ny** [comment]
It shouldn't do either of these. When a user has added a project or tag(s) to a time entry and taps one of them, eg a project token, it opens project suggestion mode (like when you tap project icon when the project is already selected). We do not remove or replace that project or do not add @ symbol at the end of the text. Though when a user selects a new project from the list, then we'll replace it (like we do right now).

However, the question remains when a user taps a tag token, not project one. It would be nice to allow quickly removing a tag(s).

**Comment by simonrozsival** [comment]
OK. I have also a question regarding the point
> When user has typed in description AND picked a project AND starts typing in normal mode (not in projects suggestion mode), we do not suggest time entries anymore. (For future reference, we can consider suggesting time entries with picked project)

Do you prefer me implementing this in a way in which we don't suggest anything or suggesting TEs with the selected project?

**Comment by pe0ny** [comment]
I wouldn't suggest anything at this point.

**Comment by simonrozsival** [comment]
OK. Follow-up question:
>When user has typed in description 

Does this mean, that when the description is empty and the user has selected a project, then we should show all the time entries suggestions but as soon as the user starts typing, we should hide everything?

**Comment by pe0ny** [comment]
> Does this mean, that when the description is empty and the user has selected a project, then we should show all the time entries suggestions

Yes, that's what we do already and we should keep it that way.


> but as soon as the user starts typing, we should hide everything?

No, we do not hide anything atm and we shouldn't hide anything. What I meant is when the description is not empty (user already typed in something) and added a project, and continues typing in the description, then we shouldn't suggest all the time entries that are allocated under the selected project. But we should suggest time entries that match with typed in TE string and project (if any). Does it make sense?

**Comment by simonrozsival** [comment]
Yeah, that makes sense. Thanks for the clarification! :)

**Comment by amulware** [comment]
Closing since we're getting a full rewrite of this. We can look at that once it's done and see if we want things changed.
