### ISSUE TITLE
Time entry is created repeatedly when it changes during sync

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3162]
## 🐛 Bug Report
There is a weird bug which causes our app to create duplicite TEs. The main reason is that if the network is slow and the POST request takes too long (several seconds), the user can easily change the time entry - e.g., stop it. When the change is detected by the `CreateEntityState` it changes the ID to the one given by the server and returns the `EntityChanged` result. This result is then looped back to the `CreateEntityState`. This time we push the entity again, even though it already has a positive ID and there is no reason to push it 🤦‍♂️

## Expected behavior
What should happen instead is that the `EntityChanged` result of the `CreateEntityState` should be connected to the `UpdateEntityState`.

## To reproduce
- Use Network Link Conditioner to simulate Edge connectivity
- start a time entry and stop it immediately before it syncs
- wait for the app to sync
- force-sync the app again
- you will now see an extra running TE appearing from nowhere

## Suggestions
The solution is already described in this bug report.

**Comment by amulware** [comment]
<img width="585" alt="screen shot 2018-09-05 at 11 54 42" src="https://user-images.githubusercontent.com/3987892/45088951-81c4a800-b102-11e8-9300-183c44eeac2b.png">

Yap, this is a clear bug. Good find.

**Comment by amulware** [comment]
This issue might exist because of:

<img width="461" alt="screen shot 2018-09-05 at 12 06 40" src="https://user-images.githubusercontent.com/3987892/45089479-38755800-b104-11e8-95f2-1024fd5e3b3a.png">

Which I think we should also fix change, even if it might be correct. No actually, it's not correct, since the entry might have been deleted.
