### ISSUE TITLE
Undo snackbar does not go away after the timeout sometimes and tapping the button leads to a crash

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3177]
## 💥 Crash Report

Sometimes (I can't reproduce this reliably yet) the snackbar which is shown when a TE is deleted with the swipe gesture does not go away after the timeout (5s) and the user can still tap on the `UNDO` button which leads to a crash if the app syncs and hard-deletes the TE from the database.

### 👥 Impact

I can't find any occurance of this bug in the AppCenter. Maybe it happens only in the simulator? Maybe people don't delete time entries that much and the bug hasn't surfaced yet?

### 📝  Exception & Stack Trace
`Toggl.PrimeRadiant.Exceptions.DatabaseOperationException` - `Database operation failed [T]: Sequence contains no matching element`

The exception is obvious. The database does not contain the TE with the ID stored in the view model, so an update which un-deletes the TE fails.

**Comment by heytherewill** [comment]
Is this still the case?

**Comment by simonrozsival** [comment]
I haven't noticed this problem in a long while. We must have fixed it but either there was a duplicate issue or we simply didn't notice this one and fixed it anyway or by accident.. 😄
