### ISSUE TITLE
Make sure calendar event drag handle is always on top of all the other views.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3179]
Take a look at the small round circle in the image. It should be on top of the other calendar entry.
![screen shot 2018-09-06 at 14 21 29](https://user-images.githubusercontent.com/15633003/45154561-9b3c2180-b1e0-11e8-919a-c6e2bd89b98a.png)

**Comment by juanlaube** [comment]
Closed by #3186
