### ISSUE TITLE
NullReferenceException in EditTimeEntryViewModel.isDirty

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3199]
## 💥 Crash Report
Something is null when `isDirty` is called from `closeWithConfirmation`.

https://github.com/toggl/mobileapp/blob/133c046cb7398e65ad5fdfcf356bb942a7fe02fb/Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs#L56-L66

### 👥 Impact
- 165 occurrences to 138 users, 19% of crashes in 1.9
- all sorts of devices and iOS versions

### 🔗 Context
**I think this bug was introduced with 1.9.** It seems to not happen for earlier versions. Maybe that helps in finding the issue.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/5e9ebaf763d160e0722cdc73c43298606b31a513?period=last7Days

### 📝  Exception & Stack Trace
`System.NullReferenceException: Object reference not set to an instance of an object`
```cs
EditTimeEntryViewModel.get_isDirty ()
EditTimeEntryViewModel+<closeWithConfirmation>d__160.MoveNext ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
MvxAsyncCommandBase+<Execute>d__14.MoveNext ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by simonrozsival** [comment]
The `EditTimeEntryViewModel` was edited twice since the `1.8.2` release:
1. 🚧 Refactor schmrfactor (#2826) 
2. 🐞 confirm changes inconsistency (#3013)

Both are quite trivial changes which should not change the way the `isDirty` is evaluated.

I have an idea: maybe the `originalTimeEntry` is garbage collected when the app is in background and when it is brought back to foreground, the `isDirty` throws? I will try to replicate this bug. Or maybe it is some side effect of the navbar? I have not been able to reproduce it so far.

**Comment by amulware** [comment]
The relevant change could of course be something else that causes the `null` to happen. /shrug

**Comment by simonrozsival** [comment]
It is not obvious, what exactly is `null`. I tend to thing that it is the `originalTimeEntry`. If `originalTimeEntry.TagIds` were `null`, the initialization would throw.

**Comment by simonrozsival** [comment]
I am unassigning myself from this issue for now as I am not able to reproduce it and therefore I can't fix it at this moment.

**Comment by dshr** [comment]
Also affects Android: https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/250e4d39dc1bd7518eb93c911db65cd31fc09f58?appVersion=1.3.2&period=last90Days
