### ISSUE TITLE
Calendar events don't disappear when deselecting a user calendar.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3208]
## Expected behavior
The events from deselected calendars should be removed from calendar view.

## To reproduce
1. Have several user calendars with events on the current date.
2. Have those calendars selected in our app.
3. Open calendar view (the events from selected calendars are now visible in the calendar view)
4. Press the settings icon while in the calendar view
5. Deselect a few of the calendars (or all of them).
6. 💥 
7. Events from the deselected calendars are still visible in the calendar view.

**Comment by juanlaube** [comment]
The issue was solved already on `calendar-integration`
