### ISSUE TITLE
Add StyleCop to all projects

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#321]
I've been experimenting with it, it seems to work very well, and we can configure it to cause build errors when set rules are broken. We only have to see if it works on Mac as well.

Here is a PR that shows how easily this can be done: https://github.com/beardgame/utilities/pull/109

Ref #38

**Comment by willsb** [comment]
I've seen it working on macOS via the Nuget package + assembly attributes. Dunno how to make it work the Windows way. But I'm all up for it (in fact I had a PR implementing it the macOS way and you said you didn't like it :P)

**Comment by amulware** [comment]
I don't remember that. Link?
