### ISSUE TITLE
Update old Android deprecation

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3219]
The overlay implemented in https://github.com/toggl/mobile/pull/1998 currently specifies July as deprecation date. We gotta update that once we know for sure which date it'll be. Only then can we create the final build of the old app.

**Comment by pe0ny** [comment]
The new date is Nov 1st.

So the copy should be the following: "Support for the current app ends on Nov 1st 2018"

**Comment by kornelijepetak** [comment]
This has been done with toggl/mobile#1998
