### ISSUE TITLE
Animations: Card - stopping a running entry

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#322]
**Stopping a running time entry**
Stop button scales down and entry moves away with the card.

![card-running-stop](https://user-images.githubusercontent.com/5064445/28776927-967e6d36-7601-11e7-95bd-46a4ce0f51ee.gif)

```javascript
toggl.stop.onTap ->
	hideIcon(toggl.stop)
	hideEntry()
	hideCard()

hideIcon = (icon) ->
	icon.animate
		scale: 0
		options:
			time: LeaveTimingFaster
			curve: EaseIn

hideEntry = () ->
	toggl.entry.animate
		opacity: 0
		y: 568
		options:
			time: LeaveTiming
			curve: EaseIn

hideCard = () ->
	toggl.card.animate
		y: 568
		options:
			time: LeaveTiming
			curve: cardOutCurve
```

**Comment by willsb** [comment]
I'd like this to be on hold until I return from vacation, for I have a WIP branch [here](https://github.com/toggl/mobileapp/tree/stop-te-animation-wip). If it can't wait, please try and base your solution on what I have written.
