### ISSUE TITLE
Calendar view can be briefly seen before the onboarding screen

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3229]
## Steps to reproduce
1. Have a fresh install, where calendar onboarding hasn't been completed
2. Open the app
3. Go to the calendar tab
4. For a split second you can see some other view (i assume the actual calendar view) before the onboarding view fades in.

## Why this is happening
This is due to visibility set in the .xib and animating these properties.

In the .xib:
* onboarding is invisible
* calendar view is visible

After user goes to the calendar tab, we fade in the onboarding view and we can see the other view while the animation hasn't completed yet.

## Possible solution
Set the correct visibilities in `ViewDidLoad` without the animations.

## Things to consider
We have to make sure that we don't end up with the inverse problem - onboarding view slightly seen before calendar view appears.

**Comment by willsb** [comment]
Closed by #3238
