### ISSUE TITLE
1.4 Crashes when creating a tag right after creating a project

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3239]
App crashes when creating a tag immediately after creating a project

## 🐛 Bug Report
The app crashes and needs to be restarted after trying to create a tag

## Context
My internet connection might not be the most stable or speedy. 6down 0.7up

Build/Branch:1.4 (internal build)
Phone OS: 8.0.0
Phone model: HTC U Ultra

## Expected behavior
To have a tag created and assigned to the entry

## To reproduce
Start a new time entry, create a project with an existing client quickly then create a new tag and the app crashes when pressing the tag creation button

**Comment by daividssilverio** [comment]
@ApocalypticFish , I'm not able to replicate that.
Can you replicate that consistently? How fast do you have to create the tag to make it 💥 ?

**Comment by daividssilverio** [comment]
Since we can't replicate the issue anymore. I'm closing this issue.
