### ISSUE TITLE
Invalid workspace still displayed on settings page

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3241]
## 🐛 Bug Report
The user had 2 workspaces, they were deactivated from one of them and now cannot create entries in this workspace or view it. This workspace is still displayed on the settings page

## Context
The user did have a time entry running in this workspace at the time, not sure if this would have any effect

Build/Branch:1.4
Phone OS:8.0.0
Phone model:HTC U Ultra

## Expected behavior
The workspace should not be displayed on the settings page as the user no longer has access to this

## To reproduce
Have a user with 2 workspaces, have another user in one of those workspaces deactivate the user on that workspace, check the mobile app and the user will still have access

**Comment by amulware** [comment]
Known and not a new issue. The app does not detect losing access to any sort of entity at the moment.

This particular case will be handled in https://github.com/toggl/mobileapp/projects/11
