### ISSUE TITLE
Icon constraint issues in calendar item views.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3243]
## Steps to reproduce
1. Turn off internet connection -> time entries won't sync -> entries in calendar will have an icon. Alternatively you can use other method to force an icon to appear in the calendar item views.
1. Create a short time entry in the calendar by tapping and holding
2. Immediately release your finger **without dragging a bit**.
3. Press "Confirm changes" in the edit view.
4. Tap and hold on the newly created entry
5. Drag the bottom handle downwards.
6. 💥 The icon is now in the wrong place (see image).
![img_7a925649d6a5-1](https://user-images.githubusercontent.com/15633003/45486041-655be780-b762-11e8-9643-48f27fd6f7a4.jpeg)

**Comment by juanlaube** [comment]
Closed by #3272
