### ISSUE TITLE
Add Siri UI for Intents' ready state.

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#3246]
We have the Siri UI Intents implemented in #3122. However currently, it's missing an intermediate state where the intent ready and waiting for user interaction. 

This state is not visible when user interact with Siri through voice 🔈, but only when interacting with the shortcut manually ( see GIF ). Having this state allow the users to:

![kapture 2018-09-13 at 19 48 27](https://user-images.githubusercontent.com/6994441/45489299-204daa80-b78e-11e8-926d-0731caee1eb9.gif)

- Click on it and continue the activity inside the app
- To be reminded of what the "Do" button's action

**Comment by khoi** [comment]
@pe0ny maybe a simple confirmation could work here?

**Comment by pe0ny** [comment]
@khoi Yes, let's go with the copy you proposed. 👍

Can we also change the "Do" text? It seems a bit confusing to me. I would replace it with "Stop the timer" for example.

**Comment by Odrakir** [comment]
I think we don't have the flexibility to add whatever text we want in the button. We maybe, can find one of the predefined ones that fits better with our action.
