### ISSUE TITLE
Invalid date headers since Daneel 1.9

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#3262]
Several users have reported issues with invalid date headers since Daneel 1.9 was out. One user has confirmed the issue is present also with 1.10, hence creating the issue. 

Reporting issue based on recent example, will add other examples as they come in. 

## 🐛 Bug Report
User's timezone is set to America/Los_Angeles, their device's timezone matches. Some of their recent time entries that were recorded on September 16th as per time in LA are displayed as September 17th. 

## Context
Build/Branch: Daneel 1.9
Phone OS: iOS 11.4.1
Phone model: iPhone 7

conversations/18519489605
User ID 3570297

## Expected behavior
If user's devices timezone and profile timezone match and the user has recorded time entries on day A, time entries should be displayed in their app as being recorded on day A. 

## To reproduce
Have not been able to reproduce yet, but reporting regardless as the number of issues is high.

**Comment by maritoggl** [comment]
conversations/18516201337, America/Los_Angeles tz, v1.10

**Comment by amulware** [comment]
Definitely related to the RX factor, something must have gone wrong with the headers.

**Comment by vedr4n** [comment]
Got another user on 1.10 reporting the problem. 

conversations/18549225499, Phone model: iPhone 6, Platform and OS version: iOS 11.4.1

**Comment by nicktoggl** [comment]
conversations/18464595053 v1.9, iPhone 6, iOS:11.3.1

conversations/18375711891 v1.10, iPhone 6s, iOS:11.4.1

**Comment by simonrozsival** [comment]
I thought I fixed this with in #3287 but after reading not only the title, but also the description, this still needs a different fix.

Isn't @khoi already working on a fix for this problem in #3195?

**Comment by simonrozsival** [comment]
I generated random data and got this in my log: <img width="511" alt="screen shot 2018-09-20 at 12 35 08 pm" src="https://user-images.githubusercontent.com/374616/45818138-20dfc700-bce1-11e8-8b9b-3fb129a16127.png">

The first `Yesterday` is selected based on the start time `{9/19/2018 10:27:02 PM +00:00}`, the second `Yesterday` then from `{9/19/2018 9:44:02 PM +00:00}`. Couldn't there be a problem in the way we group the TEs?

**Comment by maritoggl** [comment]
User reported that he's in UTC -4 time zone. During some parts of the day, everything is displayed properly. At 8 PM local time (meaning UTC midnight), days get messed up.

**Comment by amulware** [comment]
We're definitely not using local time everywhere we should here.

**Comment by maritoggl** [comment]
The same user that made the previous comment also reported that in reports, Today/Yesterday buttons select the date a day ahead of what they should. Probably related.

**Comment by simonrozsival** [comment]
@maritoggl please create a separate issue! :)

**Comment by vedr4n** [comment]
@simonrozsival Once this issue is closed/fixed, will it also fix headers from a few weeks ago? 

I got a report from a user who says that everything is okay with new headers (today, yesterday, etc), but those from a few weeks ago are still broken. 
Example: https://downloads.intercomcdn.com/i/o/79292305/34cbcccada6c3bd861ae9fd4/image3.png

**Comment by simonrozsival** [comment]
Yes, it should. We might release in 1.5.1 next week :thinking: @juanlaube @willsb

**Comment by epagnini** [comment]
bumping to see if there is a tentative release date :)

**Comment by khoi** [comment]
@epagnini This's been released in `1.12.1`.
