### ISSUE TITLE
App crashes when deleting emojis in the description text field

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3265]
## 🐛 Bug Report
App crashes when deleting an emoji in the description text field.

## Context

Build/Branch: Daneel 1.10
Phone OS: iOS
Phone model: any?

## Expected behavior
App shouldn't crash.

## To reproduce
1️⃣ Start a new time entry with an emoji in the description, like `🔍 Code reviews` or similar.
2️⃣ Try to delete the emoji.
💥 App crashes.

## Suggestions
Good luck, live long and prosper 🖖

**Comment by simonrozsival** [comment]
This is the same bug as #2922
