### ISSUE TITLE
The start view does not allow to create projects and tags with text and emoji directly

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3268]
## 🐛 Bug Report
Follow-up of #3265 

The problem is that text and emoji sequences are split into separate `TextSpan`s. The "Create project XYZ" uses only the first `TextSpan` as XYZ, so it will either be just emoji, or text.

This might be possibly a problem with Japanes, Chinese and other non-latin character sets, but I haven't tested that.

## Context
Build/Branch: `develop`
Phone OS: `iOS`

## Expected behavior
The whole sequence of normal chars and emoji should be used as the text of the project/tag name.

## To reproduce
Type in `abc #abc 👻 def` into the text field in the star time entry view. It should show you `Create tag "abc 👻 def"`, but it does not show tag suggestions at all.

## Suggestions
"Simply" collapse all consecutive `TextSpan` and `QueryTextSpan` into a single `TextSpan` (or a `QueryTextSpan` if there is a cursor positioned in any of the text spans).

**Comment by daividssilverio** [comment]
Not the same problem I guess, but we can't even create tags with Japanese characters. It won't show the create tag option. Same thing for projects.

Also, if you type a lot of Japanese characters and add a # in the middle of it, 💥
