### ISSUE TITLE
Workspace selection doesn't work sometimes

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#3269]
## 🐛 Bug Report
If you have a bunch of workspaces, try changing between then in the reports screen.
Sometimes it will stop working. You can change workspaces using the FAB and selecting one from the dialog list, but it won't update the workspace title and the charts.

## Context
Build/Branch: develop (after #3235 gets merged)
Phone OS: Android (6.0.0)
Phone model: Nexus 5

## Expected behavior
Changing workspaces in the reports screen should always work.
The charts and the workspace title should be updated every time you change

## To reproduce
1. Have more than 1 workspace.
2. Go to the reports
3. Change workspaces in the reports screen.
4. That's it, it stops updating the charts and workspace label. (Not always).

## Suggestions
I guess this is related to our AsDriver implementation and how it stops propagating events on Error.
Something is derping and the workspace observable ends up completed.

**Comment by heytherewill** [comment]
@daividssilverio Can you confirm this still happens?

**Comment by daividssilverio** [comment]
It looks like it isn't. I'm guessing #3995 fixed it.
