### ISSUE TITLE
TimeEntriesDataSource.Stop — NoRunningTimeEntryException

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#3281]
## 💥 Crash Report
Got it from AppCenter. Looks like sometimes we're trying to stop a TE either:

a) no actual TE is running
b) the running TE is considered as not running by our code

### 👥 Impact
Has happened 462 times so far to 320 users on 1.3.2 over the last 30 days.

### 🔗 Context
Could be caused by the rxfactor of the Main Activity (?)

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/7cd15fcfb5d281da7241fafe21d20d2cd571b08b?appVersion=1.3.2

### 📝  Exception & Stack Trace
```cs
    TimeEntriesDataSource+<>c.<Stop>b__32_1 (System.Collections.Generic.IEnumerable`1[T] timeEntries)
    Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
    ExceptionDispatchInfo.Throw ()
    ExceptionServicesImpl.Rethrow (System.Exception exception)
    ExceptionHelpers.ThrowIfNotNull (System.Exception exception)
    AsyncSubject`1[T].GetResult ()
    MainViewModel+<stopTimeEntry>d__161.MoveNext ()
    TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
    ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
    MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext ()
    TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
    ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
    MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext ()
    TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
    ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
    MvxAsyncCommandBase+<Execute>d__14.MoveNext ()
    AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
    SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
    Thread+RunnableImplementor.Run ()
    IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
    (wrapper dynamic-method) System.Object.4547d832-b287-4d9a-841f-e0581acac1a1(intptr,intptr)
```

**Comment by amulware** [comment]
Still occurring in 1.6, the second most common crash, over 10% of all crashes:
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3888407288u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3017473257u/overview

**Comment by amulware** [comment]
This may be related to issues with running timers not showing up (except the inverse where a timer is showing, while the TE is stopped). See https://github.com/toggl/mobileapp/issues/3495

**Comment by daividssilverio** [comment]
Can't replicate 🤔 It might still be early but I can't see this crash in 1.7 and 1.7.1 anymore. I'll try to replicate it a bit more tomorrow and if it doesn't and @juanlaube can't replicate either, we might give it a few days to see if it happens on 1.7.1, considering it was common crash on 1.6.

**Comment by juanlaube** [comment]
I can't replicate either, lets keep this open for a few days and see if this is still an issue or is resolved, maybe because of a refactor or another bug fix. We will have another release in the meantime too.

**Comment by juanlaube** [comment]
Still not happening in 1.7.1, I think we can close this.

**Comment by daividssilverio** [comment]
Let's wait the weekend, if everything is alright on Monday I think we should close this as well.

**Comment by daividssilverio** [comment]
Still not seeing this crash or its earlier form. Unfortunately, not sure what could have fixed it. Might have been #3544.
