### ISSUE TITLE
Mvx.Resolve[TService]() — Object reference not set to an instance of an object (again! 💥) 

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#3282]
## 💥 Crash Report
Got it from AppCenter. Looks a constructor problem with the Android Logger.

### 👥 Impact
Has happened 372 times so far to 223 users on 1.3.2 over the last 90 days.

### 🔗 Context
Seems to be distantly related to https://github.com/MvvmCross/MvvmCross/issues/2342.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/groups/ba8a7f84f206d5023307b46e79767fc49d76ca08?appVersion=1.3.2&period=last90Days

### 📝  Exception & Stack Trace
```cs
    Mvx.Resolve[TService] ()
    MvvmCross.MvxAndroidLog..cctor () <0x7f87e45a24 + 0x0001f> in :0
```

**Comment by heytherewill** [comment]
Given the options (introduce a major slow down in the app vs solve sporadic crashes to <1% of users), we've chosen to ignore this for the time being, until we remove MvvmCross from the app (which will, consequently, fix this issue)
