### ISSUE TITLE
Submit feedback form not scrollable for long text

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#3301]
## 🐛 Bug Report
When writing loooong text on the app's submit feedback form, it's not possible to scroll down.

## Context

On the iOS app v 1.11 (1820) (running production iOS 12 on an iPhone X)

## Expected behavior
When writing long text, the box should scroll down with when I type past the screen's bound. I should also be able to scroll upwards to review the message.

## To reproduce
1. Tap the gear icon on the top right corner
2. Tap Submit Feedback
3. Enter a lot of text

![image](https://user-images.githubusercontent.com/5687885/45870857-88b80f80-bdbe-11e8-9e6a-d9107a81f4bd.png)

## Additional Context
A similar situation occurs on Android 1.5 (on an Android 8.1.0, OnePlus 6). You can drag on the textbox to scroll back up, but are unable to scroll down.

**Comment by simonrozsival** [comment]
This does not work in 1.12.1 anymore. We broke it again.

**Comment by khoi** [comment]
I've just checked, this is working fine on `develop`. 

Somehow it didn't make it to `fd15281` `1.12.1-4`? Git problem? @simonrozsival

**Comment by simonrozsival** [comment]
Oh. I see - I thought this was already released in 1.12 or in a hotfix. It was merged into `develop` after the 1.12 was already released (so it wasn't possible to include it in a hotfix. I am closing this now agian. Thanks for investigating, @khoi!
