### ISSUE TITLE
Caps lock indicator overlaps the reveal password button

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3306]
**Steps to reproduce:**
1. Open the login view or signup view
2. Focus the password view
3. Enter a few characters so that the reveal password button appears
4. Double tap the shift button on the simulator keyboard OR tap caps lock on your actual keyboard
5. 💥 

<img width="288" alt="screen shot 2018-09-21 at 05 00 33" src="https://user-images.githubusercontent.com/15633003/45880225-ef81fc80-bdaf-11e8-8dd1-f358d6b8546a.png">

**Comment by khoi** [comment]
Aligning the `Reveal Password` button and the system Capslock is kinda tricky. However, we can remove the system's Caplocks indicator, would that be an option @pe0ny

**Comment by heytherewill** [comment]
🔏
