### ISSUE TITLE
Workspace logic

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#331]
- On a timer page, we'll show time entries from all workspaces
- When suggesting or filtering time entries, projects, clients, tasks and tags, we need to show which workspace these items belong to. eg:
![toggl - ios - projects 1x](https://user-images.githubusercontent.com/5064445/28859454-fafaba4e-775f-11e7-9fca-018f05cfa5ff.png)
- When user has only one WS, don't display WS name when suggesting or filtering time entries, projects, clients, tasks and tags.
- User can switch default ws from settings
- When creating a new time entry with out a project (client, task) and tag, this time entry will go under user's default WS
- Editing ☝️ above mentioned TE which went under a default ws 'a' and adding a project to this TE which belongs to ws 'b', means that TE will be under ws 'b' as well
- When time entry has a project and user wants to edit tasks or tags, we will show only these tasks and tags will belong to the same WS where the project belongs to.
- When time entry has a tag(s) and user wants to add/edit a project, we'll allow to select projects from all the ws user has. This means selecting a project, overrides everything else.

**Comment by pe0ny** [comment]
About the last point, that's how webapp does it:
- I have a TE in ws 'a' and it has a project and tags
- I change the project which is from ws 'b', TE will be now in ws 'b' and it creates automatically tags i had in ws 'a' and added these in ws 'b' as well. So basically I still have those tags in my TE.
IMO it doesn't make much sense or does it? I would say changing project which is from another ws overrides other stuff.

**Comment by amulware** [comment]
The last point should be confirmed with higher up, imo. I.e. what is the intended Toggl behaviour?

**Comment by pe0ny** [comment]
Confirmed with the higher up: When picking a project from a different WS, we won't keep tags, instead tags will be removed from a TE.
Also, we should show some kind of notification that 'you picked a project from a different ws'

**Comment by amulware** [comment]
Does that notification involve a cancel button? Or is the cancel button on the screen/card itself enough?

**Comment by pe0ny** [comment]
I think this notification should involve proceed and cancel buttons

**Comment by jayvdb** [comment]
> User can switch default ws from settings

I cant see this in the preferences yet.  It would be lovely.
And that alone would be enough to solve https://github.com/toggl/mobileapp/issues/675
