### ISSUE TITLE
Calendar settings: long calendar names are not faded out

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3319]
## 🐛 Bug Report
Long calendar names continue under the on/off switch in the calendar settings modal view.

![img_1712](https://user-images.githubusercontent.com/374616/46297917-215c4580-c59e-11e8-8805-78399e154aae.PNG)

## Context

Build/Branch: `develop`
Phone OS: `iOS`
Phone model: any iPhone

## Expected behavior
The text should fade out and not be visible under the switch.

## To reproduce
Create a calendar with a very long name, go the settings view.

## Suggestions
The marquee effect we have for the currently running time entry could be applied here maybe? Well maybe not...

**Comment by juanlaube** [comment]
Closed by #3320
