### ISSUE TITLE
Glitch in start time entry screen

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3322]
## 🐛 Bug Report
Something is broken in the start time entry screen when editing the duration. See the attached screenshot.

## Context

Build/Branch: `sirius`
Phone OS: iOS
Phone model: Any?

## To reproduce
1️⃣ Start a new time entry
2️⃣ Tap the clock icon in the toolbar to edit the start and stop times
💥 

![img_b46e628c96a2-1](https://user-images.githubusercontent.com/8163330/46342319-b876db00-c63a-11e8-8802-95dfcfce9005.jpeg)

**Comment by juanlaube** [comment]
The bug was introduced in ea9a3cf4

**Comment by heytherewill** [comment]
🇮🇹
