### ISSUE TITLE
App is randomly not assigning tags to new entries when an entry is continued

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3324]
Bug Report
Tags aren't always being brought across to new continued entries

Context
Create a new entry through either continue method on a 4G connection

Build/Branch:1.12
Phone OS:12
Phone model:iPhone SE

Expected behavior
Each entry created in this way should still contain the same details of the initial entry

To reproduce
Continue an entry through swipe or small play icon on the entry
Do this several times in quick succession
Tags aren't always being assigned to the created entries as they should be

![image](https://user-images.githubusercontent.com/18132080/46354235-72337300-c65e-11e8-99f2-2944f7333570.png)

All of the entries were continued from the lowest #Delete this task with tags assigned. I've tested without the # in the name as well and the same thing occurs.

**Comment by juanlaube** [comment]
This is a regression in 1.12 and should be fixed. The bug only happens with the continue button, but not with the swipe to continue action.

**Comment by khoi** [comment]
This can be closed right?
