### ISSUE TITLE
Make sure we don't accidentaly commit changes to RealmConstructors

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3334]
This is a follow-up of #3332.

The T4 file `RealmConstructors.tt` produces incorrect code so we manually override it with our custom code. The problem is that it can be really easy to miss this and commit the automatically generated code by accident (during merge for example). We must either fix the T4 file, or remove it.

**Comment by heytherewill** [comment]
Part of the PrimeRadiant refactor
