### ISSUE TITLE
Calendar events and time entries are displayed in a weird cascade

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3340]
## 🐛 Bug Report
Calendar events which start at the end time of the previous event are displayed correctly until there is a parallel time entry displayed at the same time, then it looks like this:

![calendar_cascade](https://user-images.githubusercontent.com/374616/46598584-e3eb4100-cae4-11e8-8f46-67fda8fdbe68.png)

## Context

Build/Branch: 1.12
Phone OS: iOS
Phone model: iPhone 7

## Expected behavior
The calendar and events and time entries are displayed in two columns.

## To reproduce
Create a bunch of events in the calendar which start at the same time a different  one ends. Then create time entries for the events. You should get similar result  as in the screenshot.

**Comment by simonrozsival** [comment]
A few hours later...

![img_d36a67911ffc-1](https://user-images.githubusercontent.com/374616/46603210-b6a58f80-caf2-11e8-8e84-55cdf3132ed3.png)

**Comment by juanlaube** [comment]
Closed by #3739
