### ISSUE TITLE
Identify and list candidates to optimization 

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3347]
This is fairly simple. Try stressing all flows of the app and make sure to take notes on things that are slow. Also take note of things that are not necessarily slow, but that we want to keep fast (since heavily used/low battery/hot phones might have performance drops).

Preferably, test the apps on older iPhone models (5c/5s/6).

**Comment by dshr** [comment]
Didn't get my hands on an iPhone 5 yesterday, so tested it all on a 6s. Still oldish, but not that old.
So far what seems improvable:
- Startup time.
- Scrolling performance on longer tables (main log, projects and tags). Had to duplicate the data in code for this one just to get longer lists, so might've made it slower by that.
- Typing when creating a new TE. Definitely getting some lag over there.
- Rendering report data when moving to the reports tab — might be more of a network thing though.

Will do some more checks today too, and will looks through the code for some more obvious candidates.

**Comment by willsb** [comment]
Closing this since the knowledge here contained has been transferred into issues
