### ISSUE TITLE
Identify and list candidates to optimization

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3348]
This is fairly simple. Try stressing all flows of the app and make sure to take notes on things that are slow. Also take note of things that are not necessarily slow, but that we want to keep fast (since heavily used/low battery/hot phones might have performance drops).

Preferably, test the app on cheap droid phones. Avoid emulators.

**Comment by daividssilverio** [comment]
Nexus 5 test with about 1 year of data.

- **Startup** takes 3+ seconds

- Main Log
    - **Overdraw in main log**
        - TE cards are being draw at least more than once, specially descriptions, duration and continue. icon
    - Possibly **lots of work going on the main thread** that could be directed to other threads.
    - Spikes of commands between frames when **scrolling**.
    - Specific spike of cpu usage when **loading the first item (suggestions)**.
    - Specific spike when the description contains **emojis**.
    - **Calculating the sum of TEs for sections** seems to create spikes in cpu usage as well.
    - It would be nice to check the possibility to **tweak recycler view pre fetching/caching**. 
    - **Initial hiccup is still there**.

- Reports
    - **Load time for reports** is noticeable (1 or 2 secs)
    - **Scrolling between calendar pages is occasionally slow**; sometimes with hiccups (layout seems to be slow)
    - **Selecting shortcuts** (specially longer ones) also gives hiccup (lots of work is going on in the main thread)

- Settings
    - **Load time is also not ideal**, little hiccup when moving to the activity.
    - **Profile image loads funny** (a placeholder is needed).
    - **No smooth scroll when selecting workspaces**.

- Select Project
    - **Load time is considerable**.
    - Massive spikes of main thread usage when **typing to filter projects**
    - **Deleting characters** is laggy
    - Rendering is also taking considerable cpu.
    - Tasks **grouping/rendering** are slow.
    - **Scrolling when tasks are open** is laggy.

- Create/Select tags
    - **Big spikes of cpu usage when creating tags**.
    - **Deleting characters** is laggy.

- Start time entry
    - **Typing in the filter feels slow** most of the time.
    - **Deleting characters** is laggy.
    - **Projects suggestions** hiccup sometimes.
    - **Typing when a project and multiple tags are set is super laggy**.

**Comment by daividssilverio** [comment]
Oh, forgot one:
- TextView usage
    - Multiple TextViews to render single lines is not ideal
    - Span usages might be helpful (with care)

**Comment by daividssilverio** [comment]
Tools used (visually only):
- https://developer.android.com/studio/profile/android-profiler
- https://developer.android.com/studio/profile/inspect-gpu-rendering

**Comment by willsb** [comment]
Closing this since the knowledge here contained has been transferred into issues
