### ISSUE TITLE
Add tracking to Siri Extension

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3354]
We need to track the usage of Siri Shortcuts, probably for now it'll be enough to track every execution of an intent and the responses (StopTimerSiriIntent, StopTimerSiriIntentResponse(Success/Error)...)

There are two possible approaches for this:
1) Store the events in the shared storage as they happen and send them when the app opens.
2) Send them directly from the extension:
    a - By including a light version of the analytics service in the extension
    b - By moving some the anlytics service code to the `ExtensionKit` project so it can be shared between the extension and Daneel.

I think the best approach is 2b, but I'm open to discuss it.

**Comment by khoi** [comment]
since the time when the event happens is important, I agree that we should go with something like 2b. We could either:

- Extract Analytics Service to its own project.
- Import `Firebase` and `Appcenter` into `ExtensionKit` and implement an isolated tracking logic there.

I prefer the 2nd option since it's probably easier.

**Comment by khoi** [comment]
After some research, the 2nd option implementation could be potentially hazardous. There is no SDK that dedicatedly supports app extension on iOS.

If we use the SDKs in the extensions
- It could damage the app launching metrics
- there is no guarantee on when the metrics will be sent on the server

**Comment by Odrakir** [comment]
Ok, let's use the shared storage and send the events from the app for now. We'll see if that's good enough and keep investigating another way of doing it otherwise.
