### ISSUE TITLE
Setting Eesti as first Preferred Language makes app weird

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#3367]
## 🐛 Bug Report
Estonian users on iOS 12 have reported the app having weird issues and even not launching when Eesti is set as their first Preferred Language through Settings > General > Language & Region.

Estonian users on Android report the app crashing when Eesti is set as the first language under Settings > System > Languages & input > Languages

## Context
Build/Branch: Daneel 1.12 & 1.11, Giskard 1.5.1
Phone OS: iOS 12, Android 8.0.0 (47.1.A.16.20) 
Phone model: Confirmed on iPhone X, iPhone 6s, Sony XPERIA XZ1 (model G8341) 

(I have not been able to reproduce this on my iPhone 8 Plus, still on iOS 11)

## Expected behavior
The app should continue behaving properly regardless of what is selected as the device's Preferred Language.

## To reproduce (on iOS)
1. Update to iOS 12, if you haven't
2. Go to Settings > General > Langauge & Region
3. Select "Eesti" and make it the first item under Preferred Langauge
4. Attempt to start the app and see it freeze/act weirdly

## To reproduce (on Android)
1. Go to Settings > System > Languages & input > Languages
2.  Add Eesti (Estonian) and make it the first language on the klist
3. Install the app 
4. Launch the app 
5. Type in Email and Password, press Log In 
6. Go to Android OS home screen 
7. Attempt to open app again, it hangs 
8. Open Android app switcher 
9. Close app
10. Attempt to open app again 
11. App is no longer logged in 

## Suggestions
Maybe the weirdness and crashing is related to how some virtual keyboard elements are rendered in Eesti?

The current workaround is to ensure that Eesti is not the first item under the Preferred Language list. 

iOS 12:
/conversation/18860146892
/conversation/18818577533

Android:
/conversation/18972554465

**Comment by dshr** [comment]
Pinpointed it in iOS —  parsing fails silenly in `FoundationExtensions.cs:31`, bc in English the format is `dd/mm/yyyy hh:mm:ss +hh:mm` while in Eesti it's `dd.mm.yyyy hh:mm.ss +hh:mm`. It's still strange why DateTimeOffset won't parse it's own output, but that's what I'm going to look into tomorrow.

**Comment by nicktoggl** [comment]
for my reference /conversations/19070785346

**Comment by ricotheque** [comment]
For my reference /conversations/19066602982

**Comment by maritoggl** [comment]
Quick update that at the moment, there are at least 10 users that have reached out about this. Most are Android users, which makes sense, as iPhone users typically don't have the preferred language set as Estonian.
