### ISSUE TITLE
Swedish vowels character crashing app

### ISSUE THREAD

**Issue by nicktoggl** [toggl/mobileapp#3368]
🐛 Bug Report
When creating or using a project with Swedish vowels (I used Å, Ä, Ö) the app freezes and crashes with a 'Toggl has stopped' error. Reported by a user originally (see /conversations/18964989614), I've been able to replicate.

Build/Branch: 1.5.1, user version to come
Phone OS: Android 8.0.0, user version to come
Phone model: Samsung Note 8, user model to come

## To reproduce
Create a project with Swedish vowel characters in Toggl mobile app
## Suggestions
Potentially related to https://github.com/toggl/mobileapp/issues/3367

**Comment by simonrozsival** [comment]
Just a side note: I tried replicating this on iOS and I didn't experience any problems.

**Comment by daividssilverio** [comment]
I can't replicate this on Android as well, tried both Android 8.0 and 6.0.1.
Can you replicate this consistently @nicktoggl @TheSoloJake? I got one crash that seems to be #3730 while trying this, but only once. Do I have to use some specific keyboard to replicate it? I've used the Samsung Keyboard and GBoard with Swedish.

**Comment by juanlaube** [comment]
I wasn't able to reproduce this either, tried with Android Oreo in the emulator and Nougat in a Samsung device, using the develop branch.
The report is for Giskard 1.5.1, so I tried that version and I got a consistent crash for accessing Realm from an incorrect thread, I think this bug was solved before and can be closed.

**Comment by juanlaube** [comment]
After talking with @daividssilverio, we agreed this can be closed since the bug cannot be reproduced in Giskard 1.7.1 anymore.
