### ISSUE TITLE
Setup syncing graph for ghosts clean-up

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3375]
This issue should replace #2640.

We should add a simple sequence of states into the clean-up sync loop:
1. remove ghost time entries (#2631)
3. remove ghost tasks (#3362)
2. remove ghost tags (#2633) (2. and 3. can be swapped)
4. remove ghost projects (#2634)
5. remove ghost clients (#2635)
6. make sure user's default workspace is not a ghost workspace (#3363)
7. remove ghost workspaces (#3361)

**Comment by juanlaube** [comment]
On-hold until we can add the step to make sure the user's default workspace is not inaccessible. All the other states are already in the state machine.

**Comment by simonrozsival** [comment]
This is not on-hold anymore.

**Comment by juanlaube** [comment]
Closed by #3528 since there's nothing else to do about the reason it was on-hold.
