### ISSUE TITLE
Fix extensions version number

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3376]
We are getting this from iTunes Connect

> CFBundleShortVersionString Mismatch - The CFBundleShortVersionString value '1.11' of extension 'Toggl.Daneel.app/PlugIns/SiriExtension.appex' does not match the CFBundleShortVersionString value '1.12.1' of its containing iOS application 'Toggl.Daneel.app'.
> 
> CFBundleShortVersionString Mismatch - The CFBundleShortVersionString value '1.11' of extension 'Toggl.Daneel.app/PlugIns/Toggl.Daneel.SiriExtension.UI.appex' does not match the CFBundleShortVersionString value '1.12.1' of its containing iOS application 'Toggl.Daneel.app'.

And I think is due to the cake script not replacing the extensions bundle versions.

**Comment by heytherewill** [comment]
Does this still apply? 🤔

**Comment by amulware** [comment]
We aren't doing anything automatic with the main app's version either. What exactly is proposed here?

**Comment by Odrakir** [comment]
Do you expect me to remember why I wrote this 2 months ago? 😂

I don’t know. I was probably suggesting to use the cake script to replace version numbers on extensions because I thought that’s what we were doing for the app... 🤷‍♂️
