### ISSUE TITLE
Implement peek and pop for time entries

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3378]
iOS allows for the peek and pop actions when performing a 3D touch on elements.

We've tried implementing it for calendar on #3253 but it feels a bit off for some reasons:

- The preview VC needs to pop into full screen VC, which is not the case for the edit view
- We might wanna have a better preview VC so we can use it both on calendar and for the main log

Before we've fully drafted what needs to be done, we shouldn't be working on these

**Comment by amulware** [comment]
I'm closing this because I don't see it happening anytime soon. We should rethink this, also based on what Apple is doing with replacing 3d touch with long touch now.
