### ISSUE TITLE
Siri: Review rules to avoid sync errors

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#3384]
This was mentioned in the specification but we never got around to do it properly.

We should store the last edit time of the latest entry (that's the weirdly name `at` property) in the shared storage. And compare that to the `at` property of the latest entry in the server.

- If local at time <= server at time: Everything is in sync. Do action.
- If local at time > server at time: There's an unsynced entry, we can continue the shortcut in the app, but not online directly. Not sure if we can do that or we just have to force the user to open the app and try again.

There are many more edge cases, but I'm not sure if it's worth it to handle them or if it's worth it to do it now. Like, what happens if there's a running entry in the server but not in the app?

**Comment by amulware** [comment]
Do we have a list of known edge cases?

**Comment by Odrakir** [comment]
Not sure if this ever got answered in Slack. We don't have a detailed list of edge cases, there are many of them, but since I think all of them involve the app not being synced with the server, and Siri does requiere an internet connection to work, I think (at least for now) it's safe just to check dates and see if the app is in sync, and otherwise forward the user to the app first so it can sync now that he has internet.

We will log this errors and see if it's worth it to add more logic to act upon specific conflicts.
