### ISSUE TITLE
Start a time entry Home Screen shortcut causes infinite loop

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#3391]
## 🐛 Bug Report
When you use the Home Screen shortcut to start a new Time Entry, it loads the app and shows you the new Time Entry view. This is expected.

However, you'll find yourself in an infinite loop. Tapping X or Save pulls up the same view again. You cannot escape. It is relentless. It will never let you leave.

## Context
Build/Branch: Giskard/1.5.1
Phone OS: 9 O_MR1
Phone model: Pixel 2

## Expected behavior
Tapping on X or Save should close the new Time Entry view, then discard the new Entry or Save it respectively.

## To reproduce
(With no running Timer for your account)

1. Go to home screen or app drawer
2. Long-press Toggl app icon until the shortcuts appear
3. Tap on Start a time entry
4. App loads and shows new Time Entry view
5. Find yourself stuck as you desperately press X or Save to get out

## Suggestions
The Continue last time entry shortcut works properly... so maybe this issue is related to how the Starter new time entry shortcut loads a view?

Current workaround is to avoid using the Start a new time entry shortcut.

(/conversation/18961635498)

**Comment by ricotheque** [comment]
Just checking guys... will this be fixed in a future update?

**Comment by simonrozsival** [comment]
It hasn't been scheduled for any future release yet. @amulware either missed it or it is considered low priority..

**Comment by amulware** [comment]
This was not labeled properly, so I did not see it.
