### ISSUE TITLE
Create Api clients

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#34]
We need at least:

- [x] User
- [x] Workspace
- [x] Client
- [x] Project
- [ ] Task
- [x] Tag
- [x] Time Entry

These should be implemented separately and tested appropriately.

**Comment by arturs105** [comment]
Project and Task API clients have been implemented [here](https://github.com/toggl/mobileapp/tree/projects-api) and [here](https://github.com/toggl/mobileapp/tree/tasks-api), however there are some issues with testing them related to premium features. When #207 is resolved, we should be able to use them properly.
