### ISSUE TITLE
Measure app startup time

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3403]
Let's get some accurate data on how long it takes for our apps to boot!

It seems that the `FirebasePerformance` class has a couple of methods that can be tied to the lifecycle of the first activity. Let's investigate this.

In case there's no built-in mechanism, let's default to using a trace, *but only as a last resort*.

**Comment by daividssilverio** [comment]
`FirebasePerfromance` works like this:

>Starts when the app's FirebasePerfProvider ContentProvider completes its onCreate method and stops when the first activity's onResume() method is called. If the app was not cold-started by an activity (for example, by a service or broadcast receiver), no trace is generated.

Then, the values we currently have on Firebase represent the time the app needs to get from startup to the `SplashScreen:OnResume` method, which might be close to the time the app needs complete all the setup code, but is **not** the same thing.

**Comment by daividssilverio** [comment]
I'll be putting this on-hold until we finish the other tasks.
We already have the default tracing as described above, but if we decide we need more specific tracking, it should be pretty easy to add a custom trace.

**Comment by willsb** [comment]
I see that under `Com.Google.Firebase.Perf.Metrics`, there's an `AppStartTrace` class with a couple of methods (`SetLauncherActivityOnCreateTime`, and two others for `Resume` and `Start`). 

What do these methods do? Why are we not using them anywhere? Please investigate and, if they are irrelevant, feel free to close this issue

**Comment by daividssilverio** [comment]
I see them too. They have no docs and I have no idea what they do. Googling it yields Chinese results.
I rather use the custom tracking method.

**Comment by heytherewill** [comment]
This has been shipped
