### ISSUE TITLE
Measure app startup time

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3404]
Let's get some accurate data on how long it takes for our apps to boot!

Let's check if Firebase has any means of attaching itself to the AppDelegate to give us 100% accurate data.

In case there's no built-in mechanism, let's default to using a trace, *but only as a last resort*.

**Comment by dshr** [comment]
This should be already enabled by default. Weirdly enough, we have no data for Daneel in the Firebase console, even though we're using it right. After spending the most of last Friday on trying to enable it on debug, I got some data this morning. Data points seem alright too, unlike Giskard, where it logs the time it take to open the SplashScreen activity.

**Comment by heytherewill** [comment]
This has beens shipped
