### ISSUE TITLE
Measure the time it takes to open the create tag view

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3411]
This needs two measurement points:

- One from the start time entry view
- One from the edit time entry view

**Comment by daividssilverio** [comment]
Since you can't go to the `create tag view` from the start time entry view, and the query performance is to be measured at #3405, I'll add just the second item.

**Comment by daividssilverio** [comment]
Let's wait until #3421 is merged to avoid duplicated work.

**Comment by dshr** [comment]
Closed in #3466
