### ISSUE TITLE
Cache the first cell of the main log

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3413]
Given that the main cell is not reusable, unique and contains an entire recyclerview inside of it, it makes a lot of sense to cache it as to prevent it from ever being collected/recreated when scrolling all the way to the top.

**Comment by daividssilverio** [comment]
Contrary to my previous say, the suggestion list view holder is not being recreated every time the user scrolls down and back. It stays there minding its own business after it is created (Even on Android Go with 512 ram).

It does take some time to create it, about 250~350ms.

I'll put this on hold, but I see no benefit in caching this VH anymore.

**Comment by heytherewill** [comment]
Not needed for the time being
