### ISSUE TITLE
Tweak the pre-fetching properties of the main log's recyclerview

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3415]
Maybe if we configure the pre-fetch attributes adequately, we might be able to get a smoother scrolling experience

**Comment by daividssilverio** [comment]
😊 It looks like I've added the prefetch setup during the main log rxfactory :0
Let's see if it can get better.

**Comment by daividssilverio** [comment]
I've tried tweaking other caching properties but with no avail.
I've tried changing `SetItemViewCacheSize` and changing the `RecycledViewPool` max recycled views for `ItemViewType` and `SectionViewType`, but the former only made things worse and the latter didn't show much improvement.

Maybe we should come back to this after improving the main log inflation/bindings first to perceive any improvements.

**Comment by heytherewill** [comment]
Closing as invalid
