### ISSUE TITLE
Display tokens aligned with the baseline of the text

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3425]
The tag and project tokens are not aligned with the baseline of the text. The tokens design in Zeplin is not exactly aligned with the baseline too, but it is closer than what we have in the current version.

We should try making tokes look more like the designs and also align them with the baseline.

<img width="404" alt="iphone x - 12 0 2018-10-12 12-17-44 2" src="https://user-images.githubusercontent.com/374616/46864222-f71a4b80-ce19-11e8-9609-87f7b00a23b6.png">

**Comment by amulware** [comment]
I'd like to see how it looks to have the baselines actually aligned. If that looks weird or has issues with multiple lines somehow, then we'll go with what the designs show, but baseline alignment would be ideal.
