### ISSUE TITLE
Show multiple error messages when editing time entries

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3434]
Right now, only one error message (that comes from backend) is shown in the edit time entry view. We're introducing a new message when editing a time entry marked as ghost. This issue is to decide if we need a UI change to show multiple error messages, or we will show the most relevant only.

**Comment by simonrozsival** [comment]
I think the message is OK and it would be confusing if we added a second error message. Let's leave it as it is and change only based on user's feedback.
