### ISSUE TITLE
Track when user gains access to a new workspace

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3444]
Any time user gains back access to a new workspace, track that it happened.

Can we somehow ignore this right after login and sign-up? The user always gains access to at least one workspace (unless a user who has no workspace signs up). Please suggest a _nice_ way how to ignore these cases (for sign-ups we can check the onboarding storage for "is new user", but what about login?). Let's first discuss it and start writing the code only afterwards.

**Comment by juanlaube** [comment]
Wouldn't tracking only if there's another workspace in the database solve this? 🤔

**Comment by simonrozsival** [comment]
It would. I am not sure if it would not break something else :thinking:
