### ISSUE TITLE
Do not use the "ghost" word in our code

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3445]
We use the term "ghost" for two cases now:
1. when we create a temporary entity instead of an archived project (see `CreateGhostProjectsState` and `DeleteNonReferencedProjectGhostsState`)
2. when user loses access to a workspace

- [x] In the first case, I suggest renaming the methods and related references in the code to "temporary entity" or explicitly "archived project placeholder" (I prefer the latter but I will leave this one on the person creating the PR)
- [x] In the second case, let's call the properties, all references in code, comments, and documentation, using the term "inaccessble": `IsInaccesssible`, "inaccessible entity", "mark as inaccessible", and so on

**Comment by simonrozsival** [comment]
Also please feel free to suggest different names here in comments.

**Comment by dshr** [comment]
Why not ghosts and ghouls? :trollface:

**Comment by simonrozsival** [comment]
All the usages of the word 👻 are gone.
