### ISSUE TITLE
Assigned task not showing up on Timer + Create and Edit Entry Views

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#3454]
## 🐛 Bug Report
The assigned Task for an Entry does not show up on the Timer or when creating or editing an Entry.

## Context
(/conversation/18996172897)

Build/Branch: Giskard 
Phone OS: Android
Phone model:

## Expected behavior
The user should be able to see the assigned Task on the Timer, and when creating or editing the Entry.

## To reproduce
1. Create a new Entry on the Android app
2. Select a Task
3. See that the Task not appearing beside the Project's name
4. Save new Entry
5. Edit Entry
6. See that the Task not appearing beside the Project's name
7. Press X to close Edit Entry view
8. Tap on Entry's continue button on main view
9. See that the Task not appearing beside the Project's name on the Timer bar

## Suggestions
The Task already appears for the Entry while it is listed on the main view. Just carry this over to the other views mentioned here.

**Comment by simonrozsival** [comment]
Just a note: iOS app displays tasks correctly in all of the described scenarios.

**Comment by nicktoggl** [comment]
conversations/19093938667

**Comment by amulware** [comment]
Is this related to https://github.com/toggl/mobileapp/issues/3590?

**Comment by daividssilverio** [comment]
#3590 fixed the edit view part.

**Comment by daividssilverio** [comment]
Just so everybody is aware, the `client` is not showing on both android and iOS in the Start Time Entry view.
