### ISSUE TITLE
Suggestions for performance tracing/improvements

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#3458]
During the team meeting (16-10), the team asked about places that could be measured that we didn't list on #3347 and #3348.

This is issue can be used to list places you guys think could be measured/improved. 

Take a look at https://github.com/toggl/mobileapp/projects/23, #3347 and #3348 to know what is already on the radar.

@willsb will take a look at this when he is back.

**Comment by simonrozsival** [comment]
My ideas so far:
- [ ] Wheel view - how long does it take to update the view when dragging (delay between user moving the finger and the view being redrawn, maybe an average or maximum until the user closes the view)
- [ ] Calendar view - how long does it take to update the layout when user drags an item up or down (similar to the measurement above - an average + maximum delay maybe?)

**Comment by daividssilverio** [comment]
About the overdraw in the main log stuff:

- [ ] MainLogCellViewHolder: measure how much time it takes to bind a single time entry. Maybe not do it on every time entry because it might hurt performance. Sample it? Maybe only time entries with projects? Or separate TEs with projects and without projects.

**Comment by daividssilverio** [comment]
I've added a WIP PR about some ideas to improve the main log: #3480.
I'll revisit it later, but it would require measurement as well.

**Comment by daividssilverio** [comment]
I've investigated the startup for a few hours using systrace and `Debug.StartMethodTracing` and we are taking a good time in the inflation of the `MainActivity` and `OnCreate` method there as well.

We might wanna trace the `MainActivity` `onCreate` method.

**Comment by willsb** [comment]
@daividssilverio Measuring the onCreate method sounds like a good idea!
Regarding the `MainLogCellViewHolder`, how would you do it?

@simonrozsival Your ideas sound rather hard to measure (as in: No easy extension points). I don't wanna have stopwatch logic on the draw method 👀

**Comment by daividssilverio** [comment]
@willsb, as simple as starting a stopwatch before the instantiation of the VH and stopping it right before it's returned to the `OnCreateItemViewHolder`.

I've tested this on systrace already btw. It seems to be our source of jankiness in the main log.

**Comment by willsb** [comment]
Please do it, then!

**Comment by willsb** [comment]
Closing since the deadline is here
