### ISSUE TITLE
Reload time entries log when user loses access to a workspace

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3468]
This is an Android counterpart of #3467. The specs are exactly the same.

**Comment by sofokli1** [comment]
Will take a look at this after #3507 is merged

**Comment by sofokli1** [comment]
Will take a look at this after #3507 is merged

**Comment by sofokli1** [comment]
Test on the simulator same steps as the ios counterpart and works the same as is. I vote to close this

**Comment by sofokli1** [comment]
I re-tested this with the latest develop, works fine on my emulator. I am closing this
