### ISSUE TITLE
Investigate unsymbolicated crashes

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3473]
Since the release of Daneel 1.11, there are 928 unsymbolicated crashes in AppCenter (for 1.11, 1.12 and 1.12.1). We need to find those dSYM files if possible and fix this for future releases.

**Comment by khoi** [comment]
Couldn't find any helpful information regarding `Mono.dSYM`, I've opened a support ticket to AppCenter, waiting for their response.

**Comment by khoi** [comment]
AppCenter's responded
```
Hello - unfortunately we do not support symbolication of app extensions so this behavior is by design at this time.
```
Not much we can do here, in #3455 I have tracked when the intent raises exceptions, so that might help a bit.

**Comment by khoi** [comment]
I'll close this for now as there is nothing we can do
