### ISSUE TITLE
App Outdated not shown

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#3484]
## 🐛 Bug Report
When the app is outdated, the app outdated modal is not being shown.

## Context

Build/Branch: `develop`
Phone OS: Any Android
Phone model: Any

## Expected behavior
The outdated modal view should be shown. 

## To reproduce

Hard code to make the app outdated:

In `App.cs` add `|| true` to `NavigateToFirstViewModel`

```
if (true || accessRestrictionStorage.IsApiOutdated() || accessRestrictionStorage.IsClientOutdated())
```

**Comment by daividssilverio** [comment]
Alright, this was caused by #3220 in order to prevent an app freeze when launching the application from the running/not-running notifications. It seems fixable by fixing the problems in #3220 some other way and removing the forced navigation to the MainActivity.cs.
