### ISSUE TITLE
RTL languages don't display properly in reports 

### ISSUE THREAD

**Issue by epagnini** [toggl/mobileapp#3494]
related to https://github.com/toggl/mobileapp/issues/3270

## 🐛 Bug Report
1. Line 3 - anything instead of "אולי - תחזוקת שרתים"
2. Line 4 - "bl..." instead of "blak".

3. Lines 1, 2, 4 - missing percent sign (%) in the second column

The second file, from 13:23:39
Problem in the homepage, about the description and RTL

Please see the second time entry.

The description begin behind the 00.78 h, from above the right side of the arrow.

On other issues with shorter description i cannot see anything because it placed behind the time span.

Build/Branch: 1.5.2
Phone model: Xiaomi Redmi Note 3
Platform and OS version: 9 O_MR1

*images attached to convo*
conversations/19051546756

**Comment by heytherewill** [comment]
I've create a bunch of projects in RTL languages and they display just fine in the reports. Maybe this has been fixed else where?

![image](https://user-images.githubusercontent.com/7688727/50017526-7ad7ec00-ffb3-11e8-9ceb-27d92618c78e.png)
