### ISSUE TITLE
Running Timer doesn't appear

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#3495]
## 🐛 Bug Report
We've received several reports of app users not seeing a running Timer after it is started.

## Context

Build/Branch: Giskard 1.5.2
Phone OS: 6.0 LOLLIPOP_MR1, 8.0.0 N_MR1, 8.0.0 N_MR1, 8.0.0 N_MR1, 6.0.1 LOLLIPOP_MR1, 
Phone model: Sony E5333, samsung SM-N950U1, Sony F5321, samsung SM-G960U, OnePlus ONE E1005,

## Expected behavior
When starting the Timer (on the web app, desktop app, or even on the mobile app) this should be visible when going to the main app's main screen.

## To reproduce
Unable to provide at this time; no one on support is able to reproduce.

## Suggestions
The only common factor among reports so far is that they're all on Giskard 1.5.2.

Reports below might provide some insight:

(/conversations/19088435115)
_Pulling the screen down does initiate a manual sync that grabs past entries. However, it still doesn't grab the current ongoing task that I've started on the PC desktop app. The mobile app should be showing my current ongoing task._

(/conversations/19109968332)
_I'm having major syncing issues between the new Android app and the web app. for some reason whenever I start a timer on the web app my phone is hit or miss with catching it._

(/conversation/19046710379)
_New timer entries do not display at bottom of app or in notification. Timer is still running -- if you hit the green arrow again and start a new timer, the original timer is stopped and displayed in the list of completed tasks. The new timer, however, is completely hidden and the app shows no sign that it is running._

(/conversation/19101976572)
_I had started the time entry on the app, and it disappears from the currently-running timer area (ie, the bottom of the app screen). I am not able utilize the timer due to that._

(/conversations/19101976572)
_Hi, the toggl android app is not working properly. It is not showing the timer mode sometimes, even though time entry being monitored._

(/conversations/19078387693)
_Even if I run a new timer, the ongoing timer didn't appear unless I restarted the app. Just wondering if these are two related issues._

One user has been kind enough to try a manual sync and logging out then back in:

_A manual sync does not fix the issue._
_Logging out and logging back in does appear to get the running timer to display -- hooray!_

(Many more details at /conversations/19046710379)

**Comment by VeljkoTN** [comment]
another one: conversations/19120952320

**Comment by epagnini** [comment]
conversations/19351511913

**Comment by epagnini** [comment]
conversations/19519953393

**Comment by juanlaube** [comment]
I've been trying to reproduce this without any luck.
I see all those users were in Giskard 1.5.2 (except for the last one), I also tried to reproduce in that version without success.

**Comment by daividssilverio** [comment]
Leave this to me, I can replicate this very easily on my Nexus 5.

**Comment by juanlaube** [comment]
I assigned you the issue @daividssilverio 🙌 
Do you think this is a performance problem or happens only in a specific Android version? I tried with my Samsung Galaxy J7 and I couldn't reproduce.

**Comment by daividssilverio** [comment]
Thanks @juanlaube. It seems to be a race condition between the times when the observable `IsTimeEntryRunning` delivers its values and the time it takes for the radial animation to finish and actually hide/show the timer card. If you do increase the duration here:
MainActivity.cs
```
var radialAnimation =
                runningEntryCardFrame
                    .AnimateWithCircularReveal()
                    .SetDuration(TimeSpan.FromSeconds(0.5))
                    .SetBehaviour((x, y, w, h) => (x, y + h, 0, w))
                    .SetType(() => visible ? Appear : Disappear);
```
to a second or so, you are more likely to reproduce the error.
