### ISSUE TITLE
WS removal: hide current running time entry

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3524]
When we detect that user does not have access to a workspace and there is a time entry in that workspace currently running, we must hide it.

If it is in sync, we will delete it anyway, there is no reason to stop it (it would even change it to `SyncNeeded` state), just hide it.

If it is not in sync, we should stop it and the user will then be able to see it in the log, move it to a different workspace, and then adjust the end time.

**Comment by simonrozsival** [comment]
This is so far the most complex case of UI update. I would like to hear @amulware's thoughts on this before we start implementing this.

**Comment by amulware** [comment]
If it's not synced, why must we stop it?

**Comment by simonrozsival** [comment]
Because the user won't be able to stop it himself, because the only changes we allow are changing project and deleting the TE (#2902).

On the other hand I just realized that we can't "just hide" the TE even when it is in sync. We might end up with two running TEs in the database. Which would not be good... We might want to delete the TE right away (before the clean-up loop kicks in), or stop it, but set the sync status to `InSync`.

**Comment by simonrozsival** [comment]
When #3526 is implemented, all that will be left to do is to immediately remove the currently running TE if it is in sync with the server (so the user can't stop it himself before we clean up everything).

If it is not in sync then we can leave it displayed as a running TE and the user will stop it himself or delete it.
