### ISSUE TITLE
WS removal: allow stopping an inaccessible TE

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3526]
At this moment stopping a TE which is inaccessible leads to a crash.

**Comment by juanlaube** [comment]
I was able to reproduce this only once and I for some reason the exception was empty (?!). After that everything worked fine and the TE had a sync error message.

![simulator screen shot - iphone xs max - 2018-10-23 at 13 15 37](https://user-images.githubusercontent.com/8163330/47376624-7d137d80-d6c9-11e8-9574-8d04432c4a43.png)

My steps trying to reproduce this:
1. Had two accounts
2. From account A, invited the other user
3. From account B, accepted the invite and started a new time entry in the new workspace
4. Synced the running TE in the app with account B
5. Deactivated access to account B from account A
6. Sync in the mobile app
