### ISSUE TITLE
Rename our methods to close view models

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3533]
### The Problem

We have too many means of closing a view model:

- The names are split between `Back` and `Close`
- We have commands, methods and actions
- Sometimes we are closing things manually instead of using the ViewModel

### The solution

- We use close since it best conveys the action of destroying a ViewModel (`Back` implies a specific mean of navigation, which might or might not be truth)
- We should use Actions, since this is the preferred way of handling View -> VM interactions
- We create an extension on `MvxViewModel` so that every concrete implementation can close itself.
- We remove all existing close code and tests. This will significantly reduce useless code.

The result is something like this:

```csharp
public static class ViewModelExtensions
{
    public static UIAction CloseAction(this MvxViewModel viewModel)
        => UIAction.FromAction(() => viewModel.NavigationService.Close(viewModel));
}
```

**Comment by arturs105** [comment]
1. Is the intended usage something like the following?
```
this.Bind(someButton.Rx().Tap(), ViewModel.CloseAction())
```
2. We should name it `Close()` instead of `CloseAction()`, since names like that were just refactored out.
3. What about closing the view model and returning a value. Those cases still need an `RxAction` in the view model, right?

**Comment by willsb** [comment]
1. More like `someButton.Rx().BindToAction(ViewModel.Close())`
2. Yes
3. I don't think so. We can have `Close()` overrides that take into account the generic return type, since everything heavily relies on the navigation service

**Comment by arturs105** [comment]
3. That wouldn't work everywhere, since there are view models that rely on `private` members to return the data.

**Comment by willsb** [comment]
In such cases, create a local action within the VM
