### ISSUE TITLE
Drop Action suffixes from UIActions and InputActions

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#3536]
### The problem
Some UI/Input Actions have the `Action` suffix and some do not. We need consistency here.

### The solution
I say we drop all `Action` suffixes, similar to what we did with Observables, unless someone has a good case as to why we shouldn't do so. 

Either way, please consider the decision made here before working on #3533

**Comment by Odrakir** [comment]
This is simple enough.

Also, how about things like: `CloseButtonTapped = UIAction.FromObservable(cancel);`

Should the Action be called as the UI event triggering it?

**Comment by willsb** [comment]
I don't think it should, no
