### ISSUE TITLE
Remove rounded corners from the bottom of the modal sheets

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#354]
When a view controller is presented with `ModalCardPresentationAttribute` it has all 4 corners rounded, however only the top corners should be rounded.

We could extend the length of the modal view so that it still has rounded corners, but they are off screen. If we choose this approach, then #324 should be finished and merged before.

Alternatively, we could implement a way to round just 2 corners.

**Comment by amulware** [comment]
I'd say to just make the view bigger and hide the bottom corners outside of the screen. That should be the least effort, most straight forward, and most performant thing.
