### ISSUE TITLE
Test that clean-up of inaccessible entities removes everything in sync

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3581]
Create a sync test which
- already has some inaccessible entities in the database (no need to detect that the workspace is inaccessible in this test) - everything should be in sync
- schedule clean-up loop in `Act`
- test, that it removed all inaccessible TEs, clients, tags, projects, tasks related
- test, that the workspace itself was removed

**Comment by juanlaube** [comment]
Closed by #3612
