### ISSUE TITLE
Test that clean-up of inacessible entities does not remove unsynced and unsyncable entities

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3582]
Create a sync test which
- already has some inaccessible entities in the database (no need to detect that the workspace is inaccessible in this test) - everything should be either unsynced or unsyncable
- schedule clean-up loop in `Act`
- test, that it DID NOT remove any inaccessible TEs, clients, tags, projects, tasks related to the workspace
- test, that the workspace itself was NOT removed

**Comment by juanlaube** [comment]
Closed by #3613
