### ISSUE TITLE
Test that clean-up removes all entities it should remove and keeps the rest intact

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3583]
Create a sync test which
- already has some inaccessible entities in the database (no need to detect that the workspace is inaccessible in this test) - some things should be in sync, others unsynced or unsyncable
- schedule clean-up loop in `Act`
- test, that it removed all inaccessible TEs, clients, tags, projects, tasks related, and that it kept the rest in the DB
- test, if the workspace itself was removed

**Comment by sofokli1** [comment]
Already impolmented by @juanlaube
