### ISSUE TITLE
Setup basic iOS app

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#36]
This is so we can start working on UI at the same time as we work on underlying business logic and other technical bits.

There is no point in working only from one side with the upcoming test weeks.

**Comment by villasv** [comment]
Any chance of also getting an UWP app?

**Comment by willsb** [comment]
@villasv Our roadmap is for remaking the iOS and Android apps first. I can't promise anything, but we'll have a shareable core and I'd love to write an UWP app against it :)
