### ISSUE TITLE
Start running time entry from calendar event

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3622]
When the current time is in between the calendar event, we should let the user create a running time entry instead of creating the full time entry with end time (an action sheet for the UI maybe?).

**Comment by amulware** [comment]
I can see users wanting to start the entry a little ahead of time as well, or if they are behind schedule, afterward.

I propose that tap+hold or a force touch should open an action sheet with the actions:

- copy to time entry (the current function)
- start at event start time (only if the same is in the past)
- start now
- cancel

Might need some better copy.

The only thing that bothers me now is: What to do about the default behaviour on tapping? Should that sometimes create a stopped entry, and sometimes a running one? By what criteria? Can we make this intuitive, and not confusing?

Or will we always need to use the action sheet? :/

**Comment by lizaPlotnikova** [comment]
@juanlaube When do you need these designs by?

**Comment by juanlaube** [comment]
@lizaPlotnikova this is scheduled for Daneel 1.16, deadline is Jan 16th, so a few days before that would be ideal.

**Comment by juanlaube** [comment]
and by "a few days" I mean a week or so 🙂

**Comment by simonrozsival** [comment]
I will start by showing the action sheet after a long press. Hopefully we will sort the rest before I finish it 😄

**Comment by simonrozsival** [comment]
Oops. The action sheet is ready for reviews.

**Comment by amulware** [comment]
Let's do the rest of this when we have designs. :)
This is actually in 1.17, not 1.16, so we have time.

**Comment by simonrozsival** [comment]
I'm closing this until we have the designs.

**Comment by amulware** [comment]
I'm re-opening this because I want it in 1.17

**Comment by simonrozsival** [comment]
Ok then 😆

**Comment by sofokli1** [comment]
do we have designs for this?

**Comment by lizaPlotnikova** [comment]
@sofokli1 not yet :)

**Comment by amulware** [comment]
Very out of date.
