### ISSUE TITLE
Configuration for snapping interval in calendar view

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3626]
Right now the snapping interval is 15 minutes, we want to make this configurable. This should only add the setting (defaults to 15 mins) and respect it in the calendar view.

**Comment by amulware** [comment]
What's the reasoning behind this? Do other clanedar apps have a setting like this? Won't the user have troubles getting to the time they want if the interval is too small?

**Comment by juanlaube** [comment]
This is based on the discussion to improve the calendar. To be honest, I'm not a fan of this, I don't see how this could benefit users and would add a lot of complexity to the solution.
