### ISSUE TITLE
Center the calendar - improvements

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3628]
So when the user opens the calendar early in the morning or late in the evening doesn’t see hours they don’t really care.

Requires #3629

**Comment by amulware** [comment]
I don't understand the use case for this. Why is it needed?

**Comment by juanlaube** [comment]
Most people are only interested in a certain part of the day only, usually 9:00 to 17:00. Right now if you open the calendar 17:00 for example, you're more likely to see an interval between 12:00 and 22:00 (depending on the screen size).

**Comment by amulware** [comment]
So you would still keep the 'now' line (and maybe ~1h around it) visible, just bias where it opens for late/early in the day?

**Comment by juanlaube** [comment]
Yes, that's the idea. I've seen other calendar apps doing this, the interval is configurable.

**Comment by amulware** [comment]
I'd also like to make the background before/after working hours slightly gray as well. If needed please create a new issue for that in the same project, or add the needs-design label here - whatever makes most sense.

**Comment by juanlaube** [comment]
It was decided to not use the concept of "working hours". Instead the logic will be to center on avg(current time, noon) ± an offset, this should introduce a bias that makes the current time show on top in the morning and on bottom in the afternoon.

Examples:
At 9:00 - should be centered at avg(9:00, 12:00) = 10:30, so the current time indicator is close to the top of the screen
At 17:00 - should be centered at avg(17:00, 12:00) = 14:30, so the current time indicator is close to the bottom of the screen

**Comment by simonrozsival** [comment]
Should there always be an at least "20%" of the screen space visible before and after the current time indicator as it was mentioned in the discussion or any similar adjustment?

**Comment by juanlaube** [comment]
Yes, I forgot about that, sorry. There should be a space visible before/after the current time indicator, if 20% of the screen is probably ok, but the best would be to try in different devices until something looks good. This will only help in cases where the current time is before 6 am or after 8 pm (more or less), otherwise with the avg function there should be enough space.
