### ISSUE TITLE
Center the calendar in “working hours” - configuration UI

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3630]
This should add two new rows in the Calendar Settings view to select the working interval. Should open a new view to select between 0 and 24 and save those to the settings storage as defined in #3629.

**Comment by simonrozsival** [comment]
I'm not sure if I like the idea of the new view popping out - something like a range slider could lead to better UX. Or have inline time pickers for the start and end times which would slide in an out similarly to how the date picker is shown in the wheel view when you tap on the start or end times.

**Comment by juanlaube** [comment]
It was decided to not use the concept of "working hours" and a configuration is not required anymore. Instead the logic will be to center on avg(current time, noon) ± an offset, this should introduce a bias that makes the current time show on top in the morning and on bottom in the afternoon.
