### ISSUE TITLE
Pressing back after creating TEs from text selection creates new TE

### ISSUE THREAD

**Issue by shantanuraj** [toggl/mobileapp#3642]
## 🐛 Bug Report

After creating TEs from text selection, pressing back or switching back to the previous app
relaunches the Toggl app and creates a new TE.

## Context

1) Pressing the back button, restarts the activity or repeats the intent causing the app to create a new TE again.
2) Choosing the previous app from the app switcher does the same thing ^, until I close the app

Build/Branch: 1.6 from the Play Store
Phone OS: Android 9
Phone model: Pixel 2XL

## Expected behavior

After the TE is created, pressing back should let me go back to the previous app.

## To reproduce

See [video](https://toggl.slack.com/files/U8U0D02S3/FDVHWP1GU/toggl-mobile.mp4)

1) Select some text on a Chrome page
![image](https://user-images.githubusercontent.com/1716853/47993712-346eb200-e116-11e8-8dbc-488ed6a7ca60.png)
2) Press the Toggl option from the popup menu
3) Stop the newly created TE
3) Press the back button
4) A new TE is created
5) From the app-switcher select Chrome again
6) You'll land back in the Toggl app with a new TE

## Suggestions

* Not sure, but looks like on pressing back  either the intent is repeated or activity restarts creating a new TE, maybe look into the lifecycle hooks.

**Comment by TheSoloJake** [comment]
Experienced by this user: https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19883403461
