### ISSUE TITLE
Handle HTTP failures before detecting gaining and losing access to workspace

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3652]
Right now we might not handle 4xx and 5xx errors correctly and sync would finish showing `Failed` message to the user.

We must check if the HTTP request did not fail and if it did, handle it the same way we already do with all the "persist" states.

I think this could be done in a generic way in a state, which would have an internal `Func<IFetchObservables, IObservable<T>>` selector and which would have transitions `Continue[FetchObservables]` and `ErrorOccured[ApiException]`.

We could then add this state before the first state which uses some of the fetch observables for the first time in the pipeline and simplify the `Persist*` states.

**Comment by juanlaube** [comment]
Closed by #3657
