### ISSUE TITLE
Rename `DetectLosingAccessToWorkspaces` state

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3653]
The state does more than just _detecting_ that access was lost as it also marks these workspaces as inaccessible. It would be helpful if we had a more general name (but still short) which would describe what the state does in the transitions diagram.

![screen shot 2018-11-05 at 4 23 43 pm](https://user-images.githubusercontent.com/374616/48009240-8f56d800-e11b-11e8-9df8-ea25f6e90dda.png)

Some of my ideas:
- `HandleLosingAccessToWorkspaces` - too broad?
- `DetectAndMarkInaccessibleWorkspaces` - too long?

Suggest some name and when we agree on a final name, let's rename the class.

**Comment by simonrozsival** [comment]
After creating the second similar issue (#3654) I think it might even be good to split this state in two. Have a state which _detects_ losing access and a state which _marks_ these workspaces as inaccessible. The graph would be much more descriptive.

**Comment by juanlaube** [comment]
Closed by #3668
