### ISSUE TITLE
Rename `PersistNewWorkspaces` state (or split it in two?)

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3654]
Similar issue as #3653 

The state does more than just _persisting_ new workspaces, it also resets the the since params repository.

It would be helpful if we had a more general name (but still short) which would describe what the state does in the transitions diagram.

![screen shot 2018-11-05 at 4 23 43 pm](https://user-images.githubusercontent.com/374616/48009240-8f56d800-e11b-11e8-9df8-ea25f6e90dda.png)

Some of my ideas:
- `HandleNewWorkspaces` - too vague?
- `PersistNewWorkspacesAndResetSinceParams` - too long..

It might be better to split this in two states and first rest since params storage and then persist the new workspaces? 🤔 Maybe it's better than giving this state a confusing name. It would be similar to the `ScheduleCleanUp` state.

**Comment by juanlaube** [comment]
Closed by #3669
