### ISSUE TITLE
Unable to edit entries

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3663]
After updating app to 1.13.1 (mnemon hot fix)
Opened app and was logged in to existing account. 
Continued two entries by swiping, deleted one entry. 
Then was unable to edit any entries, the UI was unresponsive to anything other than swiping or pressing the settings button.
Tapping on entries had no effect.
Restarted app and function resumed as usual.

**Comment by heytherewill** [comment]
👵
