### ISSUE TITLE
Stopped entry/deletion state not updating correctly

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3664]
After updating to 1.13.1 (mnemon hot fix) and experiencing issue #3663 an entry was still running, 
stopped this entry, 
It showed as stopped,
Deleted the entry,
Then a moment later the entry appeared as running still,
Upon attempting to scroll down slightly the app froze.
There were 4 entries on the timer page

**Comment by heytherewill** [comment]
🤷‍♀️
