### ISSUE TITLE
 Improve UX for changing manual/timer modes

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#3672]
### Current state of affairs

Users can currently switch between manual and timer tracking modes in the settings. This will change the default behavior of the ➡️button in the Main Log. However, they can execute the Start in the other mode by long pressing the ➡️button. 

The problem is... many users are not really aware of this.

### Suggestions

We could improve the description in the settings, to include something like: 
> This option sets the default behavior for the start button. Regardless of the current option, long pressing the button will always activate the alternative mode.

We need a better copy, but something along those lines.

The alternative would be to use the new onboarding step, but it may be an overkill at this point. And if you think the long description would clutter the settings too much, we could maybe remove the description (or shorten it) once the user has used the long press once or twice (or whatever). Or not.

**Comment by amulware** [comment]
I'm very much against an onboarding step. Those should be for the most important features, and manual mode is not something we are promoting actively.

I agree with adding a line to the settings though, and also an animation to the start button itself (a circular bar filling up around the button while holding I'm thinking).

**Comment by amulware** [comment]
Why haven't we done this yet? We really should.

I propose:
> You can add your data manually instead of tracking it in real time. You can also long press the start button to use the alternative mode.

Unless someone comes up with something better (ping @maritoggl) I say we go with this.

**Comment by maritoggl** [comment]
This sounds reasonable enough.

**Comment by heytherewill** [comment]
I think this is a good issue for test-weekers. @amulware could you just make it clearer what was decided and what should be implemented?

**Comment by amulware** [comment]
My last comment above goes.

**Comment by semanticer** [comment]
"good issue for test-weekers" caught my eye.  I think I get what should be done, only the part "a circular bar filling up around the button while holding I'm thinking" - do ve need some visual spec for this? I can imagine a solution but don't know if it is the right one :) @amulware

**Comment by amulware** [comment]
I'd skip the animation for now and do just the thing in the settings.

**Comment by kornelijepetak** [comment]
Usually we wait for designs, but they are hard to come by in recent times, so if it doesn't take too much of your time, you can add something on your own and we can peer review. 

Also, it's totally fine to solve one part of the issue (the copy in settings screen) with a PR that closes this issue on a contigency to create another issue that deals only with animation part of it until visuals are specified better.

**Comment by amulware** [comment]
Something like this is what _I_ had in mind. If you feel like implementing this, or you think you got a better idea, don't let us stop you. But like Kornelije said, let's not spend too much time on it.

![IMG_2351](https://user-images.githubusercontent.com/3987892/62211417-4a07c400-b396-11e9-970b-e69f2bf4c624.jpg)

**Comment by semanticer** [comment]
The proposed text is maybe too long. 
> This option sets the default behavior for the start button. Regardless of the current option, long pressing the button will always activate the alternative mode.
It takes 3 rows on average size devices, then we have to make the whole Manual Mode settings row higher and I'm not sure it looks good, but if it's necessary it's possible.

**Comment by semanticer** [comment]
@amulware yeah that's how imagen it too, maybe just start the loading circle on top so the user is able to see immediately that something is happening. The bottom start can be shadowed by the user's finger easily.

**Comment by amulware** [comment]
I thought hiding the start point actually might look better and the user can see it fill around their finger? Otherwise, most of the animation is hidden behind the finger. :D

**Comment by heytherewill** [comment]
Should we implement the animation for 2.3 as well (using the guidelines from this issue + best judgement) or should I move this issue to the next release so we get proper designer specs?

ping @amulware

**Comment by heytherewill** [comment]
Why was this closed? Should't this wait until the animation is implemented?

**Comment by Odrakir** [comment]
It was closed for one simple reason: I was looking at the project view and I intended to close the issue view, not the issue itself and I hit the wrong button. 🤦‍♂
