### ISSUE TITLE
Misbehaving AndroidClientHandler

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#3687]
## 🐛 Bug Report
After #3602, Giskard Https requests stopped working in debug mode.
AndroidClientHandler doesn't seem to trust our certificate.

## Context
#3602 was made to help improve our integration tests. We kind of want it.

## Expected behavior
We should be able to run the app in debug mode.

## To reproduce
Run the app with `AndroidClientHandler` as the `HttpMessageHandler` for the `ApiFactory`.

## Suggestions
Testing can still be done if you replace the `AndroidClientHandler` with `HttpClientHandler`.

**Comment by daividssilverio** [comment]
ref #3686

**Comment by heytherewill** [comment]
🤖
