### ISSUE TITLE
OnePlus3 and OnePlus3T are having issues

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3709]
## ⛑️ User Support
Noticed that several users in Android reviews have been reporting strange issues and are using this device. Not sure if it's because the device is in high circulation or because of device.

I'll investigate this after the GoLoco week.

App version:1.6
Phone OS:8.0
Phone model:OnePlus3, OnePlus3T

**Comment by amulware** [comment]
Please specify 'strange issues'.

Suggestions:
- check how often the device is used on firebase
- check crash numbers for the device on app center

**Comment by amulware** [comment]
:one:➖
