### ISSUE TITLE
Delete button (Swipe) hidden under play button

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3714]
## Context
Need at least a full timer page of entries

Build/Branch: 1.13
Phone OS: 
Phone model: iPhone SE

## Expected behavior
The play button should either not be visible during this action or the page should scroll down further when swiped

## To reproduce
Have a full timer page of entries.
Attempt to delete the last entry by swiping
Delete button is hidden behind the play button.

![img_6146](https://user-images.githubusercontent.com/18132080/48356693-2204f300-e697-11e8-931d-33c1193e3bd3.PNG)

**Comment by amulware** [comment]
For the time being, add more padding to the bottom of the table. If there is no design showcasing this specifically, add exactly so much padding that the distance between the last TE and the play button top equals the distance between the play button bottom and the nav bar top.
