### ISSUE TITLE
Start time view crashes because of invalid stopwatch reference

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3715]
## 💥 Crash Report
This issue happened to me a few times, but not consistently. It happened when I wrote a "long" description and then I held the backspace key until everything was deleted. Then the app crashed.

### 👥 Impact
This happened to me in the 1.14 TestFlight version of the iOS App. But I suppose it also affects the Android 1.7 release. These perf updates haven't been released to the users yet, so this doesn't have a big priority and doesn't have to be fixed asap. Apps for both platforms should be fixed before they are released to the users though - ref #3711, #3712.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/993163f0cfaa5c1356db54496c91828cb9448f3f?appVersion=1.14

### 📝  Exception & Stack Trace
`FirebaseStopwatchProviderIos+IosFirebaseStopwatch.Stop ()`
`System.NullReferenceException: Object reference not set to an instance of an object`
```cs
    FirebaseStopwatchProviderIos+IosFirebaseStopwatch.Stop ()
    BaseStopwatchProvider+SingleUseStopwatch.Stop ()
    StartTimeEntryViewModel.StopSuggestionsRenderingStopwatch ()
    StartTimeEntryViewController.<ViewDidLoad>b__10_49 ()
    StartTimeEntryTableViewSource.WillDisplay (UIKit.UITableView tableView, UIKit.UITableViewCell cell, Foundation.NSIndexPath indexPath)
    (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
    UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
    UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
    Application.Main (System.String[] args)
```

https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/groups/993163f0cfaa5c1356db54496c91828cb9448f3f?appVersion=1.14

**Comment by simonrozsival** [comment]
If you call `FirebaseStopwatchProviderIos.Start()` and `FirebaseStopwatchProviderIos.Stop()` in two parallel threads one after another, the `Stop()` might try to dereference a `null` before the reference was assign in `Start()`. That would cause the crash. Whatever `Performance.StartTrace(Operation.ToString());` does might take quite a few instructions.

Since we do some things with the bg scheduler in the start view, this race condition seems like a plausible explanation. I think we should investigate this more and not to take #3737 as a final fix for the bug.

**Comment by daividssilverio** [comment]
This does not seem to be happening on Android. 1.7 got released to ~18% of the users and no sign of this crash in AppCenter, I can't replicate this as well. This might be because the `AndroidFirebaseStopwatch` creates a trace in the constructor, instead of doing it in the `Start()` as in the `IosFirebaseStopwatch`.

**Comment by daividssilverio** [comment]
Closing this since it's not affecting Android (can't replicate, there are no crash reports, no support issues) and iOS already has a fix for it.
