### ISSUE TITLE
Calendar doesn't observe the local timezone

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3722]
## 🐛 Bug Report
The calendar view doesn't observe the local timezone, thus showing an incorrect day.

## Context

Build/Branch: Daneel 1.13.1
Phone OS: iOS
Phone model:

## Expected behavior
The calendar should observe the local timezone and always show the current day.

## To reproduce
Create some time entries today and tomorrow.
Set the device in a timezone that is already in the next day (e.g: at 13:00 UTC, it's already the next day in GMT+11).
Go to the calendar view.
You shouldn't see any time entries from the previous day and only see the time entries from the current day (in the new timezone).

## Suggestions
Timezones are a mistake, humanity should switch to stardate or something similar or we will never progress.

**Comment by amulware** [comment]
Let's include this in 1.4. I'm assuming this is a one-line fix (and a lot more lines of tests).

**Comment by juanlaube** [comment]
Closed by #3723
