### ISSUE TITLE
Detect timezone on signup

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3724]
And set the timezone as the user's time zone in the preferences, so that reports look correctly from the start.

**Comment by amulware** [comment]
Unless we can send the timezone with the signup request (let's check this), this might not be trivial. We'd need to wait for the preferences to pull, then set the setting and make sure it syncs back up.

**Comment by amulware** [comment]
I think the timezone is part of the user object, so we definitely need to set that after fetching the user with the signup request (and make sure to mark the user object as needs-sync). Might actually not be too difficult to insert the timezone thing at that point.

**Comment by khoi** [comment]
it's possible to send timezone data to the `/signups` endpoint according to https://github.com/toggl/toggl_api_docs/blob/master/chapters/users.md

**Comment by khoi** [comment]
Also for consistency, we should probably follow the implementation of our web client https://github.com/toggl/project-firefly/pull/390

- Fetch supported tz by sending request to `/timezones`
- Try to guess the device timezone
- If the tz is supported, use it, else fall back to UTC
