### ISSUE TITLE
Realm accessed from incorrect thread

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3730]
## 💥 Crash Report
We're accessing Realm on another thread when creating clients as per `SelectClientViewModel+<createClient>d__30.MoveNext ()` in the stacktrace.
https://github.com/toggl/mobileapp/blob/e17e9061b4fb07f3a0304f2d284e438f45833a97/Toggl.Foundation.MvvmCross/ViewModels/SelectClientViewModel.cs#L104-L110

### 👥 Impact
- occurs on 1.6, different devices
- over 200 crashes, 150 users
- accounts for about 5% of crashes

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/769535172u/overview

### 📝  Exception & Stack Trace
`System.Exception: Realm accessed from incorrect thread.`
```cs
NativeException.ThrowIfNecessary (System.Func`2[T,TResult] overrider)
ObjectHandle.TryGetLink (System.IntPtr propertyIndex, Realms.ObjectHandle& objectHandle)
RealmObject.GetObjectValue[T] (System.String propertyName)
RealmClient.get_RealmWorkspace ()
RealmClient.get_Workspace ()
Client.From (Toggl.PrimeRadiant.Models.IDatabaseClient entity)
ClientsDataSource.Convert (Toggl.PrimeRadiant.Models.IDatabaseClient entity)
Select`2+Selector+_[TSource,TResult].OnNext (TSource value)
ExceptionServicesImpl.Rethrow (System.Exception exception)
ExceptionHelpers.ThrowIfNotNull (System.Exception exception)
AsyncSubject`1[T].GetResult ()
SelectClientViewModel+<createClient>d__30.MoveNext ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult ()
MvxAsyncCommandBase+<Execute>d__14.MoveNext ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
```

**Comment by dshr** [comment]
Looks very MVExit-y to me, bc of the `IMvxAsyncCommand`.

**Comment by heytherewill** [comment]
I'm assigning this to @dshr so people don't work on it while he's working on #4013, which will probs close this as well.

**Comment by daividssilverio** [comment]
Can we move this to Giskard 1.11 since #4013 is also there?

**Comment by daividssilverio** [comment]
Ok, this crash isn't happening when creating Clients anymore, at least based on AppCenter.
Realm accessed from incorrect thread is currently happening only in the EditProjectViewModel.
-> https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/503184512u/overview
-> https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3005535668u/overview

But also, it looks like mvx should fix it #3828.

**Comment by kornelijepetak** [comment]
Possible solution to this problem is #4486 which is pending review and #4366 which has been merged. 

Since this issue is somewhat intermittent and not clearly related to any specifics (or better yet, related to many different possible causes), I'd rather close this issue after the above-mentioned PR is merged. And then reopen it if this happens again.

I think this has partly been solved also by one PR some time ago which took care that all the realm queries are enumerated before leaving Realm thread so that there's no cross-thread access anymore to Realm entities.

@simonrozsival might remember more.

**Comment by amulware** [comment]
I'm closing this since as far as I can tell, the original problem is not occurring for 1.11

We'll create new issues for other crashes.
