### ISSUE TITLE
Change Firebase parameter names

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#3736]
Current firebase parameter names for user rating dialogs are not good. They are too vague.

I propose a two-fold change:

1. Add two new parameters with the same values and update the apps with the new parameters
2. Phase out (delete) old parameters when there's only an insignificant number of users on old versions.

Proposed change:
`criterion -> UserRatingDialogTrigger`
`day_count -> UserRatingDialogDelayInDays`

For now, number 1. is already done in code, but as of yet not part of any release.

When we are doing number 2. is completely up to @amulware.

This issue should be closed when BOTH of the points are acted upon.

**Comment by amulware** [comment]
2. can be done as soon as support for 1. is released to ALL users

**Comment by juanlaube** [comment]
Adding to the proposal, can we prefix these values with the platform? Just in case we want to change something just for one of them? This means we need two set of values, but gives us more flexibility to change things (specially when things go wrong).

**Comment by amulware** [comment]
That's not necessary, we can configure different values for a parameter, based on filters such as the platform.

**Comment by juanlaube** [comment]
In that case, please ignore my comment. People at Google are smarter than me 😄

**Comment by kornelijepetak** [comment]
I have updated the Firebase Remote Config params.

When the majority of users update to a version containing #5542, the following parameters should be deleted from FB:

* `day_count`
* `criterion`
* `handle_push_notifications`
* `register_push_notifications_token_with_server`

**Comment by kornelijepetak** [comment]
The old firebase parameters are no more. Rest in peace, firebase parameters!
