### ISSUE TITLE
Schedule background app refresh

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#3761]
Use [Background App Refresh](https://developer.apple.com/documentation/uikit/core_app/managing_your_app_s_life_cycle/preparing_your_app_to_run_in_the_background/updating_your_app_with_background_app_refresh) to be able to run code in background.

We should not sync in bg before the user logs in or signs up. If the app is started and the user is already sign in, we should also start syncing in bg.

**Comment by dshr** [comment]
Closed in #3904
