### ISSUE TITLE
Design suggestion settings

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3782]
This probably requires a separate screen like calendar settings.

Settings we are gonna have:
* Suggestion count. This is can be a cell (row) with a single digit integer, and i think a stepper would be useful (a `+` and `-` button). We have to limit this number between 3 and 9.
* A switch for each type of suggestions, for example, "Most used time entries", "suggestions from calendar". Since we want to discourage users from disabling the suggestions by unchecking all the providers, we have to ensure that at least 1 provider is selected.

**Comment by lizaPlotnikova** [comment]
👋 Hi! I was just playing with the suggestions layout and I mocked up the max. To me, it feels like a few too many. What do you think?
![9 suggestions](https://user-images.githubusercontent.com/24964497/49622940-75a9ea00-f980-11e8-9084-7c2dec703bd4.gif)
