### ISSUE TITLE
Introduce suggestion priorities

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3789]
We need to have a way to order the suggestions. I think the easiest way would be to have an integer priority per suggestion type. Things to consider:
* The priority needs to be persisted. Key value storage is probably most suitable for this.
* The priorities can change depending on the suggestion usage.
  * Suggestion used: priority increases
  * Suggestion dismissed: priority decreases
* The priorities need to be reset after logout

**This PR should** add the persistent storage and a way to increase and decrease the priority for a suggestion type. The priorities need a default (initial) value as well. I think 0 makes sense because that way it can go both: up and down.

**Comment by amulware** [comment]
This needs a very detailed design of the mentioned up/down voting system. How exactly is it going to work? What is the predicted outcome? How will the system account for and correct selection bias and unintended feedback loops (suggestions that show up more often will naturally be used more, hence they will be upvoted even more, etc.)? Will this system reach some sort of stable state or be chaotic? If it reaches a stable state, what will that state look like? If it only ever shows the most use suggestion type to the user, that won't be any good.

Please run this past me before implementing it.

**Comment by arturs105** [comment]
#3807 will be better
