### ISSUE TITLE
Refactor the external usages of the TimeEntries property from ITogglDataSource

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3796]
In our effort to remove the ITogglDataSource, we'll start by removing the dependencies on sub DataSources.
In order for this issue to be considered done, we need to refactor the following use cases to use interactors:

- [ ] GetById #4071 
- [ ] CurrentlyRunningTimeEntry #4072
- [ ] Deleted #4073 
- [ ] Created #4074 
- [ ] Updated #4075 
- [ ] GetAll #4076 

Do note, however, that not all use cases need a counterpart interactor. Some may be merged or not, depending on how the observable is being consumed.

**Comment by amulware** [comment]
Specifically the GetById case is important to me since this was highlighted as a likely problem in #2920
