### ISSUE TITLE
Figure out how to store tags

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#380]
Ref #167

As far as I know (test this) tags can be created by pushing their names when pushing/putting time entries.
The tag ids do not need to be pushed, and backend should return them (new ids for new tags, existing ids for existing tags (test this!)).

There is also an endpoint to fetch a list of all tags. As far as I can tell, these can be used for auto completion, but serve no other purpose.

Regarding storage of tags in PR, I think it would be most efficient to store them in a string, separated by some magic character (which? check with backend if there is a character that cannot occur in tag names, or find some fool proof way to escape). I don't think there is ever any reason to store tag ids on a time entry, since backend does matching on names anyways when we push/put (test/check this as well).

When working on this, consider all the scenarios that can happen with respect to tags.

Ideally, submit findings and proposal before implementation.

**Comment by willsb** [comment]
Realm can't `IList<string>`, but it can `IList<RealmTag>`. This removes the need of storing it as a string with magic separators and them doing `.Split`, which is gross and flaky.

**Comment by simonrozsival** [comment]
I tested the API and it behaves as @amulware wrote in the first paragraph. I am not very sure if there is any need for storing the IDs of the tags, as the names are unique within one workspace.

**Comment by amulware** [comment]
We are going to wait with this until backend changes the endpoints to allow us to treat tags just like any other entity and refer to them by id.
