### ISSUE TITLE
RxFactor the EditDurationViewModel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3827]
[Standard RxFactor rules apply](https://www.notion.so/List-of-Refactors-070744dc374f416eacb0381d72143734#0f425d73fe5343a38a454551e8d26a04)

This view is pretty straightforward, but it's also crucial to the app's core functionality, so make sure to test your changes thoroughly and request my review!

**Comment by amulware** [comment]
I believe this is necessary to implement The Wheel on Android (see: https://github.com/toggl/mobileapp/projects/38).

Please coordinate appropriately.

**Comment by simonrozsival** [comment]
It would be nice if we also renamed the view. The view is used to edit the start time, end time, and duration. Not just duration (which it used to do originally).
