### ISSUE TITLE
RxFactor the EditProjectViewModel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3828]
[Standard RxFactor rules apply](https://www.notion.so/List-of-Refactors-070744dc374f416eacb0381d72143734#0f425d73fe5343a38a454551e8d26a04)

This view is pretty straightforward, but it's also crucial to the app's core functionality, so make sure to test your changes thoroughly and request my review!

**Comment by kornelijepetak** [comment]
Someone forgot to unassign themselves before the vacations... 👎
