### ISSUE TITLE
RxFactor the EditTimeEntryViewModel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3829]
[Standard RxFactor rules apply](https://www.notion.so/List-of-Refactors-070744dc374f416eacb0381d72143734#0f425d73fe5343a38a454551e8d26a04)

This View has some obsolete members and is full of complex triggers that rely on the `INotifyPropertyChanged`, so extra care is required.

**Comment by amulware** [comment]
Please take into account https://github.com/toggl/mobileapp/issues/4252

**Comment by kornelijepetak** [comment]
This is being completed as part of the 🔟 (Grouped Time Entries project).

Resolved by
#4407 
#4438 
and another PR which will be submitted today (for iOS).
I will update this issue when it's done.

**Comment by simonrozsival** [comment]
This issue was implemented and merged into the GTEs project. I'm closing it now.
