### ISSUE TITLE
RxFactor the StartTimeEntryViewModel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3830]
[Standard RxFactor rules apply](https://www.notion.so/List-of-Refactors-070744dc374f416eacb0381d72143734#0f425d73fe5343a38a454551e8d26a04)

This is by far the hardest ViewModel to RxFactor and it also happens to be the single most important view in the app, so tread (and thread) carefully.

Also, instead of trying to rewrite bits and pieces of the ViewModel, I think it'd be simpler to start a fresh new ViewModel and reuse the tests, like we did with the LoginViewModel and the TimeEntriesViewModel.

**Comment by amulware** [comment]
Please take into account https://github.com/toggl/mobileapp/issues/4251

**Comment by arturs105** [comment]
Since we share some components between this view and the project selection view, there might be some useful things in #4372.
