### ISSUE TITLE
Make sure suggestion certainties are balanced

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#3854]
We have to make sure that all the suggestion providers are "on the same page" regarding certainties -we can't have one provider generating suggestions with 20% - 30% certainties and another one with 60% - 80% range.

**Comment by sofokli1** [comment]
How is this issue going? Is PR `Check and remove duplicate suggestions` #4046 even needed if we are taking into account @simonrozsival comment about using duplication as score boost? I am asking if that is going to be implemented here or is it going to be a separate issue to be implemented after this is done.

**Comment by arturs105** [comment]
Stale issue is stale
