### ISSUE TITLE
Test Country Selection in Signup:

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3861]
Add test that tests country selection on signup page.
Will need to
-Navigate to signup page
-Test country selection by selecting country (this can be typed)
-Test back button to exit country selection
-Do both return to signup page with correct country selected? (Is it even possible to check this)

**Comment by daividssilverio** [comment]
I didn't understand what you meant here:
> Do both return to signup page with correct country selected?

**Comment by ApocalypticFish** [comment]
When you click on the country, does it close the country selection window

**Comment by daividssilverio** [comment]
Yeah, it does.

**Comment by ApocalypticFish** [comment]
So the test will fail if it doesn't properly

**Comment by daividssilverio** [comment]
Oh, that's what you meant. That's possible to check, yeah.
