### ISSUE TITLE
Users unable to login after updating to Daneel 1.14

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#3865]
## 🐛 Bug Report
Some users were logged out and unable to login again after updating from an old version to Daneel 1.14. This problem is caused by accessing a non-existent dynamic property in a database migration.

## Context
Build/Branch: Daneel 1.14 (maybe Giskard 1.7 too?)
Phone OS:
Phone model:

## Expected behavior
Users shouldn't be logged out after updating.

## To reproduce
Update from Daneel 1.8 to Daneel 1.14.

**Comment by simonrozsival** [comment]
I believe this is now resolved.

**Comment by juanlaube** [comment]
Yes, this was resolved in Daneel 1.14.2
