### ISSUE TITLE
Create .strings files for Daneel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3872]
As it currently stands, all UI strings that do not come from Foundation are hardcoded in Daneel's .xib/.storyboard files. We got to change that.

The first step is to go in every .xib/.storyboard file and extract all of its strings into a `.strings` file which we can later be translated. [This article](https://medium.com/@mario.negro.martin/easy-xib-and-storyboard-localization-b2794c69c9db) can be of help if you're not familiar with this process.

**Comment by khoi** [comment]
since no PR is required for this issue.
I've marked this issue directly as `pending-review` so it will get proper attention.

**Comment by simonrozsival** [comment]
I don't understand why there's no PR necessary for this issue? Shouldn't the `.strings` files be in the repository? Shouldn't there be at least a `.sh` script which would contain the `find` command with all the arguments or something like that?

**Comment by heytherewill** [comment]
While I wanna hug you for the effort of having a script, it's not really what we want.

We need to have a centralized `.strings` file with meaningful names that can help translators. These identifiers are not really useful in giving context to translators. We need something like [what we have on android](https://github.com/toggl/mobileapp/blob/develop/Toggl.Giskard/Resources/values/Strings.xml)
