### ISSUE TITLE
Extract iOS code string literals

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3873]
In order to progress the work in the upcoming 

Extract the following string literals from `.cs` files into resources inside `Foundation`:
- CreateClientViewCell: line 26
- IntentDonationServiceIos.cs: lines 17~19 [?]

[?] - Is it that simple to make siri multi-lingual? If it is not as simple as suggesting a different sentence, we should not touch these literals. ping @Odrakir here

Note that this is only the work needed for the code part. The interface part is much more complex and it's described in #3872

**Comment by Odrakir** [comment]
So, we are using `Resources.resx` for strings and that file will get a version for every language when we translate the app, right?

In that case... Is there any formal way of doing string interpolation?

For example, the string "Create client [CLIENT_NAME]" might have the client name somewhere else in other languages.
