### ISSUE TITLE
Rename api error response message

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#3877]
It was agreed internally that the future format of error messages will be as follows.
```
{
  "error_code" : "FAILED_TO_DO_STUFF(format of codes is TBD)",
  "error_message" : "Stuff failed due to 2 being smaller than 5 (this message could be shown to the user if no localised message is available)",
  "parameters" : {
    "number1" : 2,
    "number2" : 5
  }
}
```

For minimal forwards compatibility, we need to ensure the message property in `ResponseError` is parsed correctly.
https://github.com/toggl/mobileapp/blob/develop/Toggl.Ultrawave/Models/ResponseError.cs#L1-L9

We could either add a Json.Net attribute to make it parse from `error_message` or if snake-case parsing works correctly, we could rename the property itself to `ErrorMessage`.

I'll leave that up to you. In either case, just make sure (test if we don't do so yet) that once we get error messages of the format above the message property will parse correctly.

We can add the other properties down the line, when they become necessary.

**Comment by juanlaube** [comment]
@amulware is renaming enough? I think backend is sending error messages as JSON with the key "message" right now. Renaming means we will ignore that key and use the default message we pass in the ApiException constructor.

**Comment by amulware** [comment]
To my knowledge backend isn't sending any json errors for any endpoints.
