### ISSUE TITLE
Clean up the dependencies from UserAccessManager

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#3885]
🔑 Related to `user-access-improvements` project.

Currently, the `UserAccessManager` depends on
* `IApiFactory`
* `ITogglDatabase`
* `IGoogleService`
* `IApplicationShortcutCreator`
* `IPrivateSharedStorageService`
* `Func<ITogglApi, ITogglDataSource>`

Some of those dependencies should not be there. 

To solve this issue, remove dependencies on the following:

#### `IApplicationShortcutCreator` and `Func<ITogglApi, ITogglDataSource>`

The `createDataSource` delegate is currently only used to get the data source for the `ApplicationShortcutCreator`. Instead of these dependencies, the two observables of `UserAccessManager`, namely `UserLoggedIn` and `UserLoggedOut` should be used by `ApplicationShortcutCreator` in order to turn on and off the app shortcuts so that the authorization manager has nothing to do with app shortcuts.

#### `IPrivateSharedStorageService` 
This dependency can be removed by subscribing the storage service to the newly exposed `LoginManager.UserLoggedIn`, as suggested in previous point.

_From what I've found out in discussions, the private shared storage is needed for Siri to work properly._

#### **Precursors:**
Doing #3884 first will make the merge of this issue much easier.

**Comment by khoi** [comment]
you mean `UserAuthenticationManager` 🤔

**Comment by kornelijepetak** [comment]
After several attempts to declutter the dependencies, it is clear that it's impossible to remove them without changing too much 🔑-unrelated things.

Because of future plans to refactor the way dependencies are being set up, for now I will have to leave the UAM as it is. Unfortunatelly, the scope creep of this issue is too high.
