### ISSUE TITLE
Login/Signup abstractions into login/signup providers

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#3886]
🔑 Related to `user-access-improvements` project.

Many of the steps we are taking during the authentication process are the same, regardless of the mode of the authentication. It makes sense to turn this into the meaningful abstractions.

* Abstract the login step into a `ILoginProvider` and create two implementations:
	* `EmailAndPasswordLoginProvider` 
	* `GoogleLoginProvider`
* Abstract the signup step into a `ISignupProvider` and create two implementations:
	* `EmailAndPasswordSignupProvider` 
	* `GoogleSignupProvider`

Then, use those abstractions in the `UserAccessManager`.

#### **Precursors:**
Doing #3884 first will make the merge of this issue much easier.

**Comment by khoi** [comment]
unassigning myself as this PR provides a little benefit for now. will probably revisit it later

**Comment by kornelijepetak** [comment]
With talks about how to structure the app dependencies and interactors, I believe this issue is no longer valid.
