### ISSUE TITLE
Rename `Toggl.Foundation.Sync.Test` for consistency

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3913]
If we look at the way we do naming, the project should be called `Toggl.Foundation.Tests.Sync` instead of its current naming

**Comment by simonrozsival** [comment]
I understand this issue and I have a related idea: what if we moved the syncing logic into a Toggl.Sync project and the tests into Toggl.Sync.Tests?

**Comment by heytherewill** [comment]
I wouldn't mind that, but that can only happen once we break the cyclic dependency between `ITogglDataSource` and `ISyncManager`
