### ISSUE TITLE
Add mobile app specific documentation

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#395]
I'll use this issue for reminding me to document some things that might be a bit cryptic or that only exist in my head:

- [ ] Toggl's linker strategy
- [x] Cake's variable replacement
- [x] Certificate for staging (this one needs docs, specially on the iPhone)

**Comment by amulware** [comment]
While we're at it:

- [ ] iPhoneX UI guide (what to take into account, now that we live in a notched world)

**Comment by amulware** [comment]
This has been stale for too long.
