### ISSUE TITLE
Test signup with an invalid email address

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#3950]
Test signup with an email address that already exists in the database to ensure that the error displays correctly.
-Navigate to the signup page
-enter an existing email address into the signup field and password
-signup
-error

Test that it's possible to sign up with a valid email address after this.
-Navigate to the signup page
-enter an existing email address into the signup field and password
-signup
-error
-clear email field
-enter non-existing email
-success

**Comment by daividssilverio** [comment]
If you add a space before the beginning of your bullet points, they become bullet points.
Like this:
- Navigate...
- enter...

**Comment by daividssilverio** [comment]
By the way, I think those are already covered by existing tests. You might wanna run them and confirm if they are testing what you were expecting.

**Comment by daividssilverio** [comment]
Another point: The Login/SignUp screen is being revamped, so we'll need to rewrite the tests there and you might want to rewrite the specs for the those tests.

**Comment by dshr** [comment]
Already present, closing this.
