### ISSUE TITLE
Use environmental variables for user agent in API integration tests

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#396]
This would allow us to simplify the cake script, and allow us to easily run individual tests from within the IDE.

**Comment by willsb** [comment]
I don't see the reason why. The good thing about the hash is that it point us to the exact commit that caused the problem, making it simpler to track down whether the problem was the API or the client. And how will using Env Vars allow for tests to be ran from the IDE? You'll still need variable replacement.

**Comment by amulware** [comment]
I doubt that we'll ever actually get that hash from the backend in some way, but even if: We can still stick the hash into the env variable in cake.

The reason the tests fail from the IDE right now is that the replacement string is not a valid user agent. If every test would just get the environmental variable when constructing the user agent, that would solve that without changes to the code we don't want to commit.

**Comment by willsb** [comment]
Oh, I see what you mean now. If we're using Env Vars during runtime, we might just go all in and use them in the UI tests as well, then.

**Comment by amulware** [comment]
But don't the UI tests run on the phone? i.e. a different device with different environmental variables?

**Comment by willsb** [comment]
I believe that the dll that controls the test does not run on the phone, but we'll have to test

**Comment by amulware** [comment]
Not necessary for the time being, though if anyone wants to pick this up in the future if it still makes sense, feel free.
