### ISSUE TITLE
Investigate Search Ads attribution API

### ISSUE THREAD

**Issue by djalex15** [toggl/mobileapp#3991]
This is about potentially adding a Search Ads attribution API to our iOS app, so we could:
- Get more numbers once we start doing them during Q1 (with the SA specialist)
- See which keywords are performing the best and bringing signups
- See which keywords bring users that have a good retention rate (7 & 28 days)
- More data!*

* This API provides more data that can potentially be integrated with an MMP partner, like [Adjust](https://www.adjust.com/), allowing for an insight into some data that Apple doesn't share on its own through Search Ads.

------

Things to do:

- [x] Investigate how much of a problem would be (and how much time would it take) to integrate this in our iOS app
- [x] Investigate will this somehow bloat the app (like the Facebook SDK)
- [x] Check if it's possible to gather and preview/use this data on our own or would we need to integrate with some 3rd party (Adjust, Appsflyer)? Is Firebase integration possible?

Useful links:
1. https://searchads.apple.com/advanced/help/measure-results/#attribution-api
2. https://searchads.apple.com/v/advanced/help/b/docs/pdf/attribution-api.pdf

**Comment by amulware** [comment]
@djalex15 When is this needed?

**Comment by djalex15** [comment]
The earlier, the better / preferably early January 🙏

**Comment by amulware** [comment]
Also please post below what data this gathers about our users (and who has access to it) and give an overview of how to implement this technically.

**Comment by simonrozsival** [comment]
So I did the research and this is what I found out:

Getting the information from Apple is very easy with the Xamarin integration:

```csharp
using iAd;
...
var attribution = await ADClient.SharedClient.RequestAttributionDetailsAsync(); // we also need to handle errors which might occur in some cases ofc
```
We don't need to add any new `NuGet` packages to the app and it just works. It will increase the size of the app, but we're talking about a few `kB`s. This is not a problem at all.

For docs check this page: https://developer.xamarin.com/api/type/iAd.ADClient/

This gives us a `NSDictionary` with 16 keys and values like this:
```
{
    "Version3.1" =     {
        "iad-adgroup-id" = 1234567890;
        "iad-adgroup-name" = AdGroupName;
        "iad-attribution" = true;
        "iad-campaign-id" = 1234567890;
        "iad-campaign-name" = CampaignName;
        "iad-click-date" = "2019-01-03T10:00:40Z";
        "iad-conversion-date" = "2019-01-03T10:00:40Z";
        "iad-conversion-type" = Download;
        "iad-creativeset-id" = 1234567890;
        "iad-creativeset-name" = CreativeSetName;
        "iad-keyword" = Keyword;
        "iad-keyword-matchtype" = Broad;
        "iad-lineitem-id" = 1234567890;
        "iad-lineitem-name" = LineName;
        "iad-org-name" = OrgName;
        "iad-purchase-date" = "2019-01-03T10:00:40Z";
    };
}
```
It's up to us what to do with the data then. We can ask backend to create an endpoint for us which will gather this data and give you a big CSV with all the information and we could analyze it ourselves somehow.

The other option is to integrate this with a tool which would do this for us. I checked the Adjust app and they support Xamarin, so it should be possible ("easy") to integrate it as well - see https://github.com/adjust/xamarin_sdk

**Comment by amulware** [comment]
I take it none of the tools we already use support this? (firebase/app center)

**Comment by amulware** [comment]
That's a lot of MBs. Leaving this for review by @djalex15. Please advise if further efforts are necessary.

**Comment by simonrozsival** [comment]
I’m closing this issue for now and @djalex15 will reopen it or create a new issue once the Traffic team has concrete requirements/specifications.
