### ISSUE TITLE
Document how we should use strings in our app

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#3996]
We're doing some groundwork to allow for our apps to be fully translatable in the future. The very fact that we need to do some groundwork shows that not everyone is following each platform's guidelines on how to work with strings in order to make the app simpler to translate.

We need to write some documentation on what needs to be done to keep the app in a translatable state.

**Comment by khoi** [comment]
# i18n for iOS

## Approaches

### Mono Based Approach

Using `RESX files` in `System.Resources` and `System.Globalization` namespaces.

#### Pros

- Less boilerplate code
- Strongly typed access to the translations.
- The RESx files are shared across platforms.

#### Cons

- May not be able to support all native language/region combinations

```
For example, setting an iPhone’s language to English and its region to Spain will cause the following APIs to yield different values:

CurrentThead.CurrentCulture: en-US (Mono API)
CurrentThread.CurrentUICulture: en-US (Mono API)
NSLocale.CurrentLocale.LocaleIdentifier: en_ES (Apple API)

Mono-based localization (for example, with .resx files) may not yield expected results for these language/region combinations. In these situations, rely on Apple's APIs to localize as necessary.

Excerpt from: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/
```

- Images still need to be handled in a platform-specific way.

#### What need to be done?

- Create a new `Resources.rex` file in `Foundation` for each supported language with the translated text.

```
Resources.fr.resx - French language translations.
Resources.es.resx - Spanish language translations.
Resources.de.resx - German language translations.
Resources.ja.resx - Japanese language translations.
... etc
```

- Create `ILocalize` service in `Foundation` 

```
public interface ILocalize
{
    CultureInfo GetCurrentCultureInfo ();
    void SetLocale (CultureInfo ci);
}
```

- Implement platform specific `ILocalize` classes to get the locale and feed the info to Mono. Refer to [Platform Specific Code](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=macos#platform-specific-code).

#### How should we use strings in Daneel

- From now on, all the text that are set using Interface Builder (.xib, .storyboard) has to be added to the `Resources.resx` files and overrode in `ViewDidLoad`

```
public override void ViewDidLoad()
{
	LoginLabel.Text = Resources.Login
}
```

### Native iOS SDK approach

Use native iOS `.strings` files and `NSBundle.MainBundle.GetLocalizedString` to lookup localized text.

#### Pros

- It's the native way of doing localizations, so it can cover everything from text to images. 
- Support localizing in interface builders UI directly.

*Localizing interface builder directly will introduce new strings files for each xib, storyboard file. And these files are not automatically updated when you change the interface. So doing this is highly encouraged.*

#### Cons

- Have to maintain iOS `.strings` files as well as `Resources.resx` and possibly Android's ones as well.
- Can cause discrepancy in translations.

#### What need to be done

- Create a new `.strings` file for each language with the translated text.
- Update `Resources.SomeText` to use `NSBundle.MainBundle.GetLocalizedString` 


#### How should we use strings in Daneel?

- in `ViewDidLoad` of each ViewController set the text for each UI element

```
LoginLabel.Text = NSBundle.MainBundle.GetLocalizedString("LoginKey", "Login")
```

**Comment by khoi** [comment]
IMO, I'm leaning towards the first option for a couple of reasons:

- We're already using `Resources.resx` files
- Less strings to maintain

**Comment by dshr** [comment]
+1 for option 1. We don't have any localise-able images in the app (as of now though), so we'd only have to support the `resx` files.

**Comment by simonrozsival** [comment]
I like the way .NET handles localization/globalization. The autogenerated `Resources` class is a cool thing. We can't build the app with an incorrect identifier of a string. So having the possibility to use it seems nice.

I don't think we should have shared localization resources. Android and iOS should have their own set of strings even if there is a (significant) overlap.

It should be fairly easy to switch between the two if we find out that it doesn't work well for us, right? Both of the `.resx` and `.strings` are just key-value formats, one is XML and one is plaintext... but a single regex should convert between the two. The same should be true for changing the code from one to the other. If there's no catch I'm not seeing now, I would start with the .NET approach and switch to the native variant only if we run into some issues.

If we do that, we should add more information to the feedback API call - at least the values of `CurrentThead.CurrentCulture`, `CurrentThread.CurrentUICulture`, and `NSLocale.CurrentLocale.LocaleIdentifier`. That could be helpful if the user compains that we claim to support his/her language and he is stuck with English.

**Comment by khoi** [comment]
> I don't think we should have shared localization resources. Android and iOS should have their own set of strings even if there is a (significant) overlap.

what do you think about having sharing a single Resources file, and using different keys for each platform if the translation diverse? 

```
<data name="iOSLoginButtonTitle">
	<value>Apple</value>
</data>
<data name="AndroidLoginButtonTitle">
	<value>Orange</value>
</data>
```

I want to have as fewer files as possible, since as the translations grow, it takes an effort to keep all the translation files in sync if done manually.

**Comment by simonrozsival** [comment]
I don’t like prefixes/suffixes.

**Comment by heytherewill** [comment]
I'm with @simonrozsival on this one. We should have a mix of both, having shared translations for shared resources but also leveraging the native capabilities for UI specific things (like `@string/blah` on Android and `.strings` files on iOS), which will help us *a lot* when it comes to things like testing the UI for different languages

**Comment by khoi** [comment]
beside having a shared `Resources.resx` file, do you want to

- have a global `strings` file for iOS and set the interface builder files' strings in `ViewDidLoad`
- or have a global `strings` and also a `strings` file dedicated for each `xib`, `storyboard`?

**Comment by khoi** [comment]
after discussion with @heytherewill, we agreed to use a single shared `Resources.resx` for both platforms. 

and if the translation ios and android, we could provide different keys for the strings.
