### ISSUE TITLE
RxFactor the SelectTimeViewModel

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4014]
Check #3352 for details

**Comment by heytherewill** [comment]
I think this too is probably not necessary because of the wheel

Pinging both @amulware and @daividssilverio

**Comment by heytherewill** [comment]
If this indeed is not needed, please use this issue as a reminder to 🔥 this ViewModel and all of its strings/assets/what-not

**Comment by juanlaube** [comment]
I asked @daividssilverio and The Wheel ™️ will actually replace the `SelectTimeViewModel` so there's no need to rxfactor this, however we should delete everything related to that view model and the corresponding fragment after The Wheel is ready.

**Comment by simonrozsival** [comment]
I believe we should remove this from the Daneel release project then, @amulware.

**Comment by kornelijepetak** [comment]
I confirm that with the integration of the Wheel-based viewmodel, this view model and all it's brothers and sisters can be 🔥d.

**Comment by kornelijepetak** [comment]
I have assigned myself so that I will close the issue once this is wiped out.
