### ISSUE TITLE
Calendar: Allow snapping to other TEs

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4032]
When:

- moving a TE
- adjusting a TE starting
- adjusting a TE end time

I think it should not only snap to regular intervals, but also to the start/end of other TEs (start only snaps to end, end only to start).

This allows use-cases like:

"I forgot to start my TE right after the last one, and want to move the start time to the previous TEs end time"

Other thoughts very welcome, especially if there are ways in which this could harm UX.

**Comment by sofokli1** [comment]
I made a PR but didn't make the 
> start only snaps to end, end only to start
To me it made more sense to allow the user the freedom to snap to all possible time of interest to allow cases like:
Move start time to same start as `other entry` and delete the `other entry`.
Same can be said about end but in reverse.
Also it feels way more consistent like this IMHO.
@amulware if you have time, give a try and let me know if I should go back to `start only snaps to end, end only to start`

**Comment by amulware** [comment]
I see your reasoning. I don't know when I have the time to look at it, but I'm alright with leaving it that way, if whoever tests and reviews finds no issues with it. :)
