### ISSUE TITLE
Calendar: Fix text alignment and scaling

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4033]
The text on calendar events and Time entries often doesn't feel quite right and isn't aligned properly.

Sometimes it scales strangely as well.

The text should always be aligned well, and be maximum size if possible, and only scale if necessary.

**Comment by simonrozsival** [comment]
Can you show some examples with screenshots? I don't know what "often doesn't feel quite right" looks like and I can't spot it myself :)
