### ISSUE TITLE
Fix leaky onboarding leaky windows 

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4035]
I was testing the background sync and realized we are leaking the popup windows when we go into background while a popup is visible. 

This should be as easy as dismissing the popups when the activity goes into background.
This has to be fixed on all the activities that show a window popup.

A leak warning is shown when you have a leak:
```
android.view.WindowLeaked: Activity md5a44fea7db10133e9f6bddee3bde9d640.MainActivity has lea
                            ked window android.widget.PopupWindow$PopupDecorView{8f03aae V.E...... ......I. 0,0-547,172}
                             that was originally added here
                         E      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
                         E      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
                         E      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                         E      at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
                         E      at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
                         E      at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1069)
                         E      at mono.java.lang.RunnableImplementor.n_run(Native Method)
                         E      at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
                         E      at android.os.Handler.handleCallback(Handler.java:739)
                         E      at android.os.Handler.dispatchMessage(Handler.java:95)
                         E      at android.os.Looper.loop(Looper.java:148)
                         E      at android.app.ActivityThread.main(ActivityThread.java:5417)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Get rid of those and you don't have any more leaks 👍 

Why? We don't want our app to be holding references it doesn't need, we need to free resources when we are not using them anymore, let's be good neighbours to other applications.

**Comment by semanticer** [comment]
I'm having a hard time reproducing this. Is there a particular chain of actions that reliably produces this leak?

**Comment by semanticer** [comment]
I attempted to solve it blindly in the pull request #5699 
But in general, I think things like these should be more foolproof and shouldn't rely on the developer's memory and short attention span :) We can leverage the Lifecycle library for this purpose.

**Comment by daividssilverio** [comment]
@semanticer 
> I'm having a hard time reproducing this. Is there a particular chain of actions that reliably produces this leak?
Yeah, were able to see the pop windows at least? If you didn't, you can make them appear by searching for the right `*OnboardingStep`, and change condition for it to appear to always be true.
When you can see them, all you have to do is to put the app in background, move between screens, that kind sort of stuff.
