### ISSUE TITLE
Never ask for more than two months of history with `since` parameters

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#405]
Instead, consider just getting all entities instead in that case.

We also have to check how much data we actually get in the case of time entries and consider instead of 'all' getting the last ~6 weeks to make sure we have data to show, and to complete and suggest from.

**Comment by amulware** [comment]
Background: API will fail when asking for >3 months ago. Let's stay clear of that limit.

**Comment by simonrozsival** [comment]
I asked #backend and found out this: 

- By default we get 10 days of data
- We shouldn't ever ask for more than ~10 days and use detailed reports instead

I am not sure if detailed reports help us. I will wait with this issue until you come back and we can discuss it more.
