### ISSUE TITLE
Add total tracked time to Calendar View

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4052]
I'd like to use the Calendar more, but I find myself missing the total number of tracked hours a lot.

If there are arguments not to add that, please explain below.

**Comment by simonrozsival** [comment]
I think it's a good idea to add the total time. But how should it look like? Is that up to the dev who implements this?

**Comment by amulware** [comment]
My intuition says to add a thin header showing the total time, and maybe 'today' or the date or something, but that should be confirmed with a designer.

In either case, as discussed in the PR above, we should probably include the running time entry in this total as well, since it is displayed in the calendar, and since this view is similar to the 'today' timeline header on the webapp timer page.

**Comment by amulware** [comment]
Actually, we could maybe just use the already existing bar at the top, and show this instead of the Toggl logo? (similar to how we show the date selection in reports)

**Comment by lizaPlotnikova** [comment]
Seems reasonable. (sorry after all the pinging yesterday I still didn't look at it :P) Can you send a screenshot of what you have?

**Comment by simonrozsival** [comment]
We don't display the total tracked time anywhere atm and I only wrote some code which calculates the time we should display.

**Comment by simonrozsival** [comment]
Does this look OK?

![image](https://user-images.githubusercontent.com/374616/51317604-4fd03480-1a58-11e9-8585-5342fd2a4659.png)

And for running TE:
![image](https://user-images.githubusercontent.com/374616/51317652-71c9b700-1a58-11e9-90f0-1f20346b0ec3.png)
