### ISSUE TITLE
Fix RealmConstructors.tt and other generators

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#409]
The generator generates code that does not compile at the moment.

- [x] _RealmConstructors.tt_ assumes that everything ending with `Id` is a reference to a different entity and it will try to load that entity. This fails for `IWorkspaceFeature` and the enum `WorkspaceFeatureId`. The easiest solution would be to remove the `Id` suffix from this specific property.
- [x] _RealmConstructors.tt_ assumes that every model should have an `Id` property
- [x] _RealmConstructors.tt_ assumes that every Multivac model has corresponding Prime Radiant `IDatabase...` interface
- [x] _RealmConstructors.tt_ assumes that every property of the Multivac model interface will have also a setter defined in the concrete class. This fails in some cases - especially for lists.
- [x] _FoundationModels.tt_ does not have using for `Toggl.Multivace.Models`. This is a problem for entities which contain list of other entities (`IWorkspaceFeature` - `IWorkspaceFeatureCollection`)

**Comment by amulware** [comment]
Please see if any of this still applies.

**Comment by simonrozsival** [comment]
All of these sub-issues were already resolved and so I close this issue.
