### ISSUE TITLE
Show loading animation when loading suggestions in start view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4098]
We made this properly async (and potentially throttled it?) which makes the view respond much faster, but sometimes it takes up to a second for me to load project suggestions, and I get confused for a moment why my project isn't showing up even though I thought I typed in a valid search string. I then go to correct it which makes the project take even longer to show up, or not show up at all if I delete too much text.

Just adding a loading spinner or similar that's visible any time that it's busy running a search in the background would prevent this I think. This should be visible no matter which kind of search it is running, just to make it clear that it is busy.

I'm not sure if Android has the same issue. Can someone check that out and create an issue if it does?

**Comment by Odrakir** [comment]
This should be done after #4012
