### ISSUE TITLE
Track Siri actions under regular events

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4107]
We currently have separate events for tracking Siri Start and Stop events. I see no reasons why these should exist. Instead, we should track these under the existing Start/Stop events to make the data easier to evaluate.

**Comment by Odrakir** [comment]
While we are working on this: Is there a way to know where the intent was launched from? If it was spoken to Siri or through Spotlight suggestions for example... ¿?

**Comment by khoi** [comment]
>While we are working on this: Is there a way to know where the intent was launched from? If it was spoken to Siri or through Spotlight suggestions for example... ¿?

This is possible since they're processed differently

- with voice, it goes through the IntentHandler
- tapping through Spotlight suggestion goes through a deep link in AppDelegate

We're currently NOT counted "invoking through Spotlight" as Siri events, should we? @Odrakir

**Comment by Odrakir** [comment]
I think we definitely should, yeah. Probably same deal as this one with a different TimeEntryStartOrigin.

Do you want to do it here or in a new issue?

**Comment by khoi** [comment]
@Odrakir let's create a new issue for it

**Comment by khoi** [comment]
issue created https://github.com/toggl/mobileapp/issues/4530
