### ISSUE TITLE
Setting language to Thai causes app to crash

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#4116]
## 🐛 Bug Report
When an iPhone's language to set to Thai, the app starts crashing

## Context
Build/Branch: Daneel 1.14.2
Phone OS: iOS 12
Phone model: iPhone 8 Plus
[Conversation](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100764/conversations/20304554539)

## Expected behavior
The app should continue working properly regardless of what language the device is set to.

## To reproduce
1. Go to iPhone Settings > Language & Region > iPhone Language
2. Select Thai
3. Go to home screen, and try to launch app
4. See app freeze on logo screen

## Suggestions
Current workaround: set iPhone language to English

Might be similar to https://github.com/toggl/mobileapp/issues/3367?

**Comment by simonrozsival** [comment]
```
System.ArgumentOutOfRangeException: Not a valid calendar for the given culture.
```

The problem occurs in `TimeSpanExtensions.convertToImprovedFormat`.
