### ISSUE TITLE
Add UI tests based on this testing template.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4128]
Mark tests that exist as completed on this issue.
Mark tests that have issues as completed as well.

Create issues for tests which don't exist.

Then test the existing tests and create issues where appropriate.

## Testing sign in area ##

- [x] Test standard email and password sign in
- [x] Test standard email and password sign in with invalid email address
- [x] Test standard email and password sign in with invalid password
- [x] Test signup with standard email and password
- [x] Test terms and conditions link
- [x] Test privacy policy link
- [x] Test signin with Google signin
- [x] Test signup with Google signin
- [x] Test forgotten password link
- [x] Test forgotten password link with invalid email
- [x] Is country selection automatically selecting the right country?
- [x] Is country selection allowing manual selection
- [x] Test email field with invalid email
- [x] Test email field with mixed character sets (including various languages)
- [x] Test password field for old/changed password

## Testing timer page
- [x] Start timer
- [x] Stop timer
- [x] Enter description
- [x] Add new project
- [x] Add new client
- [x] Add new tag
- [x] Add long description and confirm character limit error shows
- [x] Add new project using existing client
- [x] Add existing project
- [x] Add existing tag
- [x] Start new timer, select no project, stop
- [x] Create new manual time entry
- [x] Start a new entry, add multiple tags.
- [x] Start a new entry, discard new entry.
- [x] Continue an entry
- [x] Delete an entry

## Testing editing time entry
- [x] Change description
- [x] Change project
- [x] Remove project
- [x] Change tags
- [x] Remove tags
- [ ] Change start time with the barrel/manual selection
- [ ] Change start time with the wheel
- [ ] Change end time with barrel/manual selection
- [ ] Change start date
- [ ] Change end date
- [ ] Change duration
- [ ] Change date from main entry page
- [ ] Discard changes to entry
- [ ] Delete entry from edit view
- [ ] Confirm changes
- [ ] Create new project from edit view
- [ ] Create new client from edit view
- [ ] Create new tag from edit view

## Testing report screen
- [ ] Custom range
- [ ] Is correct data displayed
- [ ] Are categories displaying correct timerframe and dates?
- [ ] Is web displaying the same data?
- [ ] Today
- [ ] Yesterday
- [ ] This year
- [ ] This month
- [ ] Last month
- [ ] This week
- [ ] Last week
- [ ] Custom range 1 year
- [ ] Custom range 1 month
- [ ] Custom range 1 week
- [ ] Custom range 1 day
- [ ] Ensure correct year is selected on all options
- [ ] Change workspaces

## Testing settings page
- [ ] Sign out normal email
- [ ] Sign out google sign in
- [ ] Change workspace
- [ ] Date format MM/DD/YYYY
- [ ] Date format DD-MM-YYYY
- [ ] Date format MM-DD-YYYY
- [ ] Date format YYYY-MM-DD
- [ ] Date format DD/MM/YYYY
- [ ] Date format DD.MM.YYYY
- [ ] 24 hour time format
- [ ] 12 hour format
- [ ] Duration format Classic
- [ ] Duration format Improved
- [ ] Duration format Decimal
- [ ] First day of the week Monday
- [ ] First day of the week Tuesday
- [ ] First day of the week Wednesday
- [ ] First day of the week Thursday
- [ ] First day of the week Friday
- [ ] First day of the week Saturday
- [ ] First day of the week Sunday
- [ ] Manual mode
- [ ] Submit feedback
- [ ] About
- [ ] Help
- [ ] Is "Synced" displaying correctly?

## Testing Calendar Integration
- [ ] Are calendar entries showing correctly?
- [ ] Create an entry from a calendar entry
- [ ] Adjust the start time
- [ ] Adjust the end time

## Testing Siri Integration
- [ ] Start a time entry
- [ ] Stop a time entry

## Multiple Workspaces
- [ ] Switch workspaces
- [ ] Go offline then switch workspaces (Airplane mode)
- [ ] Switch between workspaces while timer running
- [ ] Is data displaying correctly in web?
- [ ] Force sync then switch
- [ ] Leave a workspace
- [ ] Be removed from a workspace while offline
- [ ] Be removed from a workspace with an active entry running

## Testing Interactions/Sync between this app and others
- [ ] Edit client on web whilst mobile online
- [ ] Delete client on web whilst mobile online and tracking a task
- [ ] Edit client on web whilst mobile online and tracking a task
- [ ] Tags
- [ ] Archiving
- [ ] Create new project on web whilst mobile offline
- [ ] Tasks
- [ ] Try creating new entries on web whilst mobile offline
- [ ] Edit client on web whilst mobile offline
- [ ] Try stopping timer on web while mobile offline
- [ ] Delete project on web whilst mobile offline
- [ ] Make changes to projects on web

## Testing in different timezones

- [ ] Check

## Testing onboarding

- [ ] Check

## Test that the UI is appearing as intended and report any issues

- [ ] Check

**Comment by amulware** [comment]
In case you weren't doing so yet, please add issues starting with those that add the highest value in terms of saving us manual testing time (or other kinds of value if there are other concerns I can't think of atm).

**Comment by ApocalypticFish** [comment]
[x] create a tag with the # symbol
[x] create a project with the @symbol

**Comment by ApocalypticFish** [comment]
[ ] switch to manual mode
[ ] switch to manual mode then create a new entry
[ ] create a manual entry through long press

**Comment by ApocalypticFish** [comment]
[ ] about
 - [ ] Privacy policy
 - [ ] Terms of Service
 - [ ] Licenses
