### ISSUE TITLE
Look into frequent API token resets

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4143]
## 🐛 Bug Report
Sometimes, some users might experience frequent API token resets.
It happens randomly on staging as well (Once a day, for the first time the api is used, it's normal)

## Context
Not much, it happens randomly, it seems to be related to the bad combination of HTTP responses with status codes 429 and 403 and the way we handle it.
There are some users experiencing this, but there is this case: /conversations/20142600551 

Build/Branch: develop
Phone OS: Experienced on Android
Phone model: Samsung seems to be more frequent

## Expected behavior
Well, API token resets should only happen when the user resets his/hers api token manually in the web app.

## To reproduce
Good luck. Really.

## Suggestions
Maybe trying it on Android with Samsung devices might help you.

**Comment by simonrozsival** [comment]
So far I have come to two possible scenarios where this problem of false positives when detecting reset API tokens might occur:

1. The app sends a 401 response for some endpoint when there is some problem but it is a different problem than a reset API token

2. The `/me/logged` endpoint returns `4xx` even with the correct API token

I talked to the backend guys and they didn't know exactly if the 401s can be thrown in different cases or what could be the problem with the `/me/logged` endpoint.

Right now I think our best choice is to update the way we interpret the response from the `/me/logged` endpoint and specifically we look for the 429 Too Many Requests which should be rethrown. Only a 403 response to the `/me/logged` endpoint should be considered as confirmation of the token being reset.
