### ISSUE TITLE
Start TE: Add new tag

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#4165]
Sign in
Start time entry
Create tag
Save entry
Stop time entry
Successful sync status displayed?

**Comment by heytherewill** [comment]
Is this needed? Is it not superseded by #4212?

**Comment by ApocalypticFish** [comment]
I'm not sure. I've seen an issue in the past where creating one tag was fine. But creating multiple causes an issue. It might be handy to have both for troubleshooting/diagnostic purposes
