### ISSUE TITLE
Giskard 1.10 - Manual testing

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4170]
# :penguin: Manual Test Template

## Testing sign in area ##

- [x] Test standard email and password sign in
- [x] Test standard email and password sign in with invalid email address
- [x] Test standard email and password sign in with invalid password
- [x] Test signup with standard email and password
- [x] Test terms and conditions link
- [x] Test privacy policy link
- [x] Test signin with Google signin
- [ ] Test signup with Google signin
- [x] Test forgotten password link
- [x] Test forgotten password link with invalid email
- [x] Is country selection automatically selecting the right country?
- [x] Is country selection allowing manual selection
- [x] Test email field with invalid email
- [ ] Test email field with mixed character sets (including various languages)
- [ ] Test password field for old/changed password

## Testing timer page
- [x] Start timer
- [x] Stop timer
- [x] Enter description
- [x] Add new project
- [x] Add new client
- [x] Add new tag
- [x] Add long description and confirm character limit error shows
- [x] Add new project using existing client
- [x] Add existing project
- [x] Add existing tag
- [x] Start new timer, select no project, stop
- [x] Create new manual time entry
- [x] Start a new entry, add multiple tags.
- [x] Start a new entry, discard new entry.
- [x] Continue an entry
- [x] Delete an entry

## Testing editing time entry
- [x] Change description
- [x] Change project
- [x] Remove project
- [x] Change tags
- [x] Remove tags
- [x] Change start time with the barrel/manual selection
- [x] Change start time with the wheel
- [x] Change end time with barrel/manual selection
- [x] Change start date
- [x] Change end date
- [x] Change duration
- [ ] Change date from main entry page
- [x] Discard changes to entry
- [x] Delete entry from edit view
- [x] Confirm changes
- [x] Create new project from edit view
- [x] Create new client from edit view
- [x] Create new tag from edit view

## Testing report screen
- [x] Custom range
- [x] Is correct data displayed
- [x] Are categories displaying correct timerframe and dates?
- [x] Is web displaying the same data?
- [x] Today
- [x] Yesterday
- [x] This year
- [x] This month
- [x] Last month
- [x] This week
- [x] Last week
- [x] Custom range 1 year
- [x] Custom range 1 month
- [x] Custom range 1 week
- [x] Custom range 1 day
- [x] Ensure correct year is selected on all options
- [x] Change workspaces

## Testing settings page
- [x] Sign out normal email
- [x] Sign out google sign in
- [x] Change workspace
- [x] Date format MM/DD/YYYY
- [x] Date format DD-MM-YYYY
- [x] Date format MM-DD-YYYY
- [x] Date format YYYY-MM-DD
- [x] Date format DD/MM/YYYY
- [x] Date format DD.MM.YYYY
- [x] 24 hour time format
- [x] 12 hour format
- [x] Duration format Classic
- [x] Duration format Improved
- [x] Duration format Decimal
- [x] First day of the week Monday
- [ ] First day of the week Tuesday
- [ ] First day of the week Wednesday
- [ ] First day of the week Thursday
- [x] First day of the week Friday
- [ ] First day of the week Saturday
- [ ] First day of the week Sunday
- [ ] Manual mode
- [x] Submit feedback
- [x] About
- [x] Help
- [x] Is "Synced" displaying correctly?

## Testing Calendar Integration
- [ ] Are calendar entries showing correctly?
- [ ] Create an entry from a calendar entry
- [ ] Adjust the start time
- [ ] Adjust the end time

## Testing Siri Integration
- [ ] Start a time entry
- [ ] Stop a time entry

## Multiple Workspaces
- [x] Switch workspaces
- [x] Go offline then switch workspaces (Airplane mode)
- [x] Switch between workspaces while timer running
- [x] Is data displaying correctly in web?
- [x] Force sync then switch
- [ ] Leave a workspace
- [ ] Be removed from a workspace while offline
- [ ] Be removed from a workspace with an active entry running

## Testing Interactions/Sync between this app and others
- [x] Edit client on web whilst mobile online
- [x] Delete client on web whilst mobile online and tracking a task
- [x] Edit client on web whilst mobile online and tracking a task
- [x] Tags
- [ ] Archiving
- [ ] Create new project on web whilst mobile offline
- [ ] Tasks
- [ ] Try creating new entries on web whilst mobile offline
- [ ] Edit client on web whilst mobile offline
- [ ] Try stopping timer on web while mobile offline
- [ ] Delete project on web whilst mobile offline
- [ ] Make changes to projects on web

## Testing in different timezones

- [ ] Check

## Testing onboarding

- [ ] Check

## Test that the UI is appearing as intended and report any issues

- [ ] Check

## Release
Refs: #4169

**Comment by amulware** [comment]
This should have some notes on additional things to be tested given the changes in the specific release. Please add them!

**Comment by juanlaube** [comment]
Closing as we have already released and there's enough confidence in the build.
