### ISSUE TITLE
Start TE: Select Existing Project

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4174]
Sign in
Start time entry
Enter project creation
Select Existing Project
Save Entry
Stop Entry
Successful sync status displayed?

**Comment by heytherewill** [comment]
The same problem from #4175 applies to this issue

**Comment by ApocalypticFish** [comment]
Yep so, I'd rather have it go through the whole process from the create a new project test. Then create a second entry with that existing project.
