### ISSUE TITLE
Start TE: Test "No Project" Option

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4178]
Sign in
Start a time entry
Enter project selection screen
Select "No project"
Save entry
Stop entry
Successful sync status displayed?

**Comment by heytherewill** [comment]
There needs to be a at least one project in order for `No Project` to be selectable. Can you either clarify what you wish to test or change the steps?

**Comment by ApocalypticFish** [comment]
Okay, so start a time entry.
Enter @symbol and project name. 
Create project. 
Save/done on time entry. 
Stop time entry. 
Start another time entry
Click the project selection button
Click "no Project" 
Press done/save on the time entry
Stop entry

**Comment by ApocalypticFish** [comment]
This also raises an issue that it will be worth testing both @ and # symbols as well as the project and tag menu options
