### ISSUE TITLE
Remove Toggl.Foundation.Helper.Color

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#4187]
Depends on #4181
Depends on #4186

This issue addresses the `Toggl.Foundation.Helper.Color` class.

It has a few public members that we can move around and then remove the file:
* `IsValidHexColor`. I think it makes sense that this would be a static method on `Multivac.Color`.
* `DefaultProjectColors`, `NoProject` and `ClientNameColor` should be moved to `Colors.cs` file from #4186

**Comment by heytherewill** [comment]
I am a bit against this one. I agree that it should be named Colors, but I don't know if it should live in Toggl.Foundation when color is clearly a UI related concept.
