### ISSUE TITLE
Use Color struct in IProject

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#4188]
Similar to `IUser.Email` being `Multivac.Email`, we should make `IProject.Color` a `Multivac.Color` and then update all the implementations of that interface.

**Comment by amulware** [comment]
Why is this [mvexit]? Before I approve going forwards with this, are we sure this is a good idea? We'd have to convert to/from string in the API and database all the time (whether we are actually gonna render the project or not). (That being said, we could store the colour as a 32 bit ARGB integer in the database, making the conversion much faster).

What I'm really trying to say: please provide more details and a cost/benefit analysis.

**Comment by arturs105** [comment]
This actually isn't part of MvExit - i wrongly added that tag, thinking that all color refactors were a part of MvExit, this issue falls into "Let's use more types like `Email`, `Password` etc." category.

The main benefit would be consistency in using our own types to represent things instead of plain strings.

**Comment by amulware** [comment]
I can see the argument above but am worried that this would cause additional overhead when interacting with the database. However, maybe we could use this to actually optimise how we store colours in the database, and store them as a single integer, instead of a string?

**Comment by amulware** [comment]
Dumping this on @heytherewill for further investigation/thinking :)
