### ISSUE TITLE
tests running smoothly iOS simulator

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4196]
Is it possible to make the tests run one after the other on the iOS simulator 
Can captain Xamarin investigate this please.
Currently the simulator needs to restart one after the other for iOS whereas android doesn’t have this limitation and just restarts the app

**Comment by heytherewill** [comment]
I just tested this locally and had zero flakiness after completely removing the reboot code. I used the iPhone 8 Plus emulator on iOS 12.1. @juanlaube, would you kindly test this again on your environment to see if a recent update (or lack thereof) suddenly made this work again?

**Comment by Odrakir** [comment]
@juanlaube Any status on this?

**Comment by ApocalypticFish** [comment]
@heytherewill @juanlaube What do you guys think about this? Are people still having problems? Should I just close this for now until we get more complaints?

**Comment by juanlaube** [comment]
This is still a problem and I have no idea how to fix it. Would be nice if someone can confirm this is a problem for others or just happens on my machine.
