### ISSUE TITLE
Project list unpopulated in reports

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4197]
## 🐛 Bug Report
Open a report on 1.10 Giskard and no projects are displayed underneath the pie chart in the project list area

<img width="202" alt="screenshot 2019-01-14 at 17 18 07" src="https://user-images.githubusercontent.com/3987892/51128680-6429ec80-1820-11e9-96e5-dc5e53e69135.png">

## Context
Replicated by Paul and I
Build/Branch:1.10
Phone OS:8.0.0
Phone model:HTC U Ultra

## Expected behavior
There should be projects in the list
## To reproduce
Access reports and view a range with entries with project selected 
## Suggestions
Have projects in the project section

**Comment by juanlaube** [comment]
Closed by #4204
