### ISSUE TITLE
Add a user settings for grouped Time Entries

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4217]
🏆 User should be able to decide whether they want their time entries to be grouped or not from the Settings screen. Make sure that we save the value received from `me/preferences` endpoint and use it in the viewmodel.

**Comment by simonrozsival** [comment]
Push sync should be triggered right after we update the preferences the same way we do it for time/date/duration format.

**Comment by kornelijepetak** [comment]
Solved by #4320
