### ISSUE TITLE
Implement infrastructure for grouped Time Entries

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4218]
#### Background 
Currently, we are using the following combination of view models:

* `MainViewModel` - governs the main screen
* `TimeEntriesViewModel` - governs the list of time entries on the main log.

`TimeEntriesViewModel.TimeEntries` is an `IObservable<TimeEntryViewModel>` that provides the list of time entries. 

So far, it seems to me that the easiest solution is to inherit a new class (e.g. `GroupedTimeEntryViewModel`) from the `TimeEntryViewModel` because the grouped time entry is basically a time entry template and has just a bit more information than the `TimeEntryViewModel` (and the observable should be of a single common type). Interface could be used as well, but it would basically be a copy of the `TimeEntryViewModel`. 

💡 Of course, this is just an idea. If the person solving this thinks there is a better way to solve this, this is in no way the only allowed solution. Use best judgement. Note however, that inheriting from the `TimeEntryViewModel` will make the Edit TE process much easier.

#### Requirements

🏆 This issue will be solved if:

* [x] The `TimeEntriesViewModel` exposes a collection observable that returns the items for the main log.
	* [x] The items are groupped by the matching time entry data
	* [x] The groups are sorted in a regular way (older groups further down the list)
	* [x] The groups have a way to be collapsed/expanded (which changes the collection)
* [x] The view model provides a way to navigate to the EditTimeEntryViewModel for a single item (as is currently already implemented), as well as for the group
	* [x] In case of a single TE, send TE's ID as a parameter
	* [x] In case of a group, send ID of any TE in that group (for simplicity: first)
* [x] The TEs are not grouped if user did not request that feature from settings screen
* [x] All the relevant tests for this functionality should be written.

**Comment by simonrozsival** [comment]
This issue was fully implemented with a series of PRs which were merged into a release branch. The only thing that's left is sending correct parameters to the edit VM, but this part is still being developed, so it will be connected later, hopefully as part of #4219.

I'm closing this issue now manually.
