### ISSUE TITLE
Update EditTimeEntryViewModel to support Grouped Time Entries

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4219]
The Edit Time entry screen currently accepts only the TE ID (`long`) and then loads the TE again from the database. Extend this parameter type to include the information about whether the edit is requested for a single item, or a group (something like `isEditingGroup`).

🏆 Update EditTimeEntryViewModel to support grouped time entries:
* [x] Parameter change
* [x] Setup logic
* [x] Deletion logic
* [x] Saving logic
* [x] Tests

The setup flow should be as follows:

* [x] Load TE specified by the ID
* [x] If the edit was requested for a single item, that's it.
* [x] If the edit was requested for a group, fetch all the TEs matching the same group criteria as the TE specified by the ID to find out the number of affected TEs
* [x] Emit that number through an observable so that view can show how many entries would be affected with the edit operation

The save flow:
* [x] If the edit was requested for a single item, update that item and close the view
* [x] If the edit was requested for a group, fetch all the TEs matching the same group criteria as the TE specified by the ID, update them according to the user's changes and then close the view.

The deletion logic:
* [x] The logic is the same as for the save, but instead of updating the TEs, delete them.

The reason why caching of grouped TE during setup is not suggested is the fact that a scheduled sync (or one started manually before opening the edit view for the group) could cause the number of affected TEs to actually change. It makes a bit more sense to update all the affected TEs at the moment of saving, and not those that would be affected at the Edit screen setup.

But I would like @amulware and @maritoggl to confirm this, or propose alternative solution.

**Comment by maritoggl** [comment]
It sounds like this is about how things are handled on the background, so I don't have a comment on that. I could comment, approve or disprove if I understood how this appears to the user :)

**Comment by kornelijepetak** [comment]
Closed by #4407
