### ISSUE TITLE
Update iOS Edit Screen to support grouped TEs

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4220]
🏆 Update the edit screen on iOS to support changes in the `EditTimeEntryViewModel` as defined in the #4219.

Make sure that two things are different for groups:
* [x] Remove time editing controls
* [x] Show how many entries would be affected by the edit
* [x] Update the delete label to include the number of affected TEs (something like `Delete all 12 entries in the group`)

@maritoggl, @lizaPlotnikova, please specify all the relevant copies for the changed UI elements.

**Comment by simonrozsival** [comment]
This issue was already solved.
