### ISSUE TITLE
Update cells for Time Entries and the group

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4222]
🏆 A new cell is required to display the group. 
Follow the designs to see what needs to be implemented.

* [x] Tapping the number of entries in the group will expand/collapse the group
* [x] Tapping the continue button will start a new TE based on the group's data
* [x] Tapping the rest of the group will open the Edit screen

~🏆 Additionally, the old `TimeEntryViewModel` (and corresponding platform-specific cells) used to represent the regular main log TE cell should have a flag showing whether the entry is part of a group or a regular ungrouped TE. If it is a TE in the group, it does not need to show the description/tags/project/client/task but instead show the appropriate times. There have been talks about this, but I am not sure about the final decision. @maritoggl, @lizaPlotnikova, @amulware, please reach the verdict.~ (For details of scratching, read further comments).

💡 This is required on both Android and iOS.

**Comment by maritoggl** [comment]
@kornelijepetak as of right now, for each individual time entry in the expanded group, same data fields should be displayed as are displayed for ungrouped time entries. We may come back to changing that in the future if we get relevant feedback from users.
