### ISSUE TITLE
NullReferenceException in ConcurrencyAbstractionLayerImpl

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4230]
## 💥 Crash Report
Cannot reproduce yet and there's not enough information right now, the stacktrace is not helpful.

### 👥 Impact
- 45 times to 32 users, that's 63% of the crashes in Giskard 1.10
- Found after releasing Giskard 1.10 to 5% of active users

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/749082492u/overview

### 📝  Exception & Stack Trace
`System.NullReferenceException: Object reference not set to an instance of an object`
```cs
ConcurrencyAbstractionLayerImpl+<>c.<StartThread>b__8_0 (System.Object itemObject)
ThreadHelper.ThreadStart_Context (System.Object state)
ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
ThreadHelper.ThreadStart (System.Object obj)
```

**Comment by heytherewill** [comment]
As per the logged [events](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/749082492u/reports/2518545871749829999-35ada7d7-1074-4b96-9b8d-ed47b6504eff/events), this seems to be a bug in the background sync

**Comment by amulware** [comment]
This occurs in 1.11.1 - I thought background sync was disabled?

**Comment by amulware** [comment]
Also, is this actually being worked on? If not, please unassign.

**Comment by juanlaube** [comment]
Ok, this is still a thing in Giskard 1.11.1, the problem is not exlusive to background sync, but something in sync in general, that's why we still see some of these even with background sync disabled.

The new events track every transition and state change in sync, I hoped to find all the crashes in the same sate but that's not a thing, however something I noticed is the last events recorded are always `PersistListState` or `EnsureFetchListSucceededState`, maybe that's useful for future research.

@amulware I will unassign myself because I'm working on the calendar, but I think this should be prioritized.

**Comment by kornelijepetak** [comment]
For the big majority of cases, the last sync state is `EnsureFetchListSucceededState<T>`. There's another one that I've noticed, `PersistListState`. Whether the last sync state for which we have an event tells us anything I am not sure. Almost all of them being the same last sync event it's possible, but I couldn't guarantee it.

In all cases it's `NullReferenceException` so I've tried to look at things that could possibly be `null`. Most likeley something like `fetch.GetList<T>();`

I've tried putting a breakpoint on some of those places, but I wasn't able to crash the app and cause such an exception.

I think @simonrozsival should take a deep breath and take a look at this issue, as it's highly likely that he'd spend the least amount of time debugging this (maybe other guys that were working on sync project).

**Comment by kornelijepetak** [comment]
One of the strangest things we also have to bear in mind is the fact that this does not happen on iOS. 🤔

**Comment by amulware** [comment]
I suggest that everyone who looked into this or might have some sort of idea gets on a call together to see if they can figure anything out.

**Comment by amulware** [comment]
More on 1.12: https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/821619005u/overview

**Comment by kornelijepetak** [comment]
I was looking a bit at the source code for the class itself.

https://github.com/dotnet/reactive/blob/master/Rx.NET/Source/src/System.Reactive/Concurrency/ConcurrencyAbstractionLayerImpl.cs#L69

It seems to me that the only way for this to cause a `NullReferenceException` is if the action that is being scheduled was `null`. However, this seems to be deeply rooted inside the RX/System.Threading that it's kind of hard to find out where exactly the `null` gets into the story.

It is theoretically possible that we are sending a delegate somewhere to be executed which can sometimes be null. I say '_sometimes_' because it obviously work in most scenarios. Obviously fails only at times.

**Comment by kornelijepetak** [comment]
The part `<StartThread>b` of the stack trace in
`ConcurrencyAbstractionLayerImpl+<>c.<StartThread>b__8_0 (System.Object itemObject)`

refers to the anonymous method inside the StartThread:

```cs
itemObject =>
{
    var item = (WorkItem)itemObject;
    item.Action(item.State);
}
```

according to the rest of the code, `item` always is `WorkItem`, so the only explanation is that the `item.Action` is null so the function can't be called.

**Comment by juanlaube** [comment]
We are collecting more analytics events in 1.14 so I'm moving this issue to 1.15.

**Comment by kornelijepetak** [comment]
So far, there haven't been any cases of this [crash in 1.14](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors?version=1.14&period=last30Days&status=&errorType=unhandlederror&sortCol=lastError&sortDir=desc).

I will monitor it for a bit more and reevaluate this issue when 1.14 is in the hands of larger number of users. If there are still no crashes like this, I will close the issue.

**Comment by amulware** [comment]
Do we know how this got fixed, assuming it did?

**Comment by juanlaube** [comment]
We don't know and that's scary, but my theory is the dependency injection refactor solved this. Would be nice to know the reason though, given this crash has been a stone in our shoes for months.

**Comment by kornelijepetak** [comment]
@amulware yes, and honestly I don't think it's worth investing time into finding out why. If it never happens again in the future, it becomes irrelevant (albeit would be a mental lesson). If it does, we will still have to find out. 

I don't think that benefit would outweigh the time invested at this point.

So for the moment, as no occurences of this have seen in 1.14 as of yet, I am closing the issue.

**Comment by kornelijepetak** [comment]
⚠ With the deepest regret, I must reopen this issue.

**Comment by kornelijepetak** [comment]
While not exclusive, this sequence of steps is very thematic

![image](https://user-images.githubusercontent.com/7033216/61121578-d6158280-a49f-11e9-9a3d-964fc00173b1.png)

In many of the cases, we can see app being open for 40 minutes, 2 hours and such, which is also weird.

**Comment by kornelijepetak** [comment]
I am now closing this issue.

For some reason, the try-catch-rethrow seems to be enough to either
1) prevent this crash
2) make it crash in such a way so we don't detect it at all.

That being said, I don't think it's valuable to keep this open.
