### ISSUE TITLE
Pinch zooming in Calendar View

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4233]
Right now I can see about ~10 hours on my iPhone 6S in the Calendar View. That's great for having an overview of the day, but any time entry smaller than ~30m gets a bit finicky, especially if I want to use the drag-to-edit features.

I'd like us to investigate how difficult it would be to allow the user to two-finger pinch to zoom in and out on the calendar.

In terms of constraints, the user could zoom out so far that they only see a single day, and maybe zoom in by a factor of 2 or 3 compared to now.

If this is very hard to do, we probably shouldn't (still, please report below how it could be done, and why it's difficult!).

If it's easy, let's at least give it a try and see how we like it. :)

**Comment by sofokli1** [comment]
This is doable and we should definitely do it. U made a PR #4266 as a prove of concept, it will need more work than that. Below is a gif. I left some tech specifications in the PR.

![jan-18-2019 16-08-12](https://user-images.githubusercontent.com/885122/51391954-36081d80-1b3c-11e9-8d05-ee52143d8ff8.gif)

This shouldn't take more than 1 or 2 to build and 1 or 2 days for review and fixes.

**Comment by sofokli1** [comment]
Should I close this issue?

**Comment by sofokli1** [comment]
PR is good for review
