### ISSUE TITLE
Add support for Adaptive Icons

### ISSUE THREAD

**Issue by JacobDB** [toggl/mobileapp#4234]
## 🐛 Bug Report
Newer versions of Android support a feature called Adaptive Icons. This essentially lets users pick the shape for all of the icons on their home screen. On phones which support Adaptive Icons, Toggl appears with a white border around it, instead of being solid red.

[Demonstration](https://user-images.githubusercontent.com/1123997/51327766-a6794680-1a37-11e9-878e-dd61697fda47.gif)

## Context

Build/Branch: Google Play [v1.9 (402290)]
Phone OS: Android
Phone model: Pixel 3

## Expected behavior
When choosing a different icon shape, the Toggl icon should adapt to fit the new shape.

## To reproduce
On a phone that supports adaptive icons, such as a Pixel:

1. Press and hold on the home screen
2. Tap "Home settings"
3. Tap "Change icon shape"
4. Select any shape
5. Return to the home screen, and find the "Toggl" icon
6. Observe the white border

*Note: On some phones, you may need to enable developer settings to see the "change icon shape" option, but on others, it's enabled by default.*

## Suggestions
Implement adaptive icon assets using [Google's documentation](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive).

**Comment by amulware** [comment]
We should definitely consider updating/simplifying our icons on both platforms. iOS also has the white border around it and we should decide if we intend to keep it that way, switch to all-red, or maybe do something else.

I'm leaving this up to @maritoggl. If we decide what to do and get new images, switching them out is very little effort.

**Comment by amulware** [comment]
Strictly speaking, the Android icon is 'fine' the way it is, in the sense that the red circle is part of the logo, not just the background, however, it does look a bit silly, especially with circular background.

**Comment by heytherewill** [comment]
We support adaptive icons for a while now, so I think this can be safely closed :)

@JacobDB thanks for opening this issue and feel free to reach out if you have any doubts
