### ISSUE TITLE
Create the MainBottomBarActivity

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4241]
Let's try to use the native version of the BottomNavigationView for this one. It might need some tweaking.

That's the equivalent of the `MvxTabBarViewController` for iOS and will be the view for the `MainTabBarViewModel`.

**Comment by daividssilverio** [comment]
Things to remember:
- Update the animations (remove them) in the fragments that replaced the old activities. They won't be necessary as it doesn't make sense anymore.
- Update the `TogglPresenter` It now has to work with the `MainBottomBarActivity` and its fragments.
- Fix the toolbar in the `SettingsFragment`
- Take a look at the backstack configuration of the fragments. We basically don't have one for the bottom bar, pressing back on the bottom bar shouldn't go to the previous fragment, it should lead the user to the `MainFragment` if he's not there or close the application otherwise.
- You'll have to remove the existing `ForkNavigation` usages.
- Make sure that the snackbar isn't weird.

**Comment by juanlaube** [comment]
Closed by #4397
