### ISSUE TITLE
Implement the CalendarServiceAndroid

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4243]
Implement the android part of the `PermissionAwareCalendarService`. Right now it's mocked.

This will be used to populate the Android calendar view, but it should not block the implementation of the view, since we can mock it.

**Comment by heytherewill** [comment]
If suggestions are not merged in time, this is as easy as cherry picking #3857 into develop 👌

**Comment by daividssilverio** [comment]
I knew this was implemented already! That's very helpful, thanks o/

**Comment by daividssilverio** [comment]
Closed by #4392 by cherry-picking #3857
