### ISSUE TITLE
Re-schedule calendar notifications after device Restart

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4245]
This issue depends on #4244.

Android is nice to us and removes all pending intents when a device is restarted, we've got to reschedule all pending intents using the `AlarmManager` once again when the device is restarted.

Hints:
Take a look at
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
```

We are most likely going to create a broadcast receiver to listen to the device boot and re-schedule pending notifications.

**The notifications will have to be stored somewhere**, or we can use `ScheduleEventNotificationsInteractor` in the broascast receiver, if possible (this would actually be more precise, in case the events changed).

**Comment by juanlaube** [comment]
Closed by #4520
