### ISSUE TITLE
Compile report on current usage of Siri features

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4260]
I'd like to see how many users use our Siri integration in what ways. Any data we have really.

Please also include how we can improve tracking of Siri usage to gain more valuable information in the future.

**Comment by Odrakir** [comment]
Analytics report: https://www.notion.so/Siri-Usage-Analytics-Report-ce3c7b34a9474fdda7eb9896a4e74149

**Comment by khoi** [comment]
the report looks good 👍
