### ISSUE TITLE
Compile report on user facing results of workspace gain/lose project

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4262]
I'd like to know if we have any data on how often gaining/losing workspaces happens. Also the no-workspace and no-default-workspace cases, anything else related to these.

@simonrozsival volunteered to take care of this.

**Comment by simonrozsival** [comment]
I compiled a document and sent it to Slack. I don't think these data should be published in GH, so I won't put it here.

**Comment by kornelijepetak** [comment]
@simonrozsival You could at least give a link to the slack item. Having a slack link here will not make it public.
Then close the issue.
