### ISSUE TITLE
The syncing state bar hides too early when syncing twice in a row

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4263]
## 🐛 Glitch Report
When you sync once and then initiate sync with a pull-to-refresh again, the "Syncing..." bar will hide before syncing finishes instead of staying visible until the app's done syncing.

## Context
Build/Branch: 1.15, 1.16
Phone OS: iOS
Phone model: any iPhone

## Expected behavior
- The "Syncing..." bar is shown until syncing finishes unless the user scrolls down the main log.

## To reproduce

- Let the app sync
- As soon as you see "Synced ✅" pull to refresh again
- The bar will now say "Syncing..." and it will retract after a few seconds
- After a few more seconds it will appear again saying "Synced ✅"

## Suggestions
Reset the hiding animation when the app starts syncing while the "Synced ✅" status is shown.

**Comment by amulware** [comment]
Let's address this with a more complete solution as part of #4279.
