### ISSUE TITLE
Track of how many users are using suggestions and log view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#428]
We want to know of how many users are using suggestions and log view.
To measure that, track of how many time entries are being made (both from 'play' and 'continue' button) on both views (suggestions and log view).

**Comment by amulware** [comment]
Just to be clear, this is three different events:
- started from start button
- started from suggestion
- continued previous entry from log

**Comment by amulware** [comment]
Ideally, these would all fall under the same sort of event with sub categories so we can get numbers for all, and for each specifically in our analytics.
