### ISSUE TITLE
1.16 freezing when continuing entries

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4280]
Fresh install
Created a new account
Started and stopped an entry
Edited and added 8 tags to that entry.
Swiped to continue multiple times and the app froze.
Force closed the app and reopened it.
Continued entries again and the app froze again.

**Comment by simonrozsival** [comment]
I think this could be related to #4278

**Comment by simonrozsival** [comment]
Could you please test if this happens with 1.15 as well?

**Comment by simonrozsival** [comment]
Fix was merged into a release branch. We will reopen this if we run into this issue while testinf 1.16
