### ISSUE TITLE
Create the Android Calendar "Get Started" placeholder

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4287]
That's the initial page when the permissions were not granted and no calendars events were configured to appear in the app.

This view should show a quick rationale about the feature.
Clicking "Get Started" should trigger a dialog with a rationale why we need permissions to read the calendar or offer the user to start the calendar without it.

**Comment by juanlaube** [comment]
Closed by #4420

**Comment by daividssilverio** [comment]
This issue only covered the view part. I'll create another issue for the bindings and related logic.
