### ISSUE TITLE
Track new users activity

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#429]
We want to track how many users continue actively using the app after installing it. For that we should measure the activeness by the creation of time entries, not simply by opening the app.
- Track of how many new users (new user = user who signs up, not existing Toggl users) create at least 5 time entries between 5th to 12th day after installing the app. *We don't care how many hours there are between the time entries, as long as the time entries are created within 5 to 12 days after the date of app installation.*

**Comment by amulware** [comment]
We already track users creating time entries here: #428

What is asked in the issue above is very complicated, and I do not want that kind of code in our app, that is not where it belongs. Instead, that data should be available/extractable from our analytics service.

Is that good enough, @pe0ny?

**Comment by amulware** [comment]
After internal discussion, this will be as I suggested above, so this is covered by other issues.

**Comment by pe0ny** [comment]
@amulware Are you sure this should be closed since we don't have that information/calculations haven't yet been made in Firebase?

**Comment by amulware** [comment]
The information needed is implicit in #428.

Is it up to us here to figure out how to massage the data in Firebase?

**Comment by pe0ny** [comment]
Do you know/are you sure these can be implemented in Firebase without any coding effort? Also, will this data come in as 'Events' in Firebase?

**Comment by amulware** [comment]
I do not know this at the moment. I'd say we implement the simple stuff first and then see how it looks, and what we can do with it.

If we then decide that we really need more complicated logic, we can make a more informed decision then.
