### ISSUE TITLE
Crash when long-tapping calendar event twice

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4294]
## 🐛 Bug Report
When I long-tap a calendar event in the calendar view, dismiss the dialog that pops up and long tap it again, it will crash about a second or so after the second dialog shows.

## Context

Build/Branch: 1.16
Phone OS: latest iOS
Phone model: 6S

## Expected behavior
No crash pls.

## To reproduce
- long-tap a calendar event
- dismiss the dialog
- long-tap the same calendar event (might also work with different one, not sure
- dialog pops up, wait about a second and it crashes (every time)

## Suggestions
Not severe enough to delay 1.16, but let's fix it for 1.17.

This doesn't seem to show up in AppCenter. Curious?

**Comment by simonrozsival** [comment]
AppCenter report: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3082113359u/overview
