### ISSUE TITLE
Enable background sync in Android again

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4298]
We need to undo the changes in #4297 and #4299  and enable background sync in Android again, only after #4230 is solved.

**Comment by amulware** [comment]
We'll delay this until we start working on push notifications.

**Comment by simonrozsival** [comment]
This might be related to #5345 - the `BackgroundSyncJobSchedulerService` class calls `UserAccessManager.CheckIfLoggedIn`, which could cause a crash.

**Comment by amulware** [comment]
What's the status of this? Are we still going to do this?

**Comment by daividssilverio** [comment]
🤔 With PNs working, this would become obsolete, right? Or at least conflicting with the PNs syncs.

**Comment by amulware** [comment]
I don't see why it would. It's just another source of syncs for situations where PNs aren't working or are throttled. Happy to hear arguments against though.

**Comment by juanlaube** [comment]
In iOS users can disable both notifications and background sync, I guess there must be something similar in Android. I agree with @amulware and I don't think this is obsolete, in any case both sync sources are complimentary.

**Comment by juanlaube** [comment]
Regarding this issue in particular, the crash that forced us to disable background sync is gone, we don't know why exactly though, but the dependency injection refactor before mvexit solved the problem. I don't see why we shouldn't enable background sync again.

**Comment by heytherewill** [comment]
In the new light of CALI 🥦, do we still wanna enable this?

IIRC, this crash was similar to (if not the same as) CALI

**Comment by juanlaube** [comment]
I think we should try again if CALI doesn't happen anymore after 2.1.6 (so far so good 🤞)

Background sync is not the source of CALI, I've found the crash happening before we released that feature (at least since Android 1.4 iirc) and it did happen after we disabled it again. If anything, background sync helped CALI to occur more often.
