### ISSUE TITLE
Null ref in CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4304]
## 💥 Crash Report
App crashes in the calendar view. I have no idea what exactly causes the problem or how to reproduce it.

### 👥 Impact
The impact is very low, the crash happened 27x for 22 users. That makes only 0.7% of users affected by this crash. It is still the most frequent crash in 1.16 at the moment.

### 🔗 Context
I haven't seen a similar crash before.

There are some similar crashes which might be related somehow:
- https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3726594500u/overview
- https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/2989517920u/overview

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/2108006625u/overview

### 📝  Exception & Stack Trace
`SIGABRT: Object reference not set to an instance of an object`
```cs
    CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath (Foundation.NSIndexPath indexPath)
    CalendarCollectionViewLayout.frameForEditingHour (Foundation.NSIndexPath indexPath)
    CalendarCollectionViewLayout.LayoutAttributesForSupplementaryView (Foundation.NSString kind, Foundation.NSIndexPath indexPath)
    (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
    UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
    UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
    Application.Main (System.String[] args)
```

**Comment by amulware** [comment]
More of the same here:
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/1270117691u/overview

Most frequent crash in 1.7 as well. Accounts for 40+% of crashes there.

**Comment by sofokli1** [comment]
This can be reproduced quite easily in 1.7 and `develop` by creating TEs in calendar view with long press to create and drag up or down to change the duration. Usually happens when adding a second TE and the main reason it can pass through our testing. The following is from a user:

![feb-19-2019 16-54-10](https://user-images.githubusercontent.com/885122/53024075-057f1080-3467-11e9-95cc-1cecadc2b25c.gif)

**Comment by dshr** [comment]
This looks related to #4371.
