### ISSUE TITLE
Update appfigures

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#431]
Update appfigures data, so instead of the old app data, we'll get new ios number of downloads and rating.

**Comment by amulware** [comment]
In addition to, or entirely replacing the old iOS app? It's the same amount of work in either case.

Also, note that this will require changes from backend.

**Comment by pe0ny** [comment]
Entirely replace the old iOS app

**Comment by amulware** [comment]
The app does not show up there yet. We may have to release it publicly before it does. Fortunately, that is the earliest when we can use the data anyways.

**Comment by amulware** [comment]
I added the new app, and a slack integration to post reviews. I also created an issue for backend to update the ids. Once backend gives the ok, I'll remove the old app from appfigures, since we no longer care.

**Comment by amulware** [comment]
Those changes will happen _whenever_.

**Comment by amulware** [comment]
Done.
