### ISSUE TITLE
Country selection view cannot be reopened after dismissing

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4317]
## 🐛 Bug Report
When you go to the country selection view and you don't select a country but you dismiss it by the `x` button or by swiping down, you can't reopen it again. Going to the login view and back to signup "unlocks" it.

## Context

Build/Branch: `1.16`
Phone OS: `iOS`
Phone model: doesn't matter

## Expected behavior
You can open and close the view as many times as you want.

## To reproduce
- Go to sign up view
- Tap on "Select country" or the preselected country
- Tap on the `x` button or swipe down to dismiss the view
- Tap on the country selection button again
- Nothing happens even though the country selection view should appear

## Suggestions
The VM is probably not properly closed and it is stuck `awaiting` the result of the previous time it was opened.

**Comment by khoi** [comment]
Tested in latest `develop` https://github.com/toggl/mobileapp/commit/5f49417a77b415f3cb6c5513f3023537326392dc and it's been fixed. 
I'm closing this

**Comment by khoi** [comment]
UI Test also added in https://github.com/toggl/mobileapp/pull/4080 to make sure this doesn't happen again in
