### ISSUE TITLE
Scrolling calendar in reports has no inertia

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4332]
## 🐛 Bug Report
Not really a bug, but a small glitch, when you show the calendar in reports and then try to scroll it doesn't have inertia as the rest of the table view does, so it's a little frustrating.

Not sure if it's easy to fix without changing a lot of the view structure though.

## Context
It happens in any iOS version.

## Expected behavior
It should be easier to scroll down, it should have inertia.

## To reproduce
Just show the calendar in reports and try to scroll down.

**Comment by heytherewill** [comment]
Obsolete after rewrite
