### ISSUE TITLE
Analyse test coverage

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4336]
I'd like us to go over all projects and check our test coverage. Please create a list of all code that is not tested below.

I specifically mean unit test coverage. Rider/Resharper should have tools to figure this out easily.

**Comment by kornelijepetak** [comment]
`Develop` branch on today.

![image](https://user-images.githubusercontent.com/7033216/55232129-deb1b800-5224-11e9-888a-010fdd87f305.png)

**Comment by kornelijepetak** [comment]
The complete [Test Coverage Report](https://github.com/toggl/mobileapp/files/3022582/TestCoverageReport.zip) that shows what is and what is not tested.

**Comment by kornelijepetak** [comment]
@amulware please state whether for this issue you want anything else?

**Comment by amulware** [comment]
Very nice, thanks!
