### ISSUE TITLE
Add batch update/insert/delete to database repositories

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#434]
The method should take a list of the respective entities and persist them all.

If an entity is already known (check by id), it is updated. Otherwise, it is created.
However, if the entity is set to deleted, and it exists locally, it should be deleted instead.

The trickiest bit about this might be to ensure all realm references are gotten correctly in both cases. We may have to generate more code to update an existing realm model from another one while preserving/updating references appropriately.

---

If this turns out to be a special case of #436, maybe having only that method would be enough. Certainly, if that means we don't have to make PrimeRadiant understand when do create/update/delete (thinking especially about delete here, since that requires some knowledge about the models).

**Comment by arturs105** [comment]
And by "it should be deleted instead" do you mean set the `IsDeleted` or really delete?
