### ISSUE TITLE
Hide the date and tracked time labels during calendar onboarding

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#4340]
The labels inside the navigation bar serve no purpose during onboarding, so they should be hidden until user finishes the onboarding.

![screenshot 2019-02-05 at 12 44 35](https://user-images.githubusercontent.com/15633003/52269511-efd9f900-2946-11e9-9ee9-8ae80c4671e1.png)

**Comment by amulware** [comment]
I believe this onboarding no longer exists.
