### ISSUE TITLE
Do not replace variables using 🍰 when (just) running unit tests

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4351]
Sometimes cake doesn't clean up when the script is interrupted or when the cosmic radiation is too strong or something. It leaves a mess in git and you have to pay attention to not commit something you shouldn't...

Replaced variables have no effect on unit tests anyway. We only need it for production builds.

**Comment by heytherewill** [comment]
Let's avoid messing with cake for obvious reasons
