### ISSUE TITLE
Add section for custom Siri shortcut workflows in the in-app settings

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4358]
Separated from normal shortcuts, we could have predefined workflows for the shortcuts app. Things like "Get current location -> Send message to wife -> Stop timer" or whatever, that the user can add to the Shortcuts app from our app with just a tap.

Something like what sharecuts does but in the app: https://sharecuts.app

**Comment by khoi** [comment]
is there an app example of how this could be done?
