### ISSUE TITLE
Add batch update/insert/delete with conflict resolution to database repositories

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#436]
Similar to #434, however, the conflict resolution behaviour should be injected from Foundation.

I see this working something like this:

```
parameters:
IEnumerable<IDatabaseModel> items
Func<IDatabaseModel, Expression<Func<IDatabaseModel, bool>> getRealmItemExpressionFor
Func<IDatabaseModel, IDatabaseModel, ResolveMode> howToResolve

using(new transaction)
    foreach(item in items)
    {
        var realmItem = repo.Get(getRealmItemExpressionFor(item)) // maybe this can just be done by id instead if that's all we ever want to do here?
        var resolveMode = howToResolve(item, realmItem)
        if (resolveMode == TakeNew)
            // somehow write all values from item to realmItem, without creating a new item?! (could generate a method to set all fields)
        else if (resolveMode == TakeOld)
            // do nothing
    }
```

Very pseudo. Much incomplete.

Consider the real use cases, and that we have to handle at least: overriding data, creating new entity, deleting existing entity

We also have to make sure that any references inside the updated model are persisted correctly, which might mean we have to generate more code to update a RealmModel from an IDatabaseModel while resolving references.

**Comment by simonrozsival** [comment]
I'm closing this manually, because it wasn't referenced well in the description of the pull request #467.
