### ISSUE TITLE
Add reports to the Siri Extension UI

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4361]
Right now showing reports are the only shortcuts that need to open the app to do something. What I would like to do here is show a minimal version of the reports directly in the Siri UI without the need of opening the app (which you could still do by tapping)

This code could be shared with a future possible Today Widget that shows similar info.

Something like what the Activity app shows in the Today Widget should be enough:

![img_00fb355d89b6-1](https://user-images.githubusercontent.com/724743/52424164-b7c6e780-2af9-11e9-9fdf-6c8ff5335559.jpeg)

**Comment by amulware** [comment]
Depending on how things go, I think we might wanna make this an optional stretch goal. But I am curious to see what we can figure out here if we do have the time.
