### ISSUE TITLE
Classic duration behaves the same as Improved duration in edit view

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#4383]
## 🐛 Bug Report
Go to settings set the duration style to classic and go back to a TE and tap to edit. check the duration style there. compare with the other 2 styles for reference. (might be shown in a wrong way elsewhere too.

## Context
Build/Branch: `daneel-1.17` most likely in `develop` too
Phone OS: ios
Phone model: iphone x

## Expected behavior
show the duration with the classic style when selected

## To reproduce
follow the steps described above

## Suggestions
might be an error on the format used for the strings

**Comment by amulware** [comment]
Should it be shown according to the format from the setting there? @maritoggl?

**Comment by maritoggl** [comment]
I will doublecheck and confirm this at first opportunity. Currently, I am not sure whether the user settings should only be considered in reporting or elsewhere as well and what's the current behaviour on other platforms.

**Comment by maritoggl** [comment]
Yes, we should respect the user setting here and elsewhere where durations are handled.

**Comment by arturs105** [comment]
I checked this on the following versions and couldn't replicate:
* 1.18 from the app store
* 1.19 from Testflight
* latest `develop`

@sofokli1 Could you please check again to see if this is still an issue?

**Comment by sofokli1** [comment]
it still happens for durations bigger or equal than 1h 
in the screenshot below you can see 2 types of formatting (it looks the same in the edit view for each of them as it looks in the log).
![IMG_1343](https://user-images.githubusercontent.com/885122/54220625-80819700-44fa-11e9-93f5-2ee2b1875e18.png)

**Comment by arturs105** [comment]
I was missing that the entry needs to be longer than 1 hour. Starting to work on this now.

**Comment by arturs105** [comment]
The format is actually correct - when duration is longer than 1 hour, this is the way that it is supposed to be displayed. Web app does the same thing. Going to write this down in notion, since this is not the first time this question has been raised.
