### ISSUE TITLE
Add the Calendar View Onboarding card in the main log

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4387]
This should be a simple card that leads to the calendar page in similar fashion to the Rating view card.

We might or might not use Remote config for this card.

**Comment by amulware** [comment]
This needs a lot more thinking, specifically on how showing/hiding the card works exactly, and what data needs to be stored where.

Please run those details past me before implementation.

**Comment by maritoggl** [comment]
Let's skip this for now and come back to the topic of how to make users aware of different features we have in the scope of a separate project.
