### ISSUE TITLE
Create the header row for the calendar

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4389]
It should have two states:

When the calendar permissions weren't given:
https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5c61d5586f0f43465eb218dc

Displaying a button to restart the calendar permissions request.

When the calendar permissions were given:
https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5c61d558a981283c0b3f6493

It should contain the current day, time entries (with summed times) and the number of events

**Comment by daividssilverio** [comment]
Closed by #4525

**Comment by daividssilverio** [comment]
🤦‍♂️ The issue isn't closed yet... #4525 handles the layout only...

**Comment by juanlaube** [comment]
Closed by #4525 and #4540
