### ISSUE TITLE
Set and hook up first state machine for fetching on app start

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#440]
What the title says. Requires #438

We should see about where to expose the state machine, but it's probably gonna be in the main data source somewhere. I'm not entirely sure who should be in charge of creating the sync manager for the data source, but maybe it does not matter that much right now.

We should then trigger a full sync anytime the user logins or opens the app when logged in. This trigger should happen from the UI I think, so that the app has control over it, and can consume the created observable.

- [x] Set up state machine
- [x] Expose state machine in data source
- [x] Trigger full sync on login/app start when logged in

**Comment by willsb** [comment]
For reference:  The best point in the lifecycle to start the sync is [here](https://github.com/toggl/mobileapp/blob/develop/Toggl.Foundation.MvvmCross/App.cs#L43), but it should be made it so that starting the sync machine on a `BackgroundTask` or on an Android `Service` is simple, allowing for silent background syncs :shipit:

**Comment by amulware** [comment]
@willsb how do you mean "it should be made it so that starting the sync machine on a BackgroundTask or on an Android Service is simple"? The state machine is all observy and stuff so it will already run almost everything in the background.

**Comment by willsb** [comment]
That much I get it, I'm sure you take your observy stuff serious!

What I meant is that the state machine should be thought to be started in situations such as iOS' [Backgorund Fetch](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html) and Android's [Background Service](https://developer.android.com/training/run-background-service/create-service.html), where you have some limitations (namely: MvvmCross is not fully available, etc).

**Comment by simonrozsival** [comment]
I am closing this issue manually because the PR just referenced the issue, but didn't say it was closing it.
