### ISSUE TITLE
Show project creation error when users hit "Create"

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4401]
Since the users are now allowed to create projects with the same name if they're associated with different clients (#4380).

The error message showing when users enter the project creation view is confusing (see video). 

We'll change the behavior so that message only show when users hit "Create"

![name](https://user-images.githubusercontent.com/6994441/52759103-46c58980-303d-11e9-8cc3-11ea1ad2877c.gif)

**Comment by maritoggl** [comment]
I propose changing the "Sorry, this name is already taken" to "Sorry, such project already exists".
