### ISSUE TITLE
Eugene can't login with google

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#4404]
## 🐛 Bug Report
It is a bit of an odd title but is something that has always been an issue for me. Not sure what is the problem. I can't login with google. I get the usual generic error message. Never thought much about this because it looks like other people can sign-in fine and I can sign-in with username and pass. I think it is worth having this issue here just in case. I have tried with 2 accounts that I have and I get the same results. Signup has happened with username and pass, so maybe that is an issue when trying sign-in with google. 2fa is enabled on both accounts. I use the kind of 2fa that asks to open the google app and tap on `yes it is me` in order to complete login (so leaving the app an coming back is needed).

## Context
Build/Branch: 'any'
Phone OS: ios 12
Phone model: x

## Expected behavior
sign-in with google normally

## To reproduce
I can reproduce anytime but that is related to my account so not sure how to reproduce for someone else.

## Suggestions
None

**Comment by amulware** [comment]
I'm closing this. Feel free to reopen if it's still an issue. I suggest double checking that your account is properly linked with Google and that Google Login is enabled in your users settings (in the webapp).
