### ISSUE TITLE
Test Chlorine

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4406]
# 🐧 Manual Test Template

The release PR is #4405

## Testing sign in area ##

- [x] Test standard email and password sign in
- [x] Test standard email and password sign in with invalid email address
- [x] Test standard email and password sign in with invalid password
- [x] Test signup with standard email and password
- [x] Test terms and conditions link
- [x] Test privacy policy link
- [x] Test signin with Google signin
- [x] Test signup with Google signin
- [x] Test forgotten password link
- [x] Test forgotten password link with invalid email
- [x] Is country selection automatically selecting the right country?
- [x] Is country selection allowing manual selection
- [x] Test email field with invalid email
- [x] Test email field with mixed character sets (including various languages)
- [x] Test password field for old/changed password

## Testing timer page
- [x] Start timer
- [x] Stop timer
- [x] Enter description
- [x] Add new project
- [x] Add new client
- [x] Add new tag
- [x] Add long description and confirm character limit error shows
- [x] Add new project using existing client
- [x] Add existing project
- [x] Add existing tag
- [x] Start new timer, select no project, stop
- [x] Create new manual time entry
- [x] Start a new entry, add multiple tags.
- [x] Start a new entry, discard new entry.
- [x] Continue an entry
- [x] Delete an entry

## Testing editing time entry
- [x] Change description
- [x] Change project
- [x] Remove project
- [x] Change tags
- [x] Remove tags
- [x] Change start time with the barrel/manual selection
- [x] Change start time with the wheel
- [x] Change end time with barrel/manual selection
- [x] Change start date
- [x] Change end date
- [x] Change duration
- [x] Change date from main entry page
- [x] Discard changes to entry
- [x] Delete entry from edit view
- [x] Confirm changes
- [x] Create new project from edit view
- [x] Create new client from edit view
- [x] Create new tag from edit view

## Testing report screen
- [x] Custom range
- [x] Is correct data displayed
- [x] Are categories displaying correct timerframe and dates?
- [x] Is web displaying the same data?
- [x] Today
- [x] Yesterday
- [x] This year
- [x] This month
- [x] Last month
- [x] This week
- [x] Last week
- [x] Custom range 1 year
- [x] Custom range 1 month
- [x] Custom range 1 week
- [x] Custom range 1 day
- [ ] Ensure correct year is selected on all options
- [x] Change workspaces

## Testing settings page
- [x] Sign out normal email
- [x] Sign out google sign in
- [x] Change workspace
- [x] Date format MM/DD/YYYY
- [x] Date format DD-MM-YYYY
- [x] Date format MM-DD-YYYY
- [x] Date format YYYY-MM-DD
- [x] Date format DD/MM/YYYY
- [x] Date format DD.MM.YYYY
- [x] 24 hour time format
- [x] 12 hour format
- [x] Duration format Classic
- [x] Duration format Improved
- [x] Duration format Decimal
- [x] First day of the week Monday
- [x] First day of the week Tuesday
- [x] First day of the week Wednesday
- [x] First day of the week Thursday
- [x] First day of the week Friday
- [x] First day of the week Saturday
- [x] First day of the week Sunday
- [x] Manual mode
- [x] Submit feedback
- [x] About
- [x] Help
- [x] Is "Synced" displaying correctly?

## Testing Calendar Integration
- [ ] Are calendar entries showing correctly?
- [ ] Create an entry from a calendar entry
- [ ] Adjust the start time
- [ ] Adjust the end time

## Testing Siri Integration
- [ ] Start a time entry
- [ ] Stop a time entry

## Multiple Workspaces
- [x] Switch workspaces
- [x] Go offline then switch workspaces (Airplane mode)
- [x] Switch between workspaces while timer running
- [x] Is data displaying correctly in web?
- [x] Force sync then switch
- [x] Leave a workspace
- [x] Be removed from a workspace while offline
- [x] Be removed from a workspace with an active entry running

## Testing Interactions/Sync between this app and others
- [x] Edit client on web whilst mobile online
- [x] Delete client on web whilst mobile online and tracking a task
- [x] Edit client on web whilst mobile online and tracking a task
- [x] Tags
- [x] Archiving
- [x] Create new project on web whilst mobile offline
- [x] Tasks
- [x] Try creating new entries on web whilst mobile offline
- [x] Edit client on web whilst mobile offline
- [x] Try stopping timer on web while mobile offline
- [x] Delete project on web whilst mobile offline
- [x] Make changes to projects on web

## Testing in different timezones

- [x] Check

## Testing onboarding

- [x] Check

## Test that the UI is appearing as intended and report any issues

- [x] Check

## Testing specific to this release

- [x] The wheel works fine on Lollipop
- [x] The wheel works on Android > 5
- [x] The wheel doesn't crash even when you stress it 
- [x] Tags are created without their names being truncated
- [x] The lists in select views are sorted alphabetically (#4321, #4277, #4321 and #4281)

**Comment by ApocalypticFish** [comment]
Had a crash when selecting various custom dates on reports, can't replicate but wanted to mention.
Have the amount of requests to the reporting API been limited as well?

**Comment by ApocalypticFish** [comment]
Had another crash when creating an entry through Manual Mode, entered a description, created a new project and created a new tag. Once I hit create on the new tag the app crashed. Sent through feedback for it. Doesn't happen again, but I've seen this type of issue a lot when doing those things in succession in past builds. Intermittent fault. Not sure if the same but it seems similar.

**Comment by heytherewill** [comment]
[AppCenter report](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/4109757680u/reports/2518516938494979999-ec90c06a-70d1-4fb2-90ea-55e9866ed375/threads) says this is a Realm problem. Due to the nature of this bug (and the fact that it happens on the Start Time Entry View, which is being refactored at the moment) I say this should not postpone the release because of it

**Comment by ApocalypticFish** [comment]
Okay, the first issue didn't give me a chance to send feedback either the app blackscreened then kicked me back to the login page. Just FYI

**Comment by ApocalypticFish** [comment]
@heytherewill I'm pretty well done with this. There are a couple of issues I've opened #4429 #4433 #4432

**Comment by heytherewill** [comment]
Properly released!
