### ISSUE TITLE
Reports doesn't show total duration at the top

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#4418]
## 🐛 Bug Report
In reports view the total duration at the top of the view is always 0:00:00

## Context
Build/Branch: daneel 1.17
Phone OS: iOS (haven't tested on android)
Phone model: any

## Expected behavior
To show the correct duration

## To reproduce
Just go the reports view and make sure there are time entries for the selected period.

## Suggestions
Might be rx factoring related

**Comment by sofokli1** [comment]
@amulware do we need a hot fix for this or should this be fixed with the next release?

**Comment by amulware** [comment]
1.18 is scheduled for this week. Please inform support that they can expect messages from users on this, and that we will be fixing it with the upcoming update.

**Comment by Beee4life** [comment]
Good to see I wasn't the only one who experienced this :)
