### ISSUE TITLE
Android Bottom Bar: Create placeholders for pages

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4423]
The bottom bar is cool, but switching pages can be a bit sluggish, specially on the Reports view and most likely the calendar page when it's ready.

We can add a fade transition to reduce a bit of the problem, but ideally, we would need placeholders to show while the data is loading.

**Comment by amulware** [comment]
Do I understand correctly that the idea is to remove the delay between selecting a tab and that tab actually opening (even if the content might take a moment to appear)? If so, yes, that's good, though I'm not surely sure why it takes so long to load the different tabs to begin with.

**Comment by amulware** [comment]
Also, do we need designs for placeholders? Using an empty screen might look even more broken. (?)

**Comment by daividssilverio** [comment]
Yeah, we need proper designs for this.

**Comment by daividssilverio** [comment]
Are you handling this @heytherewill ?

**Comment by heytherewill** [comment]
I am, this is being tackled by #5946

**Comment by AlicjaSuska** [comment]
We can use so called 'skeleton screens' - similar to those used in our web app. Quite straightforward and easy to design. Example:

![1_FiO-dbI17tpUF1A1-nlYPw](https://user-images.githubusercontent.com/20326070/68192887-595c6600-ffb2-11e9-8323-9111463c07ed.png)

**Comment by AlicjaSuska** [comment]
I can add it to design backlog. Probably will be able to get to it within week or two.

**Comment by daividssilverio** [comment]
Hey @maritoggl , is that OK with you? We can schedule this for next release (droid 2.8) if the designs can get done within a week or so. Also, a version of this issue for iOS might be needed.

**Comment by maritoggl** [comment]
I don't see how this can hurt anything, but I'd like us to investigate the reasons behind the slowness and somehow understand how big of a problem it is.

**Comment by semanticer** [comment]
@daividssilverio @maritoggl @amulware So I guess it's time to move this to 2.8 right?

**Comment by semanticer** [comment]
Confirmed by @AlicjaSuska if everything goes well, she should be able to deliver designs for this in time for 2.8.

**Comment by AlicjaSuska** [comment]
![Loading-states](https://user-images.githubusercontent.com/20326070/69540528-15dc9280-0f87-11ea-85b8-d760462ab62f.png)
I've prepared the proposition of loading states - please, share your feedback about improvements :)
Also, do you need me to make propositions for the dark UI as well or they can be translated they way you did so far? @semanticer @maritoggl @daividssilverio

**Comment by daividssilverio** [comment]
Wow! That looks quite nice! @AlicjaSuska !
And yes, propositions for the dark mode would help quite a bunch.

Also, for the main log, shouldn't we replace what currently is the "empty placeholder" with something else other than the "new" loading placeholder? It can be quite confusing.

**Comment by AlicjaSuska** [comment]
@daividssilverio I'm not sure I get it right. For the 'Timer page' we should use:
- skeleton for loading
- empty state with the spider for no results

Is that what you meant above? :)

**Comment by daividssilverio** [comment]
Yes, that's exactly what I meant.
But that's my humble opinion. Please note that we are currently doing:

- skeleton for empty state (which is confusing for some people, because it looks like it's loading something)
- we show the spider when welcoming back an user (not a new user and has no recent time entries).

**Comment by AlicjaSuska** [comment]
I agree with you @daividssilverio . Let's implement the approach discussed above :)

**Comment by AlicjaSuska** [comment]
![Loading](https://user-images.githubusercontent.com/20326070/69644997-b608e900-1065-11ea-8052-28f61d67138a.png)
Here are propositions for dark mode as well. Please, let me know about your thoguhts @maritoggl @daividssilverio

**Comment by AlicjaSuska** [comment]
https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/dashboard?seid=5ddd3f0ce51b2d1b4cae2144

**Comment by maritoggl** [comment]
These look neat, thanks a bunch!

**Comment by heytherewill** [comment]
This kinda depends on #6679. The layouts could be worked on, but without lazy VMs a lot of the purpose is lost
