### ISSUE TITLE
1.11 Date range selection in reports showing wrong month.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4429]
## 🐛 Bug Report
The date range selection is showing the correct date range for the current week at the top 19-02 - 25-02
But it is showing December 1 underneath that.
Showing 19-25th selected in blue and This week highlighted in blue.

![image](https://user-images.githubusercontent.com/18132080/53041852-41c16980-3485-11e9-93a7-e0e09d6b33d7.png)

## Context
New account several hours ago, currently set on Classic time format, the first day of the week is set as Tuesday, 24h mode.

Build/Branch:1.11
Phone OS:8.0.0
Phone model:HTC U Ultra

## Expected behavior
It should be showing February and I'm not sure what the 1 is meant to represent the year?

## To reproduce
Look at date range selection?

## Suggestions
https://www.youtube.com/watch?v=xhy7dXWjpAA

**Comment by ApocalypticFish** [comment]
It starts working after I press a few of the presets like last month etc.

**Comment by VeljkoTN** [comment]
Reported by a user in case #21103865894
