### ISSUE TITLE
EditTimeEntry: Edit time entry description

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4443]
Sign in
Start time entry
Enter description
Save Entry
Stop Entry
Tap on entry
Edit entry description
Confirm/Save

**Comment by ApocalypticFish** [comment]
Hey, I just realised that these will need to be categorised differently and into EditTimeEntryTests which doesn't yet exist

**Comment by ApocalypticFish** [comment]
Added one in #4471

**Comment by arturs105** [comment]
No worries, I had the same idea and had already added exactly the same file 😄
