### ISSUE TITLE
Edit view project selection and auto completion

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#445]
I hope this can reuse the completion from the creation dialog.

It should split the entered string into words and match those against client, project, and task names.

Of course, the user should then be able to choose a project, and upon confirmation, the change has to be persisted.

**Comment by willsb** [comment]
To whoever works here (hopefully me, even though arturs is the one working on the EditView right now): The whole system can be refactored pretty easily to work on both start and edit 😄
