### ISSUE TITLE
Start/stop time edit dialog

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#448]
This will be used for editing the start time, stop time, and choosing the start time when creating a time entry.

See zeplin, poke @pe0ny for designs/functionality.

- [x] Modify `ModalPresentationController` or create a new one for smaller dialogs
- [x] Create the dialog
- [x] Wait for MvvmCross 5.2
- [x] Return selected value from the edit dialog

**Comment by pe0ny** [comment]
Just a note: we don't have option to edit stop time - only start time and duration (which also changes end time)

**Comment by arturs105** [comment]
This was actually closed in #566
