### ISSUE TITLE
Calendar: Handle "Don't ask again" permission requests results

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4491]
When the user selects "Don't ask again" during a permission request, currently we aren't doing anything. This makes the app look irresponsive.

We should show a simple dialog explaining why we need the permission and send the user the system app settings to manually give us the permission.

**Comment by juanlaube** [comment]
Closed by #4577

**Comment by daividssilverio** [comment]
Closed by #4577
