### ISSUE TITLE
iPad version: Modals

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#4499]
- Max width
- Get height from the presented VC preferred height, or use default if not set
- KB behaviour
- Ensure it works as intended on mobile vs narrow split-screen options

For more in-depth details, see https://www.notion.so/Popover-specs-e9f66fb413414155b01fe10a9ac36387

**Comment by sofokli1** [comment]
@dshr Do we just need to port from the other ipad branch here, or do we want so more complex functionality?

**Comment by sofokli1** [comment]
I commented in notion but will add here as well

> ipad 11" landscape needs 40pt top margin because it will conflict with the 360pt min height

**Comment by dshr** [comment]
> Do we just need to port from the other ipad branch here, or do we want so more complex functionality?

While some of the functionality is there in the old branch, we need to implement the new, more complex behaviour too.
