### ISSUE TITLE
Choose start time when creating time entry

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#451]
~~Requires #448~~ Done

- [x] Add the option to select start time when starting a time entry
- [ ] Limit the available range (Chosen date/time must be within X hours, and must be in the past. (X to be decided))

**Comment by pe0ny** [comment]
Start time icon: 
<img width="37" alt="screen shot 2017-09-13 at 08 53 08" src="https://user-images.githubusercontent.com/5064445/30361676-fd5dbcf6-9860-11e7-8559-ca05711f541b.png">

**Comment by willsb** [comment]
>Limit the available range (Chosen date/time must be within X hours, and must be in the past. (X to be decided))

☝️  @pe0ny What's the value of X?

**Comment by pe0ny** [comment]
@willsb I'm not sure but I think he meant that backend allows max duration 999 hours. Which means we also should keep the range same.
