### ISSUE TITLE
Document use of workspace features

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4521]
Let's write a document (on Notion) of which workspace features we use (this should be easily searchable in your favourite IDE), and list exactly what we use them for.

**Comment by kornelijepetak** [comment]
I've left a short [document about this](https://www.notion.so/Workspace-Features-ccdedeb565464b71bddbcc65baaf1491) on Notion.

**Comment by amulware** [comment]
Looking good, thanks!
