### ISSUE TITLE
Write i18n guide and framework

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4523]
## The Guide

I'd like us to write add a guide to our /docs specifying:

- where all the relevant files for translation are
- how to handle/translate these files, including any specific details necessary
- what format a pull request needs to have so we can consider it (let's be as lenient as we can but as strict as we need to)

This document should be written to address our users and make it as easy as possible for them to help us:

- submit a full new translation for a new language we don't support yet
- submit fixes/improvements for already existing translations
- create an issue if something needs fixing in a translation but the user does not feel up for making these changes themselves

We want to make this easy for them to do and guide them in a way that makes it easy for us to review and merge changes.

## The framework

We may want to consider keeping a GitHub project where we organise translation related issues (hard to know how many we'll end up with). This would also allow our users to see what work is required, and help them contribute.

We may need issue templates for these as well. Both for ourselves, and for our users.

And possibly guidelines for ourselves on how to merge translation changes.

Lastly, I want us to consider putting comments into our string resource files about where strings are used, maybe the context around them, etc. to help people translate (and possibly to help ourselves as well). Or if there's a better place to have this information, I'm open to that as well.

## To do

- [x] Write an internal proposal for how the whole i18n process should work
- [x] Discuss and refine that proposal and get it approved by @amulware and @maritoggl 
- [x] Final framework doc on Notion/in our repo (see which makes more sense)
- [x] Write translation guide, markdown, in /docs and make sure @amulware and @maritoggl approve the PR
- [x] Create any necessary issue templates/projects/whatever
- [x] Create any follow-up issues for updating our resource files, or whatever else is needed

**Comment by amulware** [comment]
Please communicate with @maritoggl (and @amulware) from the start, just to make sure we're on the same page.

For example, (if not clear from the above) the current plan is to crowdsource translations from our users and let them PR directly into the repo. If there are other options, we might consider them.

Also, note that our process should account for new copy, and ideally have ways for us to get translated copy before we even release new/changed features.

**Comment by daividssilverio** [comment]
Proposals were posted internally. Please check our internal communication tools.

**Comment by daividssilverio** [comment]
The initial framework has been created. We've already translated the app into Japanese.
