### ISSUE TITLE
Duration input is being reset when editing running time entry

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4524]
## 🐛 Bug Report
While editing a running time entry, its duration is being reset while editing.

## Context
Build/Branch: 1.11.1
Phone OS: Android
Phone model: All, _systemic anomaly_.

## Expected behavior
* Editing duration for a running time entry should change StartTime accordingly
* While the duration is being edited by using the input field, no changes to that input should be happening.

## To reproduce
1. Open app
2. Make sure manual mode is off
3. Tap on play button to create new running TE
4. Tap on duration field on new TE screen
5. Tap on duration, try to enter something
6. Duration field is resetting

## Suggestions
I've noticed while reproducing that it resets it in a timely manner, and my intuition says that it's CurrentTime observable emitting events that end up resetting the input. Check this theory first, might be easy to fix.

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/21165070846)
