### ISSUE TITLE
Duration input not updating in Wheel view for running TE

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4532]
## 🐛 Bug Report
When editing the times for a running time entry, the Wheel view's duration field does not tick as the seconds go by. Changes only do happen when a full minute passes by.

## Context
Build/Branch: 1.11.1
Phone OS: Android
Phone model: All. Systemic anomaly.

## Expected behavior
If a running time entry's times are being edited through the wheel view, the seconds should be visible as they go by on the duration field. (Unless, the duration is being edited, of course).

## To reproduce
* Be in Real-Time tracking mode.
* Start a new TE
* Tap duration to open Wheel view.
* 👀 Look at the duration. Nothing's going on except when full minutes pass by.

## Suggestions
Fix it. 😄

**Comment by amulware** [comment]
Happens on iOS as well, almost just created a duplicate issue. I had the same suggestion.

**Comment by daividssilverio** [comment]
Hey, I think this is fixed, cannot replicate it on droid. Pretty sure it was fixed on #4989.

**Comment by kornelijepetak** [comment]
Yes, this was definitely fixed. Not sure if that's the exact PR, but it was fixed. I remember that. And also, `develop` works fine.
