### ISSUE TITLE
Setting the Start or Stop Time for a TE uses the seconds of the current time

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#4541]
Setting the Start and Stop Times in Manual mode uses the current time's seconds, potentially resulting in Time Entries that are shorter than their apparent length. For example, the wheel may show 9:00 - 9:05, but the new TE's duration ends up being 00:04:47.

## Context

Build/Branch: Giskard 1.11.1
Phone OS: Android 9
Phone model: ONEPLUS A6003_22_190123

## Expected behavior
The new TE created should have a duration that matches the set Start and Stop Time.

## To reproduce
1. Open a computer clock that shows you seconds. Open the app and get it ready.
2. Create a new Time Entry under manual mode when the it’s :00 seconds on the computer clock. Take your time with the next steps.
3. Tap on the Duration of the new TE view (this opens the wheel)
4. Set the Start Time to 9:00AM
5. Set the Stop Time to 9:05AM
6. Tap Save (this closes the wheel)
7. See the Duration now show 4:XX, where XX is the number of seconds that has elapsed between steps 2 and 5 above

## Suggestions
It looks like this is unintended behavior. Per @amulware "changing start/stop time manually should always set the seconds component to 0".

[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100764/conversations/21089583473)

**Comment by TheSoloJake** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/21115099092)

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/21183879936)

**Comment by ricotheque** [comment]
[case](https://github.com/toggl/mobileapp/issues/4541)

**Comment by VeljkoTN** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21283479663)

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100764/conversations/21337421163)

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/21319841759)

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21308813050)

**Comment by VeljkoTN** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21345153107)

**Comment by VeljkoTN** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21351587509)

**Comment by ricotheque** [comment]
Hey guys, I need to reopen this issue. 

Unfortunately I still encounter this while running 1.14 Giskard. In fact, I can't no longer make the extra seconds disappear if I try creating a new Time Entry when it's 0 seconds after the current minute.

Build: Giskard 1.14 (402890)
OS: Android 9
Phone ONEPLUS A6003_22_190123

1) Open mobile app
2) Hold down play button to create a new Time Entry under manual mode
3) Tap duration on the bottom left of the create Time Entry view
4) See "Duration" field in the middle of wheel show "0:30:00"
5) Tap "Duration" field
6) Type in "800" to indicate 8 hours
7) Press check button on numeric keypad to confirm 
8) See "Duration" now show "07:59"
9) Tap "Save"
10) Tap "Save"
11) Tap on Time Entry on main view to edit it again
12) Tap on "Start time" or "End time" field
13) See "07:59:XX" on "Duration" field (On my end, I saw "7:59:51")

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100764/conversations/21873122663)

**Comment by amulware** [comment]
Please create a new issue linking to this one instead.
