### ISSUE TITLE
App crashes when navigating to the settings page

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4553]
It happened all of the time for @maritoggl in the last adhoc test build.

Might be worth it to open the settings with the last build using different devices and see what gives.

When it happens: Sometimes, when you don't have a profile pic set up.

**Comment by maritoggl** [comment]
Tested with moto g6 (XT1925-5), Android 8.0.0

**Comment by daividssilverio** [comment]
This seems to be a bug from 1.11.1.
Let's revisit this if we have time when we are done with the calendar bugs/testing.

**Comment by amulware** [comment]
I definitely want this fixed for 1.12. Whether we include the calendar or not.

**Comment by juanlaube** [comment]
I'm removing myself from this until I'm done with the calendar.

**Comment by maritoggl** [comment]
Happens if the user has no avatar set.
