### ISSUE TITLE
Siri: Tapping the response UI should open edit view

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4559]
When starting or stopping time entries through Siri, tapping the response UI opens the app.

Ideally we would open the edit view for that entry. This probably needs syncing first, so it might not be to easy, and maybe it takes too long for the user to wait for it to show up. Still we should try to see if it makes sense.

**Comment by khoi** [comment]
https://github.com/toggl/mobileapp/issues/4538#issuecomment-470662949

**Comment by khoi** [comment]
Internal discussion regarding the issue can be found @ https://twist.com/a/79709/ch/195005/t/768530

**Comment by Odrakir** [comment]
The discussion got lost in Twist, but this is how it started:

> This potential feature showed up during the Siri Improvements project, but I’m not sure if it makes sense and I want other opinions.
>
>When you start an entry using Siri, we show a small UI inside of Siri’s interface with the Description of the entry (Or “No Description”) and a timer ticking. Tapping that UI opens the app.
>
>The idea is that it’ll also open the edit view for that new time entry.
>
>The problem is Siri works with the server, not the app, and though there’s a flag forcing the app to sync, we would need sync to finish in order to show that UI, and as it takes some seconds, maybe it’s a little weird for the edit view to appear after that time.
>
>Alternatively we could store some information about the TE in the private shared storage (instead of the force sync flag), show a UI from that info, and then merge whatever the user does with what’s on the server somehow… But I’m not sure if that’s worth the trouble.
>
>Any thoughts?
