### ISSUE TITLE
Handle deleted accounts

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#4574]
Currently when you are logged into an account and delete that account on the web app, you are redirected to token reset view, but the thing is, the token can't be reset, because the account does not exist anymore. A simple screen with a message saying that the account has been deleted should be enough.

**Comment by amulware** [comment]
Do we need this @maritoggl? I'm hesitant to add UI for a very niche use case. Even right now, users can simple 'logout' from the token-reset screen in this case, so they won't get stuck.

**Comment by maritoggl** [comment]
Indeed. I appreciate you catching this, but I don't see this getting priority at the moment.
