### ISSUE TITLE
The two columns layout won't always be in sync with settings

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4596]
To replicate:

1. Accept the calendar permissions at least once.
2. Link at least one calendar.
3. Close the app (optional).
4. Remove the calendar permissions from the app in the system settings.
5. Re open the app.
6. Go to the settings page.
7. Click calendar calendars button.
8. Enable some calendars.
You should see the previously selected calendars already selected (not good) in the calendars list.
9. Press done.
Go to the calendars page. You shouldn't see the two columns layout yet, even though you have calendars enabled. (That's the main bug). If you press the `Link calendars` button, it will sync and the two columns will appear immediately.

The source of this problem is probably the same as #4557.

**Comment by juanlaube** [comment]
Closed by #4625
