### ISSUE TITLE
Test the calendar features on android 23, 24 and 25

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4599]
That's essentially the same that has to be don on #4598, but now with permissions, the app should ask for calendar permissions when using calendar features.

- [x] It doesn't crash on a fresh login/sign up
- [x] It doesn't crash when you close the app and re-open it.
- [x] You can open all the four pages and interact with them
- [x] You can click to edit a time entry in the main log
- [x] You can see the changes in the calendar page when you do so
- [x] You receive calendar notifications when you've set a smart alert
- [x] You receive calendar notifications when you've set a smart alert and re-booted the device/emulator.

**Comment by ApocalypticFish** [comment]
If the app has been in the background and you create an entry from the calendar it doesn't update on the calendar but shows on the timer page.

**Comment by daividssilverio** [comment]
I'm closing this issue as there's nothing platform specific happening. Testing has been done. Similar to #4598 I also found some crashes related to some thread marshalling problem.
