### ISSUE TITLE
Test the calendar features on android 26, 27, 28 and 29

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4600]
Essentially the same as #4598, but let's focus on the notifications and making sure they work after a device reboot.

- [x] It doesn't crash on a fresh login/sign up
- [x] It doesn't crash when you close the app and re-open it.
- [x] You can open all the four pages and interact with them
- [x] You can click to edit a time entry in the main log
- [x] You can see the changes in the calendar page when you do so
- [x] You receive calendar notifications when you've set a smart alert
- [x] You receive calendar notifications when you've set a smart alert and re-booted the device/emulator.

**Comment by juanlaube** [comment]
I tested using emulators for Android 27 and 29 and real devices for Android 26 and 28.
