### ISSUE TITLE
Test calendar view

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4602]
What and how should it be working now?

- [x] it should only one column when there's no calendars linked
- [x] it should show two columns when calendars are linked, even when there's no events in that day
- [x] it should show the sum of time logged in the current day's worth of time entries
- [x] clicking on a calendar event should create another time entry with the event description as the time entry description and having the same start time and duration
- [x] clicking on an empty space in the time entries column should create a time entry with 30 minutes of duration and no description, it should open the edit view immediately

**Comment by juanlaube** [comment]
@daividssilverio when tapping on an empty space, it creates a time entry in the database, I think we should show the start time entry view, but don't create the TE unless the user saves it, what do you think?

**Comment by juanlaube** [comment]
I couldn't find more bugs, but I will do another pass in the latest build.

**Comment by daividssilverio** [comment]
Feel free to close this issue when you are satisfied with your tests on the calendar @juanlaube .

**Comment by juanlaube** [comment]
This can be closed now, I didn't find any other bug in the calendar view.
