### ISSUE TITLE
Report bar charts missing on app stratup

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#4613]
## ⛑️ User Support

A user reported that the bar charts are missing on the Report page in the app. We tested this on our end and found that if you change the date range or click anywhere else that's clickable and go back to reports the bar charts will appear. 

## About the user

App version: Daneel 1.18
Phone OS: iOS 12.1.4
Phone model: iPhone 6s

## Expected behaviour
The bar chart should be there on app startup when it's first viewed without having to navigate away from it or change the date range

## To Reproduce
1. Close out the app completely if you can see the bar chart at the moment, if you can't see it skip this step,
2. Go to check out the Repor - the bar chart should be missing
3. Change the date range or click on the calendar or navigate away and go back to the report page and the bar chart should appear.

NOTE: if you close out the app and re-start it the bar chart should be gone again.

**Comment by amulware** [comment]
Does this occur on Android? If so, please add it to the 1.13 project.

**Comment by VeljkoTN** [comment]
It does not occur on Android, just tested it.
