### ISSUE TITLE
Daily total in timer view does not update after adding more than one time entry 

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#4614]
## 🐛 Bug Report
Daily total in main timer view does not update after adding new time entries after the first one. 

## Context
While testing the grouped time entries feature on iOS, noticed that when I added a first time entry of the day, the daily total duration was valid. After adding a second, third etc time entry, the daily total did not update and stayed as the total of the first time entry that was created. 

Tested also with 1.19 and couldn't reproduce the same issue, so should be specific to 1.20 only I think. 

Build/Branch: 1.20
Phone OS: 12.1.4
Phone model: iPhone 7

## Expected behavior
Daily total updates when adding new time entries to the day.

## To reproduce
1. Create a time entry
2. Check the daily total - all should be good and matching
3. Create another time entry to the same day
4. Check the daily total - it still shows as the total of the first time entry that was created

**Comment by simonrozsival** [comment]
This is related to #4564. The durations are calculate correctly, but the headers are not reloaded by the diffing algorithm.

**Comment by simonrozsival** [comment]
Fix was merged into the project branch.
