### ISSUE TITLE
Improve hiding of reports calendar

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#4616]
When tapping the navigation bar to reveal the reports calendar, it animates really nicely and we can hide the calendar by scrolling downwards. However the scrolling to hide it is subpar as it does not have inertia. It should be possible to hide the calendar with a simple flick upwards, but it is not - i have to scroll until the calendar disappears and default iOS scrolling kicks in. We should make hiding the calendar more iOS like.

**Comment by amulware** [comment]
I assume this is no longer relevant after the rewrite.
