### ISSUE TITLE
Show tags when editing inaccessible time entry

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4617]
Ref #2902

When an inaccessible TE is visible, the tags row should be visible, but user shouldn't be able to tap on it and open the tags selection view (which would be empty). Currently the tags row is hidden, which is not the correct behavior.

**Comment by kornelijepetak** [comment]
Removing `Android` label. This is a purely iOS issue.

The Android does not hide rows for quite some time now.
