### ISSUE TITLE
Calendar item is unreadable when duration is short

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4621]
## 🐛 Bug Report
The calendar item text is unreadable when the duration is too short. See the attached screenshot.

## Context

Build/Branch: `project/calendroid`
Phone OS: Android
Phone model:

## Expected behavior
The text should be readable regardless of the item height, we could change the margins or resize the text (iOS does both for example).

## To reproduce
Have an item with duration <= 15 mins

![Screenshot_1552416582](https://user-images.githubusercontent.com/8163330/54227493-ca5c8400-44de-11e9-9e4a-341c9ff2434f.png)

**Comment by daividssilverio** [comment]
Closed by #4650
