### ISSUE TITLE
The calendar view doesn't observe time entry changes sometimes

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4623]
## 🐛 Bug Report
Sometimes when creating or editing time entries from the timer tab, or even when editing time entries from the calendar tab, the calendar view doesn't reflect the changes.

## Context

Build/Branch: `project/calendroid`
Phone OS: Android
Phone model:

## Expected behavior
The calendar should reflect the changes.

## To reproduce
Create or edit time entries.

**Comment by daividssilverio** [comment]
Closed by #4624
