### ISSUE TITLE
Select user calendars view settings don't respect selected calendars sometimes

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4651]
This is one edge case, but it happens like this:

1. Go to the settings view
2. Go to Calendar settings
3. Click on the link calendars switch
4. Select some calendars
5. Click twice on the link calendars switch (disable and enable again)
6. You should see the previously selected calendars (before disabling the switch) still selected
7. Press done
8. You end up with no calendars selected

Desired behaviour: What you see is what you should get.
Why should we care? Users can misclick and disable the switch by mistake, clicking again and seeing the calendars still selected would give the wrong idea.

It would be nice have this fixed (and we will fix it), but I don't think this has high priority.

**Comment by juanlaube** [comment]
Closed by #4709
