### ISSUE TITLE
Android App freezes when editing groups

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4662]
Currently the app freezes when editing/deleting multiple time entries. It just freezes for a while, then it starts working again.

It doesn't take too long for groups of 2 or 3 time entries, but you can start feeling the lag on groups of 4+ time entries.

- [x] The app shouldn't freeze when editing groups of time entries, regardless of the size of the group.
- [x] The app shouldn't freeze when deleting groups of time entries from the edit screen, regardless of the size of the group.
- [x] The app shouldn't freeze when deleting groups of time entries when swiping in the main log, regardless of the size of the group.
- [x] The main log shouldn't freeze groups of time entries are edited/deleted

**Comment by kornelijepetak** [comment]
We got the point. The app shouldn't freeze 😄

**Comment by kornelijepetak** [comment]
So far we've gone with batch updates and we need to see how it behaves on device in another test run.
