### ISSUE TITLE
Calendars cells are not being recycled in the UserCalendarsRecyclerAdapter

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4665]
Steps to replicate:

Have a bunch of calendars. Enough to fill like 1.5 screens.
Scroll a few times. You'll notice how some calendar names start showing wrong items.

Setting `HasStableIds` to false in the constructor should do the job.
```
protected BaseSectionedRecyclerAdapter()
        {
            HasStableIds = true;
        }
```

**Comment by juanlaube** [comment]
Closed by #4682
