### ISSUE TITLE
Calendar events are all white on Android 21-22

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4667]
How to replicate:

Try the app on android 21-22.
Both calendar events and time entries are all white.

Screenshot for reference.
![Screen Shot 2019-03-14 at 6 07 33 PM](https://user-images.githubusercontent.com/2173493/54394826-5cea5800-4684-11e9-8d57-f07f2476a934.png)

**Comment by juanlaube** [comment]
Closed by #4689
