### ISSUE TITLE
Link calendars button on onboarding needs more horizontal padding

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4668]
It looks weird on smaller devices.
Testing on Android 21,22,23 it looked like this:
![Screen Shot 2019-03-14 at 5 45 48 PM](https://user-images.githubusercontent.com/2173493/54395755-206c2b80-4687-11e9-9c8e-9c4d4db552dd.png)

**Comment by juanlaube** [comment]
Closed by #4683
