### ISSUE TITLE
Android flavors app icon

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4696]
We need different app icons to differentiate between `Toggl`, `Toggl for Tests` and `Toggl for Devs`, it's easy to confuse them when having all the builds installed, just see this screenshot.

![Screenshot_20190318-083432](https://user-images.githubusercontent.com/8163330/54528058-8b08ba00-495a-11e9-8f21-e9d9c6561d52.png)

For simplicity, I propose we change the logo color for `Toggl for Tests` and `Toggl for Devs`, but we can also add a banner of some kind.

**Comment by heytherewill** [comment]
IMO this should follow the pattern of using 🚧 stripes + desaturation that we currently have on iOS.
