### ISSUE TITLE
The syncing bar doesn't retract after a successful sync

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4723]
The syncing bar stays there saying ":white_check_mark: Synced" and it won't retract until you stroll the table view a bit. Not a bit deal, but it looks weird.

**Comment by simonrozsival** [comment]
It doesn't happen all the time and I'm not sure what causes it. Maybe we don't have to deal with that right now.

**Comment by simonrozsival** [comment]
I'm removing this issue from the project for now.

**Comment by amulware** [comment]
We should still do a proper rewrite of the sync indicator at some point. Closing this for now, since we won't address it any time soon.
