### ISSUE TITLE
App sometimes crashes when swipe-deleting TEs

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4724]
I "stress tested" the app by adding and continuing and swipe deleting TEs and after one swipe-to-delete the app froze for a few seconds and then it showed me this exception which was thrown at this spot:

![image](https://user-images.githubusercontent.com/374616/54610902-3cd8e100-4a56-11e9-89c3-e74d82492cab.png)

Apparently we update the underlying data structure before we diff and update the UI which still tries to display some of the sections and rows.

**Comment by simonrozsival** [comment]
Update: the app crashes every time you delete the last time entry from a section.

**Comment by simonrozsival** [comment]
(and it doesn't matter if it's using swipe to delete, the edit view, or when syncing)

**Comment by Odrakir** [comment]
🤔 Not to me. I did manage to make it crash by adding and deleting really fast, but I can delete the last entry with no problems.

**Comment by simonrozsival** [comment]
I experienced the same crash now that I had just one item and I did a pull-to-refresh:

![image](https://user-images.githubusercontent.com/374616/54624343-7c5ef780-4a6d-11e9-8f8a-35c6a480c42b.png)

**Comment by Odrakir** [comment]
Maybe it has something to do with #4727 ? Did you delete any entries prior to that?

**Comment by simonrozsival** [comment]
Fix was merged into project branch.
