### ISSUE TITLE
GTE: Deleting entries doesn't delete them from the server

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4727]
Steps to reproduce:
- Open the app and the web at the same time
- Insert an entry, see how the web updates instantly
- Delete any entry (or group of them). Wait for the undo message to disappear
- See how the web doesn't refresh
- Force sync in the app, deleted entries don't show back
- Restart the app, there they are!

**Comment by simonrozsival** [comment]
This issue was already fixed, but we did not close the issue, I'm closing it now manually.
