### ISSUE TITLE
Enable Nullable Reference Types

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4732]
This works in Visual Studio 2019 preview, so we can already start working on it.

We need to add the following to our `.csproj`s:

```xml
<LangVersion>8.0</LangVersion>
<NullableContextOptions>enable</NullableContextOptions>
<WarningsAsErrors>CS8600;CS8602;CS8603</WarningsAsErrors>
```

After that, we just have to whack-a-mole our way into making the project build again. 

How hard can it be?®

**Comment by kornelijepetak** [comment]
> How hard can it be?®
Very hard. 😛
