### ISSUE TITLE
Ensure all projects build on Bitrise for each commit

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4738]
It appears we're at least not building the ui-test projects. Otherwise, this could not have sneaked in:

https://github.com/toggl/mobileapp/blob/9a2702d8b12082474aeb6b30a1409aa278e9e911/Toggl.Daneel.Tests.UI/IosAccessibilityNames.cs#L95-L115

Let's go over all projects and make sure they are all included in the relevant build configs.

**Comment by heytherewill** [comment]
They are
