### ISSUE TITLE
Setup AppCenter for Adhoc builds

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4744]
We'll have to update `TogglApplication:OnCreate` on Android and `AppDelegate:FinishedLaunching` on iOS using the new app secrets for Android and iOS respectively.

We'll have to update `build.cake` and add something to replace the new app secrets:
The release app secrets are replaced on `GetAndroidTogglApplicationTransformation` and `GetIosAppDelegateTransformation` for reference.

Currently we use the build defined variable `USE_ANALYTICS` to tell if we use AppCenter or not. We might need to create another variable because iOS uses that for more than AppCenter.

Let's make sure the new AppCenter configuration is **only enabled for AdHoc builds**, **it shouldn't affect the current release configuration** and **it shouldn't be enabled for debug builds**.

Create extra issues as necessary.

**Comment by amulware** [comment]
New app configs are setup on AppCenter, you can find them, and the relevant secret keys there.
