### ISSUE TITLE
Ensure there can only ever be one running time entry when pulling data

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#476]
Otherwise, :boom:

Followup to #437.

How to do it (roughly?), according to frontend:

> We have 2 running time entries after a pull. We compare the ats and determine the later one - that one will remain running. The other one needs to be stopped. The stop time of the other one becomes **the start of the "next" time entry (going forward in time) or now if there isn't one**.
>
> This should work for most cases where the user has started a TE on an offline-device, then started another one on another device and eventually these have both ended up in the webapp (one coming from our store and the other from the server) regardless of which whether is "ours" or "theirs" is newer.
>
> Additionally, since the automatically calculated stop time may still not be correct we could try to be polite and display a notification that tells the user to double check the time entry.

(emphasis mine)

Apart from the bold part, this could be implemented by adding a more complicated batch update method, something like this:

```
public IEnumerable<TModel> BatchUpdate(
	IEnumerable<TModel> entities,
	Func<TModel, Expression<Func<TModel, bool>>> matchEntity,
	Func<TModel, TModel, ConflictResolutionMode> conflictResolution,
	Func<TModel, Expression<Func<TModel, bool>>> areRivals,
	Func<TModel, TModel, (TModel, TModel)> fixRivals)
{
	Ensure.Argument.IsNotNull(entities, nameof(entities));
	Ensure.Argument.IsNotNull(matchEntity, nameof(matchEntity));
	Ensure.Argument.IsNotNull(conflictResolution, nameof(conflictResolution));

	var resolvedEntities = new List<TRealmEntity>();

	var realm = Realms.Realm.GetInstance();
	using (var transaction = realm.BeginWrite())
	{
		var realmEntities = realm.All<TRealmEntity>();

		foreach (var entity in entities)
		{
			var oldEntity = (TRealmEntity)realmEntities.SingleOrDefault(matchEntity(entity));
			var resolveMode = conflictResolution(oldEntity, entity);
			var resolvedEntity = resolveEntity(realm, oldEntity, entity, resolveMode);

			if (resolvedEntity != null)
			{
				resolvedEntities.Add(resolvedEntity);
			}

			if (resolveMode == ConflictResolutionMode.Create || resolveMode == ConflictResolutionMode.Update)
			{
				var rival = (TRealmEntity)realm.All<TRealmEntity>().SingleOrDefault(areRivals(entity));
				if (rival != null)
				{
					(TModel fixedEntity, TModel fixedRival) = fixRivals(resolvedEntity, rival);
					resolvedEntity.SetPropertiesFrom(fixedEntity, realm);
					rival.SetPropertiesFrom(fixedRival, realm);
				}
			}
		}

		transaction.Commit();
	}

	return resolvedEntities;
}
```

Except that the bold part needs another query, and things become a bit of a mess potentially.

Also, we really don't wanna run the `areRivals` query for every entity persisted, but only for those that can potentially have rivals (i.e. running time entries), so that adds a bit more complication.

**Comment by simonrozsival** [comment]
I edited the code snippet - changed `var rival = (TRealmEntity)realmEntities.SingleOrDefault(areRivals(resolvedEntity));` to `var rival = (TRealmEntity)realm.All<TRealmEntity>().SingleOrDefault(areRivals(entity));`
