### ISSUE TITLE
Do not keep invisible time components when editing time

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#4765]
## 🐛 Bug Report
I believe that when editing time, even though we don't allow editing seconds, but only full minutes, the seconds component of the respective time (start/stop/duration) is maintained. It should not be.

Instead, when editing either of the three components, it should set it to the exact value.

**Comment by VeljkoTN** [comment]
[Case link 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21283479663)

**Comment by amulware** [comment]
Duplicate of more accurate https://github.com/toggl/mobileapp/issues/4541
