### ISSUE TITLE
Check use of ObserveOn in platform code

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#4774]
This has been spotted in Giskard, but it might be happening in Daneel too. When subscribing to an Observable (or Driver) that comes from the VM there's some times an unnecessary `ObserveOn(SynchronizationContext.Current)`. 

Those Observables should already be exposed on the main thread from the VM.

**Comment by daividssilverio** [comment]
There doesn't seem to be any `ObserveOn` on the view model's exposed observables in any view code on Android.

I think it's safe to close this. Unless you meant to check `ViewModels`.

@Odrakir @heytherewill

**Comment by heytherewill** [comment]
No need to change VM behavior for this
