### ISSUE TITLE
Automatic builds not working

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#478]
Both @pe0ny and me have trouble running the current builds.

For both of us the first time we try to login it shows the error message, and the second time it crashes for her, while I keep getting the error.

**Comment by willsb** [comment]
The problem has already been identified and options for fixing it are on slack

**Comment by amulware** [comment]
Fixed for now by using Debug builds for testing. Won't close this, because we need to fix release builds too.

**Comment by amulware** [comment]
We mostly sorted this out.
