### ISSUE TITLE
Trying to create a project or tag isn't showing the create project or tag prompt

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4798]
## 🐛 Bug Report
Trying to use the project button to create a new project, on a new time entry, isn't showing the create

## Context
New account just created
First new entry created

Build/Branch: 1.12
Phone OS: 8.0
Phone model: HTC U Ultra

## Expected behavior
To have the prompt show with "create x as new project/tag"

## To reproduce
New signup
Start time entry
Enter description
Press project or tag button above keyboard
Type name in
Prompt to create new project or tag isn't displayed
(Also confirmed this isn't occurring with @ or # as well)
Reproduced this multiple times, restarted the app and reproduced, reinstalled and reproduced as well.
![image](https://user-images.githubusercontent.com/18132080/55024407-1212fd80-4fff-11e9-8503-c8e69449f807.png)

## Suggestions
![image](https://user-images.githubusercontent.com/18132080/55024434-21924680-4fff-11e9-9849-eeb7124fb5b1.png)

**Comment by ApocalypticFish** [comment]
I can add them through the edit time entry menu, but not through creating one.

**Comment by amulware** [comment]
If this one slipped through, please make sure to test the entire start-view thoroughly.

**Comment by juanlaube** [comment]
This is a layout issue in the recycler view, the create tag or create project items are visible when scrolling up. I couldn't find a fix yet.

**Comment by juanlaube** [comment]
@daividssilverio feel free to grab the issue if you're working on this.
