### ISSUE TITLE
Duration isn't changing if manually typed and saved

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4799]
## 🐛 Bug Report
When editing an entry and changing duration if manually typed and not changed through the wheel it is not saved.

## Context
Editing an existing entry with no description, projects or tags
It seems to happen when the new duration is less than the old duration

Build/Branch:1.12
Phone OS:8.0
Phone model:HTC U Ultra

## Expected behavior
To save the new duration 

## To reproduce
Edit an existing entry
Click on the start or end time to show the wheel
Click on the duration and edit it by typing in a time
Click save
On the time entry edit view it will appear as it was before you changed it.
The edited time
![image](https://user-images.githubusercontent.com/18132080/55028380-d466a280-5007-11e9-89ab-30c56d80eb00.png)
After clicking save
![image](https://user-images.githubusercontent.com/18132080/55028391-daf51a00-5007-11e9-9fb5-4750b0790a70.png)

## Suggestions
![image](https://user-images.githubusercontent.com/18132080/55028509-2c050e00-5008-11e9-9afa-cd317bece29a.png)

**Comment by amulware** [comment]
Do you mean **duration**, instead of **description**?
