### ISSUE TITLE
+ and play icon not appearing after switching to manual mode

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/mobileapp#4801]
## 🐛 Bug Report
Use the app for some time maybe several hours, create a few entries, access reports then switch manual mode on and the + icon doesn't display, switch manual mode off and the play icon doesn't show. Just the green circle is displayed

## Context
Used the app for some time previously and left it open

Build/Branch:1.12
Phone OS:8.0
Phone model:HTC U Ultra

## Expected behavior
Play button and + icon should show

## To reproduce
~Use the app for a little while then switch Manual mode on~
Updated (and consistent) [repro steps](https://github.com/toggl/mobileapp/issues/4801#issuecomment-477172042)

## Suggestions
![image](https://user-images.githubusercontent.com/18132080/55031215-6a053080-500e-11e9-8718-705952d59a68.png)

**Comment by kornelijepetak** [comment]
This seems to be a bug in Android code.
https://issuetracker.google.com/issues/111316656

I've tried some workarounds I could think of, but I was unable to produce a consistent change of button image.

**Comment by kornelijepetak** [comment]
This can be easily replicated like this:

1. Set to Timer mode in settings.
2. Start a TE by pressing Green Play button
3. Save the TE.
4. Stop the TE by pressing Red button.
5. Open settings.
6. Switch to manual mode
7. Switch to Timer screen again

The bug basically manifests itself whenever setting an image after there has been a change in visibility in FAB.

**Comment by daividssilverio** [comment]
I'm guessing we should re-open this issue since #6597 has been merged. Please check #6597 to understand why we've decided to go this way. @amulware @kornelijepetak @heytherewill
