### ISSUE TITLE
Make Android swipe to delete/continue actions more robust

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#4805]
Android swipe to delete/continue time entry actions are responsive even to the slightest swipes, making people accidentally delete or continue their time entries while they simply wanted to scroll their log up or down. 

The same feature on iOS is nice. Slight swipe makes the continue/delete button appear, after which the button can be tapped to proceed with the action. In order to continue/delete an entry purely by swiping, the swipe gesture needs to be made over at least half the screen. 

Let's make the swipe to continue/delete action a bit more robust for Android as well in order to prevent users from accidentally losing their data by unwantedly deleting it.

**Comment by amulware** [comment]
I don't know if we have this much control. Can we investigate and see what's possible here? What do other Android apps do?
