### ISSUE TITLE
Log in view UI fixes

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#482]
- [x] Check back, 'Log in', and next font sizes and weights from zeplin - these don't seem to be correct
- [x] Back/next are not aligned correctly in login view (check padding 16pt from left and right)
- [x] Remove 1password icon from login view since it won't be needed in beta (low prio)

**Comment by amulware** [comment]
On the 1password icon: Why remove something that works?

**Comment by pe0ny** [comment]
I tap and tap and nothing happens - I assumed it does not work.

**Comment by willsb** [comment]
The tappable area in the login buttons is bad. Enlarging it is the same effort as removing, so I'll just make the button better 😄

**Comment by pe0ny** [comment]
@willsb Left/right margin looks nice 🙌
How about the first point? Font-size should be 14pt but i'm pretty sure it's 15 or 16 atm.
