### ISSUE TITLE
Empty state view is visible after creating first time entry

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4820]
## About the bug
The empty state is visible after creating the first time entry, this is the spider view (sign in) or the fake time entries (sign up).

App version: 1.12
Phone OS: Android
Phone model:

## Expected behaviour
The empty state view shouldn't be visible after a time entry is visible in the main log.

## To Reproduce
1. Sign up, or sign in with an account without time entries
2. Start and stop a time entry
3. Empty view is visible

**Comment by arturs105** [comment]
To me it seems like this is solved. I couldn't replicate neither the fake time entries view neither the spider view - the both were hidden after i stopped the time entry.

I'd like for another person to verify this before closing this issue.

**Comment by kornelijepetak** [comment]
I can confirm that this does not happen on 1.12.

**Comment by juanlaube** [comment]
I cannot reproduce this again, but I'm sure I saw this yesterday 🙂
