### ISSUE TITLE
Add comments to string entries on Resources.resx to facilitate translations

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#4830]
This is what it is.
After #4827 #4828 #4829 are done, we can add some context in the strings comments to facilitate translations.

The idea is to have a section telling where the copy is located in the app.
Something like:
```
<data name="LastWeek" xml:space="preserve">
        <value>Last week</value>
        <comment>Where: 
On Android:
Reports Tab > Click on the Toolbar down arrow > Check the buttons to quickly select reports periods below the calendar
On iOS: Somewhere </comment>
    </data>
```

**Comment by amulware** [comment]
This is a lot of work, how will this be organised as a single issue?

**Comment by heytherewill** [comment]
Work started in #6385, so just go to that issue and add comments at will!
