### ISSUE TITLE
incorrect project creation cell text 

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4842]
## 🐛 Bug Report
project creation cell shows incorrect text

## Context
Build/Branch: `release/daneel-1.20-ifni`

## To reproduce
Create entry with the format:
`abc #tagb #tabod @udi`

![image](https://user-images.githubusercontent.com/6994441/55227316-be482480-5249-11e9-875e-8d52ec034352.png)

## Expected behavior
The cell should shows `Create project "udi"`

**Comment by simonrozsival** [comment]
Fix was merged into a release branch.
