### ISSUE TITLE
incorrect tag creation cell text

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4843]
## 🐛 Bug Report
tag creation cell shows incorrect text

## Context
Build/Branch: `release/daneel-1.20-ifni`

## To reproduce
Create entry with the format:
`abc #kd`

![image](https://user-images.githubusercontent.com/6994441/55227387-f2234a00-5249-11e9-9a05-d4f1f59d4868.png)

## Expected behavior
The cell should shows `Create tag "kd"`

**Comment by simonrozsival** [comment]
Fix was merged into release branch.
