### ISSUE TITLE
Create a presenter for Fragments

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4854]
Depends on #4852 
Depends on #4871

We need to create an AndroidPresenter that is capable of displaying ViewModels that are associated with Fragments

**Comment by daividssilverio** [comment]
Do we really?
Our non-dialog fragments work with nested viewModels, all we have to do is set the right viewModels on the fragments when showing them and everything should work alright, unless I'm missing something.

**Comment by heytherewill** [comment]
I think you are correct. After an internal discussion with @maritoggl we are allowed to change the only non-modal fragment that is not nested (the WorkspaceFragment in the create project view). I will use this issue as a way to track it there and from there on we can see what we do.
