### ISSUE TITLE
Create a presenter for Tab Item ViewControllers

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4860]
Depends on #4852

We need to create an IosPresenter that is capable of displaying ViewModels that are associated with Tab Item ViewControllers

**Comment by juanlaube** [comment]
We don't need a tab presenter after all, fixing the tabs loading is much easier than adding a tab presenter and allows us to hold the reference to the child view models, something we cannot do with the navigation service.
We can see later if we want to improve how we create the view models and view controllers, but right now this is enough.
