### ISSUE TITLE
Make ReactiveViewController call the appropriate VM lifecycle methods

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4864]
Depends on #4863 

We need to define what methods of UIVIewController map to the ViewModel lifecycle methods we decide to stick to when working on #4863. Then we need to make `ReactiveViewController` call those methods.

**Comment by juanlaube** [comment]
`ReactiveViewController` (and the ugly table counterpart) already call some of the lifecycle methods.

We still need to:
- Call `ViewDestroyed` on dismiss and removing from parent
- Call `DetachView` after `ViewDestroyed`
- Review the already existing lifecycle calls
