### ISSUE TITLE
Make ReactiveActivity call the appropriate VM lifecycle methods

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4865]
Depends on #4863
Depends on #4871

We need to define what methods of `Activity` map to the ViewModel lifecycle methods we decide to stick to when working on #4863. Then we need to make `ReactiveActivity` call those methods.

**Comment by daividssilverio** [comment]
The Activity lifecycle is alright.
We could use different strategies, but for our purposes and how everything is setup right now, it makes sense to have:

`OnCreate` -> `ViewModel.Attach` (Activity reference is there)
`OnDestroy` -> `ViewModel.Detach` (Activity is going to be lost)

`OnStart` -> `ViewModel.ViewAppearing`
`OnResume` -> `ViewModel.ViewAppeared` (view is visible)
`OnPause` -> `ViewModel.ViewDisappearing` (view can be visible or invisible, might disappear)
`OnStop` -> `ViewModel.ViewDisappeared` (view is invisible)

Right now we are not using the lifecycle to release resources when we are not using them. But we can do it if necessary later.

**Comment by heytherewill** [comment]
Fair enough
