### ISSUE TITLE
Figure out and implement a new TopActivity service

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#4871]
The solution can probably be largely dependent on the existing implementation that we are using over MvvmCross' implementation. We need to think this through, though, since it is a very important part of the application.

Also, we need to scan the app for classes that inherit from `MvxTask` and make sure that the new system will allow those classes to work.

**Comment by daividssilverio** [comment]
To completely remove the need for the TopActivity, we'll need to complete the following:
- [x] Replace the usages of IDialogService with the IView implementations on Droid
- [ ] Replace the usages of IDialogService with the IView implementations on iOS
- [ ] Replace the usages of IPermissionsService with the IView implementations on Droid
- [ ] Replace the usages of IPermissionsService with the IView implementations on iOS
- [ ] Replace the `TogglPresenter` mechanism to close Views.

**Comment by heytherewill** [comment]
Further, we need to:

- [ ] Get rid of the Google Service on iOS
- [ ] Get rid of the Google Service on Android
- [ ] Remove the unused service for good: `IDialogService`, `IPermissionsService` and `IGoogleService`
