### ISSUE TITLE
Issue with tags in hebrew

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#4874]
## ⛑️ User Support

A user reached out saying that when they edit an existing time entry and try to change an existing or allocate a new tag, considering that their selected language is Hebrew, all tags names are aligned to the right and are not visible. 

![image](https://user-images.githubusercontent.com/36152180/55325356-2171cb00-5485-11e9-9b75-e6aa4ca86f75.png)

[Case link 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21436355738)

## About the user

App version: Giskard/1.11.1
Phone OS: Android 6.0
Phone model: LG-H815 (should be LG G4)

## Expected behavior
Hebrew writing goes right to left and the alignment for Hebrew should accommodate that across the app.

**Comment by daividssilverio** [comment]
I looked at the case in intercom and based on the information given, this glitch has already been fixed.
I tested on the `giskard-1.11.1` and replicated  the issue, but it can't be replicated on `giskard-1.13.4`.

**Comment by kornelijepetak** [comment]
This was fixed by #4264 and deployed with:

* iOS 1.18
* Android 1.12
