### ISSUE TITLE
Test 1.13 - Potassium

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4884]
## Pull Request
Refers to release `Giskard 1.13`: #4885

## Testing sign in area ##

- [x] Test standard email and password sign in
- [x] Test standard email and password sign in with invalid email address
- [x] Test standard email and password sign in with invalid password
- [x] Test signup with standard email and password
- [x] Test terms and conditions link
- [x] Test privacy policy link
- [ ] Test signin with Google signin
- [ ] Test signup with Google signin
- [ ] Test forgotten password link
- [x] Test forgotten password link with invalid email
- [x] Is country selection automatically selecting the right country?
- [x] Is country selection allowing manual selection
- [x] Test email field with invalid email
- [x] Test email field with mixed character sets (including various languages)
- [x] Test password field for old/changed password

## Testing timer page
- [x] Start timer
- [x] Stop timer
- [x] Enter description
- [x] Add new project
- [x] Add new client
- [x] Add new tag
- [x] Add new project using existing client
- [x] Add existing project
- [x] Add existing tag
- [x] Start new timer, select no project, stop
- [x] Create new manual time entry
- [x] Start a new entry, add multiple tags.
- [x] Start a new entry, discard new entry.
- [x] Continue an entry
- [x] Delete an entry

## Testing editing time entry
- [x] Change description
- [x] Change project
- [x] Remove project
- [x] Change tags
- [x] Remove tags
- [x] Change start time with the barrel/manual selection
- [x] Change start time with the wheel
- [x] Change end time with barrel/manual selection
- [x] Change start date
- [x] Change end date
- [x] Change duration
- [x] Change date from main entry page
- [x] Discard changes to entry
- [x] Delete entry from edit view
- [x] Confirm changes
- [x] Create new project from edit view
- [x] Create new client from edit view
- [x] Create new tag from edit view

## Testing report screen
- [x] Custom range
- [x] Is correct data displayed
- [x] Are categories displaying correct timerframe and dates?
- [x] Is web displaying the same data?
- [x] Today
- [x] Yesterday
- [x] This year
- [x] This month
- [x] Last month
- [x] This week
- [x] Last week
- [x] Custom range 1 year
- [x] Custom range 1 month
- [x] Custom range 1 week
- [x] Custom range 1 day
- [x] Ensure correct year is selected on all options
- [x] Change workspaces

## Testing settings page
- [x] Sign out normal email
- [ ] Sign out google sign in
- [x] Change workspace
- [x] Date format MM/DD/YYYY
- [x] Date format DD-MM-YYYY
- [x] Date format MM-DD-YYYY
- [x] Date format YYYY-MM-DD
- [x] Date format DD/MM/YYYY
- [x] Date format DD.MM.YYYY
- [x] 24 hour time format
- [x] 12 hour format
- [x] Duration format Classic
- [x] Duration format Improved
- [x] Duration format Decimal
- [x] First day of the week Monday
- [x] First day of the week Tuesday
- [x] First day of the week Wednesday
- [x] First day of the week Thursday
- [x] First day of the week Friday
- [x] First day of the week Saturday
- [x] First day of the week Sunday
- [x] Manual mode
- [x] Submit feedback
- [ ] About (has UI cut issues but not fixing in this release)
- [x] Help

## Testing Calendar Integration
- [x] Are calendar entries showing correctly?
- [x] Create an entry from a calendar entry
- [x] Adjust the start time
- [x] Adjust the end time

## Multiple Workspaces
- [x] Switch workspaces
- [x] Go offline then switch workspaces (Airplane mode)
- [x] Switch between workspaces while timer running
- [x] Is data displaying correctly in web?
- [x] Force sync then switch
- [ ] Leave a workspace
- [ ] Be removed from a workspace while offline
- [ ] Be removed from a workspace with an active entry running

## Testing Interactions/Sync between this app and others
- [x] Edit client on web whilst mobile online
- [x] Delete client on web whilst mobile online and tracking a task
- [ ] Edit client on web whilst mobile online and tracking a task
- [x] Tags
- [x] Archiving
- [x] Create new project on web whilst mobile offline
- [ ] Tasks
- [ ] Try creating new entries on web whilst mobile offline
- [ ] Edit client on web whilst mobile offline
- [x] Try stopping timer on web while mobile offline
- [ ] Delete project on web whilst mobile offline
- [x] Make changes to projects on web

## Testing in different timezones

- [ ] Check

## Testing onboarding

- [ ] Check

## Test that the UI is appearing as intended and report any issues

- [ ] Check

## Grouped Time Entries (Release specific)
- [x] Make sure the `Group time entries` setting is propagated to the server
- [x] Check whether the main log respects the grouping setting
- [x] Check whether the group count is correct in both expanded and collapsed groups
- [x] Collapse and expand various groups (ones with and without descriptions, tags, or projects, etc.)
- [x] Tap to edit a group header
- [x] Tap to edit a TE in an expanded group
- [x] Swipe to delete a group
- [x] Swipe to delete a TE from an expanded group
- [x] Edit a TE from a group and change something and check that it is no longer in the group
- [x] Edit a TE group
- [x] Delete a TE group from an Edit View
- [x] Check whether the group summary time on both main log and in Edit view is the same and correct

## Wheel View (Release specific)
- [x] The duration updates correctly when manually inputting the duration
- [x] The duration shows seconds for running time entry

**Comment by ApocalypticFish** [comment]
I need to work out how it's happening but one of my grouped entries isn't expanding when clicking on the number button on the left while the others are

**Comment by ApocalypticFish** [comment]
Two groups of entries only have descriptions but can expand the other has a project but is not. Still troubleshooting

**Comment by kornelijepetak** [comment]
Check the tags. There used to be a problem in tags. If one has them, and the other one doesn't. We've fixed it since, but not sure if that's the thing?

**Comment by ApocalypticFish** [comment]
Had a crash when on the reports screen, left the date range selection menu and minimised the app

**Comment by ApocalypticFish** [comment]
Swiping on both the heading and the grouped entries whether expanded or not just continues an entry it does not edit them. @kornelijepetak is this correct? Looking from the tests added I would have expected them to be edited.

**Comment by kornelijepetak** [comment]
This was my copy/pasta error @ApocalypticFish.
It should've said `tap` instead of `swipe`.

**Comment by kornelijepetak** [comment]
I have tested said features and put a checkmark there.

**Comment by ApocalypticFish** [comment]
@kornelijepetak It's looking good to me I think it's safe to start a rollout on this one

**Comment by kornelijepetak** [comment]
Greenlighted from multiple sources.
Me, @ApocalypticFish and several other testers confirmed no particular problems.
