### ISSUE TITLE
EditTimeEntryViewController RxActionNotEnabledException crashes 

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4890]
## 💥 Crash Report
The VC must have called the action when it was not supposed to 🤔 

### 👥 Impact
Happened to 11 users 

### 🔗 Context
Daneel 1.20

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3366506569u/overview

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
ExceptionServicesImpl.Rethrow (System.Exception exception)
ExceptionHelpers.ThrowIfNotNull (System.Exception exception)
AsyncSubject`1[T].GetResult ()
EditTimeEntryViewController+<Dismiss>d__10.MoveNext ()
ModalPresentationController+<dismiss>d__24.MoveNext ()
ModalPresentationController+<handleSwipe>d__23.MoveNext ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by khoi** [comment]
I couldn't replicate this, from the crash reports, it has something to do with the "handleSwipe" method. Maybe other @toggl/ios-senseis have some idea?

**Comment by arturs105** [comment]
I can't replicate this as well, but i'm thinking this has something to do with `isExecuting` of `RxAction`, since `RxActionNotEnabledException` gets thrown if the action is disabled or is executing, but because the `Close` action never gets disabled, it must be because of `isExecuting`.

**Comment by Odrakir** [comment]
It's definitely about the swiping down to dismiss, but I can't think on what's causing it. It happened only 3 times since 1.21, I think we can leave this on hold for now.

**Comment by juanlaube** [comment]
I don't see this happening in 1.21.1 and 1.21.2.

**Comment by juanlaube** [comment]
I'm closing the issue because this is not happening anymore.
Only affected some users in 1.20 and only one in 1.21.1 a few weeks ago, we don't have affected users in 1.21.2 and 1.22.
