### ISSUE TITLE
No description suggestions when editing an existing TE

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#4894]
## ⛑️ User Support

A user reported (and I confirmed on my end) that when you are editing the description of an existing TE the app will not be offering a drop-down list of suggestions. Suggestions for TE description only show up if you are creating a new TE.

## About the user

App version:  Giskard/1.12
Phone OS: / 
Phone model: / 
* the user reached out via email, no device or OS info, but we do know it's the latest version of the app and I was able to reproduce the issue on a Samsung S9+ running Android 9 (One UI).

## Expected behaviour
When an existing TE's description is being edited a list of drop-down suggestions should appear. 

## To Reproduce
Try editing the description of an existing time entry

**Comment by amulware** [comment]
This is by design and has never been different. It's likely going to change in the future, when/if we make the start and edit views more similar (or entirely merge them). But for the time being, it is what it is.
