### ISSUE TITLE
Some TE details not saved when TE created via calendar view

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#4895]
## 🐛 Bug Report
When creating a time entry using the calendar view, time entry details (description, project) do not get saved. TE is created, but has no description or a project attached to it. 

## Context

Build/Branch: Daneel 1.20
Phone OS: iOS 12.2
Phone model: iPhone 7

## Expected behavior
TE details that I specify upon creating a time entry using the calendar view get saved at first attempt. 

## To reproduce
Open the calendar view on an iphone, 
long press the view to create a new time entry, 
type in a description, 
perhaps select a project as well, 
save.

TE gets saved with no description and project.

**Comment by juanlaube** [comment]
Closed by #4903
