### ISSUE TITLE
Performance issue with a lot of TEs in a WS

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#4896]
## ⛑️ User Support

A user reached out initially saying that the app was trying to sync a bulk edit that was performed on the web app. The user bulk edited descriptions of about 250 TEs and the app took over 30 hours to sync that change.

Upon closer inspection, we saw that the user has a total of 4336 TEs in the database and 126 unsynced time entries at the time they first reached out. 

The app eventually synced all the changes but it slowed down significantly with tasks such as starting a new timer taking as much as 5s-10s

They say that these syncing issues and slow performance started happening with the latest update. 

## About the user

App version: iPhone SE
Phone OS: iOS 12.2
Phone model: iPhone SE

[Case link 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/21525406798)

**Comment by amulware** [comment]
So.. is the problem lots of projects or lots of time entries?

**Comment by VeljkoTN** [comment]
TEs 🤦‍♂️

**Comment by amulware** [comment]
Generally, we should support up to 200 TEs/day for two full months of history without any noticeable slowdown on both platforms.

The only thing we can't help is that sync will take a while if there are many unsynced entities since that limit is imposed by our API.

**Comment by VeljkoTN** [comment]
User following up on this issue, any chance 1.13 will improve their experience when it goes out?

**Comment by kornelijepetak** [comment]
@VeljkoTN 1.13 unfortunatelly does not deal with performance specifically. We do have a focus on app stability and performance in the following months.

**Comment by amulware** [comment]
I'm actually closing this issue, not because it's solved, but because it's not actionable.

We will work on performance in the coming months and will keep you updated internally.
