### ISSUE TITLE
Modal doesn't resize when width changes on iPad

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4905]
## 🐛 Bug Report
When a modal (popup) is presented, and the width of the application changed, the modal doesn't resize itself.

## Context
Build/Branch: `project/ipad`
Phone OS: iOS
Phone model: iPad

## Expected behavior
- it should be resized properly

## To reproduce
- Signup
- "Review the Terms" modal appears.
- Split the ipad screen

**Comment by khoi** [comment]
![IMG_0916](https://user-images.githubusercontent.com/6994441/55939485-0f9fdd00-5c68-11e9-9db3-f5b85e6669e9.PNG)

**Comment by sofokli1** [comment]
@dshr I think this only happens when presenting using `ModalDialogPresentationController.cs`
