### ISSUE TITLE
Dismiss action sheet disappears on iPad

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4906]
## 🐛 Bug Report
The native action sheet disappears if there is a modal displaying in the app. 

## Context
Build/Branch: `project/ipad`
Phone OS: iOS
Phone model: iPad
 
## Expected behavior
Native action sheet always on top

## To reproduce
- make changes to an entry
- tap outside the view to show the native action sheet
- tap outside again and the action sheet disappears

**Comment by khoi** [comment]
https://khoi-screenshots.sgp1.digitaloceanspaces.com/panoram-hemorrhoid-unrecuperative-tapeworm.MP4

**Comment by dshr** [comment]
This is expected behaviour when tapping outside the modal, isn't it? Like, don't other action sheets do the same thing?

**Comment by khoi** [comment]
The thing is u can't ever show the action sheet again after that. Try it out on an iPad and you'll see the problem. It's kinda hard to explain in words
