### ISSUE TITLE
Add sync status next to a sign out button in settings view

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4907]
Users should be able to check the status of the sync process by looking at the settings screen. 
The best place to put it is close to the sign-out button because when they sign out the entirety of their local data is wiped out so everything that has not been synced would be lost.

~If the user taps sign out, maybe we should check whether there's unsynced data and warn the users about the possible loss of data.~ (read comments)

**Comment by amulware** [comment]
Do we not check for unsynced data before logging out? This should DEFINITELY happen. Please copy the way it works on iOS.

**Comment by kornelijepetak** [comment]
@amulware We actually do. The naming is just off IMO. There are two methods: `tryLogout` and `logout`. `tryLogout` actually checks that. But the name should definitely say that it's checking for sync, not just _trying_ to logout. It's not trying to logout, it's deciding whether it should. `logout` is actually trying that, and for the vast majority of cases succeeding. 😄
