### ISSUE TITLE
Our app might log out users when the HTTP requests are redirected

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4908]
There are scenarios, when our users might be "logged out of our app" - our app will think that the API token was reset. I will describe later why that happens but first I want to mention that this is not a critical problem, the app will just ask the user to enter the password again and it will log him back in showing all the data, even unsynced changes.

If a wifi network redirects the user or user's traffic is redirected by some router/firewall (like the one they have in China)/VPN and:

1. the response to our request is `403 Forbidden`
2. the response to a follow-up request to `/api/v9/me/logged` does _not_ return `200 OK` (e.g., 403 again)

We don't verify that the response was actually created by our server for example by checking the presence of the `x-toggl-request-id` header or some other header value (we should consult the BE team first to be sure we use something that won't change or disappear in the future revisions of v9 or v3.

**Comment by amulware** [comment]
This is something we need to discuss with other teams, maybe even Product to make sure that whatever we end up doing is by design, and not a bandaid on a bug in the API specs.
