### ISSUE TITLE
Allow logging in with API tokens in staging builds

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#4909]
This would allow support agents to test syncing and performance issues reported by users which might be related to their data (the amount of data, the values of descriptions, names, ...) and other combinations which we don't think of.

IMO we shouldn't allow this in production builds, just to be sure support agents don't mess with live users' data, by using `USE_PRODUCTION_API` value in preprocesor.

**Comment by amulware** [comment]
I don't think this is actually needed. We have other ways to do the same.
