### ISSUE TITLE
iPad: Modal positioning breaks after going from 2/3 to fullscreen with overlay

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#4924]
## 🐛 Bug Report
1. Have the 2/3 split
2. Start a new TE
3. Open the Change Start Date modal
4. Change the 1/3 app to overlay
5. The Change Start Date modal is positioned weirdly.

## Context
Build/Branch: project/ipad
Phone OS: 12.1
Phone model: iPad Mini

## Expected behavior
It should be centered.

**Comment by sofokli1** [comment]
Looks like [this line](https://github.com/toggl/mobileapp/blob/d2a3edcd0da7bfebd7a8c415f1956163b3d8da1d/Toggl.Daneel/Views/SpiderOnARopeView.cs#L264) needs to take into account the device orientation and add the appropriate 90 degrees per possible interface orientation.
