### ISSUE TITLE
iPad: on-boarding mock tablet size

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#4933]
## 🐛 Bug Report
This is low priority and rare for a user to encounter
In the following 2 screenshots the tablet mock has different size
![IMG_0222](https://user-images.githubusercontent.com/885122/56152853-7bae7800-5fbd-11e9-8e29-97aad6372745.jpeg)
![IMG_0221](https://user-images.githubusercontent.com/885122/56152854-7bae7800-5fbd-11e9-9057-ee31c4c72f2b.png)

## Context

Build/Branch:  ipad/project
Phone OS: ios
Phone model: ipad

## Expected behavior
For the same size class the mock tablet should be the same size

## To reproduce
Just run the app in split screen as in the screenshots

## Suggestions
I consider this low priority
This may be related to autolayout constraints that check for horizontal and vertical size classes

**Comment by sofokli1** [comment]
Took a look at this, it can't be fixed using AL since we want a constraint to work based on device than based on class size. I think the design need changing in this case since it looks better with phone aspect ration when the view is in 1/3. I say we close this issue. What do you think @dshr ?

**Comment by dshr** [comment]
Yeah, let’s close this, it looks quite good as is!
