### ISSUE TITLE
iPad: Report view weird size changes

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#4935]
## 🐛 Bug Report
The report view's width changes weirdly when selecting "Yesterday"

## Context
Build/Branch: project/ipad
Phone OS: 12.1
Phone model: iPad

## Expected behavior
It should be the same for all dates.

## To reproduce
Select "yesterday".

**Comment by sofokli1** [comment]
@dshr Can you make a gif or screenshots (whatever shows it better), I can't reproduce this
