### ISSUE TITLE
NSConstraintExtensions.ConstantAnimated 💥

### ISSUE THREAD

**Issue by khoi** [toggl/mobileapp#4960]
SIGABRT: Objective-C exception thrown. Name: NSGenericException Reason: *** Collection <__NSArrayM: 0x2827d3de0> was mutated while being enumerated. 

### 👥 Impact
Highest crashes in `1.20.1`

### 🔗 Context
Something to do with `AnimationExtensions` 

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/176021915u/overview

### 📝  Exception & Stack Trace
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/176021915u/overview

**Comment by amulware** [comment]
This seems to be introduced with 1.20.1, and there is many similar errors, not just the linked one. This is a pretty major deal and needs to be addressed.

**Comment by amulware** [comment]
hotfix time!

**Comment by dshr** [comment]
This seems to be a threading/realm-related issue, with the `AnimationExtensions` being a red herring — there were no changes touching animation between 1.20 and 1.20.1 https://github.com/toggl/mobileapp/compare/daneel-1.20...daneel-1.20.1

**Comment by dshr** [comment]
From Slack: `mutating while enumerating is an easy thing to happen if you change a collection in a loop… assuming the exception is actually the .net exception I’m thinking of, somehow wrapped into the objective-c thing :)` — but there's looping here per se. `Select`s don't count, should they?

**Comment by amulware** [comment]
`Select` loops. The question is, where are things being mutated?

**Comment by amulware** [comment]
But I'm not sure why we're looking at the Realm stuff at all. This whole thing seems to be about uikit constraints and happen in our AnimationExtensions as mentioned above.

**Comment by amulware** [comment]
OMG btw, the amount of observable calls in that stacktrace... No wonder we have performance issues :D

**Comment by dshr** [comment]
> But I'm not sure why we're looking at the Realm stuff at all. This whole thing seems to be about uikit constraints and happen in our AnimationExtensions as mentioned above.
We're looking at Realm bc the only changes in 1.20.1 were touching Realm and the adapters :(

Unassigning myself since I've spent way too much time on this with little to no progress.

**Comment by sofokli1** [comment]
plenty of this crashes are happening in 2.1.3 ios

**Comment by sofokli1** [comment]
for reference https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors?version=2.1.3&appBuild=&period=last30Days&status=&errorType=unhandlederror&sortCol=count&sortDir=desc

**Comment by sofokli1** [comment]
this is a sneaky one. the crash tittle is very long and different from case to case so it may look like small single crashes independent of each other. although i see this may happen in difference places it looks like the same pattern (somewhere there is a `LayoutIfNeeded` and 💥 follows). Might be just a threading issue.

@amulware i would bump this up just because it is disguising itself from us in the above manner (even just to investigate better where and why it is happening)
