### ISSUE TITLE
Shortcut actions not showing in some devices

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#4961]
## ⛑️ User Support
The shortcut actions (long press on the app icon) are not showing up in some phones, however the actions are visible (or can be added) in the quick settings area (swipe down from the top edge).

## About the user
I noticed this on my Google Pixel 3 XL w/Android 9
@kornelijepetak confirmed it also happens on his OnePlus 5t w/Android 9
@maritoggl however said she can see the shortcuts on her Moto G6 w/Android 8

App version: Giskard 1.13.3
Phone OS: Android 9
Phone model: ???

## Expected behaviour
The shortcut actions should show up regardless of the device.

## To Reproduce
Long press on the app icon, the shortcuts do not work in some devices.

## Suggestions
Take a look at `ApplicationShortcutCreator` in Toggl.Droid.

**Comment by kornelijepetak** [comment]
Could it be a launcher issue?

**Comment by juanlaube** [comment]
I don't think so, it was working for me last week. I'm just guessing, but it could something related to the dependency injection refactor.

**Comment by kornelijepetak** [comment]
@juan I was also thinking about it. We are doing dynamic shortcuts, which should reset when for example, a time entry is started. But nothing changes for me after that trigger. So, it might as well be the dep-inj.
