### ISSUE TITLE
Suggestions: Suggestion tracking

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#4974]
We want to know how much the new suggestions providers are used by our users so check the old project approach and see if it can be reused here as well, otherwise come up with a new way.

The goal is to find out which suggestion provider gets used the most.

Reference issue from previous project #3779

Take a look at [this comment](https://github.com/toggl/mobileapp/issues/4974#issuecomment-497355530)

**Comment by kornelijepetak** [comment]
Here's a list of things we should test, and a request for providing more ideas/suggestions.

#### TimeEntryStarted(
`✅[Existing event]`
For historical reasons, we should keep tracking this event.
Current values (as of `2019-05-27`) show that approximately 15% and 23% (on Android and iOS, respectively) of all time entries on mobile are created using suggestions.

#### SuggestionStarted(Type, Certainty) 
`🚫[Implemented but unpublished]`
I'm in favor of keeping this event. 
I would just add another parameter: `Mode`. With two possible values: `Continue` and `ContinueAndEdit`. If user long-presses the suggestion, the time entry will be started and a start time entry screen open.

#### SuggestionPresented(Type, Certainty, Index)
`🚫[Implemented but unpublished]`
This one has to be reconsidered. The questions that need to be answered:
1. What are all the triggers for running suggestions refresh.
1. Are all suggestion providers polled at the same time?
1. If there are periodic refreshes as well, what is the period.
1. If the next cycle of suggestions yields exactly same results, are we sending the data again?

These questions concern mostly the performance and the amount of analytics data sent to the server. 

Additionally, the point is that some people will not have the calendar suggestions, maybe that's also something that we'd like to know.

#### CalendarSuggestionContinued(Offset)
`💡[Proposition]`
By current designs, [as described in the logic docs](https://www.notion.so/Suggestions-560be63e89104522b029689a6f3a751c), we should fetch calendar entries in the near future and in the very recent past (cca 1h). It'd be interesting to see how many people are continuing the time entry for calendar events prior to the event and how many in retrospect. Continuous `Offset` should be discretize into reasonable ranges (such as `5-15 minutes before`, `on time`, `more than 8 hours later`). Ideas?

#### MachineLearningContinued(Mode)
`💡❓[Tentative]`
For some reason, I think this area is important to track, but I know too little about how it was implemented and what could be gotten from it, but maybe others can add to it. I don't want artifical events just for the sake of it, but I fear that I may be missing something here, so if you got an idea, please fill in.

**Comment by sofokli1** [comment]
In general we can drop the `Certainty` parameter everywhere since we will not have that anymore.

Apart from the above:
- `TimeEntryStarted` we should keep since it will be used to measure the success of the project.
- `SuggestionStarted(Type)` looks good and i like the new `Mode` param you suggest
- `SuggestionPresented(Type, Index)`:
  1. Anytime the app opens or the mail log is shown. I would also set a timer to refresh every 10 min in case the app remain open in the main log. (Since we are introducing 1-2 suggestion providers that are time based we want to those to run whenever the ui is shown so that the user gets the best suggestion for the moment they see the main log view).
  2. Yes
  3. 10 min is a big enough change to give new results in the new providers but will leave the final number to be decided after some usability testing.
  4. we should not skip it since it indicates how often we run the algos

Since we do not have certainty score and thus no way to compare the different suggestions between them, all will have a predefined positions in the 3 slots. The lack of one of those will result in the below suggestion to move one up and have the frequency based provider fill the empty slot. We should also keep in mind that the machine learning approach can also not have anything to suggest due to not enough data available. For all these reason i propose `SuggestionsPresented(Int numberOfMachineLearningSuggestions, Int numberOfCalendarSuggestions, Int numberOfMostFrequentSugggsestions)`
What do you think @kornelijepetak ☝️ ? Does this make sense?

- `CalendarSuggestionContinued(Offset)` I see the need for something like this but not sure about the discretising of the offset unless it is ok to have both the discretize and actual value (like hours).

I also suggest something like this for the other two providers and maybe have the difference in days from the suggestion and the difference in time (hours). I think this should give us a good indication of how users daily tasks are repeated.

- MachineLearningContinued(Mode) what i said above.

**Comment by sofokli1** [comment]
To sum up
- We are going to keep `TimeEntryStarted(Origin)` as is.
- Will use `SuggestionStarted(Type)` so we know which suggestion provider is used the most
- Will add `SuggestionsPresented(Int numberOfMachineLearningSuggestions, Int numberOfCalendarSuggestions, Int numberOfMostFrequentSugggsestions)` to have a centralised place to see which providers are providing and which are struggling
- Will add `CalendarSuggestionContinued(Offset)` to see how close to the calendar events time are the users starting time entries from these provider.

**Comment by kornelijepetak** [comment]
Just adding some information we internally decided:

Allowed ranges for `Offset` in `CalendarSuggestionContinued` are:

* `<5`
* `5-15`
* `15-30`
* `30-60`
* `>60`

all units are in minutes.

**Comment by amulware** [comment]
Note that I'd like a `totalNumber` property in the `SuggestionsPresented` event, just to easier see how often we don't fill all three slots.

I also tentatively proposed having a string property that gives us the exact combination of providers (like `(2, 0, 1)`) internally, which I'd like discussed a bit more. :)
