### ISSUE TITLE
Tasks Not Selectable in TE Edit Screen

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/mobileapp#4982]
## ⛑️ User Support
Just what the title says: when creating a time entry or editing one, selecting a project works, but attempting to select a task nested in the project does not. 

NOTE: cannot be replicated on Moto g6; see user information below for specific use-case

## About the user

App version: Giskard 1.12
Phone OS: 6.0.1
Phone model: Redmi 4A

## Expected behaviour
Selecting a task from the task list should immediately attach the task to the time entry. 

## To Reproduce
1. Start a time entry
2. From the edit screen, attempt to select a task dropdown from a project that has tasks 
3. Either task list doesn't drop down, or task list inside of dropdown doesn't allow for task selection 

## Suggestions

Intercom [Case Link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/21753852670#part_id=comment-21753852670-2975203191)

Slack [convo](https://toggl.slack.com/archives/C029WU7AY/p1556131540017600) with @juanlaube  being able to replicate

**Comment by kornelijepetak** [comment]
Just adding myself a mental note about things @juanlaube and me found out.

Tasks can't be expanded only if:

1. Tapping the project icon in Start TE view, or the `@ Search Projects` item. Typing `@` on keyboard shows the same list, but tasks can be expanded correctly.
1. The project whose tasks are to be expanded belongs to the currently selected workspace. If it's the project in another workspace, it works correctly.
