### ISSUE TITLE
Consider using dedicated views for Create Project suggestion

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4986]
When typing into a filter in project selection, the app will prepend a `Create Project XYZ` item to the beginning of the list. In order for this item to be visible, the list has to be scrolled to the beginning, because in the current implementation, it's just a regular row in the tableview/recycler. In order to do that, the scroll state has to be reset to top.

If we extract this row and use a dedicated view (with toggling its visibility), we could have the scroll independent of the creation process, leading to better UX.

This is what @maritoggl suggested as a desired behavior.

@amulware If you agree with her suggestion, make sure to schedule this issue somewhere.

**Comment by amulware** [comment]
Shouldn't this have platform labels? Doesn't seem like an actual refactor to me.

Also, I'm fine with this, assuming there are proper designs.

**Comment by maritoggl** [comment]
Hmm. I don't think this needs new designs, perhaps using the term "view" brought about some confusion. I have not proposed using entirely new visuals, but an improvement to how the list that we already have is being scrolled up and down - basically removing automatic scrolling, but still displaying the create new project row at the beginning of the list.

**Comment by kornelijepetak** [comment]
@amulware yes, as @maritoggl said, this is supposed only to stop adding "Create new" label as a row in a table and instead show it (when needed) as a separate view so that it is indepenedent of scrolling.

**Comment by amulware** [comment]
Have we considered how this will look on small screens? Will there be enough space for anything to actually scroll if more space is taken up by this additional view?

**Comment by kornelijepetak** [comment]
Well, if there's a user on whose phone only one row can be visible, trust me, he will not be able to use other parts of the app anyway...

This may be a radical comment, but I don't think it's gonna be a problem. But that is a product question, @maritoggl should decide.

**Comment by maritoggl** [comment]
I approve.

**Comment by amulware** [comment]
Before I schedule this.. @maritoggl why do we actually need this? Being scrolled to the top is the default already... It seems inelegant to me to put this view always at the top.

**Comment by kornelijepetak** [comment]
@amulware for reasons described here https://github.com/toggl/mobileapp/issues/4822#issuecomment-486990846, it is not being scrolled to the top by default. 

I've added that behavior (hard scroll to top) at some point in a fix.

However, I'm revisiting this issue, because my _fix_ introduced another issue:
When tasks are expanded, the list is reset to top even thought the tasks and their project are somewhere down the list.

**Comment by kornelijepetak** [comment]
Honestly, I'd put it here... And show it only when something's written in the filter

![image](https://user-images.githubusercontent.com/7033216/57777165-79a51980-7721-11e9-8585-b13cf2eb5ae4.png)

**Comment by amulware** [comment]
For reference, we decided to not do anything with this at the moment.

**Comment by amulware** [comment]
I'm closing this. If we decide to do it we can reopen/create a new issue.
