### ISSUE TITLE
Monitor the setupViews crash issue and remove redundant code

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#4987]
I have added some diagnostics code into Edit View in order to better detect the reason for the crash. Since the release and up until the moment of writing this, no crashes of this type were seen in production.

If by the time 1.14 is ready to be released there are still no such crashes, let this issue be a reminder to remove this diagnostics code.

Check #4968 to see what diagnostics were added.
Make sure that rehydration code is not erased from the view model accidentally.

**Comment by juanlaube** [comment]
I will move this to 1.15 just in case we might actually need this in 1.14.

**Comment by kornelijepetak** [comment]
`1.14` has been released to 20% of users and I see zero errors of this kind, while before it is rather prominent.

**Comment by kornelijepetak** [comment]
However, [1.13.4 shows several cases of the crash](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/1878191884u/overview) even though it was supposedly fixed on that build. So, the crash can still occur, but it indeed does happen a lot less frequent.

Interestingly enough, it did happen a few times [outside of rehydradtion](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/analytics/events/DebugEditViewInitialSetup?period=last30Days&version=1.13.4).
However, in all cases the cause is that the Time Entry Ids collection is empty.

**Comment by kornelijepetak** [comment]
Even more interesting, there are cases where ViewModel is even `null`. 😱
I hope some of these issues should be resolved automatically by MVXit.

For now, I'll retain this issue here and the code for the diagnostics until 1.14 is fully released. Then I'll decide whether to remove it still in 1.15 or leave it for one more release.
