### ISSUE TITLE
Show report calendar shortcut names in the title

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5003]
When a user selects one of the quick select shortcuts in the reports calendar, we should show the shortcut name in the title bar/navigation bar instead of a date or a date range. We do this for the "This Week" shortcut, but all the other shortcuts display a date range or a date.

I think i implemented this, when i initially wrote that calendar, but somehow the feature has gone missing. Let's make reports calendar great again.

**Comment by maritoggl** [comment]
Just to clarify, this should apply also when the shortcut matching date range is manually selected from the calendar. That's how "This week" shortcut currently behaves as well.
