### ISSUE TITLE
Close the reports calendar when a date range is selected

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5004]
When i've selected a date range (usually with the shortcuts) in the reports calendar, i find it annoying that i have to close the calendar manually. Especially since it can't be closed by a simple swipe up - you have _drag_ it to the very top, or reach your finger to the top of the screen to tap the open/close button, which is cumbersome. There's already an [issue](https://github.com/toggl/mobileapp/issues/4616) to improve the calendar hiding behaviour, but i think we should still implement closing of the calendar when a report period is selected.

**Comment by amulware** [comment]
Probably no longer relevant with the recent rewrite.
