### ISSUE TITLE
Un-representable DateTime in WheelForegroundView.updateEditedTime

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5014]
## 💥 Crash Report
Seems like you can get the wheel view to crash by adding or subtracting some time span form some date time, which results in an unrepresentable date.

My first guess is that you might get this crash if you set the start date of a time entry to be `DateTimeOffset.MinValue` (jan 1 2001) and then try to set the start time before that using the wheel. Alternatively you could try going higher than `DateTimeOffset.MaxValue`, though why would someone do this?

Also: the crashes happened on April 28 - May 1, so those dates might have something special, though doesn't seem like it. Maybe the jump from April to May causes this crash?

### 👥 Impact
This crash has affected the most users for 1.21, and it seems like each user has experienced the crash only once.
25 users affected in the last 7 days.
25 crashes in the last 7 days

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3161697801u/overview

### 📝  Exception & Stack Trace
`SIGABRT: The added or subtracted value results in an un-representable DateTime. Parameter name: t`
```cs
DateTime.op_Addition (System.DateTime d, System.TimeSpan t)
DateTimeOffset.op_Addition (System.DateTimeOffset dateTimeOffset, System.TimeSpan timeSpan)
WheelForegroundView.updateEditedTime (System.TimeSpan diff)
WheelForegroundView.touchesMoved (CoreGraphics.CGPoint position)
WheelForegroundView.handleTouch (UIKit.UIPanGestureRecognizer recognizer)
UIPanGestureRecognizer+Callback.Activated (UIKit.UIPanGestureRecognizer sender)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by amulware** [comment]
Hotfix time!
