### ISSUE TITLE
NullReferenceException in CalendarViewController.ScrollToTop

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5016]
## 💥 Crash Report
Since this is a really simple method, there's not much that _could_ be `null`:
```
public void ScrollToTop()
{
    CalendarCollectionView.SetContentOffset(CGPoint.Empty, true);
}
```
My bet is on `CalendarCollectionView` somehow becoming `null`. How? I don't know, but i don't see any other places where in this method a `NullReferenceException` could be raised.

### 👥 Impact
8 crashes to 8 users in the last 7 days.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/2719510634u/overview

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
CalendarViewController.ScrollToTop ()
MainTabBarController.ItemSelected (UIKit.UITabBar tabbar, UIKit.UITabBarItem item)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by amulware** [comment]
I believe this is new in 1.21? Let's hotfix it.
