### ISSUE TITLE
Set up APN and Firebase for iOS push notifications

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5027]
We need to set up the APN auth key and upload it to Firebase.

Link to docs: https://firebase.google.com/docs/cloud-messaging/ios/certs and https://firebase.google.com/docs/cloud-messaging/ios/send-multiple#upload_your_apns_authentication_key

Youtube tutorial: https://www.youtube.com/watch?v=1ybusY3R28Y

**Comment by amulware** [comment]
This is too many steps for me. Please do this yourself. :D

**Comment by simonrozsival** [comment]
The Auth Key was uploaded to Firebase.
