### ISSUE TITLE
Implement service: Access FCM token

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5031]
Implement the platform specific part of #5283.

https://firebase.google.com/docs/cloud-messaging/android/client
Xamarin: https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm - it might be a bit outdated, check also https://github.com/xamarin/GooglePlayServicesComponents/tree/master/samples/com.google.firebase/firebase-messaging/FirebaseMessagingQuickstart

**Comment by daividssilverio** [comment]
Closed by #5303
