### ISSUE TITLE
Implement service: Destroy FCM token

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5032]
When the user logs out of the app, he/she should not receive any further notifications. We will not send any sensitive data through the notifications, but we still don't want to send any notifications to an app where nobody is logged in.

Implement the token destruction method of #5283

**Comment by simonrozsival** [comment]
on iOS, it should be something like:
```cs
var token = Messaging.SharedInstance.FcmToken;
await Messaging.SharedInstance.DeleteFcmTokenAsync(token);
```
on Android, it should be:
```cs
FirebaseInstanceId.Instance.DeleteInstanceId();
```

**Comment by simonrozsival** [comment]
- [ ] the `LogoutInteractor` should call the destroy method from #5283.
- [ ] the iOS part of the service has to be implemented
- [ ] the Android part of the service has to be implemented

I'll keep this in one issue, it can be closed either in one PR or in multiple PRs.

**Comment by simonrozsival** [comment]
You might want to check this link: https://stackoverflow.com/questions/43193215/firebase-cloud-messaging-handling-logout

**Comment by Odrakir** [comment]
So, in the end we need to delete instance id for both platforms or only for Android? 🤔

**Comment by simonrozsival** [comment]
We need to delete the token on both platforms so that the device does not receive any updates when the user is not logged in.

**Comment by Odrakir** [comment]
This calls the `InvalidateCurrentToken` which does so for both platforms. I'm closing the issue, in case I'm mistaken, please reopen it.
