### ISSUE TITLE
Time Entries created under manual mode are "shorter" than they seem

### ISSUE THREAD

**Issue by ricotheque** [toggl/mobileapp#5038]
## 🐛 Bug Report
Creating new Time Entries with manual mode may be shorter than their apparent length. For example, the wheel may show 9:00 - 9:05, but the new TE's duration ends up being 00:04:47.

## Context

Re-opened version of https://github.com/toggl/mobileapp/issues/4541

Build/Branch: Giskard 1.14 (402890)
Phone OS: Android 9
Phone model: ONEPLUS A6003_22_190123

## Expected behavior
The new TE created should have a duration that matches the set Start and Stop Time.

## To reproduce
1. Open mobile app
2. Hold down play button to create a new Time Entry under manual mode
3. Tap duration on the bottom left of the create Time Entry view
4. See "Duration" field in the middle of wheel show "0:30:00"
5. Tap "Duration" field
6. Type in "800" to indicate 8 hours
7. Press check button on numeric keypad to confirm
8. See "Duration" now show "07:59"
9. Tap "Save"
10. Tap "Save"
11. Tap on Time Entry on main view to edit it again
12. Tap on "Start time" or "End time" field
13. See "07:59:XX" on "Duration" field (On my end, I saw "7:59:51")

## Suggestions
It looks like this is unintended behavior. Per @amulware "changing start/stop time manually should always set the seconds component to 0".

The current workaround is to move the start time one tick backward.

[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100764/conversations/21873122663)

**Comment by amulware** [comment]
This is actually a bit complicated. If you don't touch one of the wheel endpoints, the respective time should NOT be stripped of the seconds component I _think_.

We have to do some better thinking on what exact circumstances should remove the second component, and which shouldn't.

Maybe time entries that are created non-running (i.e. manual mode mostly) should start out without seconds component to begin with? But does that cover all cases?

@maritoggl Would be great if you could take a look, or otherwise make someone else do it. (Also, how do the other Toggl clients handle this? This sort of things really should be unified if it isn't. Details matter.)

**Comment by maritoggl** [comment]
Even though we don't display the seconds in the UI when creating new time entries in manual mode, the timestamps still include a non-zero seconds component - we don't strip anything. Currently, this behavior is the same in all clients - tested. 

Web and desktop do not strip any seconds also when the time entry duration is changed. In mobile, however, the behavior is different depending on how the duration has been changed. For instance, if duration in iOS is changed in the time entry creation view without navigating to the wheel view, the seconds stay intact. If, however, any changes are made in the wheel view, we start stripping seconds. 

Ideally, I think we should just stop stripping seconds as well just like our other clients do (and iOS as well in at least one scenario). If that's not feasible, let's evaluate other options that at least fix the issue that has been reported with Android, 'cause what's happening there is fishy - there we keep the start time seconds intact, but strip the stop time seconds, which brings about this odd duration. The same does not occur in iOS, where, if we strip anything, we do it for both start and end times.

**Comment by amulware** [comment]
We can stop stripping seconds, but we started doing so on purpose because otherwise you simply can't align time entries to full minutes and you get other non-obvious behaviour where time entries don't have the duration you think they should.

I think this needs more thinking.

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22223166098)

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22665710605)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22722618761)

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/22903758274)

**Comment by amulware** [comment]
Any update on this, @maritoggl?

**Comment by maritoggl** [comment]
I haven't analyzed this further as I still think we should simply go with the same approach as our other clients do - stop stripping seconds, regardless of which method has been used for editing the time entry. I don't understand how this approach would result in getting time entries with non-obvious duration - we don't have this problem with any of our other clients, nor do we have this issue with mobile when the time entry has been edited using traditional means, not the wheel. 
If you have a chance to explain the issues with the proposed approach (that we use almost everywhere) a little further, that would be great - currently, I just don't understand the downsides.

**Comment by amulware** [comment]
I don't follow what you mean. The web definitely strips seconds/rounds to full minutes when you edit times, I just tried it. In fact it seems to change both times, even if neither of them was edited by the user when you hit ENTER in the popup.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24194979723)

**Comment by amulware** [comment]
I'm closing this since there has been no process and no clear problem stated.
