### ISSUE TITLE
Make each IViews ViewModel property readonly

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5061]
This means receiving the ViewModel as part of the constructor and then passing it back to base. Since we have manual control over this, there's no reason not to.

Since activities are the oddball here, they won't receive it during construction but rather just continue doing what they are doing right now.

**Comment by daividssilverio** [comment]
This won't work well for droid. We need parameterless constructors for both Activities and Fragments.
I guess we can close this after the iOS part is done.
