### ISSUE TITLE
Track widget install/uninstall

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5090]
Detect when the widget is installed/uninstalled and track the necessary events.

Add a new event, `TimerWidgetInstallStateChange(bool installed)`.

Installs and uninstall events are not provided by the platform, but we can use two values in user defaults to accomplish this, LastUpdatedDate and InstallTracked. When the widget is updated, we set the current date in that value.
If the InstallTracked value is false, we track an install event.
If the value is older than X days (we need to decide how many days are X), we track an uninstall event and remove both values from user defaults.

While not 100% accurate, it's still better than nothing.

Depends on #5084

**Comment by sofokli1** [comment]
is this good to close?

**Comment by juanlaube** [comment]
Yes!
