### ISSUE TITLE
Track widget install/uninstall

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5097]
Detect when the widget is installed/uninstalled and track the necessary events.

Add a new event, `TimerWidgetInstallStateChange(bool installed)`, and track it on the install/uninstall detection.

We can get notified by the platform when a widget is installed or uninstalled by listening to some breadcast intents, here's more info about that: https://developer.android.com/guide/topics/appwidgets#ProviderBroadcasts

Depends on #5092 and #5404

**Comment by kornelijepetak** [comment]
I have taken a good amount of time testing this and checking some parts. It seems that this was indeed finished by the #5577 .

All my attempts executed the tracking code, so I'm assuming this works correctly.

For this reason, ~I'm out~ I'm closing the issue.
