### ISSUE TITLE
Notifications disappears when tapped

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5122]
## 🐛 Bug Report
The `Running Timer` and `Stopped timer` notifications disappear when tapped.

## Context
Build/Branch: `develop` or `scandium (1.15)`
Phone OS: At least on Android 9
Phone model: Most likely unrelated

## Expected behavior
If the option is turned on, the `Running timer` notification should always be there, as long as there is a runnig time entry. Tapping the notification should turn on the app (or bring it into view if it's already running), but should not remove the notification.

## To reproduce
1. Go to settings and turn on the `Running timer` notification
1. Go to Timer view
1. Start a Time entry
1. _Notification should now be visible_
1. Pull down the status bar
1. Tap the notification 
1. _The app opens_
1. ⚠ _The notification is no longer there_

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22040434091)

**Comment by heytherewill** [comment]
I wasn't able to reproduce this on any of my devices. 

Could you please check if your phone has some system-wide setting that disables persistent notifications, @kornelijepetak? If the users have that unable I'm afraid that there isn't much we can do. If it's something else it might be worth investigating

**Comment by kornelijepetak** [comment]
I tried it again on 2.0 and it still happens for me on OP5T.
Could be an Oxygen thingie, but I couldn't say 🤷‍♂️

But if you think it's not an issue, maybe we can close it and reopen if we see it actually reported or otherwise troubling the users.

**Comment by daividssilverio** [comment]
Managed to replicate this.
You you have to do is go into background for a while. When you get back to the app, it closes the notifications, until you go back to the main fragment page.

I'm working on a fix.

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22627397687)
