### ISSUE TITLE
Issues navigating on Lollipop

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5124]
Trying to open the edit view on a Phone running Android 5.0 yields `Android.Util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`

We need to investigate this to figure out if the problem is indeed the OS version and what the best fix would be. In principle, we can simply use the reference to `IView` that now comes with every navigation request.

**Comment by daividssilverio** [comment]
> Simply use the reference to `IView` that now comes with every navigation request

☝️ seems very reasonable
