### ISSUE TITLE
Display placeholder bars instead of "(unsynced project/task)"

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5136]
Instead of this:
![image](https://user-images.githubusercontent.com/374616/57846989-b4688980-77d5-11e9-91d4-7360c8316923.png)

We will show gray bars take from the "empty main log" placeholders in the place of a placeholder project and placeholder task
- [x] in the main log cell
- [x] in the currently running time entry card

![iOS](https://user-images.githubusercontent.com/374616/57846898-8420eb00-77d5-11e9-92c6-cd2acd5cd875.png)
![Android](https://user-images.githubusercontent.com/374616/59102225-c6000580-892b-11e9-9d3a-15acc729e285.png)

**Comment by simonrozsival** [comment]
Screenshot from the android design:
![image](https://user-images.githubusercontent.com/374616/59102225-c6000580-892b-11e9-9d3a-15acc729e285.png)

**Comment by simonrozsival** [comment]
The final decision (confirmed by @maritoggl): We will display the placeholder bars in the main log and for the currently running time entry. Everywhere else (e.g., the edit view), we will simply show the name which says "(unsynced project/task/workspace/tag)". The color of the placeholders should be always gray.

**Comment by daividssilverio** [comment]
I'm working on the droid bits.
