### ISSUE TITLE
Update log view empty state

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#514]
See zeplin for details.

**Comment by pe0ny** [comment]
**Welcome screen: for new users**
- [ ] New users should see this welcome screen after they sign up: https://zpl.io/boG56kb
- [ ] Show it until user has created his/her first time entry

![toggl - ios - log welcome screen 1x](https://user-images.githubusercontent.com/5064445/30327236-fbeb4a10-97d3-11e7-9226-e95764884cad.png)

**Empty state: for existing users**
- [ ] Show this screen to existing users who haven't tracked their time for 6 weeks: https://zpl.io/VOnJp82
- [ ] Show this until user creates another time entry

![toggl - ios - log empty state 1x](https://user-images.githubusercontent.com/5064445/30327264-1a266b0e-97d4-11e7-881a-7074e201785c.png)
