### ISSUE TITLE
Add simple suggestion provider

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#517]
On app start/login (and maybe after finishing a pull sync, especially when logging initially) we want to show simple suggestions: Basically, go over all time entries of the previous 4 weeks, and suggest the most common (description, project(, task)).

@pe0ny How do tags work with suggestions if at all?

**Comment by pe0ny** [comment]
Previous 6 weeks!

**Comment by pe0ny** [comment]
@amulware We suggest only time entries and display these the way we display time entries in a log view (so in the list view, user can't see if this time entry has tag(s) or is billable). So if time entry has or has not a project/task or a tag(s) shouldn't affect results. At least for now when we suggest only most used time entries.

**Comment by willsb** [comment]
@pe0ny Right now this already works, but we only show one suggestion at a time. We can have as many providers as we like in the future, but should this simple one only give one suggestion at a time?

**Comment by pe0ny** [comment]
But why only one? Let's fill the screen up to 5 suggestions (most used time entries)

**Comment by willsb** [comment]
👌
