### ISSUE TITLE
Add a screen for triggering access restriction screens

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5172]
## 🚧 Refactor Proposal
We need to have an easy way to test our restriction screens. My idea is to have a special modal that shows up after some combination of taps/swipes is entered. From that screen, we can trigger any restriction we want.

This is similar to the `We need a way to crash our apps` issue, but different in a way.

## Platforms affected:

- [X] 🤖 Android
- [X] 🍎 iOS
- [X] 🖥️ Shared layer

## Technical aspects
Ideally, the backend team would grace us endpoints that return only 401/410/418, but even if they don't we can create mocked methods in our API that receive and `HttpStatusCode` and fake an HTTP result with that status code. This will allow us to really test whether our system is capable of handling restrictions or not.

This view should also have an offline mode that simply calls the adequate `IAccessRestrictionStorage` methods since sometimes we just wanna test the restriction views themselves and not the whole integration between the API results and the way our app deals with them.

**Comment by amulware** [comment]
Tell me more about how you want this to be triggered - I don't want users stumbling over it.

**Comment by heytherewill** [comment]
My idea is to have this appearing only in Debug builds, but if we want it in AdHoc we could make it be triggered with some kind of input like an easter egg

**Comment by amulware** [comment]
If this is not in production I don't see why the trigger has to be that complicated.
