### ISSUE TITLE
Reports: bar chart empty state

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5197]
## 🐛 Bug Report
The bar chart in reports doesn't show the empty state when there's no data, instead of showing a bar with 0s clocked, the view is empty (only the chart legend is visible).

## Context

Build/Branch: project/mvexit
Phone OS: Android
Phone model:

## Expected behavior
Should show the chart like in `develop`

## To reproduce
Load a report for a date range without time entries.

**Comment by daividssilverio** [comment]
Closed by #5231
