### ISSUE TITLE
Better handle login errors

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#520]
It should show the user different messages, depending on if the login is invalid, or the server is not reachable in the first place.

**Comment by willsb** [comment]
@pe0ny Can you elaborate on which message to use and when? Because right now we show two kinds of messages: one for server unreachable and one for invalid login

**Comment by pe0ny** [comment]
@willsb I think that's about it then. I thought we only show one for invalid login (when email/password was incorrect). So when we have those two, we're good to go:

> Incorrect email/password. Please try again.

> Sorry, we’re having trouble logging you in. Please try again.

**Comment by willsb** [comment]
Then we're covered :shipit:
