### ISSUE TITLE
Time entry creation empty state

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#521]
More info coming from @pe0ny

**Comment by willsb** [comment]
Needs more info from @pe0ny 😄

**Comment by pe0ny** [comment]
Show these hits when user starts a new time entry.
Both - @ and # should be clickable as well and trigger project and tags suggestion views like buttons below.

![toggl - ios - add new entry empty state 1x](https://user-images.githubusercontent.com/5064445/30540799-5bc3f264-9c81-11e7-8b06-4baa88a02756.png)
