### ISSUE TITLE
Track time entry cell index when continuing

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5214]
I'd like to know how far users are willing to scroll down to continue time entries.

My proposal would be to track the index of the time entry cell when continuing, as a property on the `TimeEntryStarted` event.

Things to figure out/consider:
- name of the property
- a special value (or no value at all? is this possible? maybe a special value is still better, just in case) for the non-continue case
- is the cell index the right thing to track? we could track 'how many time entries are newer than this one' instead, which we can maybe get easier, but how does this work with grouping?
- how does this behave with grouping on/off? how do we want it to?
- should we have another property for 'continued group/continued non-group/not actually continued'
- should we track how many days in the past the time entry is? maybe how many days as shown in the timeline? (i.e. friday->monday is 1, not 3, or whatever)
- given how many things could be tracked and how complicated this might get, should this maybe a separate event after all?

I'd like some thoughts from people who know the code better than me.

Like I said, my goal is to understand what time entries people are continuing better, and if they bother scrolling down into the list a lot for that or not.

Also note, I want this released soon, before the new suggestions update (on android specifically) to see if the suggestions update makes a difference.

**Comment by juanlaube** [comment]
My thoughts with that goal in mind:
- I think the cell index is the right thing to track regardless of the grouping
- Grouping might affect those numbers though, so I would track if that's enabled or not
- How many days the user scroll is also worth tracking
- I think this looks like a new event, but do we need to correlate this event with something else? and can we do that?

**Comment by kornelijepetak** [comment]
1. I agree that tracking the index is kind of messed up with grouping in play, however, just getting the recentness of the time entry is not gonna tell us much about how much the user has scrolled down. So, I'd maybe track both the index and the recentness of the continued TE. 

The number of entries chronologically before the continued time entry feels kind of the same thing as an index. Of course, grouping changes this concept a lot, but
* Index is simpler (probably faster) but gives us more information about scrolling habits
* Count of later time entries takes a bit more time, but we don't know much about it.

Maybe it's best to track both?

My question relating to indices/recentness though is whether we want to put them in ranges. I couldn't find out whether AppCenter/FB actually group stuff in ranges automatically, but it seems that they don't (as they shouldn't). However, it's gonna be a mess there seeing too many different numbers. And also, we don't really care if it's index 1 or 4, it's roughly on the first page. Also, relative offset in days for recentness?

2. @amulware are you sure you want to extend `TimeEntryStarted(Origin)` event with a parameter that is only used in some of the cases of `Origin`? 
These are: 
* `SingleTimeEntrySwipe`
* `SingleTimeEntryContinueButton`
* `TimeEntriesGroupSwipe` 
* `TimeEntriesGroupContinueButton`.

What would be a default value for all other cases, where the index is N/A? `-1`, `null` (can AppCenter accept `null`s as parameter values)? It is not possible in our current setup to extend this and `not` send any value. A value always has to be sent, but maybe `null` is fine as well.

3. Name: MainLogIndexOfTimeEntry

4. Re the timeline, I wouldn't complicate stuff. Simply a day offset as I've mentioned above should be enough.

5. I'd again propose a new event, not touching the previous one.

**Comment by amulware** [comment]
@juanlaube We don't get correlation between events or between properties (so adding an is-grouping-enabled property doesn't help much either) I'm afraid.

@kornelijepetak Thank you for the detailed thoughts!

I think the only real argument for not using a separate event is the limited number on AppCenter, but we're not even close yet, so this is a rather weak argument, especially since we can't correlate data anyways (or at least not on AppCenter/Firebase directly).

So a separate event it is: `TimeEntryContinued`

Let's have the following properties:
- `Origin`: `Swipe|ContinueButton|GroupSwipe|GroupContinueButton`
- `IndexInLog`: integer, index in log
- `DayInLog`: integer, how many days are in front of the continued day in the log
- `DaysInThePast`: integer, how many days in the past (0 == today, 1 == yesterday, check actual date, not just the difference to now divided by 24)

I don't think I want to track the number of time entries after the continued one, because that might be a performance issue, having to iterate and count, and I don't think we'll get much info that we don't already get from the above.

I also don't think we need to group the properties, do we? AppCenter shows the top 10 in the UI, and I think we can grab all of them using the API if needed. I'm thinking that the vast majority of values will be in the 0-10 range. If the data we get is problematic, we can change it to be grouped down the line.

What do you guys think?

**Comment by juanlaube** [comment]
The event and its properties make sense to me.

I just have one question, would `GroupSwipe` and `GroupContinueButton` be used when GTE is enabled, even if that particular time entry is not in a group? I'm asking just to clarify what that means.

I agree we do not need to group the properties, if we get more than 10 possible values and the we notice some interesting distribution, we can decide some grouping later, but doing that right now is not very useful.
