### ISSUE TITLE
Suggestions: Add longPress/force touch to start and edit time entry

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5222]
When a suggestion is long pressed (force touched) the app should continue a TE and open the edit view.

**Comment by amulware** [comment]
I'd argue we should open the start-view with filled in data instead, and only actually persist the time entry if the user confirms.

**Comment by sofokli1** [comment]
That may make sense if the user wants to create a manual entry out of the suggestion but from what they are used to, taping starts the timer. Shouldn't a long press start the timer and allow the user to edit. @maritoggl do you have an opinion about this?

**Comment by sofokli1** [comment]
this feature was also mentioned in notion before [link to mentrion](https://www.notion.so/Suggested-time-entries-improvements-0522d4d99ddb4eb9aea20f8f981537b9#1df1c71f1b474b27a12c6a03ed304ab3)

**Comment by sofokli1** [comment]
This was dropped from these project
