### ISSUE TITLE
The smart notification settings modal can only be opened once

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5227]
## Context
As [reported by Olivia](https://toggl.slack.com/archives/CJCF85Y5U/p1558974820045600), the Smart reminders modal only works on the first time you tap it if you dismiss it by tapping outside of the modal area or pressing the physical back button.

Build/Branch: `project/mvexit`
Phone OS: Any
Phone model: Any

## Expected behavior
The modal opens whenever you request it

## To reproduce
- Go to calendar tab
- Click `Link calendars`
- Select some calendars
- Go to settings
- Tap the `Smar reminders` option
- Press anywhere outside the modal or the physical back button

## Suggestions
This is probably related to `Cancel` not being called, which would make the CloseCompletionSource in a hung state.

**Comment by daividssilverio** [comment]
Closed by #5230
