### ISSUE TITLE
Translucent tab bar hides the stop button.

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5253]
## 🐛 Bug Report
![IMG_2078](https://user-images.githubusercontent.com/8163330/58568012-d87e8e80-8209-11e9-9946-f2644dfba708.PNG)

See the attached screenshot, the tab bar is translucent and it hides the running time entry and stop button.

## Context

Build/Branch: develop
Phone OS: iOS
Phone model:

## Expected behavior
Not sure of the tab bar should be translucent now, but the content behind should be visible.

## Suggestions
If we want a translucent tab bar, then we should consider adjusting the extended edges for bottom bars.
Problem may have been introduced in #5218.

**Comment by Odrakir** [comment]
If we can't find a way to fix this, we can just revert the iPad constraints commit. But in any case the table view and this view should have independent constraints so that changing one doesn't break the others.
