### ISSUE TITLE
Pass user id to App Center

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5256]
Earlier this year AppCenter introduced a useful search feature to the diagnostics section. Part of this is that we can not provide it with a user id, which can also be searched for. By using this, we will be able to check what errors specific users are experiencing and hopefully make life easier for us, support, and ultimately our users.

Here is the announcement post from App Center: https://devblogs.microsoft.com/appcenter/introducing-diagnostics-search-and-user-id-support/

Things we have to do:
- Tell AppCenter the user id on login
- Make AppCenter forget the user id on logout

And, to catch up on existing users:
- Tell AppCenter the user id on app start, if we're logged in

Whoever works on this please think through if all of this makes sense, and where the best places are to do this. Let's also test and make sure this works in both adhoc and store builds (and maybe should be disabled in debug, that's up to you to figure out).

**Comment by amulware** [comment]
Also please consider if we should remove the notification on app start again sometime down the line (when virtually all users will have updated) and if so create a followup issue.

**Comment by kornelijepetak** [comment]
@maritoggl is this GDPR-friendly, considering the term `identifiable`?

**Comment by kornelijepetak** [comment]
What you wrote, @amulware it makes sense. I think this is the best way to implement it like this. 

For now use I'll use Toggl's DB ID. If this is not GDPR-friendly, we'll change it to something else. Waiting for response from legal sector.

**Comment by amulware** [comment]
No response or clarification is needed. I talked to the relevant people before creating this issue. Please proceed with the user id (that is a/the proper Toggl business logic term) as indicated above.
