### ISSUE TITLE
Support Tasks in creation view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#526]

**Comment by willsb** [comment]
Question: When will we support Workspaces in the suggestions of the start time entry view? 

I think it's quite relevant and since I'll do some refactoring for supporting Tasks, I think including Workspaces might make sense, if it's to be supported soon

**Comment by amulware** [comment]
I don't understand the question. How do you mean 'support workspaces'? Workspaces should already be supported in the sense that projects from different workspaces are shown, and the time entry should be assigned to the workspace of its project.

**Comment by willsb** [comment]
I'm talking about grouping time entries per workspace

**Comment by amulware** [comment]
I believe this has been answered internally?
