### ISSUE TITLE
Enable Android strict mode for debug builds

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5273]
While checking the fragment's lifecycle for our custom made framework.
I've enabled Android's Strict mode and stepped upon some problems.

It might be beneficial to enable some configurations and logging for Debug builds.
Maybe even combine it with AppCenter for Adhoc builds.

Strict mode can be misleading and should be used to detect stuff that is happening by mistake or accident. For example, Strict mode can detect IO access, but that's something essential for in our app.

A very simple, not harmful addition would be:
```
StrictMode.SetVmPolicy(
                new StrictMode.VmPolicy.Builder()
                    .DetectAll()
                    .PenaltyLog()
                    .Build());
StrictMode.SetThreadPolicy(
                new StrictMode.ThreadPolicy.Builder()
                    .DetectCustomSlowCalls()
                    .Build());
```

During development, we can add a `.PenaltyDeath()` to make the apps crash if something is detected.

For adhoc, we could use `.PenaltyListener(...)` and log warnings with AppCenter.

**Comment by amulware** [comment]
This sounds like a good idea. How will we make sure we actually pay attention to the things in AppCenter?

And if we can 'simply' log bad behaviour, shouldn't we include that in production builds as well to get a view of what's going on with our users?

**Comment by daividssilverio** [comment]
I can only suggest this for `Adhoc` or `Debug` builds.

For `Adhoc` builds we'd ask people to run tests and make sure we are checking any useful events when they are using the app.

For `Debug`, we could make this a step during testing. Just check the logs or make the app crash when something terrible is going on with `.PenaltyDeath()`. We could even add this to UI tests, it could work well together (I haven't thought this through).

**Comment by amulware** [comment]
But why can't we do it in production?

**Comment by daividssilverio** [comment]
This is development tool, designed for pre-production use, testing and detecting unwanted/accidental code in the app.

I've never used or heard about this being used in production, nor do I know about its effects on an app in production. I can't recommend this.

If we really want to add this, I'd suggest we plan what we want to track, do a bunch of internal testing and make sure performance isn't affected (that would add a bunch of extra listeners inside our app).

**Comment by amulware** [comment]
Very well. Only for debug and maybe adhoc it is then. :)
