### ISSUE TITLE
Support billable flag in creation view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#528]
The button should only be shown if either:
- the user has selected a project that has a workspace with the Premium feature enabled PR
- the user has not selected a project and the default workspace has said feature enabled

i.e.

```
billableButton.Visible = (project?.Workspace ?? user.DefaultWorkspace).HasFeature(Premium)
```

Further, when the user selects a project the billable button state should be set to the projects DefaultBillable (or something like that) value. (Basically, users can have projects that will always default to billable time entries for convenience)

Of course, if the workspace in question does not have the feature enabled, billable should never be set to true.

**Comment by willsb** [comment]
This is already supported! The `Start` method of the DataSource takes the billable flag into account, and the button in the UI is already bound, so I think there's not much else to do in this issue

**Comment by willsb** [comment]
Please clarify and close as needed, @amulware :shipit:

**Comment by amulware** [comment]
Does it only show the UI if the workspace (of the chosen project/default workspace if no project is chosen) has the appropriate feature enabled?

**Comment by amulware** [comment]
Updated description.
