### ISSUE TITLE
Add interactor: Subscribe to push notifications

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5284]
This is necessary for #5030, #5031.

1. Obtain FCM token through a platform specific service (#5283).
2. API request (#5238).

**Comment by simonrozsival** [comment]
There is an open question: what to do when the API request fails? We should probably either repeat the request immediatelly (e.g., the same way as we implement it for signup - delayed retry) or next time the app is opened.

First implement a naive solution of the interactor (which ignores failure of the HTTP request), but don't close this issue. Please suggest then a solution to this issue and we'll discuss it here and decide on the next steps.

**Comment by daividssilverio** [comment]
We can check if the app has successfully registered an fcm token with our servers every time the app is resumed.

On droid, the usual strategy requires us to save the token anyways.

**Comment by daividssilverio** [comment]
🤔 We could call the `SubscribeToPushNotificationsInteractor` (#5316) everytime the app tries to sync or comes to foreground. That would check if the token stored internally has already been registered with the api, and register it if not, doing nothing otherwise.

**Comment by simonrozsival** [comment]
The implementation was merged into project branch.

**Comment by daividssilverio** [comment]
@simonrozsival  But I thought we'd close this issue after we took care of:
> First implement a naive solution of the interactor (which ignores failure of the HTTP request), but don't close this issue. Please suggest then a solution to this issue and we'll discuss it here and decide on the next steps.
