### ISSUE TITLE
Improve reports bar image

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5289]
As stated in a comment in #5201, on very large display/font sizes, the bar chart image and the line in the header are touching where ther is supposed to be a margin between them.

![image](https://user-images.githubusercontent.com/7033216/58780828-6a0b4900-85da-11e9-95a9-d789199edbf9.png)

**Comment by amulware** [comment]
The image/bar really shouldn't scale with font size, should they?

**Comment by kornelijepetak** [comment]
@amulware on droid there are two different scales used:
* Font size (Small, Default, Large, Larger, Largest)
	* in-situ explanation: `makes the text on screen smaller or larger`
* Display size (Small, Default, Large, Largest)
	* in-situ explanation: `makes the items on your screen smaller or larger. Some apps on your screen may change position.`

That being said, @amulware the reason the images change is the `Display Size`. As long as we are specifying things in `dp` (as we should), we can't prevent OS messing things up with this setting.

> Note that OS warns you that UI elements might change position if you changed the Display size. We should strive to make the app work on all sizes, but let's be honest, it's not possible to satisfy all combinations without actually making different UI for each. On droid, that is 4 x 5 = 20 different combinations.
