### ISSUE TITLE
Implement service: Destroy FCM token

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5292]
Add Android implementation of invalidating/destroying of the FCM token of #5283 

It should be something like (see https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=macos#disconnecting-from-fcm):
```cs
FirebaseInstanceId.Instance.DeleteInstanceId();
```

**Comment by daividssilverio** [comment]
Closed by #5303 (at least for now, reopen if necessary)
