### ISSUE TITLE
Show failed sync in time entry edit view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#531]
Also show the message returned from backend for items that failed to sync to allow the user to fix the problematic data. Ask @pe0ny for design.

**Comment by pe0ny** [comment]
We should always explain to user why we can't sync their time entries.
Show notification-like message at the top of the screen (content stays below the message).
Display this message every time when user opens a time entry that we can not sync.
User can close this message by tapping on it (the whole message should be tappable); though it should appear again when user opens the time entry and we still can't sync it.

![toggl - ios - edit error message 1x](https://user-images.githubusercontent.com/5064445/30548388-b1983e3e-9c9a-11e7-8df9-ddb58bd167ef.png)

**Comment by pe0ny** [comment]
It would also good to know which kind of messages we can get from backend and change the copy if needed.

**Comment by amulware** [comment]
@pe0ny The text from backend is a localised error message that is intended to be shown to the user.

There is no id, or otherwise clear way of knowing what the message _means_ for our app, so having our own copy for specific errors is not realistic until some sort of unique and stable error ids are introduced by backend. I was told this will not happen before v10.

**Comment by pe0ny** [comment]
@amulware Ok, thanks. But is it possible to see some examples? To just make sure these will fit/how these gonna look like.
