### ISSUE TITLE
Only administrators should be able to create public projects

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#5324]
Currently, our mobile apps allow all workspace users to create public projects. This is not expected behavior. Only administrators should be allowed to create public projects, all projects should be private by default. 

For that reason, we need the following changes:
* when creating new projects, public/private switch should be visible only to workspace administrators
* when creating new projects, projects should be by default private

Related to https://github.com/toggl/discussions/issues/53

**Comment by amulware** [comment]
How do we know whether the user is an admin?

What if the user selects a different workspace/client from a different workspace while creating a project?

**Comment by maritoggl** [comment]
When creating a project, user needs to select the workspace as well. The default workspace is selected by default. Perhaps we can simply enable/disable toggling the switch depending on which workspace has been selected? Or hide/show the switch? Will need to check with the designer here which would be a better approach. 
Regarding how do we know whether the user is an admin... I'm not sure, how do we do it in other situations? For instance, how do we know if a user is an admin when we check if they are allowed to create projects at all?

**Comment by amulware** [comment]
I don't know the answer to that question. Perhaps we ignore it completely. And I can't think of anything else that depends on whether we're an admin or not. I recommend checking with one of the developers.

**Comment by syko** [comment]
> The default workspace is selected by default. Perhaps we can simply enable/disable toggling the switch depending on which workspace has been selected? Or hide/show the switch? 

Furthermore, there is also a workspace setting `Who can create projects/clients`. If that is `off`, non-admins shouldn't be able to create projects at all. For that we can filter the list of workspaces in that view to only those where the user an admin. That's what web is doing.

Tech-note: I don't exactly know which endpoints you're using but if you're using v9/me/workspaces, there is an `admin` flag indicating if the current user is an admin in that workspace or not.

**Comment by amulware** [comment]
I'd like a developer to confirm that we store the admin flag in our database correctly. I see that it is in our model interface:

https://github.com/toggl/mobileapp/blob/develop/Toggl.Shared/Models/IWorkspace.cs#L9

Assuming that, this should be relatively easy to fix in the project creation flow.

**Comment by amulware** [comment]
I'm not 100% sure if the changing-workspace question is answered. To make sure to think that case through to not allow users to create wrong data (I'm thinking of hidden html form fields that still submit data).

> Furthermore, there is also a workspace setting Who can create projects/clients. If that is off, non-admins shouldn't be able to create projects at all. For that we can filter the list of workspaces in that view to only those where the user an admin. That's what web is doing.

This sounds like a different point. If we don't implement this, but need to, please create a separate issue @maritoggl

**Comment by heytherewill** [comment]
We already ensure that the user only sees the workspace in which they can create projects (view the `IsEligibleForProjectCreation` method), so all we need to do is check if the user is an Admin to toggle the visibility of the `IsPrivate` field. Also, we should always default `IsPrivate` to true when the user is not an Admin, so we need to check that when changing Workspaces
