### ISSUE TITLE
Write documentation for push notifications

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5340]
- [x] Firebase settings documentation
- [x] API related documentation
- [x] Shared code documentation (FCM token storage, FCM token syncing, interactors)
- [x] iOS specific documentation
- [x] Android specific documentation

**Comment by simonrozsival** [comment]
Add the docs into the `/docs/push-notifications.md` document.

**Comment by daividssilverio** [comment]
Droid docs are ready on #5480.

**Comment by simonrozsival** [comment]
All docs were merged into a project branch.
