### ISSUE TITLE
Make firebase configuration optional

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#5348]
Running the app in the simulator or on a device without the (firebase) keys properly substituted causes the app to crash during launching.

We must make this setup conditional again.

**Comment by daividssilverio** [comment]
I've done this for android some time ago.
There's dummy entries for debug and adhoc profiles.

**Comment by simonrozsival** [comment]
How does it work? And how can we do the same on iOS?

**Comment by daividssilverio** [comment]
On android, the `google-services.json` has dummy entries for the firebase clients.
https://github.com/toggl/mobileapp/blob/develop/Toggl.Droid/google-services.json
https://github.com/toggl/mobileapp/blob/a72e972287ca03a9ac1efd4209c672b2482840ec/Toggl.Droid/google-services.json#L41-L84

That's enough to stop the app from breaking on debug and adhoc.

**Comment by simonrozsival** [comment]
Implementation was merged into the project branch.
