### ISSUE TITLE
[Discussion] Precache suggestions to speed up load time

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5351]
💬 **This is a discussion issue and refers to potentialy improvements to suggestions in some future suggestion update.**

Suggestions are great if they are suggested in a timely manner. But since we are potentially looking at a large amount of TEs to determine suggestions, it may maybe make sense to cache some things in advance. 

So, this is how it would be executed. 
* When user opens the app, suggestions are generated (also after sync and other data-changing triggers).
* Immediately, recalculate the suggestions as if it was `two hours`* later and cache the results.
* User closes the app and reopens it a later time. While the suggestions are being calculated, he is presented with the cached ones (if the time distance from the cached version is not too great). If newly calculated ones differ, they overwrite the cached ones.

The only provider for which this does not make sense at the moment is the most used time entries provider. Calendar provider can check events closer to that another time and also the ML one can mock it's time input to that time as well.

Now, the main issue is: ♻ Cache invalidation is hard.
\* The proposed time of 2 hours is really arbitrary and needs to be thought out to find proper value. It is even possible that no value makes sense.

Another thing is: We need to measure some 🏎. Since this idea is a rather big technical bite, it is possible that the benefit in the speed boost does not really justify the cost.

**Comment by amulware** [comment]
This definitely needs discussion and should be based on actual data.
