### ISSUE TITLE
Fetch 6 weeks of time entries if there is no (valid) since date

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#536]
Please do a test of how many time entries the API returns when not given a since date. I believe it may be 9 days or something like that but would like this confirmed. Please test which parameters are taken into account for this as well: start time, end time, at date.

In either case, we most likely want to make sure to fetch 6 weeks of data, if we would otherwise fetch without a since date. This will make sure we have enough data for suggestions and auto completion.

**Comment by simonrozsival** [comment]
I asked #backend and found out this:

- By default we get 10 days of data
- We shouldn't ever ask for more than ~10 days and use detailed reports instead

I am not sure if detailed reports help us. I will wait with this issue until you come back and we can discuss it more.

**Comment by amulware** [comment]
What is currently implemented in this regard @simonrozsival?

**Comment by simonrozsival** [comment]
I didn't do anything related to this issue other than the discussion with backend.

**Comment by amulware** [comment]
It won't break the way it is right now, so let's leave it at that. We'll pick this up again using detailed reports once we implement the reports API.
