### ISSUE TITLE
Suggestions: Recalculate suggestions when app enters foreground from background

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5388]
When app goes to background and comes back to foreground the `viewAppeared` does not fire (since the view never disappeared in the first place, just went to background). which is fine when changing tabs. Suggestions need to recalculate also when the app comes to foreground state.

- Check if the app updates the suggestions when coming to the foreground after entering the background and discuss if it needs changes

**Comment by kornelijepetak** [comment]
I am not sure about iOS, but on Android, if the app returns from background (i.e. after unlocking phone or switching from another app) the activity will transition to the `RESUMED` state which corresponds to the `viewAppeared` viewmodel's lifecycle method. I can see it being called.

So, I might not be understanding your question. 🤔 

Can you please elaborate a bit more. Or maybe specify whether this is an issue on iOS (and whether it was reported when testing an iOS app).

**Comment by sofokli1** [comment]
It looked like this when testing your branch on iOS but will test some more and update here

**Comment by sofokli1** [comment]
Tested, when coming from background to foreground  `ViewAppeared` does not fire on iOS.

**Comment by sofokli1** [comment]
I will use the background service in suggestionsVM to recalculate suggestions as well
