### ISSUE TITLE
Suggestions disappear when app goes to the background

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5391]
As reported, 

> I double-hit home (this is iOS), and in the preview with the other apps, it stopped showing suggestions, but kept the space empty, and then when I went to the app, the empty space collapsed - I guess that’s just a funnily timed layout update though.

and 

> suggestions are gone again though
> just had the app in the background for the last hour or so

Let's investigate what's going on.

**Comment by kornelijepetak** [comment]
I'll also check whether this happens on droid as well. If yes, I'll add a `android` label.

**Comment by sofokli1** [comment]
possible steps to reproduce:
- have app in background for several hours
- go back to it
- force refresh
- while/at the end of the sync (hard to tell), pull down again slightly, as soon as I release (I think) the suggestions where gone

**Comment by sofokli1** [comment]
possible issue: 
one of the providers crashes (I give a good probability to the machine learning one) and the error gets propagated to the suggestionsVM thus ending the observable, suggestion view goes away. Recreating the suggestionVM with an app restart, makes it work nice again.

**Comment by kornelijepetak** [comment]
This seems to have been fixed. We need to reopen if it starts happening again.
