### ISSUE TITLE
Suggestions: Decide on  how many calendar based events are we going to show

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5413]
At the moment we are showing all we can.
First we show calendar machine learning (1 or 0)
Then we show calendar events (0 - 3 based on the above and availability of calendar events) 
In the end we show suggestions based on frequency (0 - 3 based on the above and availability of enough time entries)

Max total is 3.

The question is should we constrain the calendar events to the 1 max, since it can completely remove from the UI the frequency based once?

@maritoggl what do you think?

**Comment by sofokli1** [comment]
As discussed in slack there will be only 1 calendar suggestion

**Comment by kornelijepetak** [comment]
This actually reminded me what was one of my future improvement ideas, @sofokli1. Gonna create an issue for that.
