### ISSUE TITLE
About page not working

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5429]
## 🐛 Bug Report
The About page in settings is not working in iOS 2.0, it's working fine in 1.22 though.

## Context

Build/Branch: release/daneel-2.0-apple
Phone OS: iOS
Phone model:

## Expected behavior
When I select the About page, I expect to see links to the privacy policy, terms of service and licenses.

## To reproduce
Open settings
:bug: Tap about

**Comment by heytherewill** [comment]
https://github.com/toggl/mobileapp/pull/5399
