### ISSUE TITLE
CalendarCollectionViewSource: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5432]
## 💥 Crash Report
Apparently there's something wrong with the calendar layout.
```
CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath (Foundation.NSIndexPath indexPath)
SIGABRT: Object reference not set to an instance of an object
```

### 👥 Impact
This is affecting 93 users (iOS 12.3.1 for most of them) of 1.22 and it has happened 200 times so far.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3567257895u/overview

### 📝  Exception & Stack Trace
`CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath (Foundation.NSIndexPath indexPath)
SIGABRT: Object reference not set to an instance of an object`
```cs
CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath (Foundation.NSIndexPath indexPath)
CalendarCollectionViewLayout.frameForEditingHour (Foundation.NSIndexPath indexPath)
CalendarCollectionViewLayout.LayoutAttributesForSupplementaryView (Foundation.NSString kind, Foundation.NSIndexPath indexPath)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22707177856)

**Comment by TheSoloJake** [comment]
Can replicate issue on iPhone XS; Slack link below to video replicating issue 

https://toggl.slack.com/archives/C029WU7AY/p1562675149015300
