### ISSUE TITLE
DateTimeToFormattedString: The added or subtracted value results in an un-representable DateTime.

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5434]
## 💥 Crash Report
Judging by the reports this happens when editing a time entry.

### 👥 Impact
58 users for 1.22. Happening 65 times at the moment.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/2387448588u/overview

### 📝  Exception & Stack Trace
`DateTimeToFormattedString.getDateTimeOffsetInCorrectTimeZone (System.DateTimeOffset value, System.TimeZoneInfo timeZone, Toggl.Core.Analytics.IAnalyticsService analyticsService)
SIGABRT: The added or subtracted value results in an un-representable DateTime. Parameter name: t`
```cs
DateTime.op_Addition (System.DateTime d, System.TimeSpan t)
TimeZoneInfo.ConvertTime (System.DateTimeOffset dateTimeOffset, System.TimeZoneInfo destinationTimeZone)
DateTimeToFormattedString.getDateTimeOffsetInCorrectTimeZone (System.DateTimeOffset value, System.TimeZoneInfo timeZone, Toggl.Core.Analytics.IAnalyticsService analyticsService)
DateTimeToFormattedString.getDateTimeOffsetInCorrectTimeZone (System.DateTimeOffset value, System.TimeZoneInfo timeZone, Toggl.Core.Analytics.IAnalyticsService analyticsService)
DateTimeToFormattedString.Convert (System.DateTimeOffset date, System.String format, Toggl.Core.Analytics.IAnalyticsService analyticsService, System.TimeZoneInfo timeZoneInfo)
EditTimeEntryViewController+<>c.<ViewDidLoad>b__9_10 (System.DateTimeOffset stopTime, Toggl.Core.Models.Interfaces.IThreadSafePreferences preferences)
WithLatestFrom`3+_+FirstObserver[TFirst,TSecond,TResult].OnNext (TFirst value)
```

**Comment by arturs105** [comment]
Putting this on-hold, since this issue can potentially be closed when we get the result from #5237.
