### ISSUE TITLE
Track if users install the app internally or externally

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5435]
Since #5433 allows the app to be moved/installed to the SD card, we can measure, how many users actually do that.

A simple check on startup should be enough. I found [this](https://stackoverflow.com/questions/6256751/android-get-install-location-with-packagename) SO post about getting install location, which might help.

❗️ Though beware of OEMs like Samsung, Huawei etc. - the install location may be different on different devices. This needs to be tested on as many different devices as possible, and best if they are from different manufacturers. ❗️

**Comment by kornelijepetak** [comment]
Two points needs addressing.

There is a chance for the check to fail. In that case, we can't say with certainty whether it's in internal memory or on sd card. Regarding metrics, I propose that we introduce the `Unknown` value for cases like these. This makes most sense to me.

The question is also, when to send this metric?

* [ ] On app start
* [ ] Once per install/login (stored in a local storage)
* [ ] Once per change (stored in local storage and then refreshed if changed)

**Comment by amulware** [comment]
1. makes sense to me
2. app start is simplest I figure? any arguments not to do that? it'll still give us a decent enough ratio I figure
