### ISSUE TITLE
Include install location in Submit Feedback data

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5436]
Ref: #5433 

Since installing the app in an SD card will reduce performance, the install location could be useful data to include in the feedback report, especially if users are complaining about poor performance, slow startup times etc.

**Comment by heytherewill** [comment]
This should be a boolean value

**Comment by arturs105** [comment]
If this is a boolean then we must be careful and test this on lots of varying devices due to the following:

(horrible) OEMs like Samsung, Huawei etc. may change the install location to something different on different devices. This needs to be tested on as many different devices as possible, and best if they are from different manufacturers
