### ISSUE TITLE
Custom Siri intents are only available for iOS 12 +

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5438]
## 💥 Crash Report
Custom Siri intents are only available for iOS 12 and up, which is causing the Siri section of settings to crash for users in iOS 11.

### 👥 Impact
30 users, 36 times.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3965596390u/overview

### 📝  Exception & Stack Trace
Not much needed to add here, since the issue is pretty self explanatory.

**Comment by amulware** [comment]
@juanlaube Do include issues fixed in a hotfix in your release project please. ;)
