### ISSUE TITLE
Let's not block anything because of RemoteConfig

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5446]
## 🚧 Refactor Proposal
During #5411, I noticed that we are using Firebase remote config in a not ideal way.

We are running and the remote config service and fetching values from Firebase in the main views of the app. This isn't bad in the case of the `RatingView` because it subscription runs in background and it shouldn't be blocking anything.
Firebase should be keeping the local cache and only making http requests every 12 hours.

The problem is more serious when we put the remote config calls inside sync states.
More specifically, in #5411 `SyncPushNotificationsTokenState` queries the remote config to check if we should have the app's FCM token registered with the server.

During my tests, even with firebase's remote config developer mode enabled, the remote config takes about 60 seconds to finish fetching the values. 

It sounds a lot like it, and we are most likely just being throttled; and this shouldn't happen in production. Still, in normal circumstances, it will make an http request and take whatever time it takes to complete it every 12 hours. This will slow down sync every 12 hours.

This is also a problem when handling received push notifications. On #5377, the remote config dependency was added to check wether or not we should handle incoming push notifications.
This can happen when the app is in background/not open on android, where there's an execution limit of 10~20 seconds.

## Platforms affected:

- [x] 🤖 Android
- [x] 🍎 iOS
- [x] 🖥️ Shared layer

## Technical aspects
The idea is add another level of cache, handled by us in the application.
Then, we can asynchronously fetch firebase remote config when the application starts.
We can check if the remote config succeed in the last 12 hours or more, running it again if it didn't.
The app would use default values and internally cached values for most of the time.

Also, it seems that iOS isn't displaying that throttling problem I've commented above.
I've also tested firebase with our credentials with the updated Firebase libraries on a kotlin project and it works alright there.

So... even after doing all of this, we might want to revisit this problem when we are able to update the Xamarin Firebase libraries without breaking the app (and the libraries's apis are present).

**Comment by simonrozsival** [comment]
The implementation was merged into a project branch.
