### ISSUE TITLE
Investigate syncing observable

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#545]
It appears that the syncing observables currently does not appear to be sending updates correctly.

I took a quick look at the code and it seems fine, so probably needs some more detailed debugging.

**Comment by simonrozsival** [comment]
So the problem is that the `SyncManager` locks itself - the private `isRunningSync` variable is set to `true`, although it should be `false` after sync operation finishes. Also the `StateMachine` locks itself - the `currentState` is not set tu null.
