### ISSUE TITLE
The sync spinner is visible after app starts without sync

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5457]
## 🐛 Bug Report
The spinner of the sync bar is visible when app starts and not syncing. It shows as 2 dots on the navigation bar lower line separator (gif below) 

## Context
Build/Branch: Push notification adhoc build may happen in develop
Phone OS: iOS
Phone model: any

## Expected behaviour
no spinner spinning if there is no sync

## To reproduce
Start the app wait for the sync to finish. fully close the app (not just send it to background) and open it again in a couple of seconds. no sync will happen and the spinner will be interfering with the navigation bar lower separator line just under the toggl word in the tittle.
![Jun-20-2019 13-37-33](https://user-images.githubusercontent.com/885122/59849817-99eb7800-9360-11e9-8b22-8806faa5ac3a.gif)

## Suggestions
most likely the spinner it needs to be set as hidden in the xib or code as default initial state

**Comment by amulware** [comment]
Actually, if you close the app entirely, shouldn't it start a sync when you open it? Nevertheless, this glitch should not be happening.

The question is whether it's worth fixing, or if we should entirely redo the sync-status bad sometime soon as we've discussed.. a long time ago.

**Comment by sofokli1** [comment]
i think, it will not sync if less than 5 min have passed

**Comment by amulware** [comment]
Is that state persisted? I thought this was only saved in memory and would be reset if entirely restarting the app.

**Comment by amulware** [comment]
I'm closing this for now. We should redo the syncing indicator from scratch at some point.
