### ISSUE TITLE
iOS App: Resetting Device Settings Prevents Reapplication of Settings

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/mobileapp#5471]
User recently cleared all Location & Privacy settings on their iPhone through the option Settings > General > Reset > Reset Location and Privacy. After doing this, the option to reenable calendar access is not shown in the app settings area. 

Affected user [case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/22559747815)

User is planning on deleting and reinstalling app to get option back.

**Comment by amulware** [comment]
I'm wondering if, even though we can't show the permissions dialog more than once, we still need to poke iOS for permissions for this to show up in the settings again.

Definitely needs investigating.

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24175710310)

**Comment by juanlaube** [comment]
I cannot reproduce the problem, I don't know when or what we did, but this bug has already been fixed.
After doing a reset of location & privacy, when I go the the calendar settings, I'm immediately requested to authorize access to the calendars.
