### ISSUE TITLE
Start date change glitch

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5472]
## 🐛 Bug Report
In edit view when editing start date and hitting the X button (even if no change is performed), the date changes to `01-01` in the edit view UI.

## Context
Build/Branch: develop
Phone OS: ios (should be the same on android)
Phone model: any

## Expected behavior
the original date before the date picker is shown should not change if the user taps on the x button.

## To reproduce
- open the edit view for any TE
- tap on `start date`
- tap x and look at `start date` value

## Suggestions
possible bug in `SelectDateTimeViewModel`

**Comment by amulware** [comment]
Worse: it is set to 01-01-01 (or something like that). This might be the origin of the unrepresentable date times we've been seeing.

Ref https://github.com/toggl/mobileapp/issues/5237

In either case, this seems like a major issue.

**Comment by amulware** [comment]
Ref https://github.com/toggl/mobileapp/issues/5434

**Comment by sofokli1** [comment]
![Jun-25-2019 17-56-39](https://user-images.githubusercontent.com/885122/60117977-318f0300-9773-11e9-979f-142eac8d868d.gif)

**Comment by sofokli1** [comment]
not sure what was merged since i tested, but this looks fixed on develop now. we can close this.

**Comment by heytherewill** [comment]
Probably fixed by #5241
