### ISSUE TITLE
Track how many users have an Apple Watch

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5484]
We can track how many users have an Apple Watch paired with their iPhones using [this](https://developer.apple.com/documentation/watchconnectivity/wcsession/1615665-ispaired). This will help us decide if it's worth to work on an Apple Watch app.

We need a new analytics event, `WatchPaired` with one single boolean parameter, `Installed`.

In my opinion we should track this only once per user to avoid duplicates, the event could be tracked on login or sign up so we don't add new storage for a single event.

The event name is generic enough to be reused in the future in Android for WearOS devices.

**Comment by amulware** [comment]
No tracking for existing users then? That actually might be also very interesting, and very interesting to know if there's a difference between existing and new users. 🤔

**Comment by juanlaube** [comment]
Good point! 😄  
So yeah, we need storage if we want to track only once per user

**Comment by amulware** [comment]
I'm sort of fine with tracking on every app start, but it does occur to me that we will then get more data from users who use the app more/restart the app more, which may not be ideal.. not sure about that one.

Ref https://github.com/toggl/mobileapp/issues/5435

**Comment by heytherewill** [comment]
Tracking only once per user might signal falsely if the user has a watch but is not connected to it when the app opens, right?

**Comment by amulware** [comment]
Perhaps, but which of these two is the bigger problem? Do we need to do both? :D

**Comment by amulware** [comment]
Maybe going with the simpler solution for now would be best /shrug

**Comment by juanlaube** [comment]
I think the method will return true if the watch is paired, even if it is not reachable, because there's a different method for that. But all your points are valid and maybe tracking per session is best right now.

**Comment by sofokli1** [comment]
@amulware @juanlaube @heytherewill do you all agree about tracking per session?
should i move forward with the proposed analytic event mentioned at the top?
> We need a new analytics event, WatchPaired with one single boolean parameter, Installed.
