### ISSUE TITLE
Track TE deletion origin

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5496]
## What

Add an `Origin` parameter to the `DeleteTimeEntry` event. Current options (I think?):
- `EditView`
- `LogSwipe`

Seems straight forward? Not forgetting anything?

## Why

I'd like to know how much swiping is used to delete. I suspect it's higher than continuing since swipe deletion is a very common feature and going to the edit view is very cumbersome.

**Comment by juanlaube** [comment]
@amulware do you want to consider two cases for the swipe? Single and grouped? 🤔

**Comment by juanlaube** [comment]
Same thing applies for the edit view.

**Comment by amulware** [comment]
Yes, why not, let's add a property for that. :)
