### ISSUE TITLE
Fix TimeEntryContinued.Origin event parameter on Android

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5497]
## 🐛 Bug Report
TimeEntryContinued.Origin on Android doesn't show any occurrences of `GroupContinueButton` while there's a lot on iOS. Must be a bug somewhere?

## Context
Observed here: https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/analytics/events/TimeEntryContinued

## Expected behavior
I'd expect roughly similar numbers as iOS, or at least SOME occurrences, definitely not 0.

**Comment by kornelijepetak** [comment]
This is really confusing.

I've now tried on `2.1` (internal test track) to group some time entries and then continue the group several times to see what gets reported. I see immediate increase in `ContinueButton` parameter.

However, when I run the app in debug and tap the continue button on a group, I see the correct value returned to the event:

![image](https://user-images.githubusercontent.com/7033216/60716434-aacee880-9f1f-11e9-816b-898c79376da2.png)

This is weird.

**Comment by kornelijepetak** [comment]
This is even closer to the bare metal:

![image](https://user-images.githubusercontent.com/7033216/60716756-7f98c900-9f20-11e9-9878-5c2170419392.png)

**Comment by juanlaube** [comment]
This was solved by @heytherewill in #5529

The problem was in `MainLogCellViewHolder.onContinueClick`, instead of sending the correct continue mode it was using a hardcoded parameter.
