### ISSUE TITLE
Update provisioning profiles to include the widget

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5499]
We need to update our provisioning profiles to include the widget extension in debug, ad hoc and app store.

**Comment by sofokli1** [comment]
@juanlaube shouldn't the ad hoc happen when the widget is in develop and the app store one when the widget is scheduled to be in the next release?

**Comment by sofokli1** [comment]
do you mean create widget provisioning profile like the ones we have for siri?

**Comment by juanlaube** [comment]
Correct, we need to do the same thing we have for the Siri extension. Paul is the only person with permissions, so please coordinate with him if you're going to take this.
