### ISSUE TITLE
Make toolbar's height consistent

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5524]
We have 4 different screens (tabs).
Literally, the toolbars in each have different heights.
I'd like to make them all the same height.

Any objections?

Also, what's the situation on iOS? Is it the case there as well?

**Comment by daividssilverio** [comment]
Really? I thought the ones that were not the default height (`56dp`) were custom components that look like toolbars, like Start/Edit/Calendar views.

**Comment by kornelijepetak** [comment]
Some of the toolbars are indeed custom, but non the less, all should be of the same height. It looks a bit jumpy if they are not.
