### ISSUE TITLE
Group time entries not working always correctly

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5556]
## 🐛 Bug Report
Group time entries in rare occasions do not group correctly. In my case 8 TEs without description, project etc. in the same day were grouped as 6 and 2. screenshots below

## Context
Build/Branch: 2.1, 2.0.1
Phone OS: ios maybe also android
Phone model: iphone x

## Expected behavior
group everything correctly or at least as the web app
![IMG_1959](https://user-images.githubusercontent.com/885122/60842066-eeee1180-a1db-11e9-8a6b-dc669c1a7adf.png)
<img width="1441" alt="Screenshot 2019-07-08 at 23 20 33" src="https://user-images.githubusercontent.com/885122/60842080-fa413d00-a1db-11e9-90f4-2d66be7c241f.png">

## To reproduce
unknown

## Suggestions
maybe the diffing algo!?

**Comment by sofokli1** [comment]
in order to reproduce this:
create a group with at least 4 TEs (no project, not tag, no nothing)
select 1 of the internal projects and set the `no project` option from an other Workspace
repeat for the next on and see how you end up with 2 groups of 2 TEs that in the web still look like 1 group of 4.

My understanding is that Web disregards the WS when no project is selected in the TE.
@amulware should we mimic web or should this be regarded as the correct behaviour?

**Comment by amulware** [comment]
Did you test this in web? If so, and it works like you describe, please create an issue on the internal discussions repo to verify what the correct behaviour is.

**Comment by amulware** [comment]
If we need that input from product, I propose we move this to the next release.

**Comment by sofokli1** [comment]
@arturs105 moving this to the next release is you jurisdiction since this was planned in your release.

**Comment by sofokli1** [comment]
for reference https://github.com/toggl/discussions/issues/66

**Comment by amulware** [comment]
It was clarified that ours is the correct behaviour.
