### ISSUE TITLE
Creating tags crashes

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5569]
## 🐛 Bug Report
I don't have any more info than the title, except that several users have reported this through reviews.

## Context

Android. (At least I haven't seen reports on iOS)

## Expected behavior
🚫💥

## To reproduce
Try creating some tags in the start or edit view, see what happens.

## Suggestions
💣🔫

**Comment by nicktoggl** [comment]
**First case** 
App name and version: Giskard 2.1, 
Phone model: 9ONEPLUS A6013 
Platform and OS version:Android 9
conversations/22787786814

"Steps to reproduce: click the tags field, type 1 character, app crashes"

**2nd Case**
App name and version: Giskard/2.0.1
Phone model: SM-G973F
Platform and OS version: Android 9
conversation/22803926749

"the app is crashing a lot. when trying to create an extra tag to track an assignment I'm doing and every time I type the first character for the tag, the app restarts."

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/22819537259)
Giskard 2.1.1
Android 9
POCOPHONE F1

>when using &#34;Tag&#34; app crashes right away. I have done update also and before last update it was not working also

**Comment by amulware** [comment]
Since we have 2.1 reports, consider checking specific user's exceptions on app center.

**Comment by juanlaube** [comment]
Some crash made it to AppCenter: https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/1997674262u/overview
