### ISSUE TITLE
Reports calendar is broken on iPad

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#5571]
## 🐛 Bug Report
On iPad we can enter a state when the reports calendar doesn't show in wChR mode.

## Context
Build/Branch: develop
Phone OS: iOS 12.2
Phone model: Simulator and real iPads

## Expected behavior
It should switch to the mobile view.

## To reproduce
Start iPad app in wRhR, open reports, resize to wChR, and try opening the reports calendar.

## Suggestions
Change the code that adds/removes the Reports Calendar VC to be triggered by Size Class instead of Interface idiom.

**Comment by dshr** [comment]
This might need a proper re-evalution, since both the iPad and iPhone implementation is rather lacking.

**Comment by amulware** [comment]
Unscheduling for now, since we'll likely shake this thing up a lot.

**Comment by amulware** [comment]
I assume this is no longer relevant.
