### ISSUE TITLE
Customise cell swipe actions

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5574]
We basically need the Android part of: #5540 

The iOS and Core parts are already in place. There's a setting in `IUserPreferences` for each of the swiping actions, and there's another PR coming that will add the ability for users to change that through the app settings.

So all this is missing for now is the Android part of the actual custom swiping actions for the three cases: disabled, delete and continue.

**Comment by amulware** [comment]
It's not confirmed whether we are going to do this.

**Comment by semanticer** [comment]
What is the state of this task? @amulware @Odrakir Is it now ready for work? 👷

**Comment by amulware** [comment]
I believe it's ready, @Odrakir knows for sure.

**Comment by Odrakir** [comment]
It's working for iOS, meaning the preference storage and property in the view model are there, all it's missing for Android is to add the setting in the settings screen and make the changes so it actually reflects on the swiping.
