### ISSUE TITLE
No suggestions visible after some time

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5583]
## 🐛 Bug Report
After using the new suggestions for maybe a day, they are no longer visible until I restart the app.

## Context

Build/Branch: 2.1 AppStore
Phone OS: 12.3
Phone model: iPhone 6S

## Expected behavior
I have so much data and frequent calendar events, there should always be suggestions (and there have always been in the past).

## To reproduce
Not exactly sure, it just happened after I used the app for a while, possibly a whole day or so.

Nothing I do seems to get them back, except restarting the app completely.

**Comment by sofokli1** [comment]
If they disappear completely there was an error in one of the providers thus completing the observable that handles the suggestions and stoping to emit until restart.
