### ISSUE TITLE
Android widget design leftovers

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5607]
Some leftovers from #5568

This is feedback from @kornelijepetak on that particular PR

I'm having issues with this

![](https://user-images.githubusercontent.com/7033216/61376114-c54e7d80-a8a0-11e9-9ee3-05a6233a7452.png)

This is all in the same line. When the widget is sized down, things don't go into a new row.

Also, "marquee" does not work in this setup. I can't see anything scrolling. Most probable that the width of particular textview is not fixed.

But otherwise, I'd actually propose a change in the design that puts the project/client/task to new row, as the running TE does. Otherwise, it's a lot of blank space. Even on smaller phones, I think the card is big enough for both rows to be visible. Gives more space for both description and project/client/task.

**Comment by kornelijepetak** [comment]
Closed in favor of #5093 .
