### ISSUE TITLE
Get rid of Firebase Remote Config

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5638]
This was discussed in Buenos Aires. Apparently it's possible since we are not using it anywhere, but no one volunteered to investigate this initiative, so I'm creating this issue with high hopes that a noble soul will stand up for this task

**Comment by kornelijepetak** [comment]
I'm confused. We are using Firebase Remote Config for detecting when to fire a "Rate the app" dialog...

Are we talking about the same thing?

**Comment by amulware** [comment]
I also do not recall any such discussion. We're using it both for the rating dialog and for push notifications, and it's the only AB testing system we have, should we want to test something in the future.

**Comment by heytherewill** [comment]
This is the last point in my notes. I honestly don't remember who pointed it out, but someone said so. I'm just the messenger 😄

**Comment by kornelijepetak** [comment]
We should not shoot the messenger, but we might wanna close this issue. It makes no sense to me. :/

**Comment by amulware** [comment]
Messenger better have a good message or else. :trollface:
