### ISSUE TITLE
Use collections more consistently in our codebase

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5643]
## 🚧 Refactor Proposal
@juanlaube has pointed out during our Buenos Aires discussions that we've had problems with enumerating sequences multiples times. A good way to avoid that is making sure that we are enumerating things that do expensive operations.

## Technical aspects
The safest route I see is simply making sure that we are always exposing `IImmutableList` from ViewModels. This will ensure that we enumerate only once before displaying any kind of list. 

Whoever works on this, please keep an eye open for possibilities of improvement. While  we want to enumerate, we only wanna do it at the last possible moment

**Comment by amulware** [comment]
This issue is much too open-ended, what should actually be done here?

**Comment by amulware** [comment]
Clarified: This issue is for using IImmutableList everywhere. Any other things found should be follow-up issues.
