### ISSUE TITLE
Track edit view closing

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5648]
I'd like to add an event `EditViewClosed` with the following property:

`reason` : `save|save-without-change|cancel|delete`

I'm not married to the name of the property, so if you have something better, go ahead. I do definitely want to have all four values, especially the distinction between saving after editing and saving without editing.

Depending on which is easier, I'm fine if 'without change/editing' is implemented as 'without tapping any of the fields' and not actually does a comparison - i.e. do which is easier. But please be clear about which way you do this in the PR description and why.

**Comment by juanlaube** [comment]
I added a second property that indicates if this is about grouped time entries or not.
For `SaveWithoutChanges`, it compares the initial vs final values, this reason will be used unless some field is different when saving.
