### ISSUE TITLE
Track time entry stopping from edit view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5649]
I believe we currently don't track this at all.

I propose we add another value to the `TimeEntryStopped.Origin` property, and also add another value to `EditViewTapped.TapSource`, but I'd like whoever does this to look into other cases.

For example, there's stopping in the edit view itself, but what about stopping in the wheel view - which can be done from both edit and start view? Can we track these cases in a meaningful way? Are there other cases?

**Comment by amulware** [comment]
In the future (from now) it may also be possible to stop straight from the calendar view - take a look at that as well.

**Comment by kornelijepetak** [comment]
Separated Widget and Calendar parts as #6355 and #6356, respectively.
