### ISSUE TITLE
Autocorrect and project/tag completion cause graphical glitch

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5662]
## 🐛 Bug Report
If you search for a project in the start view, and they keyboard thinks that your search string should be corrected to something else, it will select the whole word (including the @) and that selection will still be visible if you then select a project.

<img width="1200" alt="Screenshot 2019-07-29 at 12 37 33" src="https://user-images.githubusercontent.com/3987892/62045826-44777600-b1fe-11e9-8c7e-bd6500768392.png">

## Context

Build/Branch: 2.1.3 Appstore build (has been this way for months though)
Phone OS: 12.3 or so
Phone model: iPhone 6S

## Expected behavior
EITHER
1. the selection should go away after the project was selected
OR
2. it shouldn't even autocorrect when searching for tags/projects

## To reproduce
- be in the start view
- search for a project (very sure this happens for tags too)
- type something that results in a project suggestion, but also makes iOS want to correct your spelling
- select a project
- see the selection still visible until you continue typing

## Suggestions
Depending on the desired behaviour (and maybe technical feasibility) we should either:
1. clear the selection when selecting a project or tag
OR
2. disable auto correction if we're searching for projects/tags (and only then, we do want it on otherwise)

I _think_ we should go with 1. because we want users to be able to have correctly spelled project names when creating new projects, but maybe @maritoggl should weigh in.

**Comment by maritoggl** [comment]
1
