### ISSUE TITLE
Profile the Start Time Entry View model startup

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5665]
This view takes a while to load on older devices. We should measure what are the most problematic methods and figure out what can be improved to make it load faster.

**Comment by pdrj** [comment]
In my profiling, the activity load took 452ms. 350ms of that was spent in `InitializeBindings`. Out of these, 

```
    ViewModel.Suggestions
                .Subscribe(adapter.Rx().Items())
                .DisposedBy(DisposeBag);
```

took by far the longest: 175ms. I will keep looking for what can be done.
