### ISSUE TITLE
Profile dropped frames when pulling to refresh

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5666]
When pulling to refresh on the main log on older phones, you can notice that the spinner's animation jaggy at the beginning. We need to figure out what is being done on the main thread and can be further improved.

**Comment by heytherewill** [comment]
This seems to be resolved on newer builds (tested develop on a garbage-tier Lollipop phone)

Could someone else from @toggl/androids test as well just as a sanity check?

**Comment by daividssilverio** [comment]
Yeah, tested on my android Go, 512 ram, quite slow device and it works fine. There were some frames dropped, but not during the pull-to-refresh process. We may close this.

**Comment by heytherewill** [comment]
Closing as fixed
