### ISSUE TITLE
Force our interactors to execute on a Background thread

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5667]
Everything that's UI related in our app already marshalls to the main thread, so we can safely simply force our interactors to run on a background thread in the very execute method. 

This can be done creating a wrapper class and composing-instead-of-inheriting :tm:

```csharp
public sealed class BackgroundExecutionInteractor<T> : IInteractor<IObservable<T>>
{
    private readonly IScheduler backgroundScheduler;
    private readonly IInteractor<IObservable<T>> innerInteractor;

    public BackgroundExecutionInteractor(IInteractor<IObservable<T>> innerInteractor, ISchedulerProvider schedulerProvider)
    {
        this.innerInteractor = innerInteractor;
        backgroundScheduler = schedulerProvider.BackgroundScheduler;
    }

    public IObservable<T> Execute()
        => innerInteractor.Execute().SubscribeOn(backgroundScheduler);
}

public static class BackgroundExecutionExtensions
{
    public IInteractor<IObservable<T>> EnsureExecuteRunsOnBackground(this IInteractor<IObservable<T>> innerInteractor, ISchedulerProvider schedulerProvider)
        => new BackgroundExecutionInteractor(innerInteractor, schedulerProvider);
}
```

And then using this whenever applicable (which should be most places; we don't really have any interactors that should run on a special thread).

**Comment by Odrakir** [comment]
I might be wrong, but this seems a bit dangerous to me. I don't really know if the interaction needs to run in a specific thread, do I? Maybe it's deriving an observable from something happening in the DB layer and it has to run in the same thread where the DB was first initialised...

I don't know, I think I would leave this to each specific interactor.

**Comment by amulware** [comment]
If something needs to run on a DB thread, it should probably run inside database code. The upcoming database queries should make that much easier.

**Comment by heytherewill** [comment]
Not needed since we are moving towards the idea of using tasks, which are much easier to deal with when it comes to marshalling
