### ISSUE TITLE
Check the solution for deadlocks in SyncManager and StateMachine

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#568]
There was a problem with synchronization getting stuck in a dead-end (#545) and it was fixed with PR #561 

I would like @amulware to have a look at this solution since he was on vacation at the time the problem was addressed (Sprint II).

**Comment by amulware** [comment]
I do not fully understand that original problem, but the solution to it looks fine to me. I.e. I do not see how it could introduce any other errors.
