### ISSUE TITLE
Start a new time entry with all required properties set to valid values

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#569]
Right now at least the `WorkspaceId` and `UserId` are not set explicitly and so both default to `0L`, which makes it impossible to sync.

- [x] Set `UserId` to the logged in user's ID
- [x] Set `WorkspaceId` to the user's default workspace
- [x] Set `CreatedWith` to the name of the app (and its version?)
- [x] Check the POST endpoint of time entries, if all the required properties have an explicitly set value
- [x] Update the Builder validation to require explicitly setting these propreties

**Comment by simonrozsival** [comment]
So there are only 3 required fields for a time entry: `start`, `workspace_id`, and `created_with`. We could add `[IgnoreWhenPosting]` to the `UserId` property to simplify our lives. But we still have to specify the `WorkspaceId`, so maybe posting the explicit values could be less error prone and we should still enforce these fields in the Builder.

**Comment by willsb** [comment]
I agree that we should enforce it in the builder. I wouldn't add `IgnoreWhenPosting` unless absolutely needed
