### ISSUE TITLE
IndexOutOfBoundsException on RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5692]
## 💥 Crash Report
It seems to be a crash that happens when adding/selecting tags.

### 👥 Impact
I has affected 167 users, with 446 occurrences; 
About 0.2% of our users in the last 30 days. 

### 🔗 Context
Very similar to #5691 and possibly #5569
Could have been already fixed by #5624

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/917105280u/overview

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:-1).state:12 android.support.v7.widget.RecyclerView{f6b25a3 VFED.V... ......ID 0,168-1080,1050 #7f0d01e9 app:id/SelectTagsRecyclerView}, adapter:md5e6930ea5438967c9497bdc857a01d090.SelectTagsRecyclerAdapter@fab1958, layout:android.support.v7.widget.LinearLayoutManager@528e0a0, context:md56d31f6f2c59878fdf075cc45b4e7258a.SelectTagsActivity@bd46e3b
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
...
```

**Comment by pdrj** [comment]
@daividssilverio this seems to be the same as #5820 - are you OK with closing this one? I know this issue has been created first, but the other one has a bit more info in it.

**Comment by daividssilverio** [comment]
Alright @pdrj . Superseded by #5820 .
