### ISSUE TITLE
Project Name is hidden by Workspace Name 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/mobileapp#5696]
## ⛑️ User Support

The project name on the Reports page is hidden by workspace name. If you scroll to the bottom of the page, the last project name is hidden. 

![image](https://user-images.githubusercontent.com/49634673/62359527-69d2ef80-b530-11e9-8600-4365e9095b51.png)

## About the user

App version: iOS (2.1.3) 
Phone OS: iOS
Phone model: iPhone 8

## Expected behaviour

The Reports page shows the workspace name at the bottom. However, this covers the project name. Scrolling even to the bottom of the page doesn't help, as the last project name is still covered up. 

## To Reproduce

Open Reports page on mobile app

**Comment by amulware** [comment]
Looks like a simple fix - add some padding.

**Comment by dshr** [comment]
Also has been solved by @Odrakir's iPad fixes
