### ISSUE TITLE
Edit view resets billable flag on opening

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5697]
## 🐛 Bug Report
If I open a billable time entry in the edit view, it doesn't show the billable toggle enabled. Even worse, if I then save this TE, it will be made non-billable.

## Context
Build/Branch: 2.1.6
Phone OS: Android 8
Phone model: redmi 5a

## Expected behavior
The toggle button should have the correct state when the edit view is opened.

## To reproduce
- Have a billable time entry (stopped or running, doesn't matter)
- Tap to edit it
- Oh no, the toggle is off

## Suggestions
Populate UI correctly.

**Comment by kpv1993** [comment]
I checked this and I don't see any issue. The billable is in the correct state. Let me know if anyone else is also facing this issue. Otherwise we can close it.

**Comment by heytherewill** [comment]
The Switch in that view is black instead of blue, so maybe that should be fixed. 

The state, however, is indeed correct

**Comment by VeljkoTN** [comment]
A user reached out about this, linking the [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/23219593253) for reference.
