### ISSUE TITLE
Unify toolbars across the app

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5698]
## 🐛 Bug Report
In the wheel view, the save button in the toolbar is too close to the edge of the screen (or at least it's closer than the other various save buttons in the app).

![Screenshot_2019-08-02-11-19-44-442_com toggl giskard](https://user-images.githubusercontent.com/3987892/62364689-1ce41e80-b51a-11e9-84b7-ebace4b8cb8e.png)

## Context

Build/Branch: 2.1.6
Phone OS: Andriod 8
Phone model: redmi 5a

## Expected behavior
The toolbar layout should confirm to designs and be the same everywhere.

## To reproduce
Check the wheel view, compare to the save button in the edit/start views.

## Suggestions
Check designs. Also check if the title text in the same view is aligned correctly.

**Comment by daividssilverio** [comment]
🤔 The `EditDuration` is the only `Activity` that's using the system provided toolbar menus.
The other `Activities` are using a custom fake toolbar. 
I think the right thing to do is to update the other activities.

**Comment by amulware** [comment]
@maritoggl do you have a strong preference? My main concern is that they should all look the same.

**Comment by maritoggl** [comment]
I agree that all should look the same, what's happening under the hood is up to you - do what's most reasonable.

**Comment by dshr** [comment]
There are several other toolbars that need some attention, as flagged by @shantanuraj:
