### ISSUE TITLE
Transition to Androidx

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#5700]
## 🚧 Refactor Proposal

It is now possible to make the transition to AndroidX even in the Xamarin world [Introducing AndroidX for Xamarin](https://devblogs.microsoft.com/xamarin/androidx-for-xamarin/) so we should make the transition to be able to access the latest support libraries. 

## Dependencies

It involves a couple of changes best defined in the blog post mentioned above.

**Comment by daividssilverio** [comment]
I like this. Please mr. Architect (said @heytherewill), let's do this.

**Comment by heytherewill** [comment]
Did some investigation on this one. Apparently, it's literally just a matter of removing all of our AppCompat packages and adding the AndroidX ones, since we don't have any third party dependencies that use AppCompat. I'd like to see this included in 2.4, since it will touch a lot of files and it's better done sooner than later because of possible conflicts with projects.

**Comment by semanticer** [comment]
Cool, I will look into it later this week. Pazzo week might be a good time to do this since just some of us are touching the app.

**Comment by semanticer** [comment]
All the androidx packages are in preview3 version so maybe, it's not ready for primetime 😭

**Comment by semanticer** [comment]
I encountered a lot of issues with this, maybe @heytherewill can help me but maybe it is still too early to do this anyway and we should wait for the final release 😢

**Comment by semanticer** [comment]
And if Microsoft doesn't release the final version very soon we should remove this from the 2.4 release as well.

**Comment by semanticer** [comment]
I am moving this out of 2.4 since I don't believe Microsoft will release the final version soon enough.

**Comment by semanticer** [comment]
There is no progress with this on Microsoft's side. It looks like it's still preview02 after 3 months now. I don't know what to do, there are more and more things depending on this @heytherewill
