### ISSUE TITLE
Settings page is cut off

### ISSUE THREAD

**Issue by lise-toggl** [toggl/mobileapp#5714]
## 🐛 Bug Report
The settings page is cut off at the sides for this [user](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/23105805184):
![image](https://user-images.githubusercontent.com/50156618/62511821-cac43580-b858-11e9-98cd-f77e17e9f8a0.png)

Build/Branch:
Phone OS: iOS 12.3.1
Phone model: iPhone 7

## Expected behavior
The page should not be cut off

## To reproduce
Could not reproduce with a long workspace name on iPhone SE so probably not that 🤷‍♀ 

## Suggestions
Nada 👶

**Comment by Odrakir** [comment]
Might be the same bug as in #5803

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23800405210)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23841843724)
