### ISSUE TITLE
Can't go to settings a second time

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5715]
## 🐛 Bug Report
In iOS you can't go to settings a second time after you exited tapping the timeline button in the tab bar.

## Context
Build/Branch: develop and AppStore version
Phone OS: 12.4
Phone model: Xs

## To reproduce
- Open the app, go to settings
- Tap on the timeline button down on the tab bar to go back to the timeline
- Try to open settings again. Does it work?

**Comment by arturs105** [comment]
This has been merged into `develop` now.
