### ISSUE TITLE
Fix long press on the play button in the main log

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5719]
Currently the long press only works when the finger is lifted up - you press and hold the button, but the start time entry view only opens after you lift the finger up. It should open when a certain amount of time has passed after the initial touch.

**Comment by amulware** [comment]
Why is one preferable over the other? Should we maybe work on adding an animation or something instead to make it clearer that something else happens/will happen?

**Comment by amulware** [comment]
(also @maritoggl)

**Comment by arturs105** [comment]
I don't think any (well polished) app uses a long press similar to what we have on the play button now. This is what went through my head, when i tried it:
1. Let's try long pressing on the play button to test manual mode
2. _Tapping and holding_
3. ???
4.  _Still holding_
4. ???
4. Huh... Nothing's happening - long press must be broken
5. _Releases finger_
6. _The view opens_
7. ???
8. [What?](https://i.kym-cdn.com/photos/images/original/000/746/236/be4.36628)

Another argument: try long pressing on any app on iOS home screen to enter the rearrange/uninstall mode - you get to that before lifting the finger up, so that's a good indicator on how long press gesture should behave on iOS.

Another another argument: there should be some feedback that the long press is working. Executing the action for the long press before the finger is lifted is a good feedback to the user to indicate that the long press gesture worked. Otherwise who knows how long the long press needs to be. Adding an animation to the long press would just be icing on the cake (which is definitely good to have).

**Comment by maritoggl** [comment]
Arturs' points sound valid. Even us ourselves have the same behavior in the calendar view for instance when creating new time entries from here. 
With that said, probably makes sense to look into whether or not this is a standard for Android as well.

**Comment by amulware** [comment]
Let's do it on iOS. I'll create an issue for checking Android as well.

**Comment by amulware** [comment]
Actually I won't, it already works that way on Android and there is even haptic feedback - we should have that on iOS as well, please do that with this issue.
