### ISSUE TITLE
Confirm running time entry conflict resolution

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5759]
There's new documentation on how exactly running time entry resolution should work: https://www.notion.so/Running-Time-Entry-Conflict-Resolution-248add2d519b452c9d27905a84304bf7

Please:
- [x] Read the above carefully
- [x] Compare it to our implementation **carefully and in detail**
- [x] Detail below how we differ from the specs
- [x] Create and link one or multiple issues to make the necessary changes with clear and detailed descriptions
- [x] Take into account https://github.com/toggl/mobileapp/issues/2454 (information might be outdated, if so, close that issue, or maybe we actually have to do something, if so, please handle as mentioned above)

**Comment by juanlaube** [comment]
The proposed algorithm is:

1. Determine the Time Entry with the largest `at` value and leave it running.
2. For all other Time Entries set their `stop` value to the `start` value of any Time Entry that comes after (larger `start` value) and which is at least as "new" (`next.at ≥ te.at`) or `now` if none found.

We don't follow the step 2 completely. We do set the stop time of the time entry in conflict to the start time of the next time entry, but the part that differs from our implementation is `and which is at least as "new" (`next.at ≥ te.at`)`.

There are 5 examples in the document, with our current implementation `With overlapping TEs - server newer 2` has the same result as `With overlapping TEs - server newer 2`.

**Comment by amulware** [comment]
Actually, consider creating a couple of sync tests for this as well, please. :)

**Comment by juanlaube** [comment]
Created issue #5771 but put it on hold until we have confirmation all clients should implement that.

**Comment by amulware** [comment]
Follow up issue is good.
