### ISSUE TITLE
Edit dialog - description covered by keyboard

### ISSUE THREAD

**Issue by lise-toggl** [toggl/mobileapp#5776]
## 🐛 Bug Report
On some iOS devices, editing the description of an existing entry makes the edit dialog move downwards, hiding the description behind the keyboard. See first 10s of this video by @nidarasheed:

https://toggl.slack.com/files/UHVETTGTW/FMG7FM3B2/file_from_ios.mp4

## Context

Build/Branch: Daneel 2.2.1
Phone OS: Apple
Phone model: iPhone 7, 8

## Expected behavior
The description should not disappear behind the keyboard

## To reproduce
See video.
Reported on iPhone 7 and 8.
Not an issue on iPhone SE.

## Suggestions
[User reports](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/23284784420) this only started happening with 2.2.1

**Comment by VeljkoTN** [comment]
another user reached out about this. Linking the [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/23324838784) for reference.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2833855/conversations/23353496006)

**Comment by VeljkoTN** [comment]
another [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23582924371)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23699380751)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23680077735)
