### ISSUE TITLE
Select project view recycler view is updating more items than it should when opening tasks

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#5779]
## 🐛 Bug Report
When you go to the Select project view (from edit view) and expand tasks, the recycler view updates like the adapter is adding more items than the expansion is causing.

## Context
Build/Branch: Develop at time of creation of this issue; 2.2.1
Phone OS: Android
Phone model: Samsung Note 9

## Expected behavior
Only related items should be updating when expanding tasks.

## To reproduce
1. Make sure you have a lot of projects/workspaces
2. Go to Edit Time Entry View
3. Go to the Select Project View
4. Scroll down a bit
5. Select a project with tasks to expand it
6. There you go.

## Suggestions
It looks like the recycler view's adapter update logic in the select project view is flawed.

**Comment by daividssilverio** [comment]
Gif for reference: 
<img src="https://user-images.githubusercontent.com/2173493/63288828-a8d0a700-c28b-11e9-9e64-27f44417b458.gif" width=240 />

**Comment by semanticer** [comment]
I don't know ho to make the list expandable. I have 4 workspaces and multiple projects and task but I never see the expandable arrows on the right hand side of row items. What am I doing wrong @daividssilverio ?

![workspaces](https://user-images.githubusercontent.com/535613/63860276-1c1f9a80-c9a9-11e9-97c4-7168827ca886.png)

**Comment by semanticer** [comment]
Wow, the logic in `BaseSectionedRecyclerAdapter` is super complicated for reasons so far unknown to me 🥺
