### ISSUE TITLE
Tag text positioned off

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#5790]
## 🐛 Bug Report
On Android in the Edit TE view that tag TextView's text is positioned a bit higher than it should be.

![Screenshot_20190820-094743](https://user-images.githubusercontent.com/6031512/63424910-16a9d980-c418-11e9-91bf-eecb87b6e6fa.png)

## Context
Build/Branch: 2.2.1
Phone OS: n/a
Phone model: n/a

## Expected behavior
Should be vertically centered.

**Comment by semanticer** [comment]
Fun fact, it's actually changing the vertical position on the fly. When you are in the middle of writing "#newtag" it's actually centered correctly but as soon as you complete adding new tag it moves up again.

### Context
Build/Branch: develop
Phone OS: Android 10
Phone model: Pixel 1

**Comment by semanticer** [comment]
What about adding this small glitch to **Android 2.4** release @amulware ?

**Comment by semanticer** [comment]
I did some research, and the problem is that TokenSpan.Draw method is called with different **bottom** parameter value depending on the rest of the EditText's content.
