### ISSUE TITLE
Add long press hint on iOS

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5796]
The start time entry button on the main view has two modes: normal mode as defined by the user preferences when tapping and alternate mode when long pressing.

The problem is this feature is not really easy to find unless you know it's there. We we'll probably need to add some kind of animation to make it clear to the user.

There's a current discussion here: https://toggl.slack.com/archives/CMB9FDE5D/p1565778022020100

**Comment by amulware** [comment]
We should take inspiration by how iOS 13 now handles long-pressing various things, with the death of replacement of force touch by haptic touch. Maybe even just growing/shrinking the start button a little, similar to long-pressing an icon on the home screen would work?

**Comment by simonrozsival** [comment]
I like the idea with the animation + it should have haptic feedback (just like the home screen icons).
