### ISSUE TITLE
Calendar settings go over the sides of the screen

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5803]
## 🐛 Bug Report
This only happens in iOS 13 beta, apparently, but I don't think it'll work in the final version. When accessing the calendar settings from the app settings (via the main view) that table view goes over the sides of the screen and it's unusable.

I'm attaching a screenshot.

![image](https://user-images.githubusercontent.com/724743/63581186-bc835280-c596-11e9-991a-bc086713ab9b.png)

## Context
Build/Branch: This happens in the App Store version (can't test on develop because VS doesn't want to)
Phone OS: iOS 13 (beta 8)
Phone model: iPhone Xs

## To reproduce
Open the app, got to the main timeline -> settings -> Calendar settings
(for the calendar settings to show you have to enabled the calendar integration first)

## Suggestions
This is probably related to how we layout those table views for them to show properly in the iPad.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23800405210)

**Comment by zdericnina** [comment]
[user report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/23837006811)
