### ISSUE TITLE
Improve tag selection views and make them consistent

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#5824]
**Context: this issue started in a Slack thread** https://toggl.slack.com/archives/C02APMYTM/p1566990154012100

### 1) Launched from TE edit screen

![selectedtags](https://user-images.githubusercontent.com/535613/63886540-ff9c5600-c9da-11e9-9d9f-ef36d870ad81.png)

**Explanation of UX:** 
This is similar to our iOS solution, the user is simply selecting from the list and writing to filter the list of options. The tags are simply ✅when taped. 

**Problems:** 
- Hard to quickly scan the whole list to figure out what is already selected
- User needs to find again selected tag if he wants to unselect it

### 2) As part of creating new TE

![toggltagfail](https://user-images.githubusercontent.com/535613/63866113-0616d780-c9b3-11e9-9fa4-3be32b73183e.png)

**Explanation of UX:** 
User searches tags and receives suggestions. After taping on particular suggestion, the tag is moved to search box as a "chip" view. Suggestions suggest even the tags which are already selected. User can unselect any tag by backspacing.

**Problems:**
- Tag unselection is easier than in 1 but still hard if you need to remove something else than the last added tag
- Current "chips" are ugly 🌧️
- Suggesting already selected tags is just confusing 

**Problems with both:**
- They are completely different = confusing and the user cannot leverage knowledge from one in working with the other.
- Both solutions are not standard Android or Material practices so the user cannot leverage experience from other apps.

## Possible New Solution
I am for improving solution number 2 and using it for both selection flows. 

1. We should be using standard material way of displaying input chips https://material.io/components/chips/#input-chips with remove icon option to easily unselect any tag. 
2. Suggestions should display only unselected tags

**Comment by AlicjaSuska** [comment]
Agree with @semanticer - let's improve second solution and use it in both places. Let me put together a quick draft of how it can look like and we can start from there :) Thank you for pointing this inconsistency!

**Comment by semanticer** [comment]
@AlicjaSuska Any update on this one or should we just try to implement this as good as we can and discuss potential improvements with you afterward?

**Comment by AlicjaSuska** [comment]
@semanticer I think I will manage to get to this issue this week. Are you able to wait couple more days?

**Comment by pdrj** [comment]
I'm already working on it, but there are many more issues in 2.5, so it should be OK to leave this one for a day or two and wait for your input 🙂. Do you think you'll manage to get us some designs on Thursday @AlicjaSuska?

**Comment by AlicjaSuska** [comment]
I'm planning to start tomorrow. They should be ready, I'll keep you posted @pdrj

**Comment by AlicjaSuska** [comment]
![Android-tags-display](https://user-images.githubusercontent.com/20326070/66576586-48b5fd00-eb78-11e9-859e-db4fc423b08c.png)
![Android-Tags-multpile](https://user-images.githubusercontent.com/20326070/66576587-494e9380-eb78-11e9-99dc-82252fabe6fe.png)
![Android-Tags-one row](https://user-images.githubusercontent.com/20326070/66576588-494e9380-eb78-11e9-8c66-04392e728d18.png)

Hi! I've prepared new design for tags. As @semanticer proposed - I went with the 2nd approach. Tags look a little different when adding them (bigger, with X, in rows) and when displaying (smaller, scrollable). Please, let me know what do you think about it.

There is one important change to the flow I would like to propose. After choosing tags and clicking 'done' currently we close the whole edit popup. I think, we should just close tags screen and get user back to edit TE popup.

@pdrj please have a look as well.

@maritoggl @amulware I think, we should also improve this for iOS :)

**Comment by AlicjaSuska** [comment]
Also, we should keep # in the tags to make it consistent with adding flow. Another small change is to not enable deleting it when adding tags. IT should stay on the screen, even when user deletes characters. Otherwise it may be hard to come back to searching...

**Comment by AlicjaSuska** [comment]
Zeplin: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/dashboard?seid=5d9f3c8971f60b23d332ace5

**Comment by pdrj** [comment]
Thanks @AlicjaSuska, looks great. One question that comes to mind after taking a look - how should we deal with different entities than tags in the start time entry view? The list (the one on the top of the screen, where you type) can also have a project 'chip' or just text.

Should we just make the project chip look similar to the tag one, but with the background color corresponding to the project's color and the project name prepended with '@', and have a blank chip for regular text?

**Comment by pdrj** [comment]
@maritoggl, just out of curiosity, is the decision of not allowing the #/@ characters on chips due to them not being visually pleasing, or are there other reasons?

@AlicjaSuska in this case, can we please have some icons prepared?

**Comment by AlicjaSuska** [comment]
For project and text I would stay with the solution we have currently - no chip. It makes sense to use chips for multiple items. As user can choose only one project, I would unify visuals between screens and go with the solution used for editing TE - colorful text.

This:

![Screenshot_20191014-094233](https://user-images.githubusercontent.com/20326070/66735654-44832b80-ee67-11e9-938a-1ef24c443c00.jpg)

Instead of this (currently used when adding new TE):
![Screenshot_20191014-094308](https://user-images.githubusercontent.com/20326070/66735666-4cdb6680-ee67-11e9-8bad-98db905562db.jpg)

@maritoggl if # is impossible to add, I would go with simple chips in this case, with no character / icon. Tag icons would be excessive. If we use chips only for tags there's no need to differenciate them more with icon. Could you please explain why # is a no go?

**Comment by pdrj** [comment]
I see, just to be clear, you're proposing to remove the current start TE screen and adapt the edit one to serve this purpose? That is, remove start/end times, duration and the 'delete' button from it? 

How should the list with tag/project suggestions be anchored in this case? To the edit text at the top - then when you select an item, it'll be added to the correct row (that row will be covered with the suggestions list however, so user might get confused)? Or should we have separate lists that will open once you select a row? Ie. if you click on the tags row, you only get tag suggestions and the list will be anchored to that row.

Any thoughts on that @maritoggl?

**Comment by AlicjaSuska** [comment]
@pdrj sorry for the confusion, I was referring only to how we show Project in both cases (colored text, no colorful backgroud)

**Comment by pdrj** [comment]
Oh I see 😄 So chip for tags, just colored text for the project and regular text for... text, right?

**Comment by AlicjaSuska** [comment]
Unifying edit and new TE view is probably totally separate matter. In my opinion, should be done. The question is if we want to get to it now. Seems like a bigger change that needs more analysis. @maritoggl

**Comment by pdrj** [comment]
@maritoggl please let me know if you're good with the solution proposed here.

**Comment by maritoggl** [comment]
Having a # is visually not pleasing plus it is not consistent with our other apps. The text on the chip should reflect the actual name of the tag and # is simply not part of it - it's just a shortcut that's used. Also, some users actually have tags that have # as the first character - in such case, they'd see super-weird tags that would be like ##text.

Unifying the edit and new time entry views is indeed a bit of a bigger change, which we should take up in near future, but I'm not sure how this relates to the discussion here.

**Comment by pdrj** [comment]
@AlicjaSuska in the start TE view, how are we going to deal with deletion of the project item or the regular text item if we don't put them in a chip? Tags will be deleted by clicking the 'x' on the chip. Having the other entities being deleted by 'backspace' is quite confusing I think. Wouldn't it be better to put project/text in their own chips as well and distinguish them with an icon, as @maritoggl suggested?

**Comment by maritoggl** [comment]
Regarding the icon, didn't say I prefer that approach, but that I'd be willing to consider it if a case is made :) I actually prefer iconless option.

**Comment by pdrj** [comment]
Thanks for clarification.

TBH, I feel that the start TE view with addition of chips is going to be a bit of a mess. You'll have 3 types of entities in one 'list' (the edit text at the top), unless we change the design. Don't you think it'll be better to just go with the unification of start/edit view and not waste time on this approach now and then on the unification too?

**Comment by AlicjaSuska** [comment]
When it comes to tags with no # - no problem. I understand your concerns Mari :) I'll remove them

Question asked by @pdrj - I also think it would be beneficial to work on unification of start/edit views first instead of working on different designs for different cases. It will probably be the separate project though and the question is when we can get to it. @maritoggl how do you see it?

**Comment by daividssilverio** [comment]
Removed from 2.7 and 2.8 as this is most likely part of project on its own (unifying start/edit views) and just using chips doesn't seem to be a good idea based on comments here in internally on slack.
