### ISSUE TITLE
Fix nightly builds

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#5826]
Both the nightly AdHoc and AppStore build are currently broken (see internal reports).

They need to be fixed.

**Comment by dshr** [comment]
The AppStore build is broken due to a `#if DEBUG` mishap which was fixed during the release process of 2.3, so will be fixed when #5852 is merged. As for the AdHoc build — looks like the linker is still set to Link All for that flow. Will post a PR to fix that too.
