### ISSUE TITLE
Migrate to Material Components & Material theme

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#5829]
## 🚧 Refactor Proposal

We need to migrate to Material components if we want to take advantage of the latest and greatest theming options and predefined components. 

More: https://material.io/develop/android/docs/getting-started/

## Technical aspects

We can either decide to go slowly and use one of the `.Bridge ` Themes which shouldn't destroy our current theme but gives us the option to use Material Components or we can go all the way to Material Theme and carefully fix possible issues throughout the application.

**Comment by semanticer** [comment]
Turns out this issue is related to #5700 and they should be dealt with together.

**Comment by semanticer** [comment]
This doesn't compile if we upgrade Androidx and material libs to the latest version preview03: 

  Xamarin.Android.Common.targets(1824, 2): [XA2002] Can not resolve reference: `Xamarin.AndroidX.AppCompat.Resources`, referenced by `Xamarin.Google.Android.Material`. Please add a NuGet package or assembly reference for `Xamarin.AndroidX.AppCompat.Resources`, or remove the reference to `Xamarin.Google.Android.Material`.

You can try this yourself on `tomas/material-theme` branch 

or

If we stick with preview02 it looks like only some of the material themes are available. `Theme.MaterialComponents.NoActionBar` works well but all `DayNight` variations like `Theme.MaterialComponents.DayNight.NoActionBar` does not work. 

Branch `tomas/material-theme-preview02`

**Comment by heytherewill** [comment]
This is blocked by https://github.com/xamarin/AndroidSupportComponents/issues/226

**Comment by heytherewill** [comment]
Issue to track the block has changed to https://github.com/xamarin/AndroidX/issues/12

**Comment by daividssilverio** [comment]
@semanticer any idea if we can use some other alternative theme available in the current libraries? Or maybe if we are able to bind the themes manually somehow?

**Comment by semanticer** [comment]
I'm not sure, @heytherewill was the one implementing the dark mode. I can certainly look into it but I'm a little afraid the solution will be too ugly and not worth it.
