### ISSUE TITLE
The calendar view is ignores 24-hour clock preference

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#5833]
## 🐛 Bug Report

When you change your setting to "Use 24-hour clock" the first column of calendar view is still in pm/am format.

## Context

Build/Branch: develop
Phone OS: Android 10 beta
Phone model: Pixel 1

## To reproduce

1. Change settings to enable "Use 24-hour clock"
2. Check calendar view and see good old pm/am

**Comment by daividssilverio** [comment]
Closed by #6526
