### ISSUE TITLE
Cursor jumps to the end when inserting emoji

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#5839]
## 🐛 Bug Report
When inserting an emoji in the description field in the edit time entry view, the cursor jumps to the end.
For some reason it only happens with emojis, works fine for regular characters.
Deleting the emoji also works fine, i.e: no cursor jumps.

## Context

Build/Branch: iOS 2.2.1, AppStore build
Phone OS: iPhone
Phone model: any

## Expected behavior
The cursor shouldn't jump.

## To reproduce
Insert an emoji at the beginning or in the middle of the description.

**Comment by simonrozsival** [comment]
The cursor jumps even for regular characters (iOS 13, app v2.7)

**Comment by simonrozsival** [comment]
This issue is caused by #5669. I'll have to figure out how to keep the RTL fix while fixing the bug with jumping cursor.
