### ISSUE TITLE
Calendar: Improve visibility of calendar events from time entries

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5858]
Calendar events will have a line at the bottom and the small calendar image next to their description.

`Text`,`small calendar icon` and `line` should have the color of the calendar the event is from, the background should be same color but with opacity at 24%

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8a175b0830e2161df7fcee

**Comment by daividssilverio** [comment]
Closed by #6298
