### ISSUE TITLE
Calendar: Add week line custom controller

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5866]
Depends on #5865 

Add weekly date picker above the calendar view to show the days of the week (the controller will behave similarly to the iOS day view in the default Calendar app).

- [x] Create UI for this component
- [x] Modify already available VM logic if needed
- [x] Today's date should be marked with different colour
- [x] Selected date is marked with a circle (check designs for color when circle is on current day and on other days)
- [x] Future days and unavailable past days are disabled/greyed out
- [x] User can move back up to 2 weeks
- [x] Scrolling left-right in the weekly date picker area changes the whole week (paged scrolling). Days always stay in the same order and the same weekday should be selected. For ex. user sees Wed, Sep 12 → scrolls left → sees Wed, Sep 5
- [x] make sure changes in the weekly date picker are reflected in the calendar below
- [x] swiping in the calendar should update the selected date in the  weekly date picker view
- [x] beginning of the week should be based on the user settings

Feel free to copy this list in the PR so that the reviewer knows what to check

Designs: 
https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8a175b0830e2161df7fcee
https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8a280265a7831666fad463

**Comment by sofokli1** [comment]
@daividssilverio can you also check the completed stuff here

**Comment by daividssilverio** [comment]
Closed by #6139
