### ISSUE TITLE
Calendar: Add manual time entry creation

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5868]
Depends on #5867 

Manual TEs
- [x] Use long press to create new Entry with handlers and contextual menu appear.
- [x] New entries should snap to quarter hour and other calendar events start and end times
- [x] Should have a default duration of 30 min
- [x] If created in the gap between 2 TEs that is 2 hours or less, it should fill the whole gap by default

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8a2802a3c39b61c2643a26

**Comment by daividssilverio** [comment]
Closed by #6300
