### ISSUE TITLE
CalendarCollectionViewSource.updateCalendarItem index out of range

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5869]
## 💥 Crash Report
🤷‍♂ Check App Center for all the info on the crash.

### 👥 Impact
This crash has occurred 136 times to 54 users in the last 30 days, which translates to 0.1% affected users

### 🔗 Context
We've had index out of range crashes in `CalendarCollectionViewSource.updateCalendarItem` (#4886) and seems like it was fixed, however there are new crashes in this method in 2.2.1, so we need to do something about this.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/775237137u/overview

### 📝  Exception & Stack Trace
`SIGABRT: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
```cs
List`1[T].get_Item (System.Int32 index) in <939d99b14d934342858948926287beba#01b7521b705f92edab0b11232d0eaaea>:0
CalendarCollectionViewSource.updateCalendarItem (Foundation.NSIndexPath indexPath, System.DateTimeOffset startTime, System.Nullable`1[T] duration)
CalendarCollectionViewSource.UpdateItemView (System.DateTimeOffset startTime, System.TimeSpan duration)
CalendarCollectionViewCreateFromSpanHelper.longPressChanged (CoreGraphics.CGPoint point)
CalendarCollectionViewCreateFromSpanHelper.onLongPress (UIKit.UILongPressGestureRecognizer gesture)
UILongPressGestureRecognizer+Callback.Activated (UIKit.UILongPressGestureRecognizer sender)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by amulware** [comment]
I recommend coordinating with the calendar improv project team to prevent unnecessary merge conflicts.

**Comment by simonrozsival** [comment]
This bug was present even in the latest release (https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/2808190499u/overview?q=CalendarCollectionViewSource&searchType=unhandlederror) but it might go away in 2.7 with the release of calendar improvements, as @amulware mentioned.

**Comment by simonrozsival** [comment]
There is one very similar issue in 2.7 even after the calendar update, although the stack trace is different: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3609072023u/overview

**Comment by arturs105** [comment]
Yeah, this exact crash hasn't happened in 2.7 at all, so i'm considering closing this issue, but then again 2.7 hasn't been out for long enough to be certain, so let's just go to the Winchester, have a nice cold pint and wait for al of this to blow over 🍻.

**Comment by simonrozsival** [comment]
The current most common crash in 2.7 seems to be related: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/137415887u/overview

```
CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath (Foundation.NSIndexPath indexPath)
SIGABRT: Object reference not set to an instance of an object
```

For some reason sometimes the `indexPath` is outside of the valid range, which was the problem in the original issue. This could be maybe something related to deleting things?
