### ISSUE TITLE
Calendar: Add contextual menu

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5871]
VM work should be done in this issue

For all contextual menus, if the user taps outside the the contextual menu should shake (this is to show the user that it needs to make a decision in order to dismiss it). There is one exception to the above and that is for the situations where the user drags a TE start, stop or the whole thing (only for the one that is in focus in the contextual menu).

Ideally we want the start and end time that is shown in the contextual menus (where it applies) to update when the user drags the handles of the TE or the whole TE. If this is hard to manage please let me know so that we can act accordingly.

### Newly created TE contextual menu (triggered when creating a TE with long press)
- [x] Discard (deletes the TE)
- [x] Edit (opens edit view)
- [x] Save

- [x] New `CalendarNewTimeEntryCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `Discard`
    - `Edit`
    - `Save`

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8a2802a3c39b61c2643a26

### Existing TE contextual menu (triggered when tapping on an existing TE)
- [x] Delete
- [x] Edit (open edit view)
- [x] Save (to save changes when dragging the handles or the whole view)
- [x] Continue (starts a new TE with same metadata project, tags, etc at current time. Same as in main log)

- [x] New `CalendarExistingTimeEntryCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `Delete`
    - `Edit`
    - `Save`
    - `Continue`

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8bb8fbf389236569b71bc2

### Running TE contextual menu (triggered when tapping on a running TE)
- [x] Discard (deletes the TE)
- [x] Edit (opens the running TE edit view)
- [x] Save (to save changes when dragging the handle on top)
- [x] Stop (stops the running TE)

- [x] New `CalendarRunningTimeEntryCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `Discard`
    - `Edit`
    - `Stop`
    - `Save`

- [x] New `CalendarTimeEntryCreated` event with 3 parameters (event may be exist already but may be missing the below type)
    - `Type` string with possible values from the following list
        - `CopyFromCalendarEvent` (triggered when TE is created from contextual menu (same name option) of calendar event is tapped)
    - `DaysSinceToday` int. Difference in days between the start date of the TE and today. If negative it is in the past, if positive it is in the future (with our  implementation all the values should be negative since we do not allow swiping to future dates, for now)
    - `DayOdTheWeek` string. The name of the day of the week

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8bb8fbbbf24c0250f05d16

### Calendar event contextual menu (triggered when tapping on a calendar event)
- [x] Copy as Time Entry (creates a TE with start and end set and the description of the calendar event)
- [x] Start (Creates a Running TE that starts at current time and has the same description as the calendar event)

- [x] New `CalendarEventCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `CopyAsTimeEntry`
    - `Start`

- [x] New `CalendarTimeEntryCreated` event with 3 parameters (Calendar event may be there already but not for the below type)
    - `Type` string with possible values from the following list
        - `StartFromCalednarEvent` (triggered when TE is created from contextual menu (same name option) of calendar event is tapped)
    - `DaysSinceToday` int. Difference in days between the start date of the TE and today. If negative it is in the past, if positive it is in the future (with our  implementation all the values should be negative since we do not allow swiping to future dates, for now)
    - `DayOdTheWeek` string. The name of the day of the week

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8bb8fa41d2b91698dc3778

**Comment by daividssilverio** [comment]
Hey @sofokli1 
>Running TE contextual menu (triggered when tapping on a running TE)
...
> New CalendarTimeEntryCreated event with 3 parameters (event may be exist already but may be missing the below type)

> Type string with possible values from the following list
CopyFromCalendarEvent (triggered when TE is created from contextual menu (same name option) of calendar event is tapped)
DaysSinceToday int. Difference in days between the start date of the TE and today. If negative it is in the past, if positive it is in the future (with our implementation all the values should be negative since we do not allow swiping to future dates, for now)
DayOdTheWeek string. The name of the day of the week

This event didn't make sense to me in the `Running TE contextual menu`, so I've added it to the `Calendar event contextual menu ` only, because it seems to belong there. I've requested your review about this in #6018 just to make sure. Please leave a comment if the implementation should be changed.

**Comment by sofokli1** [comment]
@daividssilverio you are right, I updated the description above

**Comment by sofokli1** [comment]
@daividssilverio please check what is completed in here

**Comment by daividssilverio** [comment]
Closed by #6099
