### ISSUE TITLE
AnimationExtension.Animate Collection was mutated while being enumerated

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5872]
## 💥 Crash Report
So there seems to be a bunch of these crashes in iOS 2.2.1 in App Center (see links below), not sure if they are exactly the same crash, but they do look very similar

### 👥 Impact
Hard to say, since there are a bunch of instances in App Center. The greatest one has 170 occurrences to 159 users in the last 30 days.

### 🔗 Context
There were similar errors a couple of versions back: #4960.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3380399390u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/1296809681u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/1017829453u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/390901223u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/2898663805u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/565874181u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/684477729u/overview
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/1062927025u/overview

### 📝  Exception & Stack Trace
`SIGABRT: Objective-C exception thrown. Name: NSGenericException Reason: *** Collection <__NSArrayM: 0x283091530> was mutated while being enumerated`
```cs
Runtime.ThrowNSException (System.IntPtr ns_exception)
Runtime.throw_ns_exception (System.IntPtr exc)
(wrapper native-to-managed) ObjCRuntime.Runtime.throw_ns_exception(intptr)
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr)
UIView.LayoutIfNeeded ()
NSConstraintExtensions+<>c__DisplayClass2_0.<ConstantAnimated>b__1 ()
Trampolines+SDAction.Invoke (System.IntPtr block)
AnimationExtensions.Animate (System.Double duration, System.nfloat delay, Toggl.Core.UI.Helper.Animation+CubicBezierCurve curve, System.Action changes, System.Action completion, System.Nullable`1[T] cancellationToken)
AnimationExtensions.Animate (System.Double duration, Toggl.Core.UI.Helper.Animation+CubicBezierCurve curve, System.Action changes, System.Action completion, System.Nullable`1[T] cancellationToken)
NSConstraintExtensions+<>c__DisplayClass2_0.<ConstantAnimated>b__0 (System.nfloat constant)
AnonymousSafeObserver`1[T].OnNext (T value) in <12cae72f24674302a4c964a96bed8f31#01b7521b705f92edab0b11232d0eaaea>:0
NSConstraintExtensions+<>c__DisplayClass2_0.<ConstantAnimated>b__1 ()
Trampolines+SDAction.Invoke (System.IntPtr block)
AnimationExtensions.Animate (System.Double duration, System.nfloat delay, Toggl.Core.UI.Helper.Animation+CubicBezierCurve curve, System.Action changes, System.Action completion, System.Nullable`1[T] cancellationToken)
AnimationExtensions.Animate (System.Double duration, Toggl.Core.UI.Helper.Animation+CubicBezierCurve curve, System.Action changes, System.Action completion, System.Nullable`1[T] cancellationToken)
NSConstraintExtensions+<>c__DisplayClass2_0.<ConstantAnimated>b__0 (System.nfloat constant)
AnonymousSafeObserver`1[T].OnNext (T value) in <12cae72f24674302a4c964a96bed8f31#01b7521b705f92edab0b11232d0eaaea>:0
AnimationExtensions.Animate (System.Double duration, System.nfloat delay, Toggl.Core.UI.Helper.Animation+CubicBezierCurve curve, System.Action changes, System.Action completion, System.Nullable`1[T] cancellationToken)
AnimationExtensions.Animate (System.Double duration, Toggl.Core.UI.Helper.Animation+CubicBezierCurve curve, System.Action changes, System.Action completion, System.Nullable`1[T] cancellationToken)
NSConstraintExtensions+<>c__DisplayClass2_0.<ConstantAnimated>b__0 (System.nfloat constant)
AnonymousSafeObserver`1[T].OnNext (T value) in <12cae72f24674302a4c964a96bed8f31#01b7521b705f92edab0b11232d0eaaea>:0
```

**Comment by simonrozsival** [comment]
The bug is gone, there hasn't been a single report in 2.3 and newer. The extension method `ConstantAnimated` is called only from the `ReportsCalendarViewController`. The `ReportsCalendarViewSource` uses an `ImmutableList` instead of a classic `List` since 2.3 (https://github.com/toggl/mobileapp/pull/5732) and I suppose this prevents the `Collection was mutated while being enumerated` problem.

**Comment by Odrakir** [comment]
Makes sense 👍
