### ISSUE TITLE
Figure out a way of uploading bundles to Bitrise

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5877]
#5832 introduces the possibility of building bundles, but the release step in Bitrise fails because it expects apks. We need to figure this out

**Comment by semanticer** [comment]
Well, I've added some emoji reaction to https://github.com/bitrise-steplib/steps-xamarin-archive/issues/35 but there is no other development there. Do you think it's time to move this to 2.5 @heytherewill ?

**Comment by heytherewill** [comment]
Yeah, moving to 2.5 it is

**Comment by amulware** [comment]
How much effort would it be for us to PR into bitrise to fix it for them? If it's not much work, we could 'just' do it ourselves?

**Comment by kornelijepetak** [comment]
The referenced issue does not show any progress. Moving it to the next release, or you have some info about this @heytherewill ?

**Comment by amulware** [comment]
My question above has not been answered. Please do. And also answer the question whether it's worth doing so.

**Comment by heytherewill** [comment]
How much effort? Dunno, we'd need to take some time to investigate. @daividssilverio might be better suited to answer this question
Is it worth? Definitely. We are getting warnings whenever we ship binaries. It's already past time we switched to using bundles

**Comment by heytherewill** [comment]
@kornelijepetak I think you should move it to, at least, 2.7

**Comment by daividssilverio** [comment]
Removed the `on-hold` label because bitrise might take some time to fix it and we want it.

**Comment by daividssilverio** [comment]
@heytherewill , are you still gonna do it? I can't look into this until next week.

**Comment by heytherewill** [comment]
I can probs take a look at it 

_Puts Go hat on_

**Comment by heytherewill** [comment]
https://github.com/bitrise-io/go-xamarin/pull/49
https://github.com/bitrise-steplib/steps-xamarin-archive/pull/38

Once these are merged we can update the step and close this issue :)

@daividsilverio When the release deadline comes closer, feel free to move this issue to the next release if the PRs are not merged yet

**Comment by heytherewill** [comment]
@daividssilverio and I got this working and managed to upload an aab to bitrise!!!! 
Since we don't know how long it's gonna take for the bitrise team to fix thing, we will create a working step inside the toggl company so we can use it while the PR sits there waiting to be merged :)

**Comment by heytherewill** [comment]
Moving this one to 2.9

**Comment by pdrj** [comment]
Moving this to 2.10 - after fixing some other issues with release build for 2.9 (#6909), [the workflow failed at the upload step](https://app.bitrise.io/build/d8d6037159d1efd5#?tab=log) and there was no time to investigate further.

**Comment by heytherewill** [comment]
This is closed by #5832. I will create a follow-up issue for us to monitor https://github.com/bitrise-steplib/steps-xamarin-archive/pull/38 and change to the official step once bitrise merges it :)
