### ISSUE TITLE
Polish and ship dark mode

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5878]
We need to figure out what still needs to be done for Dark Mode (#5811) and do it so we can include it into the next release!

**Comment by semanticer** [comment]
@heytherewill We still need to fix how we communicate elevation in dark mode. You can read about google's recommendations here https://material.io/design/color/dark-theme.html#properties and more about the implementation in section Elevation Overlays here https://material.io/develop/android/theming/dark/ but I don't know if we can take advantage of that surface magic without switching to material design library. 

Having said that, the only place where I see this as a problem is the bottom tab bar and current running TE view. They both blend into the rest of the content and that's not ideal.

**Comment by AlicjaSuska** [comment]
Hi! In Zeplin / design files there are no dark mode designs ready to link. If some design work is needed it has to be planned as a project for design team. @maritoggl that would be great if you could see this thread and please, let me know if you already have schedule in mind for this project:) Thank you!
