### ISSUE TITLE
There is no space between Default and Workspace on settings screen

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#5884]
Well, just check the settings screen.

![image](https://user-images.githubusercontent.com/7033216/64769859-5615a280-d54c-11e9-9548-cfa38eb8e54e.png)

**Comment by maritoggl** [comment]
Related: there's also no - in Email currently. I'd change that to E-mail instead.

**Comment by kornelijepetak** [comment]
In an internal discussion with @maritoggl, it was decided that we will continue to write the `email` without a hyphen. 

Some reasoning behind the decision (in and out of discussion):

1. We are already doing so on may places
2. In 2019, this form is used more than the `e-mail` version and is also included as a regular valid word in Oxford's and Cambridge's dictionaries of the English language, with `e-mail` stated as a variant.
3. Virtually every other big player (Apple, Google, Microsoft, Amazon, Facebook, _insert your favorite company here_) is using `email` instead of `e-mail`, even Clo... 🤦‍♂
