### ISSUE TITLE
 New Language Request - Japanese, ja-JP

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#5904]
**Target Language:** Japanese, ja-JP

**Comment by kazushono** [comment]
I intend to contribute to this translation.
Can you check how to do it? For example line 113, 119 in attached "Resorces.ja.resx.txt
[Resorces.ja.resx.txt](https://github.com/toggl/mobileapp/files/3786511/Resorces.ja.resx.txt)
". 
Is this OK?

If OK, then I will continue the translation work.

**Comment by MozyOk** [comment]
hi @kazushono san. It may be all right. let’s create a Toggl.Shared/Resources.ja-JP.resx and start translating. i’ll help u.

**Comment by kohki-shikata** [comment]
I'm interested this project too.
How can I help you?

**Comment by mogya** [comment]
Working. Is this a competition?:-)

https://github.com/mogya/mobileapp/commit/3fa7c091c6ed4b05d632a55eb2d679df6f9aaf4d

**Comment by mogya** [comment]
I made the first PR #6389 . I'm welcome your comment or feedback as I know this is not perfect.  @kazushono @kohki-shikata

**Comment by kazushono** [comment]
[Resorces.ja.resx.txt](https://github.com/toggl/mobileapp/files/3788416/Resorces.ja.resx.txt)
This is my translation
