### ISSUE TITLE
Layout messed up on startup before first sync

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#5909]
## 🐛 Bug Report
When starting the app (not when opening the app from background), the time log view layout is messed up until the first sync completes. Suggestions seem to overlap the time entries. 

## Context

![IMG_3632](https://user-images.githubusercontent.com/35216651/65021559-06fab380-d938-11e9-824d-9a4367b5487e.jpg)

Build/Branch: Daneel 2.3
Phone OS: iOS 12.4.1
Phone model: iPhone 7

## Expected behavior
No overlap of different sections. 

## To reproduce
Start the app from scratch (not from background)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24086563571)

**Comment by simonrozsival** [comment]
Fix was merged into a release branch.
