### ISSUE TITLE
Unify the behaviour of UISwitch

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5911]
Currently not all of our switch controls behave the same way - in some places the whole row is tappable and in other places only the switch control is tappable.

To add consistency to the app we should make it so that only the `UISwitch`es are tappable and not the whole row, since that seems to be the default behaviour for iOS.

I found 3 places that need to be changed:
* The create/edit project view
* User calendar selection in the settings
* User calendar selection dialog in the calendar view

☝️ This is not an exhaustive list, since i didn't check all the views in the app, so whoever works on this, please go through the whole app to check if all switches are behaving correctly.

**Comment by amulware** [comment]
I'd like confirmation from @maritoggl on which behaviour we want to use everywhere.

**Comment by maritoggl** [comment]
Let's go with what you've proposed - only the switch is tappable in iOS. 
Afaik Android has a different default - that's ok and we can keep it different.

**Comment by dshr** [comment]
Started on this before my vacay, check `des/wip-selector-madness` for some initial work. Basically, the UISwitches are reconnected to the VM, but for some reason the `SelectCalendar` `InputAction` gets disposed after each selection :(
