### ISSUE TITLE
Dark mode switch breaks the Reports page

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#5926]
## 🐛 Bug Report

Switching the dark theme toggle while looking at the Reports page makes all graphs invisible until next app kill and restart. 

## Context

Build/Branch: develop
Phone OS: Android 10
Phone model: Pixel 1

## Expected behavior

Reports should continue to work as before the switch.

## To reproduce

- go to reports page
- toggle the theme from quick settings
Now The theme has been updated and reports tab is still correctly selected but all the graphs disappeared. The reports tab remains broken like this until your kill and relaunch the app.

## Suggestions

We will leave this one for @kornelijepetak since he will be in charge of the complete Reports rewrite.

**Comment by amulware** [comment]
May no longer be relevant, but let's double-check.

**Comment by daividssilverio** [comment]
Doesn't seem to be happening in 2.9 release candidate.
@semanticer are you still able to replicate this issue?

**Comment by pdrj** [comment]
We had the following issue in the project: https://github.com/toggl/mobileapp/issues/6564
I validated that it no longer happens, but my phone doesn't have dark mode switch in quick settings, so please validate it doesn't happen when utilizing those.

**Comment by daividssilverio** [comment]
I've tested and validated it on my Note 10 with android 10. It was working there.
Closing this, re-open if necessary.
