### ISSUE TITLE
Calendar: Non-confusing settings button

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5931]
Settings button will be in the top right corner of the calendar view.

- [x] corner view of calendar
- [x] corner view of main log (like iOS)
- [x] remove tab bar settings item

It leads to general settings (not calendar settings any more)

(https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5a8613f5a212ab0471a3e0b4) positioning if easily possible

**Comment by daividssilverio** [comment]
Closed by #6317
