### ISSUE TITLE
Change workspace button in reports freezes the app

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#5932]
## 🐛 Bug Report
The title says it all.

## Context

Build/Branch: 2.4 from testflight
Phone OS: iOS 12.something
Phone model: iPhone X

## Expected behavior
The select workspace view should show up

## To reproduce
1. Open reports
2. Press the button to change workspaces
3. ❄️ 

## Suggestions
Probably related to the select view refactors.

**Comment by Odrakir** [comment]
@arturs105 This happens with every selector in settings as well, so the problem is probably with the new generic selector.
