### ISSUE TITLE
Deduplicate expensive Rx calls

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#5952]
## 🚧 Refactor Proposal
We are doing some expensive calls on Rx more than once. this is impacting our startup times.

## Technical aspects
We need to check each expensive call we make using Rx and make sure that we are using Connect/RefCount correctly to avoid multiple subscribers making multiple calls.

**Comment by amulware** [comment]
This is still pretty vague - what are those expensive calls? Where should one look? What's required for this issue to be closed?

**Comment by heytherewill** [comment]
This will be collaterally fixed by a bunch of other issues that will be opened, so I'll close it for the time being.
