### ISSUE TITLE
Find a way to re-enabled Siri Workflows

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#5966]
Apple disabled sharing shortcuts via a file in iOS 13, so this completely broke our Workflows section (we disabled it in 2.4).

We need to find a way to enable it again. Apparently there's something new coming in 13.1, we need to check if it'll help us.

Also, the workflows section in settings has been disabled, but the rest of the code is there and should be taken care of together with this issue. 

Reference: https://www.imore.com/apple-improves-support-sharing-links-your-siri-shortcuts

**Comment by simonrozsival** [comment]
There doesn't seem to be a solution for this problem at the moment. We should revisit this in the future and check if we have some new options.

**Comment by Odrakir** [comment]
I'm closing this for now. If we ever want to do anything like workflows again it'll probably require a completely different approach (thanks Apple...)
