### ISSUE TITLE
Review the way we detect running time entries

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#597]
The problem is that we assume that a running time entry is one which has a `null` value of the `Stop` property. 

> reports are based on start and duration
> stop is nice to have
> given v8 will be around for some time, time entries w/o start and stop are also present
> as in, yes, they have start and stop times, but since they’re duration only, one should look start for the day/date and duration for, well, duration
> stop there is the timestamp when the entry was last stopped

Possible solutions:

- change the logic in the app to check for the `Duration` property instead of `Stop` property
- make the serialization logic smarter in the sense of setting the `Stop` property to `null` if the `Duration` is negative

**Comment by amulware** [comment]
This makes me mad. I'll figure out how to handle this asap.

**Comment by amulware** [comment]
Backend may be changing this stuff up in the near future. Let's wait for that and until then we just do what we are doing right now since it works.
