### ISSUE TITLE
Calendar: Top toolbar improvements

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5972]
Set the date and the total duration of the day as in the design below.

- [x] Label at the top left side of the screen (with chosen date displayed) to maintain left aligned Android app layout
- [x] Daily tracked hours on the right

Design: https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5d8a175b0830e2161df7fcee

**Comment by daividssilverio** [comment]
Closed by #5983
