### ISSUE TITLE
Calendar: Use `ISectionViewModel `

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#5997]
Migrate from `ObservableGroupedOrderedCollection` to `ISectionViewModel` in the calendar view

**Comment by Odrakir** [comment]
To clarify, that obsolete thing (that we should :fire:) is only used in `CalendarCollectionViewSource` and `CalendarDayViewModel`

**Comment by sofokli1** [comment]
ref https://github.com/toggl/mobileapp/issues/6953
