### ISSUE TITLE
Review and correct sizing methods

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6007]
I've corrected most of these in #5994 but there are still some left.

Basically this is two things:

- We shouldn't be using `UIUserInterfaceIdiom` to layout items depending on iPad/iPhone. Instead we should use `TraitCollection.HorizontalSizeClass`
- We shouldn't use `UIScreen.MainScreen.Bounds` to get the size of the app's window, instead we should probably be looking at the parent VC bounds or layout guides. But if we really need the window we should use `MyVc.View.Window.Bounds` or  `UIApplication.SharedApplication.KeyWindow.Bounds`

All this is basically because of multitasking views on iPad. In iPhone (or iPad fullscreen), everything works fine, but as soon as the app doesn't fill the whole screen we need to be careful about where do we get those measures from.

To solve this we need to search and replace all occurrences of `UIUserInterfaceIdiom` and `UIScreen.MainScreen.Bounds`.

**Comment by heytherewill** [comment]
@Odrakir Is this worth working on?

**Comment by Odrakir** [comment]
I don't think so, but we should probably be careful and not copy that same code in the rewrite.
