### ISSUE TITLE
Pie chart is not updated after deleting a TE

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#6028]
## 🐛 Bug Report
After visiting the reports page, then going back to the main view, deleting a time entry and going back to the reports page, the pie chart still shows old data, as if the TE has not been deleted.

## Context

Build/Branch: develop
Phone OS: android
Phone model: pixel emulator

## Expected behavior
Pie chart to be updated with the new data (deleted time entry not shown).

## To reproduce
Create 2 TEs for the current day.
Go to the reports page, select 'today' as the time range.
Validate that the pie chart displays the two TEs.
Go back to the main view, delete one TE.
Go back to the reports page, both of the TEs are still shown on the pie chart.

**Comment by amulware** [comment]
Simon is right. What we could do is show 'generated at <time>' when a user comes back to the reports page at the top somewhere.

I'll leave this to @maritoggl - close it if things are as they should, or let us know what to do. :)

**Comment by maritoggl** [comment]
Would it be tricky to clear that cache after certain actions? Actions such as deleting, editing and/or stopping a running time entry.

**Comment by amulware** [comment]
It may not be (check with a developer). But consider that syncing takes time/can fail, so it's not a perfect solution. Maybe clearing the cache when sync finishes would be a solution?

**Comment by pdrj** [comment]
I've not looked at the cod and to be clear - I'm talking about local deletions only, not cross client. It also works fine for new time entries - the pie chart is updated without any delays, so I figured it should work for local deletions in the same way.

What's interesting, in testing I did today, it was sometimes updated for deletions, sometimes not. It was not a case of me hitting the 5 min cache invalidation, as the situation happened multiple times in a 5 minute window.

**Comment by amulware** [comment]
I don't know exactly what our app does and if it actually caches, but I do know that deletion (because of the undo feature) will take at least 5 seconds to actually go through, plus whatever time it takes to sync to backend. Once synced, any new reports will be generated with the updated data.

**Comment by amulware** [comment]
I'm closing this because I'm not sure what we can do to improve UX here. Feel free to reopen if you think otherwise.
