### ISSUE TITLE
Siri doesn't allow users to set shortcuts with parameters

### ISSUE THREAD

**Issue by nidarasheed** [toggl/mobileapp#6038]
In Daneel 1.12.1, the changelog included "- Improved Siri Shortcuts integration, you can now create time entries including the project and tags information" however, this is no longer an option with Siri shortcuts. 

## 🐛 Bug Report

Siri shortcuts for Toggl no longer support adding a project or tag to the shortcut. 
## Context

Build/Branch: 2.4
Phone OS: 12.4.1
Phone model: iPhone 8 

## Expected behavior

I would expect to be able to set a shortcut that includes project and tag. 
## Suggestions

[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/23869010561)
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/23939198023)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24160017495)

**Comment by Odrakir** [comment]
This is the same as #6299
