### ISSUE TITLE
Background syncing does not work on iOS 13 (it seems)

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6039]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/374616/66206844-8cf55900-e6b1-11e9-935a-4b4f1292bc2d.png)

See: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/analytics/events/BackgroundSyncFinished

## Context

Build/Branch: iOS 2.4
Phone OS: iOS 13 (most likely)
Phone model: any `iPhone`

## Expected behavior
Background syncing starts and finishes.

## Suggestions
@juanlaube said that there is a new framework for background syncing in iOS 13

**Comment by simonrozsival** [comment]
We decided to use only "sync light" in the background sync interactor to decrease the time it takes background syncing. We'll see how that affects the number of successful syncs in the next release.

**Comment by Odrakir** [comment]
Since we still need to look at this issue after it's released, I'm moving it to 2.6

**Comment by simonrozsival** [comment]
I should have noticed this earlier. We broke background syncing in iOS 2.3. Here's the comparison of number of events in 2.2.1 and 2.3:
![image](https://user-images.githubusercontent.com/374616/67275541-22228b00-f4c3-11e9-86d4-45621b0b6274.png)
![image](https://user-images.githubusercontent.com/374616/67275546-264ea880-f4c3-11e9-8be7-2c3a05c4cd99.png)

It's the same for 2.4. No background sync has been successful since the release of 2.3.
