### ISSUE TITLE
Fix certificate trust issue on iOS 11

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#604]
Right now we are ignoring the certificates altogether, but we need to investigate, find out what's causing the problem and provide an appropriate solution for the problem.

**Comment by willsb** [comment]
xamarin/xamarin-macios#2864 is needed before this is closed. Xamarin.iOS [11.4](https://developer.xamarin.com/releases/ios/xamarin.ios_11/xamarin.ios_11.4/) is based on branch `d15-5`, which [does not contain the fix](https://github.com/xamarin/xamarin-macios/blob/d15-5/src/Security/Tls/AppleCertificateHelper.cs). One must wait 🤷‍♂️

**Comment by willsb** [comment]
I also advise removing this from the milestone

**Comment by amulware** [comment]
Agreed.

**Comment by amulware** [comment]
I don't see this happening anytime soon.
