### ISSUE TITLE
Move from JobScheduler to WorkManager

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6094]
## 🚧 Refactor Proposal
We use WorkManager instead of JobScheduler. WorkManager will give us more flexibility, should be more consistent across all android versions and all the new features are added there.

## Dependencies
We most probably need to solve the AndroidX migration first https://github.com/toggl/mobileapp/issues/5700

## Technical aspects
We need to implement every `Job` as `Work` and since WorkManager's API is more powerful, we might consider spitting the jobs into more Work(s) to increase granularity and use chained execution. WorkManager provides many cool API's like that so we should make sure we are taking advantage of them.

**Comment by semanticer** [comment]
This is a huge refactor and because it's dependent on #5700 I would rather not do both in one release. I strongly suggest moving this to 2.9 or in this case maybe even 2.10 when the situation around AndroidX is hopefully more stable.
ok @amulware ?

**Comment by daividssilverio** [comment]
This issue might still be worth doing. Because of the current crash we are experiencing without known sources, but likely related to our services.
