### ISSUE TITLE
Migrate over to ViewPager2

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6095]
## 🚧 Refactor Proposal
There is the new version of ViewPager in town! It's based on recycler view and allows much more flexibility. 

## Dependencies
We need to solve the AndroidX migration first https://github.com/toggl/mobileapp/issues/5700

## Technical aspects
ViewPager2 is a complete rewrite based on the RecyclerView so the API should be different but familiar. 
More about ViewPager2 usage, benefits and implementation: https://medium.com/google-developer-experts/exploring-the-view-pager-2-86dbce06ff71

**Comment by semanticer** [comment]
This is a huge refactor and because it's dependent on #5700 I would rather not do both in one release. I strongly suggest moving this to 2.9 when the situation around AndroidX is hopefully more stable. 
ok @amulware ?

**Comment by heytherewill** [comment]
@semanticer Does this depend on #5829?

**Comment by semanticer** [comment]
No, it's not a material component - only part of Androidx

**Comment by heytherewill** [comment]
@kornelijepetak Do consider using ViewPager2 in your calendar endeavors!

@semanticer where else should we use ViewPager2?

**Comment by semanticer** [comment]
WeekStripePager(`Resource.Id.WeekStripePager`) in the Calendar and maybe also DaysPager(`Resource.Id.Pager`) if we can recreate `LockableViewPager`'s  behavior.

**Comment by semanticer** [comment]
Even though viewpager2 is in a stable 1.0.0 version for some time now, there is no Xamarin binding yet.  I'm adding `on-hold` label and removing this from 2.9 release.
ping RM @pdrj
