### ISSUE TITLE
Widget doesn't respect device "Night" mode

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6135]
This is a samsung feature as far I know, but on my Note 10.
The widgets don't update their colours when I turn the "Night Mode" on and off.
If I remove and add the widgets again, it works fine.

As far as the dark mode interaction, the app also doesn't respect this "Night mode" thingy as well.
It whole app only notices the "night mode" and applies the dark mode after 10 pm (yes..., I'm not joking).

**Comment by juanlaube** [comment]
The widgets respect the system theme correctly when installed but won't change automatically when the night mode setting changes. While I don't have confirmation, this looks like a problem with the widgets host and is something we cannot control.
