### ISSUE TITLE
Consider adding visual indication for the "locked swipe" when the calendar contextual menu is open

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6141]
We might or might not do this, creating this issue so that we can decided to do it later and not block #6099.

>It's not clear at all that the contextual menu is locking the swiping of days. I thought it was a bug before looking at code. I advise changing this behavior or making it more clear by adding some UI indication

originally posted by @heytherewill on https://github.com/toggl/mobileapp/pull/6099#pullrequestreview-300811588

**Comment by daividssilverio** [comment]
This doesn't seem to be related to refactorations. Are we closing UI improvement related issues as well?

**Comment by heytherewill** [comment]
We are closing issues that might introduce complexity and instability, which seems to be the case for this one. If you think that's not the case, we can work on this :)
