### ISSUE TITLE
Make sure UI updates do not block execution of syncing

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6146]
This is a follow-up of #6144.

We want to make sure, that no operation in the UI does not block the execution of the syncing algorithm. We had a problem that because syncing waited for `DataSource.BatchUpdate` to complete, it wasn't able to finish synchronization. The problem was that `BatchUpdate` was blocked by a UI update, which waited for database and data source to fetch all the time entries from Realm and convert them to POCOs.

Many of the syncing states alter the state of the database, which might trigger an UI update. We must make sure that the UI update runs in a different thread and that we don't wait for it to finish. It might be necessary to just force observations of `ObservableDataSource.ItemsChanged` to be on a different thread, but I'm not sure if that would suffice. It is necessary to investigate this more in depth.

**Comment by amulware** [comment]
This still seems like a big deal.
