### ISSUE TITLE
Group count doesn't look good with more than 1000 TEs

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6148]
## 🐛 Bug Report
The count label in a time entries group wraps to two lines when it has more than 1000 time entries. See the following screenshot.

![Screenshot_1571230965](https://user-images.githubusercontent.com/8163330/66922021-a032ed80-effc-11e9-812b-f02febd208c5.png)

## Context

Build/Branch: develop
Phone OS: Android
Phone model:

## Expected behavior
The label should fit in one line, alternatively we can show `+99` or something similar 🤷‍♂

**Comment by amulware** [comment]
@maritoggl Do we really need this? Sure, it looks stupid, but is it even worth writing code for this?

If so, I'd say let's go with `99+`. Otherwise I'm also fine if we just ignore this.

**Comment by maritoggl** [comment]
Ignore
