### ISSUE TITLE
Implement detailed logging in the app

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6173]
It would be very helpful for debugging purposes to log the operations that are happening in the app and send them to support when the Feedback form is submitted.

I am not sure at this moment, if we should simply store the events we send to analytics events to the database (it would be quite easy to implement and it would be a good way of debugging syncing problems) or if we should add "new" logging mechanism (probably not). I leave this to the implementor to figure out (or for somebody else to specify this later).

I think this should add a new table to Realm and write log objects into it. It would be then serialized into a text file, which would be uploaded somewhere (either BE gives us some way of doing it or we just use firebase storage to store these logs and add a link to the file to the feedback form.

**Comment by amulware** [comment]
This issue is too vague. I agree that we could use logging, but we have to actually figure out how to best implement it.
