### ISSUE TITLE
Splash screen on iOS has always black background

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6177]
Even in light mode, the background of the splash screen is black.

**Comment by Odrakir** [comment]
I can't reproduce it, can you make a video?

**Comment by simonrozsival** [comment]
I can't reproduce this in the simulator anymore, but I will send you a recording of the testflight version in Slack. Our code looks OK. The only thing we could do is to use the system background color (white/black) instead of our custom background color, but I guess we don't have to and we can ignore this for now, most users won't notice it anyway and maybe it's just some test-flight/iOS glitch whcih will be fixed by Apple at some point.
