### ISSUE TITLE
Dark Mode: Reports project list has white border on iPad

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6190]
![IMG_FA732C69042C-1](https://user-images.githubusercontent.com/3987892/67008221-f9744d00-f0e0-11e9-8575-2af9a6d74d9c.jpeg)

**Comment by amulware** [comment]
Also note the mismatching rounded and non rounded corners, not sure if that's a quick fix.

**Comment by simonrozsival** [comment]
The fix was merged into release branch.
