### ISSUE TITLE
Dark Mode: Calendar has white margins on iPad

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6191]
![IMG_64B43847CEF3-1](https://user-images.githubusercontent.com/3987892/67007987-81a62280-f0e0-11e9-8091-8e47afdb5cad.jpeg)

**Comment by amulware** [comment]
Same on light mode, with the calendar being light gray, and it looks.. strange.

**Comment by simonrozsival** [comment]
Fix was merged into release branch.
