### ISSUE TITLE
Use DateTime instead of string in models

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#62]
Models currently represent dates with a string property (`User.At`, `Workspace.At`). The type of these fields should be `DateTime`.

The problem is that this modification messes up the serialisation - it doesn't add timezone and it causes the converted json to differ from the one that the API returns. Instead of being something like "2016-03-31T20:43:57+00:00", it is "2016-03-31T20:43:57".

Could probably be solved with a custom json converter.

**Comment by amulware** [comment]
In accordance with #75, let's use the NodaTime Instant type instead.

**Comment by amulware** [comment]
For practical reasons, we decided to use DateTimeOffset instead for the time being.

**Comment by amulware** [comment]
Feel free to reuse the code in the closed PR above, but please submit a new one after making sure DTO is used everywhere it should be.
