### ISSUE TITLE
Suggestions ignore tags

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6221]
Starting a time entry from the suggestions in the main log ignores the tags.
I've found `Toggl.Core.Suggestions.Suggestion` ignores the tags in the constructor, everything else (project, client, task, billable, etc) is set properly and respected when starting a time entry.

I'm not sure if this is by design, so I'm pinging @amulware and @maritoggl just in case.

**Comment by kornelijepetak** [comment]
I don't think this was by design. It looks like an oversight...

**Comment by maritoggl** [comment]
Not by design. Let's fix.
