### ISSUE TITLE
Password suggestion in dark mode

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6239]
When signing up, if the system fills the password with a suggested one, the field looks weird.

![IMG_BA1634457DE1-1](https://user-images.githubusercontent.com/724743/67189107-ebc70c00-f3ed-11e9-83b9-aca68fde1904.jpeg)

This is true also for light mode, but it's not that bad.

![IMG_2DC06417919A-1](https://user-images.githubusercontent.com/724743/67189119-ee296600-f3ed-11e9-863b-291d9c7db7c4.jpeg)

**Comment by dshr** [comment]
Can't even get this option to show up on iPhone 7, plus nothing comes up in the docs regarding customising this.

**Comment by heytherewill** [comment]
This seems to be ugly on purpose (to denote that you filled your password using a service) and it's ugly on every other app as well, so I guess there's nothing we can do here 🤷‍♂

**Comment by arturs105** [comment]
It seems like we can't do anything about the fact that it's ugly jellow, however we could do something about the size of it - make it smaller and/or add rounded corners. I suspect it is as ugly because we are using a custom text field.

**Comment by simonrozsival** [comment]
If we can detect that this is happening, I think it would be a good solution to:
- set text color to black (the background color is always yellow in both light and dark theme,
- hide the 👁 button.

It would be nice if we could move the "Password" label to be above the yellow background (and with black text color).

**Comment by simonrozsival** [comment]
Maybe we don't have to set the text color to black, but rather to "default text input color". The OS will handle the change of color for us.

One thing that makes it look weird is that the base line "Strong password" text isn't aligned with the base line of the actual password. Maybe it could be possible to fix it somehow.

**Comment by simonrozsival** [comment]
I think this might have been a bug in iOS which they now fixed:
![image](https://user-images.githubusercontent.com/374616/68870912-efebfe00-06fb-11ea-991f-65b8dec2717d.png)
![image](https://user-images.githubusercontent.com/374616/68870957-009c7400-06fc-11ea-8bbd-c215c4ccdf33.png)

I suggest closing this issue for now.

**Comment by simonrozsival** [comment]
OK. Don't listen to me. It doesn't work properly in the simulator for some reason, it looks exactly how Ricardo described it on my device.

**Comment by simonrozsival** [comment]
My proposal is to simplify the login/signup fields. We can keep our custom look, but we won't have the over-complicated animating placeholders/labels, which don't even feel very "native" on iOS IMO.

![image](https://user-images.githubusercontent.com/374616/68939609-55de9100-07a1-11ea-9993-222113332120.png)

**Comment by Odrakir** [comment]
I'm not sure if that solves the issue, though... Have you tried? 🤔

**Comment by simonrozsival** [comment]
If the password has regular height (33pt) instead of our custom (54pt), It's all just one line. The `Password` label would be visible and it won't be overlapped by the yellow rectangle. It's just a few adjustments, I'll try it quickly and I'll post a screenshot.

The 👁 button would still be displayed over it... we'd need to have the icon displayed under the text input, but the button above the text input so it reacts to touch.

One thing I'm not sure what to do about is the text color. In dark mode, it's always white and it is hardly noticeable against the yellow background.

**Comment by simonrozsival** [comment]
This is what it could look like: 
![image](https://user-images.githubusercontent.com/374616/68942705-86c2c400-07a9-11ea-97ca-caa7d2863e3f.png)

There's still the 👁 icon weirdness. I'm not gonna dig into this deeper at the moment.

**Comment by Odrakir** [comment]
Yeah, it's a bit better, but the thing with the text being unreadable is still there (and also the eye icon). I'm ok with doing what you suggest, but still doesn't fix this issue.

**Comment by simonrozsival** [comment]
This is how it looks in Spotify:
![image](https://user-images.githubusercontent.com/374616/68945521-de186280-07b0-11ea-800e-a06b663264e7.png)

- the password is normally shown as black letters, for some reason it's not shown in the screenshot (security?).

**Comment by simonrozsival** [comment]
I figured out the problem with the eye icon. We must use the `rightView` property of the `UITextField`.
