### ISSUE TITLE
Forgot password error message not showing

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6241]
When the keyboard is out, the forgot password error message is hidden, it only shows when the user hides the keyboard.

https://toggl.slack.com/archives/C02APMYTM/p1571647222199400

**Comment by simonrozsival** [comment]
I couldn't reproduce this in the simulator.

**Comment by Odrakir** [comment]
Me neither, only in the old version on device... Maybe it was fixed somehow? 🤔 I'm closing it for now.
