### ISSUE TITLE
Can't see eye button in login in dark mode

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6243]
The eye button that shows/hides the password in loging/signup its not visible in dark mode.
![IMG_C31C0AD05ACC-1](https://user-images.githubusercontent.com/724743/67190611-87f21280-f3f0-11e9-9ff0-d941fd1de4d2.jpeg)
![IMG_D9649BA48AAC-1](https://user-images.githubusercontent.com/724743/67190613-89233f80-f3f0-11e9-8ef0-50de4e5653ea.jpeg)

**Comment by simonrozsival** [comment]
A fix was merged into a release branch.
