### ISSUE TITLE
New entry description not visible in dark mode

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6245]
If you start a new entry, and try to input the description, the text will be black and thus, invisible. After you change focus, it'll show white as it should.

![IMG_C287B336262D-1](https://user-images.githubusercontent.com/724743/67191275-a60c4280-f3f1-11e9-9fd2-751eb6a442bb.jpeg)

**Comment by simonrozsival** [comment]
Fix was merged into release branch.
