### ISSUE TITLE
Log whole API response on failed api test

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#625]
As the title says. Not sure how to implement this best, but it would help us a lot with analysing errors, especially since the response contains a unique id that backend could grep their logs with, as well as the full error information of course.

**Comment by simonrozsival** [comment]
Just to be clear, by this you mean "just" writing the `RawData` of the failed HTTP request in integration tests to stdout? Or does _whole_ mean also serializing the headers?

**Comment by simonrozsival** [comment]
Please add more details, @amulware.

**Comment by amulware** [comment]
Headers as well, please. These include the unique response id and possibly other useful info.

Thinking about it, this might not be trivial I take it? Feel free to let us know what the options are and maybe there is a compromise somewhere.

**Comment by simonrozsival** [comment]
I thought about the best way to implement this feature, but I haven't found an ideal solution yet.

First I thought this could be done by using some attributes, but in the `BeforeAfterAttribute` I can't access the object which holds the exception which caused the failure of the test. Xunit does not have any dependency injection.

The second idea is to change the way how the `ApiException.Message` works. One problem is that this cannot be multiline and therefore everything will be printed on one long line. This probably wouldn't be a problem after all. The problem with this is that it requires to edit allll of those client and server exceptions, which is quite a lot of work.

Another solution to this problem might be adding some `Debug.WriteLine`s to the `BaseApi` class. The problem with this is that this doesn't output into stdout in Bitrise. But that might be only a problem of configuration of the project/solution.

I won't be able to do this today, so I will just leave these notes here for the next week, when this could be implemented. Any ideas and opinions are welcome!

**Comment by amulware** [comment]
I think we may have to add more data to the ApiException (in a separate property) and make sure that is printed when the exception is thrown. My assumption would be that it will use the ToString() method of the exception for printing? If so, we can override the default behaviour and add our own output, where relevant.

It does indeed seem like we need to edit all the exceptions, but other ideas are welcome.
