### ISSUE TITLE
User cannot turn on notfications

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6252]
## 🐛 Bug Report
A user says they cannot turn on notifications, the dialog doesn't show in the calendar tab, in the smart alerts setting it looks like the notifications are not authorized and in the settings app the notification settings is not showing.

![image](https://user-images.githubusercontent.com/8163330/67195571-8b28d680-f3cf-11e9-8ce4-435a5ebbe248.png)
![image (1)](https://user-images.githubusercontent.com/8163330/67195587-924fe480-f3cf-11e9-87d1-e48b96d57ea1.png)

## Context

Build/Branch: iOS 2.4
Phone OS: iOS 13.1.2
Phone model: iPhone11,6 (Xs Max)

## Expected behavior
User should be able to turn on notifications.

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24121708338)

**Comment by mattladd34** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3560471/conversations/24654936616)

**Comment by mattladd34** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24706000550)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/24912190008)

**Comment by maritoggl** [comment]
Should have discovered this issue 2 minutes ago. Created a proposal for an improved permission flow here https://github.com/toggl/mobileapp/issues/6797 - feel free to merge the two and close either one.

**Comment by mattladd34** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3560471/conversations/25132751352)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25224208585)
