### ISSUE TITLE
Start from clipboard Siri Shortcut is not working

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6255]
The started time entry has no description (it should have whatever was on the clipboard as description). Also the shortcut shows no UI.

**Comment by Odrakir** [comment]
We are out of ideas with this one, other than removing this to use shortcut inputs (#6315). This needs to be tested in future iOS versions because it actually seems like an Apple (or Xamarin) bug.

The problem being we can't read the clipboard from an app extension.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24803542736)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25257863324)

**Comment by Odrakir** [comment]
I'm closing this for now, as it'll be handled in #6315
