### ISSUE TITLE
Calendar Bottom sheet: Dark mode

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#6264]
Add the appropriate colors and changes for dark mode. Talk with people that worked in PR #6053 for help.

**Comment by daividssilverio** [comment]
🤔 I'm not sure how to improve this, I just know that the contextual menu doesn't look great in dark mode.

Any idea on how to improve this @AlicjaSuska

![image](https://user-images.githubusercontent.com/2173493/67421034-b3663000-f59d-11e9-8978-f544e2d69b6f.png)

**Comment by daividssilverio** [comment]
Maybe @Odrakir and @simonrozsival could give their thoughts as well?

**Comment by semanticer** [comment]
Since it should be very easy to implement, I'm adding this to Android 2.8 - @AlicjaSuska is now aware of this and should provide designs soon. If not, I will try to fix this myself - it shouldn't be too hard to improve this.

**Comment by AlicjaSuska** [comment]
About the icons: I'm not sure what happened but those that are used for light designs look good on dark background. Maybe opacity is not 100%? Please, see the picture:

![Android - Calendar - Dark mode - Icons](https://user-images.githubusercontent.com/20326070/68851302-fcf5f680-06d5-11ea-8ee4-b7341352c880.png)

**Comment by semanticer** [comment]
Ok, it looks like we did something wrong with the opacity - thanks I will look at it soon.
