### ISSUE TITLE
Intents with Chrome

### ISSUE THREAD

**Issue by mskrip** [toggl/mobileapp#6278]
Hi,

is (or would it be) possible to control the application through [Android Intents with Chrome](https://developer.chrome.com/multidevice/android/intents)?

## Desired behavior

Have a link on a site (see [examples](https://developer.chrome.com/multidevice/android/intents#example)) to open the application with a custom task name and maybe a project specified?

**Comment by mskrip** [comment]
@simonrozsival Hi, would it be possible to have a word on this from maintainers? Sorry to bother, we're just being pressed on time with this as it would enable custom integrations with private static websites.

**Comment by daividssilverio** [comment]
Hey @mskrip , we do have deep linking already implemented.
You can check https://github.com/toggl/mobileapp/blob/develop/Toggl.Core.UI/Services/DeeplinkParser.cs for details.

Be aware that they are currently only being used internally only in our app extensions (widgets, notifications, tiles, etc) and weren't tested to work specifically with android intents with chrome.

About adding support specifically for that, @amulware @maritoggl, not sure if that matches our priorities at the moment.

**Comment by amulware** [comment]
Thank you for the feature request, and no bother at all!

@mskrip Please feel free to find and use the urls in the file Daivid mentioned. They are currently not officially supported, so in principle, they could change at any time, but realistically, I don't see us making frequent changes to them.

Making these official and public is not a priority right now, but we'll definitely keep this in mind for next year's plans.

Could you tell us more about your use case? What kind of actions would you like us to support, and what do you use this for?

**Comment by mskrip** [comment]
Thank you for your response. Our use case is that we want to be able to create a new time entry with the specified name and project from our private website (even static, so we are not able to handle authentication for straight integration with Toggl API). Not necessarily starting the time entry, just opening the app with predefined data should be enough. For now, that should be enough for supported actions.

I've looked at the deep linking and managed to open the app with them but not controlling the app itself. Can you please help me with that? The following link should be able to stop the currently running entry:

```html
<a href="intent://tracker/timeEntry/stop/#Intent;scheme=toggl;package=com.toggl.giskard;S.stopTime=2019-11-20T12%3A31%3A50Z;S.source=test;end">stop</a>
```

**Comment by daividssilverio** [comment]
Hey @mskrip , that intent you've just sent is almost right.
I've tested and currently, it works fine. But you have to confirm the right paths in this class: 

https://github.com/toggl/mobileapp/blob/develop/Toggl.Shared/ApplicationUrls.cs

Specifically for `stop`
https://github.com/toggl/mobileapp/blob/0680b7d5fae2425fa337d00ab9c65c703d14c807/Toggl.Shared/ApplicationUrls.cs#L42-L51

There's no `/` after the `stop` action, as you can see in the usage examples here:
https://github.com/toggl/mobileapp/blob/0680b7d5fae2425fa337d00ab9c65c703d14c807/Toggl.Core.UI/Services/DeeplinkParser.cs#L71-L78

So, your example will work if you adjust it to
```html
<a href="intent://tracker/timeEntry/stop#Intent;scheme=toggl;package=com.toggl.giskard;S.stopTime=2019-11-20T12%3A31%3A50Z;S.source=test;end">stop</a>
```

live example: https://codepen.io/daividssilverio/pen/PooLwgw

**Comment by mskrip** [comment]
Oh, right thanks. That one works now. Also using `/timeEntry/new` works for me. But for some reason, I can't manage to pass the data to the app (entry description). Using following the link it opens the app, creates a new entry but the description is not set (same for `l.projectId` that I've tried).

```html
<a href="intent://tracker/timeEntry/new#Intent;scheme=toggl;package=com.toggl.giskard;S.description=Test;end">toggl</a>
```

**Comment by amulware** [comment]
Closing this as it seems to be resolved. Feel free to reopen or open a new issue if anything else comes up. :)
