### ISSUE TITLE
A time entry in our app can become "undeletable"

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6289]
When our user has a TE in our app, which does not exist on the server, it becomes "undeletable". An attempt to delete the TE ends with the TE reappearing and the error message in the edit view says `Oops. Time entry not found.`.

This message is confusing for the users and the ux is not good. If the TE is not on the server and the user wants to delete it, then we should just delete it in our app and ignore the server error. I'm not sure how we would check that this specific "error" can be ignored and treated as a "success". We might want to check if this error has some specific numeric code (errors messages now have error codes, right? is it already in production?) which we could hardcode in our app.

The ideal way of solving this issue is to figure out how the app got into the state where there is a TE in the app's database which has a server-assigned (positive) ID, but does not exist on the server. The particular user who reported this problem has a single workspace and is the only user in this workspace. This shouldn't be related to "losing access to a workspace". We must figure out how to reproduce this without messing with the data in Realm Studio.

Intercom link: https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24064700153

**Comment by amulware** [comment]
I definitely would like to know how this can happen.

**Comment by juanlaube** [comment]
I was able to reproduce this in iOS 2.6 RC. I created a time entry with a description longer than the limit, so it was unsynchable, I deleted the time entry and after a few seconds it appeared again in the main log.
