### ISSUE TITLE
Investigate and fix janking in the android calendar

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6296]
There seems to be some janking when swiping pages in the calendar. It probably happens when you have a lot of time entries in the page you're scrolling to.

> I'm also getting some noticeable jank when changing weeks and landing on a day that has lots of time entries. Something is running on the main thread when it shouldn't

_Originally posted by @heytherewill in https://github.com/toggl/mobileapp/pull/6163#issuecomment-544528275_

**Comment by daividssilverio** [comment]
Putting this on hold until #5946 is merged.

Notes I left internally:
_I’ve profiled and the problematic parts seem simply be the view pagers creating their views in there.
We have two pagers in that fragment, one for the days and one for the week stripe.
Interesting enough is that only the first instance of the pages and their viewmodels take longer to be created (90 ms vs 1~3 ms).
Setting up the pagers take around 100 ms for each (adapter creation, first page selection, bindings, that stuff).
Any ideas on how to get that fast? I’m not having luck on that. Some new eyes could be helpful, I might be looking at the wrong place._

**Comment by semanticer** [comment]
#5946 is closed, I'm removing on-hold
