### ISSUE TITLE
Siri Shortcut - custom details not working when only "Project" is provided

### ISSUE THREAD

**Issue by lise-toggl** [toggl/mobileapp#6299]
## 🐛 Bug Report
Using the `Start timer with custom details` option: 
✔️  Providing a description and project results in a new time entry with the description and project
❌  Providing a project only (no description) results in a new time entry with neither description nor project

## Context

Build/Branch: Daneel 2.4
Phone OS: iOS 13.1.2
Phone model: iPhone SE

## Expected behavior
Providing a project only (no description) should start a new time entry with no description but with the project.

## To reproduce
1. Create a new Siri Shortcut for `Start timer with custom details`
2. Provide a project only
3. Use the shortcut

## Suggestions
[Intercom](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24112136957)
Maybe related to https://github.com/toggl/mobileapp/issues/6038?

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24882445397)
