### ISSUE TITLE
Weird highlighted state for custom siri shorcuts

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6302]
Those cells have a weird highlighted state when tapped.

![Simulator Screen Shot - iPhone 11 - 2019-10-23 at 08 54 04](https://user-images.githubusercontent.com/724743/67365951-e3e4a480-f572-11e9-894c-aaf038474160.png)

**Comment by simonrozsival** [comment]
A fix was merged into a release branch.
