### ISSUE TITLE
Settings nav bar keeps turning white

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6304]
In light mode, whenever you send the app to background and come back, while in settings (or any subsection of settings) the navigation bar background changes to white instead of the intended grey.

![Simulator Screen Shot - iPhone 11 - 2019-10-23 at 09 25 36](https://user-images.githubusercontent.com/724743/67368176-2a3c0280-f577-11e9-9f61-d6d8b57b7eb0.png)

**Comment by simonrozsival** [comment]
A fix was merged into a release branch.
