### ISSUE TITLE
Investigate a document input/output parameters for Siri Shortcuts in iOS 13

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6315]
We need to replace the clipboard shortcut by an input parameter, basically because it fails in iOS 13. Also, we might want do do something with output parameters (maybe extract some data to read back to the user or as input to another shortcut).

This issue is so we investigate what's possible and roughly how should we modify our code. After this research we'll know what subsequent issues to create.

**Comment by Odrakir** [comment]
Clipboard shortcuts are broken in iOS 13 (see #6255).

**Comment by amulware** [comment]
Please ping me and Ricardo (on Slack) when this is done. :)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24803542736)

**Comment by heytherewill** [comment]
Do we still need to work on this?

**Comment by juanlaube** [comment]
I think it makes sense to do it in Aurora only

**Comment by heytherewill** [comment]
Carrying it over to native. Let me know if you have objections, @Odrakir

**Comment by Odrakir** [comment]
None at all. But in any case re-defining this feature should be done before trying to port the current implementation. So I'll try to do the research this week anyway.
