### ISSUE TITLE
UI fixes: suggestions view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#633]
- [x] Suggestion view misses top separator
- [x] Suggestions view should end with the last suggested TE (the white are is redundant)
- [x] Determine suggestion count by the size of the screen

<img width="781" alt="screen shot 2017-09-26 at 08 41 51" src="https://user-images.githubusercontent.com/5064445/30844238-c443a382-a296-11e7-8ce2-91f2a572a642.png">

**Comment by willsb** [comment]
Should this be closed? ping @arturs105

**Comment by arturs105** [comment]
Yes
