### ISSUE TITLE
Syncing "progressbar" improvements

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6336]
I'd like to propose a change to the "Syncing progress bar" on iOS which could improve the UX of the app and help reduce the number of confused users reporting syncing issues to the support team (my OKR).

First of all: this change does not affect Android, because the Droid app does not have a counterpart to the syncing progressbar. The Android UI shows a spinner while it's syncing and if something fails, they show a "toast" bar with a "Retry" btn at the bottom of the screen.

## Current state
The syncing bar currently can have 5 states:
- the "Pull down to refresh" and "Release to Refresh" text with gray ⬛️ background
when the app is not syncing
- the "Syncing... ♻️" state with gray ⬛️ background while the app is syncing
- the "Synced ✔️" state with green ✅ background when the app successfully finishes syncing
- the "Offline ✖️" state with gray ⬛️ background when the network returns a failure
- the "Failed" state with gray ⬛️ background when syncing fails (e.g., 429, or an internal exception occurs, this state is not shown when some entity is "unsyncable", it is actually quite hard to force the app into this state and I don't know how to do it reliably.)

The "Syncing... ♻️" state is shown for at most 2 seconds and if syncing doesn't finish by then, the bar is hidden, until it finishes (success, failure, offline) or the user pulls the screen down again (then it doesn't retract automatically, but it stays there unless the user scrolls down.

A few screenshots:
![obrazek](https://user-images.githubusercontent.com/374616/67570313-51d6ca80-f731-11e9-9e25-db7182b27437.png)
![obrazek](https://user-images.githubusercontent.com/374616/67570330-61eeaa00-f731-11e9-8f6d-0937862768ea.png)
![obrazek](https://user-images.githubusercontent.com/374616/67570340-6a46e500-f731-11e9-98bb-e857b1ac770a.png)

## Proposed changes
1. don't hide the bar while syncing is in progress
    - the user shouldn't think that syncing has finished but his data doesn't appear on the server
2. show more detailed information instead of just plain "Syncing...":
    - "Getting data from server" (`Pull`, `PullTimeEntries`)
    - "Sending data to server" (`Push`)
    - "Cleaning up" (`CleanUp`)
   - (of course this does not have to be the final copy)
3. changing the background color of the failure state to red 🔴
    - if user reports that syncing failed and he saw red progress bar, we'll have much clearer idea of what could have gone wrong and we won't confuse it with performance or UX problems

## What I expect from this change:
- fewer confused users - mainly because we won't hide the syncing bar before syncing finishes
    - if they talk to support and they tell them to wait until syncing finishes, they will not think that syncing is finished after 2 seconds, when the bar retracts
- more accurate information from the users
    - we will be able to get information like "the app gets stuck while pulling data from the server" or the app always says "pushing data to the server" and it never finishes syncing, if they say "syncing doesn't work" they will say if it showed a red error or if there are problems with some data not being transferred to or from the app
- support agents will be able to sort issues into different categories more easily, because users will report more accurate information
- the app will appear less glitchy
    - the automatic retraction in the middle of syncing doesn't look good, especially when syncing finishes after 2.1 seconds while the bar is being retracted and it jumps back and turns green

## Further remarks
We might be able to show even more detailed progress to the user, for example if the user had more than N (5?) unsynced TEs in the DB, we could show something like "Pushing data to the server 2/9" and the user will have a better idea when syncing will finish. @amulware expressed his concern that users might be able to see how slow our syncing actually is. I think they already see how slow it is and that we can't make it any worse with such change 😂 On the other hand, this would require a non-trivial change to the syncing graph and I'd rather start with the low hanging fruit and see, if it improves UX enough or if users are still unsatisfied with the app.

We talked about the whole syncing bar being annoying and ugly and that we would like to get rid of it completely. While I agree to this, I don't feel confident enough re-designing this completely. I think this major change should be done by an experienced UX/UI designer. Because our designers are overwhelmed at the moment, I'd postpone this redesign until the design backlog is empty or until we decide this is a top-priority for us. Until then, let's do just baby steps.

**Comment by dshr** [comment]
While I'm normally against showing the user too much info, I think this is the case where we should be as open as possible — the visibility of the sync status will prevent user confusion, and will, IMO, improve the UX immensely!

**Comment by Odrakir** [comment]
While I know where you are coming from, I have to say I'm more inclined to the "get rid of it" approach. I think we should split it in 3 components, and I think this will still have the same positive effects you mentioned:

- Pull to refresh bar: Just shows when you start pulling, hides when you stop. Maybe add a little animation when the user pulls enough for it to fire a refresh
- Syncing indicator: Maybe a spinning thing on the left of the nav bar. It'll show when user pulls to refresh, but also when anything else happens that forces sync (and update or a notification). It'll show for as long as the syncing lasts. It's less annoying than the current bar and we could still show some small text or percentage indicator.
- Syncing error bubble (or whatever we call that component that we are already using in some other parts of the app). This will only show we something goes wrong, and we can show as much info as we feel like.

This will probably take a bit longer to do, but I think it's worth the effort.
