### ISSUE TITLE
Sync Health View

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6337]
This is my proposal on how to improve syncing in the mobile app. The goal is to give users and support a tool, which will help them troubleshoot syncing problems of the user without having to reach out to the developers.

## The idea

- Add a dedicated view to "syncing health" to the app. It will always be reachable from settings and when the users has unsyncable TEs, there will be a button :warning: icon on the main view, which would take the user to the syncing health view.
- The view would show similar information, as what support sees when they receive a message from the in-app feedback form, such as the date and time of the last successful sync, or the number of different entities in the app.
- In case the user has some unsyncable entities, there would be a table with all of these entities. It would show the type of the entity (TE/project/tag/client/preferences/...) and the error message (what's currently shown as the "Oops. ..." message in the edit view). Tapping on a TE would open the edit view for the TE (the user won't have to scroll through the main log and look for TEs with :exclamation: icons to edit these unsyncable TEs) and for projects/clients/tags which were created in the app and we weren't able to push them to the server (they don't exist on the server), we'll allow the user to delete them from the app.
- We would show a log of previous sync attempts - we could show the last `N` (5?) sync attempts and how long each of the attempts took, and it's result (successful, failure, offline, interrupted). We're currently not recording these, but we might want to (and we should send it in the feedback form attachment).

## What I expect from this change:

- Users might be able to troubleshoot syncing problems themselves (e.g., they will notice that some TE wasn't pushed to the server and they won't miss this fact, because the TE is somewhere at the bottom of the log and every sync shows "Synced :white_check_mark:" so they might think we lost their TE). After editing the TE and changing the problematic project or duration of the TE, the problem might go away, and they won't have to reach out to us or be mad at our product.
- If users reach out to support, our agents will have easier job of telling them where to look for information, which could help the devs troubleshoot the problem.
- We would increase the transparency of how our syncing works. Syncing is one of the most commonly mentioned issue mentioned in AppStore/Play Store reviews. We might be able to avoid user confusion and increase trust in the app.

## Further remarks

We started working on this one and half year ago, after Madrid, but it hasn't been finished and it is unusable (it's available only in debug mode and it does not show a lot of useful information, just unsyncable TEs). We might build on top of this, but maybe it would turn out to be easier to start from scratch (who knows if it still works, I haven't tried it in months).

I hope we could hack this together without an input of a designer. It's not something that most of the users will ever see (hopefully) and the main purpose of the view would be to convey information to the user. I'm sure we can do this ourselves.

This issue is a very basic description of the idea and I'd like to hear from @amulware and @maritoggl if they would be interested in this at all first, before I start creating more detailed spects and wireframes.

**Comment by amulware** [comment]
> It's not something that most of the users will ever see

Could we track this before we put in the effort? I.e. fire an event when we detect an unsyncable entity, maybe after sync, or some other trigger (whatever trigger we would use for this view itself to show up I figure).

That would allow us to see how often/to how many users this actually happens to see if it is a real problem.

**Comment by maritoggl** [comment]
I'm with Paul here. Ideally, we should first understand what are the reasons for sync failure, then see if there are options to mitigate such situations and then evaluate whether a separate view would be a good solution to solving such issues.
