### ISSUE TITLE
Widgets look odd on system reboot

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6345]
## 🐛 Bug Report
@semanticer left a coment in #6225 with more details, but basically the widgets do not look as expected on system boot, we need to make this look good until the systems decide to update the widgets which should happen a few minutes after boot.

## Context

Build/Branch: project/widgets
Phone OS: Android
Phone model:

**Comment by kornelijepetak** [comment]
Closed by #6358
