### ISSUE TITLE
Siri Shortcuts - creating custom details shortcuts prevents you from accessing Settings again

### ISSUE THREAD

**Issue by zdericnina** [toggl/mobileapp#6347]
## 🐛 Bug Report

Once you finish creating custom details Siri shortcut, you're returned to the Timer page where the cogwheel icon is unresponsive until force quitting the app

## Context

Build/Branch: Daneel 2.4
Phone OS: iOS 13.1.3
Phone model: iPhone 11,6

## Expected behavior

User should be able to access Settings again when brought back to the Timer page

## To reproduce

1. Create a new Siri Shortcut for` Start timer with custom details`
2. Enter all the details and save it
3. Try to press cogwheel icon when brought back to Timer page

## Suggestions

The cogwheel icon becomes unresponsive like in this issue here so not sure if related:
[#6273](https://github.com/toggl/mobileapp/issues/6273)

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/24265540951)

**Comment by Odrakir** [comment]
I think this can be closed because the flow when you finish adding a shortcut has changed.
