### ISSUE TITLE
Default running time entry color is hard to see in the calendar

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6381]
It looks like this currently:
Non dark mode:
![image](https://user-images.githubusercontent.com/2173493/67792394-74c5ef00-fa4f-11e9-9f0c-52369b6761a5.png)

Dark mode:
![image](https://user-images.githubusercontent.com/2173493/67796931-3cc2aa00-fa57-11e9-9728-45a709dc70e5.png)

While are at it, here's how all default project colors look when the time entry is running:

| Non dark mode | Dark mode |
| --- | --- |
| ![color 01](https://user-images.githubusercontent.com/2173493/67793791-e737ce80-fa51-11e9-91e9-e7fe8bc093de.png) | ![color 01](https://user-images.githubusercontent.com/2173493/67796166-e0ab5600-fa55-11e9-91e9-0f757c8f101c.png) |
| ![color 02](https://user-images.githubusercontent.com/2173493/67793795-e868fb80-fa51-11e9-82ca-c73f23b2c614.png) | ![color 02](https://user-images.githubusercontent.com/2173493/67796165-e0ab5600-fa55-11e9-9a6b-b349e3ddefa4.png) |
| ![color 03](https://user-images.githubusercontent.com/2173493/67794261-befc9f80-fa52-11e9-87e2-a3a141182c5a.png) | ![color 03](https://user-images.githubusercontent.com/2173493/67796162-e0ab5600-fa55-11e9-8deb-7c7f7353cb00.png) |
| ![color 04](https://user-images.githubusercontent.com/2173493/67793797-e868fb80-fa51-11e9-9231-b7b3c6f31c0e.png) | ![color 04](https://user-images.githubusercontent.com/2173493/67796161-e012bf80-fa55-11e9-8213-292d060cd6a4.png) |
| ![color 05](https://user-images.githubusercontent.com/2173493/67793799-e9019200-fa51-11e9-9820-95b7403bdb77.png) | ![color 05](https://user-images.githubusercontent.com/2173493/67796159-e012bf80-fa55-11e9-846e-8a4efddb23b2.png) |
| ![color 06](https://user-images.githubusercontent.com/2173493/67793810-ea32bf00-fa51-11e9-9f1a-a9aadd13c1e6.png) | ![color 06](https://user-images.githubusercontent.com/2173493/67796157-e012bf80-fa55-11e9-8134-51f45ed072ec.png) |
| ![color 07](https://user-images.githubusercontent.com/2173493/67793809-e99a2880-fa51-11e9-994c-61476ad00ea0.png) | ![color 07](https://user-images.githubusercontent.com/2173493/67796156-df7a2900-fa55-11e9-832e-b0851cba6364.png) |
| ![color 08](https://user-images.githubusercontent.com/2173493/67794216-af7d5680-fa52-11e9-81d1-36518865d6ed.png) | ![color 08](https://user-images.githubusercontent.com/2173493/67796155-df7a2900-fa55-11e9-96ff-c3c0ad7042ab.png) |
| ![color 09](https://user-images.githubusercontent.com/2173493/67793807-e99a2880-fa51-11e9-9bc2-ea30caed1ef5.png) | ![color 09](https://user-images.githubusercontent.com/2173493/67796154-df7a2900-fa55-11e9-8eaf-7132ec46399a.png) |
| ![color 10](https://user-images.githubusercontent.com/2173493/67793805-e99a2880-fa51-11e9-9b2b-b749d217b1d2.png) | ![color 10](https://user-images.githubusercontent.com/2173493/67796153-dee19280-fa55-11e9-9f57-7b07f564465c.png) |
| ![color 11](https://user-images.githubusercontent.com/2173493/67793803-e99a2880-fa51-11e9-80fc-45983a82b8ac.png) | ![color 11](https://user-images.githubusercontent.com/2173493/67796152-dee19280-fa55-11e9-942c-dc06a88debdb.png) |
| ![color 12](https://user-images.githubusercontent.com/2173493/67794184-a12f3a80-fa52-11e9-86c9-89577f409b42.png) | ![color 12](https://user-images.githubusercontent.com/2173493/67796151-dee19280-fa55-11e9-9b74-dbcabc751acc.png) |
| ![color 13](https://user-images.githubusercontent.com/2173493/67793802-e9019200-fa51-11e9-9cfd-2c33abe9b7b2.png) | ![color 13](https://user-images.githubusercontent.com/2173493/67796150-de48fc00-fa55-11e9-8a7f-c2f6725a7e85.png) |
| ![color 14](https://user-images.githubusercontent.com/2173493/67793800-e9019200-fa51-11e9-86cc-8a66571098d0.png) | ![color 14](https://user-images.githubusercontent.com/2173493/67796149-de48fc00-fa55-11e9-8b39-fdbe88500ffb.png) |
| ![color 15](https://user-images.githubusercontent.com/2173493/67793793-e868fb80-fa51-11e9-8f63-184358224796.png) | ![color 15](https://user-images.githubusercontent.com/2173493/67796148-ddb06580-fa55-11e9-9b7a-a542640e8e3e.png) |

**Comment by daividssilverio** [comment]
pinging @AlicjaSuska  and @toggl/random-android-dev for opinions.
@amulware @maritoggl @sofokli1  ➿ and decisions about fixing/doing something with it now?

**Comment by maritoggl** [comment]
I think it's fine. The running entry doesn't need to be toooo prominent. Although I do see issues with colors 12, 13 and 15 where the font color doesn't match the outline/project color - I'd go about improving that situation instead.

**Comment by daividssilverio** [comment]
@maritoggl 
> Although I do see issues with colors 12, 13 and 15 where the font color doesn't match the outline/project color - I'd go about improving that situation instead.

That was intended, since those colors are almost unreadable in dark mode, I made them white when the contrast it too low.

Here's how they look when the project colors are used. Please note that how you see on the monitor isn't how you'll see on a device, your monitor is probably brighter and much bigger than most mobile devices.

![Screen Shot 2019-10-30 at 4 49 44 PM](https://user-images.githubusercontent.com/2173493/67897941-c052c880-fb35-11e9-8031-92850d7c2c57.png)
![Screen Shot 2019-10-30 at 4 50 21 PM](https://user-images.githubusercontent.com/2173493/67897944-c21c8c00-fb35-11e9-93e1-6bbda06d873b.png)
![Screen Shot 2019-10-30 at 4 49 05 PM](https://user-images.githubusercontent.com/2173493/67897948-c3e64f80-fb35-11e9-85fb-131d7681e6db.png)

**Comment by heytherewill** [comment]
As per [internal discussion](https://toggl.slack.com/archives/C02APMYTM/p1574340111016200), I'm closing this until we figure out a way to improve our colors and dark mode
