### ISSUE TITLE
Some contextual actions take too long to finish and there's no progress indication

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6384]
![slow-close 2019-10-29 14_41_13](https://user-images.githubusercontent.com/2173493/67798588-2b2ed180-fa5a-11e9-99ed-63c22434b3ff.gif)

The app looks unresponsive when you press some actions, namely all actions that don't involve navigation. It's possible to execute other actions while the first action doesn't complete.

What should we do? Simply early closing the menu helps with the look and feel of the view, but the effect of the menu action would take some time to complete e be rendered.

Displaying some sort of progress indicator is also an option.

**Comment by daividssilverio** [comment]
pinging @sofokli1 @maritoggl ➿  and decisions.
pinging @toggl/random-android-dev and and @AlicjaSuska for opinions.

**Comment by heytherewill** [comment]
Did you profile what is taking long? Is it database access? Can this be sped up in any way so we don't need the makeup?

**Comment by daividssilverio** [comment]
@heytherewill no, but will do o/

**Comment by daividssilverio** [comment]
Oh noes... there's some side effect happening somewhere that slowed down the actions during my initial tests... they stopped happening for me 😱  ... not cool...

**Comment by maritoggl** [comment]
I'm with Will here. If it's slow, let's try to address the slowness first. If we can't figure it out, let's come back to it and see how we can improve the experience.

**Comment by daividssilverio** [comment]
So. I've added stopwatches in our interactors to see what is going on.
I guess it's no surprise to what's going on... actions that involve IO take longer (several hundred ms) and that's it.

For the `CreateTimeEntryInteractor`, the call that takes longer to complete is:
```cs
var createdTimeEntry = await dataSource.TimeEntries.Create(timeEntryPrototype);
```

For the `StopTimeEntryInteractor`, the heavy statement is:
```cs
var updatedTimeEntry = await timeEntry
                    .With((long)(stopTime - timeEntry.Start).TotalSeconds)
                    .UpdatedAt(timeService.CurrentDateTime)
                    .Apply(dataSource.Update);
```

For the `DeleteTimeEntryInteractor` is:
```cs
await dataSource.Update(timeEntry);
```

**Comment by daividssilverio** [comment]
So... I guess we can simplify things up by closing the contextual menu before the actions complete.

While the actions is running we could show some progress indicator of some sort. Not sure where, maybe a horizontal bar at the top of the view... or a simple loading bar (which can be annoying).
If something bad happens, we can flash the users with some error messages afterwards.

I'm gonna create a test build and let others test and leave their opinions on this matter. @maritoggl @toggl/androids opinions wanted.

**Comment by daividssilverio** [comment]
Reopening this, during the tests done on the 2.10 test phase, changes made to calendar items took a lot to execute. It's quite slow (stuff like save, stop, delete, the changes made from the edit view)

**Comment by daividssilverio** [comment]
@semanticer , moved it to the `To-do` kanban as I wasn't actually working in this issue. It was reopened and I was assigned to this issue before. You might want to re-schedule it.
