### ISSUE TITLE
Update the manual test template with Widgets manual testing steps

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6392]
I have created this issue to update the manual test template with the manual testing steps for Widgets.

I did not do that immediately because I first want to go thru testing so that I can make the list complete.

Until then, this issue serves to me as a reminder and an actionable.

**Comment by juanlaube** [comment]
@kornelijepetak I did this in #6427, feel free to add anything else you consider important or close this issue.

**Comment by kornelijepetak** [comment]
In light of this Juan comment above, closing the issue.

**Comment by simonrozsival** [comment]
☝️ I linked this issue by mistake.
