### ISSUE TITLE
Investigate Intercom API

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6393]
Investigate how to send users' feedback straight into Intercom using their API, which would allow us to send more metadata and attach log files.

We currently use a v9 endpoint to submit feedback: #2443

Create a summary of the investigation and after an internal discussion, create follow-up issues with the next steps we will agree upon.

**Comment by amulware** [comment]
Consider:
- the user's message body
- meta data attachements like we already have (but can we send them in a way that they show up nicer for support in one of those side bars in intercom?)
- attaching files (do different file types work differently? we might want to use it for screenshots, etc. in the future)
- attached file size limits
- other limitations
- possible extensions to a full intercom chat integration in the future
- anything else that seems possible relevant

**Comment by amulware** [comment]
I'm gonna add some more requirements here (feature creep!):

I'd also like us to look into Intercom's 'mobile push' feature, which would be another way of sending messages to our users remotely, and might be something interesting for Marketing.

There's some resources here: https://www.intercom.com/help/en/articles/3292847-get-started-sending-mobile-push-messages

I'd like to know what's possible, and how much integration with Intercom would be needed to make it work.

And while we're at it, let's see how much effort it would be to 'fully' integrate with Intercom in our app, and let users see their support threads, etc. Check how much is possible with Xamarin, and how much it might add to our app size as well, please.

Depending on what we find out, we could consider using Intercom for a lot of functionality we have to write ourselves right now.

**Comment by amulware** [comment]
Ping @vedr4n for ➿

**Comment by simonrozsival** [comment]
- Intercom provides a .NET library for its API: https://github.com/intercom/intercom-dotnet
- BE implements our endpoint just by sending an email on behalf of the user to "support@toggl.com" (https://github.com/toggl/toggl_api/blob/master/src/code.toggl.com/api/feedback/mobile_feedback.go)

**Comment by simonrozsival** [comment]
We can only attach images to a conversation and even then we must host the file somewhere ourselves and only post the URL to the image.

That means that we can always upload the log to Firebase and then add the link inside of the body of the message.

**Comment by simonrozsival** [comment]
### Full integration
- it is possible to integrate Intercom into mobile apps using their ~open-source~ libraries: https://github.com/intercom/intercom-android + https://github.com/intercom/intercom-ios
- I found some unofficial Xamarin bindings, but all of them are outdated and they're not maintained
- it would be possible to create our own binding, or use an some of those random-guy-on-the-internet old ones, but that doesn't seem to be very future-proof or reasonable to me
- Intercom's 'mobile push' feature uses FCM and it doesn't seem to offer anything other than a nice UI, from which you can send the notifications (that would be awesome for the mobile marketing team as they could send notifications to our users, but it wouldn't give us any advantage over FCM. If we wanted to send a nicely formatted PN to everybody after a release telling them that we have a great new feature, then we can already do that with FCM (we shouldn't do it because users won't like it, but we could do it). 

## My conclusion:
- integration of Intercom into mobile apps is possible in general
- integration of Intercom into Xamarin mobile apps doesn't seem feasible and maintainable

**Comment by simonrozsival** [comment]
- Current Intercom SDK version is `6.0.0` (both iOS and Android, 2 months old)
- Xamarin bindings:
    - https://www.nuget.org/packages/Intercom.Sdk/ (https://github.com/drungrin/Intercom.Sdk) - built for `3.0.15`
    - https://github.com/nventive/Binding.Intercom - built for `4.1.7` (Android) and `4.1.9` (iOS)
    - https://github.com/lipka/intercom-ios-xamarin - built for `3.0.22`

**Comment by amulware** [comment]
Looks like a dead end. Unfortunate.
