### ISSUE TITLE
Investigate custom parameter reporting in firebase/appcenter

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#6420]
We track some numerical data (for instance #6152). The problem is that it's hard to actually do anything with this data, as the event values we send from the app are always strings. It makes it hard to answer questions like: "what percentage of users has password of length > 5", or to produce nice graphs, etc.

We should investigate if sending numbers for events that emit numerical data would be beneficial. That is, if we do it, will we be able to actually produce graphs, or do some filtering on the data in Firebase/AppCenter/BigQuery? 

Firebase [for sure supports](https://support.google.com/firebase/answer/7397304?hl=en&ref_topic=6317489) custom parameter reporting with two data types - text/number.

A bit more context: [slack](https://toggl.slack.com/archives/C02APMYTM/p1572520867021200).

**Comment by amulware** [comment]
Firebase custom parameter reporting is horrible - or I really don't get it. BigQuery, which we now integrate with should allow us to answer any such questions however.
