### ISSUE TITLE
Glitch in the wheel view

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6424]
## 🐛 Bug Report
There's a glitch in the wheel view when opening it from the start view, the duration in the center and the handles tick every second, see [this video](https://github.com/toggl/mobileapp/files/3795007/RPReplay_Final1572541463.MP4.zip) for more details.

## Context

Build/Branch: iOS 2.5
Phone OS: iOS
Phone model:

## Expected behavior
It shouldn't tick.

**Comment by simonrozsival** [comment]
I added a `Debug.WriteLine(endTime);` to `WheelForegroundView.cs:58` and this is what I'm getting:

```
12/16/2019 1:01:43 PM +00:00
12/16/2019 1:01:00 PM +00:00
12/16/2019 1:01:44 PM +00:00
12/16/2019 1:01:00 PM +00:00
12/16/2019 1:01:45 PM +00:00
12/16/2019 1:01:00 PM +00:00
12/16/2019 1:01:46 PM +00:00
12/16/2019 1:01:00 PM +00:00
12/16/2019 1:01:47 PM +00:00
12/16/2019 1:01:00 PM +00:00
12/16/2019 1:01:48 PM +00:00
12/16/2019 1:01:00 PM +00:00
```

... so I guess I'm on the track of the problem. That should be easily fixable.
