### ISSUE TITLE
Stopping a time entry from the widget is not working

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6428]
## 🐛 Bug Report
As the title says, stopping a time entry from the widget is not working.
## Context

Build/Branch: release/ios-2.6-grapefruit
Phone OS: iOS
Phone model:

## Expected behavior
Pressing the stop button should stop the running time entry.

## Suggestions
My guess is this has something to do with the API refactor of Observables into Tasks and the conflicts after merging the widgets into develop.

**Comment by dshr** [comment]
Fixed in #6426
