### ISSUE TITLE
Siri. Can't differentiate shortcuts in Shortcuts app

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6443]
Plain start timer and every other custom start timer shortcut are named just "Start timer" which makes them impossible to differentiate in the shortcuts app.

![image1](https://user-images.githubusercontent.com/724743/68108870-5ba6bd80-fee9-11e9-920f-069c9521378b.jpeg)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24372195205)
