### ISSUE TITLE
Siri. Wrong error when trying to stop a timer from Shortcuts

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6444]
This only happens when running the shortcut from the shortcuts app. It's ignoring the custom response text, so the user doesn't know it's failing because there's no entry running.

We might want to consider set this as a success response instead... 🤔 

![image0](https://user-images.githubusercontent.com/724743/68109168-28b0f980-feea-11e9-9383-669c88623c6e.png)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24372195205)

**Comment by Odrakir** [comment]
I'm afraid there's nothing we can do about this for now. It seems to be a bug (or feature) in Apple side: https://openradar.appspot.com/49841875

I do suggest, though, we further implement improvements to Siri Shortcuts with the new stuff on iOS 13. Maybe we don't need to error out for some specific errors (like trying to stop when there's no entry running)
