### ISSUE TITLE
Introduce entity classes in Toggl.Shared

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6448]
In our ever going effort to make the Spanish contingent of Toggl happier by removing interfaces from the app, our entities are the next target!

We need to create one class for each entity type. e.g.: we shall introduce a `TimeEntry` type and the type should have the same fields as an `IDatabaseTimeEntry`, but it should not implement that interface! It will have a `Workspace` rather than an `IDatabaseWorkspace`, for example.

These types won't be used anywhere for now, but will in the future

The documentation for the queries project can be found [here](https://www.notion.so/toggl/Realmoval-part-one-Queries-2870434ba3eb4c8b80e18f22f95828a6)

**Comment by simonrozsival** [comment]
I realized quite quickly that I need some more information to work on this issue:
- What should the constructors of these classes look like? Should they have a "copy constructor", or a constructor with an argument for each individual property? Or should we just forget about constructors for now, and deal with it later?
- You say "[it] should have the same fields as an 1IDatabase*`", this interface inherits from the `Toggl.Shared.Models.I*` interface. Therefore it has both properties like `long WorkspaceId` and `(IDatabase)Workspace Workspace`. I suppose we should drop the ID-referencing members, and keep only references to other objects, am I right?

**Comment by heytherewill** [comment]
Very late response to Simon:

- Let's stick to constructors that make the object complete. Ideally these objects would be records, so let's make it as hard as possible to create invalid objects by not having empty constructors. Let's think about copy methods later.
- I think these should have only actual references and not id references, yes
