### ISSUE TITLE
Add an Option type

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6451]
Can we even call ourselves software developers in the 21st century without using superior these functional constructs???????

**Comment by simonrozsival** [comment]
Do you want to add a custom implementation, or do want to use a Nuget package (https://www.nuget.org/packages/Option/)?

**Comment by simonrozsival** [comment]
Paul suggested copy&pasting the code from: https://github.com/beardgame/utilities/blob/master/Bearded.Utilities/Core/Maybe.cs

**Comment by heytherewill** [comment]
I'd use `Some` and `None` instead of `Just` and `Nothing`, but other than that I have no objections
