### ISSUE TITLE
Introduce a DTO for the Stop time entry query

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6454]
This type must be added to the `Toggl.Storage` project.

With the queries project, we wanna make the types in our database more reasonable. With that in mind, we wanna introduce DTOs that are unable to express invalid states.

This DTO needs to have the stop time for the time entry and the current time (for updating the at timestamp). We need to figure out whether we wanna pass the ID of the TE we wanna stop to avoid race conditions. Pinging @amulware and @simonrozsival for ➿ reasons

For more info, please check the documentation for the queries project which can be found [here](https://www.notion.so/toggl/Realmoval-part-one-Queries-2870434ba3eb4c8b80e18f22f95828a6)

**Comment by amulware** [comment]
We definitely want to include the ID. We shouldn't blindly stop, without knowing if there is something to stop I think.
