### ISSUE TITLE
Introduce a DTO for the continue time entry query

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6459]
This type must be added to the `Toggl.Storage` project.

With the queries project, we wanna make the types in our database more reasonable. With that in mind, we wanna introduce DTOs that are unable to express invalid states.

For this DTO in particular, no invalid states means that the DTO should contain a time entry id and whichever other fields are needed for continuing (like the current date for adding at stamps)

For more info, please check the documentation for the queries project which can be found [here](https://www.notion.so/toggl/Realmoval-part-one-Queries-2870434ba3eb4c8b80e18f22f95828a6)

**Comment by amulware** [comment]
Should the current date really be part of the DTO? Shouldn't that be taking from the time service in the queries?
