### ISSUE TITLE
Include information about support being available only in English

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6466]
We are slowly starting to localize our app.

However, that fact alone can cause the users to attempt to request help from support in non-english languages. While our support indeed can talk various languages, the official support language is English and that is the ONLY language that is available for communication when users are contacting the support.

**Task:** So, we need to include such a note in the Feedback form (or some other place @maritoggl decides) so that we avoid polyglottic problems.

@maritoggl, please provide information about:
* Where to put such note
* What is the exact wording we should put there.

**Comment by maritoggl** [comment]
Our current `Submit feedback` form in iOS has the title `Contact us` and in Android `Submit feedback`. Let's change the title of both forms to `Submit feedback`.
After the title, the following text is presented on both platforms:
`Let us know what you think. Send us your feedback and questions.` 
Android also has an additional placeholder `Your message` <- is that necessary? If yes, so be it.

I would simply add an extra disclaimer a few lines below the `Let us know..` and `Your message` texts that says `PS. While we do our best to help our customers all around the world at all times, our customer support team currently operates in English only. Sorry for any inconvenience this may bring about!`

@vedr4n would you be ok with such a message?

**Comment by vedr4n** [comment]
The message is relatively long, not quite sure how it will look on the page. Assuming it looks fine, it can stay as-is. 

If it needs to be shorter just cut it to: `PS. Our customer support team currently operates in English only. Sorry for any inconvenience this may bring about!`

**Comment by amulware** [comment]
Shorter means more people will read it, I think that's the way to go.

**Comment by maritoggl** [comment]
Fine by me!

**Comment by maritoggl** [comment]
Sounds good to me!

**Comment by heytherewill** [comment]
Should the note itself be translatable or left in English only? 🤔 

IMO we should translate it, but I'm asking for sanity check

**Comment by simonrozsival** [comment]
It could be useful to include a 🇬🇧 flag to attract attention of the user. I'm not sure I would read the whole placeholder text before I started typing at which point it would disappear.

**Comment by maritoggl** [comment]
> Should the note itself be translatable or left in English only? 🤔
> 
> IMO we should translate it, but I'm asking for sanity check

I would avoid making any exceptions in our apps regarding translatability. As a rule, all the strings we use should be translatable, and this applies here as well. 

> It could be useful to include a 🇬🇧 flag to attract attention of the user. I'm not sure I would read the whole placeholder text before I started typing at which point it would disappear.

Let's test and see. If this continues to be an issue for support, we can consider testing if a flag or anything else would improve the situation.

**Comment by amulware** [comment]
Not sure if a 🇬🇧flag would potentially annoy 🇺🇸people.. 🤔
