### ISSUE TITLE
ModalPresentationController - iOS 2.5 crash on devices with smaller screen sizes (SE, 7, ...)

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6470]
## 🐛 Bug Report
The app crashes when user starts a new TE or when they open the submit feedback form - whenever the `ModalPresentationController` tries adjusting the frame of the modal view:

`ModalPresentationController.get_FrameOfPresentedViewInContainerView ()`
`SIGABRT: '40' cannot be greater than 20.`

AppCenter: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/4031421413u
Intercom sample: https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24409243186

## Context

Build/Branch: 2.5 release
Phone OS: iOS 11 and 12
Phone model: iPhone SE, 6, 7, 8

Just by looking at the crash reports, it's apparent that there's a problem in older versions of iOS. There is no report from iOS 13 (you can look at this list in more detail in AppCenter:
![obrazek](https://user-images.githubusercontent.com/374616/68279031-dd762280-0072-11ea-9028-790c6e2f8438.png)

## Expected behavior
The app does not 💥 

## To reproduce
- Use iOS 11 or 12 on an iPhone with small screen (not an X*)
- Start the app
- Tap the "play" button
- The app should crash

## Suggestions
This was probably introduced by the changes in #6323, so I'd suggest stepping into the method with a debugger and checking what's different between iOS 13 and the older iOS versions.

**Comment by simonrozsival** [comment]
Oh and my guess is that it's because of the "tall" status bar height in older iOS versions - you have to have like a hotspot or be on a call for the app to crash.

**Comment by amulware** [comment]
Should this be closed? Also please add it to the release this was fixed in.

**Comment by simonrozsival** [comment]
This bug was fixed in the 2.6.1 release.
