### ISSUE TITLE
PN+Widgets: The widget is not reloaded when the app receives a PN

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6489]
We must tell the widget that the data reloaded. The `IWidgetService.Start` method should be called before syncing starts in `SyncJobService.runSync` so it can observe the running time entry changes. The widget service will subscribe to the data source changes and notify the widget when the running time entry changes.

**Comment by simonrozsival** [comment]
We should also notify the widget when the app runs background sync, as in #6493
