### ISSUE TITLE
Add ReportsDateRangeParameter class and rename ReportsSource

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6496]
### **🎯 What needs to be done?**
Refactor some of the previously used classes:
* Add a new class `DateRange`, which is similar to `ReportsDateRangeParameter` but without the `source`; just a simple class that will represent the date range.

* Rename a `ReportsSource` into `DateRangePickerShortcut`.

_`ReportsDateRangeParameter` will be removed in another issue. Let's leave it there until we are ready to take out the old reports to avoid constant build issues._

### **📝 Detailed explanation**
The existing `ReportsDateRangeParameter` leaks out some abstractions. It used to inform the view model that a shortcut was tapped. Then the view model would change the selected time range accordingly. This will no longer be the case. The coordination between the shortcuts and the selected range is an implementation detail belonging to the newly created `DateRangePicker` control `(☑️ insert issue here)`.

The second change is related to the fact that we are tracking the shortcuts usage, so for the purpose of metrics, the `DateRangePicker` will output the selected shortcut. Since this control may not necessarily be related to reports per se, there's no need for it to reference reports in its name.

### **👕 Estimated complexity**
`EXTRA SMALL`

### **🖼 Express your sentiment towards the issue**
![image](https://user-images.githubusercontent.com/7033216/68462184-52309480-020c-11ea-8bba-f73f8c37c946.png)

**Comment by heytherewill** [comment]
A class to represent date ranges [already exists in our codebase](https://github.com/toggl/mobileapp/blob/develop/Toggl.Shared/DateTimeOffsetRange.cs)

**Comment by kornelijepetak** [comment]
I wasn't aware of that.
Effectively this invalidates this issue. The rename can be done as part of another issue.
_Closing_.
