### ISSUE TITLE
Null reference in AppDelegate.OpenUrl

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#6501]
## 💥 Crash Report
It's the most common crash in iOS 2.6, based on the stacktrace, it seems to be related with Google login.

### 👥 Impact
So far it happened 7 times to 3 users, with these numbers, it's not worth to do a hotfix, but would be awesome some fix it for future releases.

### 🔗 Context
Similar to [this](https://github.com/toggl/mobileapp/issues/5620) issue that was closed because the crash didn't happen anymore.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3332260094u/overview

### 📝  Exception & Stack Trace
`AppDelegate.OpenUrl (UIKit.UIApplication app, Foundation.NSUrl url, Foundation.NSDictionary options)
SIGABRT: Value cannot be null. Parameter name: sourceApplication`
```cs
SignIn.HandleUrl (Foundation.NSUrl url, System.String sourceApplication, Foundation.NSObject annotation)
AppDelegate.OpenUrl (UIKit.UIApplication app, Foundation.NSUrl url, Foundation.NSDictionary options)
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate)
UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName)
Application.Main (System.String[] args)
```

**Comment by simonrozsival** [comment]
This crash appeared in older versions as well, here's 2.5 log: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/1649730472u/overview

**Comment by simonrozsival** [comment]
It seems to have started in 2.5: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/search?q=OpenUrl&searchType=all

This could be caused by the fact that it was build with Xcode 11. It seems to appear only on iOS 13.

**Comment by simonrozsival** [comment]
I found this:
- https://forums.developer.apple.com/thread/119054
- https://forums.developer.apple.com/thread/119118

**Comment by juanlaube** [comment]
Also it looks like the `HandleUrl` method in the Google Sign In SDK dropped all the parameters except for the url, see the reference [here](https://developers.google.com/identity/sign-in/ios/reference/Classes/GIDSignIn#-handleurl:), I'm not sure if that's available in Xamarin yet though.
