### ISSUE TITLE
Create a row type for Report Summary

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6521]
### **🎯 What needs to be done?**
Create a row type for Reports Summary.

### **📝 Detailed explanation**
This requires no user interaction. It simply shows:
* Total tracked time
* Ratio of billable time

### 🎨 Graphical resources
You can find the [designs at Zeplin](https://app.zeplin.io/project/5a0d3cd27a75add1a8924f6e/screen/5a8613eca212ab0471a3def0).

### **🛠 Technical remarks**
Utilize the view model created in #6502 

### **🏆 Outcome**
The reports now show the correct total tracked time and the appropriate billable ratio.

### **👕 Estimated complexity**
`SMALL`

**Comment by pdrj** [comment]
Modifications to the Zeplin design: don't display graphics under the numbers.
