### ISSUE TITLE
Suggestions and log view: fade out long descriptions/projects/tasks/clients

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#653]
This applies both: suggestions and log view

![toggl - ios - log 1x](https://user-images.githubusercontent.com/5064445/30970942-35e5dc9c-a46f-11e7-912f-510ef9f171cc.png)

**Comment by willsb** [comment]
Question: How will that play along with the `needs sync` indicator? The sync failed icon replaces the play button, but the needs sync icon will overlap with the description/project name if those are too big

**Comment by pe0ny** [comment]
@willsb You're correct. I updated zeplin file and made the faded are a bit wider. Now needs sync fits as well. :)
