### ISSUE TITLE
The wrong message is shown when logging in with invalid credentials

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#6538]
## 🐛 Bug Report
When logging in with an invalid e-mail and password combination, the generic error message is shown instead of "Password and/or e-mail is wrong".

## Context

Build/Branch: iOS 2.7
Phone OS: iOS 13
Phone model: iPhone X

## Expected behavior
Incorrect e-mail & password combination should show an error message along the lines of "Password and/or e-mail is wrong".

## To reproduce
Just try logging in with gibberish e-mail and password.

**Comment by simonrozsival** [comment]
A fix was merged into a release branch.
