### ISSUE TITLE
Fix the contrast (Or border) of running TE in dark theme

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6542]
## 🐛 Bug Report
We have lost the border between the running TE view and the rest of the list view: 
![MainFragmentDark (1)](https://user-images.githubusercontent.com/535613/68681647-0a8b6f00-0564-11ea-843b-4ac5b0dc3187.png)
This is solved with a shadow in our light theme but in dark themes, this is usually solved by extra border or slightly brighter background-color as described here: https://material.io/develop/android/theming/dark/ in "Elevation Overlays"

## Suggestions
If we want to solve this using "Elevation Overlays" we first need to solve https://github.com/toggl/mobileapp/issues/5829 to get access to proper Overlay tools

**Comment by heytherewill** [comment]
Putting this `on-hold` until #5829 is closed
