### ISSUE TITLE
Calendar selection breaks after editing an event

### ISSUE THREAD

**Issue by mattladd34** [toggl/mobileapp#6547]
## 🐛 Bug Report
If a user selects calendar(s) to add to the app, edits an event/saves, then attempts to access the calendar settings again, user is told "Oops - It looks like you don't have any calendars."

## Context
Initially reported by two users stating that this was happening with Outlook calendars.  Tested myself with different calendar providers and was able to replicate the issue.

Intercom Convos:
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3560471/conversations/24514040771
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3560471/conversations/24511624425

Build/Branch: 2.6.1 (2060100)
Phone OS: iOS 13.2, iOS 13.1.3
Phone model: iPhone X, iPad (6th Gen.) both on 13.2, iPhone 12,5 (From feedback form--unsure if this refers to an 11 Pro, Pro Max, etc.) on 13.1.3

## Expected behavior
User should be able to continue to select calendars to utilize in the Toggl app after editing an event.

## To reproduce
Via Calendar tab, click settings gear in top right and select a calendar to show
Tap on an event and save it
Tap on settings gear again, receive error message.  Video below.

https://toggl.slack.com/archives/C029WU7AY/p1573592501022200

## Suggestions
Force closing the app and restarting it resolves the issue, at least until you edit/save an event again.

**Comment by nicktoggl** [comment]
Just adding a link for intercom reference [Case ref](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24511624425)

**Comment by nicktoggl** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24514040771)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24532951130)

**Comment by nidarasheed** [comment]
[Case Reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24536466387)

**Comment by nicktoggl** [comment]
For reference it should be fixed in v2.7 according to Slack

**Comment by mattladd34** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3560471/conversations/24557529298)

**Comment by mattladd34** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24589445180)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24586037707)

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/24627323983)

**Comment by nidarasheed** [comment]
[Case Reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24631033825)

**Comment by daividssilverio** [comment]
Hey @arturs105 do you know if this has been fixed on iOS 2.7?

**Comment by mattladd34** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3560471/conversations/24649358424)

**Comment by VeljkoTN** [comment]
[case reference](https://github.com/toggl/mobileapp/issues/6547)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24874431831)

**Comment by VeljkoTN** [comment]
Hey guys, just wondering if there are updates here?

**Comment by VeljkoTN** [comment]
This one is no longer reproducible with the cogwheel on the calendar section taking you to general settings

**Comment by Odrakir** [comment]
Yeah, this doesn't happen anymore, the flow has changed and nothing like described happens now. I'm closing it.
