### ISSUE TITLE
Resetting password does not work

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#6550]
## 🐛 Bug Report
Tried resetting the password for the account with may main e-mail address. The first time the app showed "great success", however no e-mail arrived. Tried repeating it and then got an error in the password reset screen: "sorry, we're having trouble resetting your password".

## Context

Build/Branch: iOS 2.7 from Testflight
Phone OS: iOS 13
Phone model: iPhone X

## Expected behavior
An e-mail should arrive with a link to reset the password

## To reproduce
1. Go to the reset password view
2. Enter your e-mail
3. Press the "Reset Password" button

**Comment by simonrozsival** [comment]
Does it work well in the web app? This might also be a backend problem.

**Comment by arturs105** [comment]
😅 My bad - the Mail app on my computer had improperly configured "toggl whitelist" filter. This is working after all.
