### ISSUE TITLE
Calendar hour marks should be right-aligned

### ISSUE THREAD

**Issue by maritoggl** [toggl/mobileapp#6553]
Currently, the hour marks in calendar view are left-aligned, which makes the list of hours visually wonky (compare 9am to 10am for instance). Right-aligning the hour marks would look better - let's improve that. 

![IMG_A6F3F175BA32-1](https://user-images.githubusercontent.com/35216651/68770489-ea74b200-062e-11ea-9bca-9f87bf72c826.jpeg)

**Comment by simonrozsival** [comment]
Add some spacing to the right, this looks weird:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/374616/71544127-6b87ce80-297b-11ea-8310-f74a5b715e09.png">
