### ISSUE TITLE
The reports view break after changing Dark mode settings

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6564]
How to replicate:
1. Open the reports view
2. Select some valid period with data
3. Change the dark/night mode setting
4. When you come back to the reports view, it will be broken

**Comment by semanticer** [comment]
Maybe we can wait for @kornelijepetak 's refactor and make sure this is addressed.

**Comment by pdrj** [comment]
I tested it and it no longer happens on our project branch. I'll take a look again once we have every element displayed on the page (we're missing calendar picker only - adding it should have no effect on this bug).

**Comment by pdrj** [comment]
Tested again - this no longer breaks.
