### ISSUE TITLE
The first two colours in the edit duration wheel look the same on Dark mode

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6565]
The first two colors of the the edit duration wheel look almost the same in Dark mode.

How to replicate:
1. Set your device to dark mode
2. Open the edit view
3. Open the edit duration view
4. You should see how the first two rings of the edit duration wheel look almost the same (very whitey)

**Comment by heytherewill** [comment]
I've pinged designers internally, but I'm also pinging @amulware here for ➿ and decision making. This issue is quite easy to fix, so I don't wanna keep it blocked for too long

**Comment by amulware** [comment]
Can you add screenshots for chinese phone users?

**Comment by heytherewill** [comment]
![Screenshot_20191119-114846](https://user-images.githubusercontent.com/7688727/69156856-d8799000-0ac2-11ea-9bbb-9c273dceb4af.png)

![Screenshot_20191119-114853](https://user-images.githubusercontent.com/7688727/69156839-d3b4dc00-0ac2-11ea-81a2-30f865ba7ff2.png)

**Comment by heytherewill** [comment]
I propose we just 🔥 the offending colors and get this over with, but the best solution would be figuring out colors that work in both themes. That would need a designer, tho

**Comment by amulware** [comment]
please show an image with the list of colours we use right now, and tell us which you propose we remove. I'll probably be fine with it, and a designer can come in later and clean things up (maybe this is even something we want to leave for the upcoming colour scheme changes).

**Comment by heytherewill** [comment]
These are the colors I'd 🔥 

![image](https://user-images.githubusercontent.com/7688727/69170429-d28ea980-0ad8-11ea-82d9-40a6e12a2a99.png)

**Comment by amulware** [comment]
I agree 75%. I think there's one other hard to see contrast between the first two yellowish colours, so I'd remove the second, instead of the third yellow.

See the image below. Problematic contrasts are arrows, circle is the one I think you missed. New matrix with new Xs included.

![IMG_F751AA75197A-1](https://user-images.githubusercontent.com/3987892/69223260-f272ab80-0b72-11ea-82b7-6c7b09b24e5b.jpeg)
