### ISSUE TITLE
RTL support isn't great on android

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6566]
Tested setting the device default language setting to Hebrew.
Here's what I found:
- adding a description, the text appears on the left of the screen; as you type, the cursor stays still and the characters are added to the right of the left edge of the sentence
- it's possible to create projects and tags alright, but they look the same as :point_up:
- all texts views in the main log appear from the left to right.

I can't really tell if there's something wrong here... how should it actually be? But comparing to other apps, the behaviour isn't the same. Pinging @maritoggl (not sure if we should do something about it for this release)

**Comment by maritoggl** [comment]
That's an interesting question you have here. At the moment, I'm actually not sure how the proper behavior should be in a situation where the app itself isn't fully translated to any RTL locale and is thus not fully localized. For the time being, I feel like as long as the app doesn't blow up when anyone is writing in RTL language and they can actually input descriptions/project names/tags properly, we should be fine and shouldn't stress too much about positioning the cursor. But that will certainly become a topic when we get to actually fully localizing the app to any RTL locale.

**Comment by daividssilverio** [comment]
@heytherewill I'd suggest moving this down in the priority queue, or even removing it from 2.9.
Maybe we should revisit this when we actually have an RTL localization. 

I'm not sure what's the correct way to go. Btw, simply replacing all `Left`s with `Start`s and `Right`s with `End`s doesn't seem to have much of an effect in our layouts for some reason...

**Comment by daividssilverio** [comment]
On hold until someone else leaves a decision or suggestion/idea.

**Comment by heytherewill** [comment]
Leaving this issue orphan until we start translating the app to an RTL language, because then we will have people who know what is needed involved.
