### ISSUE TITLE
It's possible to input non-ascii e-mails in the sign-up screen

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6570]
It's possible to login/sign up using Japanese characters for example: こころ@mailinator.com

How to replicate:
- Copy your desired e-mail using special characters to your clipboard
- Go to the sign up screen
- Paste the e-mail with special characters into the e-mail field
- type in a valid password
- Sign up

:point_up: Should we block it? Should we not? FE blocks it.

**Comment by heytherewill** [comment]
@maritoggl and @syko both confirmed [in this slack thread](https://toggl.slack.com/archives/C02APMYTM/p1573727685110500?thread_ts=1573685351.094300&cid=C02APMYTM) that mobile's behavior is correct, so I'm closing this
