### ISSUE TITLE
it's not possible to sign up with google after logging in with google once

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6572]
How to replicate:

1. Log in with google
2. Log out from the settings screen
3. Try to sign up with google from the Sign up screen
4. The account picker dialog won't appear and an error message will appear (tried to sign up with an existing account).

The account picker should appear after a logout.

**Comment by daividssilverio** [comment]
Since this does not a recent regression (happens on 2.6 at least) and it's an edge case, I'm moving it out of 2.7. @semanticer might want to include it into 2.8.

@amulware loop (might want to include it future releases).

**Comment by semanticer** [comment]
Just to add some additional info: when you try again after the first failure,  dialog finally appears as it should.

**Comment by semanticer** [comment]
This is hard to debug because google login doesn't work in debug builds, but I bet my money on the fact that we don't perform google logout during logout.

**Comment by semanticer** [comment]
This is a minor bug and it will be fixed with Aurora. Last attempt (https://github.com/toggl/mobileapp/pull/7061) didn't work anyway.
