### ISSUE TITLE
Add border or make the toolbar brighter in dark theme

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6573]
## 🐛 Bug Report
We need to add a border or make the background brighter whenever we use "raised" toolbar in the dark theme. We are raising the toolbar in multiple screens including the main screen, the calendar screen, reports or settings. 

![calendardarkedit copy](https://user-images.githubusercontent.com/535613/68844653-6bcd5280-06ca-11ea-8717-1e35da30a304.png)

## Context
Dark theme

## Expected behavior
Users should be able to see the transition between our toolbar and the rest of the content.

## To reproduce
Switch to Dark Theme
Go to Calendar 
Scroll down

## Suggestions
This is solved with a shadow in our light theme but in dark themes, this is usually solved by extra border or slightly brighter background-color as described here: https://material.io/develop/android/theming/dark/ in "Elevation Overlays"

**Comment by heytherewill** [comment]
Much like #6542, this is being put `on-hold` until #5829 is closed
