### ISSUE TITLE
Edit duration view does not confirm before discarding changes

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6582]
How to replicate:
1. Tap to edit a time entry
2. Tap Start Time, End Time or Duration to open the Edit duration view
3. Play with the wheel (make sure you made some changes)
4. Press back or the `<-` up navigation
5. You are sent back to the edit view/start view and the changes are not committed. Shouldn't destructive changes confirm intention before discarding changes?

@maritoggl What do you think?

**Comment by heytherewill** [comment]
This behavior is not wrong. The changes are only actually committed when you save *in the edit TE view*, not when you save in the edit duration view. Hence, discarding the time changes in the edit duration view is a pretty ephemeral action and doesn't need a popup.

IMO we should close this issue

**Comment by amulware** [comment]
I agree that we shouldn't do anything about this now. Instead, we should review all similar flows across the entire app and unify them (similar to what Ricardo proposed for iOS).
