### ISSUE TITLE
Siri shortcuts aren't showing up immediately

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#6587]
It takes them a second to show up. See gif below.
![siri](https://user-images.githubusercontent.com/15633003/68945216-88e04f00-07b8-11ea-88cf-d9536a961470.gif)

**Comment by Odrakir** [comment]
Retrieving the shortcuts from the shortcut center is an async operation, but it's local and it shouldn't take that long.

I can't reproduce this, is it still happening to you?

**Comment by arturs105** [comment]
Can reproduce this on the version from the App Store, however, the version in Testflight and latest `develop` does not have this issue, so it looks like it's solved.
