### ISSUE TITLE
Support `null` description for time entries

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6591]
It is possible to create a time entry with `"description": null` and our apps crash or show a blank log (I'm not sure why sometimes it's the former and sometimes the latter) when this happens.

We must check every place we work with TE description (e.g., the edit view, grouping TEs) and add the default value for `null`s.

**Comment by amulware** [comment]
Is it our app that creates those entries, or is it our API that allows for it? If the latter, we should check business docs to see if null is actually a valid value and how this should be handled correctly.

**Comment by simonrozsival** [comment]
It's the FitBit app.

**Comment by amulware** [comment]
Have you checked business docs as I suggested?
