### ISSUE TITLE
Calendar settings do not store selected calendar the first time those are selected

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#6593]
## 🐛 Bug Report
Calendar settings do not store selected calendar the first time those are selected. so first time using the calendar settings that is, when we ask for permissions. it works fine the second time though

## Context
Build/Branch: develop
Phone OS: ios (maybe android too)
Phone model: x

## Expected behavior
To keep in storage the selected user calendars from the settings (the first time).

## To reproduce
Fresh install go to settings calendar selection, give permissions and select some calendars. Hit back and done. Go back to settings and those calendars are not selected. Select again and go back and done. now those are saved if you go to the same view.

## Suggestions
Something is wrong when asking for permissions and trying to save user selected calendars, seems VM related

**Comment by daividssilverio** [comment]
That doesn't seem to be affecting android. It worked fine on 2.7.

**Comment by arturs105** [comment]
Can reproduce this on iOS 2.7 Testflight build

**Comment by sofokli1** [comment]
@arturs105 will leave it up to you to close this
