### ISSUE TITLE
Calendar destructive actions don't confirm before deleting time entries

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6600]
No confirmation dialog is shown before deleting time entries in three cases in the contextual menu actions:

1. "Discard"  for running time entry contextual menu;
2. "Delete" for stopped time entries
3. "Discard" for new time entries

Try pressing those actions and the time entry will be deleted directly without confirmations.

**Comment by heytherewill** [comment]
Discard for the new TE is not really destructive; the TE is not created unless you hit save
