### ISSUE TITLE
EditDuration event properties broken on Android

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6614]
## 🐛 Bug Report
Most of the EditDuration event properties are always false on Android.

## Context
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/analytics/events/EditDuration

## Expected behavior
The various event properties should have fractions showing 'true', but a lot of them are 100% 'false'.
See the iOS event for comparison: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/analytics/events/EditDuration

**Comment by daividssilverio** [comment]
Hey @amulware , found the problem, but android doesn't have "barrels" for the parameters 

```
BarrelStartTime
BarrelStopTime
BarrelStartDate
BarrelStopDate
```

We display time/date pickers instead, is it alright to use the same parameters to track the changes made using pickers? Or should we create new parameters just for that?

By the way, we already have: 
```
WheelStartTime,
WheelEndTime,
WheelBothTimes,
BarrelStartTime,
BarrelStopTime,
BarrelStartDate,
BarrelStopDate,
NumpadDuration
```

**Comment by amulware** [comment]
I'd use the existing parameters. It's not barrels, but both are native pickers so we should use the same parameters. The name inst great (should be 'NativePickerStartTime' or similar), but I rather not change it so it's easier to analyse historical data,
