### ISSUE TITLE
January 2020 Campaign Popup Plumbing and VM

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6616]
## 🎯 What needs to be done?
We want to add a relatively simple popup for our upcoming winter discount campaign.

This issue deals with the shared remote config, view model and metrics.

## 📝 Detailed explanation

Showing the popup:
- The popup will be disabled by default (we will enable it using a firebase remote config parameter).
- The popup will show when the main view is shown (be that on a fresh start, activation from background, or navigation from another screen in-app), **if the user has installed the app more than 48 hours ago** and **if the user has at least two time entries in the local database**.
- As soon as the popup is shown, we set a flag in shared storage that will prevent it from ever being shown again.
- There is no need to close the popup when the user leaves the app with it open (i.e. it should still be open when the user comes back quickly). However, if the app gets cleaned up in the background, we also don't have to restore the popup if it was open. I.e. we're keeping it as simple as possible.

The popup itself:
- There are two slightly different versions (Option A and Option B), with slightly different copy and a slightly different link. Which option to use will be part of the remote config parameter.
- The popup will have various images and/or text specified in platform-specific follow-up issues.
- The popup will have a call-to-action button which, when tapped, will close the popup and open a URL (specified in platform-specific issues) in the browser (NOT in the in-app browser!) 
- The popup will have a dismiss button that closes it.

Events:
- A. One when the popup is shown (with a parameter indicating what campaign this is)
- B. One when the call-to-action is hit (with a parameter indicating what campaign this is)
- C. One when the dismiss button is hit (with a parameter indicating what campaign this is)

Note that if correctly implemented, B. and C. are mutually exclusive, and B+C<=A (< because some users will close the app and lose the popup that way).

## 🎨 Graphical resources
Provided in follow up platform-specific issues.

## 🛠 Technical remarks
The firebase remote config flag will be called `January2020CampaignOption`. It defaults to `none` and can be `A` or `B` which will cause the correct option of the popup to be shown.

The shared-storage parameter will be called "ShowedJanuary2020Campaign" (I'm not sure about the canonical formatting here, feel free to change that if camel or snake case are most customary). It defaults to `false` and is set to `true` when the popup is shown. 

The new events are called:
- A. `MarketingMessageShown` with property `Campaign="january2020"`
- B. `MarketingMessageCallToActionHit` with property `Campaign="january2020"`
- C. `MarketingMessageDismissed` with property `Campaign="january2020"`

Despite the property values currently being hardcoded, this should be done in the view model, not in the event itself. We'll likely use the same event in the future for other marketing campaigns.

## 🏆 Outcome

- [x] Added remote config property, including default value, and expose it in relevant service
- [x] Added shared storage property and expose it in relevant service
- [x] Added view model with call to action and dismiss functions
- [x] Integrated view model to be shown on the correct conditions on the main view (will this work without actual views? Either way the condition to show the popup should be part of this issue)
- [x] Added all three events and called them at the appropriate points

**Comment by simonrozsival** [comment]
Question: should we only show the popup to `Free` users, or also to paid users?

**Comment by simonrozsival** [comment]
> if the user has installed the app more than 48 hours ago

We don't track this at the moment. We can of course start tracking the first time the user opens the app, but I have a simplified proposal: check if the time from last login is > 48 hours. Most people will login only once after they install the app. We can also distinguish people, who signed up using the app (unless they logged out and then logged back in). Would that be useful?

**Comment by simonrozsival** [comment]
In an internal discussion (https://toggl.slack.com/archives/C6TPBE2GJ/p1574335330033800?thread_ts=1574243248.015700&cid=C6TPBE2GJ) we agreed to show it to *all users (not just Free users)* and that we don't need the "48 hours after installing the app" condition, but it'*s enough to check for "48 hours after last login"*.

**Comment by daividssilverio** [comment]
Should the dialogs be dismissible when clicking outside of it?

**Comment by amulware** [comment]
@daividssilverio I don't think there's a need for that, with the clear dismiss button.

**Comment by daividssilverio** [comment]
Currently, it's dismissible when clicking outside @amulware. That's the default behaviour.
If we don't want that, we'll need one small update.
