### ISSUE TITLE
Display merged suggestions, time entries and rating in a flat table view

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6639]
Basically iOS UI part of https://github.com/toggl/mobileapp/issues/6083 
When https://github.com/toggl/mobileapp/pull/6628 is merged a new property in `MainViewModel` called `MainLogItems` will be available. This observable will contain suggestions, time entries and ratings merged and ready for "flat" presentation in table view.

**Comment by arturs105** [comment]
This was solved in #6785
