### ISSUE TITLE
Drawing behind the navigation bar is obtrusive when using 2-button navigation

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6674]
## ⛑️ User Support
This user had the system navigation set to use the `2-button navigation` setting.

## About the user
App version: 2.7
Phone OS: Android 10
Phone model: Pixel 2

## Expected behaviour
The device's navigation bar shouldn't be able to obstruct permanently the app's content.
When using whichever system navigation settings, the user should be able to scroll and see the content without any obstructions.

## To Reproduce
I was able to replicate this issue using an emulator accessing the Settings screen.
1. Go to the settings screen
2. Scroll all the way to the bottom of the screen
You should see this:
![image](https://user-images.githubusercontent.com/2173493/69460248-09b7c180-0d4a-11ea-9117-0d98669c2477.png)

## Suggestions
This problem has been partially fixed in develop after 2.7 was released, so I guess we just have to do whatever we did in the `CalendarView` for the settings view as well.

Here's a comparison of what we have right now:

| 2.7 | develop |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2173493/69461238-7633c000-0d4c-11ea-9f34-384051457427.png) | ![image](https://user-images.githubusercontent.com/2173493/69461262-8186eb80-0d4c-11ea-8ad1-21995315c61c.png) |
| ![image](https://user-images.githubusercontent.com/2173493/69461325-ada26c80-0d4c-11ea-8da1-b2f289ea2de3.png) | ![image](https://user-images.githubusercontent.com/2173493/69461348-b8f59800-0d4c-11ea-8779-f861271be84b.png) |

**Comment by heytherewill** [comment]
The contextual menu fix was added by #6629
Doing the same in the settings view shouldn't be hard
