### ISSUE TITLE
Run initial sync in a background thread

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6677]
Starting background sync during startup (https://github.com/toggl/mobileapp/blob/develop/Toggl.iOS/Startup/AppDelegate.cs#L116) takes non-trivial amount of time (ca 180ms on my iPhone 7, see the full report in #5954).

The reason why we trigger it during startup and not when the app reaches the main screen is to get the data from the server as soon as possible and to decrease the time the user will see old data when the app is shown. This effort shouldn't block app's startup process. It would be safe to wrap this in a `Task.Run(() => ...)` and run this in a background thread and let the UI thread initialize the rest of the app.

**Comment by heytherewill** [comment]
Already done in #5946

**Comment by amulware** [comment]
Was this done? If so, should this be closed?

**Comment by simonrozsival** [comment]
The PR which @heytherewill linked hasn't been merged yet. This issue shouldn't be closed.

**Comment by heytherewill** [comment]
Do measure whether this brings any performance benefits or not; if it doesn't just close the issue

**Comment by pdrj** [comment]
Current version:
![foreground](https://user-images.githubusercontent.com/53510080/74941102-c3c6d400-53f2-11ea-98f5-348e182ec92b.png)

Background:
![background](https://user-images.githubusercontent.com/53510080/74941105-c5909780-53f2-11ea-8dd5-2e0a1f2d41a3.png)

the 'stopwatch' time is how long the `app.ForceFullSync()` invocation took in `SplashScreen`.

I think this is good enough improvement to warrant going through with this. Do you agree @heytherewill?

**Comment by pdrj** [comment]
Numbers for a release build. The first two screenshots are for the current version, the other two have the bg sync.

![Screenshot 2020-02-21 at 10 54 56](https://user-images.githubusercontent.com/53510080/75025827-2c1dc000-549c-11ea-9576-1799aa82ce7b.png)
![Screenshot 2020-02-21 at 10 41 55](https://user-images.githubusercontent.com/53510080/75025837-2d4eed00-549c-11ea-91a8-6c6cb38321db.png)
![Screenshot 2020-02-21 at 10 48 44](https://user-images.githubusercontent.com/53510080/75025834-2cb65680-549c-11ea-827a-8eb7eb24f304.png)
![Screenshot 2020-02-21 at 10 36 15](https://user-images.githubusercontent.com/53510080/75025835-2d4eed00-549c-11ea-9a8e-c701ea617d18.png)

I didn't put this into a spreadsheet, but it seems we get about 40-50 ms speedup consistently.
