### ISSUE TITLE
Load and initialize the VMs for all tabs lazily

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6679]
Currently when the user opens the app (cold start), the `MainTabBarViewModel` is loaded. This VM creates its child VMs in its constructor (main VM, reports VM, calendar VM) and the initialization method of the VM initializes all of the tab VMs.

I think we should change this:
- we should only create and initialize the main VM during startup
- the rest of the VMs should be either created and initialized in a background thread without blocking the UI
- or we should simply load the VMs and initialize them at the first occasion when the user navigates to the tabs (the user might not go to calendar or reports every time he/she opens the app)

Since this is all `Toggl.Core` territory, we must make sure we don't break either the iOS or the Android app while we're doing this. Both of these app's performance would benefit from this change.

**Comment by daividssilverio** [comment]
This is being at least partially by #5946  @heytherewill ➿ 
Moving this to 2.11 as I don't think this will be handled during this release. I suggest the same for iOS @sofokli1
