### ISSUE TITLE
Add a Help Us Translate The App link to the settings

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6692]
## 🎯 What needs to be done?
We need to add a link to [this page](https://github.com/toggl/mobileapp/blob/develop/docs/internationalization/how-to-contribute-with-translations.md) in our app to make users more aware that our apps can be translated if they wish to help

## 📝 Detailed explanation
We need to figure out if we wanna include the link in the settings view (below the link to the about view) or if we should put it in the about view (below our terms of service). I'm pinging @maritoggl and @amulware here for decision making.

## 🏆 Outcome
A link has to be included in both apps. We should also track how often the link is being clicked to see if the discoverability of the link is good enough. This means, we should track an event (`TranslationLinkClicked`) whenever the user taps the link to open the translation link. No properties are needed, since we only want the number of clicks.

## 🖼 Express your sentiment towards the issue
![image](https://user-images.githubusercontent.com/7688727/69567219-a7540080-0f97-11ea-838b-edcd08d41ad7.png)

**Comment by amulware** [comment]
If there should be an event, add `metrics` and actually add detailed specs, please.

I'm also not sure if this issue is a question or a statement, it seems to be both, please clarify.

**Comment by maritoggl** [comment]
What do you think about adding the link behind the "Submit feedback" menu item instead? Would that make sense in your opinion or not?
So the menu would be
* Submit feedback
** E-mail support -> opens the feedback view we currently have
** Help with translations -> opens the translations guidelines

**Comment by amulware** [comment]
I don't think we should create a sub menu for only two options.
