### ISSUE TITLE
Add API token to the settings view

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6693]
## 🎯 What needs to be done?
We need to allow our advanced/h4x0r users to access their API tokens from within the app. 

## 📝 Detailed explanation
The token should be included in the settings view. A good place to add it is the `GENERAL` section of the settings view. The token should be easy to copy. Options:

A) Long pressing copies the token to the clipboard (we add some helper text so the users know how to copy)
B) Tapping copies the token to the clipboard 
C) We add a button to copy to the clipboard 

A is, IMO, the best option (since it makes it hard enough so that the user doesn't copy the token by accident while keeping the simplicity of the settings view), but I'm pinging @maritoggl for decisions.

## 🏆 Outcome
The API token has to be accessible from both apps. Also, we should track how often the API token is copied for analytics purposes:tm:

## 🖼 Express your sentiment towards the issue
![image](https://user-images.githubusercontent.com/7688727/69567266-bfc41b00-0f97-11ea-95bf-0d53ed96338e.png)

**Comment by kornelijepetak** [comment]
I vote for A 😄

**Comment by amulware** [comment]
Please add actual specifications for the event to track.

**Comment by maritoggl** [comment]
A

**Comment by amulware** [comment]
@heytherewill (or anyone else) See my request above.
