### ISSUE TITLE
NullReferenceException in CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath 

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#6722]
### 👥 Impact
Has occurred 41 times to 32 users and accounts for more than half of all crashes in iOS 2.7 (we've had 80 crashes since the release on November 20). This is by far the most common crash in 2.7, since the second most common crash has only 8 occurrences.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/137415887u/overview

### 📝  Exception & Stack Trace
`SIGABRT: Object reference not set to an instance of an object`
```cs
CalendarCollectionViewSource.LayoutAttributesForItemAtIndexPath (Foundation.NSIndexPath indexPath)
CalendarCollectionViewLayout.frameForEditingHour (Foundation.NSIndexPath indexPath)
CalendarCollectionViewLayout.LayoutAttributesForSupplementaryView (Foundation.NSString kind, Foundation.NSIndexPath indexPath)
(wrapper managed-to-native) ObjCRuntime.Messaging.objc_msgSend(intptr,intptr)
CalendarDayViewController.showContextualMenu ()
CalendarDayViewController.<ViewDidLoad>b__21_5 (System.Boolean _)
(wrapper other) System.Object.gsharedvt_out()
NSRunloopScheduler+<>c__DisplayClass2_0`1[TState].<Schedule>b__0 ()
DispatchQueue.static_dispatcher_to_managed (System.IntPtr context)
Application.Main (System.String[] args)
Application.Main (System.String[] args)
```

**Comment by simonrozsival** [comment]
Ref #5869

**Comment by juanlaube** [comment]
Closing since #6823 should solve the problem, we can reopen this issue in case the crash happens again.
