### ISSUE TITLE
Increase the hitbox of the calendar drag handle

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#6727]
It seems like the dragging only works if you hit _inside_ of the time entry rectangle, which is a shame, because the drag handles are drawn outside the bounds of the rect and should react to tocuhes there as well. Just to be clear: we don't need to increase the size of the drag handles themselves, just the hitboxes.

![Nov-28-2019 13-35-58](https://user-images.githubusercontent.com/15633003/69803218-26d60f80-11e4-11ea-962c-cfdd684d421a.gif)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24975200149)
