### ISSUE TITLE
Rewrite CalendarCollectionViewSource so that it doesn't remember indexPath

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6739]
Ref: #5869, #4886, #5432

The problem with all the crashes ☝️ is that the indexes of the items in the calendar view change over time and the `indexPath` state variable now might not point to the same item, or it can even point outside of the range of items in the collection.

The latest report is from 2.8: https://appcenter.ms/orgs/Toggl/apps/Toggl-iOS/crashes/errors/3327916630u/reports/2518272647600009999-608a2aa2-054e-437d-90db-5cf016fde339/threads

We tried preventing these crashes, but it seems pointless. We should find a better way to represent the state of the collection while editing.

**Comment by Odrakir** [comment]
I'm pretty much lost here. I can't reproduce the crashes and I'm not sure on what to do regarding the indexes. I think it's better if someone with more experience in that code checks this one out, I'm unassigning my self.
