### ISSUE TITLE
Calendar contextual menu dismissal triggers strange cell animation

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#6748]
## 🐛 Bug Report
When I close the contextual menu (bottom bar), either cancel or save, all calendar cells animate strangely, as if they start too large and have to be scaled down.

## Context
Build/Branch: 2.7
Phone OS: ios
Phone model: 11 pro

## Expected behavior
Just dismiss and maybe perform needed changes to the selected cell where the changes are performed on.

## To reproduce
Check description

## Suggestions
May be related to some reload data calls in the viewSource

**Comment by sofokli1** [comment]
@amulware if you have a video/gif for this issue, it would make it easier to fix

**Comment by amulware** [comment]
Find a screen recording internally: https://toggl.slack.com/archives/CD40QCV25/p1575282991270200?thread_ts=1575275086.269400&cid=CD40QCV25

I noticed that the effect is much more pronounced when you have multiple columns. If there's only a single column, it's just a small fade.

**Comment by Odrakir** [comment]
I'm looking at this... I see that after every change we are calling `collectionView.ReloadData`, which causes the whole thing to reload and shouldn't be necessary. Also, this is using the obsolete `ObservableGroupedOrderedCollection`, when it should be using `IObservable<IImmutableList<AnimatableSectionModel>>`.

As a matter of fact the calendar is the last piece of code still using the old class. This should be changed and it might even help with the other crashes we are getting in #6739 

But this is kind of a big change as it'll probably requiere refactoring how the calendar works entirely. Do we want to get into this now?

**Comment by sofokli1** [comment]
That is a question for @amulware ☝️

**Comment by sofokli1** [comment]
what @Odrakir proposes is related to this other issues not part of ios 2.10 https://github.com/toggl/mobileapp/issues/5997

**Comment by amulware** [comment]
I'm not sure I'm qualified to make this decision.

But what I'd do: if the flicker can be fixed relatively easily without making big changes, I'd do that for now. Then I'd create a follow up issue for the refactor and make sure @heytherewill prioritises it compared to other refactoring.

If it's not possible to fix easily/without the refactor, document that here, add `[refactoring]` and still talk to @heytherewill, with the added pressure of this relatively small glitch :D

**Comment by juanlaube** [comment]
I spent some time trying to fix this without a major refactor but every single time I made something work, I broke something else. As mentioned above, we should start using the `AnimatableSectionModel` and proper diffing instead of reloading the collection for every change. We already have the implementation for diffing in tableviews and it should be almost identical for collectionviews.
