### ISSUE TITLE
Calendar discarding changes when hitting edit in the contextual menu

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#6749]
## 🐛 Bug Report
If I change the time by dragging and then hit ‘Edit’ it resets the time I edited.

## Context
Build/Branch: 2.7
Phone OS: ios
Phone model: 11 pro

## Expected behavior
It should keep the changes made while dragging when selecting `Edit` in the contextual menu

## To reproduce
What the description says

## Suggestions
The issue here is that until we select `Save` in the contextual menu the changes made while dragging are not saved. so when selecting `Edit` we use the default edit view we use in the log too which works with its own logic on how to fetch TEs, edit and save those. So either the edit view should be refactored to work with temp data that is not saved yet, which is a pain, or **perform an actual save when the `Edit` is selected just before opening the edit view.**

**Comment by amulware** [comment]
I understand it would be easier to implement, but if we save the dragged times when the user hits 'Edit', but then they cancel twice, it will still have the change made which is maybe not ideal?

**Comment by sofokli1** [comment]
How about we ask the same way we ask for discarding changes when taping the edit button. `Do you want to keep the new start/end time?` yes, we save and open edit. no, we discard and open edit.
How does this sound?

**Comment by amulware** [comment]
That might be alright, even if just slightly clunky... @maritoggl what do you think?

Otherwise, I think we should pass the new times as some sort of optional parameters to the edit view and do it that way.

**Comment by maritoggl** [comment]
But given we _will_ be working on refactoring the edit and new time entry views in the very near future... perhaps that's something we can consider in the scope of that project as well? Working with temporary data? Even if it seems like a pain at the moment when compared to other options. 

One alternative would also be instantly applying changes upon edit but introducing an option to undo (Google Calendar works like that). 

The double confirmation would functionally work, but I do agree it feels clunky and I wouldn't yet want to take that route.
