### ISSUE TITLE
Calendar: Save, delete and continue actions are slooow

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6756]
## 🐛 Bug Report
Actions in calendar contextual menu are very slow on my Pixel device and do not provide any progress feedback. 

## Context

Build/Branch: android-2.8
Phone OS: Android 10
Phone model: OG Pixel

## Expected behavior
We have to either make these actions faster or provide the user some feedback that something is happening. We should also consider disabling all contextual buttons to not allow any other actions during loading. We may consider some loading overlay over the whole bottom sheet that intercepts all the taps or hide bottom sheet and display loading on top of the calendar view.

## To reproduce
Select random TE in calendar view
Tap on delete action
Wait
Wait
Wait
Done

## Suggestions
We should provide some loading bar and ideally also disable all contextual menu actions during that time.

**Comment by daividssilverio** [comment]
Possible duplicate of #6384

**Comment by daividssilverio** [comment]
Currently investigating to see if we can find what's the reason for that. If we can fix that instead of adding progress indicators, that would be better, right?

**Comment by semanticer** [comment]
Yes, fast is always better than loading bar 👍 
Also, you are right, I'm closing this as duplicate.
