### ISSUE TITLE
Forgotten Password: invalid email

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6759]
## 🐛 Bug Report
The button "Get password rest link" is enabled even when you enter completely invalid email like "asdsasd". The app let's you click on the button but doesn't provide any feedback and nothing happens.

## Context

Build/Branch: android-2.8
Phone OS: Android 10
Phone model: OG Pixel

## Expected behavior
The button should be either disabled until a valid email is entered or we should display some error.

## To reproduce
Go to "Forgot your password?" 
Enter invalid email like "dasds"
You can click on the submit button and nothing happens

**Comment by heytherewill** [comment]
Fixed by #6774
