### ISSUE TITLE
Forgot your password button touch target is too small

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6761]
## 🐛 Bug Report
It is quite hard to hit the forgot your password button and there is no touch feedback

## Context

Build/Branch: android-2.8
Phone OS: Android 10
Phone model: OG Pixel

## Expected behavior
Touch target should be a bit bigger and there should be some ripple effect

**Comment by heytherewill** [comment]
You mean the link in the login view?

**Comment by semanticer** [comment]
Yes the "forgot your password?" textview link in the Login screen.
