### ISSUE TITLE
Sync stuck when getting back to the app

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6766]
## 🐛 Bug Report
This morning, I opened the app (on iPad, probably doens't matter), started a time entry, and it didn't sync. A little later I came back to the app and stopped it. Still not syncing. It kept having the gray 'unsynced' icon.

When I pulled down to force sync, the syncing bar appeared, but it was gray and the spinner wasn't working. It just appeared stuck like that (I waited for at least 30 seconds).

Restarting the app resolves the issue.

## Context

Build/Branch: 2.8-1
Phone OS: iOS 13.something
Phone model: iPad Pro

## Expected behavior
Time entries should always sync promptly and the animation should never be stuck.

## To reproduce
Unclear. I suspect the app was running during the entire night and probably tried to sync in the background a couple of times. 

This or something else caused the app to get into this 'stuck' state.

## Suggestions
It would be useful if we had some sort of debug screen (even in release versions, just well hidden?) that could do things like.. tell us what sync state we are in? Or hey, maybe just having a logfile could help a lot. :D
See #6393

**Comment by simonrozsival** [comment]
With #6851 we will now be able to monitor the HTTP calls the app makes even in the production build and we will be able to see if there's an infinite loop in pull or push sync, or if there is no networking activity and sync still never finishes (e.g., if clean-up gets stuck).

**Comment by sofokli1** [comment]
@amulware still and issue or can we close this?

**Comment by amulware** [comment]
It still happens to be every now and then, but it seems much less common. I don't think looking into this is high priority. Feel free to close it, we can probably find more important things to do for a while.
