### ISSUE TITLE
🇯🇵Fix tags/project Japanese translation

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6779]
## 🐛 Bug Report
Tag and project string should be translated
![device-2019-12-04-132522](https://user-images.githubusercontent.com/535613/70144224-c04a6900-169d-11ea-9b49-5e7c2d4560aa.png)

## Context

Build/Branch: release-2.8
Phone OS: Android 10
Phone model: OG Pixel

## Expected behavior
tags and projects should be translated into Japanese

## To reproduce
Switch your phone to Japanese and start a new entry

**Comment by simonrozsival** [comment]
This is shared with iOS
