### ISSUE TITLE
Calendar smart alerts on Android seem to be broken

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/mobileapp#6792]
## ⛑️ User Support
Notifications for events are not appearing for the user, even though app and system settings show notifications turned on. 

## About the user

App version: Giskard 2.7.1 
Phone OS: Android 9 
Phone model: Galaxy S9

## Expected behaviour
Notifications should appear for events when notifications function is turned on

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/24810677703)

**Comment by maritoggl** [comment]
Replicated with moto g6, Giskard 2.8, Android 9

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24936226919)
User has the opposite problem - notifications are showing when disabled

**Comment by nidarasheed** [comment]
[User has same problem as what Diane mentioned](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/25376471754)
