### ISSUE TITLE
Enable Reports via deep links

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6821]
## 🎯 What needs to be done?
Make reports deep-linking work again.

## 📝 Detailed explanation
During the creation of the new code, the deep links got disconnected.
Make reports link work again.

## 🏆 Outcome
The reports can be reached over a deep link. Try browser, try app shortcuts.

## 👕 Estimated complexity
`MEDIUM`

**Comment by pdrj** [comment]
For Android - in case you want to test a deep link with a custom scheme, you probably won't be able to do it via chrome, or pasting it somewhere.

Instead do something like:
`adb shell am start -a android.intent.action.VIEW -d "toggl://tracker/reports?workspaceId=1&startDate="2019-04-18T09:35:47Z"&endDate="2019-04-18T09:45:47Z"" com.toggl.debug`
