### ISSUE TITLE
Returning from iOS Settings to the app does not restore settings screen

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#6840]
## 🐛 Bug Report
When I go to the iOS settings from the Calendar settings screen and then back to the app, I find myself on the main screen, not the Calendar settings screen, which is a bit strange/confusing.

If I then go to the Calendar settings screen I still get the 'maybe later?' popup if I didn't enable (or in fact DISABLED) calendar permissions in the iOS settings, so it appears to know that I got back from the settings after all - or... it just seems to show that popup every time? That's pretty confusing. If, maybe weeks after I disabled/denied permissions I go to the calendar settings screen, I don't expect to get a popup saying 'no worries' - that should only be shown if I JUST disabled/denied it.

## Context

Build/Branch: iOS 2.8
Phone OS: iOS 13.3
Phone model: iPhone 11 Pro

## Expected behavior
I expect:
- the app to still be on the settings screen if I get back from iOS settings that the app sent me to
- the 'maybe later' popup to only show if I JUST denied/disabled calendar settings (or even just in the 'denied' case)

## To reproduce
- go to calendar settings in app
- go to iOS settings from there and disable calendar access
- hit '< Toggl' in the top corner
- :x: find yourself on the main screen of the app (after a short splash screen, which is also weird to me)
- go to calendar settings again
- :x: get popup as if I just denied permissions on that screen

## Suggestions
Let's rework this flow to be nicer. If needed we can have a discussion on how it should work, otherwise go with what I said above (if you think it makes sense).

Let's maybe also check the rest of the settings for any places that lead us outside of the app to make sure they work as expected and create follow up issues.

**Comment by amulware** [comment]
Please also consider/address #5471

**Comment by Odrakir** [comment]
What's happening here is that the system kills the app after certain settings are changed, I think the same happens with camera access, for example. I don't think there's a way to prevent that.

A workaround might be to store the state of the app before sending the user to the system settings, and restore it after he's back. Although this might be a bit troublesome for something that's kind of standard behaviour in most apps.

Do we want to go down that route?

**Comment by amulware** [comment]
If this isn't very easy to do, then I'd say it's probably too much effort for a relatively minor problem for now. I'll leave that judgement to you, but don't spend too much time on it.

**Comment by amulware** [comment]
(And feel free to close this if we won't do anything about it.)

**Comment by Odrakir** [comment]
It's not hard to store/restore state. But this has some implications that would be complicated. Like: What happens if the user doesn't return immediately? Do we also go back to the calendar? What if a day has passed? 

Also, the splash screen will show no matter what, are we sure it makes sense to navigate directly to the calendar after the splash screen? Won't that make it even more confusing?

I'm closing this for now. Feel free to open it again if you have a different opinion.
