### ISSUE TITLE
Edit view: multiple tags

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#685]
When user has selected multiple tags, let's use only one row to display tags and if there are more to fit, use '...' to indicate. When user taps on '...' or on any other tag, open tag view.

![toggl - ios - edit tags 1x](https://user-images.githubusercontent.com/5064445/31326702-4a8fd6d2-acd2-11e7-8660-5533f923d343.png)

Zeplin: https://zpl.io/2vnPWw5

**Comment by arturs105** [comment]
Since this requires some modifications to `EditTimeEntryViewController.xib` and some modifications are being made to that file in #720, i'm going to postpone this until #720 is merged to avoid nasty merge conflicts in the .xib file.

**Comment by amulware** [comment]
@arturs105 What is the status on this?

**Comment by arturs105** [comment]
Have some code for this locally, though it calculates tag width/count without borders for now.
