### ISSUE TITLE
New Copy Translation Request - Text for Cancel login process when back pressed

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6869]
**Target Languages:** 
🇯🇵

**New Copies:**
```
    <data name="CancellingLoginAttempt" xml:space="preserve">
        <value>Cancelling your login attempt</value>
    </data>
```

This is now used by https://github.com/toggl/mobileapp/pull/5703/

**Comment by heytherewill** [comment]
Might not be needed if we decide not to merge #5703

**Comment by maritoggl** [comment]
Closing this for now since #5703 was closed without merging.
