### ISSUE TITLE
TE disappearing

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#687]
Reproducing steps:
1) Install the app from scratch. use test.mobile.1 account to log in
2) Start a new TE, type in ‘test’ and pick a suggestion, tap green check
3) Open running TE edit view
4) change start time, save; confirm changes
5) Open running TE edit view
6) add tags, save; confirm changes
7) you should be on timer page now; stop TE (it disappears)

**Comment by pe0ny** [comment]
Though I'm trying different combinations atm and it seems the app doesn't save new TE anymore..

**Comment by simonrozsival** [comment]
I am trying to debug this and find a way how to fix it.

**Comment by simonrozsival** [comment]
So far I have found out that this happens every time you edit a running time entry in the edit view. When you stop the time entry then, it is not added to the list and the UI stops updating so stopping any other time entry (even without any edits) won't change the UI.

Good thing is that this is only a presentational bug - the changes are persisted well and can be synced to the server.
