### ISSUE TITLE
Main Log is empty until a TE is stopped within the app

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#6873]
## 🐛 Bug Report
Right after login or after starting the app when the user is already logged in, the main log is shown completely empty. Syncing doesn't fix it (even if it fetches new TEs) and the only thing so far is stopping the running TE (either on the main screen or in the calendar screen).

## Context

Build/Branch: build 2.8.1 - `2080103` from TestFlight
Phone OS: iOS
Phone model: doesn't seem to matter

For some reason it doesn't affect debug builds.

## Expected behavior
The main log is shown as usual.

## To reproduce
Try installing the build from TestFlight.

## Suggestions
No idea.

**Comment by semanticer** [comment]
Related slack thread: https://toggl.slack.com/archives/C02APMYTM/p1577973556340400
And this is indeed most likely the same issue we encountered in https://github.com/toggl/mobileapp/pull/5832

**Comment by juanlaube** [comment]
This has to be a build setting, there is something that affects only `Release.AppStore`, I tried changing things in `Debug` using the same values from release but nothing seems to work to reproduce the bug.

**Comment by pdrj** [comment]
Bisect told me that https://github.com/toggl/mobileapp/commit/c7e0dec5461f634a59c320548b73afefa187cbc5 is to blame. Investigating further.
