### ISSUE TITLE
Decide and implement a rounding algorithm in the donuts

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6878]
## 🎯 What needs to be done?
The current donut rounds down percentages in order to show tham better on the chart. The sum does not necessarily amount to exactly 100%. Decide on the rounding algorithm and implement it.

⚠ **DECISION**. See a comment below for details on what has been decided.

## 📝 Detailed explanation
Not aware of the initial reasoning, but with the change to the donut, adding fractional digits (`.3` for example), requires much more space, making things difficult for smaller donut segments. The rounding down was chosen for legacy reasons. But they may not be the best option.

## 🛠 Technical remarks
One alternative I could propose is to not round down, but round to the closest integer and then only correct the last segment so that the total amounts to 100%. But, this is a product question, so I'm invoking @maritoggl. Also @amulware, because math.

## 🏆 Outcome
This issue is complete when there is a comment on this issue containing the decision about how to algo this into existence, and when there is a PR that actually implements that algo (if any is needed).

## 👕 Estimated complexity
`SMALL`

**Comment by kornelijepetak** [comment]
@simonrozsival proposed using [Largest remainder method](https://en.wikipedia.org/wiki/Largest_remainder_method)

**Comment by kornelijepetak** [comment]
I should also note that this should touch only the way the percentage labels **are displayed**, not correcting the underlying data!

**Comment by amulware** [comment]
This should be handled the same as we do in other clients. Please communicate with them (or let @maritoggl do so).

**Comment by kornelijepetak** [comment]
The powers that be decided that we are doing the following:

1. To each slice, assign the value equal to the `integral part` of its percentage
2. Let `N` be the sum of all those integral slices
3. Calculate `T = 100 - N`
4. Sort the slices by their fractional remainder, in descending order
5. Add `1` to first `T` slices in the above sort

---
**EXAMPLE**

Slices:

| | A | B | C | D | E |
| - | - | - | - | - | - |
| | 32.48 %|27.11 %|15.56 %|13.53 %|11.32 %|
| Integral | 32 | 27 | 15 | 13 | 11 |
| Fractional | .48 | .11 | .56 | .53 | .32 |

2. Calculate `N`
`N = 32 + 27 + 15 + 13 + 11 = 98`

3. Calculate `T`
`T = 100 - N = 2`

4. Sort by `Fractional`, descending:
`C`, `D`, `A`, `E`, `B`

5. Add `1` to first `T` elements

| | C | D | A | E | B |
| :-: | :-: | :-: | :-: | :-: | :-: |
| | ✅|✅ | | | |
| |15.`56` %|13.`53` %|32.`48` %|11.`32` %|27.`11` %|
| FINAL | 15 + `1` | 13 + `1` | 32 |11 | 27  |
