### ISSUE TITLE
Decide and implement a Reports reloading strategy

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#6879]
## 🎯 What needs to be done?
Decide what to do about refreshing the reports when getting back to it.

## 📝 Detailed explanation
When we go back to the reports screen, the data does not refresh immediately. In my opinion it shouldn't. Doing a request that potentially changes nothing is a drain on the server resources for nothing. On the other hand, detecting whether the changes to our time entries (both from tracking and from sync with the server) actually fall into the currently selected report parameters (workspace+period) is too complicated to be worth it. Maybe at the time it could be done somewhat clean, in the future, if we allow more filters/grouping (such as filter by projects/clients/tasks/tags), the autodetection of whether it needs a new request becomes too messed up (albeit not saying impossible).

Options are:
* Refresh the data whenever coming back to the reports screen (and don't care about the cost of such, in most cases, useless requests).
* Introduce pull-to-refresh to the reports to make it natural for users who use the pull-to-refresh in Main log. It refreshes the data with the previous parameters.
* Detect that something has changed and inform user on reports screen that they may be looking at the old data. Then provide a button to refresh the data (or combine this with the previous pull-to-refresh) option.
* _insert your option here_

I personally favor the third option, pull-to-refresh with a hint to the user.
Detecting that _something_ has changed is not hard. Detecting exactly whether whatever changed actually would influence the data currently shown in the reports is much much more work.

Pinging @amulware and @maritoggl for decision making purposes.

## 🏆 Outcome
The decision what to do has been made and the feature implemented.

## 👕 Estimated complexity
`MEDIUM`

**Comment by maritoggl** [comment]
Let's start with the simple pull to refresh. If we learn that users still have issues with old data, we can introduce some sort of notification as well in a later phase.
