### ISSUE TITLE
Push time entry deletion

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#688]
We use a local bool flag to indicate that a time entry was deleted. If this is pushed successfully, the entity can be deleted from the database entirely.

**Comment by simonrozsival** [comment]
This is now waiting for PR #727 to be merged.

**Comment by simonrozsival** [comment]
Now this is waiting for PR #734

**Comment by simonrozsival** [comment]
There are issues for the remaining imperfections of the whole deletion - #689 and #751, so the PR #752 should have closed this issue, instead of just referencing it. Therefore I close this issue manually now.
