### ISSUE TITLE
Ensure single running time entry when starting timer

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#690]
This has to happen inside a database transaction to ensure there are no race conditions.

If necessary we have to make sure this also works when continuing or starting a timer from suggestions, but ideally, we only have to have this logic in one place.

**Comment by simonrozsival** [comment]
This is now on hold because of a backend bug.

**Comment by simonrozsival** [comment]
So if there would be some time entry already running, it should be stopped. In the single transaction. Did I get it correctly?

**Comment by amulware** [comment]
Yap.
