### ISSUE TITLE
Gray icons look dull in dark theme 

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6900]
## 🎯 What needs to be done?
We need to make different versions of icons for dark theme or simply use a different tint color. 

## 📝 Detailed explanation
**Example from project creation screen:**
 
![dark (1)](https://user-images.githubusercontent.com/535613/72263484-3cc75480-3619-11ea-872e-53c6c26f9507.png)

All screens with this issue:
Project Creation, TE edit
Duration edit
Probably also bottom bar in start TE
Possibly bottom navigation icons in main screen

## 🎨 Graphical resources
TODO @alicjasuska 
If these icons are already in vectors, we just need a new color for dark theme

**Comment by AlicjaSuska** [comment]
![New-icon-colour](https://user-images.githubusercontent.com/20326070/73171676-95aae880-4101-11ea-9d2c-02068e327468.png)

How about using #b1b1b5? We use it as 'neutral' colour in light theme all over our app so there is'some' consistency in our style guide :P I made project icon lighter and left WS icon darker for comparison. Please, let me know if all icons are in svg and if you need any to be added to Zeplin? @semanticer

**Comment by heytherewill** [comment]
They are all SVGs, so we can easily change their colors!

@AlicjaSuska just confirming: The color of the icons should remain the same on Light Mode and we should use #B1B1B5 only on dark mode, right?

**Comment by AlicjaSuska** [comment]
Yes, change applies only to dark mode :) @heytherewill
