### ISSUE TITLE
Toolbar actions should be more prominent

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6904]
## 🐛 Bug Report
**Toolbar actions like the "Create" on the screenshot below look inactive and insignificant even though they are quite often the most important buttons on the screen**

![createaction](https://user-images.githubusercontent.com/535613/72274195-fb8c7000-362b-11ea-9f9b-d7b0f892af47.png)
We should either add some highlight color or consider full material button like google did in the Calendar app:
<img width="601" alt="Screenshot 2020-01-10 at 08 04 32" src="https://user-images.githubusercontent.com/535613/72275598-87070080-362e-11ea-9071-b69904823265.png">

We still need some input from @aicjasuska to decide which way to go.

**Comment by AlicjaSuska** [comment]
Great insight! Can we use our blue for those actions:
light theme - 2f6bdf
dark theme - 008dff

@semanticer
