### ISSUE TITLE
The wheel positioning doesn't work well on small screens

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6906]
## 🐛 Bug Report
This is how the duration edit looks on a small Nexus 5's screen
![bounds](https://user-images.githubusercontent.com/535613/72276660-bdde1600-3630-11ea-88af-c55016a534f9.png)

The position of the wheel view should be relative. It should be in the middle of vertical space between Start/End time textviews and the bottom of the screen. 

## Context

Build/Branch: develop
Phone OS: Android 10
Phone model: Nexus 5

## Suggestions
Simple constraint layout magic should do the trick

**Comment by daividssilverio** [comment]
@semanticer  Actually, as far as I remember, the idea was to have it near to bottom of the screen to make it easier to handle on longer/bigger displays.
