### ISSUE TITLE
Slight settings redesign 

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#6908]
## 🎯 What needs to be done?
Currently, the settings view looks a bit odd when you look at these gaps. Every gap functions as a separator of some logical sections but it look very odd when you have sections without a title:

<img width="385" alt="Screenshot 2020-01-09 at 21 55 29 (1)" src="https://user-images.githubusercontent.com/535613/72336497-32609580-36c1-11ea-89b1-766efabb498b.png">

Instead, we should try a cleaner layout inspired by newer versions of the Android settings app:

<img width="385" alt="Screenshot 2020-01-09 at 21 55 29 (1)" src="https://user-images.githubusercontent.com/535613/72336647-7f446c00-36c1-11ea-885b-77095cfc4784.png">

## 📝 Detailed explanation
The key is to drop the dividers between every single item and use them only to separate sections instead of the vertical spaces we use now. For the sections that currently have some title, we can change the way the title is laid out to get even closer to the native setting app.

Check out this example of sections with and without a titles:

<img width="385" alt="Screenshot 2020-01-09 at 21 55 29 (1)" src="https://user-images.githubusercontent.com/535613/72338170-33df8d00-36c4-11ea-8bfc-4344d9bf61f9.png">

## 🎨 Graphical resources
I don't think we need any

## 🛠 Technical remarks
This should be pretty straightforward

## 👕 Estimated complexity
This should be a matter of hours not days. I have no idea what 👕 is the right one in this case, **M**?

## 🖼 Express your sentiment towards the issue
❤️

**Comment by daividssilverio** [comment]
Hey @AlicjaSuska @semanticer here's how it looks with 64 dp of left margins.

| dark mode | light mode |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/2173493/72900678-bab4eb00-3cfe-11ea-97d8-e95fed241fae.png" width=240 /> | <img src="https://user-images.githubusercontent.com/2173493/72900695-bf799f00-3cfe-11ea-8d28-f164b5289d93.png" width=240 /> |
