### ISSUE TITLE
Cancel Sync on Logout

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#692]
We have to figure out how to stop the sync machine in such a way that it is guaranteed to make no changes to the database anymore.

This is needed so that on logout/in no data from the previous user is visible to the new one.

I propose we find some way of telling the sync machine to stop once the next state finishes, and prevent it from entering any other state from that point on - i.e. freezing it. I do not think there is any need to ever unfreeze it, so this should be relatively easy?

Note that the logout has to wait until the sync machine is confirmed to have stopped all states before proceeding to clear the database and navigate to the login screen.

**Comment by simonrozsival** [comment]
This should be easy. I don't think we ever discussed any case where we would want to stop the machine manually and resume later on.
