### ISSUE TITLE
Animate FAB long press

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#6959]
We should animate the FAB long press, ideally adding a "radial progress bar" animation. See example below:

<img width="755" alt="Screenshot 2020-01-22 at 18 20 19" src="https://user-images.githubusercontent.com/6031512/72911766-a3e8b580-3d4b-11ea-9fd7-25b65c5dab32.png">

**Comment by amulware** [comment]
Alternative (just an idea): What about making the button grow, similar to how long press all over iOS 13 mimics 3d touch?

**Comment by juanlaube** [comment]
Why not both and we A/B test them and see which one generates more events? 😄

**Comment by amulware** [comment]
Not the most useful A/B test perhaps - unless the user knnows what the feature does I'm not sure it's entirely clear at a first glance what long press does - but I mean.. you do you :D

**Comment by juanlaube** [comment]
Yeah, I agree with that, I'm just trying to push my agenda 😄
