### ISSUE TITLE
Cannot edit start time past end time/Editing start time changes duration

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#696]
In the edit view, I don't seem to be able to edit the start time past the end time (the spinner resets).

Also, editing the start time seems to change the entries duration, instead of its end time.

Either this has to be fixed, or it has to be changed (please confirm, @pe0ny).

**Comment by pe0ny** [comment]
IMO it works as it should work.
- start time < end time
- editing start time, changes duration; that's how it behaves in webapp as well
- editing duration, changes end time

**Comment by amulware** [comment]
I see. And I think I disagree because if I have a timeslot of one hour that I want to move by two hours forwards in time, I have to change it to three hours in length and then move the start time forwards by 2, which I find very counter-intuitive.

The desktop app has a 'change duration when changing start-time' toggle for this.

Btw, I find this especially annoying since end times cannot be edited (which I think should be possible).

Overal I find editing time a bit clunky right now. If I can think of something better I'll poke again.

If you say that this should stay as it is despite my comments, feel free to close this issue.

**Comment by arturs105** [comment]
I agree that moving time entries is kinda hard now. Maybe we could have a segmented control above or below the date picker indicating which of the two editing modes is currently active:
1) Editing start time changes duration
2) Editing start time changes end time

**Comment by amulware** [comment]
( fix end time | FIX DURATION )

Works for me. Up to @pe0ny

**Comment by pe0ny** [comment]
Let's keep it as it is for now. Product team has been informed about the topic and it makes sense to change this logic when it will be changed for all platforms.
