### ISSUE TITLE
Smoothly hide the tab bar when showing the calendar contextual menu

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#6961]
Currently the tab bar feels a bit jumpy when we open the contextual menu, since it's hide/show process is not animated. This is much more pronounced on iPad in landscape view, where it just behaves erratically. What we want is to smoothly fade out/in the tab bar items across all size classes.

![tab-bar-jump](https://user-images.githubusercontent.com/6031512/72912137-3d17cc00-3d4c-11ea-998f-251fa614c641.gif)

**Comment by Odrakir** [comment]
FYI, there's some discussion on wether to make the tab bar disappear or not here: https://github.com/toggl/mobile-discussions/issues/50
