### ISSUE TITLE
Create an animated time label

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#6962]
The label should increment/decrement the label's value over a fixed period of time, so larger changes should take the same time as smaller ones. The recommended period is 250ms.

Use it to animate:
- [ ] calendar item start/end labels when resizing the item
- [ ] the calendar total tracked time label
- [ ] reports summary values population

**Comment by Odrakir** [comment]
Aren't the start/end times of calendar items animated as you drag?
