### ISSUE TITLE
Time entry creation in the calendar visually divides the time entry being created when you go and come back from the edit view

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6972]
How to replicate:
- Long press to create a time entry
- Click `Edit` in the contextual menu
- Press back in the edit view that appears
- You should go back to the calendar view and the time entry you were working with should be divided now.

It should look like this:
![image](https://user-images.githubusercontent.com/2173493/73014419-7f92e480-3df0-11ea-8fe8-47cf27ae6da9.png)

**Comment by daividssilverio** [comment]
Not sure if we'll have the time to work on this, but I've moved it to 2.11 @semanticer . 
It's an ugly glitch, but not really common.

**Comment by pdrj** [comment]
@daividssilverio can you still reproduce it as described? In my case, I still get the full-width TE when I go back from the edit screen, but the TE doesn't seem to be persisted. When I sync, it disappears from the calendar.
