### ISSUE TITLE
Calendar events with short durations display the calendar icon even if there's no room for it

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6973]
The title says it all.
Here's an example: 
![image](https://user-images.githubusercontent.com/2173493/73014610-dac4d700-3df0-11ea-93aa-5e3b12b4c247.png)

**Comment by heytherewill** [comment]
What should the correct behavior be?

A) The icon shrinks to fit
B) No icon is shown, but the padding remains the same
C) No icon is shown and the text takes the place where the icon should be
D) We crash the app and apologise to the user using a Toast

**Comment by maritoggl** [comment]
a

**Comment by daividssilverio** [comment]
Closed by #6984
