### ISSUE TITLE
Contextual menu start/end dates are always in AM/PM mode.

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6975]
Title says it all.
To see what I'm talking about, try the following:

- Check your `Use 24-hour format` user preferences (true)
- Go to the calendar view
- Select any entry from the calendar
- Check the string at the top of the contextual menu, it will be using the (AM-PM) format.

**Comment by daividssilverio** [comment]
@sofokli1 do you know if this behaviour was intended?

**Comment by sofokli1** [comment]
can't recall anything to make this specific am/pm. @maritoggl do you recall anything?

**Comment by maritoggl** [comment]
Definitely not intentional - we should be respecting the user preference.

**Comment by heytherewill** [comment]
This also affects iOS, so I'm including it in 2.11

ping @arturs105
