### ISSUE TITLE
Date format user preference is not always working

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6976]
More specifically, try changing the date format to `MM/DD/YYYY` or `DD/MM/YYYY`. 
Those two specific formats are not working properly and the edit view will still display data in the `MM-DD` format.

**Comment by heytherewill** [comment]
I could not reproduce this. Tested on current store version (2.9) and on `develop`. I say we close this for now and reopen it if users complain about it

**Comment by daividssilverio** [comment]
Hey, this is still happening in 2.12.
To test this: change the date formats and check out the reports bar charts.

**Comment by daividssilverio** [comment]
Closed via #7164
