### ISSUE TITLE
Find and fix critical observables that are misbehaving

### ISSUE THREAD

**Issue by heytherewill** [toggl/mobileapp#6978]
## 🎯 What needs to be done?
We need to look in our data sources and ensure that the observables that are alive during the entire lifecycle of the app (that is, the ones that observe DB changes and not the ones that return a single value and finish) are behaving properly

## 📝 Detailed explanation
We need to ensure that these observables behave correctly because they run during initialization, which means that they can have a severe impact on the startup times of the app

## 🛠 Technical remarks
For these observables to be considered correct, they should:

- Not start producing values immediately after creation, but rather only when they are subscribed to
- Have a shared subscription instead of producing values whenever they are subscribed to
- Always produce values on a background thread

## 🔗 Dependencies
Similar to #6977, but on a lower level

## 🏆 Outcome
All DataSource methods and Interactors that return long living observables should be reviewed and, in case they are misbehaving as per the above write-up, fixed.

## 🖼 Express your sentiment towards the issue
![image](https://user-images.githubusercontent.com/7688727/73034600-23e24e80-3e24-11ea-93d7-08117605c6e0.png)

**Comment by heytherewill** [comment]
While working on #6679 I found the following offenses:

- `TimeEntriesDataSource.cs`
  - `CurrentlyRunningTimeEntry` runs a query to find the currently running TE during construction
  - `IsEmpty` behaves similar to the above
- `SingletonDataSource.cs`
  - `Current` is a connectable observable that connects immediately when it could use `RefCount` to connect only when subscribed to

**Comment by daividssilverio** [comment]
Un-assigning myself from the issue to let other people take a look.

@heytherewill , I took a look at the `SingletonDataSource`, `CurrentlyRunningTimeEntry`, `IsEmpty` and I couldn't figure out a way of fixing what you pointed out.

**Comment by heytherewill** [comment]
No way this can be done without breaking the consistency of the sync algo and possibly introducing instability
