### ISSUE TITLE
Continuing a time entry from the suggestions widget does not give any feedback to the user

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6990]
That's only an improvement suggestion.
We currently don't give any feedback to the user when clicking on the suggestions to start a new time entry.

It could show something in the widget itself, or maybe a simple notification.

@maritoggl what do you think?

**Comment by juanlaube** [comment]
I agree we should show something, however due to limitations on the API we need to research what we can do if we decide to do something inside the widget.
