### ISSUE TITLE
Running time entry with archived project doesn't show the "archived icon"

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6992]
How to replicate:

1. Set a project to the running time entry
2. Archive it from the web app
3. Sync the app
4. You should see the running time entry card with the project without any indication of it being archived.

@maritoggl Since we handle archived projects in the main log with an icon, don't you think we should do the same for the main running time entry card?

**Comment by amulware** [comment]
Definitely not a bug in either case. If anything it's a missing feature.

**Comment by maritoggl** [comment]
We can do that, sure. Quite a low priority issue, but feel free to tackle it if it's a quick and straightforward improvement.
