### ISSUE TITLE
Archived project on running time entry doesn't appear in the web, but stays as (archived) in the time entry on mobile

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#6993]
How to replicate:

1. Have some time entries with a project in the main log on the android app.
2. Have a running time entry with said project.
3. Go to the web app, archive said project
4. Go back to the android app, sync and you should see the archived projects in the main log and in the running time entry card.
5. In the web app, ~you can't see the projects anymore~, you can see the archived projects in the stopped time entries, but the running time entry doesn't have any project.

Is that intended? Should we be showing the archived projects in the mobile apps? @maritoggl

**Comment by amulware** [comment]
Mobile behaviour is intended. Sounds like a bug on web.

**Comment by maritoggl** [comment]
Confirming what Paul said.

**Comment by daividssilverio** [comment]
I'll double check, close this and ping someone from FE.

**Comment by daividssilverio** [comment]
Ok, so, correcting the issue. Archived projects to appear in the Web project, but running time entries with archived projects do not. Stopping a running time entry in the web app seems to not create a time entry. On the mobile app, it creates a time entry with the archived project normally.

**Comment by daividssilverio** [comment]
Closing as it's probably more related to FE than mobile.
