### ISSUE TITLE
Dark Mode Issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#6996]
## ⛑️ User Support

We've had a number of users reaching out asking why Dark Mode is no longer working after we rolled out Giskard 2.9, most of these users are on Android 9. 

While discussing this with the mobile team it was clarified that the Toggl app will only go into dark mode in Android 9 if the device has battery saving mode enabled. Only users on Android 10 will have the app behave according to their system's dark/light mode preferences. This was not the case with Android 9 before the Giskard 2.9 update was rolled out. 

You can see references on what made the app go into dark mode in slack before Giskard 2.9 was rolled out [here](https://toggl.slack.com/archives/C029WU7AY/p1572958760151000). 

## About the user

There's a few users so I'll try to fit this into the template format for mobile issues

App version: Giskard/2.9
Phone OS: Android 9, Android 8.1.0
Phone model: Mi MIX 2S; Samsung S9, Samsung S8, Sony Xperia XZ1, Xiaomi poco f1, Xiaomi Mi 8, Xiaomi Mi A2 Lite, Galaxy Note9, Samsung Galaxy M30s, OnePlus 3 

There's about 30 cases in the last 3 weeks, if you need to look into them I think it's best if I just link up the search results for the phrase "dark mode" and with the "last 30 days" range selected: [🔗](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/25487083479?adminDateRangeEnd=2020-01-27&adminDateRangeStart=2019-12-28&assigneeIdentifier=all&q=dark%20mode) 

## Expected behaviour
The app should also go into dark mode if system settings are set to dark/night mode as well

## To Reproduce
1. Enable dark mode in your phone's sys settings
2. Start the Toggl app
3. Check if it's in dark mode or not (not)

## Suggestions
@heytherewill thinks he pinpointed the issue here: 
https://github.com/toggl/mobileapp/pull/6513/files
https://github.com/toggl/mobileapp/pull/6789/files

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/25504363169)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/25537252071)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/25481034229?assigneeIdentifier=all&q=dark%20mode)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/25517417047?assigneeIdentifier=all&q=dark%20mode)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/25509812180?assigneeIdentifier=all&q=dark%20mode)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/25475293412?assigneeIdentifier=all&q=dark%20mode)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/search/conversations/25509187251?assigneeIdentifier=all&q=dark%20mode)

**Comment by nidarasheed** [comment]
[Case  reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25494391493)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25539527618)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/25521326527)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25493949686)

**Comment by dianetoggl** [comment]
[Case reference ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25617513304)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/25561023270)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3724360/conversations/25639157122)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3724360/conversations/25654105344)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25704521956)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25877711585)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25899966367)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26136690938)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26815687627)
