### ISSUE TITLE
Review Google Sign In

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6997]
I personally haven't ever been able to Sign In with Google, not with my Toggl account and not with my personal Gmail account. Apparently there are some users with this problem too.

Analytics show this is not a big deal,  but still it'll be interesting to investigate. Maybe even adding more analytics events, mostly to user actions like tapping the Google Sign In button, which we are currently not tracking.

Someday said we should update the Google Sign In package, but I believe it's on the latest version, so I'm not sure if that was referring to using some other means of authenticating with Google...

**NOTE:** This issue is part of the `Onboarding refactor` project and it should be merged into the project branch and not into develop.

**Comment by sofokli1** [comment]
I had a similar issue in the past. the switch was hidden in a drop down menu in the past.

@Odrakir do you have this switch enabled in web profile settings?
<img width="650" alt="Screenshot 2020-02-12 at 2 03 17 PM" src="https://user-images.githubusercontent.com/885122/74333439-9e0d4f80-4da0-11ea-99d2-78b623ae4f88.png">

**Comment by dshr** [comment]
Shared this on Slack before, gonna post it here too:
In `SignupViewModel.cs:356` we pass a `timezone` string to the `SignUpWithGoogle` method of the `UserAccessManager`. Problem is that that variable isn't initialised anywhere in the whole class. This might mean that all new sign-ups pass an empty string to the API, throwing an error, which explains why Google Login works fine for some of us, while being broken for others.

**Comment by dshr** [comment]
Closed with #7131
