### ISSUE TITLE
Create Onboarding ViewModel

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#6998]
This is the crossplatform part of the onboarding. It has to include actions for social sign in (just Google for now) and a way to navigate to the email sign up / login flow. No actual onboarding for now, this will be added later. Implement or reuse current interactors where possible.

In the case of login, this will take the user directly to the timeline. In the case of sign in, it'll take him to a country selector, TOS check screen that's being done in another issue. This screen will probably be a modal dialog and won't requiere its own ViewModel.

In the case of email sign in, we'll direct the user to sign up or login, depending on factors. This is done in another issue as well.

Most signup/login logic should be taken from the current implementation, but bear in mind that this time signup/login can be done from two different screens with different ViewModels, so ideally we would move shared logic to interactors.

**NOTE:** This issue is part of the `Onboarding refactor` project and it should be merged into the project branch and not into develop.

**Comment by juanlaube** [comment]
This is also where we would need to put A/B testing code, if we want to do it.

**Comment by Odrakir** [comment]
Yep, just created an issue for that: https://github.com/toggl/mobileapp/issues/7020
