### ISSUE TITLE
Create email login ViewModel

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#7006]
This will take some logic from the current login implementation, but share some other with the new social signup screen, that we'll be put in interactors.

It'll take the email and password from the user, validate the data and then try to log him in. If it succeeds it'll take the user to the timeline, otherwise it should show the appropriate error.

Designs and full specs: https://www.notion.so/toggl/Designs-wip-d767ebc157c542c790e1bc93eeaf006f#835299ea40344044b2572f356b4f47c1

**NOTE:** This issue is part of the `Onboarding refactor` project and it should be merged into the project branch and not into develop.

**Comment by daividssilverio** [comment]
🤔 What should be different from the current implementation?
The `LoginViewModel` already looks good enough to be used as is.
We can remove the `GoogleLogin` from it if we'd have a screen just for social login.
