### ISSUE TITLE
Reports view does not update after TE changes

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#7009]
## 🐛 Bug Report
After opening the reports view for the first time, going back to the main log, updating a TE duration or creating a new one and going back to reports. The report view will not show the new durations changes. Same goes for date changes that move a TE outside of the reports rage, a reload is not triggered.

## Context
Build/Branch: ios 2.10
Phone OS: 13.3
Phone model: 11 pro

## Expected behavior
Expected to see reports reloaded after changes to TEs, like duration and dates.

## To reproduce
- open the app and go to reports to load for the first time
- go to mail log and either perform changes to TEs that are in the range of the reports view or just create new TEs.
- go to reports view and expect no changes compared to the first load (at first point)

**Comment by amulware** [comment]
It is intended behaviour that the reports view does not reload every time you open it. What's your proposal?

**Comment by dshr** [comment]
Oh! While this is indeed intended behaviour, we could add a drag-to-refresh to reload the reports view. Should be easier now, now that it's a proper `UICollectionView`.

**Comment by amulware** [comment]
We could also reset the timer (is there a timer?) or set a flag to have it reload on sync finishing, which would maybe catch most cases automatically.

**Comment by dshr** [comment]
There used to be a timer, but not anymore. As for reloading on finishing sync — that should work

**Comment by sofokli1** [comment]
@dshr sync does not trigger a refresh either

**Comment by dshr** [comment]
I meant that rigging the refresh to trigger after each sync could be a workable solution, not that it was already implemented 🙃
