### ISSUE TITLE
Main log section header total duration is not updating after changes in the section

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#7013]
## 🐛 Bug Report
Main log section header total duration does not update after changes to the data in the section.

## Context
Build/Branch: ios 2.10
Phone OS: 13.3
Phone model: iphone 11 pro

## Expected behavior
To show the correct duration of the section

## To reproduce
- Start a TE
- Stop it
- Continue that TE
- Stop it
- Section duration and sum of TE duration does not match
If we scroll the section header out of bounds and back in, it will refresh

## Suggestions
We need to reload sections headers when datasource changes.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/25480473674)
