### ISSUE TITLE
Custom Siri reports shortcut not working

### ISSUE THREAD

**Issue by sofokli1** [toggl/mobileapp#7018]
## 🐛 Bug Report
I can get the reports to show but when trying to use custom reports shortcuts like `Yesterday reports` it only opens the reports in the state that it is already without changing the range.

## Context
Build/Branch: release ios 2.10
Phone OS: 13.3
Phone model: iphone 11 pro

## Expected behavior
To change the range of the reports view to the custom range specified in the shortcut.

## To reproduce
Open siri shortcut and create a shortcut with custom range. Ask siri to execute it and see what happens

**Comment by dshr** [comment]
Closed in #7289
