### ISSUE TITLE
A/B Test different onboardings

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#7020]
We believe the onboarding is the best place to play with A/B testing as users are new to the app and there are few side effects that could mess with the results.

This is still pending some discussion, but it would be very nice to try different sets of onboarding steps to see which ones attract more users to signup.

**NOTE:** This issue is part of the `Onboarding refactor` project and it should be merged into the project branch and not into develop.

**Comment by juanlaube** [comment]
We decided to postpone this since we don't have a baseline yet.
