### ISSUE TITLE
A/B test the effect of having the calendar view as the first tab in the bottom bar

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7032]
The idea is to go crazy and see how the position of the calendar view affects the usage of the calendar view.

Although... it can be tricky to see if the usage is actually increasing or it's just the fact that the calendar view is the first thing the users see.

For this test to work, it would be better to track an event for the main tab bar clicks.

The first tab should be the calendar view.
The second tab the timer.
The third tab should be the reports view.

This sounds like is a risky one, let's maybe just target very few users for this experiment. Maybe 5 or 10% of the users.

@amulware @maritoggl

**Comment by maritoggl** [comment]
I’m ok with experimenting with the order of buttons in the bottom bar, but at the moment I won’t approve switching the calendar view to be the default view that’s open as a first thing for the user.
