### ISSUE TITLE
Fix rating view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#7035]
## 🐛 Bug Report
As discussed at length here: https://github.com/toggl/mobile-discussions/issues/51 it looks like something is very wrong with our rating view. 

Our event data says that the view is shown to a great number of users, however less than half of the expected number interact with them (this is compared to numbers from before the view was broken for a while).

Note that on iOS, the view behaves fine and we see the data we expect. Something broke on Android specifically, between September and November.

## Context
Rating view was entirely broken in October until: https://github.com/toggl/mobileapp/pull/6087
Data and discussions on what we observed recently is here: https://github.com/toggl/mobile-discussions/issues/51

## Expected behavior
The rating view should work properly for all users, as configured with remote config. The conversion rates of each step should be the same as they were throughout most of last year.

## To reproduce
N/A

## Suggestions
I'm not sure if we can easily reproduce it, but it's worth a try. Otherwise, look at what code changes happened between September and November that could have broken it on Android specifically.

**Comment by amulware** [comment]
Please double check the data and conclusions in the linked discussion issue. It shows that there likely is some sort of bug, perhaps already introduced before September, that causes the view to not show up or be unresponsive in some way that prevents users from using it.

There is also a slight chance that things have returned to normal with one of the recent releases, but this is not clear in all the data, and I would like us to figure out what happened and to fix any remaining issues in either case.

**Comment by heytherewill** [comment]
I've investigated this thoroughly and apparently there are only two possible points of failure in the Android app:

1) Firebase is not sending us the the configuration so the screen never shows
2) The intent to open the store is broken

Both of these work (and after further discussing with @amulware, they wouldn't even be a problem in the first place.

My best guess is that https://github.com/toggl/mobileapp/pull/6628 fixed whatever was wrong with the rating view (it was a hot mess before that PR), so we should see our ratings slowly normalizing over the next few versions of the app.

I'll wait for @amulware's final veredict, but IMO this issue needs no more work

**Comment by amulware** [comment]
I did some more data, specifically for 2.9, which includes the refactor mentioned above, and there is indeed improvement!

It looks like the correct number of users who interact and say they like the app agree to rate the app now, so that part of the UX seems fine.

However, of the people who are shown the view, still only half as many as expected actually interact with it! I think there's still some issue here.

Could you check again whether there's any source of potential issues around the part of the code that's showing the view? Specifically, the Shown event is getting through in expected numbers, so it gets that far in the code (which rules our remote config issues too), however, the FirstStep event occurs half as often as it should, compared to historical data (and iOS), so it seems that something still goes wrong between those two events. :/

**Comment by heytherewill** [comment]
Passing the baton to @pdrj since he can reproduce the corner case that's causing us trouble and he recently worked on the rating view
