### ISSUE TITLE
Create loading screen for iOS

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#7036]
After the user finishes the onboarding (signup/login, but mostly login) we need to show a loading screen while the app loads whatever data is available. This will take between 2 and 10 seconds.

Light mode: https://toggl.invisionapp.com/share/J3VWZDDQVFD#/screens/404298503
Dark mode: https://toggl.invisionapp.com/share/J3VWZDDQVFD#/screens/404298502

**Comment by sofokli1** [comment]
@Odrakir do we have designs for this, or still waiting?
