### ISSUE TITLE
Create loading screen for Android

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#7037]
After the user finishes the onboarding (signup/login, but mostly login) we need to show a loading screen while the app loads whatever data is available. This will take between 2 and 10 seconds.

Light mode: https://toggl.invisionapp.com/share/ANW6KYJQM6H#/screens/407008871
Dark mode: https://toggl.invisionapp.com/share/ANW6KYJQM6H#/screens/407008870

**Comment by daividssilverio** [comment]
Closed via #7186
