### ISSUE TITLE
Investigate and fix high ANR numbers

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#7038]
## 🎯 What needs to be done?
Investigate and fix high ANR numbers of the Android app.

## 📝 Detailed explanation
Go to Google Play console, enter the 'Vitals' tab. You'll see that our ANR numbers are not great. These numbers influence store positioning and we need to make them lower. At first glance, the most common ANR may seem to be related to Android versions between 5 and 6: [link](https://play.google.com/apps/publish/?account=6541371164481955362#AndroidMetricsErrorsPlace:p=com.toggl.giskard&appid=4975048714562868710&appVersion&lastReportedRange=LAST_60_DAYS&errorType=ANR&clusterName=apps/com.toggl.giskard/clusters/39212e95&detailsAppVersion), but a very similar one happens on v9: [link](https://play.google.com/apps/publish/?account=6541371164481955362#AndroidMetricsErrorsPlace:p=com.toggl.giskard&appid=4975048714562868710&appVersion&androidVersion=28&lastReportedRange=LAST_60_DAYS&errorType=ANR&clusterName=apps/com.toggl.giskard/clusters/2e5352a8&detailsAppVersion&detailsAndroidVersion=28). The linked Android 5-6 ANR, in more than `50%` cases, happens on LG G3 devices. 

Note that at the time of this writing, the `BackgroundSyncJobSchedulerService` ANR has yet to happen on Android 10 devices.

All in all, if we manage to fix the `BackgroundSyncJobSchedulerService` ANR, that alone could make the ANR ratio go down significantly.

## 🏆 Outcome
Ideally, keep the ANR rate below the 'bad behavior threshold', which is `0.47%` ATM.

**Comment by heytherewill** [comment]
Our ANR rate for the last 30 days is 0.32%, which is below the 0.47% bad behavior threshold, so this can be closed and we can reopen if it goes up again
![image](https://user-images.githubusercontent.com/7688727/81194969-a0440c00-8f93-11ea-9588-1c741004d2e5.png)
