### ISSUE TITLE
Investigate random ANRs & Freezes

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7067]
## 🎯 What needs to be done?
It seems like we are having some ANRs being reported by google. Something like 2% of the users seem to be affected by it. I managed to get into an ANR and I've reported through the Playstore, so we should receive something about it.

## 📝 Detailed explanation
There was a running time entry when it happened, it was being animated to the stopped state, which lagged and the whole app started janking until it actually froze. After that, even after closing the app, it would get stuck on the splash screen.

This could be related to the VPN being active, but... it didn't unfroze when I disabled the VPN.
The app started working again after I tried to create a bug report through the developer options.

## 🎨 Graphical resources
None.

## 🛠 Technical remarks
None.

## 🔗 Dependencies
None. But It seems to only be replicated in production.

## 🏆 Outcome
No ANRs!

## 👕 Estimated complexity
L.

## 🖼 Express your sentiment towards the issue
https://media.giphy.com/media/xU9TT471DTGJq/giphy.gif

**Comment by heytherewill** [comment]
Duplicate of #7038 ?

**Comment by daividssilverio** [comment]
Closed, duplicate of #7038
