### ISSUE TITLE
Review onboarding dark mode for iOS

### ISSUE THREAD

**Issue by Odrakir** [toggl/mobileapp#7069]
This might have been done during the implementation of each screen, but still it's probably worth it to take some time to review dark vs light modes in the whole onboarding flow.

**Comment by sofokli1** [comment]
main onboarding screen
- [ ] page indicator does not change to black color in dark mode (the 2 dots at the bottom, above the buttons)

email login
- [ ] background color does not change to dark color
- [ ] action button text color does not change to black

email signup
- [ ] background color does not change to dark color
- [ ] navbar text color does not change to white color
- [ ] action button text color does not change to black

country select
- [ ] no toggl logo as in the designs
