### ISSUE TITLE
App crashes when stopping a TE

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#708]
1) Start a new time entry or continue existing one
2) Tap stop
3) App crashes

**Comment by simonrozsival** [comment]
Do you see the time entry in the log with some weird large negative duration? I just want to confirm that this is the very same bug I am observing.

**Comment by simonrozsival** [comment]
The bug was fixed by the backend team yesterday. There is a related bug though (issue #714) which also happens after clicking the stop button, so I will leave this issue open until the other is closed.
