### ISSUE TITLE
TE reappearing as running after it's stopped

### ISSUE THREAD

**Issue by semanticer** [toggl/mobileapp#7091]
## 🐛 Bug Report
TE reappears as running shortly after it's stopped. This probably happens during the sync since you have to be online to see this bug.
Here is the gif: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/535613/74436815-5e5d6b00-4e67-11ea-99a9-555310caa633.gif)

(I will add a video via slack)

## Context
Tested in production to be sure it's happening there as well.

Build/Branch: android-2.11-liquorice
Phone OS: Android 10
Phone model: OG Pixel

## Expected behavior
TE should be stopped when it's stopped and stay that way. 

## To reproduce
**You need to be online**
Not sure yet about the exact steps to reproduce 100% but it's pretty easy to simulate most of the time. 
1. Start non-manual TE
2. Stop very quickly (1-10s)
3. Wait - TE should appear in the main log list and sync is initiated, then there is like 40% chance TE will reappear as running TE

## Suggestions
This might be related to some of the speed optimizations or to whatever we changed with syncing (the "fixed" user preferences sync maybe?)

**Comment by pdrj** [comment]
As said on slack, I couldn't reproduce this. Waiting for other @toggl/androids to test on their devices.

**Comment by semanticer** [comment]
I solved this by rebooting my phone which is extremely strange. Closing this for now. I will ask support if this is a common thing and reopen if needed.
