### ISSUE TITLE
"Forgot Password" Button Doesn't Work

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/mobileapp#7121]
## 🐛 Bug Report
Just after a fresh install of the app, I open it and tap on the "forgot password" button to reset my password. 

Only it doesn't let me reset my password. Like a moth hitting a lightbulb I keep on tapping those accursed words "forgot password" but alas, to no effect. I can't reset my password in the mobile app. 

## Context

Build/Branch: 2.11 
Phone OS: iOS 13.3.1
Phone model: iPhone 11 Pro Max

## Expected behavior
When one tappeth on the button 
One should reset their password 

## To reproduce
1. Fresh install app from App Store 
2. Tap to open app 
3. Tap "forgot password" words 
4. Experience existential anguish and head over to website to reset password 

## Suggestions
No suggestions; you guys are all awesome!

**Comment by TheSoloJake** [comment]
Link to video of action: https://drive.google.com/file/d/1Rx8ufSJkrdkU6de_kKpQPs_wBbOppDg4/view?usp=sharing

(Link accessible only to Toggl employees)

**Comment by sofokli1** [comment]
@TheSoloJake can you still reproduce this in the current 2.13 testflight build?

**Comment by TheSoloJake** [comment]
@sofokli1 Looks like it was resolved in 2.12, as that's the current version of the app I'm running and I can't replicate anymore
