### ISSUE TITLE
CalendarFragment.ScrollToStart crash

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#7133]
## 💥 Crash Report
One of the more common crashes in 2.11.1. The earliest reports are from 2.8.1.

### 👥 Impact
Affects about 0.04% of users. 

### 🛰 Link
[Link](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/2501995214u/overview)

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
CalendarFragment.ScrollToStart ()
System.NullReferenceException: Object reference not set to an instance of an object

CalendarFragment.ScrollToStart ()
MainTabBarActivity.onTabSelected (Android.Views.IMenuItem item)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.39(intptr,intptr)

```

**Comment by daividssilverio** [comment]
Still present in 2.12, affecting 0.1% of the users so far. Scheduling it to 2.14.
