### ISSUE TITLE
Rating view card appeared right after creating a new account

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7158]
This is a corner case, but it can happen when an existing user signs off and a new account is created in that device (actually... it might even happen if you login back right away).

Basically, we are not cleaning the `firstAccessDateKey` and `ratingViewNumberOfTimesShownKey` keys on `IOnboardingStorage.Reset().

Because of that, if you logout after 5 days and tries to create a new account (maybe even simply signing back in), you should see the rating when even though you shouldn't.

**Comment by amulware** [comment]
The rating view should happen on a precise trigger set by remote config, currently on stopping time entries. If the view shows without the user stopping a time entry, THAT is a bug. The other thing is behaviour as intended.

**Comment by daividssilverio** [comment]
Let's close this as it's working as it should as explained in #7163.
