### ISSUE TITLE
Remove existing tags, when changing a workspace for time entry.

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#716]
Currently workspace for a time entry can be changed from edit time entry view by selecting a project from different workspace. So when user presses "Confirm" after selecting a project from another workspace, the app should:
1. Show a standard iOS alert explaining that all tags will be removed. The dialog should have buttons "Remove tags" and "Cancel"
2. If user presses "Cancel", do nothing
3. If user presses "Remove tags", then remove the tags from time entry.

**Comment by amulware** [comment]
Needs alert copy from @pe0ny.

**Comment by pe0ny** [comment]
Logic should be a bit different:

When user goes to project view to change a project and selects project from another WS:
1. Show standard iOS alert explaining that user selected project from another WS.
2. When user taps 'Cancel', close the alert and keep project view open so user can select another project or go back.
3. When user taps 'Ok', close the alert and direct user back to the TE edit view.

*So this shouldn't happen already in projects view, not in time entry edit view*

**Comment by arturs105** [comment]
The dialog's text doesn't say anything about removing the tags. Should it be that way?

Also, i'm having trouble understanding this sentence:
> So this shouldn't happen already in projects view, not in time entry edit view

Was it meant to be something like this?

> So this should happen already in projects view, not in time entry edit view

**Comment by pe0ny** [comment]
Yes, thank you. *Should* happen in projects view :)

**Comment by pe0ny** [comment]
And yes, it doesn't say anything about tags. Confirmed with UE/product team and thought less text the better.
