### ISSUE TITLE
Reports tab doesn't update unless restarted or date range changed

### ISSUE THREAD

**Issue by dianetoggl** [toggl/mobileapp#7170]
## ⛑️ User Support

User experiences issue where they add a time entry and switch to the reports tab. The time entries on the tab won't update unless the app is force closed and reopened OR the date range picker at the top left-hand corner has been changed to a different date and then changed back to the original date.

## About the user

App version: Giskard/2.11.1
Phone OS: Android 10
Phone model: Pixel 2

## Expected behaviour

User should be able to go to the report page and have it update straight away.

## To Reproduce

1. Add a time entry
2. Go to report tab - report will not include your latest entry
3. Change date range
4. Change date range back - report will now be updated

## Suggestions

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26053517491)

**Comment by VeljkoTN** [comment]
@dianetoggl consider closing this one because it works on Giskard 2.13.1 (internal testing version), the Play Store version is also newer (2.12) I'd ask them to update.

**Comment by dianetoggl** [comment]
Hey @VeljkoTN 
I just tested it on 2.13.1 and  I still have the same behaviour. 

It appears another user on 2.13 iOS is experiencing the same:
[Intercom](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26500269414)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26659195319)
