### ISSUE TITLE
Project view: separators are too thick

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#719]
Separators should be 1pt, but atm these are 2pt.

**Comment by kornelijepetak** [comment]
Most of this issue has been solved by other PRs. 

However, there's still a double border between workspace groups.

I have exaggerated (in the picture below) the borders with color and size to clearly see what's what. And it seems that the workspace's border (red) was indeed 1pt, but it was shown next to project border (green), which is also 1pt. Together they make that nasty thick border of 2pts. 

I would propose to solve this by preventing last item in a group (in this case a Project's) from showing the border, unless it is contained in the last group (in case of which the border is necessary). Do you think this would be a viable solution or is there a better way? 

![image](https://user-images.githubusercontent.com/7033216/31780432-017f5216-b4f6-11e7-9526-273b08c91da0.png)
