### ISSUE TITLE
Animation in onboarding is stuck after resuming app

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#7199]
## 🐛 Bug Report
After resuming the app from background, the animation in the periscope is stuck, with the eye out of place.

## Context

Build/Branch: 2.13
Phone OS: iOS
Phone model: any

## Expected behavior
The animation should continue after resuming from background.

## To reproduce
Resume the app from background and go to the second page.

**Comment by sofokli1** [comment]
it is in the release branch, closing
