### ISSUE TITLE
Colors are switched in the bar graph 

### ISSUE THREAD

**Issue by zdericnina** [toggl/mobileapp#7202]
## 🐛 Bug Report

[User on Twitter](https://twitter.com/alexisohanian/status/1240280603850870784) reported there is a bug with Reports in the way we are displaying billable vs non-billable time in the bar graph.

## Context

I could also reproduce this on the mobile app, details below are regarding my device

Build/Branch: 2.12
Phone OS: 13.3.1
Phone model: iPhone X

## Expected behavior

Colors on the bar graph should be inverted

## To reproduce

1. Go to the Reports on the mobile app
2. See the bar graph displaying billable time as non-billable and vice versa

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26289120337)

**Comment by sofokli1** [comment]
solved in 2.13
