### ISSUE TITLE
Continue with google shows the ToS screen even when dismissing the account picker without selecting an account

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7206]
How to replicate:

1. Go to the onboarding screen.
2. Tap "continue with google".
3. When the account selector appears, dismiss it by clicking outside of its bounds/
4. You should see the "Terms of Service & Country" screen appear.

Expected behaviour:
- If the user gives up on continuing with google, the ""Terms of Service & Country" shouldn't appear.

**Comment by pdrj** [comment]
This no longer happens - most likely due to Eugene's fixes.
