### ISSUE TITLE
Android Forgot password screen feedback

### ISSUE THREAD

**Issue by daividssilverio** [toggl/mobileapp#7209]
This comes directly from the feedback provided by Janika on Notion:
- [x]  Reset password - the CTA button should be close to the text fields as per design.
- [x]  **Reset password - below the text field there is this grey text. This is not needed anymore as we have the headline. Please remove it.**
- [x]  Reset password - CTA button text is wrong. Should be as per design.
- [x]  **Reset password - Error state on email field is missing. If user clicks on CTA, but email is not added or is a wacko one, then error state on the text field should be shown.

**Comment by pdrj** [comment]
@daividssilverio I see other two points in notion:
- [ ]  **Reset password - if user had already entered email in the "Log in" screen and then clicks reset psw... then email should already be prefilled.**
- [ ]  Reset password - if user clicks blue button on the keyboard it should act as the pink CTA "Send email" button on the screen.

Are we going to do them as a part of a separate issue? The first one requires a bit more work, but maybe we could at least handle the second one here?

**Comment by daividssilverio** [comment]
Definitely, the second point one can be fixed here already @pdrj ;
I'll take a look a the first point, if it's not too complicated, I'll just fix it already.

Not sure why I've skipped those 🤔

**Comment by daividssilverio** [comment]
Fixed them now as well @pdrj .

**Comment by pdrj** [comment]
OK, checking it out.

**Comment by daividssilverio** [comment]
Fixed via #7213
