### ISSUE TITLE
AutoFill issue on signup 

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#7217]
## ⛑️ User Support

A user reached out via Twitter saying they were able to sign up fo a Toggl account without a password using the iOS app (2.12 (52120000)) and shared a **[recording](https://drive.google.com/open?id=1qafalfPekC-wwA8f_5Z9gTzNrZgHe2z2)** of his happening. 

At 0:13 you can see that the iPhone created a password for them via the AutoFill feature. The issue here is that the user claims they tapped on "choose my own password" but their choice was disregarded and a password was created without being displayed in any way. The password field remained empty while the app was showing the loading circle before they signed up into their account. 

@vedr4n helped with testing and was able to reproduce this with version 2.12 and test flight version 2.13. 

## About the user

App version: 2.12 (52120000)
Phone OS: iOS 13.3.1
Phone model: unknown at the moment but this was reproduced on Vedran's iPhone 8

## Expected behavior
If the user selects to create their own password the AutoFill feature should not be creating one and if it does create one it should be displayed (with dots I guess) not leave the password field empty with a flashing cursor as if nothing was typed.

## To Reproduce
1. Start signing up for a new account
2. Select to choose your own password when the iPhone suggests creating one for you
Note: the video shows how the user was able to sign up and how it looks as if they did it without a password. 

## Suggestions
No suggestion, just a note that we checked with BE on what our API allows here so a password was definitely created by the iPhone because there's no way to sing up without at least a 6-character pass selected. 

Slack link for the initial [Tweet 🔗 ](https://toggl.slack.com/archives/C029WRP5S/p1584609252114500)

**Comment by vedr4n** [comment]
**Quick note**: If iPhone isn't auto-generating passwords for you, go to Settings -> Passwords & Accounts -> AutoFill Passwords and enable the iCloud Keychain option.

**Comment by sofokli1** [comment]
managed to reproduce, will investigate

**Comment by sofokli1** [comment]
I can't trigger the strong password in simulator in debug

**Comment by dshr** [comment]
Same as Juxhin, can't get the password suggestion to appear
