### ISSUE TITLE
After sending feedback, the confirmation toast reappears 

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#7222]
## 🐛 Bug Report
After sending feedback, the confirmation toast reappears 

## Context

Build/Branch: 2.13 android

## Expected behavior
The toast to appear once only.

## To reproduce
Go to settings, submit feedback.
Validate toast appeared.
Go to about section, go back to settings.
Toast should appear again.

**Comment by semanticer** [comment]
I can't reproduce this on current `develop` API level 29

**Comment by pdrj** [comment]
Still present on 2.14 Play Store for me. Also v29. I'll check develop later.

**Comment by pdrj** [comment]
[https://toggl.slack.com/archives/CD40QCV25/p1586940141276400?thread_ts=1586863933.262200&cid=CD40QCV25](https://toggl.slack.com/archives/CD40QCV25/p1586940141276400?thread_ts=1586863933.262200&cid=CD40QCV25)

video taken on current develop

**Comment by semanticer** [comment]
Ok, I finally managed to repro this but only with "Don't keep activities" developer option ON.

**Comment by heytherewill** [comment]
This bug is too specific and it's harmless. I checked the code and the fix would involve counting the number of feedbacks sent. Not worth the hassle, so I'm closing this
