### ISSUE TITLE
Sync fails on fresh login

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#7238]
## 🐛 Bug Report
When logging in to the app, the initial sync fails and the spider is displayed (the one with 'you haven't tracked time in a while' message). If you then pull to refresh, the TEs appear.

## Context

I've checked all Android releases back to v2.9. 2.9 is the last one that was working properly.

## Expected behavior
The initial sync to not fail and past time entries to appear.

## To reproduce
Logout of the app, login again.

**Comment by heytherewill** [comment]
I can't seem to reproduce this on current develop or in the play store. Was this not tied to some instability in the staging server? Did you use a specific account or could you reproduce it in any account?

pinging @pdrj

**Comment by semanticer** [comment]
I also have a hard time reproducing this @pdrj 
Please see Will's questions above.

**Comment by pdrj** [comment]
> Was this not tied to some instability in the staging server?
No, it was tested on release builds. 
> Did you use a specific account or could you reproduce it in any account?
My account, but @daividssilverio saw this issue intermittently too.

If you can't repro, then maybe see what changed between 2.9 and 2.10 and might have caused this 🤔

**Comment by pdrj** [comment]
Video posted to slack: [https://toggl.slack.com/archives/CD40QCV25/p1586938628275600?thread_ts=1586880254.270500&cid=CD40QCV25](https://toggl.slack.com/archives/CD40QCV25/p1586938628275600?thread_ts=1586880254.270500&cid=CD40QCV25)

It was taken on Play Store 2.14

**Comment by semanticer** [comment]
I Still cannot reproduce this. But as you mentioned there is a couple of suspicious changes in 2.10. 
We [reenabled background sync](https://github.com/toggl/mobileapp/commit/8ef4a50b5fa6bb3155224e93322633a19406465d) 
We used [sync error to trigger noWS UI](https://github.com/toggl/mobileapp/commit/3984725c3cfbc24a5536e29d6126e285afea9e60)
And also this [humongous PR ](https://github.com/toggl/mobileapp/commit/efb9dde6cdf0ccbd1ff1cf9a1947c2d18ac5e850)

**Comment by pdrj** [comment]
Damn, that's a lot to go through... Maybe since I seem to be the only one who can semi-reliably reproduce this, I'll take a look when it's my turn to deal with ☢️ stuff. Or if @daividssilverio can repro and his watch is before mine, he can also take a look.

**Comment by semanticer** [comment]
Sound good. I will deprioritize this for now and maybe see later if I can narrow down that suspect list.

**Comment by semanticer** [comment]
I'm giving this back it's a high priority since you will be handling this release.

**Comment by pdrj** [comment]
Last good commit: a7a99e2
8ef4a50 - I can't login on this one - the loading indicator just keeps spinning, I have to kill the app and enter it again to be in the logged in state
24e326b - I can login and it's broken. 

These 3 commits are consecutive. If, on 24e326b I revert #6936, specifically re-add the lines in `Toggl.Droid/SystemServices/BackgroundSyncJobSchedulerService.cs`, the initial sync is fixed. So - the cause seems to be 8ef4a50 (re-enable background sync); but I can't validate it on that specific commit.
