### ISSUE TITLE
Track onboarding carousel events

### ISSUE THREAD

**Issue by juanlaube** [toggl/mobileapp#7241]
## 🎯 What needs to be done?
We want to track when a page is scrolled in the carousel, either because it was automatically scrolled, or because the user swiped.
We also want to track one single event before leaving the onboarding view, to know which pages have been viewed.

## 📝 Detailed explanation
The events were previously added in #7197 so this should only take care of connecting the actions in Android.

Depends on #7197

**Comment by smilechka** [comment]
"To make it official":)
For the time being let's track how many screens of the carousel the user has seen. I.e. I want to know at the end whether the majority of users reach to the last screen. The rest can wait until Aurora is launched.
