### ISSUE TITLE
Bottom navigation bar issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#7265]
##  ⛑️ User Support

If you go to the calendar view and tap on an event, then tap back (or swipe to go a step back depending on the nav settings) the bottom navigation bar disappears. I recorded a video of that happening, you can find it **[HERE](https://drive.google.com/open?id=16GFuhXpK5nl-9VxP4pUgR2v2v3IArPja)**.

## About the user

App version: Giskard/2.12
Phone OS: Android 10
Phone model: Pixel 3

## Expected behaviour
Tapping "back" (or swiping back) should just deselect the selected calendar event

## To Reproduce
1. Go to Calendar
2. Tap on an event
3. Tab "back"

Intercom case **[link 🔗](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/26376460622)**

**Comment by pdrj** [comment]
Thanks for the report @VeljkoTN. We have been aware of that for a bit though: https://github.com/toggl/mobileapp/issues/7096 and the fix will go out in the next release (2.14).
