### ISSUE TITLE
Implement a 3-way merge with conflict resolution

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#7283]
## 🎯 What needs to be done?
Implement the per-property 3-way merge with conflict resolution.

## 🛠 Technical remarks
This is an epic issue and this needs a bit more discussion.

## 🖼 Express your sentiment towards the issue
The proper 3-way merge:

![](https://media.giphy.com/media/21PV0Su6USswD76iLv/giphy-downsized.gif)

**Comment by simonrozsival** [comment]
This issue has already been closed by a PR merged into a feature branch.
