### ISSUE TITLE
App gets stuck while trying to log into an account with a password shorter than 6 characters

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#7298]
## 🐛 Bug Report
See title.

## Context
Build/Branch: iOS 2.13
Phone OS: 13.3.1
Phone model: iPhone 7

## Expected behavior
The users should either get logged in or get an explicit message saying that the password is too short.

## To reproduce
Get back-end to create you an account with a short password and try logging in.

## Suggestions
If reproducing fails, then we can just test for shorter passwords on our end and tell the users to change them.

**Comment by amulware** [comment]
Has this been checked on Android?

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/26583661321)

**Comment by amulware** [comment]
Also note that you don't need a test account to replicate this - even a nonexistent account gets stuck. (Though please test the FIX on a real account as well, to verify that login actually works.)

**Comment by arturs105** [comment]
Does not happen on the current App Store version (2.14.2). Could not reproduce on Android from latest `develop` as well.
