### ISSUE TITLE
Users cannot press start button to create a time entry or edit time entries

### ISSUE THREAD

**Issue by dianetoggl** [toggl/mobileapp#7299]
## 🐛 Bug Report
Users on iOS (13.4 & 13.4.1) 2.14 cannot press the green play button to create a time entry. Users are also unable to tap any element on the "Edit Entry" screen. 

Multiple user reports. Logging out and in and uninstalling and reinstalling changes nothing.

## Expected behavior
User can start a time entry by clicking the play button.

## To reproduce
Be on iOS 13.4 and 13.4.1  and try to create a time entry. 

## Suggestions
Cases below:
[Case 1](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26596177370)
[Case 2 - Video included](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26595956739)
[Case 3 - Video Included](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26592625741)
[Case 4](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26593646419)
[Case 5](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26598100065)
[Case 6 - Video Included](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26592950787)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26598309222)

**Comment by dianetoggl** [comment]
Case reference

**Comment by dianetoggl** [comment]
Case references:
[One](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26598550728)
[Two](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26598787233)
[Three](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26599214512)
[Four](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26599234826)

**Comment by dshr** [comment]
Closed with the release of 2.14.1. It was related to https://github.com/xamarin/Xamarin.Forms/issues/10162, submitting a build built with a non-broken version of VS4Mac solved it.
