### ISSUE TITLE
Creating a calendar time entry that starts at 00:00 creates a duplicate entry for the previous day

### ISSUE THREAD

**Issue by vedr4n** [toggl/mobileapp#7300]
##  🐛 Bug Report
If you use the Calendar to create a time entry that starts exactly at midnight, that same entry will be added to the previous day, as well. 

This is a "phantom" entry, it will be visible in the Calendar, but not on the Timer screen. 

## Context

Build/Branch:
Phone OS: iOS 12.4.6. Also tested on iOS 13.3.1
Phone model: iPhone 6. Also tested on iPhone 8. 

## To reproduce
1. Using the Calendar, create a time entry for today that spans from 00:00 to 01:00.
2. Navigate to yesterday in the calendar. You should see the entry. 

Bonus weirdness:
Edit the original entry (for today) and set the start time for 00:01. The phantom entry should disappear. 

## Suggestions
If you're struggling to reproduce, open the [Intercom conversation](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26584131354). User shared screenshots.

**Comment by heytherewill** [comment]
This is also happening on Android, so the bug must be in the shared layer
