### ISSUE TITLE
Figure out testing for the unsyncable entities dump

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#7309]
Followup of #7104

This still wasn't 100% figured out in the issue above, so let's do it here.

Here's what was suggested in said issue:

>We could add something that triggers sharing the json file with other apps so we can inspect the contents, maybe triggered by a not-so-obvious gesture like tapping 7 times on the version number or a keyboard shortcut?

>Same way we test loss of workspace access UI. The popup in setting for testing these cases seems like a good place to manually trigger it.

>We can create an unsyncable TE (extra long description for instance) and then inspect the file's contents. That inspection tool can be accessed via settings, as suggested above.

**Comment by semanticer** [comment]
I would be consistent with our previous hidden testing method and access this via Settings -> Help -> Long Press. But I'm not 100% sure how would that "inspection tool" look like.

**Comment by arturs105** [comment]
Yeah, i agree that having something similar to previous hidden testing method makes sense. 🤔 Maybe we could even add another button to the same screen.

But as to what the inspection tool should look like, i think we could simply use the system's sharing functionality and then Airdrop, e-mail or do whatever with the file to inspect it's contents.
