### ISSUE TITLE
New Copy Translation Request - Password security criteria

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#7332]
**Target Languages:** 
PT
JP
FR

**New Copies:**
- Include 8 or more characters, with at least one uppercase letter, lowercase letter, and a number.
- One more try before account gets locked for 5 minutes.
- Account is locked for 5 minutes. Account owner has been notified.
- Incorrect email or password.

~~**EDIT - adding another string**
Set a secure password~~
It turns out 'Set a secure password' won't be needed after all

**Comment by pdrj** [comment]
pt-br: Inclua 8 ou mais caracteres, com ao menos uma letra maiúscula, uma letra minúscula, e um número.

thanks to @heytherewill

**Comment by pdrj** [comment]
Adding one more string:
Set a secure password

**Comment by pdrj** [comment]
Already adding copy for the second phase:
- One more try before account gets locked for 5 minutes.
- Account is locked for 5 minutes. Account owner has been notified.
- Incorrect email or password.

**Comment by heytherewill** [comment]
I'm by no means a french speaker, so take my french with many grains of salt and run the translations through a native speaker before adding them to the app :)

- Include 8 or more characters, with at least one uppercase letter, lowercase letter, and a number.
🇧🇷 Inclua 8 ou mais caracteres, com ao menos uma letra maiúscula, uma letra minúscula, e um número.
🇫🇷 Inclue 8 ou plus caractères, au moins une lettre majuscule, une lettre minuscule, et un numéro
- One more try before account gets locked for 5 minutes.
🇧🇷 Você tem apenas mais uma tentativa de login antes da sua conta ser bloqueada por 5 minutos.
🇫🇷 Vous pouvez essayer seulement un altre fois Puis, votre compt sera bloqué.
- Account is locked for 5 minutes. Account owner has been notified.
🇧🇷 Conta bloqueada por 5 minutos. O dono da conta foi notificado.
🇫🇷 Compte bloqué par 5 minutes. La propriétere de le compte a été notifié .
- Incorrect email or password.
🇧🇷 Email ou senha incorreta.
🇫🇷 Email ou mot de passe incorrect.

**Comment by daividssilverio** [comment]
- Include 8 or more characters, with at least one uppercase letter, lowercase letter, and a number.
  🇯🇵 8文字以上でなければなりません。英字の大文字や小文字、数字、番号を一つずつー以上の文字を入れてください。
- One more try before account gets locked for 5 minutes.
  🇯🇵 もう一回間違っていたら、アカウントが五分間までにロックになります。
- Account is locked for 5 minutes. Account owner has been notified.
  🇯🇵 アカウントがロックされました。アカウント持ち主が連絡されました。
- Incorrect email or password.
  🇯🇵 メールかパスワードが間違っている。

**Comment by daividssilverio** [comment]
My teacher helped me out with some reviews, here are the reviewed translations:

- Include 8 or more characters, with at least one uppercase letter, lowercase letter, and a number.
🇯🇵 8文字以上で大文字・小文字・数字を最低1回ずつ使用してください。
- One more try before account gets locked for 5 minutes.
🇯🇵 もう一度間違えると5分間アカウントにロックがかかります。
- Account is locked for 5 minutes. Account owner has been notified.
🇯🇵 アカウントがロックされました。アカウントの持ち主に通知されました。
- Incorrect email or password.
🇯🇵 メールまたはパスワードが間違っています。

**Comment by fdelbos** [comment]
Include 8 or more characters, with at least one uppercase letter, lowercase letter, and a number.
🇫🇷 Inclure 8 caractères minimum, avec au moins une majuscule, une minuscule, et un chiffre
(tbh "include" sounds kinda useless, could be remove completely imho)

One more try before account gets locked for 5 minutes.
🇫🇷 Vous avez encore un essai, ensuite bloqué votre compte sera bloqué pendant 5 minutes.

Account is locked for 5 minutes. Account owner has been notified.
🇫🇷 Compte bloqué pendant 5 minutes. Le propriétaire du compte a été notifié .

Incorrect email or password.
🇫🇷 Email ou mot de passe incorrect.
