### ISSUE TITLE
Force users to update to new version with updated default colours

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#7335]
## 🎯 What needs to be done?
We need to teapot all users with app versions before 2.15 so they all use the new project colours. This issue does not require a PR.

Depends on #7334

**Comment by heytherewill** [comment]
Please be aware of backend deadlines and **do not request this unless 2.15 is out for all users for at least a few days so no one gets locked out of the app**.

Also, please coordinate with @pdrj, since the project he is on might require a teapot as well.

**Comment by heytherewill** [comment]
Please link the request issue here as well, for tracking sake

**Comment by dshr** [comment]
Deprecation issue is here: https://github.com/toggl/operations/issues/1477

**Comment by heytherewill** [comment]
This can be closed
