### ISSUE TITLE
Tooltip: “Tapping here will start the timer”

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#7361]
## 🎯 What needs to be done?
We need a tooltip pointing to the start time entry button saying "Tapping here will start the timer"

## 🎨 Graphical resources
https://toggl.invisionapp.com/share/2YX4NEV7WF5#/screens/416141751

## 🛠 Technical remarks
**The tooltip should be shown when:**
- The user has not seen onboarding (old one or new one)
- The user has not seen this tooltip before
- The user logged in and has stopped time entries, but doesn't have a running one
- This tooltip isn't shown after sign up

**The copy for the tooltip:**
```
Tapping here will start the timer
```

**Still have questions?**
Check this [Miro diagram](https://miro.com/app/board/o9J_kwnl_Z0=/?moveToWidget=3074457347628738556&cot=6).

## 🔗 Dependencies
Depends on #7366 and #7367
Before working on this check the progress and assignment of [relevant iOS issue](https://github.com/toggl/mobileapp/issues/7360), since there may be some overlap in the Foundation layer.

## 🏆 Outcome
- [ ] The tooltip has the new blue design
- [ ] It is shown above the start time entry button
- [ ] It is shown if user logs in and has time entries, but none of them are running
- [ ] It isn't shown after sign up
- [ ] It is not shown if onboarding has been completed (old or new)
- [ ] It is shown only once and then never again.

**Comment by heytherewill** [comment]
Closed by #7505
