### ISSUE TITLE
Custom project colour selector does not seem to work

### ISSUE THREAD

**Issue by dshr** [toggl/mobileapp#7381]
## 🐛 Bug Report
When trying to set a custom colour both the HS and B selectors don't seem to change the selected custom colour, and selecting the default custom colour seems to break the selector altogether, with no further colours being selectable.

## Context
Build/Branch: `develop`
Phone OS: iOS 13
Phone model: iPhone 7

## Expected behavior
The selectors should update the custom colour, and the user should be able to select any colour they want.

## To reproduce
Get yourself a Premium WS, and then try using the custom colour picker.

## Suggestions
My hunch is that this might've been caused by the HSV->HSB switch.

**Comment by pdrj** [comment]
I'll remove this from Android 2.15, since all seems good on the Android side. It might not be a problem in the shared layer 🤷‍♂️.

I've seen some warnings about unsatisfiable constraints when testing on iOS, so maybe that is a cause? 🤔
