### ISSUE TITLE
Do not change time entry if user confirms changes without making any

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#739]
Let's think this through, to see how it should interact with time entries marked as unsyncable.

Maybe we DO want entries to be saved to make sure the user can try syncing them again with the same data (in case the app ever temporarily messes things up).

Or maybe we not.

If not, it may be enough to toggle a save-on-confirm bool on any edit, and allow the user to change a field back and forth to trigger a save, even though the data didn't change strictly speaking.

Or maybe we want to go fancy and actually compare the entire TE.

**Comment by arturs105** [comment]
I'm leaning towards saving even if there were no changes. If the user wants to save a time entry with no changes, let's allow him to do that.

Furthermore, if the user notices that pressing "Confirm" syncs the time entry on some occasions, but not on others (if we decide to not save unchanged time entries), it might be confusing for the user to not know why the sync sometimes starts and sometimes doesn't.

**Comment by simonrozsival** [comment]
What @arturs105 mentions isn't in fact related - Push sync would be triggered even when the entry wasn't updated in the database. User wouldn't notice any difference. The only difference might be when the user is offline and the TE cannot be synced so we would show the icon in the log and user will get a confirmation dialog if he tried to logout.

I don't think we need this change in the near future and maybe at all.

**Comment by amulware** [comment]
Maybe we want this in the future, but it isn't important for now.
