### ISSUE TITLE
Add Sync Pull

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#7440]
## 🎯 What needs to be done?
A database query needs to be created and an interactor that will call it that will perform the sync pull.

## 📝 Detailed explanation
Sync pull needs to gets the `all` data from the sync server and perform an update of the local state by performing a conflict resolution on the time entries. It also needs to make sure to stop any locally running time entries if the payload contains a running time entry.

## 👕 Estimated complexity
`Large`

**Comment by simonrozsival** [comment]
This issue has already been closed by a PR merged into a feature branch.
