### ISSUE TITLE
Handle tags for different workspaces in start view

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#745]
When selecting a project in the start view that causes the time entry to change workspace (starting with the default WS of course), tags have to be cleared.

Similar to #716

Whether there should be a dialog for confirmation or something similar depends on @pe0ny.

Also consider that since the time entry without project will start out in the default workspace, and what to do when the user selects a tag from there, and then selects a project from a different workspace.

**Comment by kornelijepetak** [comment]
Also, if user selects some tags before choosing a project, should we delete all tags or just those that are not in the selected project?

Also, isn't workspace also _selected_ by choosing a tag from it, just as it happens with choosing a project?

**Comment by amulware** [comment]
I don't think it should EVER show tags from more than one workspace, so at first only the default one. Following that tags can never cause a change in workspace.

**Comment by amulware** [comment]
There is an argument to be made for 'keeping' tags that have an equivalent (same name) in the new workspace, but that's something for later maybe.

**Comment by pe0ny** [comment]
> I don't think it should EVER show tags from more than one workspace, so at first only the default one. Following that tags can never cause a change in workspace.

Yes. We should always show tags from one WS, not from multiple workspaces.
When user selects a project from a different WS, we should show same popup as mentioned here #716
