### ISSUE TITLE
Preferences changes are not propagated to the server

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#7464]
In SyncV2 there's an issue with propagating preferences changes to the server:
- the app is synced
- the user changes duration format in settings
- the local database is modified correct (preferences duration format is changed, sync status is set to `SyncNeeded`)
- we pull data and overwrite the local state of preferences
- there is nothing to push to the server anymore.

**Comment by simonrozsival** [comment]
Idea: we might want to use the 3-way-merge for preferences and use the `wasDirty` and `shouldStayDrity` combo as in #7457

**Comment by kornelijepetak** [comment]
This should be done for the `User` as well, as some of the preferences are there as well.

**Comment by simonrozsival** [comment]
The implementation was merged into the feature branch.
