### ISSUE TITLE
Change `sync-server` URL for both staging and production

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#7471]
We currently don't know the final URLs for the `sync-server`. As soon as we know them, we have to put them in the source code.

**Comment by simonrozsival** [comment]
We already have the most likely final version in #7481, but the STAGING version is hardcoded for now. I'm keeping this issue open for now so that we remember to restore the switching based on the `USE_PRODUCTION_API` constant once we're about to create a production build.

**Comment by kornelijepetak** [comment]
Resolved by #7529
