### ISSUE TITLE
Add integration test for deleting a time entry which is locked

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#750]
A workspace report can be locked at a certain date:

Endpoint: `GET/POST /workspaces/{workspace_id}/preferences`
Preference: `report_locked_at` (a date value)

This is an enterprise and premium feature.

We should expect some 4xx error when deleting a time entry which is locked by this mechanism is attempted.

**Comment by amulware** [comment]
Closing this, since this should be included when we start considering time entry requirements and workspace settings in general.
