### ISSUE TITLE
Better handle 4xx http errors

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#751]
There could be many reasons for that, and we should try and handle all we can detect appropriately.

(list to be compiled)

**Comment by amulware** [comment]
The errors we need to handle are:

410: Stops sync, and shows a special screen preventing the user from interacting with the app until they update
418: Same as 410, but a different screen
401: Same as 410/418 but the screen allows the user to re-login (with the same email). If that login succeeds, we can overwrite the user object with the new api key, reinitialise the api and maybe data sources, and let the user back into the app. Otherwise, the user also has the option to log out which may cause data to not be synced.

In all three cases, if the user closes and reopens the app, it should NOT start sync, and instead immediately show the respective screen.

We need to:
- figure out how to perform these three checks for every single api call (maybe using a custom rx extension?), and then stop the sync man each time (hopefully without needing extra transitions everywhere)
- figure out how to get this data out of the sync man, probably using one or several observables (injected into the states?), so we can show the respective screens
- store this data locally so it can be considered when the user relaunches the app
- figure out how the stored 410 and 418 can be invalidated by updating the app (maybe store the offending version number and compare against the current one?)

It's quite possible I'm missing further complications, but this should cover most of it.

**Comment by amulware** [comment]
Before implementing this, I'd like a design here that covers all the above, and any other (corner) cases that we can find for discussion.

**Comment by simonrozsival** [comment]
> figure out how to perform these three checks for every single api call

- I'm not sure if it is a good idea to create Rx extensions. All of our HTTP calls go through the `BaseApi` class and so we should catch these errors (client exceptions) there and persist the information about the problem and then somehow notify the Foundation.MvvmCross layer so it navigates the user to the desired view

    - this way we don't even have to do anything in the sync manager. These errors shouldn't be caught by any state and so the sync manager will error out and will stop syncing (but maybe we should freeze it automatically then?)

**Comment by amulware** [comment]
If I'm not mistaken, right now any 400 error will cause the entity to be marked as unsyncable and the sync to proceed, so we still have to catch these errors here separately there anyways to make sure the sync is aborted, right?

If so, I see no reason to complicate the API. In general, I don't like that either, it's already passing the exception on correctly, what more can it do? Everything else should be up to whoever calls it.

Once we make these errors abort and get out of the sync man though, maybe they can be exposed as the 'reason' for the Failed event in #661, and foundation/ui can check that reason and determine how to react to it?

**Comment by simonrozsival** [comment]
Yes, any `ClientError` transition (caused by `ClientErrorException`) goes to the `MarkAsUnsyncable` state.

This is done in single class (`BasePushEntityState`) and we can filter the exceptions by type here easily and react to them appropriately here (rethrow them), instead of reporting the `ClientError` transition.

If the state machine errors out, `StateMachineOrchestrator` receives the `StateMachineError` event with the exception which caused it, se we can handle it here and inform the UI of what exactly is going on.

**Comment by amulware** [comment]
That makes sense. Note however that we also do API calls when fetching data, and we have to handle the same errors there.

**Comment by simonrozsival** [comment]
I will make sure not to forget about that.

Also there are 3 more cases when we make HTTP requests outside of the sync process:
- login
- sign-up
- forgotten password

These happen "outside of the app" and should be somehow handled as well.

**Comment by amulware** [comment]
410 and 418 should probably be handled the exact same way: show an overlay and have the user upgrade.

**Comment by amulware** [comment]
Judging by #661 This will boil down to catching 401, 410 and 418 and rethrowing them for the state machine to fail, the sync to stop, and the UI to handle them?

**Comment by amulware** [comment]
I just realised from the title of this that I accidentally conflated two issues. All the above should have been in #306. But let's leave it like it is.
