### ISSUE TITLE
Three way merge has issues

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#7541]
The title might be a bit confusing, I'll try to describe it with steps to reproduce it:
1. start a running time entry
2. stop the TE "immediately" (before syncing completes)
3. the TE reappears

What happens:
- the TE is being pushed to the server
- when the TE is stopped, it's `Duration` is set to some finite value
- when the response from the server gets back to the app, the `Duration` is overwritten with the value from the server ... which is `null`
- the TE is "resurrected" and it's running again

I thought we fixed this with #7526, but apparently it wasn't.

I found out that this issue is not specific to only TEs, but it also manifests for preferences and therefore I suppose that for updating user settings as well.

**Comment by simonrozsival** [comment]
I can still reproduce this issue in the latest AdHoc build (both TE and preferences). Apparently this wasn't fixed by #7542.

**Comment by simonrozsival** [comment]
This issue was fixed for TEs so I'll close it and I'll open a one specifically for preferences and user settings.

**Comment by simonrozsival** [comment]
This issue hasn't been resolved even by #7555.

**Comment by kornelijepetak** [comment]
But it is by #7558
