### ISSUE TITLE
Modifying preferences while they're being pushed does not work

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#7550]
This is a follow-up of #7541.

More precisely: the local changes are lost when we pull data from the server before we attempt to push the second update. How to reproduce:
1. Make sure the app is synced and that you're using Sync V2
2. Go to settings
3. Change duration format to some different value
4. Immediately flip the Collapse similar TEs switch
5. Once the app is synced, the switch will flip itself back to its original state (and so will the setting in the database)

**Comment by simonrozsival** [comment]
This issue was solved yesterday.

**Comment by simonrozsival** [comment]
It turned out that #7551 didn't fix the issue.

**Comment by kornelijepetak** [comment]
But #7558 seems to have.
