### ISSUE TITLE
Continuing TEs does not play nice with 3WM

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#7559]
## 🐛 Bug Report
This is a bug in the current implementation of Sync V2.

Steps to reproduce:
1. Make sure there's no running TE and the app is synced with the server
2. Start a running TE A in the mobile app
3. Wait for the app to sync.
4. Start a running TE B in the mobile app by continuing some older TE
5. Wait for the app to sync.
6. Instead of A being stopped and B running, the app will restore A as a running TE and stop B.

## Suggestions
When continuing a TE (or starting it from a suggestion, or from Siri extension or from a widget), we rely on the _rivals resolver_ to stop the previously running TE in the `BatchUpdate` method. When we stop the running TE, we don't "back up its duration"...

**Comment by kornelijepetak** [comment]
Closed by #7558
