### ISSUE TITLE
Add project, task and client to currently running time entry

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#756]
Currently running time entry card displays only description. Project task and client could be added as a separate label so `ProjectTaskClientValueCombiner` could be reused for that.

**Comment by arturs105** [comment]
Before work on this is started, we should wait for #755 to be merged (or closed).

**Comment by pe0ny** [comment]
Seems to be broken. It shows the project/task for a sec and then disappears. Also, it shows project/task normally after restarting the app.

**Comment by arturs105** [comment]
It's broken currently because `TimeEntriesDataSource.CurrentlyRunningTimeEntry` emits 2 entries after starting time entry and the second one doesn't have a project set, so project name and color are cleared from `MainViewModel`.
