### ISSUE TITLE
Pull sync result processing query confuses deleted entities with running TEs

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#7560]
## 🐛 Bug Report
When you lose access to a TE, GAD returns just the `id` and `server_deleted_at` properties. It looks like this:

```json
{
  "id": 1593096546,
  "server_deleted_at": "2020-06-21T22:03:58+00:00"
}
```

Our deserialization then thinks that `Duration` is `null` and calling the `IsRunning()` method on this TE will return `true` and our pull processing interactor will behave unpredictably.

## Suggestions
Check that the server running TE is not deleted.

**Comment by kornelijepetak** [comment]
Closed by #7558
