### ISSUE TITLE
Add a link to our Blog via Settings menu

### ISSUE THREAD

**Issue by djalex15** [toggl/mobileapp#7644]
## 🎯  What needs to be done?
Addition of a **link** to our **Toggl Blog** from the mobile app **Settings** menu - for both iOS & Android.

## 📝  Detailed explanation
The addition of a sub-menu option in **Settings** which links to our Blog - should work pretty much like the **Help** sub-menu which leads users to our Knowledge Base.

Currently, it will lead people to main Blog page, but we will update it with a new tag catered to mobile users in the next update. For now, please add these links:

**iOS:** 
https://toggl.com/blog/tag/mobile-productivity?utm_source=ios&utm_medium=app&utm_campaign=settings-link

**Android:**
https://toggl.com/blog/tag/mobile-productivity?utm_source=android&utm_medium=app&utm_campaign=settings-link

(we added some tags for tracking on GA)

_NOTE: If for some reason the tagged links aren't working, please use one without UTMs:
https://toggl.com/blog/tag/mobile-productivity_

**_Regarding Tracking:_** I'm not sure if there needs to be an additional parameter set or something so we can track this or will it be added natively (maybe Firebase event -> Blog Opened?) - this is for Firebase tracking.

## 🎨  Graphical resources
iOS: https://toggl.invisionapp.com/project/19996504
Android: https://toggl.invisionapp.com/project/20106285

## 🏆 Outcome
- Link to blog exists in **Settings**
- User clicks on the link -> blog opens up via in-app browser (confirmation by Milad needed re UX)
- We get a tracking link confirmation that blog was opened via mobile app

## 👕  Estimated complexity
Should be pretty easy as per @heytherewill comment during the meeting yesterday 😅

## 🖼  Express your sentiment towards the issue
_Let there be blog!_
https://giphy.com/gifs/SpoV1pB4g7gXvWo3Up/html5

**Comment by Milad** [comment]
I believe I was tagged here by mistake.

**Comment by djalex15** [comment]
> I believe I was tagged here by mistake.

Yes, my bad - sorry about that 😅

**Comment by milaads** [comment]
@djalex15 Hey.
Here are the design: https://toggl.invisionapp.com/project/19996504
https://toggl.invisionapp.com/project/20106285

**Comment by djalex15** [comment]
Thanks! 

Updated initial comment with designs.

**Comment by djalex15** [comment]
Made an update to original comment with links that should be used - we're good to go on our end 😄  🏁

**Comment by djalex15** [comment]
Link Update in original comment!
