### ISSUE TITLE
Create a way to partially serialise objects

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#77]
When making a POST request only a few of object's properties are needed, for example, when POSTing a `Client`, only it's `Name` and `WorkspaceId` are needed (`Id` and `At`) shouldn't be posted.

This could be achieved with attributes.

**Comment by amulware** [comment]
Minor correction: when posting new entities like clients, the workspace id is only included in the url, not the json.

Also note that I'd like to see alternatives to using attributes if there are any good ones.

**Comment by willsb** [comment]
[This](http://www.newtonsoft.com/json/help/html/ConditionalProperties.htm) is the default way. I prefer using annotations. We could have:

- A fody plugin that yields IL methods based on annotations.
- A custom serializer that reads said props and decides whether to serialize or not.
- Manually add the methods that decide whether something should be included or not (gross).
