### ISSUE TITLE
Stopping a running TE from calendar contextual menu breaks the UI

### ISSUE THREAD

**Issue by pdrj** [toggl/mobileapp#7815]
## 🐛 Bug Report
See the bottom of the screenshot
![WhatsApp Image 2020-10-08 at 15 05 21](https://user-images.githubusercontent.com/53510080/95462415-c5d8a580-0977-11eb-9d29-8194d7d9b06e.jpeg)

## Context

Build/Branch: 2.20
Phone OS: android
Phone model:

## Expected behavior
The calendar view looks correctly (no fab, or no bottom menu and fab correctly positioned)

## To reproduce
Stop a running TE from calendar contextual menu

## Suggestions
None

**Comment by arturs105** [comment]
Can't reproduce this on Pixel 3 API 30 emulator.

**Comment by arturs105** [comment]
Is reproducable on API 23
