### ISSUE TITLE
Create a custom UITextView with placeholder

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#783]
The title says it all.

Possible inspiration: https://github.com/devxoul/UITextView-Placeholder

Needed wherever we have a multiline TextView and a need for a placeholder.
Currently:

* TE Edit View > `Description` field

**Comment by amulware** [comment]
Please add where we need this, thanks!

**Comment by kornelijepetak** [comment]
I have. If anyone else knows some other places, feel free to add a comment or edit the OP.

**Comment by amulware** [comment]
@kornelijepetak What is the status on this?

**Comment by kornelijepetak** [comment]
I will see that this gets merged today. I just need to integrate with #944 which shouldn't be that much of a problem. Or so it seems. :)
