### ISSUE TITLE
Color of disabled "switches" in the Settings view

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#7848]
## ⛑️ User Support

One user reached out confused about the color of the switch to enable calendar permissions in the settings view. This appears to be the case with all the switches in the app, when something is disabled the switch color remains pink instead of turning gray to visually indicate that a feature/option has been disabled. 

## About the user

App version: Aurora 0.2
Phone OS: Android 9
Phone model: OnePlus 5T

## Expected behaviour

When a feature is disabled in the settings view the switch should slide over to the left side and turn gray

## To Reproduce

1. Open the Android app (Aurora 0.2)
2. Go to Settings
3. Disable something and observe the switch color
NOTE: the user who reported this is on Android 9, I can reproduce on Android 10 (Samsung One UI 2.5)

**Comment by daividssilverio** [comment]
Closing as this is a problem in the new apps.
