### ISSUE TITLE
Reports default date range showing 8 days.

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/mobileapp#7860]
## ⛑️ User Support
When you switch to the Reports view in the app you will see the today + past 7 days as the default date range, showing a total of 8 days. This happens in both iOS and Android.

## About the user

App version: Android Aurora 3.0.2
Phone OS: Android 10
Phone model: Sony Xperia XZ2

## Expected behaviour
The app should show "This Week" by default just like the Reports page does in the web app

## To Reproduce:
1. Open the Track app on Android or iOS
2. Go to Reports
3. Check the default date range

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307907505)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481308225405)

**Comment by VeljkoTN** [comment]
closing this in favor of https://github.com/toggl/android/issues/1697
