### ISSUE TITLE
Disallow multiple navigation

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#789]
This gif says all:

![oct-25-2017_15-22-04_360](https://user-images.githubusercontent.com/3987892/31998649-da4386aa-b990-11e7-9729-50028c4a2603.gif)

It's not as easy to reproduce on an actual device, but it can be done.

**Comment by simonrozsival** [comment]
I'm not able to reproduce it. Isn't it possible that @arturs105 fixed this when he refactored the nested presentation (https://github.com/toggl/mobileapp/pull/1175)?

**Comment by willsb** [comment]
Doesn't sound like the case, @simonrozsival, given Settings uses `ChildPresentation`.

This could, however, have been collaterally solved by #1152. If no one else can reproduce this I say we mark as invalid and carry on

**Comment by amulware** [comment]
I'll try and reproduce it.

**Comment by amulware** [comment]
Yap, this has definitely been fixed.
