### ISSUE TITLE
Fix resizing the container view on content size change in Edit View

### ISSUE THREAD

**Issue by kornelijepetak** [toggl/mobileapp#790]
Currently, when the Edit View content grows or shrinks, its container view is resized accordingly, but only on second layout update.

Steps to reproduce:

* Open TE Edit View
* Write some text into Description field
* Write enough (but one by one) characters and look what happens when it goes to the next line
* The moment it jumps to the next line, the modal dialog should resize, but *it doesn't*
* Any other layout-inducing change at this point (e.g. adding more characters) will correctly resize the container

**Comment by simonrozsival** [comment]
This issue was resolved and is not present in 1.5 anymore (and it was probably already fixed in some earlier version).
