### ISSUE TITLE
Only POST/PUT paid feature fields if workspace has relevant feature enabled

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#796]
Currently, this affects these two properties of time entries:

```csharp
public long? TaskId { get; set; }
public bool Billable { get; set; }
```

My idea of how this might work is:

- we inject the feature set of the relevant workspace when POST/PUTting (I don't see a way for the time entry itself to know this information about itself)
- we have an attribute on the above properties, something like `[RequiresFeature(Pro)]`
- update the serialiser to take into account the injected features and the attribute

**Comment by amulware** [comment]
I would also like integration tests that this works and assuming the API fails like it should when including these properties for an unpaid workspace, tests that verify this.

**Comment by simonrozsival** [comment]
Use attribute created in PR #617

**Comment by simonrozsival** [comment]
`BaseApi.CreateObservable` needs to be given the workspace features - now it always defaults to `null`. We should inject the `Database.WorkspaceFeatures.GetById(long workspaceId)` to the `TimeEntriesApi` and then use it before every request `Create` and `Update` request.

**Comment by simonrozsival** [comment]
So in this task we only need to inject the getter function in a nice way and create the integration tests for the time entry. This should not be very hard to do.

**Comment by amulware** [comment]
Delaying this until there is clearer word on desired and intended behaviour from backend.

**Comment by simonrozsival** [comment]
Are there any updates to this issue?

**Comment by amulware** [comment]
In principle, we should only include supported fields. In reality, this is not enforced, and indeed those fields will simply be ignored as if we hadn't sent them I believe.

Is the associated PR still reasonably up to date? If so, I can check on it to see how I like the approach.

**Comment by simonrozsival** [comment]
It won't be hard to update the old PR, there are only a few simple conflicts. Check it out and if it seems worth it, we can use it, otherwise let's close it, so that it doesn't haunt us (me?) any more.
