### ISSUE TITLE
Project creation

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#797]
- [x] User can create new project in time entry creation flow
- [x] User can create new project in projects view (when editing time entry)
- [x] Show '+ Create project "new-project-name"' at the top of the list when user has typed in project name that doesn't exist yet.
- [x] By default assign new project under default workspace
- [x] When user taps '+ Create project "new-project-name"', open 'New project' view

**Comment by amulware** [comment]
This is only about showing the "+add new project" at the top of the list in both creation and edit views.

The screen itself is in #798 and its details are in further issues.
