### ISSUE TITLE
Client creation

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#800]
- [x] User can create new client in Clients view
- [x] Show '+ Create client "new-client-name"' at the top of the list when user has typed in client name that doesn't exist yet.
- [x] Assign new client under the workspace that was selected in 'New project' view
- [x] When user taps 'Create', save and select client, and direct user back to 'New project' view
- [x] When user taps '<' arrow, take user back to 'New project' view without saving anything
- [x] When user taps 'x' clean the input field and show list of existing clients

![toggl - ios - add new client 1x](https://user-images.githubusercontent.com/5064445/32044151-690dd890-ba45-11e7-8d81-4feb8bc3e9f9.png)

**Comment by amulware** [comment]
How do we prevent duplicate client names?

**Comment by pe0ny** [comment]
I think with clients we shouldn't display '+ Create a new client "x"' when this client name already exists. Then we should let user only to select this client.
