### ISSUE TITLE
Workspaces view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#801]
- [x] User can access workspace list when creating new project (from 'New project' view)
- [x] '<' arrow takes user back to 'New project' view without saving anything
- [x] When user selects a workspace from a list, save and take user back to 'New project' view
- [x] User can only filter workspaces
- [x] When user selects another ws while client being added already, reset client field

![toggl - ios - change workspace 1x](https://user-images.githubusercontent.com/5064445/32045490-14ce5314-ba49-11e7-8663-0541a14b2c9e.png)

**Comment by amulware** [comment]
When the user selects a new workspace, that workspace might have different features enabled. How does that interact with the paid parts of project creation?

For example, do we have to check if the user has selected a non-default colour, and switch to a default one? To a random one, or the closest one to the one the user selected?

Are there any other fields that might run into issues with this?

**Comment by pe0ny** [comment]
- When user switch to free ws and has selected non-default color, let's assign a random default color to the project.
- Templates are also starter plan feature which means we should clear that field when user selects free ws. Also, project can't have billable rates, estimates or tasks then.
