### ISSUE TITLE
Templates view

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#802]
- [ ] User can access templates list when creating new project (from 'New project' view)
- [ ] Show templates only from WS that was selected from New project view
- [ ] Show 'No template' option as well so user can deselect a template if needed
- [ ] '<' arrow takes user back to 'New project' view without saving anything
- [ ] When user selects a template from a list, save and take user back to 'New project' view
- [ ] User can only filter templates

Zeplin: https://zpl.io/V4EozDX

![toggl - ios - add template 1x](https://user-images.githubusercontent.com/5064445/32046052-9496e998-ba4a-11e7-986f-f8285c469143.png)

**Comment by amulware** [comment]
When selecting a template, which fields for the new project are copied exactly? Are they copied even if the user has already selected some of them?

What happens to any fields when 'no template' is selected?

**Comment by pe0ny** [comment]
**When selecting a template, which fields for the new project are copied exactly?**
Billable rates, estimates, tasks and team.

**Are they copied even if the user has already selected some of them?**
I believe this shouldn't be an issue since user can't select any of these on mobile.

**What happens to any fields when 'no template' is selected?**
We should clear those fields and set default values: non-billabe, no estimates, no tasks or team.

**Comment by amulware** [comment]
So, we actually have to suppose tasks and teams? Tasks we can _maybe_ do (but it's not insignificant effort), but teams or anything like that is just not feasible.

Unless all of that is handled by backend when we push a project with a template?
In which case we still have the issue that the user won't get the tasks until the next full sync.

**Comment by pe0ny** [comment]
I'm thinking if we shouldn't support templates at first at all. Because it might be really confusing for users who know what templates are about and try to use it but it doesn't affect team on mobile.

What do you mean about full sync? So basically, tasks won't appear in the projects list before user restarts the app?

**Comment by amulware** [comment]
Well, I don't know about the tasks. The question is whether we have to create the tasks within the app, or if backend does so when we push the project.

If the former, that's complicated for us, but then mostly fine.

If the latter, we have to push first (might be offline!) to get the tasks created, and then do a pull-sync (currently only on app-start or when user initiates a manual sync) to get the create tasks back.

I'm also not sure how this interacts with done/archived tasks and other visibility things. Can non-admins use templates? Are there no issues with visibility? I don't know.

So yes, it might be better to skip templates for now, and only add them when we have a full understanding of all these details and are sure we can implement it all properly.

**Comment by pe0ny** [comment]
Let's skip templates for now and take a look again after public launch.

**Comment by pe0ny** [comment]
I'll close this because we have no plans atm adding templates on mobile.
