### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#803]
- [x] User can access color picker popup when creating new project (from 'New project' view)
- [x] 'x' takes user back to 'New project' view without saving anything
- [x] 'Save' takes user back to 'New project' view with saving selected color
- [x] User checkbox to indicate selected color
- [x] Show default colors to all users and picker only to starter, premium and enterprise workspaces
- [x] When user uses picker then fill empty circle with this color and add checkbox

![toggl - ios - color picker 1x](https://user-images.githubusercontent.com/5064445/32046847-db8ef64a-ba4c-11e7-9829-65306dbd384f.png) ![toggl - ios - color picker pro 1x](https://user-images.githubusercontent.com/5064445/32046851-dfb0b632-ba4c-11e7-9bdd-eb469bfe3e5b.png)

**Comment by amulware** [comment]
Some questions:
1. Can we get the official list of preset/free colours here?
2. Can we get a mathematical representation of the colour space the user can pick from below? (It looks like it's HSV or HSL but with some limits?)
3. Is the last (custom colour) circle hidden if the user selects one of the preset colours?
4. Can the user only tap, or drag around the spectrum?
5. Does the spectrum change brightness if the slider below is changed? If not, should it maybe be drawn at higher brightness? To me it seems like it's very subdued compared to the bright colours above.

**Comment by pe0ny** [comment]
1. List of pre-defined/free colors:
- #06AAF5
- #C56BFF
- #EA468D
- #FB8B14
- #C7741C
- #F1C33F
- #E20505
- #4BC800
- #04BB9B
- #E19A86
- #3750B5
- #A01AA5
- #205500
- #000000
2. I would use HSV and let user to play with hue and brightness. Or we can also add one more slider and let user to change saturation as well? :)
3. Last (custom color) circle is hidden only for free users. For paid ws it looks empty when user has selected one from pre-defined colors:
![toggl - ios - color picker pro 1x](https://user-images.githubusercontent.com/5064445/32538757-d5f254de-c46f-11e7-8257-764a0ab69172.png)
4. User can tap and drag around the spectrum.
5. Yes, the spectrum changes brightness if the slider below is changed. By default it should be on the max brightness.

**Comment by amulware** [comment]
1. Thanks
2. But.. The spectrum image is 2D - X is hue, and Y is already saturation, no?
4. Nice
5. Cool

**Comment by pe0ny** [comment]
2. Yes, of course it is. 🙈  I'm gonna make some tea..

**Comment by amulware** [comment]
2. So the question is: what range of saturation is supported? 0 to 1?

**Comment by amulware** [comment]
Same question for value.

**Comment by pe0ny** [comment]
Yes, both from 0 to 100%
