### ISSUE TITLE
Remove DateTimeOffset.Now and DateTimeOffset.UtcNow from tests unless really needed

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#805]
There are quite a few tests which rely on the current time. Some of them even combine `UtcNow` and `Now`, which might cause problems for developers in different time zones.

Property tests or some fixed date times should be used in tests to prevent unexpected behavior - tests should be predictable.

**Comment by amulware** [comment]
No argument here. But I think there may be valid cases to use `UtcNow` in integration tests.

**Comment by simonrozsival** [comment]
Sure, I know about some tests which really need it because of the API server, others can be refactored.
