### ISSUE TITLE
Projects view: empty state

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#811]
- [ ] Show this when user doesn't have any project
- [ ] Show placeholder: 'Add a project'
- [ ] When user starts typing, show '+ Create project "new-project-name"', and keep the empty state illustration + copy

![toggl - ios - projects empty state 1x](https://user-images.githubusercontent.com/5064445/32052492-0fd49b44-ba61-11e7-8c0d-b7f83b41076e.png)

**Comment by kornelijepetak** [comment]
@pe0ny  Is this only for edit TE view or also for new TE view?

**Comment by pe0ny** [comment]
@kornelijepetak This is for Projects view which user can access via edit view. We will have something fairly similar for TE creation view as well in the future.
