### ISSUE TITLE
Reports UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#812]
In the **first section** show:
- [x] Total duration for selected time period and static illustration below
- [x] Billable percentage and dynamic chart below

In the **second section** show:
- [x] Top projects pie chart
- [x] Top projects list with project (client) name, percentage and duration
- [x] Sort projects by duration (desc.)

Zeplin: https://zpl.io/bLLONJM

![toggl - ios - reports 1x](https://user-images.githubusercontent.com/5064445/32053359-c917471c-ba63-11e7-8287-8d2a5afafc8c.png)

**Comment by amulware** [comment]
This needs some more information, specifically exactly how the data shown in this report gets compiled.

- What workspace(s) are included?
- Data of the single user only?
- What does 'top projects' mean exactly? I.e. how many are shown based on what criteria?
- Is 'other' shown in the list below?
- In the design the pie chart and projects below don't match up, I'm assuming they should match in the app?
- What is that green graph under the total time? What exactly does it show and where does that data come from?

**Comment by pe0ny** [comment]
1) **What workspace(s) are included?** By default we're going to show data from default workspace. But keep in mind we want to add WS select in reports page as well if user has more than one workspace. For example, you can check these designs (last two screens): https://redpen.io/nb73cb82483e8dfce5
2) **Data of the single user only?** At first yes. Next step would be to add 'Me' and 'Team' tabs so user can see his own data and he can switch to team's data.
3) **What does 'top projects' mean exactly? I.e. how many are shown based on what criteria?** We show all the projects that duration exceed 10% of the total duration. All the projects that duration doesn't exceed 10% of the total duration will be generated under 'Other' category which may contain one or more projects (reason behind is to group smaller project so they don't clutter the pie chart and the list below).
4) **Is 'other' shown in the list below?** ☝️ 
5) **In the design the pie chart and projects below don't match up, I'm assuming they should match in the app?** Yes, these should match.
6) **What is that green graph under the total time? What exactly does it show and where does that data come from?** It's just an illustration and comes from zeplin ;)

**Comment by amulware** [comment]
@pe0ny Loading the report may take up to a few seconds I imagine (no tests so far, if you like, whoever does #970 can investigate this with some real data). Do we want some sort of loading state while the user is waiting for data to download?

**Comment by pe0ny** [comment]
Yes. Good point. We definitely need some loading state. I'll add this to design to-do list.
