### ISSUE TITLE
Reports UI: Calendar

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#813]
- [ ] Tap on the header 'This week' to show/hide the calendar
- [ ] By default show 'This week'
- [ ] Use left-right swipe to switch months
- [ ] To pick a date range: first tap - start date, second tap - end date
- [ ] User can scroll shortcuts left-right
- [ ] Close the calendar once date range has been selected (after second tap or selecting a range from shortcuts)

Shortcuts:
- This week
- Last week
- This month
- Last month
- This year

Zeplin: https://zpl.io/VYPXp0n & https://zpl.io/2ZqXD3X

![toggl - ios - reports calendar v1 1x](https://user-images.githubusercontent.com/5064445/32053593-7af4fde4-ba64-11e7-9958-81a6d8bf5917.png) ![toggl - ios - reports calendar v2 1x](https://user-images.githubusercontent.com/5064445/32053596-7dbbe934-ba64-11e7-93d0-ca0627e3b73c.png)

**Comment by amulware** [comment]
In the design, it looks like the calendar makes the header expand, instead of being on top of it. Does it scroll with the rest of the page then? Or does it stick to the top when scrolling?

**Comment by amulware** [comment]
@pe0ny The above questions.

Also, the report can show at most the data for one year. How do we limit the user to that? And in general, do we have some limit about how far back they can go? How far into the future?

**Comment by pe0ny** [comment]
- Calendar expands the header; Content reveals the calendar.
- When user start scrolling down (swipes up), then content covers the calendar and in the end closes it.
- We should limit it by not allowing user to move back in calendar more than one year.
- Current month should be the max value.

**Comment by amulware** [comment]
Also: How do 'this week', 'this month' and 'this year' work when in the middle of a week/month/year? Is it showing the last 7 days, or everything since monday (and similar for month, year)?

**Comment by pe0ny** [comment]
- Even when in the middle of a week/month/year, it shows full week/month/year

**Comment by amulware** [comment]
I'm not sure I understand. :D - so what range does it show on a Wednesday? Wed - Wed? If so, I also need an explanation of what 'last week' means.

And one other point, just to clarify: We CAN get data longer than one year ago, just not for more than one year at a time (i.e. start and end date can be no more than one year apart) - do you still want to limit it to the last year?

**Comment by pe0ny** [comment]
On Wednesday it will show range from Monday to Sunday OR when user has set in settings that weeks starts with Sunday, then from Sunday to Saturday.

**Comment by pe0ny** [comment]
@arturs105 

> Is the button, which represents currently selected period, darker? Or is last tapped button darker?

Yes, when you tap one of those buttons, it will become active/darker.


> If I select this month, using two taps on the calendar, will the "This month" button will become darker (active/selected)?

Yes, then this month becomes active/darker.
