### ISSUE TITLE
Reports UI: empty state for new users

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#814]
- Show this state to new users who haven't created any time entries yet.

Zeplin: https://zpl.io/2p0M9rQ

![toggl - ios - reports empty state 1x](https://user-images.githubusercontent.com/5064445/33313492-7890160e-d433-11e7-998d-5e280de79156.png)

**Comment by amulware** [comment]
@pe0ny How do we know that a user hasn't created any time entries? In the app we only have a history of the last few weeks. For all we know there could be data months ago, right?

**Comment by pe0ny** [comment]
Can't we pull data and check? I believe Reports API shouldn't have two weeks limit?

**Comment by kornelijepetak** [comment]
@amulware Did you check this with backend or something? How are we going to approach this? It's not that I need this for implementing the UI (I will just bind to VM props), but still it's rather important to know.

**Comment by amulware** [comment]
Sorry, my bad for now following up on this. @pe0ny How do you mean 'pull data'? Just the selected interval? That we can certainly do, yes.

But no, I'm not aware of any easy way to determine if the user has ANY time entries at all. I'm not sure if we're talking about the same thing?

**Comment by pe0ny** [comment]
If we can't check if user has ANY time entries at all, then we'll just drop this and use only #1027

**Comment by kornelijepetak** [comment]
Now that I'm almost done with it. But I agree, this may not be necessary, because it is somehow implicit in #1027 

@pe0ny Is it your final call? If yes, please close the issue. Until then, I'm off to another issue. :)
