### ISSUE TITLE
Tag creation

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#820]
- [ ] User can create new tag in time entry creation flow
- [x] User can create new tag in tags view (when editing time entry)

- Show '+ Create tag "new-tag-name"' at the top of the list when user has typed in tag name that doesn't exist yet.
- Assign new tag under the workspace that the time entry is under
- When user taps '+ Create tag "new-tag-name"', save and select this tag; clean the input field and show list of existing tags, selected tags at the top of the list; keep the tag view open; this applies both to TE creation flow and tags view;

![toggl - ios - tags 1x](https://user-images.githubusercontent.com/5064445/32094158-80215fe4-bb07-11e7-9404-f11a6a17abd0.png) ![toggl - ios - tags new tag 1x](https://user-images.githubusercontent.com/5064445/32094270-d641286e-bb07-11e7-80e4-07cc2553a1ef.png)

**Comment by amulware** [comment]
What happens if a user creates a new tag and then aborts the time entry creation/edit process? Is the tag still created? Why/why not?

**Comment by amulware** [comment]
Requires #907

**Comment by pe0ny** [comment]
I would say the tag should still be created. It makes sense to me when I hit 'Save' in tags view.

**Comment by amulware** [comment]
Alright. That should also be easier to implement. I'll assume we'll do the same for clients and projects.
