### ISSUE TITLE
Add sign up API

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#824]
Using v9 endpoints that will be a thing soon™️.

**Comment by arturs105** [comment]
Are the endpoints ready now?

**Comment by amulware** [comment]
Endpoints are available in staging and will be available in production soon(tm).

Let's at least make sure we get the API and integration tests up and running.

**Comment by simonrozsival** [comment]
Cool. I will test the endpoint today.

**Comment by simonrozsival** [comment]
@pe0ny I need specification for these two required fields in the signup process:

1. What should be the _name of the workspace_ created for the new user?
2. Should the _initial pricing plan_ be _Free_ by default?

**Comment by pe0ny** [comment]
2. yes
