### ISSUE TITLE
Signup UI

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#825]
Most of it is already there I think, but it needs to be finished and hooked up.

**Comment by willsb** [comment]
Where can I get the links for the ToS and Privacy Policy?

**Comment by pe0ny** [comment]
ToS: https://toggl.com/legal/terms
PP: https://toggl.com/legal/privacy

**Comment by willsb** [comment]
This is on hold until #824 is closed

**Comment by simonrozsival** [comment]
PR #873 is waiting for reviews.
