### ISSUE TITLE
Figure out authentication for api

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#84]
Currently, we pass username and password strings for all api calls. This is ugly, leaky, and we should use api tokens as much as possible anyways.

Here are some options I can come up with. Thoughts on these, and other ideas are welcome.

- Use an authentication object that wraps username/password or apitoken and somehow knows how to create the right http headers
  - nice abstraction, but still needs to be passed everywhere
- Have the TogglClient object have state, including the auth info 
  - does not feel as nice, but means we have to pass much less data
  - the question here is whether to re-create new TogglClients, or have it be mutable then
- Wrap the TogglClient into a thing that accesses it with auth info
  - I like the idea of this, but it means we have to create wrappers for all the individual clients I think?

**Comment by willsb** [comment]
Question: Everything in the API needs auth, correct?

I think we should have the token stored somewhere and make it so that every client knows how to access this storage to retrieve the token (via a delegate or some auth object that gets passed to the `BaseClient` via construction). If the token is not there, we simply fail the api call. This is simple and will work wonders with no user mode. 

This storage can either be the database (the token can be a property of the `User` object) or use each platforms' encrypted key/value store.

**Comment by kasthack** [comment]
How about calls and api clients which don't know anything about authentication / delegating dealing with authentication to `ApiClient`?

* Add some kind of credentials parameter to `TogglClient` (like `NetworkCredentials` but more specific)
* `TogglClient` just passes it to `ApiClient`.
* `*Client`s now just produce calls which don't know anything about authentication. Maybe we should add `bool IsAuthenticated {get;}` to `ICall` to throw without actually executing calls if they require auth and the user is not authenticated yet.
* `ApiClient` executes calls with current credentials.
* `ApiClient`/`TogglClient`'s authentication data should be immutable to prevent cases when we execute calls for user other than we intended.

Pros:
* `*Client`s don't know anything about authentication anymore
* Less repeating code(`GetAuthHeader` on almost every call)
Cons:
* I feel like I'm missing something important here but I'm not sure what exactly.

**Comment by kasthack** [comment]
Technically we already can do this without even modifying code: `TogglClient` accepts `HttpClientHandler`  which it passes to `ApiClient`. `HttpClientHandler` has `Credentials` property which does exactly what we need but it breaks all the abstraction levels in our case and feels like a dirty hack.

**Comment by amulware** [comment]
Answer: Let's assume that everything in the API will need auth, yes. And of course the token is stored. It's already part of the user object. In fact, we need to make sure we handle the case where the token is out of date, and require the user to log in again - without clearing their unsynced data in the meantime.

**Comment by amulware** [comment]
It really comes down to: Do we want to pass an auth thing for each call, or do we want to create new toggl-clients on login/out.

I currently lean towards the latter. This only requires code in a few places, and in return we can simplify all api calls.

**Comment by amulware** [comment]
We decided to pass the auth info to the toggl client on creation, no exceptions. None of the api call methods will require auth info.
