### ISSUE TITLE
Settings: switch default ws

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#860]
- [ ] Display default WS name in settings
- [ ] When user taps on a default ws, open ws view
- [ ] User can switch default WS (save automatically)

![toggl - ios - settings 1x](https://user-images.githubusercontent.com/5064445/32274825-65e4ff74-bf11-11e7-87d0-961bf7f75771.png) ![toggl - ios - settings workspace 1x](https://user-images.githubusercontent.com/5064445/33126728-3b3d7750-cf8e-11e7-9750-e54527f17a49.png)

**Comment by amulware** [comment]
@pe0ny is this change local or synced online so it applies to other clients?

**Comment by pe0ny** [comment]
It's not only local, it should be synced and applies to other clients as well.

**Comment by amulware** [comment]
When implementing this make sure that the change to the user object is synced correctly (initiate push sync after the user chooses the new workspace).

@simonrozsival Can you confirm that the `at` date on the user object works just as well as it does for other entities (to make sure we handle the case where the user changes the WE multiple times in a row correctly).

**Comment by willsb** [comment]
Why are we not reusing the same view we use when creating a project? It even has filtering, so it's even nicer than this one. 

IMO the card will make everything even nicer, but that view can be made into a normal screen if needed be

**Comment by simonrozsival** [comment]
I tried it and `at` behaves the same way as it does for the other entities.
