### ISSUE TITLE
Sometimes the app does not seem to download time entries

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#888]
Even after multiple force-syncs, the log stays empty and there are no suggestions.

My only idea is that we might hit backend's rate limit but that would not explain that this seems to only happen to some people with significant frequency, while others are not experiencing it (much?). If this happens to be the case, we might need to implement a retry loop for fetching data.

It would be great to be able to reproduce this and at least know what is going wrong so we can see about fixing it in the future - or if the fix is simple, fixing it now.

**Comment by amulware** [comment]
I'm looking at an offending account right now (this error seems account specific, though I suspect it depends on how the time entries are laid on or distributed over the day or what data they have).

- data is definitely coming in on the fetch
- it does not reach RealmAdapter:102 when syncing time entries
- I found a specific time entry that causes the .Select call before to fail
- I suspect that something goes wrong when cloning the entry and resolving the realm references

This needs more investigate though. For specific data poke internally.

**Comment by simonrozsival** [comment]
Ref #903
