### ISSUE TITLE
Remove padding between the border line and suggestions

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#889]
- There shouldn't be no padding between grey line and suggestions
- Suggestions itself should have top border (which is now at the top)

![test](https://user-images.githubusercontent.com/5064445/32345196-222ef9b8-c012-11e7-8398-0735f9810d24.png)

**Comment by kornelijepetak** [comment]
Actually, this border is artificially added after removing the timeline. It's not a border belonging to suggestions. I'll fix this asap.
