### ISSUE TITLE
Selecting text not working properly

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#890]
Both the start view text field and the edit view description text field (maybe others as well?) behave strangely with selections. Sometimes they just deselect or don't allow me to select the letters I want, instead selecting whole words or the entire text. It seems very finicky and I'm not sure what the pattern is, but it doesn't seem right.

**Comment by arturs105** [comment]
Selection in edit view's description field works properly (just tested on iPhone and simulator).

**Comment by willsb** [comment]
Will be fixed once we tame the beast 🐉  

#666
