### ISSUE TITLE
TE list: projects/tasks are not displayed

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#892]
Projects/tasks are not displayed for TE that are created while being offline.
After restarting the app, these will be showed.

**Comment by simonrozsival** [comment]
Could you add some more specific information? Where exactly are they missing? How to reproduce this?

**Comment by pe0ny** [comment]
1) Start a new time entry without having internet connection; hit the green checkbox; timer is running; all good
2) Stop a time entry; TE appears in the list but only description visible (though I added a project as well)

When I open the edit view I can see that the project is added.
I restart the app, and now it displays project name next to the TE as well in the log list.
This doesn't happen when creating new TE while having internet connection.

**Comment by simonrozsival** [comment]
Is this the latest build? I can see things properly in current `develop`: http://prntscr.com/h5njfc

**Comment by pe0ny** [comment]
It's the latest Test Flight build from yesterday 0.1(6)

**Comment by simonrozsival** [comment]
I can't reproduce this in the simulator. Does this happen every single time, or does it happen only from time to time?

**Comment by pe0ny** [comment]
I can't reproduce anymore either. If no one else can I believe we can close this issue.

**Comment by amulware** [comment]
We can always reopen it.
