### ISSUE TITLE
Test GroupedCollectionTableViewSource

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#902]
I've been told this class has no tests.

**Comment by willsb** [comment]
We should take a look at this guy again: https://github.com/xunit/devices.xunit

It was kinda buggy when we first checked it, but it probs works nicely now. Unit Testing Daneel (and in the future, Giskard) components would be a very nice plus.

Also, if one can set up devices.xunit, we can start testing Realm on actual devices too, which is a very nice added bonus

**Comment by amulware** [comment]
We'll need to run some coverage tools and start a 'fill the gaps' initiative.
