### ISSUE TITLE
NSInvalidArgumentException: UILabelLayer valueForKey: nil key

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#905]
I don't have a full stack trace of this right now, but maybe the below is already enough.

From the firebase event log, it _seems_ like this might happen in the login screen, but I wouldn't put too much value in that until we better understand how the log works. 

```
NSInvalidArgumentException: *** -[_UILabelLayer valueForKey:]: attempt to retrieve a value for a nil key
__exceptionPreprocess + 1232864
objc_exception_throw + 34100
+[NSException raise:format:] + 1232676
-[NSObject(NSKeyValueCoding) valueForKey:] + 50844
CAObject_valueForKey + 1581648
-[_UIViewAdditiveAnimationAction runActionForKey:object:arguments:] + 3068872
CA::Layer::display_() + 1140544
-[UIView _dispatchTintColorVisitorWithReasons:] + 3115160
-[UIView setTintColor:] + 546724
-[UIButton setTintColor:] + 553108
-[UINavigationButton _updateStyle] + 838780
-[UINavigationButton _UIAppearance_setTintColor:] + 854988
```

**Comment by willsb** [comment]
Login is the only place where we tint `UINavigationButton`s, so it's either there or in the proximities 😄

**Comment by willsb** [comment]
Investigate this for a while now. Doesn't seem to be happening in 0.2 anyways. Closing as invalid
