### ISSUE TITLE
Implement tag sync

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#907]
To support tag creation, we need to mark them as needing-sync just like time entries.

During push sync we then need to check if there are any tags to be synced, and if so, sync them. Tag sync has a higher priority than TE sync, given the dependency.

In case tag creation fails, they have to be marked as unable to sync and the returned reason has to be saved, just like with TEs.

**Comment by simonrozsival** [comment]
I wonder what would happen when POSTing of a tag fails and then we will try to push time entry which uses the tag. The TE won't succeed, we will mark it as unsyncable, and then it will be up to the UI to mark the problematic tags somewhere... Is that OK? In other words: I shouldn't handle dependencies between the types of entities other than the order in which they are processed, correct?

**Comment by simonrozsival** [comment]
What operations do we support? Only creating? No updating or deleting (we are missing endpoints right now)?

**Comment by amulware** [comment]
Only creation is necessary. Same goes for projects and clients.

I still have to think about what to do when any of these entities fail to sync.
