### ISSUE TITLE
Ask confirmation when deleting TE

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#911]
Ask confirmation 'Delete' or 'Cancel' when user taps 'Delete' in edit view.

**Comment by amulware** [comment]
What is the dialog copy for this?

**Comment by pe0ny** [comment]
Probably should have mention it's action sheet not alert.
Can't we have just two buttons here? https://zpl.io/a8lq6lX Because I think it's pretty clear when user first taps to 'Delete' what's this about.
