### ISSUE TITLE
Don't show 'label' in syncing bar when user is offline

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#912]
Atm when i open the app with out having internet connection, i'll get this:

![img_4522](https://user-images.githubusercontent.com/5064445/32440814-7bb2ca62-c2fd-11e7-942c-bbf9551b9e4b.PNG)

Instead, show this:

![toggl - ios - timer offline v1 1x](https://user-images.githubusercontent.com/5064445/32440841-9d5bda46-c2fd-11e7-8187-4795ecf6438f.png)

**Comment by amulware** [comment]
We currently do not know if the user is offline or not. But even now, it shouldn't show "Label" but always one of the other strings.

In this issue, let's just fix that it shows "Label", and we'll get it to show "Offline" once the syncing can tell apart different types of errors.

**Comment by pe0ny** [comment]
But what should we show instead of 'Label', 'syncing' and the spinner?

**Comment by amulware** [comment]
Yes. That is the only thing we can do right now.

**Comment by simonrozsival** [comment]
Ref #661

**Comment by kornelijepetak** [comment]
I am unable to reproduce this erroneous behaviour.
@pe0ny Do you have any reproducible steps? Cause for me it either shows what it should (when sync works correctly) or it shows grey bar with `'Syncing... ( )'` and gets stuck on that if no internet connection is available.

**Comment by pe0ny** [comment]
@kornelijepetak 

One way to reproduce this:
a) Connect with wifi, log in
b) Close the app completely and turn off wifi/data
c) Open the app and you can see this:

![img-4581](https://user-images.githubusercontent.com/5064445/32937217-2bf72b68-cb80-11e7-93da-21f1661ca686.PNG)

**Comment by pe0ny** [comment]
This also happens after sign up when there's no data

**Comment by kornelijepetak** [comment]
I have repeated your steps, but to no avail.
I need someone else to try on their computers.

I haven't tried on a physical device. Maybe there is a difference.

**Comment by pe0ny** [comment]
Also happened when installed latest TF 0.2 (8) build from scratch (production)

**Comment by amulware** [comment]
While this is suboptimal, we're almost at the point where we can rework the entire UI here based on better events from syncing. Let's do that, instead of putting more time into this.
