### ISSUE TITLE
Support pushing of user object

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#931]
This is needed for #860

I'm not sure if this is as easy as it sounds or if we want to be more careful to not accidentally change/mess up any settings. Please take care to investigate that and maybe post any relevant considerations below.

**Comment by simonrozsival** [comment]
The API part is easy (:point-up:), but I'm not sure how to handle this in the push sync - but it shouldn't be in fact different from the other types of entities. It will be an "update-only" push pipeline. I will place it at the very end of the push pipeline, after time entries, although that it could be probably anywhere after Workspaces (which aren't even implemented atm).

**Comment by amulware** [comment]
I think syncing settings is quite important, and I rather push it as early as possible. Is there any reason not to push it right after workspaces? I'd even say before, but that might be problematic with the default workspace setting.

**Comment by simonrozsival** [comment]
Create a workspace => set it as default for the user => if you would now first push the user and only after that push the workspace, we would get a 💥

**Comment by amulware** [comment]
Yes, so we need to push the workspace first, but that's the only dependency, right? If so, let's push user settings right after. I rather have those synced and miss a time entry than the other way around.

**Comment by simonrozsival** [comment]
OK.
