### ISSUE TITLE
Create new project from suggestions needs revision

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#939]
This is a follow-up of issue #797, which was already partially implemented in PR #937 .

1. When the query after the `@` symbol is empty, we should display something else than `+ Create project ""`. I didn't find anything related to this edge case in the previous issue, but I think it is really strange to see this message. In this case I would expect to see something like `+ Create project` without the quotes.

2. Also I think that PR #937 did not do exactly what was in the specification:

    > Show '+ Create project "new-project-name"' at the top of the list when user has typed in project name that doesn't exist yet.

    I interpret that in a such way that you should show the `+` button even if there are some suggestions, but none of them __exactly__ matchest the query (i.e., `ItemsSource.All(x => x.Name != CurrentQuery)`). It makes sense, because you might have a project with a name which would be substring of a different project.

I would like to ask @pe0ny or @amulware for confirmation or for any further comments to my suggestions.

**Comment by amulware** [comment]
I fully agree with these points.

**Comment by amulware** [comment]
Though there is one important point: What about capitalisation? Do we consider two project names to be the same if the capitalisation is different? Certainly while searching we don't expect users to capitalise their search term. @pe0ny?

**Comment by pe0ny** [comment]
I agree with these points as well.

Yes, we shouldn't expect users to capitalise their search terms, would be super annoying.

When creating new project - If the capitalisation is different, then project names are different. So basically you can have two different projects: 'Toggl app' and 'toggl app'

**Comment by amulware** [comment]
So, if the user has a project 'Toggl', and they enter 'toggl' we, of course, show the existing project, but we also show "+ Create project 'toggl' " - right?

**Comment by pe0ny** [comment]
Yes.
