### ISSUE TITLE
Project suggestion substitution behaves incorrectly when there are multiple '@' symbols in the description

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#946]
How to reproduce:

- Create a project called "Meetings"
- Start a new time entry
- Type into the description: "Meeting with some@one.com @Meetings"
- From the suggestions, select the project "Meetings"
- The description text will be changed to "Meeting with some [Meetings]"

Expected behavior:
- The description text will be changed to "Meeting with some@one.com [Meetings]"

**Comment by amulware** [comment]
Ref #315
