### ISSUE TITLE
API token has been reset UI

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#947]
- [x] When user has reset the API token:
a) ask user to log back in by entering his/her password
b) sign out (possible data loss)
Don't allow user to go back and access any data.
 
![toggl - ios - api token reset 1x](https://user-images.githubusercontent.com/5064445/33199984-5e037640-d0fb-11e7-8592-96a618940944.png)

- [x] When user decides to sign out and has some unsynced data, show similar warning we show on 'regular' sign out while having unsynced data.

![toggl - ios - api token reset confirmation 1x](https://user-images.githubusercontent.com/5064445/33199977-5905a9c4-d0fb-11e7-87ab-fe76d8438a97.png)

**Comment by amulware** [comment]
@pe0ny What should happen if the user logs out, has no unsynced time entries, but has unsynced projects?
Do we only check time entries? Or do we check all things? Should the copy then be changed?

It's a bit of an edge case, but let's make sure we make a conscious decision.

**Comment by amulware** [comment]
Also, in accordance with #751 make sure that this is the first thing people see if restarting the app after the bad token was detected. This is important so that our users can lock other people out from seeing their data if they lose their device - at least superficially.

**Comment by simonrozsival** [comment]
Just FYI settings view currently only checks for unsynced TEs.

**Comment by amulware** [comment]
Good point, we _probably_ want the same logic for both. (?)

**Comment by pe0ny** [comment]
@amulware Yes, we want the same logic for both (settings and when API token has been reset). I would say we should check all the data (time entries, projects, clients, tags etc).

And let's change copy to:
Are you sure?
You have some unsynced data. Any unsynced data will be lost

**Comment by willsb** [comment]
This is not on Zeplin. It'd be good to have these there

**Comment by pe0ny** [comment]
Updated Zeplin files:
API token reset UI: https://zpl.io/aRmXYgp
And confirmation: https://zpl.io/bWQXYrx

**Comment by willsb** [comment]
How should we display error when the users types in the wrong password?

**Comment by pe0ny** [comment]
We'll display the same error message that we display in 'normal' log in view and remove the API part: https://zpl.io/25Nxpg8

**Comment by willsb** [comment]
Okay, but where? Below the help text? Above it? Should we replace the help text with the error message?

**Comment by pe0ny** [comment]
Like I said before: we'll remove the API text "Your API token has been reset. Enter your password....." and show the error message "Incorrect email/password. Please try again." at the same place. Like in the link I posted above. Not below or above, the API/help text will be replaced with the error message.
