### ISSUE TITLE
'+ Create project/client x' misses top and bottom borders

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#954]
Project creation: https://zpl.io/29qgYrY
Client creation: https://zpl.io/aB1ALxK

![img_4573](https://user-images.githubusercontent.com/5064445/32777983-f9285f2c-c940-11e7-899e-aff8fb86ee89.png)

**Comment by kornelijepetak** [comment]
I am not sure what happened, but obviously part of this issue has been solved by doing other stuff. 

The client screen shows this:
![image](https://user-images.githubusercontent.com/7033216/33388072-31831976-d52f-11e7-8aa1-7ab497067252.png)

The project creation lacks only one border:
![image](https://user-images.githubusercontent.com/7033216/33388121-58f39c74-d52f-11e7-92b5-687c99cee51f.png)
