### ISSUE TITLE
Trim TE description before saving changes

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#960]
Currently we allow the user to insert several white spaces and take it as a valid description. Webapp trims the description, we should as well.

- [x] Start time entry view
- [x] Edit time entry view
- [x] Project name
- [x] Client name
- [x] Tag name

**Comment by amulware** [comment]
The same should happen for projects, clients and tags if it doesn't already. (And in those cases a whitespace-only entity should not be allowed to be created at all.)

**Comment by simonrozsival** [comment]
> also important to check for existing names after trimming, not before

**Comment by simonrozsival** [comment]
All the PRs for all the entity types were merged, I will close this now manually.
