### ISSUE TITLE
Find a way how to unit test RealmAdapter

### ISSUE THREAD

**Issue by simonrozsival** [toggl/mobileapp#966]
We do not have a single test for the `RealmAdapter` class, even though it contains very complex logic which is essential to correct behavior of the app.

The problem is the lack of an interface of the `Realm` object, so we can't mock it with NSubstitute.

**Comment by willsb** [comment]
Can this be checked again now that we are on netstandard? It might be that netcore apps running on mac (which is the case of `Toggl.PrimeRadiant.Tests`) can run Realm just fine. If it isn't the case, a runner for mac should be trivial to add (as in, a console netcore app).

**Comment by amulware** [comment]
This will be part of future testing initiatives.
