### ISSUE TITLE
Adapt the app for iPhone X

### ISSUE THREAD

**Issue by arturs105** [toggl/mobileapp#968]
- Notice, how, when scrolling, some stuff appears behind the status bar.
- The separators between sections (days in the log) look like sticky footers at the bottom, though this can't be seen in the gif, so see for yourself in the simulator.
- Probably some other stuff as well.

![nov-15-2017 13-58-42](https://user-images.githubusercontent.com/15633003/32835325-54425c32-ca0e-11e7-9d9f-2291a39735d3.gif)

**Comment by pe0ny** [comment]
- I see that some elements appear behind the navigation bar as well, which shouldn't happen as well.
