### ISSUE TITLE
Create first reports api endpoint and api client

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#970]
Relevant information:

`POST reports/v3/workspaces/{workspace_id}/projects/summary`

```
// Input:
// {
// 	-- required --
// 	"start_date": "2006-01-02",
//
// 	-- optional(can be null) --
// 	"end_date": "2006-01-02", // Default is 7 days from start_date
// }
//
// Output:
// [array of {
// 	"user_id": int,
// 	"project_id": int || null,
// 	"tracked_seconds": int,
// 	"billed_seconds": int, // Only for non-free workspaces
// }]
//
// Output headers:
// 	X-Range-Start = Actual start date used for query
// 	X-Range-End = Actual end date used for query
```

- The interval can be at most one year, we should enforce this on our side.
- Internally, the start and end date should be strongly typed.
- All integers in the output are 64bit.
- We can probably ignore the output headers for now (or ever).

The endpoint is live and should be working fine. Let's do some testing so we understand exactly how it works, and how it errors under different conditions and encapsulate that in integration tests.

**Comment by simonrozsival** [comment]
Will we create a new project for Reports API or do you want to put everything network-related into Ultrawave? I would probably prefer having a separate project, because there would be completely different endpoints and models. But maybe it is an overkill.

**Comment by amulware** [comment]
Let's keep it in the same project for now. We can keep an eye on how it develops, and if the split indeed makes sense, we'll do it down the road.

**Comment by simonrozsival** [comment]
So I tested this and the URL of the endpoint is different, it is `/reports/api/v3/workspace/{workspace_id}/projects/summary`. I'm not really sure if this is a bug or a feature (@shedokan?), as it doesn't match the specification in the backend issue, but it was reviewed, approved and deployed.

**Comment by amulware** [comment]
Please confirm the URL internally if there is confusion. Also please test what happens when projects are archived. We will probably have to fetch them manually in that case.

**Comment by simonrozsival** [comment]
Archived projects are included as well.
