### ISSUE TITLE
Ditch StateObservable in favor of ProgressObservable 

### ISSUE THREAD

**Issue by willsb** [toggl/mobileapp#981]
#978 introduces a nicer public API for interacting with the syncing algorithm. This makes the previous method (the one exposing `SyncState`) obsolete. 

We should remove the `StateObservable` from the `ISyncManager` interface and make consumers use the new observable instead, making sure to turn public members into internal while at it.

- [ ] The main view/suggestions view
- [ ] Settings view

**Comment by amulware** [comment]
This is a bit more complicated than just switching the observable, since the events contain a lot more information.

We have to handle at least the following cases separetely:

- Syncing
- Synced
- Offline
- 410/418
- 401

**Comment by simonrozsival** [comment]
The `IObservable<SyncProgress> SyncManager.ProgressObservable` works this way:
- it emits five types of progress:
    - `Unknown` (before the first real value is emitted, which should be just right after the app start) - this value can be ignored
    - `Syncing` - syncing started or continues (this value can be emitted multiple times during sync)
    - `Synced` - syncing finished without any error
    - `OfflineModeDetected` - the user is offline and sync cannot continue - in this case no `Synced` or `Failed` will be emitted
    - `Failed` - in case _any_ exception was thrown during syncing (including 401, 410, 418)

In case one of the 401, 410, 418 exceptions was caught, not only will the `Failed` value be emitted, but the syncing process will throw an error with the exception (`Toggl.Ultrawave.Exceptions.ClientDeprecatedException`, `Toggl.Ultrawave.Exceptions.ApiDeprecatedException`, `Toggl.Ultrawave.Exceptions.UmauthorizedException`). This must be caught and user must be navigated to the proper screen (`OutdatedAppViewModel`, `TokenResetViewModel`) and the reason must be saved to `Toggl.PrimeRadiant.IAccessRestrictionStorage`. When the error is thrown, the observable completes and won't emit any further values. The `SyncManager` will also be frozen and won't be able to sync anything, until user resolves the issue (use loggs in again or he/she updates the app).

**Comment by simonrozsival** [comment]
The PR #1010 should be merged first, because it contains the logic how to handle the errors.
