### ISSUE TITLE
Sign up UI: add additional copy below the password field

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#988]
When user signs up and starts entering his/her password, show this text below the input field:
'Password should be at least 6 characters.'

![toggl - ios - sign up step2 1x](https://user-images.githubusercontent.com/5064445/32952807-014cba90-cbb7-11e7-89b8-0a5c19b54876.png)

**Comment by willsb** [comment]
Why though? Is there a restriction in the API?

**Comment by pe0ny** [comment]
As far as i know yes but i'll confirm.

**Comment by refiito** [comment]
> Why though? Is there a restriction in the API?

Yes, https://github.com/toggl/toggl_api/blob/master/src/code.toggl.com/api/me/post_signup_handler.go#L97
