### ISSUE TITLE
Log view: add padding at the bottom

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#990]
Currently when user scrolls at the bottom of the log list, the last time entry is hidden behind the running time entry (or play button). To avoid that happening, padding between the last TE and bottom of the screen should be 64pt.

Zeplin: https://zpl.io/a309jlQ

Current:
![img_4593](https://user-images.githubusercontent.com/5064445/33007800-04757922-cdd9-11e7-9329-19c345efcaa5.png)

Better solution:
![screen shot 2017-11-20 at 09 51 48](https://user-images.githubusercontent.com/5064445/33007753-d74aa9c2-cdd8-11e7-8d8f-8e5f97fea8b9.png)

**Comment by pe0ny** [comment]
@kornelijepetak Is it related that currently there is some padding always visible at the bottom though it shouldn't be?

<img width="407" alt="screen shot 2017-11-30 at 09 04 41" src="https://user-images.githubusercontent.com/5064445/33418220-874c1668-d5ad-11e7-929d-d0e8d496a979.png">

**Comment by kornelijepetak** [comment]
I haven't push anything to `develop` related to this and I think @willsb hasn't either. It might have creeped in with another push. Maybe we can rush @willsb to finish his WIP so we can see if the padding is still there afterwards. What do you think?

**Comment by arturs105** [comment]
That padding at the bottom is actually a sticky footer (the gray area between the sections). That is fixed in the iPhone X PR for all devices.

**Comment by willsb** [comment]
This will be collaterally fixed by the PR to fix #322
