### ISSUE TITLE
Login with password manager is broken

### ISSUE THREAD

**Issue by amulware** [toggl/mobileapp#991]
We've gotten several reports that logging in with a password manager causes the app to enter an unusable state.

**Comment by amulware** [comment]
If it can't be fixed easily, hide the functionality for now.

**Comment by willsb** [comment]
The password manager itself **does work**

What doesn't work is the way the bindings are made, which cause the spinner, for some reason, not to spin and the keyboard not to be dismissed. This gives the impression that nothing is happening, but if you simply wait a bit, login works. To whoever tackles this: Go for the UI components and the target bindings, for there's no need to poke the `OnePasswordService`
