### ISSUE TITLE
Can't select a project

### ISSUE THREAD

**Issue by pe0ny** [toggl/mobileapp#992]
When auto-complete suggest to create a new project and also existing projects, then no matter which existing project i tap, the app opens 'new project' view. Meaning every item triggers the same thing that only '+ Create new project "tes"' should do.
I can only select existing project when i do not type in anything besides @ 

![img_4594](https://user-images.githubusercontent.com/5064445/33008235-f869c33e-cdda-11e7-8b19-ad27e9c2567f.png)

**Comment by simonrozsival** [comment]
This is the same bug as #972.
